### ISSUE TITLE
[request] API Failover Feature

### ISSUE THREAD

**Issue by jeevaengg21** [Mashape/kong#1010]
Assume that i have a micro server e.g getWeather hosted in server A and Server B manged by a Apache Proxy which does the load balancing and failover cases.

Now i have created the API in Kong with host ip of Proxy server, but it tweeks a question Kong itself has a NGINX proxy sever so do i need to again configure the Service Providers with another Proxy server. 

So is there any feature planned or already available to address the API failover case, like if server A is down or unavailable then all the request for getWeather sevice should be forwarded to Server B.

**Comment by thefosk** [comment]
This is related to #157.
