### ISSUE TITLE
[Monitoring] Cache

### ISSUE THREAD

**Issue by codebien** [Mashape/kong#1015]
How to monitor cache performance (miss, response time, ecc..)? Probably related to: #954

**Comment by thibaultcha** [comment]
Could you elaborate? Cache performance of the upstream services (Kong does not provide caching features of those) or the Kong entities?

**Comment by Tieske** [comment]
possibly related: https://gitter.im/Mashape/kong?at=57c8ae0529ee4a67058593e3

**Comment by codebien** [comment]
Kong entities. We would like to monitor how the cache system performs. Some metrics we are interested in are: cache miss, size, throughput or latency. This could help us to understand how to fix some problems, improve the systems or request new specific features.

Thanks

**Comment by thibaultcha** [comment]
The only way I see is to tweak the `database_cache` module and perform any measurement you;d like, and send them anywhere you'd like as well. Closing this.
