### ISSUE TITLE
A ldap(s) authentification plugin

### ISSUE THREAD

**Issue by sergepeter** [Mashape/kong#1022]
It could be great to have a ldap authentification plugin that give back principal with group details, that could then be use to whitelist an api.

best regards

serge

**Comment by shashiranjan84** [comment]
Currently we are working on LDAP Plugin which authenticate user using `Bind Authentication`.  We still defining the scope of the LDAP plugin and Authorization going to be part of it eventually.

**Comment by ambrons** [comment]
@shashiranjan84 How would this integrate with `Consumer`?  Or would it be a replacement?

**Comment by shashiranjan84** [comment]
So far the plugin implementation validate user using the credential(username:password) sent in the request against the LDAP server using Bind Authentication and cache the credential for future use. 

Please give it a try if possible https://github.com/Mashape/kong/tree/plugin/ldap

**Comment by thefosk** [comment]
Closed with #1133.
