### ISSUE TITLE
[Request] kong web based front end

### ISSUE THREAD

**Issue by mitchellfranklin** [Mashape/kong#1033]
Hi All,
Have been a bug fan of Mashape for a long time and looking to implement my own front end for some business services however from what I can tell (please let me know if I am wrong) is that kong does not provide such a service? i.e. API store, signup for users, admin type tasks etc.

I don't mind the curl process but obviously this would not work for day to day users or developers coming to the site.

Thanks again

Mitch

**Comment by Tieske** [comment]
Have you checked the tools listed in the readme?; https://github.com/Mashape/kong#community-resources-and-tools

If the usecase doesn't match yours, let us know when you're up and running and we'll promot yours in the readme!

btw; we're not 'bug fans' actually we try to get rid of them :smiley:

**Comment by sinzone** [comment]
- Devs signup & on-boarding we have [Gelato.io](http://gelato.io) (integrated with Kong)
 - OSS Admin GUI: https://github.com/PGBI/kong-dashboard
 - Analytics GUI: http://getgalileo.io/

**Comment by mitchellfranklin** [comment]
Thanks Tieske & sinzone - I cant believe I missed these from the main page, thanks for taking the time to point them out to me :)
