### ISSUE TITLE
Cassandra DB Install

### ISSUE THREAD

**Issue by mitchellfranklin** [Mashape/kong#1034]
Hi all,

I have looked and looked but seem to be lost or just not seeing it, is there a doco or process that I can be given to show how to use the downloaded Casandra 2.2.x version to setup this up with Kong?

Been using/updating the yml file with the provisioning information when testing but would really love to get this working.

Thanks again and apologies if I have missed something and its staring me right in the face.

Mitch

**Comment by Tieske** [comment]
Been there :smile: 

Best option is to use cassandra cluster manager (ccm); http://www.datastax.com/dev/blog/ccm-a-development-tool-for-creating-local-cassandra-clusters

**Comment by mitchellfranklin** [comment]
Tieske thanks heaps for that, it may just be my brain but I do seem to see this as way over my skill level - no ones fault but my own of course. Q: is it possible of know if a VM or Virtual Box machine is available for download which is already setup with Kong/Cassandra etc.?

**Comment by hou-xn** [comment]
@mitchellfranklin If you use vagrant, this may be helpful because cassandra is included in that env. 
https://github.com/Mashape/kong-vagrant

**Comment by mitchellfranklin** [comment]
@hou-xn thank you very much - perfect and worked like a charm - thanks all for the help it is greatly appreciated
