### ISSUE TITLE
kong not reading new changes to kong.yml

### ISSUE THREAD

**Issue by danielrmeyer** [Mashape/kong#1036]
I have a single cassandra node running.  I updated /etc/kong/kong.ya]ml with the contact_points of my node.  Here is the kong.yml:
https://gist.github.com/danielrmeyer/c2dc122c639fbebf3494

After updating the kong.yaml I get the following--indicating that it has not read my changes from the config file:

```
ubuntu@ip-172-31-32-52:~$ kong version
Kong version: 0.7.0
ubuntu@ip-172-31-32-52:~$ kong reload
[INFO] Using configuration: /etc/kong/kong.yml
[ERR] Kong is not running
ubuntu@ip-172-31-32-52:~$ kong restart
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Leaving cluster..
[INFO] Kong 0.7.0
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........cassandra keyspace=kong ssl=verify=false enabled=false replication_factor=1 contact_points=127.0.0.1:9042 replication_strategy=SimpleStrategy timeout=5000 data_centers=
[INFO] Leaving cluster..
[ERR] Cassandra error: All hosts tried for query failed. 127.0.0.1:9042: connection refused for socket with peer 127.0.0.1:9042.
[ERR] Could not start Kong```

**Comment by thibaultCha** [comment]
This configuration file uses YAML formatting, you need to also uncomment the parent node of `contact_points`: `cassandra`.

**Comment by danielrmeyer** [comment]
I thought I did that. Is this not correct?
https://gist.github.com/danielrmeyer/c2dc122c639fbebf3494#file-kong-yml-L99

**Comment by thibaultCha** [comment]
https://gist.github.com/danielrmeyer/c2dc122c639fbebf3494#file-kong-yml-L96

**Comment by danielrmeyer** [comment]
I see.  Thanks
