### ISSUE TITLE
Serf problem

### ISSUE THREAD

**Issue by nsaliu** [Mashape/kong#1037]
Hi,
I'm tring to install Kong on OVH VPS but with no luck.
Any suggestion?

I paste the console error:

root@box:/home/webuser# kong start
[INFO] Kong 0.7.0
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........cassandra keyspace=kong ssl=verify=false enabled=false replication_factor=1 contact_points=localhost:9042 replication_strategy=SimpleStrategy timeout=5000 data_centers=
[INFO] dnsmasq............address=127.0.0.1:8053 dnsmasq=true port=8053
[INFO] Leaving cluster..
[ERR] Could not start serf: Failed to start the Serf agent: Error creating Serf: Failed to create memberlist: No private IP address found, and explicit IP not provided
[ERR] Could not start Kong
root@box:/home/webuser#

**Comment by thefosk** [comment]
@nsaliu there was a problem finding the first non loopback IPv4 address. To fix this issue just explicitly set an IP address using the [`cluster.advertise`](https://getkong.org/docs/0.7.x/configuration/#cluster) property.

**Comment by thefosk** [comment]
@nsaliu did that fix your problem?

**Comment by nsaliu** [comment]
Hi,
thanks for your reply!

I don't try your solution because then I install Kong with Docker on AWS instance.  

For a complete scenario, when I got this problem, the server was an OVH VPS with Ubuntu 14.04.

Thanks so much thefosk.

**Comment by thefosk** [comment]
Okay, anyways setting an explicit `advertise` address would have fixed this problem.

**Comment by sthzg** [comment]
FWIW, I was running into this error and configuring `cluster.advertise` works for me.

**Comment by tiw** [comment]
For macos users:

sudo cp /etc/kong/kong.conf.default /etc/kong/kong.conf
vi /etc/kong/kong.conf 
Set the advertise explicitly:
> cluster_advertise = 127.0.0.1:2312

If you start serf alone, you will get the same problem. To get ride of the problem using -v.
> serf agent -advertise=127.0.0.1:2133

**Comment by thefosk** [comment]
Hello - just a friendly reminder that from Kong >= 0.11.0 Serf is not a dependency anymore, and Kong nodes don't have to cluster together anymore. But don't worry, we still cache and invalidate data the same way by relying a little bit more on the underlying datastore.

You can play with the 0.11RC at https://github.com/Mashape/kong/releases
