### ISSUE TITLE
got error when starting kong (Mac OS X)

### ISSUE THREAD

**Issue by hou-xn** [Mashape/kong#1040]
Hi 
I installed kong with brew and when I use the command "kong start",I got the error like below.
Seems it need libuuid.1.dylib but I only have libuuid.16.dylib in that directory.
------------------------------------------- error info --------------------------------------------------------------- 
pft-no-MacBook-Pro:~ pft$ kong start
luajit: error loading module 'lua_uuid' from file '/usr/local/lib/lua/5.1/lua_uuid.so':
	dlopen(/usr/local/lib/lua/5.1/lua_uuid.so, 6): Library not loaded: /usr/local/lib/libuuid.1.dylib
  Referenced from: /usr/local/lib/lua/5.1/lua_uuid.so
  Reason: image not found
stack traceback:
	[C]: at 0x0100076a70
	[C]: in function 'require'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:9: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/kong/tools/config_loader.lua:3: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/kong/cli/cmds/start.lua:4: in main chunk
	[C]: in function 'require'
	/usr/local/bin/kong:55: in main chunk
	[C]: at 0x01000012d0

-------------------------------------------------------------------------------------------------------------------

**Comment by thefosk** [comment]
@hou-xn what version of Kong are you trying to execute?

**Comment by hou-xn** [comment]
I try to execute 0.7.0

**Comment by thibaultCha** [comment]
The libuuid library should be installed by the Formula too: https://github.com/Mashape/homebrew-kong/blob/master/Formula/kong.rb#L19

Do you see it among your installed Formulas?

**Comment by hou-xn** [comment]
@thibaultCha Yes, ossp-uuid was succefully installed but the version is 1.6.(libuuid.16.dylib) and when I start the kong , it seems need libuuid.1.dylib

**Comment by thefosk** [comment]
@hou-xn are you using homebrew or the osx package?

**Comment by hou-xn** [comment]
@thefosk Yes, I used command below:
brew tap mashape/kong
brew install kong

**Comment by hou-xn** [comment]
@thefosk  @thibaultCha 
Is there any way to get an old version lib for the ossp-uuid ? Because if I use brew install ossp-uuid, I will get the newest ossp-uuid (libuuid.16.dylib) installed and kong(0.7.0) will not start unless a libuuid.1.dylib is exists.
I really want to use kong in my Mac.

**Comment by mpetyx** [comment]
I had the exact same error with @hou-xn :+1:

**Comment by hou-xn** [comment]
@mpetyx Do you have any idea about that ?

**Comment by thibaultCha** [comment]
Installing the latest `ossp-uuid` does install the right library for me:

```bash
$ brew link ossp-uuid --dry-run
Would link:
/usr/local/bin/uuid
/usr/local/bin/uuid-config
/usr/local/include/ossp
/usr/local/share/man/man1/uuid-config.1
/usr/local/share/man/man1/uuid.1
/usr/local/share/man/man3/uuid.3
/usr/local/lib/libuuid.16.dylib
/usr/local/lib/libuuid.a
/usr/local/lib/libuuid.dylib # here
/usr/local/lib/pkgconfig/uuid.pc
```

**Comment by hou-xn** [comment]
@thibaultCha Yes, I have the same library version with you. But when I start kong(0.7.0) in my mac, there would be an error like I said on the top. It needs "libuuid.1.dylib" which could not found in my pc.

**Comment by hou-xn** [comment]
@thibaultCha Can you start kong 0.7.0 with your Mac PC with the newest ossp-uuid?

**Comment by thibaultCha** [comment]
Yes, every day

**Comment by thibaultCha** [comment]
Could you try reinstalling this module and see if it results in any error or warning?

```
brew install ossp-uuid
brew link --overwrite ossp-uuid
luarocks remove --force lua_uuid
luarocks install lua_uuid
```

The linker should already at this point complain if luuid is not available.

**Comment by hou-xn** [comment]
@thibaultCha 
When I try the command below , it worked.
$ luarocks remove --force lua_uuid
$ luarocks install lua_uuid

Thank you very much.It helps me a lot.

**Comment by thibaultCha** [comment]
That's great! :D
