### ISSUE TITLE
: attempt to perform arithmetic on field 'KONG_HEADER_FILTER_STARTED_AT' (a nil value)

### ISSUE THREAD

**Issue by jimmypk** [Mashape/kong#1042]
I see many error log in /usr/local/kong/logs/error.log

2016/03/04 10:31:34 [error] 2043#0: *41194 failed to run body_filter_by_lua*: /usr/local/share/lua/5.1/kong/core/handler.lua:96: attempt to perform arithmetic on field 'KONG_HEADER_FILTER_STARTED_AT' (a nil value)
stack traceback:
        /usr/local/share/lua/5.1/kong/core/handler.lua:96: in function 'after'
        /usr/local/share/lua/5.1/kong.lua:194: in function 'body_filter'
        body_filter_by_lua:2: in function <body_filter_by_lua:1>, client: 192.168.1.73, server: _, request: "GET /oauth/user.json HTTP/1.1", host: "test.abc.com"

I don't know what problem, and how to fix it.

Thanks.

**Comment by thefosk** [comment]
I was looking at the code and it seems like `ngx.ctx.KONG_HEADER_FILTER_STARTED_AT` is being set only if [`ngx.ctx.KONG_PROXIED` is `true`](https://github.com/Mashape/kong/blob/master/kong/core/handler.lua#L74-L78).

For some reason in your case `ngx.ctx.KONG_PROXIED` is `false`.

@thibaultCha maybe can help on this one.

**Comment by thibaultCha** [comment]
What makes this strange is that this block is never accessed unless `ngx.ctx.KONG_PROXIED` is true either, so I really don't see what could be causing this without more information. Was the code changed, is there a custom Nginx module running here? Or a custom Kong plugin?

**Comment by Tieske** [comment]
@jimmypk any update on this?

**Comment by Tieske** [comment]
@jimmypk are you still having this issue? Otherwise I'll close it.

**Comment by thefosk** [comment]
Please re-open if you still experience the issue.
