### ISSUE TITLE
Invalid data in manifest file for module kong.plugins.rate-limiting.daos (feature/postgres)

### ISSUE THREAD

**Issue by siddharthkchatterjee** [Mashape/kong#1045]
@thibaultCha, your branch `feature/postgres` breaks for me when I try to run it, with this —
```
[INFO] Kong 0.7.0                                                                                     
[INFO] Using configuration: kong_DEVELOPMENT.yml                                                      
/usr/local/bin/luajit: /usr/local/share/lua/5.1/kong/tools/utils.lua:229: /usr/local/share/lua/5.1/lua
rocks/loader.lua:154: Invalid data in manifest file for module kong.plugins.rate-limiting.daos (invali
d data for kong 0.7.0-0)                                                                              
stack traceback:                                                                                      
        [C]: in function 'error'                                                                      
        /usr/local/share/lua/5.1/kong/tools/utils.lua:229: in function 'load_module_if_exists'        
        /usr/local/share/lua/5.1/kong/dao/factory.lua:98: in function 'new'                           
        /usr/local/share/lua/5.1/classic.lua:63: in function 'load'                                   
        /usr/local/share/lua/5.1/kong/cli/services/serf.lua:23: in function 'new'                     
        /usr/local/share/lua/5.1/classic.lua:63: in function 'service'                                
        /usr/local/share/lua/5.1/kong/cli/utils/services.lua:88: in function 'check_status'           
        /usr/local/share/lua/5.1/kong/cli/cmds/start.lua:21: in main chunk                            
        [C]: in function 'require'                                                                    
        /usr/local/lib/luarocks/rocks/kong/0.7.0-0/bin/kong:55: in main chunk                         
        [C]: at 0x00404e10
```

`kong/dao/factory.lua:98` seems like the problem. Removing it entirely fixes this and passes all tests. But I'm sure that's not the solution since it'll result with an empty schema further down.

**Comment by thibaultCha** [comment]
Ideally you should run this branch in a purged luarocks tree, so that no file conflicts with the current 0.7.0 version. 

```
$ luarocks purge --tree=/usr/local
```

**Comment by thibaultCha** [comment]
Thank you for giving this a try btw! As a side note, currently the branch is being tweaked by @thefosk to enable clustering capabilities in Postgres. This is currently quite unstable. For the moment, if you are fine with only running one node, I would suggest doing so.

**Comment by siddharthkchatterjee** [comment]
Alright, I purged the tree and now `sudo make dev` fails with —
```
Error: Failed installing dependency: https://luarocks.org/luacrypto-0.3.2-1.src.rock - Could not find expected file openssl/evp.h, or openssl/evp.h for OPENSSL -- you may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command. Example: luarocks install luacrypto OPENSSL_DIR=/usr/local
```

I have `openssl` installed. Any ideas? Also, you're welcome. I'm running a single node to test with.

**Comment by thibaultCha** [comment]
Are you on OS X? If so, this is a common error since the openssl shipped by default in OS X is not in the default search paths. If you are not on OS X, it seems this is the error anyways...

On OS X, installing openssl via Homebrew, and linking it overrides the default installation and places openssl in `/usr/local`, which is a default search path for your compiler and linker:

```
$ brew install openssl
$ brew link --force openssl
```

If you are not on OS X or if you do not wish to instal openssl from Homebrew, then you would have to point Luarocks to your actual openssl installation:

```
$ OPENSSL_DIR="" OPENSSL_INCDIR="" luarocks make
```

**Comment by siddharthkchatterjee** [comment]
I'm running trusty64 in a VM. I had `openssl` installed but I think I needed `libssl-dev`. Installing that fixed this. 

Also, purging the luarocks tree seems to have fixed what was breaking as well. I'm closing this issue. Thank you, @thibaultCha.

**Comment by thibaultCha** [comment]
Oh yes, of course an openssl installed is better than no install at all :)

Great!
