### ISSUE TITLE
An unexpected error occurred (feature/postgres)

### ISSUE THREAD

**Issue by siddharthkchatterjee** [Mashape/kong#1046]
@thibaultCha, I get this response from `GET /apis` after successfully registering a few routes —
```{ response: { message: 'An unexpected error occurred' } }```

The documents look perfectly fine in the database. After manually deleting all rows in the `apis` table, things work fine again. I don't see any logs written to disk.

What would you need to debug this? Can you help?

**Comment by siddharthkchatterjee** [comment]
This is the error that postgres logs —
```
ERROR:  invalid input syntax for uuid: "vagrant-ubuntu-trusty-64_0.0.0.0:7946"
STATEMENT:  SELECT COUNT(*) FROM apis LEFT OUTER JOIN ttls ON (apis.id = ttls.primary_key_value::uuid) WHERE
            (ttls.primary_key_value IS NULL OR (ttls.table_name = 'apis' AND expire_at > CURRENT_TIMESTAMP(0) at time zone 'utc'))
```

**Comment by siddharthkchatterjee** [comment]
And it automagically doesn't throw the error anymore.

**Comment by thibaultCha** [comment]
Which commit are you on exactly?

**Comment by siddharthkchatterjee** [comment]
I'm on b732652dec91f1d4cca1ca76875cb05f1b3cc6a2 (fix(plugins_iter) deterministic plugin retrieval with C*).

**Comment by thibaultCha** [comment]
I did not implement this part of the feature tbh. But I would recommend pulling the branch again.

**Comment by siddharthkchatterjee** [comment]
@thibaultCha, alright. I just got a bunch of updates in the pull. I'll comment back here if it persists. I'm sorry about the constant bother. Just trying to help.

**Comment by thibaultCha** [comment]
Sure, no bother, it's appreciated :)
