### ISSUE TITLE
A Facebook/Google/... login plugin

### ISSUE THREAD

**Issue by aviemzur** [Mashape/kong#1047]
A plugin for authentication via Facebook/Google/...

**Comment by thefosk** [comment]
@aviemzur to better understand your request, since Kong has no GUI interface, how would that work?

**Comment by Tieske** [comment]
closing this due to lack of response

**Comment by vanhtuan0409** [comment]
Could be something like using Social Account (Facebook/Google/Github/...) to authenticate the consumer
Then we can use ACL plugins to control access to service
This could be really nice to have this feature
