### ISSUE TITLE
Can kong support other database?

### ISSUE THREAD

**Issue by luofanyuguai** [Mashape/kong#1051]
like normal db?

**Comment by thefosk** [comment]
Hello. What do you mean by normal db?

**Comment by mingfang** [comment]
+1 to remove dependency on cassandra.
I'm guessing normal == mysql

**Comment by thibaultCha** [comment]
See

#183
#331
#883

**Comment by thefosk** [comment]
Support for a relation database will land in v0.8, and it's going to be PostgreSQL.

**Comment by luofanyuguai** [comment]
thanks ,

**Comment by wanghaisheng** [comment]
@thefosk  when v0.8 will be released ?

**Comment by thefosk** [comment]
Take it with a grain of salt, maybe within a month. Closing as duplicate.

**Comment by TofuLay** [comment]
+1
