### ISSUE TITLE
Kong won't start when Cassandra is in different server

### ISSUE THREAD

**Issue by kdlcruz** [Mashape/kong#1057]
Hi,

It was stuck in the "core" migration.

> [INFO] Kong 0.7.0
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........cassandra keyspace=kong ssl=verify=false enabled=false replication_factor=1 contact_points=10.176.69.147:9042 replication_strategy=SimpleStrategy timeout=5000 data_centers=
[INFO] Database not initialized. Running migrations...
[INFO] Migrating core on keyspace "kong" (cassandra)
[INFO] core migrated up to: 2015-01-12-175310_skeleton
[INFO] core migrated up to: 2015-01-12-175310_init_schema
[INFO] core migrated up to: 2015-11-23-817313_nodes

This is where my migration was stuck.
My Cassandra is in different server. 

Here is the last bit of /var/log/cassandra/system.log

> INFO  [Creating index: nodes.nodes_cluster_listening_address_idx] 2016-03-09 23:00:30,207 SecondaryIndex.java:203 - Submitting index build of nodes.nodes_cluster_listening_address_idx for data in 
INFO  [Creating index: nodes.nodes_cluster_listening_address_idx] 2016-03-09 23:00:30,207 ColumnFamilyStore.java:900 - Enqueuing flush of IndexInfo: 346 (0%) on-heap, 0 (0%) off-heap
INFO  [MemtableFlushWriter:6] 2016-03-09 23:00:30,208 Memtable.java:347 - Writing Memtable-IndexInfo@656591458(0.056KiB serialized bytes, 1 ops, 0%/0% of on/off-heap limit)
INFO  [MemtableFlushWriter:6] 2016-03-09 23:00:30,208 Memtable.java:382 - Completed flushing /var/lib/cassandra/data/system/IndexInfo-9f5c6374d48532299a0a5094af9ad1e3/system-IndexInfo-tmp-ka-108-Data.db (0.000KiB) for commitlog position ReplayPosition(segmentId=1457562122489, position=1104952)
INFO  [Creating index: nodes.nodes_cluster_listening_address_idx] 2016-03-09 23:00:30,214 SecondaryIndex.java:216 - Index build of nodes.nodes_cluster_listening_address_idx complete
INFO  [HANDSHAKE-/10.176.65.148] 2016-03-09 23:00:40,364 OutboundTcpConnection.java:485 - Handshaking version with /10.176.65.148

Thanks,
Kevin

**Comment by thefosk** [comment]
Can you check the error log at `/usr/local/kong/logs/error.log`?

**Comment by kdlcruz** [comment]
No logs is created.

> admin@burstagecom:~$ tail -f /usr/local/kong/logs/error.lo
tail: cannot open `/usr/local/kong/logs/error.lo' for reading: No such file or directory

**Comment by thefosk** [comment]
You miss a final `g` in `.log`.

**Comment by kdlcruz** [comment]
sorry, but I just checked again.

> /usr/local/kong$ ll
total 8
drwxrwxrwx  2 root root 4096 Feb 25 02:41 ./
drwxr-xr-x 12 root root 4096 Mar  8 02:51 ../

**Comment by thefosk** [comment]
What version of Cassandra are you using? Kong requires Cassandra 2.2.x

**Comment by kdlcruz** [comment]
2.1.10

I'll try to upgrade my Cassandra.

Thanks for your help!

**Comment by thefosk** [comment]
@kdlcruz let me know if that fixes it

**Comment by kdlcruz** [comment]
@thefosk 

Cassandra is now 2.2.5 but I can't start it anymore.

> ERROR 01:28:32 Fatal exception during initialization
org.apache.cassandra.exceptions.ConfigurationException: Saved cluster name Test Cluster != configured name bc5d6f7b-1561-462c-a5c4-186c9f6306b2
	at org.apache.cassandra.db.SystemKeyspace.checkHealth(SystemKeyspace.java:736) ~[apache-cassandra-2.2.5.jar:2.2.5]
	at org.apache.cassandra.service.StartupChecks$9.execute(StartupChecks.java:306) ~[apache-cassandra-2.2.5.jar:2.2.5]
	at org.apache.cassandra.service.StartupChecks.verify(StartupChecks.java:107) ~[apache-cassandra-2.2.5.jar:2.2.5]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:162) [apache-cassandra-2.2.5.jar:2.2.5]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:516) [apache-cassandra-2.2.5.jar:2.2.5]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:625) [apache-cassandra-2.2.5.jar:2.2.5]

**Comment by kdlcruz** [comment]
Ok, Everything is working now. :). First of, I was able to make it work using Cassandra 2.1.10. The probelm was the version of my nodes are not the same. So after updating the, Kong was able to start successfully. 

Thanks for your help!

**Comment by thibaultCha** [comment]
That is great! And yes, Kong is compatible both with Cassandra 2.1 and 2.2.

Alright :)
