### ISSUE TITLE
How to create a single-api consumer

### ISSUE THREAD

**Issue by ejether** [Mashape/kong#1058]
If I want to create a consumer that only has access to a one api, how can I go about doing that.  I wasn't able to find an answer in the docs. 
Thanks

**Comment by ThorArakis** [comment]
I think it depends on the auth type you are using. For instance with JWT you associate an auth to a consumer _and_ to an api. So it's more of an opt-in model per api which would allow you to have a certain JWT credential only access a single api but not others. 

Which auth method are you trying to use?

**Comment by ejether** [comment]
We are currently using key-auth style. We are converting to Kong from another api-manager proxy and that what we're set up handle currently. JWT might work for us in the future though. Thanks for the info.

**Comment by ThorArakis** [comment]
You could try using the key-auth plugin in conjunction with the ACL plugin (allows you to white/black list apis by consumer). It might be a little bit more setup but could be a lot less work then requiring you to move to a new auth mechanism.

**Comment by thefosk** [comment]
The ACL plugin would be the way to go.

**Comment by ejether** [comment]
Awesome, I'll give that a shot. 
Thanks folks!
