### ISSUE TITLE
cli: missing error check for services/prepare

### ISSUE THREAD

**Issue by deltheil** [Mashape/kong#1066]
Currently (Kong +0.6.0) there is [no error check for this step](https://github.com/Mashape/kong/blob/4943619e1b68c111caaa11e8c369ee173896f31d/kong/cli/utils/services.lua#L93).

e.g. I encountered this as I worked with wrongly configured SSL certificates. In consequence the [nginx SSL preparation](https://github.com/Mashape/kong/blob/4943619e1b68c111caaa11e8c369ee173896f31d/kong/cli/services/nginx.lua#L125-L129) **failed silently** (the CLI tool reports nothing, and Kong fails to start because `nginx.conf` is not written under the ad-hoc directory).

What about doing something like:

```Lua
for _, v in ipairs(services) do
  local obj = v(configuration, configuration_path)
  local ok, err
  ok, err = obj:prepare()
  if not ok then
    return ok, err
  end
  ok, err = obj:start()
  if not ok then
    return ok, err
  end
end
```

**Comment by thibaultCha** [comment]
I agree, the CLI is not really reliable and a lot could be done to improve it... On a private branch I have been reimplementing many of Kong's current issues, and its CLI looks something like this:

```lua
-- init.lua (main entry point)

-- retrieve args

-- retrieve command (eg: start)
xpcall(function() cmd_execute(args) end, function(err)
  -- proper error handling, with optional stacktrace retrieval
end) 
```

And have the actual commands simply throw errors:

```lua
-- start.lua
local function execute(args)
  assert(nginx.prepare_prefix(conf, args.prefix)) -- ok, err
  assert(nginx.start_signal(args.prefix)) -- ok, err

  print("Started")
end

return {
  -- ...
  execute = execute
}
```

It could probably be backported to Kong.
