### ISSUE TITLE
Error on upload files via kong proxy

### ISSUE THREAD

**Issue by jl91** [Mashape/kong#1067]
kong throwing error "An unexpected error occurred" with server 500 when we try to upload a file via kong proxy with post. We identitf that this error occurs when kong try to merge the request in 

kong/plugins/oauth2.lua

in line 94 
return utils.table_merge(ngx.req.get_uri_args(), ngx.req.get_post_args())

this error dont happen if we change this line for this another line 

return ngx.req.get_uri_args()

In my error log i have this 

coroutine 0:
	[C]: in function 'get_post_args'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:97: in function 'retrieve_parameters'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:344: in function 'parse_access_token'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:397: in function 'execute'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:12: in function 'access'
	/usr/local/share/lua/5.1/kong.lua:173: in function 'access'
	access_by_lua(nginx.conf:98):2: in function <access_by_lua(nginx.conf:98):1>, client: 127.0.0.1, server: _, request: "POST /rebate/debit-notes HTTP/1.1", host: "localhost:8000"

**Comment by thefosk** [comment]
@jl91 I believe my PR fixes your problem. Is the error message you pasted the full log?

**Comment by jl91** [comment]
no, this is a tail off log. tomorrow i update this ticket.

**Comment by thefosk** [comment]
Okay - I think my PR fixes it but seeing the full log would still help.

**Comment by jl91** [comment]
now i have another problem. Everytime i reboot my pc and when i try to start kong have this messa.

[ERR] nginx: [error] [lua] kong.lua:144: init(): Startup error: /usr/local/share/lua/5.1/kong/tools/utils.lua:221: /usr/local/share/lua/5.1/kong/plugins/runscope/handler.lua:3: module 'kong.plugins.runscope.log' not found:	no field package.preload['kong.plugins.runscope.log']	no file '/usr/local/openresty/lualib/kong/plugins/runscope/log.lua'	no file '/usr/local/openresty/lualib/kong/plugins/runscope/log/init.lua'	no file './kong/plugins/runscope/log.lua'	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta1/kong/plugins/runscope/log.lua'	no file '/usr/local/share/lua/5.1/kong/plugins/runscope/log.lua'	no file '/usr/local/share/lua/5.1/kong/plugins/runscope/log/init.lua'no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/runscope/log.lua'	no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/runscope/log/init.lua'	no file '/usr/local/openresty/lualib/kong/plugins/runscope/log.so'	no file './kong/plugins/runscope/log.so'	no file '/usr/local/lib/lua/5.1/kong/plugins/runscope/log.so'	no file '/usr/local/openresty/luajit/lib/lua/5.1/kong/plugins/runscope/log.so'	no file '/usr/local/lib/lua/5.1/loadall.so'	no file '/usr/local/openresty/lualib/kong.so'	no file './kong.so'	no file '/usr/local/lib/lua/5.1/kong.so'	no file '/usr/local/openresty/luajit/lib/lua/5.1/kong.so'	no file '/usr/local/lib/lua/5.1/loadall.so'
[ERR] Could not start Kong


To fix that always i have to "Make install again kong"

**Comment by Tieske** [comment]
see #1079

**Comment by thefosk** [comment]
@jl91 that's fixed in the next release.

**Comment by jl91** [comment]
thanks man, really thanks i love this project haha <3

**Comment by thefosk** [comment]
@jl91 btw you can give it a try, RC1 is out: https://github.com/Mashape/kong/releases/tag/0.8.0rc1
