### ISSUE TITLE
request_path already exists with value ***

### ISSUE THREAD

**Issue by windinn** [Mashape/kong#1075]
When add 2 APIs with same request_path but different request_host, kong complains:
> request_path already exists with value ***

Does it make sense?

**Comment by thibaultCha** [comment]
Yes, this is the expected behavior. Path and Host do not take each other into consideration and hence must be unique. See https://groups.google.com/forum/#!searchin/konglayer/already$20exists/konglayer/rqeWoudWBRY/hOIBFtSgCwAJ
