### ISSUE TITLE
kong.plugins.runscope.log and kong.plugins.runscope.buffer

### ISSUE THREAD

**Issue by worktick** [Mashape/kong#1079]
- An overview of the issue
  - We noticed that kong.plugins.runscope.handler is requesting kong.plugins.runscope.log - but in the rockspec this is defined as kong.plugins.runscope.buffer. It's slightly misleading when reading the code but also throws a startup error when installing (and starting up) from a rockspec.
- Your use case (why is this a bug for you?)
  - It throws a startup error when deploying from a rockspec
- The version of Kong you are running
  - 0.7.0 release/master
- The platform you are running Kong on
  - OSX & CentOS
- Steps to reproduce the issue
  - On a dev-build modify your `yml` config so that `lua_package_path ';;';`
  - On a release-buidl install from rockspec - run from a location where the source isn't available
- Eventually, logs from your error.log file. You can find this file at <nginx_working_dir>/logs/error.log
  - `/usr/local/share/lua/5.1/kong/plugins/runscope/handler.lua:3: module 'kong.plugins.runscope.log' not found:	no field package.preload['kong.plugins.runscope.log']	no file`
- Ideally, a suggested fix
  - In `kong.plugins.runscope.handler` change `local log = require "kong.plugins.runscope.log"` to `local log = require "kong.plugins.runscope.buffer"`
  - or in `kong-0.7.0-0.rockspec` change `["kong.plugins.runscope.buffer"] = "kong/plugins/runscope/log.lua",` to `["kong.plugins.runscope.log"] = "kong/plugins/runscope/log.lua",`

**Comment by thibaultCha** [comment]
Thank you for the detailed report! I just merged #1085 which fixes this and adds a test for such mistakes.
