### ISSUE TITLE
[Request] Oauth2 - multiple redirect_uri per app

### ISSUE THREAD

**Issue by PGBI** [Mashape/kong#1080]
Right now, only one redirect_uri per app can be defined. The Oauth2 spec actually allows to define several redirect_uri for an app: https://tools.ietf.org/html/rfc6749#section-3.1.2.3

> If multiple redirection URIs have been registered, ...

**Comment by PGBI** [comment]
@thefosk I saw you self-assigned this issue. Did you start working on it? If not, I could give it a try and submit a PR. I just want to make sure you guys are OK with this feature before I spend time on this.

**Comment by thefosk** [comment]
@PGBI I will start working on this issue next week, but if you want to jump in that'd be helpful.

**Comment by PGBI** [comment]
@thefosk will give it a try. But lua is still obscure to me :/

**Comment by Tieske** [comment]
@PGBI Thanks for trying! And considering some code we've seen, I doubt yours will shock us :smile: 
Once you have something to review, create a PR and we'll have a look.

**Comment by PGBI** [comment]
@thefosk I started to work on this issue. I started to update the oauth2_credentials schema to make redirect_uri be an array, and not a "url" anymore.

When I do:
POST /consumers/id/oauth2
```json
{ 
  "consumer_id": "5974c208-23db-4bfe-8880-d388de23801e",
  "name": "test",
  "client_id": "test",
  "client_secret": "test",
  "redirect_uri": ["http://www.google.com", "http://aaa", "http://aze"]
}
```
I get a correct answer:
```json
{
  "consumer_id": "5974c208-23db-4bfe-8880-d388de23801e",
  "client_id": "test",
  "id": "cfb33476-9324-483e-be9c-08ce0652054c",
  "redirect_uri": ["http://www.google.com", "http://aaa", "http://aze"],
  "name": "test",
  "created_at": 1458923382000,
  "client_secret": "test"
}
```

However, when I try to fetch this oauth2_credentials record afterwards, here is what I get:
```json
{
  "consumer_id": "5974c208-23db-4bfe-8880-d388de23801e",
  "client_id": "test",
  "id": "cfb33476-9324-483e-be9c-08ce0652054c",
  "redirect_uri": "\u0000\u0000\u0000\u0003\u0000\u0000\u0000\u0015http://www.google.com\u0000\u0000\u0000\nhttp://aaa\u0000\u0000\u0000\nhttp://aze",
  "name": "test",
  "created_at": 1458923382000,
  "client_secret": "test"
}
```

Here is the diff: https://github.com/Mashape/kong/compare/master...classy-org:fix_issue_1080 . I'm kind of blocked here, I would appreciate if you could enlighten me on this :)

**Comment by PGBI** [comment]
Ok. Will have something ready in a day or 2
