### ISSUE TITLE
client credentials workflow

### ISSUE THREAD

**Issue by kamaydeo** [Mashape/kong#1081]
I am having issues with setting up client_credentials OAtuh2 flow on Kong. 
 
I mainly need client_id and client_secret for this flow; however I couldn’t find any documentation reference to show me how to create a consumer with this info.

Effectively, I will make this call

curl  -X POST 'https://kong:8001/oauth2/token' -d 'grant_type=client_credentials&client_id=ns4fQc14Zg4hKFCNaSzArVuwszX95X&client_secret=ZIjFyTsNgQNyxI’

Questions

1. How do I create a consumer with client_id and client_credentials?
2. How do I link the consumer with my api?

In general, please walk me through the steps to set up client credentials OAuth2 workflow.

**Comment by thefosk** [comment]
> How do I create a consumer with client_id and client_credentials?

https://getkong.org/plugins/oauth2-authentication/#create-a-consumer and https://getkong.org/plugins/oauth2-authentication/#create-an-application

> How do I link the consumer with my api?

You can use the [ACL plugin](https://getkong.org/plugins/acl/).

**Comment by kamaydeo** [comment]
create-an-application forces you to provide redirect_uri which is not relevant for client_credentials workflow. Can I just use a fake/empty url instead?

**Comment by kamaydeo** [comment]
ok. I created a consumer and an application. 
curl -X POST http://kong:8001/consumers/ --data "username=user123"

curl -X POST http://kong:8001/consumers/user123/oauth2 \
    --data "name=Test%20Application" \
    --data "client_id=web" \
    --data "client_secret=pass" \
    --data "redirect_uri=http://some-domain/endpoint/"

When I make the following request

curl -X POST 'https://kong:8001/oauth2/token' -d 'grant_type=client_credentials&client_id=web&client_secret=pass’

I get 404 -
 {
  "message": "Not found"
}

What am I missing?

**Comment by thefosk** [comment]
This URL is wrong: `https://kong:8001/oauth2/token`. You need to append `/oauth2/token` when consuming the API on the proxy port (defaul is `8000`).

**Comment by kamaydeo** [comment]
Thanks. It works now.
