### ISSUE TITLE
Chrome: Refused to set unsafe header "Host"

### ISSUE THREAD

**Issue by fairuskhalid** [Mashape/kong#1083]
I am trying out the Kong example and using chrome rest client application.While trying to make the api request through kong.

curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: mockbin.com'

I got this error:

404: Not Found

{
"request_path": "/"
"message": "API not found with these values"
"request_host": [1]
0:  "10.1.71.58"
-
}

Upon investigation I found that chrome is blocking the change of http header with "Host" information. There is open chrome bug for this:

https://bugs.chromium.org/p/chromium/issues/detail?id=364319

The question/bug is can we use other attribute (other then 'host') to identify the api that kong need to forward to.

**Comment by thefosk** [comment]
You could use the path resolver to resolve the API, instead of using a `Host` header. That should work.

**Comment by fairuskhalid** [comment]
Thanks for the input. Further reading I found using the "X-Host-Override" header to solve the problem.

$ curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'X-Host-Override: mockbin.com'

**Comment by athlonUA** [comment]
@fairuskhalid hello! What about your last solution with `X-Host-Override`? Does it works for you?

**Comment by athlonUA** [comment]
@thefosk hi! Can you please describe your proposition about using path resolver in the tandem with Kongo?

**Comment by thefosk** [comment]
@athlonUA since CORS doesn't allow to set the `Host` header, you can still consume an API behind Kong using a path resolver instead of the host resolver. By using the path resolver you will be bypassing the problem since no headers have to be changed.

**Comment by OhBonsai** [comment]
@thefosk Could you give some examples  or doc links about `path resolver`... I can'd find path resolver doc

**Comment by OhBonsai** [comment]
@thefosk  I found request_path option isn't useful in kong 0.10+ version.....

**Comment by OhBonsai** [comment]
@athlonUA  I found an solution... 
Suppose your Api is `/api/v1/version` and your Host is ` mockbin.com`
In kong0.11+ , you can set `Uris` to `/mockbin/whateverYouWanna` and set Strip uri True.
Then  you can request `/mockbin/whateverYouWanna/api/v1/version` without setting header in request
