### ISSUE TITLE
Does Kong cluster have an virtual IP?

### ISSUE THREAD

**Issue by jimmypk** [Mashape/kong#1087]
I have setup Kong cluster 2 node successfully. Does Kong cluster have an virtual IP, so I can point the DNS record to that IP? If 1 node die, another node will handle that virtual IP.
Or I must use HAProxy to load balancing between 2 nodes?

**Comment by Tieske** [comment]
Kong just listens on the local port you configure, that's it. You have to create your own setup to spread your incoming traffic over the Kong nodes you have running.
