### ISSUE TITLE
can not create serf_event.sh in apline docker

### ISSUE THREAD

**Issue by gavinzhou** [Mashape/kong#1099]
I use alpine build kong in docker
but can not create serf_event.sh file

```
kong start
[INFO] Kong 0.7.0
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........cassandra keyspace=kong ssl=verify=false enabled=false replication_factor=1 contact_points=172.17.0.3:9042 replication_strategy=SimpleStrategy timeout=5000 data_centers=
[INFO] dnsmasq............address=127.0.0.1:8053 dnsmasq=true port=8053
[INFO] serf ..............-profile=wan -rpc-addr=127.0.0.1:7373 -event-handler=member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf_event.sh -bind=0.0.0.0:7946 -node=96bf601187c5_0.0.0.0:7946 -log-level=err
[INFO] Trying to auto-join Kong nodes, please wait..
[INFO] Successfully auto-joined 172.17.0.5:7946
[INFO] Auto-generating the default SSL certificate and key...
[INFO] Leaving cluster..
```

PS:sorry my english

**Comment by gavinzhou** [comment]
I get this error log
```
/usr/local/kong # more serf.log
==> Starting Serf agent...
==> Starting Serf agent RPC...
==> Serf agent running!
         Node name: '1b9b89ce5f71_0.0.0.0:7946'
         Bind addr: '0.0.0.0:7946'
          RPC addr: '127.0.0.1:7373'
         Encrypted: false
          Snapshot: false
           Profile: wan

==> Log data will now stream in as it occurs:

    2016/03/25 16:24:35 [ERR] agent: Error invoking script '/usr/local/kong/serf_event.sh': exit status 127
==> Caught signal: interrupt
==> Gracefully shutting down agent...
```

**Comment by gavinzhou** [comment]
I created /usr/local/openresty/luajit/bin/luajit-2.1.0-beta1 to /usr/local/bin/luajit
```
ls -l /usr/local/bin/luajit
lrwxrwxrwx    1 root     root            38 Mar 26 01:11 /usr/local/bin/luajit -> /usr/local/openresty/luajit/bin/luajit
```
it work

```
ls /usr/local/kong/
client_body_temp  logs              proxy_temp        serf.log          serf_event.sh     uwsgi_temp
fastcgi_temp      nginx.conf        scgi_temp         serf.pid          ssl
```

```
cat /usr/local/bin/kong
#!/bin/sh

exec '/usr/local/openresty/luajit/bin/luajit-2.1.0-beta1' -e 'package.path="/root/.luarocks/share/lua/5.1/?.lua;/root/.luarocks/share/lua/5.1/?/init.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;"..package.path; package.cpath="/root/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?.so;"..package.cpath' -e 'local k,l,_=pcall(require,"luarocks.loader") _=k and l.add_context("kong","0.7.0-0")' '/usr/local/lib/luarocks/rocks/kong/0.7.0-0/bin/kong' "$@"

**Comment by thefosk** [comment]
The file is being created at startup in the working directory. So can you make sure Kong can write to the working directory, and that `serf_event.sh` can be executed (`chmod +x serf_event.sh`).

The serf implementation will soon be updated with a native Lua client to get rid of this file by the way.

**Comment by gavinzhou** [comment]
I change directory mode to 777
but can not created serf_event.sh

thank you

**Comment by thefosk** [comment]
@gavinzhou in the `ls /usr/local/kong/` output you posted before, I can see `serf_event.sh`, or am I wrong?

**Comment by gavinzhou** [comment]
I created /usr/local/openresty/luajit/bin/luajit-2.1.0-beta1 to /usr/local/bin/luajit

running kong start to created serf_event.sh file

**Comment by thefosk** [comment]
hi @gavinzhou - just to better understand this, after renaming `/usr/local/openresty/luajit/bin/luajit-2.1.0-beta1` to `/usr/local/bin/luajit` kong was able to successfully create the `serf_event.sh` file. Is that correct?

**Comment by gavinzhou** [comment]
hi @thefosk 
yes,I created symbol link, it working

<pre>
/ # ls -ls /usr/local/openresty/luajit/bin/luajit
     0 lrwxrwxrwx    1 root     root            18 Mar 26 01:38 /usr/local/openresty/luajit/bin/luajit -> luajit-2.1.0-beta1
/ # ls -l /usr/local/bin/luajit
lrwxrwxrwx    1 root     root            38 Mar 26 01:39 /usr/local/bin/luajit -> /usr/local/openresty/luajit/bin/luajit
</pre>

**Comment by thefosk** [comment]
Yes, I know why now it wasn't working on your system. Because in our distributions we already move that file so that it's already in `/usr/local/bin`: https://github.com/Mashape/kong-distributions/blob/master/.build-package-script.sh#L208

Mystery solved.
