### ISSUE TITLE
When Cassandra is temporarily down make sure the connection is resumed

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#11]
It may happen because of network issues, and we need to make sure it doesn't crash the application but it logs the error and resumes the connection as soon as it's available again.

Make sure that when testing this nginx runs with `daemon on;`.

**Comment by thibaultCha** [comment]
#28 now uses the cosocket API. So we might loose some queries but the connection will be resumed as soon as cassandra is reachable again. Now we need to know if this doesn't throw any unexpected errors that could disturb the execution of plugins not using the DB.

**Comment by thefosk** [comment]
Right now this doesn't happen. Connection to Cassandra is never resumed and nginx logs the following error:

```
2015/02/24 00:35:42 [error] 19605#0: *1 [lua] access.lua:28: execute(): Cassandra returned error (Unprepared): "Prepared query with ID 29083996e2fe585226bc6e89ae37c690 not found (either the query was not prepared on this host (maybe the host has been restarted?) or you have prepared too many queries and it has been evicted from the internal cache)", client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8000"
```

**Comment by thibaultCha** [comment]
That looks like executed during the preparation phase, not during running. It looks like the connection just doesn't work at all here

**Comment by thibaultCha** [comment]
Not sure, gonna need more infos on this lol

**Comment by thibaultCha** [comment]
if the cluster shuts down and restarts, prepared query are dropped and need to be re-prepared.

**Comment by thibaultCha** [comment]
Will fix this soon as the fix has been merged into the driver now.

**Comment by thibaultCha** [comment]
BTW, re-reading the issue: it won't cause any issue if cassandra is unreachable because of network issues beyond dropping the queries.

It will only be a more critical issue if cassandra was restarted for some reason, because the statements aren't prepared anymore, resulting in errors and no query will succeed.
