### ISSUE TITLE
cli: report error before stopping services

### ISSUE THREAD

**Issue by deltheil** [Mashape/kong#1100]
In some situations [`stop_all`](https://github.com/Mashape/kong/blob/cbd03da63e206a10cb17d7cfec976064fe699905/kong/cli/cmds/start.lua#L33) could stuck forever and this could precisely be related to a service that could not start, e.g. serf (see below).

IMHO it would be better to [log the start error](https://github.com/Mashape/kong/blob/cbd03da63e206a10cb17d7cfec976064fe699905/kong/cli/cmds/start.lua#L34) _before_ stopping the services (or even put [these 2 lines](https://github.com/Mashape/kong/blob/cbd03da63e206a10cb17d7cfec976064fe699905/kong/cli/cmds/start.lua#L34-L35) before `stop_all`) so that the user gets informed of what went wrong.

Note: I encountered this problem with Kong 0.7.0 after an upgrade to Amazon Linux 2016.03 / kernel 4.4.5 which makes serf fails with `Trace/breakpoint trap` (see [this thread](https://github.com/golang/go/issues/14795)). Kong got stuck in `Leaving cluster..` forever, and no error was reported before.

**Comment by deltheil** [comment]
Closely related: the error message reported by `BaseService:_get_cmd` is systematically kind of `"Can't find <service>"` (see [here](https://github.com/Mashape/kong/blob/cbd03da63e206a10cb17d7cfec976064fe699905/kong/cli/services/base_service.lua#L74)). I have the feeling it could be more accurate if `check_path_func` was able to bubble up any non zero error code encountered. Here's a draft patch against 0.7.0 tag:

```diff
diff --git a/kong/cli/services/base_service.lua b/kong/cli/services/base_service.lua
index a8b77b8..bf311fa 100644
--- a/kong/cli/services/base_service.lua
+++ b/kong/cli/services/base_service.lua
@@ -33,17 +33,22 @@ function BaseService.find_cmd(app_name, additional_paths, check_path_func)
   end
 
   if check_path_func then
+    local ok, code
     for _, found_file_path in ipairs(found_file_paths) do
-      if check_path_func(found_file_path) then
-        return found_file_path 
+      ok, code = check_path_func(found_file_path)
+      if ok then
+        return found_file_path
       end
     end
+    if code ~= 0 then
+      return nil, "Error code: "..code
+    end
   elseif #found_file_paths > 0 then
     -- Just return the first path
     return table.remove(found_file_paths, 1)
   end
 
-  return nil
+  return nil, "Can't find "..app_name
 end
 
 function BaseService:new(name, nginx_working_dir)
@@ -69,9 +74,9 @@ end
 
 function BaseService:_get_cmd(additional_paths, check_path_func)
   if not self._cmd then -- Cache the command after the first time
-    local cmd = BaseService.find_cmd(self._name, additional_paths, check_path_func)
+    local cmd, err = BaseService.find_cmd(self._name, additional_paths, check_path_func)
     if not cmd then
-      return nil, "Can't find "..self._name
+      return nil, err
     end
     self._cmd = cmd
   end
diff --git a/kong/cli/services/nginx.lua b/kong/cli/services/nginx.lua
index a0c4b62..c040fcb 100644
--- a/kong/cli/services/nginx.lua
+++ b/kong/cli/services/nginx.lua
@@ -193,11 +193,11 @@ function Nginx:_get_cmd()
   }, function(path)
     local res, code = IO.os_execute(path.." -v")
     if code == 0 then
-      return res:match("^nginx version: ngx_openresty/") or
-             res:match("^nginx version: openresty/")
+      return (res:match("^nginx version: ngx_openresty/") or
+              res:match("^nginx version: openresty/")), code
     end
 
-    return false
+    return false, code
   end)
 
   return cmd, err
diff --git a/kong/cli/services/serf.lua b/kong/cli/services/serf.lua
index a5dfcb3..bf98409 100644
--- a/kong/cli/services/serf.lua
+++ b/kong/cli/services/serf.lua
@@ -28,10 +28,10 @@ function Serf:_get_cmd()
   local cmd, err = Serf.super._get_cmd(self, {}, function(path)
     local res, code = IO.os_execute(path.." version")
     if code == 0 then
-      return res:match("^Serf v0.7.0")
+      return res:match("^Serf v0.7.0"), code
     end
 
-    return false
+    return false, code
   end)
 
   return cmd, err
```

What do you think?

**Comment by tecnobrat** [comment]
The core of this issue on AWS is that `Amazon Linux 2016.03 / kernel 4.4.5` doesn't work with a 386 compiled version of serf (due to the go bug).  If you use the x86 version it works fine. Of course the default RPM uses 386, so we're going to have to build our own or something.

Any possibility we can get arch specific builds of kong instead?

**Comment by deltheil** [comment]
It looks like with Kong 0.8.0 the 64-bit is now used by default (see [this](https://github.com/Mashape/kong-distributions/commit/f3148c2f7d86a7acccc68a860d4c7023ff30cbbb#diff-e232aafcaa4684178079337a7d27b68dR248)).

**Comment by tecnobrat** [comment]
@thefosk can you confirm this is how the actual 0.8.0 release was packaged?

**Comment by thefosk** [comment]
The 0.8.0 is packaged with serf 64-bit

**Comment by thibaultcha** [comment]
Closing this since the CLI has been refactored in 0.9. Will make sure of that while working on #1530.
