### ISSUE TITLE
Can support self-defined config variable in kong.yml?And how to use it in own plugin

### ISSUE THREAD

**Issue by luofanyuguai** [Mashape/kong#1101]
I want to develop  my own plugin, and the plugin need a redis address what I want to define it in the config file

**Comment by thibaultCha** [comment]
Plugin configuration should go in `schema.lua`, aka in the database. You can use default values and allow for customization. The config file is meant for properties to configure the actual node itself, not plugins running in a cluster.

**Comment by luofanyuguai** [comment]
I know this. But the situation what I worry about is  that when I will change the address  , I have to change all api-plugin‘s config , think about there are 10,000 api related this plugin. This may be a problem
