### ISSUE TITLE
Proxy by "startwith" request_path

### ISSUE THREAD

**Issue by kalinchih** [Mashape/kong#1102]
Hi,

Can Kong support route by "startwith" request_path?
For example 1, /order.* routes to http://order.myapi.com with strip_request_path.
  - http://mykong.com/order.retail('id') routes to http://order.myapi.com/order.retail('id')
  - http://mykong.com/order.xsp('id') routes to http://order.myapi.com/order.xsp('id')
  
Example 2, /accounts.* routes to http://account.myapi.com, but the accounts.account('id').email routes to http://email.myapi.com
  - http://mykong.com/accounts.account('id') routes to http://account.myapi.com/accounts.account('id')
  - http://mykong.com/accounts.account('id').email routes to http://email.myapi.com/accounts.account('id').email

thanks,
Kalin

**Comment by thefosk** [comment]
@kalinchih not at the moment, but we plan to support it. Related to #369, so closing this as a duplicate.
