### ISSUE TITLE
i m installing cassandra on ubuntu 14.04 bt when m coming to ~/cassandra/bin/cqlsh this its show this error in comment  plzz give me solution for it. its urgent

### ISSUE THREAD

**Issue by DineshDhokale** [Mashape/kong#1110]
Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})

**Comment by thefosk** [comment]
The Cassandra server is not reachable. 

For production critical usages we would recommend signing up to one of our Enterprise plans with 24/7 support: https://getkong.org/enterprise/

**Comment by DineshDhokale** [comment]
so how to solve this problem plzz give me the solution on it......
i have to installed cassandra bcoz of my practicalss

**Comment by thefosk** [comment]
Either Cassandra is not running, or it's not reachable in your network. If you don't want to use Cassandra you could also try Instacluster for Cassandra in the cloud: http://www.instaclustr.com/solutions/kong/

You can also try to play with 0.8.0 RC1 which introduces PostgreSQL support, although the documentation has not been pushed online yet (read the configuration file to learn how to configure it): https://github.com/Mashape/kong/releases/tag/0.8.0rc1
