### ISSUE TITLE
Will Kong support web-service in the future?

### ISSUE THREAD

**Issue by 85022134** [Mashape/kong#1111]
As we know， Kong only support restful ad backend service at present, will Kong support web-service in the future? 
@nikz @jerodsanto @mars @rafael

**Comment by thefosk** [comment]
It *could* support SOAP web services in the future, but it's not in the near roadmap.

**Comment by avidyalalala** [comment]
@thefosk I wonder if I can write a plugin to support invoking thrift service? Is there any clue or related example?

**Comment by thefosk** [comment]
For writing plugins the best references are the [lua-nginx-module](https://github.com/openresty/lua-nginx-module#table-of-contents) documentation and the [Kong plugin development guide](https://getkong.org/docs/0.7.x/plugin-development/).
