### ISSUE TITLE
Issue with install

### ISSUE THREAD

**Issue by amolc** [Mashape/kong#1122]
Hello Guys,

Please can you help us with the install issue on centos 7

[INFO] Kong 0.7.0
[INFO] Using configuration: /etc/kong/kong.yml
/usr/local/bin/luajit: did not find expected <document start> at document: 1, line: 166, column: 1

stack traceback:
	[C]: in function 'load'
	/usr/local/share/lua/5.1/kong/tools/config_loader.lua:151: in function 'load_default'
	/usr/local/share/lua/5.1/kong/cli/cmds/start.lua:19: in main chunk
	[C]: in function 'require'
	/usr/local/lib/luarocks/rocks/kong/0.7.0-0/bin/kong:55: in main chunk
	[C]: at 0x00404a80

**Comment by Tieske** [comment]
That seems to be an error message from the yaml parser. Please check the config, and make sure it is a valid yaml file.

**Comment by amolc** [comment]
Hello,

It looks to have an issue with the hadoop connected. 

Can you help us with a default.yml . At the moment, it doesn't work and it is hard for us to know the issue to connect to a brand new hadoop installation.

**Comment by thefosk** [comment]
Since this issue is not Kong related, I will close it.
