### ISSUE TITLE
how to pass query parameters to apis in kong

### ISSUE THREAD

**Issue by gopirajum** [Mashape/kong#1123]
Hello Guys,
I don't have any idea how to pass query string to an API in kong. Below is my API code.

curl -i -X POST   --url http://localhost:8001/apis/   \
--data 'name=oauth'   \
--data 'upstream_url=http://localhost:3000/auth'   \
--data 'request_host=localhost.in' 

it's successfully created in kong, but this api is required "email" and "ip_address" as a query strings, How can I send query strings to this api? for this following way I tried

curl -i -X GET   --url http://localhost:8000/  \
--header 'Host: localhost.in'
--data "config.add.querystring=email: 'gdsdssdsdm@gmail.com'&ip_address='127.0.0.1'"

but I am getting "Missing parameters email and ip_address"  error.

could anyone please help me.

**Comment by BrianHutchison** [comment]
Have you tried:

curl -i -X GET --url http://localhost:8000/?email=gds@gmail.com'&ip_address='127.0.0.1' \
--header 'Host: localhost.in'

**Comment by Tieske** [comment]
assumed to be resolved. Closing this.

**Comment by bluedrayco** [comment]
excuse me , i have a problem using kong refering the query params, i sent this url:

http://10.0.1.187:8889/api/v1/centro?filter=lower(centro.nombre) like '%mich%' but i cant receive % in my backend, how can i receive this value using kong?
