### ISSUE TITLE
Achieve simple RBAC via passing ACL group names in a header

### ISSUE THREAD

**Issue by joelfire** [Mashape/kong#1124]
There have been existing requests for RBAC. A simple approach (not sure how scalable it would be) would be to add an optional new header that lists the groups assigned to the user that also are allowed by the ACL.

For example User 'thurston' has groups (sonic-youth, sonic-admin, venom-user)
sonic API allows (sonic-youth, sonic-admin)

Upon authentication, there is a new header:

`x-consumer-groups: "sonic-youth, sonic-admin" `

So I now know thurston has these roles.

**Comment by thefosk** [comment]
This has been implemented with https://github.com/Mashape/kong/pull/1154
