### ISSUE TITLE
Kong listen on different port

### ISSUE THREAD

**Issue by bwoodring** [Mashape/kong#1127]
Following the configuration instructions(https://getkong.org/docs/0.6.x/configuration/). I am attempting to have kong listen on port 80 instead of 8000, but I get the below error. Is there another config file that needs to be updated? I updated /etc/kong/kong.yml and /usr/local/kong/nginx.conf
proxy_listen: "0.0.0.0:80"

server {
    server_name _;
    listen 0.0.0.0:80;
    listen 0.0.0.0:8443 ssl;

`kong start -c /etc/kong/kong.yml
[INFO] Kong 0.6.1
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] database...........cassandra keyspace=kong ssl=verify=false enabled=false replication_factor=1 contact_points=127.0.0.1:9042 replication_strategy=SimpleStrategy timeout=5000 data_centers=
[INFO] dnsmasq............address=127.0.0.1:8053 dnsmasq=true port=8053
[INFO] Leaving cluster..
[ERR] nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:2nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
[ERR] Could not start Kong`

**Comment by BrianHutchison** [comment]
Any port below 1024 are privileged and you'll need to run the kong start command as root or use sudo ("sudo kong start -c ....").

**Comment by bwoodring** [comment]
How is that done when you get command not found when running at root or sudo?
kong start -c /etc/kong/kong.yml
bash: kong: command not found
