### ISSUE TITLE
Error when changing dns & cassandra settings in config

### ISSUE THREAD

**Issue by rileylark** [Mashape/kong#1128]
I need to use my own dns server instead of dnsmasq, so I set the following config file:

    dns_resolver: server
    dns_resolvers_available:
      server:
        address: "10.0.0.10:53"
    cassandra:
      contact_points:
        - "cassandra.default:9042"

This file seems to cause an unrelated bug. I get an error report on STDOUT, but errors.log is empty and kong exits with exit code zero and no further notice :(  Here's the full output:

```
[INFO] Kong 0.7.0
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........cassandra keyspace=kong ssl=verify=false enabled=false replication_factor=1 contact_points=cassandra.default:9042 replication_strategy=SimpleStrategy timeout=5000 data_centers=
[INFO] serf ..............-profile=wan -rpc-addr=127.0.0.1:7373 -event-handler=member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf_event.sh -bind=0.0.0.0:7946 -node=kong-3591152686-iqc78_0.0.0.0:7946 -log-level=err
[INFO] Trying to auto-join Kong nodes, please wait..
[WARN] Cannot join 10.0.1.4:7946. If the node does not exist anymore it will be automatically purged.
[INFO] Successfully auto-joined 10.0.2.3:7946
/usr/local/bin/luajit: /usr/local/share/lua/5.1/kong/cli/services/nginx.lua:101: attempt to index local 'nginx_config' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/kong/cli/services/nginx.lua:101: in function 'prepare_nginx_configuration'
	/usr/local/share/lua/5.1/kong/cli/services/nginx.lua:148: in function 'prepare'
	/usr/local/share/lua/5.1/kong/cli/utils/services.lua:140: in function 'start_all'
	/usr/local/share/lua/5.1/kong/cli/cmds/start.lua:30: in main chunk
	[C]: in function 'require'
	/usr/local/lib/luarocks/rocks/kong/0.7.0-0/bin/kong:55: in main chunk
	[C]: at 0x00404e10
[INFO] Auto-generating the default SSL certificate and key...
```

I don't know if this means that my config file is invalid somehow. I'm at a bit of a dead end for progressing any further with my setup.  I thin knext I will start trying to find the lua source in the stack trace. Please let me know if I can help track this down with any other info!

**Comment by rileylark** [comment]
On the advice of @thibaultCha , I supplied a value for `nginx` in the config file, copying the default value from the documentation. Here's the updated kong.yml:

https://gist.github.com/rileylark/488d361eee754a4bbfc0f0470a53f627

Unfortunately, I get the exact same stacktrace :(

**Comment by thibaultCha** [comment]
Correct value: https://github.com/Mashape/kong/blob/0.7.0/kong.yml#L166 (the website is invalid)

**Comment by rileylark** [comment]
Thanks @thibaultCha for helping me work around this issue! I guess the bug(?) is that `nginx` is a required value for the config file, exacerbated by a bad listing for the default value on the website. Shall I close this issue or leave it open to mark the problem?

**Comment by KrishnaPG** [comment]
Facing the same problem. What was the solution. I copy|pasted the `kong.yml` section from the above link, but to no avail. The server just starts and crashes without any info

**Comment by pulyaevskiy** [comment]
The solution is to use `kong.yml` provided in the root of this repository as a template (`nginx` section is required, but it's not stated anywhere in the docs).

**Comment by incubus8** [comment]
any idea on how to make it work with Nginx and Kong. Hope someone can help me here

I got the following traceback:

```
⇒  kong restart -c kong.yml
[INFO] Using configuration: kong.yml
[INFO] Leaving cluster..
[INFO] kong 0.8.3
[INFO] Using configuration: kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........postgres host=127.0.0.1 database=kong user=angel password= port=5432
[INFO] dnsmasq............address=127.0.0.1:8053 dnsmasq=true port=8053
[INFO] serf ..............-profile=wan -rpc-addr=127.0.0.1:7373 -event-handler=member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf_event.sh -bind=0.0.0.0:7946 -node=Rhezas-MacBook-Air.local_0.0.0.0:7946_0446e7129dad4c58a08489d671c47e3d -log-level=err
[INFO] Trying to auto-join Kong nodes, please wait..
[INFO] No other Kong nodes were found in the cluster
luajit: /usr/local/share/lua/5.1/kong/cli/services/nginx.lua:101: attempt to index local 'nginx_config' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/kong/cli/services/nginx.lua:101: in function 'prepare_nginx_configuration'
	/usr/local/share/lua/5.1/kong/cli/services/nginx.lua:148: in function 'prepare'
	/usr/local/share/lua/5.1/kong/cli/utils/services.lua:131: in function 'start_all'
	/usr/local/share/lua/5.1/kong/cli/cmds/start.lua:31: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/kong/cli/cmds/restart.lua:23: in main chunk
	[C]: in function 'require'
	/usr/local/bin/kong:54: in main chunk
	[C]: at 0x0100001730
```
