### ISSUE TITLE
CLI: support for reload

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#113]
Implementing support for [nginx reload](http://nginx.org/en/docs/beginners_guide.html#control) to reload nginx configuration without downtime. Required to support a specific class of Plugins, like the Nginx Plus plugin: `kong reload`.

A few notes on the `reload` functionality: nginx starts a new set of workers reloading the configuration, keeping the same `master` process alive. Every new incoming request will be forwarded to the new workers, and once the old workers have processed all the remaining requests nginx will automatically shut them down. This means there is no downtime.

**Comment by thibaultCha** [comment]
Sounds good. Should be pretty quick to do, I'll see next week too

**Comment by thibaultCha** [comment]
Is it supposed to reload the nginx.conf or also the kong.yml?

**Comment by thefosk** [comment]
It would be nice if it could reload `kong.yml`
