### ISSUE TITLE
Multiple routes per API

### ISSUE THREAD

**Issue by magic69** [Mashape/kong#1130]
Hello,

I'm using Kong version 0.7.0, I configured two API's, each pointing to a different upstream URLs:

The 1st API is using `request_path = /data/v1`
The 2nd API is using `request_path = /data/v1/test-api`

The problem: requests using "/data/v1/test-api are routed to the upstream for "/data/v1" and not to the upstream for "/data/v1/test-api".
If I change the req_path for "/data/v1/test-api" to "/data/v2/test-api" the request will be routed correctly.
We have an existing Kong running version 0.5.2 where this is working.

Any advice ?

Thanks in advance,
Ran.

**Comment by thefosk** [comment]
@magic69 I think this has been fixed with 0.8.0 - can you give it a try and let us know?

**Comment by thefosk** [comment]
Please re-open the issue if the problem persists.

**Comment by magic69** [comment]
I just installed the latest version(0.8.1), I can confirm this issue no longer exists.
Thanks !
