### ISSUE TITLE
Error installing on AWS: Can't find serf

### ISSUE THREAD

**Issue by cludden** [Mashape/kong#1131]
when launching kong
```bash
[ec2-user@ip-xxx-xx-xx-xx local]$ bin/kong start
[INFO] Kong 0.7.0
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........cassandra auth=password=<password> username=<username> timeout=5000 data_centers= password=<password> ssl=verify=false enabled=false contact_points=<contactpoints> replication_strategy=SimpleStrategy username=<username> replication_factor=1 keyspace=kong
[INFO] dnsmasq............address=127.0.0.1:8053 dnsmasq=true port=8053
[INFO] Leaving cluster..
[ERR] Can't find serf
[ERR] Could not start Kong
```
for what its worth, serf is located at `/usr/local/bin/serf`

**Comment by thefosk** [comment]
@cludden can you try to manually invoke serf:

```bash
$ /usr/local/bin/serf version
```

?

**Comment by cludden** [comment]
```bash
[ec2-user@ip-xxx-xx-xx-xx bin]$ serf version
Trace/breakpoint trap
```
is this an AWS issue?

**Comment by thefosk** [comment]
I think we found the problem, Kong is unable to check the version of Kong.

Can you try to manually download Serf and run the same command: https://www.serfdom.io/downloads.html

**Comment by cludden** [comment]
reinstalling seemed to work.. any idea if this is an error with the install process or AWS?

**Comment by thefosk** [comment]
@cludden did you install the 32 or 64 bit version?

**Comment by cludden** [comment]
64 bit

**Comment by thefosk** [comment]
@cludden just to confirm the error, if you try to download the 32 bit and execute it does it give you the same error?

**Comment by cludden** [comment]
when I install the 32-bit version off of Hashicorps page, i get the `Trace/breakpoint trap` error when attempting `serf version`

**Comment by cludden** [comment]
specifically, this version:
```
https://releases.hashicorp.com/serf/0.7.0/serf_0.7.0_openbsd_386.zip
```

**Comment by cludden** [comment]
sorry
https://releases.hashicorp.com/serf/0.7.0/serf_0.7.0_linux_386.zip

**Comment by thefosk** [comment]
@cludden perfect, thanks for confirming this. I have fixed this issue in the distribution packager, so it shouldn't show up anymore in the new versions.

**Comment by cludden** [comment]
Awesome, thanks @thefosk!
