### ISSUE TITLE
Postgres - Potential breaking change in database creation migration

### ISSUE THREAD

**Issue by chrisanderton** [Mashape/kong#1136]
@thefosk - 

#1105 introduced code to create the Postgres database if it doesn't exist.

The migration passes a `true` value into the `no_database` parameter of the Postgres query method - for some reason the query assumes a username and database of `postgres` - which doesn't always exist - this prevents startup of the cluster in cases where the username/db name of 'postgres' are not valid on the database server:

https://github.com/Mashape/kong/blob/release/0.8.0/kong/dao/postgres_db.lua#L128-L131

Perhaps auto creation should be a config setting to allow this to be skipped in cases where this assumption is invalid?

**Comment by thefosk** [comment]
@chrisanderton that is correct. I improve the implementation to first use the user that has been specified in the configuration, if it's not set I will check for the `postgres` user, otherwise the database needs to be manually created.

**Comment by thefosk** [comment]
By the way I tried to drop the `postgres` user, and I get the following message:

```
postgres=# drop user postgres;
ERROR:  cannot drop role postgres because it is required by the database system
```

So I am not sure it can even be removed at all.

**Comment by thibaultCha** [comment]
Pretty sure @chrisanderton is referring to the *database* here, which was one of the reason behind ne saying creating the database automatically might not be a good idea for Postgres, since its behavior is not the same as Cassandra.

**Comment by thefosk** [comment]
Okay the database auto-creation is not going to make it into 0.8.0, so I will close this issue for now.
