### ISSUE TITLE
Kong can't write access log?

### ISSUE THREAD

**Issue by jimmypk** [Mashape/kong#1137]
I am running Kong 0.7.0, don't use docker container. I want to check the access log, but can't see any log at /usr/local/kong/logs/access.log
Can Kong write access log?

**Comment by thefosk** [comment]
Did you enable the access logs with `access_log on;` in the `nginx` property in the Kong configuration file?

**Comment by jimmypk** [comment]
Currently access_log off. I have enabled it and it's working.
Thanks.
