### ISSUE TITLE
Why does Kong remove a part of request path?

### ISSUE THREAD

**Issue by jimmypk** [Mashape/kong#1138]
I set up my api through kong. But in some case, Kong remove a part of request path. Example:
`http://my-api.domain.com/user/static/`
=> Kong pass to my api with request path /user/static/ It's correct.

`http://my-api.domain.com/user?id=1&status=-update`
=> Kong pass to my api with request path ?id=1&status=-update . It's wrong, and my api can't route properly.

Why does Kong remove a part of request path? And how to configure Kong for this case.
Thanks.

**Comment by Tieske** [comment]
What does the relevant Kong configuration look like?

**Comment by jimmypk** [comment]
Sorry, I take some wrong configuration.
