### ISSUE TITLE
Time constant string comparison for JWT tokens

### ISSUE THREAD

**Issue by snyff** [Mashape/kong#1148]
Hey guys,

Not a huge deal but the verification of the signature for JWT tokens is not time constant. It may allow an attacker to bypass the signature using brute force (the attacker will probably need to be pretty close to the target).

./kong/plugins/jwt/jwt_parser.lua line 31:
   ["HS256"] = function(data, signature, key) return signature == alg_sign["HS256"](data, key) end

Keep up the awesome work.
Cheers,

**Comment by snyff** [comment]
You could probably use is_digest_equal from kong/plugins/hmac-auth/access.lua

**Comment by snyff** [comment]
Same issue in kong/plugins/basic-auth/access.lua:

 63   return credential.password == digest

**Comment by thibaultCha** [comment]
Actually strings in Lua (and LuaJIT) are interned. Thus, string comparison is time invariant. There might be an exception to this behavior for large strings, though I could not find any information on the subject.

**Comment by snyff** [comment]
TIL
