### ISSUE TITLE
Whitelisting paths/methods

### ISSUE THREAD

**Issue by dlecorfec** [Mashape/kong#1149]
I'd like to have granular path control, in order to whitelist some path and method combination.

Example:

Allow GET on /foo
Allow GET and POST on /bar
Deny everything else

It doesn't seem implemented by available plugins. Did I miss something or do I have to write my own plugin?

**Comment by sinzone** [comment]
waiting for the #505

**Comment by thefosk** [comment]
Closing as duplicate of #505.
