### ISSUE TITLE
Kong restart should not exit an error when trying to stop Kong

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#115]
There are two problems:

* When executing `kong restart`, if the PID file doesn't exist then don't exit the operation, just skip stopping it and start Kong again. Right now the `restart` operations exists without restarting Kong.

* In an edge case scenario the PID file exists, but the process doesn't exist. The CLI is trying to kill a PID that doesn't exist anymore and returns an error. Basically [this function](https://github.com/Mashape/kong/blob/master/src/cli/utils/signal.lua#L154) should check not only for the existence of the PID file, but also check that the PID is actually a running process.

**Comment by thibaultCha** [comment]
Describe how to replicate the edgecase scenario please.

**Comment by thibaultCha** [comment]
237e8fc50440371a1d97d32ec29efef797be9bdf for 1)

**Comment by thefosk** [comment]
for 2) Start Kong, manually kill the process with `kill -9 PID`, then `kong stop`.

**Comment by thibaultCha** [comment]
Why `kill -9 PID`? If one uses kill without being in such a rush, `kill PID` is enough to stop kong and also deletes the PID..........

**Comment by thefosk** [comment]
Use `kill -9` to simulate a crash. Kong should try to kill the PID but if the PID doesn't exist it should ignore the error.

**Comment by thibaultCha** [comment]
kill -9 doesn't kill the workers, there's nothing we can do. It's kinda silly at this point. users are grown up people...

**Comment by thefosk** [comment]
I wrote a mistake, I was using `pkill -9 nginx` which also kills the workers.

**Comment by thibaultCha** [comment]
#131
