### ISSUE TITLE
headers X-Forwarded-Host and X-Forwarded-Prefix not sent when proxying an API

### ISSUE THREAD

**Issue by Yatufo** [Mashape/kong#1150]
I have setup the latest docker https://github.com/Mashape/docker-kong/blob/0.7.0/Dockerfile

1. Setup an API

curl -i -X POST \
 --url http://localhost:8001/apis/ \
 --data 'name=myservice' \
 --data 'preserve_host=true' \
 --data 'strip_request_path=true' \
 --data 'upstream_url=http://myservice:6666' \
 --data 'request_path=/myapipath'

2. Call a method in the API

curl  -X POST 'localhost:8000/myapipath/account' \
  -H 'Content-Type: application/json' \
  -d '{"content": "content"}'

Expected result: all the headers should be sent and they should correspond with the POSTed values of the API.

Actual result:
Kong is not adding these two headers when forwarding to and api.
which causes this http://stackoverflow.com/questions/30584242/hateoas-paths-are-invalid-when-using-an-api-gateway-in-a-spring-boot-app issue.

Local solution:

I hard coded the values in the kong.yml based on https://getkong.org/docs/0.7.x/configuration/

proxy_set_header X-Forwarded-Host localhost:8000;
proxy_set_header X-Forwarded-Prefix /myapipath;

And then it works.

**Comment by mdan1eli** [comment]
Why not just use for the scenario a request transformer plugin to add headers?

**Comment by thefosk** [comment]
Will land in 0.8.1
