### ISSUE TITLE
ACL in requests transformation

### ISSUE THREAD

**Issue by yograterol** [Mashape/kong#1153]
Hi everyone,

We're implementing Kong for our microservices, [ACL](https://getkong.org/plugins/acl/) is a great plugin and I want to add the group of a [customer in the header](https://getkong.org/plugins/request-transformer/), but I don't find documentation about that.

**Comment by thefosk** [comment]
@yograterol this is currently missing, but that would be a great addition. I will implement it.

**Comment by yograterol** [comment]
Thank u very much!
