### ISSUE TITLE
How to modify a ACL group?

### ISSUE THREAD

**Issue by VivianSnow** [Mashape/kong#1156]
I know that we can crate a acl group like this:curl -X POST http://kong:8001/consumers/{consumer}/acls --data "group=group1";
But how to modify or delete the group?

**Comment by JnMik** [comment]
for deletion you would add ensure: "removed"
I don't think there is any "Modify" action implemented since there is only one property to the whole object (group).

**Comment by JnMik** [comment]
While using kongfig, you would  would add ensure: "removed" for deletion.

Something like : 
`
-
      username: "test"
      ensure: "present"
      credentials:
        - name: "key-auth"
          ensure: "present"
          attributes:
            key: "1234"
      acls:
        -
          ensure: "removed"
          group: "test"
`
I don't think there is any "Modify" action implemented since there is only one property to the whole object (group). 

I might be wrong tho !

**Comment by thefosk** [comment]
Have you tried using `PATCH` or `PUT`?
