### ISSUE TITLE
Quota for a group of consumers

### ISSUE THREAD

**Issue by noamelf** [Mashape/kong#1157]
Hi, I want to set a quota for a group of consumers. This should serve the purpose of having several different developers from the same the organization that will share a quota.
From the docs I gather that Kong doesn't support this option yet, so I think about implementing it myself. 

How would you recommend to go about that? The closest thing I saw that group consumers is the ACL plugin. Is building upon the logic in the ACL plugin code sounds like the right way to go?

**Comment by thefosk** [comment]
You would need to update both the ACL plugin, to set a context variable that shares the group to other plugins, like `ngx.ctx.acl_group=something` and then update the rate-limiting plugin to use this group name as the primary identifier.

**Comment by mgazanayi** [comment]
Just a question about this, is there any development about this feature?
