### ISSUE TITLE
Encoded payload  exceeds the limit of 512 bytes warning

### ISSUE THREAD

**Issue by JnMik** [Mashape/kong#1158]
Hello guys ! 

While configuring kong, if I receive this in my logs :

`
Encoded payload is XXX and it exceeds the limit of 512 bytes!"
`

Should I consider this as a warning, and expect that kong will process my confing with chunks so it works as expected ?
Or should I expect failure on my system because the gateway might be missing some part of the configuration ? 

thx

**Comment by thefosk** [comment]
@JnMik what operation have you tried to execute, and what Kong version are you using?

**Comment by JnMik** [comment]
kong:0.6.1

operation : Trying to push an API (with 4 plugins) via kongfig application, using yml configuration file.
Something like that : http://screencast.com/t/atVV1ZYw

**Comment by JnMik** [comment]
I see you guys are already at 0.8, might worth updating before asking.. lol
Have you change anything regarding payload in the new updates ?

**Comment by thefosk** [comment]
@JnMik yes, I believe your problem has already been fixed in 0.7.0 but if you wait a little bit you will be able to upgrade to 0.8.0

**Comment by JnMik** [comment]
Alright I'll to check with 0.8 when it goes out

**Comment by JnMik** [comment]
Well I have pull the master and build the docker image locally, seems to be still working well with kongfig :) And my original issue seems to be fixed as well ! 

Good news.

@thefosk The only thing I saw was that warning msg in the kong container logs

kong | 2016/04/15 17:52:34 [emerg] 125#0: invalid number of arguments in "user" directive in /usr/local/kong/nginx.conf:2

(I do have updated my kong.yml format with the master's one)

I'll close my issue since this is another problem, feel free to investigate or create another issue if you think is it worth it, that doesn't seem to break the application and it might also only be on my VM.
This is the declaration in my kong.yml : http://screencast.com/t/9kM7X2dg

**Comment by thefosk** [comment]
Would you be able to paste the contents of `/usr/local/kong/nginx.conf`?
