### ISSUE TITLE
resolver.lua:58 https 443 as default port

### ISSUE THREAD

**Issue by hnaqvi** [Mashape/kong#1167]
a default port "443" is added to the upstream_hostname if the upstream url is a https request. Why is this being done?. Should this not be empty?

**Comment by thefosk** [comment]
That is correct - it makes the default port explicit. Are you experiencing any issue?

**Comment by hnaqvi** [comment]
an api I am trying to proxy is blocking this. The upstream API is throwing a 503 if a port is added to the host header of the request. The upstream api is a third party api and thus not in our control

**Comment by hnaqvi** [comment]
The issue is resolved by the thirdparty api.
