### ISSUE TITLE
Kong DEB Package fails to start when using Cassandra with authentication

### ISSUE THREAD

**Issue by allisthere2love** [Mashape/kong#1168]
When I run Kong 0.8.0 with a Cassandra using authentication, the following error occurs:

[ERR] Host at 10.166.69.238:39044 required authentication but no auth provider was configured for session

The fix is already in the master repository, so it seems is a packaging problem only.
I've tried the trusty and jessie packages, both are lacking the following code in cassandra_db.lua:

 ``
   if options.username and options.password then
    conn_opts.auth = cassandra.auth.PlainTextProvider(options.username, options.password)
   end
``

**Comment by thefosk** [comment]
I think @thibaultCha already answered to this issue on IRC.
