### ISSUE TITLE
Setup API with same request_host and several request_path

### ISSUE THREAD

**Issue by flowdopip** [Mashape/kong#1173]
Hi,

I have an REST API and i want to set ratelimite per resource, like twitter does:

https://dev.twitter.com/rest/public/rate-limits

Furthermore in future i need to set this values by tenant! and my tenant identifier is on access token (JSON Web Tokens).

What is the best setup for this?

something like this 

Tenant   |      Resource        |    Request (minute)
    1             GET Product           15
    1             GET Bag                 50
    2             GET Product            5
    2             GET Bag                 25

**Comment by thefosk** [comment]
Related to the implementation of #505 - closing this as dup.
