### ISSUE TITLE
how to set up 2 different endpoints for an API on a webserver level?

### ISSUE THREAD

**Issue by robertharm** [Mashape/kong#1176]
I tried to post the following question to the mailing list at https://groups.google.com/forum/#!forum/konglayer but unfortunately it always got deleted (I assume due to lots of (example) links?) - so I hope that it is ok to ask my question here...any help/hints would be appreciated!

----

Hi,

I set up a java application running at http://domain.com:2322/api?q= and would like to use the following 2 different endpoints which I can then add to kong with different rate limits:
https://domain.com/endpoint1/api?q=
https://domain.com/endpoint2/api?q=
Users should only be able to access those 2 endpoints - the access to http://domain.com:2322/api?q= will get blocked for users from the internet once the 2 endpoints are up and running.

Unfortunately we did not succeed with the needed configuration here yet. The server is running Debian 8/Apache 2.4 and my idea was to set up a transparent (or reverse?) proxy in order to configure those 2 endpoints on a webserver level, so that they can then be configured as kong endpoints (and forward any requests to one of those 2 endpoints to the main application which is running as one instance at http://domain.com:2322/api?q=)

Can anyone please point me into the right direction on how to approach this requirement? Is using mod_proxy the right approach here? Does anyone have a sample/similar configuration which we could use to build upon? We already asked several of our partners about how they would approach this requirement, but unfortunately no one could help here - so any input from members on this list would really be appreciated!
thx,
Robert

**Comment by thibaultCha** [comment]
As per my reply to your email on the mailing list, I am closing this issue so that further discussion can happen on the original thread at https://groups.google.com/forum/#!topic/konglayer/6gRk-gxHBl4
