### ISSUE TITLE
Cant get loggly integration working

### ISSUE THREAD

**Issue by shane-arkade** [Mashape/kong#1183]
I'm testing out Kong and trying to get the Loggly integration working for logging requests but I cant seem to get any logs coming through. I think its a bug given an error that appears in the nginx error log, but I'm hoping someone can help me at least identify if this is in fact a bug with Kong or if there is some mistake in the configuration.

I have Kong setup on a AWS from here: https://aws.amazon.com/marketplace/pp/B014GHERVU (0.7.0)

Ive setup the Loggly plugin as described here: https://getkong.org/plugins/loggly/

I haven't changed the configuration from the standard AWS setup, just setup my apis as per the docs.

No logs are getting through to Loggly, and i found this error in the nginx error log:
```
[error] 2728#0: lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/plugins/loggly/handler.lua:87: attempt to compare number with nil
stack traceback:
coroutine 0:
        /usr/local/share/lua/5.1/kong/plugins/loggly/handler.lua: in function </usr/local/share/lua/5.1/kong/plugins/loggly/handler.lua:86>, context: ngx.timer, client: XXXXXXXX, server: 0.0.0.0:8000
```

My Loggly plugin is setup as follows (replaced key with XXX):

```
{
      "api_id": "72e0da80-98e3-442c-9d0b-a7eeb7fde64b",
      "id": "a5412025-ef2f-4a40-9b3a-ad9fbfe76123",
      "created_at": 1461744329000,
      "enabled": true,
      "name": "loggly",
      "config": {
        "timeout": 10000,
        "host": "logs-01.loggly.com",
        "key": "XXXXXXXX",
        "log_level": "info",
        "successful_severity": "info",
        "tags": [
          "kong"
        ],
        "client_errors_severity": "info",
        "server_errors_severity": "info",
        "port": 514
      }
    }
```

I have Loggly working elsewhere so they key or Loggy setup shouldnt be an issue. Can anyone shed any light on what may be happening here?

**Comment by shashiranjan84** [comment]
Hi @shane-arkade , 

I will try to replicate it .

Thanks
Shashi

**Comment by shashiranjan84** [comment]
@shane-arkade Was the issue only with response having status b/w 400 to 500?

**Comment by shane-arkade** [comment]
Ah yes correct @shashiranjan84 it was on only on a 404 response. Although I still don't get any logs coming through for 200 or 404 etc.

**Comment by shashiranjan84** [comment]
I see the bug related to error. I am working on the fix. 

Do you have outgoing UDP port open on AWS instance?

**Comment by shane-arkade** [comment]
Yes Im pretty sure it should be, i've only restricted the admin port as per https://getkong.org/docs/0.8.x/network/ although outgoing is all open anyway.

**Comment by shashiranjan84** [comment]
Ok I already added the fix and would be released in next version 0.8.2. I will also try to test it in a  AWS environment to make sure it works.

https://github.com/Mashape/kong/tree/fix/loggly

**Comment by shane-arkade** [comment]
Thanks so much @shashiranjan84 for your help with this. 

Will the AWS marketplace AMI be updated to 0.8.2 along with the release? Or is it best to upgrade Kong myself? If so can you point me in the right direction for upgrading the AMI to 0.8.x?

Im also not clear if this fix will solve my general issue of logs not getting through to Loggly even for 200?

**Comment by shashiranjan84** [comment]
I am not sure what blocking your request to Loggly. I will try to test it.  

Regarding AMI, we create new AMI for every new version. But you can update you current AMI to new version.  Please follow the instruction to add Yum repo and update kong. 

1. download the repo file 
`wget https://bintray.com/mashape/kong-rpm-aws-0.8.x/rpm -O bintray-mashape-kong-rpm-aws-0.8.x.repo`

2.  move it to repo directory 
`sudo mv bintray-mashape-kong-rpm-aws-0.8.x.repo /etc/yum.repos.d/`

3. update Kong
`sudo yum update kong` (not sure about the command)

4. reload Kong
`kong reload`

**Comment by shane-arkade** [comment]
Great got Kong upgraded to 0.8.1 (and will upgrade to .2 when released)

If you are able to test Loggly with an AWS instance and confirm if it should work with a standard setup that would be greatly appreciated. Its really the only remaining feature we need before going ahead with Kong.

**Comment by shashiranjan84** [comment]
Ok I just tested Loggly plugin on AWS instance and it worked fine for me. You can search for tag 'kong' in the loggly dashboard.

<img width="898" alt="screenshot 2016-04-27 21 08 07" src="https://cloud.githubusercontent.com/assets/8146958/14875138/4b932276-0cbc-11e6-9fbc-883bd1679e14.png">

**Comment by shane-arkade** [comment]
Thanks @shashiranjan84 for your help and fixing that bug. 

Ill keep investigating, sounds like it must be a setup issue on my end. Would you be able to share your api and plugin setup json so i can compare?

**Comment by shashiranjan84** [comment]
I added an API

curl -X POST ec2-52-91-222-52.compute-1.amazonaws.com:8001/apis/ --data "name=mockbin" --data "upstream_url=http://mockbin.org" --data "request_host=mockbin.com"

{  
   "data":[  
      {  
         "upstream_url":"http:\/\/mockbin.org",
         "id":"cae2d9d8-a58d-4017-947c-e7a8ff353a61",
         "name":"mockbin",
         "created_at":1461816387000,
         "request_host":"mockbin.com"
      }
   ],
   "total":1
}

and then enabled Loggly plugin

curl -X POST ec2-54-85-160-68.compute-1.amazonaws.com:8001/apis/mockbin/plugins     --data "name=loggly"     --data "config.key=xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

{  
   "data":[  
      {  
         "api_id":"cae2d9d8-a58d-4017-947c-e7a8ff353a61",
         "id":"4093cf98-529b-46f9-b021-462c76073900",
         "created_at":1461816412000,
         "enabled":true,
         "name":"loggly",
         "config":{  
            "timeout":10000,
            "host":"logs-01.loggly.com",
            "key":"xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            "log_level":"info",
            "successful_severity":"info",
            "tags":[  
               "kong"
            ],
            "client_errors_severity":"info",
            "server_errors_severity":"info",
            "port":514
         }
      }
   ],
   "total":1
}

**Comment by shashiranjan84** [comment]
And if you want to fix error in current version just update the content of the file on your kong instance
`/usr/local/share/lua/5.1/kong/plugins/loggly/handler.lua` with

https://github.com/Mashape/kong/blob/fix/loggly/kong/plugins/loggly/handler.lua

**Comment by shane-arkade** [comment]
Thanks @shashiranjan84, you have been extremely helpful :) 

Closing this issue but will comment if i find anything relevant.
