### ISSUE TITLE
Question: Extra Nginx config not read from kong.yml?

### ISSUE THREAD

**Issue by TomSta** [Mashape/kong#1185]
Maybe I'm not doing it right, but from what I understood I could use nginx config block in kong.yml to add new sites to be served. Is this possible or I'm understanding it wrong and instead of trying to push stuff inside kong I should just link it with standalone nginx container? I'm using kong with docker, I've tried to add server just below the http clause, but it seems that it's not being read/working. I tried same config on pure nginx container and it works well... I point the service1.local on my host to docker ip, reload kong config and exposed ports on docker...

  http {
 
    server {
      listen 80;
      server_name service1.local;

      location / {
      	 root /usr/share/nginx/html/service1;
         index index.html;
      }

      location /nginx_status {
        internal;
        access_log off;
        stub_status;
      }

      location /robots.txt {
        return 200 'User-agent: *\nDisallow: /';
      }
    }

**Comment by thefosk** [comment]
This works locally so maybe Docker is not picking up your updated `kong.yml` file?

**Comment by Tieske** [comment]
@TomSta did you get this going? Can it be closed?

**Comment by thibaultCha** [comment]
Considering this answered.
