### ISSUE TITLE
Mutual Authentication security

### ISSUE THREAD

**Issue by ISMAELMARTINEZ** [Mashape/kong#1194]
Hi,

It will be great if we can have a mutual authentication (or client-base certificate) security plugin.

I think that will be a great plugin to have more if the "truststore" can be reloaded with new entries.

We are working with IoT devices that we register to a truststore so we can have mutual authentication, but Java keystore stuff is a pain and do require refreshing the SSL connector at least to get the new public certificates from clients (not ideal as you don't want to be messing with connections when devices are sending data)

Thanks!

**Comment by thibaultCha** [comment]
Why not using the `ssl_client_certificate` directive of Nginx? I'm not sure about the feasibility, nor even the behavior of this made as a plugin.

**Comment by ISMAELMARTINEZ** [comment]
Hi @thibaultCha, 

Our current problem is that we are registering devices to the truststore and every time this happen we need to restart the SSLConnector (this is using tomcat & Java keystore) and that is not desirable (to use nice words).

This process is basically a call to an end point that allow devices to do that sign in or registration process. We deal with the authorisation using other methods internally but that allow us to communicate using mutual authentication for the rest of the calls.

I am looking to move this implementation either to nginx on its own (adding a small nodejs or similar to it) or to kong, that I can see is base in nginx and can give us extra functionality.

I know nginx can listen for changes in the configuration (using reload) so we will not be restarting the connector.

If this could be useful for other people, I am happy to help with the development but my experience in LUA is 0. Happy to learn and looks a pretty interesting scripting language.

Thanks

**Comment by DonMartin76** [comment]
Isn't what would be appropriate this: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_certificate ?

**Comment by ISMAELMARTINEZ** [comment]
Hi @DonMartin76 ,

I end up implementing a simple server that does our logic. You can close this as is fairly specific to our needs. 

We are doing something similar to the key authentication
https://getkong.org/plugins/key-authentication/
but with certificates and creating users in our system.

Thanks in any case.

**Comment by amramtamir** [comment]
Hi @ISMAELMARTINEZ 
Can you elaborate on how did you implemented the Mutual Auth , As I have the same need and wondering if there is an easy way to achieve it.

Thanks

**Comment by ISMAELMARTINEZ** [comment]
Hi @amramtamir,

I ended up creating a GO program to do the "registration" process and using stunnel to deal with the certificates. 

So I don't think I can help much on this.
