### ISSUE TITLE
feat(plugins/log-serializers/infuxdb)

### ISSUE THREAD

**Issue by WALL-E** [Mashape/kong#1203]
I want to use infuxdb store log, then I can use Grafana, She is so beautiful.

Does anyone else have this need?

**Comment by sinzone** [comment]
usually they do something similar but with the ELK stack via one of our logs plugins.

**Comment by WALL-E** [comment]
ELK is a little too complicated, Maintenance costs are relatively high.
I’ve been working with InfluxDB + Grafana recently, much cooler, much more flexible.

kong is  easy to support infuxdb, only need to implement a serializers function.
because infuxdb use Restful-API to import data and kong's http-log is available.


usage should look like this
```
local infuxdb_serializer = require "kong.plugins.log-serializers.infuxdb".

-- more --

function HttpLogHandler:log(conf)
  HttpLogHandler.super.log(self)

  local message = infuxdb_serializer.serialize(ngx)
  local ok, err = ngx.timer.at(0, log, conf, message)
  if not ok then
    ngx.log(ngx.ERR, "[http-log] failed to create timer: ", err)
  end
end
```

Did I miss something？

**Comment by Tieske** [comment]
Contributions are welcome :smile: 

for code-reuse something like this should work;
refactor http-log slightly; factor out the serialization code from the `log` method, and replace ID's (eg. all error messages now have a hardcoded plugin name) to be configurable as properties.

From there you can `extend` the http-log object and update the properties and replace the serialization function.

A quicker route would be to just copy the http-log plugin and modify the serialization and hardcoded elements only.

**Comment by Tieske** [comment]
Refactor part is done, see #1206. You can now simply create your own body format from here.

**Comment by WALL-E** [comment]
infuxdb-log is done, see [#1214](https://github.com/Mashape/kong/pull/1214)
