### ISSUE TITLE
Unable to use the request path "/"

### ISSUE THREAD

**Issue by mortensoby** [Mashape/kong#1204]
When I specify a request path which is just "/" as show here:
`curl -X POST -F "name=messageService" -F "upstream_url=http://10.0.2.2:8080" -F "request_path=/" "http://localhost:8001/apis/"`
I get the following message:
`{"request_path":"cannot be an empty path: '\/'"}`

**Comment by Tieske** [comment]
Well, that is not allowed. So what did you expect? either `request_path` or `request_host` is required. See https://getkong.org/docs/0.8.x/admin-api/#add-api

**Comment by jarl-dk** [comment]
@Tieske: What is not allowed? The curl snippet
```
curl -X POST -F "name=messageService" -F "upstream_url=http://10.0.2.2:8080" -F "request_path=/" "http://localhost:8001/apis/"
```
does provide the mandatory `request_path` attribute. The error message claims that it is empty, which is not true. It is set to `/`.

**Comment by Tieske** [comment]
Let me ping @thefosk or @thibaultCha, they probably know why this not allowed. My guess is that its based on multiple hosts and path combination to be resolved.

**Comment by thefosk** [comment]
I can't see why `/` wouldn't be allowed - @thibaultCha?

**Comment by jarl-dk** [comment]
Great this looks good.
