### ISSUE TITLE
Cannot use non-ascii characters in request_path

### ISSUE THREAD

**Issue by mortensoby** [Mashape/kong#1205]
When I use non-ascii characters in the request path as shown in the following snippet:
`curl -X POST -F "name=kødsalg" -F "upstream_url=http://10.0.2.2:8080" -F "request_path=/kødsalg" "http://localhost:8001/apis/"`
I get the following error:
`{"request_path":"must only contain alphanumeric and '., -, _, ~, \/' characters","name":"name must only contain alphanumeric and '., -, _, ~' characters"}`
The request path aught to allow all characters that are legal in URLs.
I'm using Kong 0.7.0

**Comment by Tieske** [comment]
define `legal` :smile: 

how about [rfc3986](http://tools.ietf.org/html/rfc3986), see section 2.

**Comment by jarl-dk** [comment]
@Tieske : RFC3986 is a good proposal for definition of "legal".
Now, the question is:

**How shall I configure Kong for URL paths that needs to url-encoded?**

Basically there seems to be to possible answers:

1. Kong handles the url-encoding, accepting character encodings like UTF-8.
1. The user must deal with the url-encoding.

If you see other options to achieve the goal, please share your solution.

However it seems like kong provide no way for a user to configure an API for characters that requires url-encoding.
The curl snippet (by OP)
```
curl -X POST -F "name=kødsalg" -F "upstream_url=http://10.0.2.2:8080" -F "request_path=/kødsalg" "http://localhost:8001/apis/"
```
assumes that kong will handle it, and fails.
We have also tried the following curl snippet (that assumes user deals with url-encoding):
```
curl -X POST -F "name=kødsalg" -F "upstream_url=http://10.0.2.2:8080" -F "request_path=/k%C3%B8dsalg" "http://localhost:8001/apis/"
```
But that also fails with
```
{"request_path":"must only contain alphanumeric and '., -, _, ~, \/' characters","name":"name must only contain alphanumeric and '., -, _, ~' characters"}
```

**Comment by Tieske** [comment]
Thx for the clarification @jarl-dk

**Comment by jarl-dk** [comment]
@Tieske: When considering a solution. My suggestion is to head for
> Kong handles the url-encoding, accepting character encodings like UTF-8.

**Comment by Tieske** [comment]
not sure here. I think Kong should accept urlencoded arguments, but not necessarily do the encoding. Encodings are hard. I don't think there is a way for Kong to handle all of them, so instead I think its better to not handle them at all. The user knows what he's intending to use, so he's most capable of doing the encoding.

So fields `request_path`, `request_host` and `upstream_url` should allow for urlencoded data imo.

**Comment by jarl-dk** [comment]
A related but not the same issue: How about i18n domain names then? https://en.wikipedia.org/wiki/Internationalized_domain_name
Should users also provided the encoded names in these cases there?

**Comment by Tieske** [comment]
Just pushed a fix for this ^^

It allows %-encoding in the request_path. Upstream_url was already allowed. For now I'm skipping the host part.

Note; this allows only for accepting the path, it will not normalize it nor normalize it when the resolver matches the incoming request uris.

**Comment by jarl-dk** [comment]
Any milestone on this issue?

**Comment by Tieske** [comment]
will be in the next release. closing this.
