### ISSUE TITLE
Empty parameters not forwarded, blocker for me

### ISSUE THREAD

**Issue by JnMik** [Mashape/kong#1209]
We are using a third-party system API and we can lookup for data by searching for fields with empty values doing so :

&filters%5Bsome-field%5D%5Bconditional%5D=NOT_EQUAL_TO
&filters%5Bsome-field3%5D%5Bvalues%5D=

See that &filters[some-field][values] is passed but empty.

Our third-party receive the request like this :
```
"some-field": {
"conditional": "NOT_EQUAL_TO",
"values": ""
},

```

When using kong, our third party receive the request like this :
```
"some-field": {
"conditional": "NOT_EQUAL_TO"
},
```

Seems like the gateway don't feel the need to forward empty parameters, but there is a difference between an empty parameter and an undefined parameter.

Was that a known bug or an expected behavior ? 
I would really appreciate having this fixed but i've never done any Lua before.
Thx !

**Comment by thefosk** [comment]
I just pushed a fix for this.
