### ISSUE TITLE
Print a warning if not using LuaJIT

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#121]
We should print a warning when an instance is spawned and not using LuaJIT. Basically running on bare Lua will be very slow. Throwing some benchmarks: http://luajit.org/performance_x86.html

```lua
if jit then
  -- LuaJIT
else
  -- Not LuaJIT (slower)
end
```

@SGrondin I hope your benchmarks are using LuaJIT :p

**Comment by thefosk** [comment]
The warning can't be launched in the CLI because the CLI always uses the system Lua.
I have added a `lua_version` property at `127.0.0.1:8001/` that shows what version of Lua is being used by OpenResty.

The newer version of OpenResty are compiled by default always with LuaJIT.

**Comment by thibaultCha** [comment]
I never said the warning should be printed from the CLI. (The CLI can also use LuaJIT btw, it's my setting).
