### ISSUE TITLE
Proxy request based on dynamic lookup of remote_address header

### ISSUE THREAD

**Issue by rhasson** [Mashape/kong#1226]
Hi, 

I have a strange use case that I would like to understand if it can be supported with Kong.

I give my customers a certain url for accessing my api, for example, api.myco.com

Now I want to whitelist some customers to try a new version of the API.  I don't want to give them a new url but rather handle the translation in the backend.  In this example, customer1 has been whitelisted.  When they send a request to api.myco.com, Kong will look up their IP address in a DB such as Redis, DynamoDB, etc. to verify whether their IP has been whitelisted.  If it returns true, the request will be forwarded to api.myco.com/v2 or to a different url based on the returned response from the DB lookup.

I know it may not be very performant, nor the best approach, but I'm limited by the clients ability to change their software to point to new urls when being whitelisted for new features.

If this doesn't exist today, is it possible to enable this via a Kong plugin ?

Thanks,
Roy

**Comment by thefosk** [comment]
@rhasson have you tried to use the [ACL plugin](https://getkong.org/plugins/acl/)?

**Comment by rhasson** [comment]
So I looked at the ACL plugin and it will append a X-Consumer-Groups header with the group I've associated to a particular consumer (the API caller) based on API key or some other authentication method.  Now my challenge is how do I make a routing decision based on that header?

For example, if the header contains X-Consumer-Groups=new_feature then proxy the request to api.upstream.com/v2 instead of the original api.upstream.com/v1

Thanks,
Roy

**Comment by thefosk** [comment]
I got it now, I see what you are trying to do. Currently there is no way to routing the request to different upstream URLs based on rules like that.

**Comment by rhasson** [comment]
Thank you for the feedback
