### ISSUE TITLE
kong' s api  rule with both request_host and request_path at the same time,it works?

### ISSUE THREAD

**Issue by luofanyuguai** [Mashape/kong#1230]
indeed ,many time our api gateway may serve multi domain and one domain with multi path which one path  need different  plugin to do something

**Comment by chicoandrade** [comment]
Hi @luofanyuguai , It doesn't work.
It got answered on the issue https://github.com/Mashape/kong/issues/1056 when I asked about strip_request_path with request_host:

> This is currently expected, since request_host has the priority over request_path when routing a request. strip_request_path is only triggered when routing happens with the request_path. ...

**Comment by luofanyuguai** [comment]
in future, can support?

**Comment by Tieske** [comment]
@luofanyuguai 

if you provide both a `request_host` and a `request_path` then Kong will first try and resolve on the hostname, if it fails, it will match on the request_path.

So configure these apis;

1. `request_host=domain1.com`, no request path
2. `request_host=domain2.com`, `request_path=/path2/`
3. `request_path=/path3/`, no request_host

These will the matches be;

- `http://domain1.com/whateverthepath/`  --> 1, on request_host
- `http://domain2.com/whateverthepath/`  --> 2, on request_host
- `http://somedomain.com/path2/  --> 2, on request_path
- `http://somedomain.com/path3/  --> 3, on request_path

Each of the above 3 configurations can get their own plugins. If you define consumers, then even each consumer can get their own plugins.

So I think you should be fine, but that depends on the details of your configuration. What @chicoandrade referred to is that the `strip_request_path`  setting will only be applied if the match in on request_path (so in the above 4 examples, only the last 2)

**Comment by thibaultCha** [comment]
Considering this answered.
