### ISSUE TITLE
Does LDAP plugin work?

### ISSUE THREAD

**Issue by harryparmar** [Mashape/kong#1231]
Hi thanks for adding LDAP authenication, I am having some difficulty getting it to work.

first i think in your documentation below hide_port should be ldap_port?
$ curl -X POST http://kong:8001/apis/{api}/plugins \
    --data "name=ldap-auth" \
    --data "config.hide_credentials=true" \
    --data "config.ldap_host=ldap.example.com" \
    --data "config.hide_port=398" \
    --data "config.base_dn=dc=example,dc=com" \
    --data "config.attribute=cn" \
    --data "config.cache_ttl=60" 

second I cant get this to work
Usage

In order to authenticate the user, client must set credentials in Proxy-Authorization or Authorization header in following format

credentials := [ldap | LDAP] base64(username:password)

do both username and password have to be encoded by for utility like https://www.base64encode.org/? I have tried i cant get it to work.

**Comment by shashiranjan84** [comment]
Yes it should be  `ldap_port`, we will update the document soon.

You can use any base64 encoding utility based on the language you coding.  Following is example from the integration test for LDAP

https://github.com/Mashape/kong/blob/master/spec/plugins/ldap-auth/access_spec.lua#L74

What error you getting?

**Comment by shashiranjan84** [comment]
@harryparmar were you able use the LDAP plugin?

**Comment by harryparmar** [comment]
I will give it try on Monday and get back to you.

**Comment by harryparmar** [comment]
@shashiranjan84 I just get message 

{
"message": "Unauthorized"
}

My header looks like this



 GET /SOME_API?TEST_PARAM=5302852545&CONTRACT=1234 HTTP/1.1
 HOST: ZEUSUSNESP:8000
 credentials: dGVzdDp0ZXN0


My LDAP settings are correct as I can use third party tool like LDAP Browser

**Comment by shashiranjan84** [comment]
Are you setting Authorization header?

in your it should be something like this

Authorization: LDAP dGVzdDp0ZXN0

**Comment by harryparmar** [comment]
@shashiranjan84 changing my header to look like this

GET /SOME_API?TEST_PARAM=5302852545&CONTRACT=1234 HTTP/1.1
HOST: ZEUSUSNESP:8000
Authorization: LDAP dGVzdDp0ZXN0

Now I receive this message-

{
"message": "Invalid authentication credentials"
}

**Comment by shashiranjan84** [comment]
Check the log for any msg from LDAP server. Also please post here your Plugin config. 

Also you follow this link https://github.com/Mashape/kong/blob/master/spec/plugins/ldap-auth/access_spec.lua#L75 <https://github.com/Mashape/kong/blob/master/spec/plugins/ldap-auth/access_spec.lua#L75>
as example.

**Comment by harryparmar** [comment]
error.log
The supplied credential is invalid.
Details: 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1^@,

Ldap plugin config, this is what i used below to set it up-
curl -X POST http://xxxx:8001/apis/TEST_API_3/plugins \
    --data "name=ldap-auth" \
    --data "config.hide_credentials=true" \
    --data "config.ldap_host=192.168.140.35" \
    --data "config.ldap_port=389" \
    --data "config.base_dn=dc=test-test,dc=com" \
    --data "config.attribute=cn" \
    --data "config.cache_ttl=60"

**Comment by harryparmar** [comment]
I am not sure if these are needed
--data "config.attribute=cn" \
--data "config.cache_ttl=60"

but your plugin does not install without them

**Comment by shashiranjan84** [comment]
`config.attribute` is required field. So basically if we authenticating bob here and its DN on ldap server is `cn=bob,dc=example,dc=com`

than `config.base_dn` would be `config.base_dn=dc=example,dc=com` and `config.attribute` would be `config.attribute=cn`. 

Let say bob’s password is `password`, so you request headers should have authentication header set as

Authentication: LDAP Ym9iOnBhc3N3b3Jk

**Comment by harryparmar** [comment]
I still got same error as before triggered on line 76 of 
https://github.com/Mashape/kong/blob/master/kong/plugins/ldap-auth/access.lua

**Comment by harryparmar** [comment]
in distinguisedName on AD i have it like this
distinguishedName: CN=TEST TEST,OU=Users,OU=New York,DC=test-test,DC=com


should i change plugin setting to include OU=Users,OU=New York?

**Comment by harryparmar** [comment]
@shashiranjan84 

i changed my setting to account for OU=Users, OU=New York

{
api_id: "d8d176b7-c0cf-4fe9-a6f6-2df452bc0be2",
id: "2c23e3fa-757b-41a2-9e8f-dc4070482d35",
created_at: 1464103177000,
enabled: true,
name: "ldap-auth",
config: {
base_dn: "OU=Users,OU=New York,DC=springer-sbm,DC=com",
cache_ttl: 60,
timeout: 10000,
start_tls: false,
hide_credentials: true,
ldap_host: "192.168.xxx.xx",
verify_ldap_host: false,
attribute: "cn",
keepalive: 60000,
ldap_port: 389
}
}

I still get 

{
"message": "Invalid authentication credentials"
}

**Comment by shashiranjan84** [comment]
What you setting in authentication header? Try ldapsearch command from bash to make sure you using correct DN. You may need to install it.

**Comment by harryparmar** [comment]
@shashiranjan84 

I installed ldapsearch and ran command from this page http://www.agix.com.au/ldapsearch-active-directory/
without problem

I also foundout my username format has to be like username@domain.com using ldap browser 4.5 and then using it successfuly on ldapsearch


But I am still getting same error from Kong Plugin

**Comment by shashiranjan84** [comment]
Please paste the cammand you ran and the authorization header value here.

**Comment by harryparmar** [comment]
ldapsearch \
    -x -h 192.168.xxx.xx \
    -D "test@test-test.com" \
    -W \
    -b "dc=test-test,dc=com" \
    -s sub "(cn=*)" cn mail sn

I got password prompt and I entered it and saw results

My authorization header is 

Authorization: LDAP dGVzdEB0ZXN0LXRlc3QuY29tOnBhc3N3b3Jk

**Comment by shashiranjan84** [comment]
What attribute defines test, is it uid, cn, sn ...? Is it possible for you
paste AD hierarchy for test here? You can use Apache Directory Studio.

What error do you see Kong log?

@shashiranjan84 <https://github.com/shashiranjan84>
ldapsearch \
-x -h 192.168.xxx.xx \
-D "test@test-test.com" \
-W \
-b "dc=test-test,dc=com" \
-s sub "(cn=*)" cn mail sn

I got password prompt and I entered it and saw results

My authorization header is

Authorization: LDAP dGVzdEB0ZXN0LXRlc3QuY29tOnBhc3N3b3Jk

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/Mashape/kong/issues/1231#issuecomment-221619231>

**Comment by harryparmar** [comment]
Is there way to PM you or email it? I am just replacing my user with Test when i am posting here..but i will send you real data in PM/email.

**Comment by shashiranjan84** [comment]
are you on Gitter?

https://gitter.im/Mashape/kong

**Comment by shashiranjan84** [comment]
@harryparmar where you able to use the plugin? I know ppl are able to use the plugin successfully as it is now. Please reopen the ticket if you have more questions.

**Comment by twneale** [comment]
@shashiranjan84 Is there a chance this method will only work on Active Directory services in anonymous bind is enabled? If not that might explain why some people can't get it to work (me included).

**Comment by shashiranjan84** [comment]
Plugin(LDAP client) does not care if anonymous bind is enabled or not as it never make anonymous bind request. It just encode a bind request using DN (base DN + attribute=<username from request> ) and Password and make a simple bind authentication call

**Comment by ArunParthiban10** [comment]
Could you please explain how to use a bindDN  (ldapsearch -D ) ?

**Comment by fabiorphp** [comment]
I have the same problem, in our case the attribute used is "sAMAccountName"

**Comment by shashiranjan84** [comment]
@fabiorphp  follow #1821 for debugging.

**Comment by sreejith824** [comment]
Is there an option to configure LDAP Connection password, something like,
{
"name" : "ldap-auth",
"config.hide_credentials" : "true",
"config.ldap_host" : "localhost",
"config.ldap_port" : "398",
"config.base_dn" : "cn=root",
"config.attribute" : "cn",
"config.cache_ttl" : "60",
**_"config.ldap_password" : "password"_**
}

**Comment by sreejith824** [comment]
2017/01/31 11:41:58 [error] 82#0: *2231 [lua] access.lua:42: ldap_authenticate(): [ldap-auth] failed to connect to localhost:398: connection refused, client: 192.xxx.xxx.xxx, server: kong, request: "GET / HTTP/1.1", host: "192.xxx.xxx.xxx:pppp"

**Comment by harryparmar** [comment]
I was able to get this to work by adding ou=Users,ou=New York to Base DN, your settings will differ based on your org and ldap setup. 
Also to login I use my first name and last name instead of username.

**Comment by jhdehart** [comment]
Sorry for commenting on an issue that his been closed for so long, but I didn't want to start a new thread because this is so high in the search results.

I'm running into the same problem when attempting to integrate Kong with active directory authentication.  It works, but requires the CN, which is a bit unwieldy.  Is there any way we could instead use the sAMAccountName?

**Comment by shashiranjan84** [comment]
@jhdehart  you can configure that using `config.attribute` but current implementation only authenticate user with fully qualified DN, there is a PR open make it more flexible https://github.com/Kong/kong/pull/3093 .

**Comment by jhdehart** [comment]
Great, thanks for the update!

**Comment by ajaisam** [comment]
Does anyone have any experience of not putting the ldap_password value in plain text? 
Trying to see if there is a way around this.

**Comment by Cerberussian** [comment]
I still had {"message":"Invalid authentication credentials"} error after all that is suggested here and my problem was wrong encoding (my personal encode alias added new line). Hope this will save someone's lose of hair and delay sanity decline for a day.

**Comment by al3x609** [comment]
I have the same problem, my ldap setup has bind_DN prior to user auth, help, Where I can set the bind_dn credentials for non anonymous user connection?

**Comment by wzxsydney** [comment]
> I still had {"message":"Invalid authentication credentials"} error after all that is suggested here and my problem was wrong encoding (my personal encode alias added new line). Hope this will save someone's lose of hair and delay sanity decline for a day.

oh man you saved my day! I have the exact same issue and I started to become superstitious. Thanks a lot!
