### ISSUE TITLE
JWT plugin doesn't migrate the algorithm column properly

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#1233]
When upgrading Kong to 0.8.x a new `algorithm` column is being added by the JWT plugin. If the user was already using the JWT plugin and already had data, the `algorithm` column is not being pre-populated with any value, which causes a null exception at runtime.

**Comment by t1tcrucible** [comment]
Just for information, we solved this during upgrade to Kong 8.1 executing the following statement on Cassandra node:
update jwt_secrets set algorithm = 'HS256' where id IN (90a5336f-a798-4799-b15a-9784a8bd2e06,...,522ffee5-79b3-4baa-b436-f257ef75e27c)

**Comment by thefosk** [comment]
This could be fixed by either migrating the older data, or by assuming the default algorithm to be `HS256` if it's missing in the entity retrieved by the datastore.

**Comment by chrisbaldauf** [comment]
@thefosk, I'm not sure what you mean when you say "migrating the older data". It looks like the `algorithm` column is added in the [2016-03-07-jwt-alg](https://github.com/Mashape/kong/blob/next/kong/plugins/jwt/migrations/cassandra.lua#L25) migration.

**Comment by thefosk** [comment]
@chrisbaldauf the column is added, but if the datastore already had some tokens created by a previous version of Kong, the `algorithm` column is not pre-populated with an algorithm value (which is now required).

**Comment by chrisbaldauf** [comment]
After re-reading, I now better understand the two options - set a default value in the database or assume one in code if the db value is null. Thanks for following up.
