### ISSUE TITLE
Path/Operation restriction plugin

### ISSUE THREAD

**Issue by cvrabie** [Mashape/kong#1234]
Idea: plugin that restricts access to a path and/or operation based on white and blacklists. 
Ideally the path definitions should allow wildcards.

Example config that **blocks** 
- DELETE operations on all paths
- all operations on paths starting with `/admin/` 
- POST, PUT and PATCH operations on exactly the path `/users`: 

```
"config" : {
  "blacklist": [
    { "operations": ["DELETE"] },
    { "path": "/admin/*" },
    { "path": "/users", "operations": ["POST", "PUT", "PATCH"] }
  ]
}
```

**Comment by Tieske** [comment]
The logic of this plugin would very much duplicate the core Kong logic of matching paths etc.

Considering the new router in 0.10, apis can be configured for each of the requested configurations. All that is needed is a way to block access (or stated other wise to make the selection negative), this is currently in the works in #2051 

closing this.
