### ISSUE TITLE
Resource Level Control - Authentication & Throttling

### ISSUE THREAD

**Issue by pradeepmurugesan** [Mashape/kong#1238]
Hi,

 We are planning to integrate Kong into our architechture and after some playing around with Kond admin apis, We have the following questions.

**1. Resource level Authentication**

I could see that the Admin API for adding an API contains request_path with the help of which I can add resources to my API. Will I be able to control the Authentication at Resource and HTTP Method of the resource level.

For Example.

Lets say My Api is Pradeep and I have 2 resources within that

/todo and /user

Scenario 1:

now I want to control the Oauth 2 authentication in such a way that 

POST to /user should not be checked for authentication since , Signup need not require any token

Other resources should be authenticated. 

Scenario 2:

With the OAuth in place I need the flexibility to use different token types like Client_Credetials (Application Token) , Password or Auth Code (User). This is required for the above same reason 

/user resource any HTTP method can be accessed only with the user context. So I should be able to say something like

/user POST, GET, PUT should be allowed only for token types (password, Auth code)

**2. Resource level Throttling**

same as the above I need to set the request limit for any Resource and HTTP method combination.

Kindly let us know the feasibility of the above with kong and its plugins.

If the above scenarios are in kong's road map please let us know. We are also open to desgin and contribute the same back to Mashape if you guys think it will be really a good addition.

Pradeep.

**Comment by Tieske** [comment]
Currently incoming requests are NOT matched based on the method (get/post/etc). It's a highly requested feature that we're planning to add.

As for throttling, please checkout the rate-limiting plugin.

**Comment by thibaultcha** [comment]
Considering this answered, thanks.
