### ISSUE TITLE
Getting 500 when updating an API (postgres)

### ISSUE THREAD

**Issue by mlucchini** [Mashape/kong#1239]
I'm using Kong 0.8.1.

_/usr/local/kong/logs/error.log_:

2016/05/23 13:14:22 [alert] 122#0: send() failed (90: Message too long)
2016/05/23 13:14:22 [error] 122#0: *125 lua coroutine: runtime error: /usr/local/share/lua/5.1/kong/dao/postgres_db.lua:98: table index is nil
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/dao/postgres_db.lua: in function 'parse_error'
	/usr/local/share/lua/5.1/kong/dao/postgres_db.lua:142: in function 'query'
	/usr/local/share/lua/5.1/kong/dao/postgres_db.lua:395: in function 'update'
	/usr/local/share/lua/5.1/kong/dao/dao.lua:264: in function 'update'
	/usr/local/share/lua/5.1/kong/api/crud_helpers.lua:135: in function 'put'
	/usr/local/share/lua/5.1/kong/api/routes/apis.lua:13: in function </usr/local/share/lua/5.1/kong/api/routes/apis.lua:12>

_The request is:_

PUT https://hostname:8001/apis
created_at: 1463758915000
id: "1927522c-c09d-47aa-ad3c-58aaa9433e05"
name: "API-Admin"
preserve_host: true
request_host: ""
request_path: "/api"
strip_request_path: true
upstream_url: "https://hostname:8001"

I'm pretty sure this has worked before though.

**Comment by Tieske** [comment]
I cannot reproduce this.

````
Mashapes-MacBook-Pro-2:kong thijs$ kong start -c kong_DEVELOPMENT.yml
[INFO] kong 0.8.1
[INFO] Using configuration: kong_DEVELOPMENT.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........postgres host=127.0.0.1 database=kong_development user=kong port=5432
[INFO] dnsmasq............address=127.0.0.1:8053 dnsmasq=true port=8053
[INFO] serf ..............-profile=local -rpc-addr=127.0.0.1:7373 -event-handler=member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf_event.sh -bind=0.0.0.0:7946 -node=Mashapes-MacBook-Pro-2.local_0.0.0.0:7946 -log-level=err
[INFO] Trying to auto-join Kong nodes, please wait..
[WARN] Cannot auto-join the cluster because no nodes were found
[WARN] ulimit is currently set to "2560". For better performance set it to at least "4096" using "ulimit -n"
[INFO] nginx .............admin_api_listen=0.0.0.0:8001 proxy_listen=0.0.0.0:8000 proxy_listen_ssl=0.0.0.0:8443
[OK] Started
Mashapes-MacBook-Pro-2:kong thijs$ http put http://localhost:8001/apis name=API-Admin preserve_host=true "request_path=/api" strip_request_path=true upstream_url=https://hostname:8001
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Mon, 30 May 2016 11:17:57 GMT
Server: kong/0.8.1
Transfer-Encoding: chunked

{
    "created_at": 1464607077000,
    "id": "512eea3b-49f8-4613-b2da-147d5c91d2ce",
    "name": "API-Admin",
    "preserve_host": true,
    "request_path": "/api",
    "strip_request_path": true,
    "upstream_url": "https://hostname:8001"
}

Mashapes-MacBook-Pro-2:kong thijs$
````

Also no errors in my log file.

**Comment by Tieske** [comment]
@mlucchini If you still encounter this error, then please checkout this commit; https://github.com/Mashape/kong/commit/c069ff449dfce0d3095142120d1be6e3b6b0810a

It should no longer explode in a Lua error, but return the underlying DB error postgres is reporting. That should provide a better hint as to what is wrong.

**Comment by mlucchini** [comment]
Cheers I'll try that

**Comment by thefosk** [comment]
This will be deployed in the next version. Please re-open if the issue persists.
