### ISSUE TITLE
OAuth2 Plugin + "request body in temp file"

### ISSUE THREAD

**Issue by ammmze** [Mashape/kong#1241]
We're running into an issue with the oauth2 plugin on kong (v0.8.1) causing a 500 error when our request body is relatively large. We get an error like this:

```
2016/05/24 01:56:29 [error] 118#0: *2223 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:106: requesty body in temp file not supported
stack traceback:
coroutine 0:
    [C]: in function 'get_post_args'
    /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:106: in function 'retrieve_parameters'
    /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:366: in function 'parse_access_token'
    /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:419: in function 'execute'
    /usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:12: in function 'access'
    /usr/local/share/lua/5.1/kong.lua:188: in function 'access'
    access_by_lua(nginx.conf:98):2: in function <access_by_lua(nginx.conf:98):1>
```

As a workaround, we found that we can set `client_body_buffer_size` in the nginx configuration so it doesn't write to a temporary file. Are there any other ways we can get this work rather than setting it to some arbitrary value and hope we don't ever get a request bigger than that?

It looks like its because it's trying to read the entire body to get oauth parameters. Perhaps it would be better to only do that if the request content type was one of the form data types?

**Comment by p0pr0ck5** [comment]
Going to close this, with 4c907bcd01531ee607eef545016ffeb931c68ab3 request body handling is now more easily configurable, allowing users to avoid buffering request bodies to disk. Thanks for the report!
