### ISSUE TITLE
Running kong in docker container, exit right after started

### ISSUE THREAD

**Issue by ericln** [Mashape/kong#1242]
We are trying to get a kong container up and running in my cluster, and when we were linking database (cassandra or postgres), the kong container can be started no problem. However, when we were using a `kong.yml` file, setting the desired connection to a AWS RDS (postgres) database, then we are getting the following in the docker log and container would exit right away.

any thought?

```
[INFO] kong 0.8.1
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........postgres (<database info>)
[INFO] dnsmasq............address=127.0.0.1:8053 dnsmasq=true port=8053
[INFO] serf ..............-profile=wan -rpc-addr=127.0.0.1:7373 -event-handler=member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf_event.sh -bind=0.0.0.0:7946 -node=08023c99d5d8_0.0.0.0:7946 -log-level=err
[INFO] Trying to auto-join Kong nodes, please wait..
[WARN] Cannot join 172.17.0.17:7946. If the node does not exist anymore it will be automatically purged.
[WARN] Could not join the existing cluster
[INFO] Auto-generating the default SSL certificate and key...
[INFO] nginx .............admin_api_listen=0.0.0.0:8001 proxy_listen=0.0.0.0:8000 proxy_listen_ssl=0.0.0.0:8443
[OK] Started
```

**Comment by thefosk** [comment]
When using a custom `kong.yml` file, you want to make sure the following property in the `nginx` configuration is set as `daemon off;`: https://github.com/Mashape/docker-kong/blob/master/config.docker/kong.yml#L13

**Comment by ericln** [comment]
right that worked, thanks
