### ISSUE TITLE
Kong behind dockercloud/haproxy - Problem with oauth2 plugin (ngx.var.scheme:lower() fails)

### ISSUE THREAD

**Issue by DonMartin76** [Mashape/kong#1246]
Hello,

I have a strange problem with my current setup here when using the oauth2 plugin. My setup is as follows: I am using kong inside docker, running without SSL. Using docker-compose, we are terminating the SSL connection using dockercloud/haproxy, also to be able to cluster Kong inside our docker environment.

Now, when using the oauth2 plugin and trying to retrieve a token from the (auto-generated) oauth2/token endpoint, Kong fails with a 500; when looking inside the `error.log`, I see the following error which puzzles me greatly:

```
2016/05/24 14:36:57 [error] 109#0: *45 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:92: attempt to call method 'lower' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua: in function 'is_https'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:254: in function 'issue_token'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:415: in function 'execute'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:12: in function 'access'
	/usr/local/share/lua/5.1/kong.lua:188: in function 'access'
	access_by_lua(nginx.conf:98):2: in function <access_by_lua(nginx.conf:98):1>, client: 93.216.233.16, server: _, request: "POST /petstore-oauth/oauth2/token HTTP/1.1", host: "my-correct-server.io", referrer: "https://my-correct-server.io/somepath"
2016/05/24 14:37:08 [error] 109#0: *85 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:92: attempt to call method 'lower' (a nil value)
```

The code which it says fails looks very innocent, inside `plugins/oauth2/access.lua`:

```lua
local HTTPS = "https"

local function is_https(conf)
  local result = ngx.var.scheme:lower() == HTTPS
  if not result and conf.accept_http_if_already_terminated then
    local forwarded_proto_header = ngx.req.get_headers()["x-forwarded-proto"]
    result = forwarded_proto_header and forwarded_proto_header:lower() == HTTPS
  end
  return result
end
```

Does anybody have an idea what might wreck the oauth2 call here? If I go directly inside the docker environment and issue the same call to the oauth2/token endpoint, except directly to the `http://kong:8000/petstore-oauth/oauth2/token` endpoint, passing the `X-Forwarded-Proto` header (which normally is added by haproxy) via `-H`, the call succeeds.

What is going wrong here? Which header might be causing Kong to be so confused when being proxied via HAproxy?

Best regards,
Martin

**Comment by thefosk** [comment]
Is HAproxy sending a valid HTTP request to Kong? It's really weird that `ngx.var.scheme` would be empty.

**Comment by DonMartin76** [comment]
I would assume so as other requests work. These do not use the oauth2 plugin though. Is there an easy way to switch on debugging messages or similar so that I can see comes into Kong?

**Comment by Tieske** [comment]
>  attempt to call method 'lower' (a nil value)

How to reproduce this error in Lua at all?

````
C:\luajit>luajit
LuaJIT 2.1.0-beta2 -- Copyright (C) 2005-2016 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> (nil):lower()
stdin:1: attempt to index a nil value
stack traceback:
        stdin:1: in main chunk
        [C]: at 0x00401ff0
> (1):lower()
stdin:1: attempt to index a number value
stack traceback:
        stdin:1: in main chunk
        [C]: at 0x00401ff0
> 
````

That would give us a hint as to what is causing it. It doesn't seem to be a regular Lua type.

**Comment by Tieske** [comment]
reproduced it, seems the type is not a string as expected, but an object.

**Comment by Tieske** [comment]
that is; reproduced the Lua error, not the OP problem :smile:

**Comment by DonMartin76** [comment]
This makes so much no sense, and I bet there's some kind of "aaah" moment around the corner. I added some debugging code into access.lua, and this is what gives:

```
2016/05/25 06:58:30 [] 8567#0: *104 [lua] access.lua:89: is_https(): http, client: 87.164.97.150, ser...
2016/05/25 06:58:30 [] 8567#0: *104 [lua] access.lua:90: is_https(): string, client: 87.164.97.150, server: _, requ...
2016/05/25 06:58:30 [] 8567#0: *104 [lua] access.lua:91: is_https(): https, client: 87.164.97.150, server: _, req...
2016/05/25 06:58:30 [error] 8567#0: *104 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:95: attempt to call method 'lower' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua: in function 'is_https'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:257: in function 'issue_token'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:418: in function 'execute'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:12: in function 'access'
	/usr/local/share/lua/5.1/kong.lua:188: in function 'access'
```

I changed `is_https` to the following:

```lua
local function is_https(conf)
  ngx.log(ngx.STDERR, ngx.var.scheme)
  ngx.log(ngx.STDERR, type(ngx.var.scheme))
  ngx.log(ngx.STDERR, HTTPS)
  local result = ngx.var.scheme and type(ngx.var.scheme) == "string" and ngx.var.scheme:lower() == HTTPS
  if not result and conf.accept_http_if_already_terminated then
    local forwarded_proto_header = ngx.req.get_headers()["x-forwarded-proto"]
    result = forwarded_proto_header and forwarded_proto_header:lower() == HTTPS
  end
  return result
end
```

Which means, the debugging outputs:

* `ngx.var.scheme=="http"` (as expected)
* `type(ngx.var.scheme)="string"` (as expected)
* `HTTPS="https"`(as expected)

Just the `if`does not work. I saw `lower()` is used all over the place, so that can't be wrong,... can it? What is happening here?

**Comment by Tieske** [comment]
can you try this code and see where it fails?

```lua
local function is_https(conf)
  ngx.log(ngx.STDERR, ngx.var.scheme)
  ngx.log(ngx.STDERR, type(ngx.var))              --> added
  ngx.log(ngx.STDERR, type(ngx.var.scheme))
  ngx.log(ngx.STDERR, HTTPS)
  local result = tostring(ngx.var.scheme):lower() == HTTPS     --> added
  local result = ngx.var.scheme and type(ngx.var.scheme) == "string" and (ngx.var.scheme):lower() == HTTPS   --> added
  local result = ngx.var.scheme and type(ngx.var.scheme) == "string" and ngx.var.scheme:lower() == HTTPS
  if not result and conf.accept_http_if_already_terminated then
    local forwarded_proto_header = ngx.req.get_headers()["x-forwarded-proto"]
    result = forwarded_proto_header and forwarded_proto_header:lower() == HTTPS
  end
  return result
end
````

**Comment by DonMartin76** [comment]
Now it fails at
```
result = forwarded_proto_header and forwarded_proto_header:lower() == HTTPS
```
Wtf.

**Comment by DonMartin76** [comment]
"§/&%"%/§&%"§

It probably failed there all the time. There's the "Aaah" moment.

**Comment by Tieske** [comment]
so the line numbers in the stacktrace changed now? or was it our fault of looking at the wrong `:lower()` call without checking the linenumbers?

(I for one only looked at the first call)

**Comment by DonMartin76** [comment]
Yes, I think that was the problem. Man. I feel like a n00b now. `x-forwarded-proto` is returned as a table. Now, how do I inspect that in Lua...

**Comment by Tieske** [comment]
ok. The headers get returned as a string unless there are more of the same headers, in which case a table gets returned, listing all of them.

So;

1. can you check the request to contain that header multiple times?
2. I'm an oauth noob, so what's to be done with the multiple headers? 

@nijikokun What's your take on the number 2?

**Comment by DonMartin76** [comment]
This header has actually nothing to do with OAuth, this is just something Kong does to enforce that you aren't using OAuth over http, which is inherently not secure.

**Comment by DonMartin76** [comment]
Thanks, guys, for your time. So, together we figured out what is wrong:

* Kong does not account for the case where the `x-forwarded-proto` is added twice (and thus a table is returned instead of a string)
* Our HAproxy configuration had an explicit add for the above header, but apparently it does that by default anyway. I just had to remove the additional `add-header` directive.

Oh man. I learnt something at least.

**Comment by Tieske** [comment]
try this;
```lua
if type(forwarded_proto_header) == "table" then
   for i,v in ipairs(forwarded_proto_header) do
      ngx.log(ngx.STDERR, i, v)
   end
end
````

Should at least show the contents of all of them is the same, though I wonder why the header is added multiple times.

**Comment by DonMartin76** [comment]
As stated above: Conbination of misconfiguration of HAproxy and Kong reacting allergic to multiple headers... Difficult to say what to do here. In my book Kong shouldn't crash on this, even though it's fixable via configuration in HAproxy. It's up to you what to do with it.

**Comment by Tieske** [comment]
@DonMartin76 thanks for your help in tracking this down.

Fully agree that Kong shouldn't crash. But as it's security related, then with even a slight possibility of getting mixed http and https values, we should be conservative and bail out or assume http. 

So options to fix;

1. consider it an error, and bail out (proper http response that is)
2. just grab the first entry from the list of values
3. iterate over the list and pick the "lowest security" level (eg. http if mixed http/https)

cons;

1. makes it a user problem
2. is simple but less secure
3. is slow

So what where the header values? HAproxy delivered the headers multiple times? all with the same values? How did this happen?

**Comment by DonMartin76** [comment]
Apparently (I didn't know this) HAproxy automatically adds the `x-forwarded-proto` if it is used for SSL termination. If you then use `http-request add-header x-forwarded-proto https` to add it explicitly, well, it adds it once more. Which could arguably be implemented differently in HAproxy.

**Comment by Tieske** [comment]
since this is the first time we encounter it, I'm inclined to go for option 1 as a conservative measure

**Comment by DonMartin76** [comment]
In this case. I'm inclined to agree. At least it's fairly well documented in this issue. Thanks again for your support! Next time I encounter any of these things, I know faster how to debug Kong.
