### ISSUE TITLE
Plugin with Custom Entities does not migrates

### ISSUE THREAD

**Issue by allisthere2love** [Mashape/kong#1252]
Hi,

We're trying to use a custom plugin that has custom entities. We have the following files, besides handler and schema:
api.lua
daos.lua
migrations/cassandra.lua
migrations/postgres.lua

However, when Kong starts the custom table isn't created. Neither does it when the plugin is added to any API.

If we get the CQL from cassandra.lua and run it in CQLSH, the table is succesfully created and the plugins works.

Can you help us find what's missing for the "automatic" table creation?

thanks!

**Comment by thefosk** [comment]
Did you rename the `name` property of each migration?

**Comment by thefosk** [comment]
I will close this issue - let me know if that fixes it.

**Comment by allisthere2love** [comment]
Hi, @thefosk, if I understood it correctly, yes, we renamed it. This is my cassandra.lua in the migrations directoy:
`return {
  {
    name = "2016-05-20_init_namedquery_tb",
    up = [[
      CREATE TABLE IF NOT EXISTS namedquery_tb(
        id uuid,
        consumer_id uuid,
        query text,
        namedquery text,
        database_name text,
        qtd_params_query number,
        PRIMARY KEY (id)
      );
      CREATE INDEX IF NOT EXISTS namedquery_tb_consumer_id ON namedquery_tb(consumer_id);
      CREATE INDEX IF NOT EXISTS ON namedquery_tb(namedquery);
    ]],
    down = [[
      DROP TABLE namedquery_tb;
    ]]
  }
}
`

**Comment by thefosk** [comment]
Have you added the file into the rockspec?

**Comment by allisthere2love** [comment]
Yes, I have this structure in my rockspec:

["kong.plugins.plugin_name.handler"] = "kong/plugins/plugin_name/handler.lua",
["kong.plugins.plugin_name.schema"] = "kong/plugins/plugin_name/schema.lua",
["kong.plugins.plugin_name.daos"] = "kong/plugins/plugin_name/daos.lua",
["kong.plugins.plugin_name.api"] = "kong/plugins/plugin_name/api.lua",
["kong.plugins.plugin_name.migrations.cassandra"] = "kong/plugins/plugin_name/migrations/cassandra.lua",
["kong.plugins.plugin_name.migrations.postgres"] = "kong/plugins/plugin_name/migrations/postgres.lua",

**Comment by thefosk** [comment]
@allisthere2love this is very hard to replicate on our side since we don't have the code. I would check that the paths are correct, that Luarocks is not behaving weirdly (you can execute `luarocks purge --tree=/usr/local` to purge the local cache just in case), or take inspiration from other new plugins like https://github.com/Mashape/kong/pull/1259
