### ISSUE TITLE
Feature Request: Option for CORS Plugin to remove upstream CORS headers

### ISSUE THREAD

**Issue by ammmze** [Mashape/kong#1253]
Could we perhaps have an option in the CORS plugin that will tell it to remove upstream CORS header? 

I have an api that runs spring webmvc side-by-side with the camunda rest engine. In the spring webmvc app, I do not have CORS setup, but on the camunda rest engine it does (and it doesn't seem like it can be disabled).

So I enabled the CORS plugin in kong, but now we end up with duplicate CORS headers when using the rest engine. I had at one point attemtped to use the response transformer plugin to remove the headers, but it seemed like it ran after the CORS plugin, causing it to remove the headers from the upstream and the ones from the CORS plugin.

**Comment by thefosk** [comment]
This is related to #259 and should been have fixed by #1240 in 0.8.2 to be released in a few hours.

**Comment by ammmze** [comment]
Ha...nice :) I'll give it a try soon then
