### ISSUE TITLE
Mention all kong cluster nodes in configuration

### ISSUE THREAD

**Issue by alexraju** [Mashape/kong#1254]
Is it possible to mention all the cluster nodes in the configuration?

**Comment by thefosk** [comment]
@alexraju why do you need this? Kong will automatically join the other nodes without mentioning them in the configuration.

**Comment by alexraju** [comment]
@thefosk This is needed when we are following container orchestration. 
Deploying kong in container doesn't register the correct IP address in database. 
Also, while scaling to 4 or 10 instances in Marathon(container orchestration system), we are using the same configuration for every instance. So, we need to have a mechanism to add all nodes to the kong cluster. Also, APIs for adding new nodes will be great.

**Comment by thefosk** [comment]
So that you know we are working on a distribution for Mesosphere, which should cover your use-case. In the meanwhile you can see how we are doing this in Docker-Compose: https://github.com/Mashape/docker-kong/tree/docker-compose/autopilot

**Comment by alexraju** [comment]
Happy to know that you understood the importance. Yes, we are actually working on Mesos.
