### ISSUE TITLE
[oauth2-postgres] Adding an application generates an error

### ISSUE THREAD

**Issue by codebien** [Mashape/kong#1262]
Kong 0.8.2

Hi,
I have tried this with a clean installation on docker. I first add an API, then enable oauth2 plugin, and finally add a consumer.
When I try to add an oauth2 application to the consumer I get a 500.

Error from error.log:

2016/05/27 12:09:42 [error] 102#0: *40 [lua] app.lua:61: handle_error(): /usr/local/share/lua/5.1/lapis/application.lua:659: /usr/local/share/lua/5.1/kong/dao/postgres_db.lua:79: don't know how to escape value: table: 0x41fa1f08
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/dao/postgres_db.lua:79: in function 'escape_literal'
	/usr/local/share/lua/5.1/kong/dao/postgres_db.lua:281: in function 'insert'
	/usr/local/share/lua/5.1/kong/dao/dao.lua:103: in function 'insert'
	/usr/local/share/lua/5.1/kong/api/crud_helpers.lua:98: in function 'post'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/api.lua:57: in function </usr/local/share/lua/5.1/kong/plugins/oauth2/api.lua:56>

stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/lapis/application.lua:659: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'resolve'
	/usr/local/share/lua/5.1/kong/api/app.lua:46: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:404: in function </usr/local/share/lua/5.1/lapis/application.lua:400>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:400: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:205: in function 'serve'
	content_by_lua(nginx.conf:155):9: in function <content_by_lua(nginx.conf:155):1>, client: 127.0.0.1, server: , request: "POST /consumers/Jason/oauth2 HTTP/1.1", host: "127.0.0.1:8001"

Thanks.

**Comment by thefosk** [comment]
I will immediately publish a fix for this in a 0.8.3 release, in the meanwhile I think the problem can be fixed by changing this line (https://github.com/Mashape/kong/blob/master/kong/dao/postgres_db.lua#L75) with:

```lua
elseif t_val == "table" and field and (field.type == "table" or field.type == "array) then
```

**Comment by DonMartin76** [comment]
Due to this fix, I now get an error when adding an `oauth2` configuration to a consumer. The following sequence of `curl` calls causes Kong to crash:

```bash
curl -X POST -d '{"name":"petstore","upstream_url":"http://petstore.swagger.io/v2","request_path":"/petstore","strip_request_path":true}' -H 'Content-Type: application/json' http://localhost:8001/apis
curl -X POST -d '{"name":"key-auth","enabled":true,"config":{"hide_credentials":true,"key_names":["X-ApiKey"]}}' -H 'Content-Type: application/json' http://localhost:8001/apis/8a3ae9ee-6ec3-4d9d-88a7-a10a843987c1/plugins
curl -X POST -d '{"name":"acl","enabled":true,"config":{"whitelist":["petstore"]}}' -H 'Content-Type: application/json' http://localhost:8001/apis/8a3ae9ee-6ec3-4d9d-88a7-a10a843987c1/plugins
curl -X POST -d '{"name":"petstore-oauth","upstream_url":"http://petstore.swagger.io/v2","request_path":"/petstore-oauth","strip_request_path":true}' -H 'Content-Type: application/json' http://localhost:8001/apis
curl -X POST -d '{"name":"oauth2","enabled":true,"config":{"scopes":["api"],"token_expiration":3600,"enable_authorization_code":false,"enable_client_credentials":true,"enable_implicit_grant":false,"enable_password_grant":false,"hide_credentials":true,"accept_http_if_already_terminated":true}}' -H 'Content-Type: application/json' http://localhost:8001/apis/ae1305ed-1df7-4655-a4b4-3fbd4cc79de7/plugins
curl -X POST -d '{"name":"acl","enabled":true,"config":{"whitelist":["petstore-oauth"]}}' -H 'Content-Type: application/json' http://localhost:8001/apis/ae1305ed-1df7-4655-a4b4-3fbd4cc79de7/plugins
curl -X POST -d '{"upstream_url":"http://172.29.241.55:3000/swagger-ui","request_path":"/swagger-ui","preserve_host":false,"strip_request_path":true,"name":"swagger-ui-portal"}' -H 'Content-Type: application/json' http://localhost:8001/apis
curl -X POST -d '{"upstream_url":"http://172.29.241.55:3000/ping","request_path":"/ping-portal","preserve_host":false,"strip_request_path":true,"name":"ping-portal"}' -H 'Content-Type: application/json' http://localhost:8001/apis
curl -X POST -d '{"username":"my-app$petstore","custom_id":"dfkjhgkjldrhgksrhgklhrdgksjdhfgksfdhg"}' -H 'Content-Type: application/json' http://localhost:8001/consumers
curl -X POST -d '{"group":"petstore"}' -H 'Content-Type: application/json' http://localhost:8001/consumers/ec002dc8-0e5b-4c7a-a311-64c3d9e803c7/acls
curl -X POST -d '{"key":"e871127755397568232ba2f04d3e1e101f508f0a"}' -H 'Content-Type: application/json' http://localhost:8001/consumers/ec002dc8-0e5b-4c7a-a311-64c3d9e803c7/key-auth
curl -X POST -d '{"config":{"hour":100,"async":true,"continue_on_error":true},"name":"rate-limiting","consumer_id":"ec002dc8-0e5b-4c7a-a311-64c3d9e803c7"}' -H 'Content-Type: application/json' http://localhost:8001/apis/petstore/plugins
curl -X POST -d '{"username":"my-app$petstore-oauth","custom_id":"6fe6f2c5bb6fd13612c5cf127f0ad8403b862a10"}' -H 'Content-Type: application/json' http://localhost:8001/consumers
curl -X POST -d '{"group":"petstore-oauth"}' -H 'Content-Type: application/json' http://localhost:8001/consumers/f2f7a149-dd04-486b-b77f-28489a4238b8/acls
curl -X POST -d '{"name":"my-app","client_id":"b78ef2916e0bfee1904c9d27384e3a0b882e4b22","client_secret":"171723d1f955054c25d88154c2c50e681efd4afc","redirect_uri":"http://dummy.org"}' -H 'Content-Type: application/json' http://localhost:8001/consumers/f2f7a149-dd04-486b-b77f-28489a4238b8/oauth2
```

**Comment by DonMartin76** [comment]
Can confirm that the fix helps.

**Comment by thefosk** [comment]
@DonMartin76 perfect - I will publish 0.8.3 this week.
