### ISSUE TITLE
Kong 0.8.2 is not starting in OSX

### ISSUE THREAD

**Issue by b-rajesh** [Mashape/kong#1265]
Hi , 
I just installed Kong 0.8.2 in my Mac and i am not able to start the server as usual. I did cleaned my old version , however still having problems.

luajit: /usr/local/share/lua/5.1/kong/cli/utils/logger.lua:5: module 'ansicolors' not found:
	no field package.preload['ansicolors']
	no file './ansicolors.lua'
	no file '/usr/local/Cellar/luajit/2.1_1/share/luajit-2.1.0-beta2/ansicolors.lua'
	no file '/usr/local/share/lua/5.1/ansicolors.lua'
	no file '/usr/local/share/lua/5.1/ansicolors/init.lua'
	no file '/usr/local/Cellar/luajit/2.1_1/share/lua/5.1/ansicolors.lua'
	no file '/usr/local/Cellar/luajit/2.1_1/share/lua/5.1/ansicolors/init.lua'
	no file './ansicolors.so'
	no file '/usr/local/lib/lua/5.1/ansicolors.so'
	no file '/usr/local/Cellar/luajit/2.1_1/lib/lua/5.1/ansicolors.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/share/lua/5.1/kong/cli/utils/logger.lua:5: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/kong/cli/cmds/version.lua:3: in main chunk
	[C]: in function 'require'
	/usr/local/bin/kong:54: in main chunk
	[C]: at 0x01000018f0

**Comment by thibaultCha** [comment]
It seems Luarocks did not fully install Kong's dependencies. Try to run `luarocks install` again and maybe paste the output here if anything still looks strange.

**Comment by b-rajesh** [comment]
Hi I tried uninstall all mashape dependency for kong and reinstall kong and still having the same problem.

**
luajit: /usr/local/share/lua/5.1/kong/cli/utils/logger.lua:5: module 'ansicolors' not found:
	no field package.preload['ansicolors']
	no file './ansicolors.lua'
	no file '/usr/local/Cellar/luajit/2.1_1/share/luajit-2.1.0-beta2/ansicolors.lua'
	no file '/usr/local/share/lua/5.1/ansicolors.lua'
	no file '/usr/local/share/lua/5.1/ansicolors/init.lua'
	no file '/usr/local/Cellar/luajit/2.1_1/share/lua/5.1/ansicolors.lua'
	no file '/usr/local/Cellar/luajit/2.1_1/share/lua/5.1/ansicolors/init.lua'
	no file './ansicolors.so'
	no file '/usr/local/lib/lua/5.1/ansicolors.so'
	no file '/usr/local/Cellar/luajit/2.1_1/lib/lua/5.1/ansicolors.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/share/lua/5.1/kong/cli/utils/logger.lua:5: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/kong/cli/cmds/start.lua:4: in main chunk
	[C]: in function 'require'
	/usr/local/bin/kong:54: in main chunk
	[C]: at 0x01000018f0
**

**Comment by b-rajesh** [comment]
Please note i use brew to manage kong which worked fine until 0.8.1

**Comment by Tieske** [comment]
`ansicolors`  module was still included in 0.8.1 rockspec, see https://github.com/Mashape/kong/blob/faaa422f912128a730d65ecf994d8e72ccab3ab9/kong-0.8.1-0.rockspec

what happens if you manually install ansicolors using `luarocks install ansicolors` ?

**Comment by b-rajesh** [comment]
This issue is resolved, 
please refer
https://github.com/Mashape/homebrew-kong/issues/29#issuecomment-223501647

**Comment by Tieske** [comment]
👍
