### ISSUE TITLE
Long URI are truncated (Not an NGINX error ? )

### ISSUE THREAD

**Issue by JnMik** [Mashape/kong#1266]
Hi everyone ! 

How should I proceed to increase the maximum URI length authorized by kong ? Seems the URL is getting truncatde around 4950 characters, and one of my upstream might be receiving a bit more than that. 

I do not receive an Request-URI Too Large error, seems like kong is truncating it.
The call to the upstream is well done, but I cleary see that it does not forward the whole URL.
Missing stuff at the end like  &limit=1000&page=2 etc.

Thx!

**Comment by hutchic** [comment]
That seems like an insanely long url FYI it won't be supported by most versions of IE https://support.microsoft.com/en-us/kb/208427

**Comment by JnMik** [comment]
Yeah I know it is, but our upstream API is a 3-party API and it allows it. 
We call the API with PHP Curl, S2S. So it all work good.

**Comment by JnMik** [comment]
Well I think I'll just refactor the script calling the 3 party API, so it will do multiple calls and stack the results. Having **that long** of an URI doesn't feel right to me either lol

**Comment by JnMik** [comment]
Even if I'll refactor our code, should kong really impose a limit on URI length, considering the forwarding to the upstream should be pretty much transparent ? 

What is kong URI length limit ?

**Comment by Tieske** [comment]
> Even if I'll refactor our code, should kong really impose a limit on URI length, considering the forwarding to the upstream should be pretty much transparent ?

my thought as well

**Comment by JnMik** [comment]
I have a lot of S2S API calls to move through our gateway.
I'm not aware of all the possible use cases for all the APIs. 
We do run a lot of tests and have a efficient QA team, 
but It still feels like it might be a point of failure hard to detect.

**Comment by thefosk** [comment]
The URI limit is something that is enforced pretty much by many servers and clients. The URI should be short and anything else should be submitted as a POST request. Kong itself doesn't set any limit, and it's probably enforced by nginx. Maybe this property can help in setting a higher length: http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers

**Comment by Tieske** [comment]
not sure here. Just truncating seems wrong. Ok to set a limit imo, but then it should be explicit and return an error if exceeded.

**Comment by JnMik** [comment]
Yup and like I said, it wasn't the usual "Request-URI Too Large" error, so it didn't felt like it was NGINX's fault.

**Comment by thefosk** [comment]
I have created a test simulating a request whose URI is too long, and Kong is responding with a `414 Request-URI Too Large` response without even trying to proxy the request. Any thoughts?

My test is at: https://github.com/Mashape/kong/commit/115a91fa240955f60ecae2616055e3ab9a984403

**Comment by JnMik** [comment]
I'll try to build a scenario where my bug happens all the time, thx for taking the time to write a test about that.

Also,

>  The URI should be short and anything else should be submitted as a POST request

I don't think this is true. When doing REST API, POST method is meant to insert a ressource. 
Fetching ressources with filters should always be done through GET method.
And i'm also pretty sure at least 80%+ of the APIs on the web prefer querystring filtering over headers for GET methods.

I'll get back on this when I have a moment !
