### ISSUE TITLE
Nginx resolver

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#127]
nginx doesn't support `/etc/hosts` file as a resolver for the `proxy_pass` directive. Right now the resolver is set to the Google DNS service at `8.8.8.8` which requires an Internet connection to work.

The alternative is to install another dependency like `dnsmasq` which will simulate a DNS server on `127.0.0.1`, to be configured like:

```shell
echo -e "user=root\nno-resolv\nserver=8.8.8.8" >> /etc/dnsmasq.conf
```

With dnsmasq installed the resolver could point to `127.0.0.1` and it will read from `/etc/hosts` file, or fallback to `8.8.8.8`.

Whatever we decide to do, we need to change the way it currently works because it makes the Internet a dependency to Kong (!).

**Comment by thibaultCha** [comment]
If Kong doesn't have internet, it cannot be installed anyways, it needs Internet for the Luarocks dependencies.

Secondly, if it doesn't have internet, why does it need to do DNS lookups? One should simply set the IP of his or her API.

Finally, isn't that an edge case that we should deal with later? Do we know yet if someone with an internal API that doesn't have access to internet will be using Kong?

**Comment by thefosk** [comment]
Kong can be installed without internet through the packages. The `rpm`, `deb` etc distributions are not communicating with the Internet internally nor invoking Luarocks, Kong is bundled inside.

The only use case would be for internal environments that also have internal DNS server or custom DNS configuration in `/etc/hosts`, or for on-premise installations in private environments that don't have a NAT.

**Comment by SGrondin** [comment]
It's not about not having internet. It's about internal routes, hosts file, local enterprise DNS server, etc etc. You can't make an enterprise product without using the local resolver! Just don't add the `resolver` line in nginx.conf and it'll be fine. It'll figure it out.

**Comment by ahmadnassri** [comment]
> It's not about not having internet. It's about **internal routes, hosts file, local enterprise DNS server**, etc etc. You can't make an enterprise product without using the local resolver!

that ^

**Comment by thefosk** [comment]
Nginx **needs** a `resolver` entry otherwise you will start seeing `502 Bad Gateway` errors. So removing the `resolver` entry is not an option. It needs to point somewhere and to make it point to `/etc/hosts` we need to use `dnsmasq` as I suggested.
