### ISSUE TITLE
[admin-api] Not allowed method generates error

### ISSUE THREAD

**Issue by codebien** [Mashape/kong#1270]
Kong 0.8.2

Requests like these generate error:

curl -H "Content-Type: application/json" -X PATCH http://kong:8001/apis
curl -H "Content-Type: application/json" -X DELETE http://kong:8001/apis
curl -H "Content-Type: application/json" -X DELETE http://kong:8001/oauth2

2016/05/31 07:00:44 [error] 109#0: *5 lua coroutine: runtime error: don't know how to respond to DELETE
stack traceback:
coroutine 0:
	[C]: ?
coroutine 1:
	[C]: in function 'resume'
	/usr/local/share/lua/5.1/lapis/application.lua:656: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'resolve'
	/usr/local/share/lua/5.1/kong/api/app.lua:46: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:404: in function </usr/local/share/lua/5.1/lapis/application.lua:400>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:400: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:205: in function 'serve'
	content_by_lua(nginx.conf:155):9: in function <content_by_lua(nginx.conf:155):1>, client: 192.168.99.1, server: , request: "DELETE /oauth2 HTTP/1.1", host: "kong:8001"

2016/05/31 07:03:46 [error] 109#0: *7 lua coroutine: runtime error: don't know how to respond to DELETE
stack traceback:
coroutine 0:
	[C]: ?
coroutine 1:
	[C]: in function 'resume'
	/usr/local/share/lua/5.1/lapis/application.lua:656: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'resolve'
	/usr/local/share/lua/5.1/kong/api/app.lua:46: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:404: in function </usr/local/share/lua/5.1/lapis/application.lua:400>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:400: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:205: in function 'serve'
	content_by_lua(nginx.conf:155):9: in function <content_by_lua(nginx.conf:155):1>, client: 192.168.99.1, server: , request: "DELETE /apis HTTP/1.1", host: "kong:8001"
2016/05/31 07:07:40 [error] 109#0: *9 lua coroutine: runtime error: don't know how to respond to PATCH
stack traceback:
coroutine 0:
	[C]: ?
coroutine 1:
	[C]: in function 'resume'
	/usr/local/share/lua/5.1/lapis/application.lua:656: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'resolve'
	/usr/local/share/lua/5.1/kong/api/app.lua:46: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:404: in function </usr/local/share/lua/5.1/lapis/application.lua:400>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:400: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:205: in function 'serve'
	content_by_lua(nginx.conf:155):9: in function <content_by_lua(nginx.conf:155):1>, client: 192.168.99.1, server: , request: "PATCH /apis HTTP/1.1", host: "kong:8001"

However a correct 405 response is returned to client.

**Comment by thefosk** [comment]
This has been a knows issue for a long time, we just didn't have time to fix it. The bug is a logging bug, in a sense that, as @codebien properly stated, this errors shouldn't be logged into `error.log` at all.

**Comment by Tieske** [comment]
This has been fixed in #1360, will be in 0.9
