### ISSUE TITLE
[admin-api] Not accept Get requests with explicit content type

### ISSUE THREAD

**Issue by codebien** [Mashape/kong#1272]
Kong 0.8.2
Minor issue. Should skip the content-type header for GET requests.

**Request**
`curl -H "Content-Type: application/json" -X GET http://kong:8001/apis`

**Response**
`{"message":"Cannot parse JSON body"}`

**Comment by Tieske** [comment]
So... is this actually a bug? you're marking it as a json body, yet not providing it. I think this behaviour is quite ok actually.

**Comment by chrisanderton** [comment]
I'm not sure it's a bug - it's bad input - but at the same time for GET requests you could always safely ignore "Content-Type"; GET requests can include the "Accepts" header instead for content negotiation

**Comment by codebien** [comment]
Yes, for me it isn't a bug but however it isn't the best user experience. In an REST-like API I expect that a GET request hasn't a body so it's useless check and block the request.

**Comment by Tieske** [comment]
Right. Then the Kong admin api should ignore the body except for PATCH, PUT and POST methods.

**Comment by Tieske** [comment]
fixed in PR #1285, scheduled for 0.9

**Comment by Tieske** [comment]
fixed in #1359, will be in 0.9
