### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Nijikokun** [Mashape/kong#128]
**Core**

- [x] Installation as defined under #126 
  - [x] Configuration
  - [x] Update Ubuntu commands
  - [x] Update Debian commands
- [x] Overview
  - [x] Guide "boxes" that point to different locations in the documentation
- [x] Welcome to Kong
- [x] Getting Started / Introduction
  - [x] Thirty second quickstart with Kong
  - [x] Adding APIs
  - [x] Enabling Plugins
  - [x] Adding Consumers
  - **Future:** Adding nodes to your Kong cluster
- [x] Migrations
- [x] Plugins
- [x] Binary / CLI API
- [x] RESTful API

**Plugins**

Minimum required documentation for **all** plugins:

- [x] Name
- [x] Tagline
- [x] Installing
- [x] Configuration (including usage commands)
- [x] Usage (how it affects API(s) / Consumer(s), and examples of usage)
  
  Examples of usage are for example take the `keyauth` plugin which adds authentication that can be used in multiple places such as the `header`, `querystring`, or `form` parameter:

  ---

  Using the `keyauth` plugin as a `header`:

  ```bash
  curl -i -X GET \
     --url http://localhost:8000/ \
     --header 'Host: mockbin.com' \
     --header '<key_name>: <key>'
  ```

  Where `key_name` is a value defined in `value.key_names`, and `key` is a key created with a `POST` request to `/keyauth_credentials/`

- [ ] Explanation of each feature (how does `keyauth` differ from `basicauth`)

**Comment by Nijikokun** [comment]
Perhaps should move plugin documentation requirements to a wiki page, thoughts @thibaultCha and @thefosk ?

**Comment by orliesaurus** [comment]
[_] Update Ubuntu commands to add Kong with sudo

**Comment by Nijikokun** [comment]
**Other** is actually `Source`

Perhaps it should be renamed?

@thibaultCha

**Comment by thibaultCha** [comment]
CLI API: mashape/getkong.org#31. Which could also contain configuration (see the PR)

**Comment by thibaultCha** [comment]
This issue should probably be in getkong.org. Or closed and reopened as a smaller version there.

**Comment by Nijikokun** [comment]
This has been completed :+1:
