### ISSUE TITLE
installer for kong

### ISSUE THREAD

**Issue by vanibandi** [Mashape/kong#1282]
can i get tar ball installer for rhel6 or the installer which does not require sudo yum command.

**Comment by thefosk** [comment]
Nope - currently either your use a package or you try to compile it from source.

**Comment by vanibandi** [comment]
Hi,

Can you provide instructions to compile code present on github

**Comment by Tieske** [comment]
see https://getkong.org/install/source/

**Comment by vanibandi** [comment]
Hi,

I have followed the link provided https://getkong.org/install/source/
I was able to complete step#1 to install luajit, luarocks and openresty.

I am not able to complete step 2 to install kong via luarocks. I checked
all the dependencies and manually downloaded these from github. Now when I
run make install for kong.git, I am still getting error. In my system, we
don't have access for the Linux system to access internet and hence I am
not able to use luarock install command. Please let me know how I can
install all these dependencies from the github source downloaded and placed
locally. Most of these folders have .lua files. Please let me know if I
need to copy these .lua files to a folder for installer to recognize the
same.

Missing dependencies for kong:
lua-cjson ~> 2.1.0-1
lua-llthreads2 ~> 0.1.3-1
lbase64 ~> 20120820-1
luacrypto >= 0.3.2-1
ansicolors ~> 1.0.2-3
luatz ~> 0.3-1
pgmoon ~> 1.4.0
lua_uuid ~> 0.2.0-2
lapis ~> 1.3.1-1
mediator_lua ~> 1.1.2-0
lrexlib-pcre ~> 2.7.2-1
multipart ~> 0.3-2
lua-path ~> 0.2.3-1
lua_pack ~> 1.0.4-0
luasec ~> 0.5-2
luasocket ~> 2.0.2-6
lua-resty-iputils ~> 0.2.0-1
lua_system_constants ~> 0.1.1-0
luasyslog >= 1.0.0-2
penlight ~> 1.3.2
lua-cassandra ~> 0.5.2
stringy ~> 0.4-1
yaml ~> 1.1.2-1
lua-resty-http ~> 0.07-0
