### ISSUE TITLE
Negative caching of entities

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#1286]
Sometimes it's worth protecting the datastore with negative caching of entities in the local node.

For example when using the Key Authentication plugin, when many requests are being sent with the wrong key, that would trigger a query on the datastore for each request.

**Comment by codebien** [comment]
Interesting. Can explain how do you think to implement it. Thanks.

**Comment by thefosk** [comment]
@codebien by saving datastore misses, which will be invalidated like every other entity by the hooks.

**Comment by Tieske** [comment]
this has been implemented already, when the 2nd level in-memory cache was added. Is in 0.10.
