### ISSUE TITLE
Bug: key-auth plugin validating OPTIONS requests with CORS and preflight_continue=true

### ISSUE THREAD

**Issue by jusw85** [Mashape/kong#1292]
Using Docker Kong 0.8.3

Related to https://github.com/Mashape/kong/issues/852

As per topic:

```
curl "http://${kong_host}:${kong_admin_port}/apis/${1}/plugins"


{
    "data": [
        {
            "api_id": "7bc63d3d-32bb-40b1-a646-7e9ef34d8e81",
            "id": "2bc3666c-d25b-4785-ae6e-1c575293e9ea",
            "created_at": 1462937923000,
            "enabled": true,
            "name": "key-auth",
            "config": {
                "hide_credentials": false,
                "key_names": [
                    "apikey"
                ]
            }
        },
        {
            "api_id": "7bc63d3d-32bb-40b1-a646-7e9ef34d8e81",
            "id": "1e99391b-776a-47d3-8a93-8bd19b67c9a5",
            "created_at": 1465181734000,
            "enabled": true,
            "name": "cors",
            "config": {
                "preflight_continue": true,
                "credentials": false
            }
        }
    ],
    "total": 2
}

```

```
curl 'http://192.168.1.151/api/users' -X OPTIONS -H 'Access-Control-Request-Headers: apikey,content-type' -H 'Access-Control-Request-Method: GET' -H 'Connection: keep-alive' -H 'Host: 192.168.1.151' -H 'Origin: http://192.168.1.213:3000' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0'

{"message":"No API Key found in headers, body or querystring"}
```

With preflight_continue=false:

```
curl "http://${kong_host}:${kong_admin_port}/apis/${1}/plugins"

{
    "data": [
        {
            "api_id": "7bc63d3d-32bb-40b1-a646-7e9ef34d8e81",
            "id": "2bc3666c-d25b-4785-ae6e-1c575293e9ea",
            "created_at": 1462937923000,
            "enabled": true,
            "name": "key-auth",
            "config": {
                "hide_credentials": false,
                "key_names": [
                    "apikey"
                ]
            }
        },
        {
            "api_id": "7bc63d3d-32bb-40b1-a646-7e9ef34d8e81",
            "id": "1e99391b-776a-47d3-8a93-8bd19b67c9a5",
            "created_at": 1465181734000,
            "enabled": true,
            "name": "cors",
            "config": {
                "preflight_continue": false,
                "credentials": false
            }
        }
    ],
    "total": 2
}
```

```
curl 'http://192.168.1.151/api/users' -X OPTIONS -H 'Access-Control-Request-Headers: apikey,content-type' -H 'Access-Control-Request-Method: GET' -H 'Connection: keep-alive' -H 'Host: 192.168.1.151' -H 'Origin: http://192.168.1.213:3000' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0' -v

> OPTIONS /api/users HTTP/1.1
> Host: 192.168.1.151
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
> Accept-Encoding: gzip, deflate
> Accept-Language: en-US,en;q=0.5
> Access-Control-Request-Headers: apikey,content-type
> Access-Control-Request-Method: GET
> Connection: keep-alive
> Origin: http://192.168.1.213:3000
> User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0
> 
< HTTP/1.1 204 No Content
< Date: Mon, 06 Jun 2016 03:20:54 GMT
< Server: kong/0.8.3
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: apikey,content-type
< Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
< Content-Length: 0
< Keep-Alive: timeout=5, max=100
< Connection: Keep-Alive
```

**Comment by shashiranjan84** [comment]
In 1st request with `preflight_continue` = true, I dont see you providing `apikey` anywhere.
I am not sure what you referring as bug? Please provide more detailed bug description and reopen the ticket if you still see it as bug.

**Comment by jusw85** [comment]
In #852, the key-auth plugin was authenticating the OPTIONS request. This shouldn't be happening, because browsers strip custom headers and query parameters from OPTIONS requests; this is CORS by design.

http://stackoverflow.com/questions/13994507/how-do-you-send-a-custom-header-in-a-cross-domain-cors-xmlhttprequest
https://www.sencha.com/forum/showthread.php?265119-Authorization-header-not-sent-on-preflight-OPTIONS-request

To fix this problem, the CORS plugin has to be enabled on Kong. I've configured it this way, and it works perfect if Kong is handling the OPTIONS request.

However, I would like some upstream APIs to handle OPTIONS requests. The CORS plugin has an option that allows that(`preflight_continue = true`). This allows the plugin to proxy OPTIONS preflight requests to the upstream API.

The issue occurs when I have both the key-auth plugin and CORS plugin enabled, with CORS proxying the OPTIONS preflight request to the upstream API i.e. `preflight_continue = true`. In this scenario, the key-auth plugin authenticates the OPTIONS request. I see this as a bug, because I don't think key-auth should be authenticating OPTIONS requests (although I might be wrong).

**Comment by shashiranjan84** [comment]
@jusw85 Not sure where specification mention about request parameter, did you try with query parameter? 

If browser truncating query param, we may need to add a flag in Key Auth plugin (or other Auth plugins) config to allow `OPTIONS` request without validation. Not sure if there would be any security issue with that.

@nijikokun @thefosk @thibaultcha What you view on not authenticating `OPTIONS` requests?

**Comment by ecmendenhall** [comment]
+1 to a fix for this! Our application is running into this issue, too.

**Comment by thibaultcha** [comment]
This should be a very easy fix, contributions welcome if someone wants to tackle this.

**Comment by ecmendenhall** [comment]
We'll take a crack at this one!

**Comment by jasonbellamy** [comment]
Any updates on this being merged in?

**Comment by bootstrap314** [comment]
If you are encountering this issue, you probably are missing configuration.  Set the following setting to allow OPTIONS requests to be proxied without authentication:

run_on_preflight: false
