### ISSUE TITLE
Cassandra 3.x support

### ISSUE THREAD

**Issue by adrianlop** [Mashape/kong#1294]
Hi,
Do you have this feature in the roadmap?
Thanks!

**Comment by gavinlove** [comment]
This would be a good thing to get upgraded because Apache Cassandra 2.2 is only being supported until November 2016

**Comment by thefosk** [comment]
Since @thibaultCha is working on an improvement of the driver we could evaluate including support for 3.x.

**Comment by thibaultCha** [comment]
Support for Cassandra 3.x is on the [driver](https://github.com/thibaultCha/lua-cassandra)'s roadmap. Contributions welcome.

**Comment by vitorsdcs** [comment]
Looks like lua-cassandra 1.0.0, which was released 15 days ago, now supports Cassandra 3.x

**Comment by thibaultcha** [comment]
Yes, Kong now needs some work to switch to using 1.0.0, since it contains breaking changes. It would also, iirc, need some work on the way the existing tables are retrieved by the DAO (for the migrations), since I believe C* 3.0 does not maintain the exact same system tables as 2.x.

**Comment by adrianlop** [comment]
@thibaultcha thanks for the update.

**Comment by thibaultcha** [comment]
#1709 has been merged! This will land in 0.10 scheduled by the end of the month.
