### ISSUE TITLE
Oauth2 Plugin Security access Issue

### ISSUE THREAD

**Issue by juandavidgc** [Mashape/kong#1296]
Hello! right now I have a problem. I have multiple clients, each one uses one API (an exclusive API per client). I've configured one consumer per API and I've installed the "oauth2" plugin on each one. The issue I have is that one client could access (using his own credentials) the API of other client, puting the host on the header. Do you know how can I prevent that? is there a way in which I could join the consumer, the oauth application and the API in order to prevent that security hole? Thanks in advance!

**Comment by thefosk** [comment]
The [ACL plugin](https://getkong.org/plugins/acl/) fixes this.

**Comment by juandavidgc** [comment]
Perfect, thanks!
