### ISSUE TITLE
Unable to use hostnames without domain name in `request_host`

### ISSUE THREAD

**Issue by jarl-dk** [Mashape/kong#1300]
I have some practical hostnames in `/etc/hosts`. I want to configure kong to filter requests based on these hostnames (without a domain), so I configure kong with
```
curl -f -X POST \
  -F 'name=backend' \
  -F "upstream_url=http://backend:8080" \
  -F 'request_host=api-backend' \
'http://localhost:8001/apis/'
```

but when I do so I get
```
curl: (22) The requested URL returned error: 400 Bad Request
```

I have isolated the issue. The problem only occurs when `request_host` is given a host name that does not contain a `.` (dot) for subdomain separation.

I think this is an unnecessary limitation of the argument validation.

**Comment by Tieske** [comment]
I think you're right. This is the [offending line](https://github.com/Mashape/kong/blob/master/kong/dao/schemas/apis.lua#L33) as it requires a `.`.

**Comment by Tieske** [comment]
This also touches on the punycode again, see https://github.com/Mashape/kong/issues/1205#issuecomment-221386825 (i18n domain names)

so best of its fixed in one go.

**Comment by Tieske** [comment]
will be in the next release. closing this.
