### ISSUE TITLE
Intercept and modify API upstream_url

### ISSUE THREAD

**Issue by nicklanng** [Mashape/kong#1301]
I've been playing around with the idea of a plugin that can alter the upstream url of an API based on some database value and authentication data.

In its simplest form this is what I'm writing in my plugin
```lua
-- access.lua
local _M = {}

function _M.execute(conf)
  ngx.ctx.upstream_url = "http://www.google.com"
end

return _M
```

I find that this does indeed route the request somewhere else, to google in this case, but the request path is no longer stripped off, ie its going to http://www.google.com/test.

Is there a better way to do this, or is there a way to enforce that the request path is stripped off?

Thanks.

**Comment by nathanandersen** [comment]
Hey Nick, I think what you're trying to do is relevant for what I want to do in #1337 . Can you provide a little more insight into what you're exactly trying to do?

**Comment by nicklanng** [comment]
Hi Nathan.

The plan is to create a global Kong cluster and use global DNS to route customers to their nearest endpoint. The problem is that customer data lives in a specific region, so once the customer has authenticated I need to redirect them to the specific region they belong in. My plan is to have a mapping from consumer ID to region and hopefully use Kong to redirect their request to the right place.

The backup plan is to simply add a header to the request, pass the request on to a local HAProxy instance that can then route on the header. I'd prefer that Kong was able to do this, to reduce the number of moving parts.

**Comment by nicklanng** [comment]
Easiest way to do these seems to be to modify the ngx.ctx.upstream_url and not replacing it.
When it comes in to the plugin, all of the request path stripping has already happened - so all thats left to do is to replace the scheme, host and port as applicable.
