### ISSUE TITLE
I am getting this message: HMAC signature cannot be verified

### ISSUE THREAD

**Issue by juhee07** [Mashape/kong#1304]
I have a client in perl which sends request to a kong proxy with HMAC header.

Request has send like this:
Authorization: hmac username= "f79f1ab2-9520-4e7b-948e-ee7e8bd9a060", algorithm="hmac-sha1", headers="X-Date", signature="t2BOexU7x9c8oLqmZd4Q/mO4KoU="
X-Date: Fri, 10 Jun 2016 06:17:31 GMT

String to Sign created as : 
date: Fri, 10 Jun 2016 06:17:31 GMT

Also as per your previous suggestion I tested request by setting the clock skew to very high like 86400. But still I getting the same error.

Please help me to find the resolution.

**Comment by shashiranjan84** [comment]
I would need more details to be able to help you. 

What error you getting?
How you calculating signature?

here is another ticket related to HMAC, and users are able to use it successfully.
https://github.com/Mashape/kong/issues/599

**Comment by juhee07** [comment]
Thanks Shashi for quick reply. 
We are trying to integrate kong with another tool where we store all consumers information. So in our case username is the unique id.
Url: consumers/AdminTest/hmac-auth
Response:
{
    "data": [
        {
            "secret": "PnMFnPd4BmW9TvnX",
            "id": "9703b9f5-7cac-4cab-89ea-2491bcb95225",
            "username": "f79f1ab2-9520-4e7b-948e-ee7e8bd9a060",
            "created_at": 1465033103000,
            "consumer_id": "eb031583-fdbd-42ab-a440-2dd5ac4593ba"
        }
    ],
    "total": 1
}

So when I am sending the HMAC request with headers:
Authorization: "hmac username= "f79f1ab2-9520-4e7b-948e-ee7e8bd9a060", algorithm="hmac-sha1", headers="X-Date", signature="+5ZUljHINesjnNYUzGtct9KVEho=""

X-Date="Fri, 10 Jun 2016 18:14:49 GMT"

I am getting error 403 Fordidden
{
    "message": "HMAC signature cannot be verified"
}

The script which is creating the header is in perl

 sub createHMAC {
	$stringToSign = "";
	$username = $_[0];
	$secret = $_[1];
	$date = createDateString();
        $stringToSign ="date: " . $date ;
        $signaturestr = sha1_base64(chomp($stringToSign), chomp($secret));
      
       # Fix padding of Base64 signature
	while (length($signaturestr) % 4) {
    	$signaturestr .= '=';
	}
	$authHeader = "hmac username= ". "\"$username\", " . "algorithm=" . "\"hmac-sha1\", " .      "headers=\"X-Date\", " . "signature=" . "\"$signaturestr\"";

   	my %headers= ('Authorization' => $authHeader,'X-Date' => $date);
        return %headers;
}

Below all the details:

Username : f79f1ab2-9520-4e7b-948e-ee7e8bd9a060
Secret : PnMFnPd4BmW9TvnX
Date and Time : Fri, 10 Jun 2016 18:14:49 GMT
String to sign: date: Fri, 10 Jun 2016 18:14:49 GMT
Signature : +5ZUljHINesjnNYUzGtct9KVEho=

Also the question is the "String to sign" will be date: Fri, 10 Jun 2016 18:14:49 GMT or only Fri, 10 Jun 2016 18:14:49 GMT (excluding "date:")?

**Comment by shashiranjan84** [comment]
`$date = createDateString();
$stringToSign ="date: " . $date ;
$signaturestr = sha1_base64(chomp($stringToSign), chomp($secret));`

why you creating new date? You supposed to use the x-date.

**Comment by juhee07** [comment]
I am seding this request using Postman. I am not sure how to populate X-Date value in perl. I dont see and library in perl which supports that.
Any otherway I can pass date as a stringToSign?

**Comment by juhee07** [comment]
So instead of headers="X-Date" , Can I use headers="Date" and in request header I can add Date instead of X-Date.

Eq
Date: "Fri, 10 Jun 2016 18:14:49 GMT"

**Comment by shashiranjan84** [comment]
Sorry actually date seems to be right, 

`$stringToSign ="date: " . $date ;`  should be 
`$stringToSign ="x-date: " . $date ;`

**Comment by juhee07** [comment]
I changed date to x-date but still getting same error.

**Comment by shashiranjan84** [comment]
I am not perl expert and its difficult to debug like this. You can refer our tests for working example.

https://github.com/Mashape/kong/blob/master/spec/plugins/hmac-auth/access_spec.lua

also what  sha1_base64 funtion does?

**Comment by shashiranjan84** [comment]
Please debug your code to check correct signature has been generated. for following signature string
`x-date: Fri, 10 Jun 2016 18:14:49 GMT` base64 of hashed signature would be `Vxz0P8ROwo4ak8uVvDJzUOurKSc=`

**Comment by BrianHutchison** [comment]
The access_spec.lua along with the Cavage spec (https://tools.ietf.org/html/draft-cavage-http-signatures-01) is a great resource when trying to put together the proper hmac signature. 

For what its worth, here is some node.js JS code that works:

`
var crypto = require("crypto");
exports.headers = function(apikey, username, secret, host, path, verb) {
  var date = new Date().toUTCString();
  var requestLine = verb + ' ' + path + ' HTTP/1.1';
  var stringToSign = 'date: ' + date.trim() + '\n' 
                   + 'host: ' + host.trim() + '\n' 
                   + requestLine;
  var encodedSignature = crypto.createHmac("sha1", secret).update(stringToSign).digest("base64");
  var hmacAuth = 'hmac username="' + username + '",algorithm="hmac-sha1",headers="date host request-line",signature="' + encodedSignature + '"';

  var headers = {
    'apikey': apikey,
    'date': date,
    'Authorization': hmacAuth
  }

  return headers;
};
`

**Comment by pa1n12** [comment]
I am getting same issue while authenticating an API from my java application.

```
Date curDate = new Date();
SimpleDateFormat format = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss z");
format.setTimeZone(TimeZone.getTimeZone("GMT"));
String dateToStr = format.format(curDate);

String authorizeString = org.apache.commons.codec.binary.Base64.encodeBase64String(HmacUtils.hmacSha1("secret_123", "date: "+dateToStr));

Header oauthHeader = null;
Header dateHeader = null;
   authHeader = new BasicHeader("Authorization", "username=\"abc\", algorithm=\"hmac-sha1\", headers=\"date \", signature=\""+authorizeString +"\"" );
        dateHeader = new BasicHeader("date", dateToStr);

String serviceURL = "serviceURI";
HttpClient httpClient = HttpClientBuilder.create().build();
HttpGet httpGet = new HttpGet(serviceURL);
httpGet.addHeader(authHeader );
httpGet.addHeader(dateHeader);

HttpResponse response = httpClient.execute(httpGet);
int statusCode = response.getStatusLine().getStatusCode();
           
```
String to sign:
date: Thu, 06 Oct 2016 14:51:50 GMT
secret: "secret_123"
Auth String: //IZHcJjfS3nq448u4VQtSVrxos=

It returns 403:
{
  "message": "HMAC signature cannot be verified"
}

Any help in this regard would is appreciated.

**Comment by shashiranjan84** [comment]
authHeader seems to be set wrong, its missing `hmac` in the beginning. Also make sure client and kong server clock in sync or debug with very high clock skew.

**Comment by pa1n12** [comment]
Thanks @shashiranjan84  appreciate your quick response.
