### ISSUE TITLE
Allow connecting to Postgres database via SSL

### ISSUE THREAD

**Issue by nguilford** [Mashape/kong#1309]
Postgresql servers can be configured to force a client to connect via ssl. Kong should allow for ssl connections to postgres in its config, as is available for cassandra. This is especially important given all the secrets that are stored in the database in plain text (e.g. jwt secrets).

For reference: https://www.postgresql.org/docs/9.1/static/ssl-tcp.html

**Comment by mars** [comment]
This is the blocker for Kong with Postgres on Heroku, because Heroku Postgres requires SSL: https://github.com/heroku/heroku-buildpack-kong/issues/7

I'm selfishly in support of forking pgmoon to get this fix @thibaultCha

**Comment by thibaultCha** [comment]
Alright, we just created a temporary fork at Mashape/pgmoon and we will include Postgres SSL connections in the upcoming 0.9 release (this month).

**Comment by thibaultCha** [comment]
#1425 implements those! Testing appreciated!

**Comment by thibaultCha** [comment]
Has been implemented.

**Comment by nguilford** [comment]
Thanks! I've been on vacation but I will take a look this week.
