### ISSUE TITLE
Postgres DAO not decoding JSON data during retrieval.

### ISSUE THREAD

**Issue by grantcarver** [Mashape/kong#1316]
Kong@0.8.3
Postgresql datastore

The redirect_uri for the oauth2 plugin is JSON encoded before storage in postgres but doesn't seem to be decoding upon retrieval. This prevents the check on `allowed_redirect_uris` during oauth2 authorisation. 

`error.log`
```
2016/06/15 14:10:56 [error] 2737#0: *3209 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/tools/utils.lua:182: bad argument #1 to 'pairs' (table expected, got string)
stack traceback:
coroutine 0:
        [C]: in function 'pairs'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:182: in function 'table_contains'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:154: in function 'authorize'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:406: in function 'execute'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:12: in function 'access'
        /usr/local/share/lua/5.1/kong.lua:188: in function 'access'
```

Apologies for no PR but have no experience with Lua.

**Comment by thefosk** [comment]
@grantcarver as an update to this issue, it has been fixed in `refactor/cli` and will be available in the next version.

**Comment by grantcarver** [comment]
Great, thanks @thefosk.

**Comment by ammmze** [comment]
I assume this is why we are seeing the redirect uri come back like this: `"redirect_uri": "[\"http://localhost\"]"` instead of `"redirect_uri": "http://localhost"`?

**Comment by mashapedeployment** [comment]
@ammmze yes

**Comment by Tieske** [comment]
closing this, will be in the 0.9 release
