### ISSUE TITLE
make dev doesn't work on a fresh installation

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#132]
Also, keplerproject/luarocks#347

```shell
$ make dev
busted already installed, skipping
luacov already installed, skipping
luacov-coveralls already installed, skipping
luacheck already installed, skipping
bin/kong config -e TEST
[WARNING] No config at: /etc/kong/kong.yml using default config instead.
lua: /usr/local/share/lua/5.1/luarocks/type_check.lua:173: attempt to index local 'typetbl' (a number value)
stack traceback:
	/usr/local/share/lua/5.1/luarocks/type_check.lua:173: in function 'check_version'
	/usr/local/share/lua/5.1/luarocks/type_check.lua:201: in function 'type_check_item'
	/usr/local/share/lua/5.1/luarocks/type_check.lua:276: in function </usr/local/share/lua/5.1/luarocks/type_check.lua:263>
	(tail call): ?
	/usr/local/share/lua/5.1/luarocks/type_check.lua:276: in function </usr/local/share/lua/5.1/luarocks/type_check.lua:263>
	(tail call): ?
	/usr/local/share/lua/5.1/luarocks/type_check.lua:276: in function </usr/local/share/lua/5.1/luarocks/type_check.lua:263>
	(tail call): ?
	/usr/local/share/lua/5.1/luarocks/type_check.lua:276: in function </usr/local/share/lua/5.1/luarocks/type_check.lua:263>
	(tail call): ?
	...
	/usr/local/share/lua/5.1/luarocks/manif_core.lua:28: in function </usr/local/share/lua/5.1/luarocks/manif_core.lua:21>
	(tail call): ?
	/usr/local/share/lua/5.1/luarocks/search.lua:175: in function 'manifest_search'
	/usr/local/share/lua/5.1/kong/cli/utils.lua:73: in function 'get_luarocks_dir'
	/usr/local/share/lua/5.1/kong/cli/utils.lua:85: in function 'get_luarocks_config_dir'
	/usr/local/share/lua/5.1/kong/cli/utils.lua:100: in function 'get_kong_config_path'
	/usr/local/share/lua/5.1/kong/cli/config.lua:19: in main chunk
	[C]: in function 'require'
	bin/kong:41: in main chunk
	[C]: ?
make: *** [dev] Error 1
```

**Comment by thibaultCha** [comment]
It's not just make dev then. It's everything using the default config...

**Comment by thefosk** [comment]
`kong start` works fine, only `make dev` fails.

**Comment by ignacio** [comment]
Please check again with the current LuaRocks master

**Comment by thefosk** [comment]
@ignacio it works now, thanks. 

I will be waiting for the new release of LuaRocks before closing this issue too.

**Comment by thibaultCha** [comment]
> kong start works fine, only make dev fails.

Curious because both use that same method from Luarocks.

**Comment by thibaultCha** [comment]
@thefosk What is the version of Luarocks you were using? I am on 2.2.0 instead of 2.2.1 as recommended, and never had the issue.

**Comment by thefosk** [comment]
I had the `2.2.1` when I had that problem. Now I am running the `master` branch of LuaRocks and it's working.

**Comment by thibaultCha** [comment]
If we just recommend 2.2.0 instead of 2.2.1 for now, we can close this. In fact we should recommend 2.2.0 of there isn't anything preventing us

**Comment by thefosk** [comment]
Can you replicate the problem with 2.2.1?

**Comment by thefosk** [comment]
I confirm that the problem happens only with `2.2.1` and not with `2.2.0`.

**Comment by thefosk** [comment]
I can close the issue since the bug has been identified.

**Comment by ignacio** [comment]
Guys, could you please take a look at the recently released LuaRocks 2.2.2 and see if it works for you?

**Comment by thefosk** [comment]
@ignacio it works with `2.2.2`. On a side note, on luarocks.org it's still mentioned version `2.2.1`.

**Comment by ignacio** [comment]
Thank you for confirming.
Yes, there is a PR pending to be merged:
https://github.com/leafo/luarocks-site/pull/53
