### ISSUE TITLE
kong 0.8.3 for Ubuntu 16.04

### ISSUE THREAD

**Issue by kishorgandham** [Mashape/kong#1320]
Hi,

I didnt find a deb installation file for Ubuntu 16.04 in the download section

https://getkong.org/install/ubuntu/

It would help if kong 0.8.3 for Ubuntu 16.04 is released. Secondly, openresty 1.9.7.5 packaged with kong is not built with http_v2_module. So, I am unable to setup http/2 with kong.

Cheers,
Kishor

**Comment by thibaultCha** [comment]
I can't talk for the Ubuntu 16.04 package, but OpenResty is not tested nor officially compatible with HTTP/2, hence why it is not enabled for Kong. If you wish to use Kong with HTTP/2, you are free to do so - at your own risk - by recompiling OpenResty from source.

**Comment by kishorgandham** [comment]
Thanks for the clarification. 

The openresty change log at https://openresty.org/en/changelog-1009007.html seems to indicate that 1.9.7.4 is compatible with http/2.

**Comment by thefosk** [comment]
I will generate an Ubuntu 16.04 package in the next version.

**Comment by alex-estela** [comment]
Hi, do you know more precisely when that next version / Ubuntu 16.04 package will be made available ? I did not find information about the next release date.
Thanks in advance.

**Comment by thefosk** [comment]
Hello - it's available here https://github.com/Mashape/kong/releases/download/0.8.3/kong-0.8.3.xenial_all.deb
