### ISSUE TITLE
multiple tokens can be generated from the same authorization code

### ISSUE THREAD

**Issue by chetankmalur** [Mashape/kong#1326]
During one of our automation testing, we found that the same authorization code can be used multiple times (within 5 minutes) to generate multiple access tokens (We ended up generating 300 token for every code). Although it was an inadvertent operation isn't it better to delete the authorization code after the token is generated. One of the security blog on OAUTH suggested that we should delete authorization codes after generating the token.

I added following line plugins/oauth2/access.lua and tested it and it deletes the code after token is generated
singletons.dao.oauth2_authorization_codes:delete({id = authorization_code.id})

Can you please let me if you see any issues with it.

**Comment by mleace** [comment]
We added the same for our setup, just behind 

response_params = generate_token(conf, client, authorization_code.authenticated_userid, authorization_code.scope, state)

**Comment by thefosk** [comment]
This should be fixed in 0.9 (you can experiment with the RC)
