### ISSUE TITLE
Unable to delete consumers whose usernames are UUIDs

### ISSUE THREAD

**Issue by jusw85** [Mashape/kong#1327]
As per topic, Kong 0.8.3 running in Docker.
I do not have this problem if the username isn't in UUID format.

```
$ curl -XPOST --url "http://${kong_host}:${kong_admin_port}/consumers/" --data "username=f9370867-115a-44d8-a0dc-587225699b12"
{"username":"f9370867-115a-44d8-a0dc-587225699b12","created_at":1466577030000,"id":"d8389a3d-0316-4e11-8af6-030cd2b63d7c"}
```

```
$ curl -XDELETE --url "http://${kong_host}:${kong_admin_port}/consumers/f9370867-115a-44d8-a0dc-587225699b12"
{"message":"Not found"}
```

**Comment by DonMartin76** [comment]
I guess Kong confuses its own internal GUIDs with your (external) GUIDs. You will get the internal ID back as a result of your `POST`; that will always work with the `DELETE`.

**Comment by Tieske** [comment]
Well, the username is a username, not a uuid. If you want a uuid, use the `custom_id` field instead of the `username` field.

Kong will check the provided value to be formatted as a valid uuid. If it passes that test, it's assumed to be the `id`, if it fails, it's assumed to be the `username`

**Comment by djeeg** [comment]
I just got hit by this too when creating JWT tokens for consumers.

I have the same UUID in custom_id field, though you can't make direct API calls against this UUID(without looking up the actual consumer id)

My test to proved out my assumption here that UUIDs only match the consumerID, was to prefix the username UUID with a known string, and this worked.

```
        SendForm(nconf.get("client:kong:url") + "/consumers", { username: "USERID-" + req.user.id }, [200, 201, 409])
            .then(function(result) {
                
                SendForm(nconf.get("client:kong:url") + "/consumers/" + "USERID-" + req.user.id + "/jwt", { }, [200, 201, 409])
```

Looks like this becomes my workaround
