### ISSUE TITLE
Invalid JWT token results in 500 Internal Server Error

### ISSUE THREAD

**Issue by nguilford** [Mashape/kong#1329]
Submitting a poorly formatted jwt token results in a 500 Internal Server Error instead of a 401.

**Kong Version:** 0.8.3

**Platform:** CentOS on Docker (from mashape/kong:0.8.3 docker image)

**Steps to reproduce:**
1) Create a new proxy api in kong
2) Enable jwt for your new api
3) Submit a request to your proxy api with the following header "Authorization: Bearer X"

**Result:**
500 Internal Server Error

**Expected:**
401 Unauthorized or 403 Forbidden

It looks like this is known, given the TODO on line 70 of kong/plugins/jwt/handler.lua in https://github.com/Mashape/kong/pull/1247. Since it's not clear whether or not it will be addressed in that PR, I am opening this issue to track it separately.

**Comment by Garethp** [comment]
If PR #1333 gets merged in to #1247, this will be addressed

**Comment by Tieske** [comment]
fixed in #1362
