### ISSUE TITLE
Admin API security

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#133]
In `kong.yml` it would be nice to have a configuration entry that protects the management API, for example:

``` yaml
admin_allowed_ips:
  - 127.0.0.1
  - 192.168.0.0/16
```

**Comment by thefosk** [comment]
Maybe this could be a plugin?

**Comment by ahmadnassri** [comment]
+1 for plugin

**Comment by sinzone** [comment]
EVERYTHING should be a plugin. the core kong as lightweight as possible.

**Comment by sinzone** [comment]
API Admin plugin

**Comment by montanaflynn** [comment]
> by default localhost, plugin to manage additional sources.

I like default how it is currently. Anyone in production will set up appropriate firewalls using iptables, AWS security groups, or running their Kong(s) in an internal private network which is blocked off from public access except for port 80. 

I agree with the plugin, it would be nice to have a whitelist & blacklist plus support for blocking subnets. This would allow us to be on par with nginx's `ngx_http_access_module`, and should be introduced not only for the admin API but also as a plugin available for any user created APIs.

**Comment by thefosk** [comment]
It's related to #379.

**Comment by thefosk** [comment]
We should find a way to use existing plugins for the admin API. @thibaultCha Including CORS, user authentication, IP whitelisting/blacklisting, etc. While still having the admin running separately.

This means that the plugin execution handlers in `kong.lua` need to be also used in the `content_by_lua` of the admin server on port `8001`. As opposed to the server on port `8000`, we decide which plugins are running and are installed on the Admin API.

**Comment by sinzone** [comment]
Kong Shield: can be new commercial solution.

Enterprise Admin Governance.

**Comment by sgulics** [comment]
How are people securing the admin api in production environments? I would assume that if someone added/changed/deleted an API through the ADMIN API, you would want to know who did it.

**Comment by thibaultCha** [comment]
They put the port behind a firewall for internal usage only.

**Comment by thefosk** [comment]
@sgulics as per proper authentication and activity logging, this is related to #380

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [admin-api security](https://trello.com/c/rjWs0OrK/24-admin-api-security)

**Comment by coopr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Admin Authentication, Admin API security, Plugins on Admin API](https://trello.com/c/8Xmdxpy0/25-admin-authentication-admin-api-security-plugins-on-admin-api)

**Comment by p0pr0ck5** [comment]
We have published a doc that highlights some of the best practices we suggest when considering securing the Admin API: https://getkong.org/docs/0.10.x/secure-admin-api/

**Comment by p0pr0ck5** [comment]
Worth noting here that Kong Enterprise [now supports RBAC](https://getkong.org/docs/0.10.x/secure-admin-api/#role-based-access-control)! 

Not sure how much value is left in keeping this issue open...
