### ISSUE TITLE
OAuth2 plugin with implicit grant flow does not output the access token in the fragment

### ISSUE THREAD

**Issue by saponace** [Mashape/kong#1334]
Hi,

When using the OAuth plugin on my APIs, I can set the flow to implicit grant and everything works great (I get an access token back that works).

There is however something I am concerned about: The redirect URI sent by Kong in response looks like: http://redirect-domain.com/path?access_token={access_token}&expires_in={expiration_delay}&token_type=bearer (access token in the query string))
instead of: http://redirect-domain.com/path#access_token={access_token}&expires_in={expiration_delay}&token_type=bearer (access token as a fragment)

The RFC 6749 (https://tools.ietf.org/html/rfc6749#section-4.2.2) says that with the implicit flow, the access token should be returned in the fragment, and not in the query string of the URL.

Is that an intended feature ?

Thanks !

EDIT: I'm having this behaviour with Kong 8.1

**Comment by thefosk** [comment]
This is a bug and will be fixed in the next version.

**Comment by thibaultCha** [comment]
Resolved with #1408, thanks for the report.
