### ISSUE TITLE
Kong reports read errors in cassandra as timeouts

### ISSUE THREAD

**Issue by ThorArakis** [Mashape/kong#1343]
I'm currently running kong v7 app code against a database (cassandra) that has already had v8 migrations run on it. This results in a database state where v7 kong is unable to proxy any requests for apis with plugins, because it throws errors when accessing the plugins table. 

However kong is erroneously reporting the error as a database timeout instead of the database error. This is a bit misleading when trying to diagnose database migration failures.

**Comment by thefosk** [comment]
@thibaultCha maybe has some more thoughts on this

**Comment by thibaultcha** [comment]
Any update on this? Error logs or anything useful to look at?

**Comment by ThorArakis** [comment]
Yeah I should have appended logs when I originally saw it. But given that it was a v7 code base with DAO related issues, I'd say the behavior is most likely very different in the new versions given the DAO rewrite :)

I'll reopen if I repro on the newer versions of kong.
