### ISSUE TITLE
Port number is stripped from `Host` http header.

### ISSUE THREAD

**Issue by jarl-dk** [Mashape/kong#1347]
When a http request hits kong with a http header `Host: en.wikipedia.org:8080` then Kong correctly forwards this http header, but it strips off the port number.

According to wikipedia (https://en.wikipedia.org/wiki/List_of_HTTP_header_fields) This http header should contain the host and port (unless it is standard according to protocol scheme). Therefor I expect Kong to respect this and keep the complete value (including the port number)

**Comment by thibaultCha** [comment]
I believe this to be Nginx behavior since Kong's proxying is transparent. Have you tried
```
proxy_set_header Host $http_host;
```

in the Nginx config?

**Comment by Tieske** [comment]
@jarl-dk any update on this?

**Comment by Tieske** [comment]
scheduled for 0.10, fixed in #2045
