### ISSUE TITLE
PUT to plugin endpoint on admin API throws 409 Conflict

### ISSUE THREAD

**Issue by nicklanng** [Mashape/kong#1348]
Hi

`
curl -X PUT http://localhost:8001/apis/testAPI/plugins/ --data "name=key-auth"
`

The documentation says that this should create or update the plugin, but it's throwing a 409 as if it's a POST request.

```
<html>
<head><title>409 Conflict</title></head>
<body bgcolor="white">
<center><h1>409 Conflict</h1></center>
<hr><center>openresty/1.9.7.5</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Comment by thibaultCha** [comment]
That is indeed a known limitation of the PUT implementation right now, see:

https://github.com/Mashape/kong/blob/master/spec/integration/04-admin_api/apis_routes_spec.lua#L131

**Comment by thibaultcha** [comment]
Closing this as this limitations is currently known.

**Comment by channgli** [comment]
@nicklanng  how did you fix this issues ? i can not open the link that you provide

**Comment by nicklanng** [comment]
Hi @channgli, as far as I remember, I think we just had to check for the existence of the key and create or update as necessary.
