### ISSUE TITLE
`no request found`

### ISSUE THREAD

**Issue by jney** [Mashape/kong#1349]
hi, while executing this code in a king plugin:

```lua
local redis = require('resty.redis')
local red = redis:new()
```

I've got the following error

```
2016/06/28 16:34:42 [error] 62#0: [lua] kong.lua:168: init(): Startup error: /app/.heroku/share/lua/5.1/kong/tools/utils.lua:211: /app/.heroku/lualib/resty/redis.lua:101: no request found
```

it seems there are missing libraries to run redis. do you have any idea how to fix it ?

**Comment by thibaultCha** [comment]
You must be using this module in the `init_by_lua` context where it is not supported due to the cosocket API limitations. 
This is expected in OpenResty, see https://github.com/openresty/lua-nginx-module/issues/206 for more information since the issue is not Kong-related and lua-resty-redis is not developed by us.

**Comment by jney** [comment]
thank you for the support @thibaultCha 
any advice to store/access session data ? 
should it be initialized in `CustomHandler:init_worker` ?
Is cassandra more appropriate than redis to this in an openresty context ?

**Comment by thibaultCha** [comment]
`init_worker` is not supported by the cosocket API either, see the list of supported contexts in the [ngx_lua documentation](https://github.com/openresty/lua-nginx-module#tcpsockconnect).

Cassandra is no more appropriate than any other solution, but the lua-cassandra driver implements a workaround that allows it to be used inside of the `init` and `init_worker` contexts by relying on LuaSocket. See [socket.lua](https://github.com/thibaultCha/lua-cassandra/blob/master/src/cassandra/socket.lua) and [lua-resty-socket](https://github.com/thibaultCha/lua-resty-socket).

The OpenResty team is eagerly waiting for contributions to add support for the cosocket API inside of the `init` contexts, consider this solution a temporary workaround at the only cost of depending on LuaSocket instead (which we find totally reasonable). I do not know where the OpenResty team stands regarding adding this workaround to lua-resty-redis.
