### ISSUE TITLE
Automatically proxy new docker containers?

### ISSUE THREAD

**Issue by dcowden** [Mashape/kong#1352]
In the docker world, the well-known nginx-proxy container will automatically configure nginx to proxy containers by watching the docker backplane.

Kong is awesome, but it would be _more_ awesome if it watched the docker backplane, and automatically proxied new containers.

On a related note, it would also be awesome if it could serve as a kubernetes ingress controller.

**Comment by sinzone** [comment]
@dcowden for Kubernetes we're just releasing GKE support: https://github.com/Mashape/getkong.org/pull/250

**Comment by sinzone** [comment]
Also https://github.com/EwanValentine/KongBeat/blob/master/README.md

**Comment by thefosk** [comment]
If you need a Docker Compose distribution instead, you can take a look at https://github.com/Mashape/docker-kong/tree/docker-compose/autopilot

I will publish the Docker Compose to the website soon.

**Comment by micheleorsi** [comment]
Hello guys, how's going with that merge?
Actually I am interested in running kong not in GKE, but in a Kubernetes bare metal cluster. So I would need something similar to [this](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx).

Have you got a roadmap for that integration?

**Comment by thefosk** [comment]
@shashiranjan84 may have some comments on the Kubernetes request.

**Comment by shashiranjan84** [comment]
@micheleorsi we do have simple Kong templates to run any Kubernetes managed cluster.

https://github.com/Mashape/kong-dist-kubernetes

**Comment by micheleorsi** [comment]
Thank you @shashiranjan84, but at the moment we are running a non-managed Kubernetes cluster .. Have you got other resources available for such situations? Basically we have a bare metal cluster managed by ourselves

**Comment by shashiranjan84** [comment]
@micheleorsi currently no, you can get enough help on K8 site or online to get a K8 managed cluster.
