### ISSUE TITLE
Inconsistencies on "upstream_url" and cached upstream URL in nginx/Kong (version 0.8.1)

### ISSUE THREAD

**Issue by jmdacruz** [Mashape/kong#1355]
Run into an interesting situation today, for which I couldn't find an open (or closed issue). We have a testing environment in which we continually deploy and destroy services, which means that APIs are registered and unregistered with a relatively high frequency (~5 times a day)

We found that one particular API was failing (timing out). The registered upstream URL seemed to be just fine, and hitting the service directly was working fine too. When we got into the logs we saw something interesting: Kong was logging an error entry in `error.log` saying that the upstream service was not reachable, but the IP address that it was listing was not the one that was registered as the upstream URL. Inspecting the information for the APIs via de admin API listed the correct upstream URL, but somehow Kong (or nginx) was using a different IP address (which we can only assume was an old IP address for a previous incarnation of the service).

When we modified the `upstream_url` of the service via the admin API by entering a dummy value and then reverting back to the same value (modifying the existing API, which already had plugins registered, not deleting it and re-adding it), the API magically started working again via Kong.

Any thoughts on what might be going on? This issue is not easy to reproduce, but it all points to some inconsistency or race condition.

**Comment by thefosk** [comment]
@jmdacruz I will be curious to replicate this with our first 0.9 RC1 once we release it, since we did some improvements to our clustering management. I will ping here once we release it (hopefully by this month).

**Comment by Tieske** [comment]
@jmdacruz does this issue still exist? have you migrated to the 0.9.x releases?

**Comment by jmdacruz** [comment]
@Tieske We haven't seen this issue in the wild again on 0.8.3 (we didn't really try to reproduce it, and it didn't occur naturally), and we haven't yet updated to the 0.9.x releases (we'll do that as soon as we possibly can). Given that the issue seemed to happen after a few registration/unregistrations cycles, and that there is a workaround (forcing the modification of the API, which triggers the invalidation of the cache, hence forcing Kong to re-read the configuration) I'd say this is low priority.

**Comment by Tieske** [comment]
ok, closing this for now. Feel free to reopen.
