### ISSUE TITLE
ditch CHANGELOG.md in favor of github releases

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#136]
maintaining a single markdown file will get lengthy and harder as you add more releases.

Github Releases, not only shows the appropriate release names / tag / assets, but is also Markdown powered, so you end up with a better "change log" that's also paginated, with direct links to versioned tag  + release assets.

**Comment by thibaultCha** [comment]
I prefer a change log.

**Comment by ahmadnassri** [comment]
can we at least update the release description in Github Releases with meaningful info?

**Comment by thibaultCha** [comment]
you can do it if you want but I think it'll be useless. 

A changelog is:
- more flexible
- less relying on github
- easier to search in
- part of the git history

From there, I see no reason to write things in releases or to duplicate information between the two. Except for a link to the changelog section.

**Comment by Nijikokun** [comment]
generally projects do both, so, in the famous words of zoidberg, *"why not both?"*

by doing releases, you create the changelog snippet there, and just copy it over to `changelog.md` or *vice versa*

**Comment by ahmadnassri** [comment]
also thinking of other projects to keep consistent.

**Comment by thibaultCha** [comment]
We'll update release notes. let's stop nitpicking
