### ISSUE TITLE
Oauth2 `redirect_uri` validated improperly for the issue_token endpoint

### ISSUE THREAD

**Issue by mrosales** [Mashape/kong#1363]
This relates to the OAuth2 plugin's `/oauth2/token` endpoint and the associated documentation.

The `redirect_uri` parameter should really not be included at all here because it is not relevant to the OAuth protocol (and is [not in the spec for this section](https://tools.ietf.org/html/rfc6749#section-4.1.3))

The [kong-oauth2-hello-world](https://github.com/Mashape/kong-oauth2-hello-world) example includes the lines at the bottom to explain the endpoint:

```
curl https://127.0.0.1:8443/oauth2/token \
     -H "Host: test.com" \
     -d "grant_type=authorization_code" \ 
     -d "client_id=318f98be1453427bc2937fceab9811bd" \ 
     -d "client_secret=efbc9e1f2bcc4968c988ef5b839dd5a4" \
     -d "redirect_uri=http://getkong.org/" \ 
     -d "code=ad286cf6694d40aac06eff2797b7208d" --insecure
```

The problem is that the plugin attempts to validate the `redirect_uri` if it is present. The plugin improperly validates the uri in the `get_token()` function ([source here](https://github.com/Mashape/kong/blob/master/kong/plugins/oauth2/access.lua#L267)), because the parameter is a string, and the `redirect_uri` that it is matching it against is really an array of `allowed_redirect_uris`. 

If the redirect_uri is going to continue to be allowed for this endpoint, the validation function should be updated to properly check to see if the table contains the url instead of matching for equality.

See how the `authorize()` function handles this same thing. For example, compare the two lines below to illustrate the difference:

    -- authorize() line 147
    allowed_redirect_uris, client = get_redirect_uri(parameters[CLIENT_ID])

    -- issue_token() line 261
    local redirect_uri, client = get_redirect_uri(client_id)

**Comment by thibaultCha** [comment]
Fixed with #1405, thanks for the report!
