### ISSUE TITLE
API not found with these values

### ISSUE THREAD

**Issue by rbrtmrtn** [Mashape/kong#1365]
I'm attempting to set up a test instance of Kong with an endpoint that points to `mockbin.com`, per the [docs](https://getkong.org/docs/0.8.x/getting-started/adding-your-api/). However, I'd like to use the `request_path` param so I don't have to pass in a `Host` header. So I created the endpoint like so:
```
$ curl -i -X POST \
  --url http://localhost:8001/apis/ \
  --data 'name=mockbin' \
  --data 'upstream_url=http://mockbin.com/' \
  --data 'request_path=/mockbin'
```
But when I try to `curl http://localhost:8000/apis/mockbin` I get a response of:

`{"request_path":"\/apis\/mockbin","message":"API not found with these values","request_host":["localhost"]}`

Can anyone tell me what I'm doing wrong? Any tips would be much appreciated.

**Comment by thibaultCha** [comment]
I suggest you read the [Proxy Reference](https://getkong.org/docs/latest/proxy/) to better understand how to map incoming requests to registered APIs.
In that case, you are adding the unnecessary `/apis/` prefix to your URI which is misleading Kong.
