### ISSUE TITLE
Consumer scope 

### ISSUE THREAD

**Issue by mavencode01** [Mashape/kong#1375]
Am integrating Kong oAuth2 plugin with my services but I would like to have different scopes (permission) for different consumers.

Right now, upstream services have no way to know if the scopes or permissions the consumer passed in is validated.

Any solution for this?

**Comment by thefosk** [comment]
@mavencode01 you can have multiple scopes per different consumers, and the accepted scopes are readable from the upstream service in a `X-Authenticated-Scope` request header.

Does this answer your question?

**Comment by mavencode01** [comment]
Yes, thanks @thefosk
