### ISSUE TITLE
Loadbalancing with Kong

### ISSUE THREAD

**Issue by Kenovo** [Mashape/kong#1376]
Hello, im a new user of Kong, i want to implement it as an api gateway in a microservice architecture and i want to know if i can route and loadbalance the trafic from an api path to multiple Vms endpoints.

( ps: i use Kongfig )

Thank you

**Comment by thibaultCha** [comment]
Load balancing is not natively supported by Kong yet, but check the existing issues for possible solutions/implementation updates about it: https://github.com/Mashape/kong/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20load%20balancing
