### ISSUE TITLE
How to implement kong OAuth2.0 with java 

### ISSUE THREAD

**Issue by CMTHM** [Mashape/kong#1378]
Hi ,

Can anyone give some idea or suggestion how can I implement my war file (UI) and run with kong ?

**Comment by thefosk** [comment]
This is a very specific question on Java - you can follow the doc at https://getkong.org/plugins/oauth2-authentication/ and implement it with a language of your choice. I would ask to a Java forum if they can give more specific support. 

Pretty much all you need to do on your side is being able to make HTTP requests.
