### ISSUE TITLE
CORS methods are not working in 0.8.0

### ISSUE THREAD

**Issue by DaniyalGeek** [Mashape/kong#1380]
i enabled cors plugin on apis with only get method but its working with all methods

**Comment by thefosk** [comment]
Can you try to update to 0.8.3?

**Comment by DaniyalGeek** [comment]
Yes i use 0.8.3 but its still not working?
On Jul 12, 2016, at 11:32 PM, Marco Palladino <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you try to update to 0.8.3?

**Comment by DaniyalGeek** [comment]
i just want to block POST method on my API that any consumer cannot POST method

am i using correct plugin?

**Comment by thibaultCha** [comment]
The CORS plugin does not intend to "block" HTTP methods. CORS is a client-side enforced mechanism (generally enforced by web browsers): https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

There is currently no plugin I know of to prevent the execution of particular HTTP methods on an API. But this should be easily doable and/or enforced on the API itself.

**Comment by DaniyalGeek** [comment]
oh ok i got it 
sois there anyway to restrict the HTTP methods so consumer cannot DELETE or POST on API i am doing for secruity only

**Comment by thibaultCha** [comment]
> There is currently no plugin I know of to prevent the execution of particular HTTP methods on an API. But this should be easily doable and/or enforced on the API itself.

Closing this for now, considering it answered.
