### ISSUE TITLE
Can Kong Authenticate browser apps

### ISSUE THREAD

**Issue by dcowden** [Mashape/kong#1382]
I'm running a docker registry, which is a perfect case of a service to put behind kong.  I can use plugins to get all kinds of auth options,without doing the docker-specific weirdo setup. Great!

But, i'm also running a registry ui, which is a UI application, not a REST service.  In this case, I want to prompt the user interactively for login ( using LDAP or another interactive OAuth provider).

Question: will this work?  It appears that Kong is designed for APIs, but can it be used to front browser apps as well, and provide metrics/auth for those too?

**Comment by shashiranjan84** [comment]
@dcowden are you talking about session handling? Currently all plugin handles requests in stateless pattern except we do cache data in memory to save calls Kong Database. But I don't think it would be difficult to create plugin which cache session and run relevant logic.
