### ISSUE TITLE
Handle `unlimited` ulimit

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#1384]
Handle the ulimit value in the CLI when it's `unlimited` and not a numeric value.

**Comment by Tieske** [comment]
This sets/influences the values for; `worker_rlimit_nofile` and `worker_connections`.

should they be removed and left to the user to optimize (directly nginx config)?

**Comment by thefosk** [comment]
It seems like by default `worker_rlimit_nofile` sets the value of the ulimit, so we can avoid setting it explicitly. But `worker_connections` by default is `512` and that definitely needs to be increased.

**Comment by Tieske** [comment]
What is the proper value then?

imo 2 options;
1. we retain current behaviour, but explicitly need to set a number when its "unlimited"
2. only retain `worker_connections` and make it configurable in the config file
