### ISSUE TITLE
Routing Consul via Kong ?

### ISSUE THREAD

**Issue by Kenovo** [Mashape/kong#1387]
Hello, i use consul service discovery in a microservice architectur on an openstack envirement, and i use kong to expose microservices apis to other openstack tenants, i want to know if i can expose consul (as a service) and route all the WAN gossip trafic with kong to local consul servers (TCP/UDP trafic, NOT HTTP), can i do that with kong ? it is a good idea to do so ? 

(im looking for a way to connect consul servers on multi openstack tenants without having publique ip adresses on those servers)

Thank you :)

**Comment by Tieske** [comment]
Sorry, Kong only does http.
