### ISSUE TITLE
avoid Kong SPOF

### ISSUE THREAD

**Issue by Kenovo** [Mashape/kong#1388]
Hello, 
i want to expose my APIs via KONG but i dont want to have a single KONG Server beacause of Sing point of failure problems, it is any tools / config provided by Kong to do so ? 

Thank you

**Comment by Tieske** [comment]
Kong already does this out of the box.

You can set up a Kong cluster. Multiple Kong nodes can join the same cluster and hence provide resilience. You'd need a loadbalancer in front of it to distributed the incoming requests over the nodes. 

Other than that you need to setup the datastore in a resilient manner, see the Postgres and/or Cassandra docs for that.
