### ISSUE TITLE
CORS plugin 

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/kong#139]
It's a common task to enable CORS for an API so it would be a good plugin. This [node.js middleware](https://github.com/troygoode/node-cors) has over 100k downloads in the last month and would be a good inspiration for various options. Once it's done and Kong is officially announced we could ask to be included on [this website](http://enable-cors.org/server.html) that shows how to enable CORS in many popular servers.

**Comment by SGrondin** [comment]
:+1: very good suggestion

**Comment by Nijikokun** [comment]
I've started on this, and it is almost complete, currently in testing.
