### ISSUE TITLE
LDAP-Auth plugin giving bad argument error

### ISSUE THREAD

**Issue by jescochu** [Mashape/kong#1393]
Using Kong 0.8.3

I am having an issue with the ldap-auth plugin. Every request I send to my ldap-auth enabled endpoint throws a 500 error. Here is the plugin configuration:
	
	$ curl http://192.168.99.101:8001/apis/test/plugins
	{"data":[{"api_id":"742ecd3a-3597-4a1b-b985-b2d2a528bd1f","id":"a2d8f9bf-3780-4dca-81e0-a5843a3e18bb","created_at":1468445673000,"enabled":true,"name":"ldap-auth","config":{"ldap_port":3269,"cache_ttl":60,"timeout":10000,"start_tls":true,"hide_credentials":true,"ldap_host":"REDACTED","base_dn":"dc=ad,dc=ea,dc=com","verify_ldap_host":false,"keepalive":60000,"attribute":"cn"}}],"total":1}

Here is an example of a request to an endpoint:

	$ curl -v -H 'Authorization: LDAP REDACTEDBASE64ENCODEDSTR' http://192.168.99.101:8000/test/location
	*   Trying 192.168.99.101...
	* Connected to 192.168.99.101 (192.168.99.101) port 8000 (#0)
	> GET /test/location HTTP/1.1
	> Host: 192.168.99.101:8000
	> User-Agent: curl/7.43.0
	> Accept: */*
	> Authorization: LDAP REDACTEDBASE64ENCODEDSTR
	>
	< HTTP/1.1 500 Internal Server Error
	< Date: Wed, 13 Jul 2016 21:48:37 GMT
	< Content-Type: text/plain; charset=UTF-8
	< Transfer-Encoding: chunked
	< Connection: close
	< Server: kong/0.8.3
	<
	An unexpected error occurred
	* Closing connection 0

On the actual Kong container I see this in the error log corresponding to each request I make:

	2016/07/13 21:48:37 [error] 117#0: *47 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/plugins/ldap-auth/ldap.lua:34: bad argument #1 to 'bunpack' (string expected, got nil)
	stack traceback:
	coroutine 0:
		[C]: in function 'bunpack'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/ldap.lua:34: in function 'claculate_payload_length'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/ldap.lua:117: in function 'start_tls'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:47: in function 'ldap_authenticate'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:75: in function 'cb'
		/usr/local/share/lua/5.1/kong/tools/database_cache.lua:128: in function 'get_or_set'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:72: in function 'authenticate'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:98: in function 'execute'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/handler.lua:12: in function 'access'
		/usr/local/share/lua/5.1/kong.lua:188: in function 'access'
		access_by_lua(nginx.conf:98):2: in function <access_by_lua(nginx.conf:98):1>, client: 192.168.99.1, server: _, request: "GET /test/location HTTP/1.1", host: "192.168.99.101:8000"

I don't really know Lua too well but doing a basic scan through those lines of code:

`packet = socket:receive(2)`
`_, packet_len = claculate_payload_length(packet, 2, socket)`

https://github.com/Mashape/kong/blob/master/kong/plugins/ldap-auth/ldap.lua#L116

It looks like the var "packet" is the nil in this case that is supposed to be a string.

Even when I do not enable TLS I get a nearly identical error:

	2016/07/13 21:58:32 [error] 117#0: *72 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/plugins/ldap-auth/ldap.lua:34: bad argument #1 to 'bunpack' (string expected, got nil)
	stack traceback:
	coroutine 0:
		[C]: in function 'bunpack'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/ldap.lua:34: in function 'claculate_payload_length'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/ldap.lua:65: in function 'bind_request'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:57: in function 'ldap_authenticate'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:75: in function 'cb'
		/usr/local/share/lua/5.1/kong/tools/database_cache.lua:128: in function 'get_or_set'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:72: in function 'authenticate'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:98: in function 'execute'
		/usr/local/share/lua/5.1/kong/plugins/ldap-auth/handler.lua:12: in function 'access'
		/usr/local/share/lua/5.1/kong.lua:188: in function 'access'
		access_by_lua(nginx.conf:98):2: in function <access_by_lua(nginx.conf:98):1>, client: 192.168.99.1, server: _, request: "GET /test/location HTTP/1.1", host: "192.168.99.101:8000"

Now it gets called from bind_request instead of start_tls. Have I maybe configured something incorrectly? We have APIs that handle auth on their own using this same AD server for LDAP auth.

**Comment by shashiranjan84** [comment]
@jescochu can you try running this command from container

ldapsearch -H ldap://ec2-54-210-29-167.compute-1.amazonaws.com:389 -x -D "uid=einstein,ou=scientists,dc=ldap,dc=mashape,dc=com" -W

Change host and DN to hit your LDAP server.

**Comment by jescochu** [comment]
I am able to get ldapsearch to work:

	# extended LDIF
	#
	# LDAPv3
	# base <dc=ad,dc=ea,dc=com> with scope subtree
	# filter: cn=easwops
	# requesting: ALL
	#

	# easwops, New - User Accounts - Service, eac.ad.ea.com
	dn: CN=easwops,OU=New - User Accounts - Service,DC=eac,DC=ad,DC=ea,DC=com
	objectClass: top
	objectClass: person
	objectClass: organizationalPerson
	objectClass: user
	cn: easwops
	distinguishedName: CN=easwops,OU=New - User Accounts - Service,DC=eac,DC=ad,DC
	 =ea,DC=com
	instanceType: 4
	whenCreated: 20090825180929.0Z
        ......
        ......
        ......

I can also get the plugin to work if I disable TLS and swap to our server's LDAP port (rather than LDAPS).

In case it helps, I have not imported the cert for our server into the container, so I have to add `TLS_REQCERT never` to the ldap.conf to make the ldapsearch work, however I am also never enabling `verify_ldap_host` in the plugin.

**Comment by shashiranjan84** [comment]
TLS_REQCERT is for client authentication. To just make communication b/w kong server and ldap server encrypted, enable 'start_tls' in plugin config and use LDAP port only.

**Comment by jescochu** [comment]
Thank you @shashiranjan84 it does work if I just use LDAP port, so I'll close the issue.

Is LDAPS support incoming? If not, the docs might make it more clear that attempting to connect through LDAPS will result in a nondescript error.

**Comment by fabiorphp** [comment]
I have the same problem, in our case the attribute used is "sAMAccountName"

**Comment by shashiranjan84** [comment]
@fabiorphp follow https://github.com/Mashape/kong/issues/1821 for debugging.

**Comment by Djalmar** [comment]
@jescochu any issue requesting LDAPS support ?
