### ISSUE TITLE
'lua_ssl_verify_depth' has to be configurable

### ISSUE THREAD

**Issue by jmdacruz** [Mashape/kong#1395]
Currently, the nginx configuration file/template includes a way to provision the trusted SSL certificates for Cassandra (via the `cassandra.ssl.certificate_authority` configuration), but there is no way to configure other parameters such as the validation depth (`lua_ssl_verify_depth`). This parameter is vital in the scenario where the certificate for Cassandra is issued by an intermediate CA, which in turn is rooted on a root CA (which makes the validation depth at least `2`).

Right now the workaround is to tweak the nginx configuration template inside the kong configuration file to add this value. This issue is somewhat related to #1188, since it applies not only to the Cassandra configuration, but any module trying to use nginx cosockets to talk to external services protected with TLS

**Comment by thibaultCha** [comment]
I agree. While this is very easily doable with the current configuration file (simply adding the directive in the `nginx` section is not much harder than modifying a yaml property), the new CLI does not expose the Nginx configuration out of the box, making this a bit more tedious.

**Comment by jmdacruz** [comment]
Agree, that's how we are doing it right now on 0.8.3. I was thinking about the new CLI too.

**Comment by thibaultCha** [comment]
Implemented with #1420.
