### ISSUE TITLE
Single numerical primary key breaks with postgres DB

### ISSUE THREAD

**Issue by jaredpetker** [Mashape/kong#1401]
I am using SERIAL / INTEGER primary keys on some of my tables, and kong seems to have issues with this when using setting this column as the primary key, the issue seems to be here

https://github.com/Mashape/kong/blob/master/kong/dao/postgres_db.lua#L171

In relation to the ttls table / query that gets ran when there is only 1 primary key (note when you use more than one primary key, a simpler query code path is used). Since my primary key is numerical, the "join on" portion of the statement fails since it tries to compare my table's primary key (an int) to a ttls table column (which is text).

I have bypassed this issue by doing this in my daos.lua

```
primary_key = {"id", "id"},
```

Which is quite the hack, but at least the code path with the simple select query is ran which works for me.

Unsure of what a good solution for this is or if it's mean to be this way, but seems like from reading other portions of the codebase point to the fact that numerical primary keys should work.

**Comment by thibaultcha** [comment]
The DAO is not meant to be used with integer primary keys, only uuids. If you wish to use integer primary keys, you should bypass the DAO and write your own queries.

**Comment by thibaultcha** [comment]
(A patch fixing this is of course welcome, but ideally we'd rather discourage such usage of the DAO since a Cassandra/Postgres interoperability - think migrating between the two - is preferable for us).
