### ISSUE TITLE
CSV import export problem with table plugins 

### ISSUE THREAD

**Issue by DaniyalGeek** [Mashape/kong#1410]
### Summary
when i import csv from plugins then it copy prefectly but when importing it gives me error 

### Steps To Reproduce

1. copy plugins from 'plugins.csv';
2. delete all plugins 
3. copy plugins to 'plugins.csv';
4. got error

### Additional Details & Logs

ERROR 

`Failed to import 1 rows: ParseError - badly formed hexadecimal UUID string,  given up without retries
Failed to process 1 rows; failed rows written to import_kong_plugins.err`

- Kong version (`0.8.3`)

**Comment by Tieske** [comment]
Kong doesn't import csv. Are you using some tool to manage Kong? Then you should probably contact the author of that tool.

**Comment by DaniyalGeek** [comment]
yes this is from cassandra but i think this problem relates to   migration uuid and primary because i checked import export on other schemas like apis and consumers but these are working perfectly

**Comment by Tieske** [comment]
@thibaultCha any ideas? still seems like a Cassandra devops problem to me. I don't see what Kong itself has to do with this...

**Comment by thibaultcha** [comment]
Yeah sorry, I really don't see a reason why the plugins in particular would fail compared to the others. Feel free to give us more info and if you eventually resolved this.

**Comment by tedpearson** [comment]
Most likely this issue: https://issues.apache.org/jira/browse/CASSANDRA-11549

**Comment by thibaultcha** [comment]
Considering this answered.
