### ISSUE TITLE
Method Restriction

### ISSUE THREAD

**Issue by fabiorphp** [Mashape/kong#1411]
Idea: Plugin that restrict api access only with allowed http methods.

Example:

I have a api to manage categories (GET, POST, PUT and DELETE), but for some user, I need that the user has access only the GET method, and for another user, only POST and PUT methods.

Plugin usage:

``` sh
curl -X POST http://kong:8001/apis/mockbin/plugins \
    --data "name=method-restriction" \
    --data "config.methods=GET, POST, PUT, DELETE"

curl -X POST http://kong:8001/apis/mockbin/plugins \
    --data "name=method-restriction" \
    --data "config.methods=GET" \
    --data "config.consumer_id=876bf719-8f18-4ce5-cc9f-5b5af6c36007"
```

**Comment by thibaultcha** [comment]
(This will be included in the upcoming new router, which will enable a more complex routing of incoming traffic to upstream services. APIs will be defined with:
```json
{
  "name": "",
  "uris": ["/path1", "/path2"],
  "headers" : {
    "Host": ["domain.com"],
    "X-API": ["api-xxx", "api-yyy"]
  },
  "methods": ["GET", "POST", "X-CUSTOM"]
}
```

In this model, all properties must match except the ones with several values (X-API, uris and methods), for which only one is enough to fulfill the requirement. Removing the beginner label for now and putting this under the `0.10` milestone.

**Comment by fabiorphp** [comment]
But, after this new feature the PR #1414 will be necessary?

**Comment by thibaultcha** [comment]
#1411 would still be relevant for Consumer-level method restriction I believe. The new resolver mentioned would globally restrict APIs to the specified methods, but there is still room for a plugin taking care of this at the Consumer level.

**Comment by gabel** [comment]
A basis restriction will only be the first step. I agree with thibaultcha, that a consumer level restriction to methods should be the final target. We have exact that use case....

**Comment by fabiorphp** [comment]
I agree guys.

So, I will wait for a new version, after that, I will continue with the development.

**Comment by fabiorphp** [comment]
Well, I have been thinking about this customer plugin, and I have a two questions.

1 - The priority will be greater than API restriction?
2 - ACL integration?

**Comment by thibaultcha** [comment]
An update on this: see the [feat/new-router](https://github.com/Mashape/kong/tree/feat/new-router) branch to track the progress on the new router which will implement method restriction directly into the core.

Also, I'll be closing this as we consider it part of #505, thanks!

**Comment by HenryChelsea** [comment]
@thibaultcha  awesome!!!
