### ISSUE TITLE
Request Size Limiting Plugin Payload Size Miscalculation

### ISSUE THREAD

**Issue by nicklanng** [Mashape/kong#1415]
### Summary

The documentation makes it clear that the allowed payload size should be in megabytes, 128 should mean 128,000,000 bytes.
https://getkong.org/plugins/request-size-limiting/

When we use this plugin we find that 128 will actually give a size limit of 12,800,000 bytes.
If we look at the code the offending line is quite clear:
https://github.com/Mashape/kong/blob/master/kong/plugins/request-size-limiting/handler.lua#L14
I believe this number multiplied by the payload size should have an extra 0.

### Steps To Reproduce

1. Add a request size limiting plugin to your API 
2. Set the request size limit to 10
3. Create a file called test in your home folder of size 9MB.
4. Run: `curl -X "POST" -i --data "@~/test" http://localhost:8000/{your api request path}`
5. The request is rejected.

### Additional Details & Logs

- Kong version: 0.8.3
- Operating System: CentOS

**Comment by Tieske** [comment]
So it seems! good catch. Thx

**Comment by Tieske** [comment]
fixed in #1416
