### ISSUE TITLE
Self-signed upstream cert

### ISSUE THREAD

**Issue by cookandy** [Mashape/kong#1419]
### Summary

Hello,

When I send traffic to an upstream haproxy server via https (using SNI on haproxy), my requests via kong fails.  Is there a way to import my HAProxy self-signed cert into kong?

### Steps To Reproduce

1.  Install Kong
2.  Create self-signed cert for upstream service (called `service`)
3.  `curl -i -X POST --url http://localhost:8001/apis/ --data 'name=service' --data 'upstream_url=https://service.service.consul' --data 'request_host=test.com'`
4.  `curl -i -X GET --url http://localhost:8000/   --header 'Host: test.com'`

```
HTTP/1.1 503 Service Unavailable
Date: Tue, 19 Jul 2016 01:21:39 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache
X-Kong-Upstream-Latency: 461
X-Kong-Proxy-Latency: 0
Via: kong/0.8.3

<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```

Is there a way to import my HAProxy self-signed cert into kong?

### Additional Details & Logs

- Kong version (`$ kong version`):  **0.8.3**
- Kong configuration (registered APIs/Plugins & configuration file):  **NONE**
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Operating System  **CoreOS (running Kong docker image)**

**Comment by shashiranjan84** [comment]
I don't think Kong failed here because of SSL validation as you getting 503, is your service available at '<https://service.service.consul>' on port 443? you can try accessing upstream server over ssl after logging into the container.

**Comment by shashiranjan84** [comment]
@cookandy closing this ticket, reopen if problem persists.
