### ISSUE TITLE
API Fallback Plugin

### ISSUE THREAD

**Issue by rohanarya** [Mashape/kong#1431]
### Summary
When an upstream URL is not responding KONG a backup URL can be configured in KONG which will be used instead till the primary upstream comes back. For this maybe a status URL and a duration and http error code can be configured to mark a url bad and trigger the fallback.

**Comment by Tieske** [comment]
Duplicate #112

**Comment by sinzone** [comment]
also https://github.com/Mashape/kong/issues/154

**Comment by hxzhao527** [comment]
emmmm, maybe it is not the same with the other existing issues.

I want to find a way to config a special fallback content for the particular route/service, not just 503.
Is it possible?
