### ISSUE TITLE
Support for api routing through host header and request path at the same time

### ISSUE THREAD

**Issue by alexanderjardim** [Mashape/kong#1433]
At issue #1230 it was said that Kong does not support api routing through host header and request path at the same time.

I have a use case where I need to route requests using the patterns

api.subdomain1.com/v1/API1 => api1.internal/v1/subdomain1
api.subdomain2.com/v1/API1 => api1.internal/v1/subdomain2
api.subdomain1.com/v1/API2 => api2.internal/v1/subdomain1
api.subdomain2.com/v1/API2 => api2.internal/v1/subdomain2

Sadly, I can't change the url pattern in such a way that it works the way Kong expects it. Is there a way of doing this case in Kong? Do you have plans on making it possible?

**Comment by thibaultCha** [comment]
Yes, we are planning on adding support for this use case, the discussion is currently happening on #845, so I'll close this for now.
