### ISSUE TITLE
oauth2 plugin should support putting all endpoints on admin interface

### ISSUE THREAD

**Issue by djMax** [Mashape/kong#1434]
I believe that exposing the oauth2 endpoints to the "public" side of Kong can present a problem. If one wishes to use the authenticated_userid as the primary identification system for my APIs behind kong, then the only thing separating an oauth client from impersonating anyone is the provision_key for the api. Is that correct? If so, it seems an unpleasant reality in some cases - one that would be addressed if the oauth APIs were on the admin port and therefore only called by my services.

It's possible that using a signed value in authenticated_userid would address this, but that's not super pleasant either.

**Comment by thefosk** [comment]
Related to #1328.
