### ISSUE TITLE
LDAP-AUTH can't login with by users in sub OU

### ISSUE THREAD

**Issue by forhot2000** [Mashape/kong#1438]
### Summary

our ldap users is organized by OU, but I can't use users in sub OU to access apis, how can I support this case?

for example, we have two users
- `cn=user1,dc=example,dc=com`
- `cn=user2,ou=test,dc=example,dc=com`

and set ldap-auth plugin base on `dc=example,dc=com`, then, `user1` is passed, but `user2` is forbidden.

### Additional Details & Logs

- Kong version (0.8.3)

**Comment by shashiranjan84** [comment]
Currently LDAP plugin only support Bind authentication, which basically look for user in configured DN and do password verification on LDAP server. More ACL or role based features would be added in future roll out of the plugin.
