### ISSUE TITLE
x-forwarded-for header is not passed correctly

### ISSUE THREAD

**Issue by mortensoby** [Mashape/kong#1445]
### Summary

When a request with the _x-forwarded-for_-header set to '12.12.12.12' passes through Kong, the header is changed to '12.12.12.12, 12.12.12.12' in the forwarded request. 
### Steps To Reproduce
1. Send a request with the _x-forwarded-host_-header set.
### Additional Details & Logs
- Kong version 0.8.1
- Mac OS

**Comment by thefosk** [comment]
@mortensoby The system concatenates properly the header, in case the request goes through multiple proxies: https://en.wikipedia.org/wiki/X-Forwarded-For#Format

**Comment by mortensoby** [comment]
This is true, but the host after the comma should be the host from the request to Kong, not just a copy of the value of the _x-forwarded-for_ header. Eg _12.12.12.12, proxy.kong.internal_

**Comment by thibaultcha** [comment]
Moved to @2202. Thanks!
