### ISSUE TITLE
[WEBSITE] Plugin development guide link in the FAQ is broken

### ISSUE THREAD

**Issue by sey** [Mashape/kong#1446]
### Summary

The plugin development guide link is broken in the [FAQ](https://getkong.org/about/faq/#what-are-plugins), section "What are plugins?".
It is missing the kong version: docs//plugin-development 
And should be docs/0.8.x/plugin-development or maybe docs/latest/plugin-development.

**Comment by thibaultcha** [comment]
Thanks!
