### ISSUE TITLE
Failed to do ssl.https request

### ISSUE THREAD

**Issue by wenchma** [Mashape/kong#1460]
### Summary
When I call the https api  using ssl.https request, it will fail with connection close.
Check the ssl.https libs version:

```bash
$ luarocks list luasec
Installed rocks:
----------------

luasec
   0.5-2 (installed) - /usr/local/lib/luarocks/rocks
```
After I upgrade luasec from 0.5-2 to 0.6-1, the call succeed.

### Steps To Reproduce

1. call ssl.https request  on luasec 0.5-2 version  - Fail
2.call socket.http request  - success
3. upgrade luasec to 0.6-1
4. call ssl.https request  on luasec 0.6-1 version  - success

### Additional Details & Logs

- kong version: 0.8.3
- Kong configuration (registered APIs/Plugins & configuration file)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Operating System

**Comment by thibaultcha** [comment]
Additionally to the comment made in #1461, one should use a coroutine-based module inside of OpenResty. See one of the lua-resty-http modules available online.
