### ISSUE TITLE
Best practices for allowing developers to manage their own API endpoint configuration

### ISSUE THREAD

**Issue by dselans** [Mashape/kong#1465]
Hi there!

Are there any best practices written up for how to allow developers (ie. service owners) to define/manage the configuration of the API gateway?

Something like this (but better):

1. Have a "api-gateway-configs" repo
2. Developer submits a config/script for their service name (ie. my-auth-service.sh) that configures the API gateway; opens a PR
3. Another dev or API gateway owner(s) review and merge the PR
4. Automated deployment of updated API configuration via hooks/jenkins/etc.

Step 2 could be abstracted with YAML and have a "processor" during step 4 perform all the necessary `curl`'ing, but there are still some areas that aren't clear - how to keep credentials out of source?

Has anyone done this, who manages the config of your API gateway(s)?

Note: To be perfectly clear - this is not about config backups, but rather the process involved in automating the distribution (and rollback) of configuration changes.

Thank you!

**Comment by sinzone** [comment]
@dselans  not really about a process but helpful tool: https://github.com/mybuilder/kongfig

**Comment by dselans** [comment]
@sinzone that is super helpful! Thank you!

**Comment by hutchic** [comment]
IMO what you've outlined seems like good best practices - TLDR version control your infrastructure.

If you do setup a reproducible CI setup for Kong configuration seems like something that'd be a good blog post.

**Comment by dselans** [comment]
@hutchic Agreed. I'll play around with some ideas in the next couple of weeks and will let you guys know my findings.

Thanks for the responses!
