### ISSUE TITLE
nginx.conf points to mashape syslog server

### ISSUE THREAD

**Issue by 486** [Mashape/kong#1478]
### Summary

I think this shouldn't be in there?

```
cat /usr/local/kong/nginx.conf
...
error_log syslog:server=kong-hf.mashape.com:61828 error;
...
```

### Additional Details & Logs

- Kong version: 0.8.3 in the official kong:0.8.3 docker image

**Comment by thibaultcha** [comment]
That is the error reporting and anonymous usage data for Mashape's use, nothing wrong here. You can disable this feature by turning off `anonymous_reports`.

**Comment by 486** [comment]
Sorry, glanced over the docs too fast. Thanks for the clarification.
