### ISSUE TITLE
File log plugin log file location

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/kong#148]
Reading http://getkong.org/plugins/file-log/ I couldn't find the path of the "Kong Log File". 

Also shouldn't this be configurable? I didn't find anything in the kong.yml that is not inside the nginx block, which does have an enabled access log, so kong is always writing to a log file at  `/usr/local/kong/logs/access.log` even without this plugin enabled.

**Comment by thibaultCha** [comment]
From my searches, the log will simply be `your_nginx_working_directory/logs/error.log` since the plugin only logs stuff using nginx's `ngx.log` method.

**Comment by Nijikokun** [comment]
It should probably be made note of on the plugins page.

**Comment by thefosk** [comment]
Closed: http://getkong.org/plugins/file-log/
