### ISSUE TITLE
OAuth using client_credentials

### ISSUE THREAD

**Issue by dlokhande** [Mashape/kong#1482]
### Summary

Unable to create OAuth using client_credentials. The API fails for http://localhost:8000/oauth2/token with

{"request_path":"\/oauth2\/token","message":"API not found with these values","request_host":["localhost"]}

### Steps To Reproduce

1.curl -i -X POST \
  --url http://localhost:8001/apis/ \
  --data 'name=mockbin' \
  --data 'upstream_url=http://mockbin.com/' \
  --data 'request_host=mockbin.com'

{"upstream_url":"http:\/\/mockbin.com\/","strip_request_path":false,"id":"378a5237-dcae-4b19-8124-da4cacd5eaa1","created_at":1470763256000,"preserve_host":false,"name":"mockbin","request_host":"mockbin.com"}

2. Added key-auth

3.Added consumer 
curl -i -X POST \
>   --url http://localhost:8001/consumers/ \
>   --data "username=dinesh"
HTTP/1.1 201 Created
Date: Mon, 08 Aug 2016 13:28:41 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.8.3

{"username":"dinesh","created_at":1470763620000,"id":"605368ee-4a20-4d55-94fa-8ed8989c04e5"}

4. Enabled oauth plugin
curl -X POST http://localhost:8001/apis/mockbin/plugins --data "name=oauth2"     --data "config.scopes=email,phone,address"     --data "config.mandatory_scope=true"     --data "config.enable_client_credentials"

{"api_id":"378a5237-dcae-4b19-8124-da4cacd5eaa1","id":"6ea729ed-d6f4-470c-ad0e-472541f95168","created_at":1470765215000,"enabled":true,"name":"oauth2","config":{"mandatory_scope":true,"token_expiration":7200,"enable_implicit_grant":false,"scopes":["email","phone","address"],"hide_credentials":false,"enable_password_grant":false,"accept_http_if_already_terminated":false,"provision_key":"bd7414b03b904d49a0015b0ad8323025","enable_client_credentials":true,"enable_authorization_code":true}}

5. Create Application with following command
curl -X POST "http://localhost:8001/consumers/605368ee-4a20-4d55-94fa-8ed8989c04e5/oauth2" --data "name=mockbin" --data "client_id=mockbin" --data "redirect_uri=http://localhost:8080/"

Response -> {"consumer_id":"605368ee-4a20-4d55-94fa-8ed8989c04e5","client_id":"mockbin","id":"e9257bdb-25ce-443a-a545-5336e1af498f","redirect_uri":["http:\/\/localhost:8080\/admin\/"],"name":"mockbin","created_at":1470768256000,"client_secret":"mock bin"}

6.Get access token using following command which returns API not found with these values

curl http://localhost:8000/oauth2/token -d "client_id=mockbin&grant_type=client_credentials" -d "client_secret=mockbin"
{"request_path":"\/oauth2\/token","message":"API not found with these values","request_host":["localhost"]}

### Additional Details & Logs

What am I doing wrong on Step 6?  What is the expected output of this command ? Will I get access_token after I run this command? 

- Kong version 0.8.3
- Kong configuration (registered APIs/Plugins & configuration file)

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

no errors seen while running these commands

- Operating System OSX Yosemite

**Comment by dlokhande** [comment]
I also tried following
curl -X POST http://localhost:8001/oauth2/token -d "client_id=mockbin&grant_type=client_credentials" -d "client_secret=mockbin"

{"message":"Not found"}

**Comment by thibaultcha** [comment]
Use:
```
curl http://localhost:8000/oauth2/token \
  -H "Host: mockbin.com" \
  -d "client_id=mockbin&grant_type=client_credentials" \
  -d "client_secret=mockbin"
```

**Comment by dlokhande** [comment]
I tried following command with no success

Request -> 
curl http://localhost:8000/oauth2/token   -H "Host: mockbin.com"   -d "client_id=mockbin&grant_type=client_credentials"   -d "client_secret=mockbin"

Response
{"error":"access_denied","error_description":"You must use HTTPS"}

Is it true that Kong OAuth Plugin requires https to work? 

I uncommented following line in kong.yml
proxy_listen_ssl: "0.0.0.0:8443"

curl --insecure https://localhost:8443/oauth2/token   -H "Host: mockbin.com"   -d "client_id=mockbin&grant_type=client_credentials"   -d "client_secret=mockbin"

Response
{"error":"invalid_scope","error_description":"You must specify a scope"}

Please advise how to proceed ?

**Comment by dlokhande** [comment]
The scope was defined while enabling auth plugin with the option config.scopes=email,phone,address

Enabled oauth plugin curl -X POST http://localhost:8001/apis/mockbin/plugins --data "name=oauth2" --data "config.scopes=email,phone,address" --data "config.mandatory_scope=true" --data "config.enable_client_credentials"

**Comment by dlokhande** [comment]
Waiting to get suggestion on OAUTH client_credentials support. I tried following as per suggestion but got error response

curl http://localhost:8000/oauth2/token \
  -H "Host: mockbin.com" \
  -d "client_id=mockbin&grant_type=client_credentials" \
  -d "client_secret=mockbin"

Response
{"error":"invalid_scope","error_description":"You must specify a scope"}

**Comment by thefosk** [comment]
When you request the access token, you must specify a `scope` parameter. In your first comment you are only specifying `grant_type`, `client_id`, `client_secret` but no `scope`.

**Comment by dlokhande** [comment]
I am able to create access_token by specifying scope, however the APIs fails when token is passed. Please see request and response below

curl --insecure https://localhost:8443/oauth2/token -H "Host: mockbin.com" -d "client_id=mockbin&grant_type=client_credentials" -d "client_secret=mockbin" -d "scope=email" 
{"token_type":"bearer","access_token":"a1d40be5f8674f3ebb063bf074599ffa","expires_in":7200}

curl -i -X GET   --header 'Authorization: Bearer 9199bf37a1f24ea685f9afee71a9a192' --url http://localhost:8000/   --header 'Host: mockbin.com'

HTTP/1.1 502 Bad Gateway
Date: Tue, 16 Aug 2016 18:35:16 GMT
Content-Type: text/plain; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: kong/0.8.3

An invalid response was received from the upstream server

What am I missing or doing wrong?

**Comment by thefosk** [comment]
`502` is usually an error returned when the upstream service is not reachable. Make sure the final API is up and running, it seems to be down or crashing.

**Comment by dlokhande** [comment]
Thanks for the response. I found out that the API returns an error with "HTTP/1.1 502 Bad Gateway" behind corporate firewall/proxy.  

Here is the error.log

2016/08/17 11:30:29 [alert] 14271#0: send() failed (49: Can't assign requested address)
2016/08/17 11:30:29 [error] 14271#0: *179 peer closed connection in SSL handshake (54: Connection reset by peer) while SSL handshaking to upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "https://104.27.140.72:443/docs/0.8.x/getting-started/adding-your-api/", host: "getkong.org"
2016/08/17 11:30:29 [alert] 14271#0: send() failed (49: Can't assign requested address)
2016/08/17 11:30:29 [crit] 14271#0: *179 SSL_shutdown() failed (SSL: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init) while SSL handshaking to upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "https://104.27.140.72:443/docs/0.8.x/getting-started/adding-your-api/", host: "getkong.org"
2016/08/17 11:30:29 [alert] 14271#0: send() failed (49: Can't assign requested address)

I created following API
curl -i -X POST   --url http://localhost:8001/apis/   --data 'name=kong' --data 'upstream_url=https://getkong.org/docs/0.8.x/getting-started/adding-your-api/' --data 'request_host=getkong.org'

What settings are needed when kong gw is installed behind corporate firewall/proxy to reach external APIs? 

Another question - How scope is used in Oauth authentication? I see that scope is mandatory parameter to create oauth token for client_credentials. It is not clear how scope can be be used for authorization.

**Comment by thefosk** [comment]
> How scope is used in Oauth authentication?

You can define available scopes and decide if they should be mandatory or not. When you authenticated a user with a specific scope, the authenticated scope is passed into a `X-Authenticated-Scope` upstream request header.

Please check the documentation at https://getkong.org/plugins/oauth2-authentication

**Comment by tarunsaxenattn** [comment]
In Kong, you can do one thing. You can terminate SSL(trusted , can use free SSL via ACM) on ELB of KONG and use the feature "Accept HTTP if already terminated" in OAUTH2 plugin. But keep in mind the ELB Listeners will be (Secure TCP 443)--> (Secure TCP 8443 [https port exposed by KONG]) . It worked for me. Cheers. My Oauth is working as expected on Kong. :D

**Comment by polefishu** [comment]
I add two apis to kong layer, 
### 1
 ```curl -i -X POST \
  --url http://localhost:8001/apis/ \
  --data 'name=cm' \
  --data 'upstream_url=http://shu.cloud.com/' \
  --data 'request_path=/cloud/m'
```
### 2
```
curl -i -X POST \
  --url http://localhost:8001/apis/ \
  --data 'name=cf' \
  --data 'upstream_url=http://shu.cloud.com/' \
  --data 'request_path=/cloud/r'
```
both of them not use request_host, only request_path
then I Forward my requests through Kong, I got 
```
curl -i -X POST \
 --url http://localhost:8000/cloud/m
HTTP/1.1 200 OK
Date: Fri, 03 Mar 2017 06:49:25 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 32
Connection: keep-alive
X-Kong-Upstream-Latency: 3
X-Kong-Proxy-Latency: 0
Via: kong/0.9.9

{"ConfirmToken":"ConfirmToken"}
```
return 200, now, i'm going to configure the OAuth 2.0 plugin to add authorization to my API, 
some information
```
curl http://localhost:8001/apis
{"data":[{"upstream_url":"http:\/\/shu.cloud.com\/","request_path":"\/cloud\/r","id":"cc2cb304-fd31-4660-a096-b6d837fdc544","created_at":1488448334000,"preserve_host":false,"strip_request_path":false,"name":"cf"},{"upstream_url":"http:\/\/shu.cloud.com\/","request_path":"\/cloud\/m","id":"e30cd702-a733-4987-b0f4-ec48a46f9186","created_at":1488448547000,"preserve_host":false,"strip_request_path":false,"name":"cm"}],"total":2}
curl http://localhost:8001/consumers
{"data":[{"username":"Jason","created_at":1488449860000,"id":"6f927b27-5744-4f1f-ad88-b3f73c4a23a9"}],"total":1}
```
### 1
```
curl -X POST http://localhost:8001/apis/cf/plugins \
    --data "name=oauth2" \
    --data "config.enable_client_credentials=true" \
    --data "config.scopes=email,phone,address" \
    --data "config.mandatory_scope=true"
{"api_id":"cc2cb304-fd31-4660-a096-b6d837fdc544","id":"3bc28de6-9c6d-4e7c-8ece-9a1aeefb6a83","created_at":1488508864000,"enabled":true,"name":"oauth2","config":{"mandatory_scope":true,"token_expiration":7200,"enable_implicit_grant":false,"scopes":["email","phone","address"],"hide_credentials":false,"enable_password_grant":false,"accept_http_if_already_terminated":false,"provision_key":"74e13a4bcbb74b77a7e7b27a71dc1074","enable_client_credentials":true,"enable_authorization_code":false}}
```
### 2
```
curl -X POST http://localhost:8001/consumers/6f927b27-5744-4f1f-ad88-b3f73c4a23a9/oauth2 \
    --data "name=Test%20Application" \
    --data "client_id=SOME-CLIENT-ID" \
    --data "client_secret=SOME-CLIENT-SECRET" \
    --data "redirect_uri=http://some-domain/endpoint/"
{"consumer_id":"6f927b27-5744-4f1f-ad88-b3f73c4a23a9","client_id":"SOME-CLIENT-ID","id":"dab4e113-2adb-4010-95db-7cc1439aa7db","created_at":1488508973000,"redirect_uri":["http:\/\/some-domain\/endpoint\/"],"name":"Test Application","client_secret":"SOME-CLIENT-SECRET"}
```
### 3
when I POST /oatuth2/token: I got "message":"Not found".
```
curl -X POST http://localhost:8001/oauth2/token \
>  --data "client_id=SOME-CLIENT-ID&grant_type=client_credentials" \
>  --data "client_secret=SOME-CLIENT-SECRET"
{"message":"Not found"}
```
```
curl -X POST http://localhost:8001/oauth2/token \
>  -H "Host: shu.cloud.com" \
>  --data "client_id=SOME-CLIENT-ID&grant_type=client_credentials" \
>  --data "client_secret=SOME-CLIENT-SECRET" \
>  --data "scope=email"
{"message":"Not found"}
```
