### ISSUE TITLE
LDAP attribute property to be optional and use referrals

### ISSUE THREAD

**Issue by michallis** [Mashape/kong#1487]
### Summary

We want to use LDAP plugin for different customers, but the actual schema requires the 'attribute' property. 
We want to add an alternative way to perform authentication. At the moment:
is_authenticated, error = ldap.bind_request(sock, who, given_password)
where 'who' = conf.attribute.."="..given_username..","..conf.base_dn
we want to do 'who' = domain\\login

This means that the conf.attribute is optional, and the conf.base_dn does not get appended to the who string.

Can we PR a proposal, which is working for our existing LDAP customers?

**Comment by shashiranjan84** [comment]
@michallis a PR would be great, Thanks
