### ISSUE TITLE
kong can't start

### ISSUE THREAD

**Issue by seedotlee** [Mashape/kong#1492]
### Summary

config `/etc/kong/kong.yml`

```
PostgreSQL configuration
postgres:
  host: "127.0.0.1"
  port: 5432

  ######
  ## Name of the database used by Kong. Will be created if it does not exist.
  database: kong

  #####
  ## User authentication settings
  user: "kong"
  password: "123456"
```

run `kong start` 

```
[INFO] kong 0.8.3
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........postgres host=127.0.0.1 database=kong user=kong password=123456 port=5432
[INFO] Leaving cluster..
[ERR] ERROR: function to_regclass(unknown) does not exist (8)
[ERR] Could not start Kong
```

### Additional Details & Logs

- Kong version (0.8.3)
- Kong configuration (none)
- Operating System (ubuntu 14.04)

**Comment by thibaultcha** [comment]
Kong requires Postgres 9.4+

**Comment by seedotlee** [comment]
The PostgreSQL's version is 9.4.8
```
psql -V
psql (PostgreSQL) 9.4.8
```

**Comment by seedotlee** [comment]
eh~~~
I'm installed psql 9.4.9 and start kong there is nothing wrong....

Thanks @thibaultcha

**Comment by base698** [comment]
I get this error: 
```
2017/07/17 19:16:14 [verbose] Kong: 0.10.3
2017/07/17 19:16:14 [verbose] no config file found at /etc/kong/kong.conf
2017/07/17 19:16:14 [verbose] no config file found at /etc/kong.conf
2017/07/17 19:16:14 [verbose] no config file, skipping loading
2017/07/17 19:16:14 [verbose] prefix in use: /usr/local/opt/kong
2017/07/17 19:16:14 [verbose] preparing nginx prefix directory at /usr/local/opt/kong
2017/07/17 19:16:14 [verbose] saving serf identifier to /usr/local/opt/kong/serf/serf.id
2017/07/17 19:16:14 [verbose] saving serf shell script handler to /usr/local/opt/kong/serf/serf_event.sh
2017/07/17 19:16:14 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/07/17 19:16:14 [verbose] default SSL certificate found at /usr/local/opt/kong/ssl/kong-default.crt
2017/07/17 19:16:14 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2017/07/17 19:16:14 [verbose] admin SSL certificate found at /usr/local/opt/kong/ssl/admin-kong-default.crt
2017/07/17 19:16:14 [verbose] running datastore migrations
2017/07/17 19:16:14 [verbose] could not start Kong, stopping services
2017/07/17 19:16:14 [verbose] leaving serf cluster
2017/07/17 19:16:14 [verbose] stopped services
Error:
...enresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/start.lua:34: ...enresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] ERROR: function to_regclass(unknown) does not exist (8)
stack traceback:
        [C]: in function 'error'
        ...enresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
        ...penresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/init.lua:88: in function <...penresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/init.lua:88>
        [C]: in function 'xpcall'
        ...penresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/init.lua:88: in function <...penresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:7: in function 'file_gen'
        init_worker_by_lua:38: in function <init_worker_by_lua:36>
        [C]: in function 'pcall'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>
```

**Comment by thibaultcha** [comment]
@base698 You need to use Postgres 9.4+

**Comment by sankansm** [comment]
i am unable to start kong... 
ld not retrieve server_version: FATAL: Ident authentication failed for user "kong"

  Run with --v (verbose) or --vv (debug) for more details

**Comment by sankansm** [comment]
i was successful in starting the kong. now i was trying to enabled the developer portal by following steps in kong docs which tells you to add following lines in kong.conf file
i did add them and restart kong and nothing happened. developer portal is still not working.

https://docs.konghq.com/enterprise/0.34-x/developer-portal/configuration/getting-started/

portal = on
portal_gui_protocol = http
portal_gui_host = localhost:8003
portal_emails_from = flywithsan_san@yahoo.com
portal_emails_reply_to = flywithsan_san@yahoo.com

can you help how to enable the portal after installing and running kong.
i am sorry to say this but kong documents are not easy to follow.

**Comment by yanshinian** [comment]
> I get this error:
> 
> ```
> 2017/07/17 19:16:14 [verbose] Kong: 0.10.3
> 2017/07/17 19:16:14 [verbose] no config file found at /etc/kong/kong.conf
> 2017/07/17 19:16:14 [verbose] no config file found at /etc/kong.conf
> 2017/07/17 19:16:14 [verbose] no config file, skipping loading
> 2017/07/17 19:16:14 [verbose] prefix in use: /usr/local/opt/kong
> 2017/07/17 19:16:14 [verbose] preparing nginx prefix directory at /usr/local/opt/kong
> 2017/07/17 19:16:14 [verbose] saving serf identifier to /usr/local/opt/kong/serf/serf.id
> 2017/07/17 19:16:14 [verbose] saving serf shell script handler to /usr/local/opt/kong/serf/serf_event.sh
> 2017/07/17 19:16:14 [verbose] SSL enabled, no custom certificate set: using default certificate
> 2017/07/17 19:16:14 [verbose] default SSL certificate found at /usr/local/opt/kong/ssl/kong-default.crt
> 2017/07/17 19:16:14 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
> 2017/07/17 19:16:14 [verbose] admin SSL certificate found at /usr/local/opt/kong/ssl/admin-kong-default.crt
> 2017/07/17 19:16:14 [verbose] running datastore migrations
> 2017/07/17 19:16:14 [verbose] could not start Kong, stopping services
> 2017/07/17 19:16:14 [verbose] leaving serf cluster
> 2017/07/17 19:16:14 [verbose] stopped services
> Error:
> ...enresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/start.lua:34: ...enresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] ERROR: function to_regclass(unknown) does not exist (8)
> stack traceback:
>         [C]: in function 'error'
>         ...enresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
>         ...penresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/init.lua:88: in function <...penresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/init.lua:88>
>         [C]: in function 'xpcall'
>         ...penresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/init.lua:88: in function <...penresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/init.lua:45>
>         /usr/local/bin/kong:7: in function 'file_gen'
>         init_worker_by_lua:38: in function <init_worker_by_lua:36>
>         [C]: in function 'pcall'
>         init_worker_by_lua:45: in function <init_worker_by_lua:43>
> ```

Look this article https://www.setouchino.cloud/blogs/96

May be help you
