### ISSUE TITLE
could not parse configuration at :/etc/kong/kong.yml

### ISSUE THREAD

**Issue by dheersudheer** [Mashape/kong#1495]
When I start kong, it is giving this error. 'could not parse configuration at :/etc/kong/kong.yml'
Kong version:0.8.3
Kong configuration:/etc/kong/kong.yml
Operating System: Ubuntu 14.04

Can anybody help me to resolve this ?

**Comment by cmeury** [comment]
Without more details (e.g. the actual `kong.yml`) people probably won't be able to help you.

**Comment by Tieske** [comment]
yaml formatting probably, check your indentations. If you're not bound to 0.8.3, then checkout the new 0.9 RCs, way simpler configuration using a simple config format and environment variables.

**Comment by thibaultcha** [comment]
Considering this resolved (check your YAML file syntax on one of those online validators). 0.9 is not using YAML anymore anyways.
