### ISSUE TITLE
How to disassociate a consumer from group 

### ISSUE THREAD

**Issue by sbansal6** [Mashape/kong#1496]
### Summary

I have associated a consumer to two groups, admin and user. I dont see a way to remove it from a group now, say i want to remove consumer from user group 

https://getkong.org/plugins/acl/

**Comment by iam-merlin** [comment]
@sbansal6 use verb `DELETE` on your acl resource. For example, if your group is **user** with the uui : a338cd8c-f87d-4997-8cd8-49eaa4b1063b

Just `DELETE` => `http://localhost:8001/consumers/john/acls/a338cd8c-f87d-4997-8cd8-49eaa4b1063b`

**Comment by kellerj** [comment]
It would also appear that (like other Kong APIs) you can use the group name in the URL

**Comment by giorgiosironi** [comment]
Yes, since https://github.com/Kong/kong/issues/1525
