### ISSUE TITLE
Support ES256 algorithm for JWT plugin

### ISSUE THREAD

**Issue by vcsjones** [Mashape/kong#1499]
Currently the JWT implementation supports RS256. It would be nice if ECC signatures were supported. ES256 and ECC in general are more modern crypto algorithms, and the keys and signatures are much more compact.

**Comment by vcsjones** [comment]
I'm willing to take a stab at PR on this, but I wanted feedback on the idea, first to see if it would be accepted.

**Comment by Tieske** [comment]
Sure!, looking forward to it!

**Comment by Tieske** [comment]
fixed by #1920
