### ISSUE TITLE
Support for SSL into APIs

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#150]
When creating an API, we need to have the optional ability of adding an SSL certificate to the API. Kong needs to dynamically resolve the SSL certificate. We could possibly use `ssl_certificate_by_lua ` (https://github.com/openresty/lua-nginx-module/issues/331), but it requires a different version of OpenResty and a patch to nginx core.

**Comment by thefosk** [comment]
This feature has been scheduled for `0.3.0`. In order to make SSL happen on Kong we need to:

* Patch Nginx and OpenResty as mentioned in my first comment. This whole thing will be transparent if people use the distributions to install Kong (`rpm`, `deb`, `pkg`, etc), but it creates more headaches when installing from source.
* Decide if it should be an "SSL Plugin", or if it should be a core functionality embedded into the `API` object, adding two properties like `ssl_crt` and `ssl_key` alongside with `public_dns`, `target_url`, and the others.

Comments?

**Comment by Nijikokun** [comment]
Core sounds like a much better location for SSL to live, is there any benefits to having it as a plugin?

**Comment by thibaultCha** [comment]
The pros of making it a plugin, is that only the instances using the plugin need to patch nginx, and it keep things simple for API that don't strictly need SSL (which might be an anti-pattern).

The pros of embedding it into the core, is that we are enforcing "https everywhere". But it makes the core a little bit more bloated.

**Comment by Nijikokun** [comment]
> The pros of embedding it into the core, is that we are enforcing "https everywhere". But it makes the core a little bit more bloated.

Couldn't the options be **optional**, so its not an *enforcement* but an option.



> The pros of making it a plugin, is that only the instances using the plugin need to patch nginx, and it keep things simple for API that don't strictly need SSL (which might be an anti-pattern).

What about other plugins that will require SSL, for instance OAuth 2.0

**Comment by thefosk** [comment]
My personal opinion is that with or without an "SSL Plugin", the Kong core should be able to support SSL natively and make the `ssl_certificate_by_lua` handler available as a standard feature to every plugin that would like to interact with it.

**Comment by thibaultCha** [comment]
yes they would be optional but still bloat the core and documentation. The core being supposed to be as lightweight as possible.

> What about other plugins that will require SSL, for instance OAuth 2.0

We already discussed in the past about plugins that have dependencies, it's something we need to address separately.

I think in the core would make more sense. It's future proof and when the patch gets merged into nginx it'll be more standard. I still hate having to patch it tho.

**Comment by thibaultCha** [comment]
I just thought it was important to let everyone know this would require a patch for now.

**Comment by thefosk** [comment]
Supporting SSL into the core I think should be done, so that we have the `ssl_certificate_by_lua` available to any plugin that wants to use it.

But in this specific case, should SSL be supported as an additional plugin, or should it be configurable when creating the API object setting two additional properties (`ssl_key` and `ssl_cert`)?

**Comment by thibaultCha** [comment]
> Supporting SSL into the core I think should be done, so that we have the ssl_certificate_by_lua available to any plugin that wants to use it.

Makes sense


> But in this specific case, should SSL be supported as an additional plugin, or should it be configurable when creating the API object setting two additional properties (ssl_key and ssl_cert)?

If you follow what you said previously then we assume to always have `ssl_certificate_by_lua`, in that way I think a plugin makes more sense. Like a certificates plugin.

**Comment by thefosk** [comment]
> Like a certificates plugin.

Okay. This means that to add a certificate the user will need to do something like:

```shell
curl -d "name=ssl" \
     -d "api_id=API_ID" \
     -d "value.cert=CERT" \
     -d "value.key=KEY" http://kong:8001/plugins_configurations/
```

**Comment by Nijikokun** [comment]
> that way I think a plugin makes more sense. Like a certificates plugin.

:+1:

**Comment by thefosk** [comment]
Consider the following example, how do we tell that an API only needs to be consumed under HTTPs?

```shell
# Create API
curl -d "public_dns=test.com" \
     -d "target_url=http://mockbin.com" http://kong:8001/apis/

# Create Plugin
curl -d "name=ssl" \
     -d "api_id=API_ID" \
     -d "value.cert=CERT" \
     -d "value.key=KEY" http://kong:8001/plugins_configurations/
```

**Comment by thibaultCha** [comment]
That sounds good to me, standard plugin configuration

**Comment by ahmadnassri** [comment]
> that way I think a plugin makes more sense. Like a certificates plugin.
:+1: 

> how do we tell that an API can only be consumed under HTTPs

could rely on `target_url` for this:

- `*://mockbin.com` `HTTP` & `HTTPS` allowed
- `http://mockbin.com` only `HTTP` allowed
- `https://mockbin.com` only `HTTPS` allowed

**Comment by thefosk** [comment]
@ahmadnassri the `target_url` can't really be used to determine that, because the `target_url` is not the entrypoint of the request.

We need a way to tell that the API can only be access by SSL and not by regular `http`, but where this should property be stored? (@thibaultcha commented but didn't answer my question).

Should we have a property called `only_ssl=true` in the API object, or in the plugin?

**Comment by ahmadnassri** [comment]
@thefosk I meant you can use `target_url` for more than what its used for now ... you can even create a new property: `match_pattern`

```shell
curl http://kong:8001/apis/ \
     -d "public_dns=test.com" \
     -d "target_url=http://mockbin.com" \
     -d "match_pattern=*://mockbin.com"
```

**Comment by ahmadnassri** [comment]
on the main topic of SSL support, how do you plan to forward SSL requests to the `target_url` are you then doing SSL validation twice, once in Kong, and again with the target server?

**Comment by thefosk** [comment]
If the `target_url` is also under SSL, then the SSL validation is going to happen twice. Once from client -> Kong and another one from Kong -> Server

**Comment by thefosk** [comment]
@ahmadnassri the `match_pattern` brainstorming should probably happen in another issue, since it's a very broad topic.

**Comment by tarunsaxenattn** [comment]
In Kong, you can do one thing. You can terminate SSL(trusted , can use free SSL via ACM) on ELB of KONG and use the feature "Accept HTTP if already terminated" in OAUTH2 plugin. But keep in mind the ELB Listeners will be (Secure TCP 443)--> (Secure TCP 8443 [https port exposed by KONG]) . It worked for me. Cheers. My Oauth is working as expected on Kong. :D
