### ISSUE TITLE
OAuth2.0 how can I get the token?

### ISSUE THREAD

**Issue by seedotlee** [Mashape/kong#1500]
I'm doing with [https://getkong.org/plugins/oauth2-authentication]() step by step.

POST to `http://localhost:8001/oauth2/token` I can't get the token and the response is 404.

My body params : 

```
client_id:xxx
scope:xxx
client_secret:xxx
provision_key:xxx
authenticate_userid:xxx
```

**Comment by michallis** [comment]
You must use https

**Comment by seedotlee** [comment]
Is not visit Admin API?

https use 8443 port

Could not get any response after POST `https://localhost:8001/oauth2/token`

**Comment by seedotlee** [comment]
If I visited `https://localhost:8443/{api}/oauth2/token` 

Response output:

```
{
  "error": "unsupported_grant_type",
  "error_description": "Invalid grant_type"
}
```

**Comment by michallis** [comment]
Indeed you have to use the 8443 (configurable port). What is the grant_type you use at the moment?

**Comment by michallis** [comment]
If you have for example authorization grant, then you can do:
![authorization grant example](https://cloud.githubusercontent.com/assets/1217411/17662541/6f41fb5e-62e6-11e6-9e3c-1b150a61b01e.png)

**Comment by seedotlee** [comment]
what is the code? how can I get it?

**Comment by michallis** [comment]
for authorization grant this is the authorization code (which you have to pickup first, before calling /token endpoint):
![auth grant authorize](https://cloud.githubusercontent.com/assets/1217411/17662617/09caab30-62e7-11e6-8add-48126ecc243c.png)

**Comment by seedotlee** [comment]
Can not get token still...

Is there anything wrong？

![1 pic](https://cloud.githubusercontent.com/assets/5188604/17662871/4acbbf8c-631b-11e6-88b1-3d44c2c42fbb.jpg)
![2 pic](https://cloud.githubusercontent.com/assets/5188604/17662899/66dde7fe-631b-11e6-931f-01ed98e51c7c.jpg)
![3 pic](https://cloud.githubusercontent.com/assets/5188604/17662919/821426f0-631b-11e6-9f44-1056d908bf83.jpg)

**Comment by michallis** [comment]
did you create oauth2 credentials for your consumer? 
try: http://localhost:8001/consumers/{consumer_id}/oauth2 on your consumer to verify if oauth2 client_id and client_password exists, including callback uri

**Comment by seedotlee** [comment]
![4 pic](https://cloud.githubusercontent.com/assets/5188604/17663175/30b9f882-631d-11e6-9e77-3317035dd7d7.jpg)

**Comment by michallis** [comment]
Can you try sending as form url-encoded in your REST client ? Seem ok to me

**Comment by seedotlee** [comment]
I found your POST Headers contain `Authorization: xxxxx` , what it is?

I'm using paw like you :

![6 pic_hd](https://cloud.githubusercontent.com/assets/5188604/17665493/f7555008-632d-11e6-9f65-19d3e0717384.jpg)

**Comment by michallis** [comment]
Using Kong 0.8.3, I run through all steps just in case, using postman now :-):
API:
![schermafdruk 2016-08-15 15 58 02](https://cloud.githubusercontent.com/assets/1217411/17666593/280d4b4c-6301-11e6-9f65-8601fa331ef4.png)

An a consumer:
![schermafdruk 2016-08-15 15 58 07](https://cloud.githubusercontent.com/assets/1217411/17666598/2f564642-6301-11e6-9ed1-7f25eaf768e6.png)

Verify OAuth2:
![schermafdruk 2016-08-15 15 58 13](https://cloud.githubusercontent.com/assets/1217411/17666606/3dcc875e-6301-11e6-803f-6969fb3b52b6.png)

And as well for consumer:
![schermafdruk 2016-08-15 15 58 17](https://cloud.githubusercontent.com/assets/1217411/17666616/47b21824-6301-11e6-8169-998546a918a5.png)

Get the authorization code:
![schermafdruk 2016-08-15 15 58 25](https://cloud.githubusercontent.com/assets/1217411/17666621/503e6e52-6301-11e6-896a-9b90d8a23b9b.png)

And that should work.

**Comment by thefosk** [comment]
You need to request the token on the proxy port `8000`, while still including the right `request_path` or `request_host` to help Kong identify the API.

**Comment by seedotlee** [comment]
I do all step once again but the same problem appeared.

I GET `http://localhost:8001/consumers/7e84c1cc-7d7a-40dd-86b8-6ef935304d31/oauth2`

```
{
      "consumer_id": "7e84c1cc-7d7a-40dd-86b8-6ef935304d31",
      "client_id": "clientid002",
      "id": "bd71012e-4b66-4254-b877-a8748dc8eb41",
      "created_at": 1471310810000,
      "name": "appname2",
      "redirect_uri": "[\"http:\\/\\/www.baidu.com\"]",
      "client_secret": "clientsecret002"
    }
```

The redirect_uri contain escape character but you have not.

How do you added the `redirect_uri `?

**Comment by seedotlee** [comment]
There is a problem with Postgresql really.

I use the cassandra ,it's OK.

I think there is a bug with use postgresql...

**Comment by thefosk** [comment]
@seedotlee what version of Kong are you using?

**Comment by seedotlee** [comment]
@thefosk v0.8.3

**Comment by thefosk** [comment]
@seedotlee I reccomend upgrading to 0.9 - I think this bug has been fixed there.

**Comment by seedotlee** [comment]
@thefosk OK, thanks!

**Comment by ahwing210** [comment]
Hi, I also encounter difficulties to get the token.
Kong version: v0.10.3
I am using the Client Credentials flow.
However when I fire POST request to https://127.0.0.1:8443/oauth2/token, it returns
{
  "message": "no API found with those values"
}
Seems there is no such endpoint..?

I have enabled SSL
<img width="613" alt="screen shot 2017-06-08 at 12 04 40 am" src="https://user-images.githubusercontent.com/15073442/26888616-1a2e3240-4bde-11e7-83ca-5c1948545819.png">

have created oauth2 credentials for the consumer
<img width="631" alt="screen shot 2017-06-07 at 11 57 55 pm" src="https://user-images.githubusercontent.com/15073442/26888378-70393f28-4bdd-11e7-9d4e-c741c6d5c4ee.png">

have the OAuth2 plugin apply to all endpoints
<img width="526" alt="screen shot 2017-06-07 at 11 59 25 pm" src="https://user-images.githubusercontent.com/15073442/26888379-70705c60-4bdd-11e7-9a95-1911a43d7bc7.png">

but don't know why it said it fails in this step..
<img width="602" alt="screen shot 2017-06-08 at 12 01 44 am" src="https://user-images.githubusercontent.com/15073442/26888475-ba83e6fa-4bdd-11e7-8b7d-4dc1074efdf7.png">

**Comment by lakshmanraob** [comment]
I am unable to get authorization_token

<img width="926" alt="screen shot 2019-02-06 at 11 28 39 pm" src="https://user-images.githubusercontent.com/3072034/52362660-0e371600-2a67-11e9-917c-6c3d45e609f5.png">

need help in resolving the issue

**Comment by ardesai** [comment]
> I am unable to get authorization_token
> 
> <img alt="screen shot 2019-02-06 at 11 28 39 pm" width="926" src="https://user-images.githubusercontent.com/3072034/52362660-0e371600-2a67-11e9-917c-6c3d45e609f5.png">
> 
> need help in resolving the issue

Are you able to resolve this? I am getting the same error!

**Comment by excepts** [comment]
https://localhost:8443/oauth2/token   404 with {"message": "no Route matched with those values"}

**Comment by shadow88sky** [comment]
I am getting the same error！ Any Response?

**Comment by sebastiandelaroche** [comment]
I am getting the same error https://github.com/Kong/kong/issues/1500#issuecomment-549107330 too :(

**Comment by ElijahAhianyo** [comment]
Getting same error here. Has anyone fixed it?
