### ISSUE TITLE
Unable to start kong(0.8.3) : says can't find nginx 

### ISSUE THREAD

**Issue by Ansar1628** [Mashape/kong#1506]
### Summary

Unable to start kong , it says can't find nginx

### Steps To Reproduce

I am running kong on mac os and i dont have ruxit installed in my machine 

output of  sudo find / -type f -name "nginx"

/usr/local/Cellar/nginx-full/1.10.1/bin/nginx
/usr/local/Cellar/ngx_openresty/1.9.15.1/bin/nginx

Can someone please help in resolving the problem

when I try to start nginx alone using sudo nginx   in mac i get below error

*nginx: [error] [lua] kong.lua:161: init(): Startup error: /usr/local/share/lua/5.1/kong/tools/io.lua:66: bad argument #1 to 'open' (string expected, got nil)*

### Additional Details & Logs

- Kong version (`0.8.3`)
- Kong configuration (using default configuration) for db using postgres 
- mac os

**Comment by thefosk** [comment]
@Ansar1628 I would highly reccomend to use 0.9 RC3 (the stable 0.9 will be released this week anyways).

**Comment by Ansar1628** [comment]
@thefosk : Thanks for the quick response 
I will switch to 0.9RC3

**Comment by thefosk** [comment]
@Ansar1628 let us know if it works with 0.9 - closing this for now.
