### ISSUE TITLE
Nginx HTTP error responses contain Server identifier

### ISSUE THREAD

**Issue by nicklanng** [Mashape/kong#1508]
In our continuing efforts to obfuscate what technology is fronting our APIs, we have discovered another leak that identifies the server as running openresty and therefore nginx.

When nginx errors internally, it generates an HTML response that injects the NGINX_VER variable or hardcodes the server name in the response. We found an example of this when sending a header that was too large for the value specified with the **client_header_buffer_size** directive.

Here is the code in nginx:
https://github.com/nginx/nginx/blob/48a16463fa41e508810a6914a126cfce87273cc8/src/http/ngx_http_special_response.c

It would be great if the kong.core.error_handlers module could catch these responses and modify the content type like it does for the 5XX errors specified. 

However, the problem with that module is that it leaks that the server is running Kong, which the current favoured hack (using inline Lua in the config.yaml to null those headers) cannot override.

It also includes messages such as "the upstream" etc.... these are useful logging messages as developers but are not suitable for customers, as they give information about using a proxy server and are not standard HTTP responses.

**Comment by thibaultcha** [comment]
Closing this as #1552 and !553 are more specific, the pending PR for `0.9.1` should take care of that. Thanks!
