### ISSUE TITLE
CLI arguments to configure Cassandra datastore

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#151]
Implementing the following arguments in the CLI to override the `kong.yml` datastore configuration:

* [ ] `--cassandra-hosts`
* [ ] `--cassandra-port`
* [ ] `--cassandra-keyspace`
* [ ] `--cassandra-timeout`
* [ ] `--cassandra-keepalive`

**Comment by thefosk** [comment]
Maybe this issue should be renamed to "Allow to override any configuration property through CLI arguments" (not just cassandra properties)

**Comment by thibaultCha** [comment]
I don't like the idea. it makes things complicated for nothing. Updating your config will be faster than writing a command with 20 char arguments.

**Comment by thefosk** [comment]
Sometimes the config is generated automatically, or needs to be edited automatically, so the only alternative is updating it using regex and `sed`, which is not easy. Appending CLI arguments provides a way for better automation.

**Comment by thibaultCha** [comment]
Don't see that happening, way too much of a hassle, way too many (and too long) arguments for that to be included in the CLI.
