### ISSUE TITLE
it does not start

### ISSUE THREAD

**Issue by protossyk** [Mashape/kong#1524]
hi:
i'm getting started to use kong.
i followed doc to install ‘kong’ step by step.but it does not work.
the error is"unconfigured table schema_keyspaces"
it seems lack of config.
please, thank you.

**Comment by Tieske** [comment]
please respect the issue template. We can't help without the basic info;

```
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Operating System
```

**Comment by protossyk** [comment]
i'm so sorry to miss the  template.
### Summary
i followed doc to install ‘kong’ step by step.but it does not work.
the error message  is"unconfigured table schema_keyspaces".


### Steps To Reproduce

1. install jdk1.8,and it works.
2. install cassandra 3.7,and it starts. 
3. install kong 0.8.3, exec  'kong start', 
![kongerror](https://cloud.githubusercontent.com/assets/9349152/17805697/4f2ae1b4-6633-11e6-992d-dc11e704a0c4.png)


### Additional Details & Logs

- Kong version :0.8.3
- Kong configuration:default
- Operating System:centos7

**Comment by thefosk** [comment]
I would try to delete the Cassandra keyspace with the following command and try to restart Kong:

```sql
DROP KEYSPACE kong;
```

**Be aware** that this operation will delete all of your data. Only execute it in a staging or dev environment.

**Comment by jackyang1984** [comment]
the same error:Error: [Invalid] unconfigured table schema_keyspaces
kong: 0.9.0
cassandra: 3.7  (is up)
kong.config: /usr/local/kong/kong.conf
prefix = /usr/local/kong/
log_level = notice
#custom_plugins = acl,correlation-id,galileo,jwt,log-serializers,request-transformer,ssl,udp-log,cors,hmac-auth,key-auth,oauth2,response-ratelimiting,statsd,basic-auth,datadog,http-log,ldap-auth,rate-limiting,response-transformer,syslog,bot-detection,file-log,ip-restriction,loggly,request-size-limiting,runscope,tcp-log
anonymous_reports = on
proxy_listen = 0.0.0.0:8000
#proxy_listen_ssl = 0.0.0.0:8443
admin_listen = 0.0.0.0:8001
nginx_worker_processes = auto
nginx_daemon = on
mem_cache_size = 128m
#ssl = on
#ssl_cert = none
#ssl_cert_key = none
database = cassandra
cassandra_contact_points = 192.168.56.103,192.168.56.106
cassandra_port = 9042
cassandra_keyspace = kong
cassandra_consistency = ONE
cassandra_timeout = 5000
#cassandra_ssl = off
#cassandra_ssl_verify = off
#cassandra_username = kong
#cassandra_password = kong
cassandra_repl_strategy = SimpleStrategy
cassandra_repl_factor = 1
cassandra_data_centers = 192.168.56.103:2,192.168.56.106:3
cluster_listen = 0.0.0.0:7946
cluster_listen_rpc = 127.0.0.1:7373
cluster_advertise = 192.168.56.103:7946
#cluster_encrypt_key = none
cluster_ttl_on_failure = 3600
cluster_profile = lan
dnsmasq = on
dnsmasq_port = 8053
#dns_resolver = 8.8.8.8
#lua_ssl_trusted_certificate = none
#lua_ssl_verify_depth = 1
#lua_code_cache = on
#lua_package_path = none
#lua_package_cpath = none

**Comment by thibaultcha** [comment]
Kong is only compatible with Cassandra 2.1/2.2 for now. This error will go away once you use a compatible Cassandra version.

**Comment by thibaultcha** [comment]
BTW,
```
custom_plugins = acl,correlation-id,galileo,jwt,log-serializers,request-transformer,ssl,udp-log,cors,hmac-auth,key-auth,oauth2,response-ratelimiting,statsd,basic-auth,datadog,http-log,ldap-auth,rate-limiting,response-transformer,syslog,bot-detection,file-log,ip-restriction,loggly,request-size-limiting,runscope,tcp-log
```
There are default plugins and do not need to be specified in the custom plugins as well.

**Comment by Tigraine** [comment]
@thibaultcha Is there any news on updating the DAO for newer Cassandra versions?
What are the reasons kong can't support cassandra 3.5? (We would like to move more of our data load to cassandra but would also like to avoid having to run two clusters)

**Comment by thibaultcha** [comment]
@Tigraine See #831 and #1294
