### ISSUE TITLE
[ ACL ] Delete ACL using name (instead of uuid)

### ISSUE THREAD

**Issue by iam-merlin** [Mashape/kong#1525]
What is it my dream?
-------------------
If I have the following user `a` with group `sample` I should be able to remove `sample` using the following request : `http://localhost:8001/consumers/a/acls/sample[DELETE]`

Why is it my dream?
--------------------
We use `ACL` in our microservice and we have to maintain which group each consumers have. With the current version, I can only delete and `ACL` using the uuid. Because of that, I have to find for each user which uuid I have to DELETE.

Why I can dream dream about this issue?
-----------------------------------------
With the `consumers` endpoint we have the ability to find a consumer using `username` or `uuid` so... why not with `ACL`?

More dreams...
---------------
Have the ability to remove a specific `ACL` for all consumers.

**Comment by thefosk** [comment]
Available in >= 0.9.1
