### ISSUE TITLE
ngx.req.set_uri() ineffective in plugin access method

### ISSUE THREAD

**Issue by sje397** [Mashape/kong#1532]
### Summary

I'm trying to transform a request in a plugin, where the request path may be

> /something/{some id}

and the upstream url is something like

> /upsream?id={some id}

I thought I could accomplish that by calling (inside the plugin access method)

> ngx.req.set_uri(ngx.ctx.api.request_path)

...to strip the optional part of the path, but it does not affect the call upstream. With 'strip path' on, it still calls

> /upsream/{some id}?id={some id}

After all, calling `ngx.req.set_uri_args` does work, and the docs for `set_uri` state it should work in 'access_by_lua' directives.

Is this a bug? Is there a workaround or something I'm missing?

Thanks!

### Additional Details & Logs

- Kong version: 0.9
- OS: Centos 7 (official kong docker)

**Comment by sje397** [comment]
I found a workaround:

>   ngx.ctx.upstream_url = ngx.ctx.api.upstream_url

**Comment by Andi24** [comment]
Had the same issue where ngx.req.set_uri had not effect, so that Kong forwarded the request with `upstream_url + initial_request_uri`

@sje397 thanks for the solution & the vars you mentioned!
