### ISSUE TITLE
CQRS: allow APIs to define both command-side and query-side upstream URLs

### ISSUE THREAD

**Issue by vitorsdcs** [Mashape/kong#1534]
Hi everyone,

I'm applying the [CQRS](http://martinfowler.com/bliki/CQRS.html) pattern to my microservices architecture.

This means I have an API called, lets say, ExampleApi, but it's split into two services: one for commands (POST, PUT, etc) and another for queries (GET). Their upstream URLs are, respectively, http://exampleapi-cmd/ and http://exampleapi-query/.

Now, I could proxy them with Kong so they would be available at http://api.domain.com/exampleapi-cmd/ and http://api.domain.com/exampleapi-query/

However, I don't want the client application to call different URLs depending on the HTTP method. It would just increase complexity.

So I thought it would be nice if Kong allowed me to define a commandside_url and a queryside_url instead of upstream_url only. This way, when ExampleApi is requested, Kong can check the HTTP method and redirect to the appropriate URL, whether it's the command-side or the query-side.

I'm willing to work on this feature. Would it be useful? Or should I handle it differently?

**Comment by Tieske** [comment]
To make this work, we should be able to resolve (as in Kong resolving incoming requests to its configured apis) based not only on `request_host` and `request_path`, but also on `request_method`. Right?

This is already part of the #505 issue. The resolving on methods is currently in @thibaultcha s' hands. @thibaultcha any thoughts? or can this issue be classified as a duplicate?

**Comment by vitorsdcs** [comment]
That would solve the issue if I could create two APIs using the same name and request path but different request methods.

In my example I would have to define:

`exampleapi --request_path=exampleapi --request_method=GET --upstream_url=http://exampleapi-query/`
`exampleapi --request_path=exampleapi --request_method=POST,PUT --upstream_url=http://exampleapi-cmd/`

**Comment by Tieske** [comment]
This has now been implemented in the new router, part of the forth coming 0.10 release. Available in the RC for 0.10. Closing this.
