### ISSUE TITLE
HTTP methods policies

### ISSUE THREAD

**Issue by lg1712** [Mashape/kong#1539]
Hello,

There is no available plugin to filter HTTP methods that can call APIs via Kong. I'd like to know if you have an idea to setup such a filter to only authorize a certain type of HTTP method or to disable a user to send a DELETE method for example?

Thank you

**Comment by Tieske** [comment]
something like #1414 ?

**Comment by thefosk** [comment]
Related to #505.

**Comment by thibaultcha** [comment]
Categorizing as duplicate, see the mentioned , closing this in the meantime.
