### ISSUE TITLE
Add configuration support for client-side SSL certs

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#1547]
Support for client side SSL certificates between Kong and the upstream service in the configuration.
- [`proxy_ssl_certificate`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_certificate)
- [`proxy_ssl_certificate_key`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_certificate_key)

This will allow to close issue #1357 and maybe #740. And since it's a common use-case, having it supported in the Kong configuration will avoid suggesting people to tweak their nginx configuration properties.

**Comment by thibaultcha** [comment]
Config templating so related to CLI. Labelled as accessible to beginner contributers.

**Comment by mwaaas** [comment]
anyone working on this would like to start to work on it
