### ISSUE TITLE
OpenResty version exposed when request URL is to large

### ISSUE THREAD

**Issue by jmdacruz** [Mashape/kong#1552]
### Summary

When sending an invalid request with a URL that is too long, nginx/OpenResty returns a 414 error code which is not handled by Kong's error handler (which is only configured to handle 50x errors). The expectation is that Kong's error handler also captures this, instead of exposing information about OpenResty and it's version. The information is not only provided in the HTML body, but also on the `Server` header (which typically has Kong's version number instead)

### Steps To Reproduce

1. Call an API with a URL that is too long, e.g., `http://{KONG_HOST}:{KONG_PORT}/{REPEAT SAME CHARACTER AT LEAST 10k TIMES}`

### Additional Details & Logs

- Kong version (`0.8.3`)
- Kong configuration (Default configuration file, regardless on what APIs are configured if any)
- Ubuntu 14.04

**Comment by thibaultcha** [comment]
Taken care of in `0.9.1`, thanks!
