### ISSUE TITLE
OpenResty version exposed when hitting /50x resource

### ISSUE THREAD

**Issue by jmdacruz** [Mashape/kong#1553]
### Summary

When sending an request to the `/50x` of the server, a `404` error is returned with the version of OpenResty. The expectation is that Kong's error handler also captures this, instead of exposing information about OpenResty and it's version. The information is not only provided in the HTML body, but also on the `Server` header (which typically has Kong's version number instead)

### Steps To Reproduce

1. Call `http://{KONG_HOST}:{KONG_PORT}/50x`

### Additional Details & Logs

- Kong version (`0.8.3`)
- Kong configuration (Default configuration file, regardless on what APIs are configured if any)
- Ubuntu 14.04

**Comment by thefosk** [comment]
Possible related to #1552.
