### ISSUE TITLE
Create JWT credential does not auto generate key

### ISSUE THREAD

**Issue by hellojosh** [Mashape/kong#1556]
### Summary

When creating JWT credentials for consumers, Kong does not auto generate JWT keys for me.
### Steps To Reproduce
1. curl -X POST http://kong:8001/plugins --data "name=jwt"
2. curl -X POST http://kong:8001/consumers --data "username=hellojosh"
3. curl -X POST http://kong:8001/consumers/hellojosh/jwt

I receive a response with HTTP code 415.
1. curl -X POST http://kong:8001/consumers/hellojosh/jwt --data "key="

This creates a JWT credentials with an empty key:

{
  "consumer_id":"dbfc3c24-d4b1-45dc-937b-4bfb0f5214f2",
  "id":"8350afd0-822c-4efd-a5aa-1ee3bdf8d56b",
  "secret":"443652d2751f4180ba3ba35a5275ad1c",
  "key":"",
  "created_at":1472166023000,
  "algorithm":"HS256"
}
### Additional Details & Logs
- Kong version: 0.9.0
- Kong configuration: JWT enabled
- Operating System: Mac 10.11.5 running Docker

**Comment by DiSiqueira** [comment]
I having this issue too, any solutions?

**Comment by DiSiqueira** [comment]
Using this should work, but i don't know what is the difference
curl -H "Content-Type: application/json" -X POST -d '{}' http://localhost:8001/consumers/hellojosh/jwt

**Comment by p0pr0ck5** [comment]
When `-X POST` is applied with no form data, no `Content-Type` header is sent, which is an error in the Admin API. The docs do not make this immediately clear, and are being fixed in https://github.com/Mashape/getkong.org/pull/392
