### ISSUE TITLE
Wildcard dns with the '-' in the domain name seems to fail

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#1557]
Opening an issue for [this conversation](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/konglayer/W3Jysfq163A/AW8MCVmaDQAJ).

When `request_host` contains a dash `-`, the resolver fails, ie:

This works: `*.mydomain.com`
This doesn't: `*.my-test.domain.com`

**Comment by thefosk** [comment]
Can't replicate with #1565.

**Comment by michaelkrog** [comment]
Funny thing.

I am experiencing this as well with 0.13.
`name.domain.com` works.
`my-name.domain.com` does not work.

**Comment by Tieske** [comment]
@michaelkrog what's in the logs?

**Comment by michaelkrog** [comment]
Sorry.  Just went on vacation..  I'll get back to you next week.
