### ISSUE TITLE
typo in compile from source docs

### ISSUE THREAD

**Issue by peterbsmith2** [Mashape/kong#1559]
### Summary

Its just a simple typo where `loca` should say `local

### Steps To Reproduce

1. Go To https://getkong.org/install/source/
2. The part where it says to install Luarocks 2.30...
3. 
```
./configure \
  --lua-suffix=jit \
  --with-lua=/usr/local/openresty/luajit \
  --with-lua-include=/usr/**loca**/openresty/luajit/include/luajit-2.1
```

**Comment by Tieske** [comment]
thanks, fixed in https://github.com/Mashape/getkong.org/pull/270
