### ISSUE TITLE
cache

### ISSUE THREAD

**Issue by javacspring** [Mashape/kong#1560]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Operating System

**Comment by sinzone** [comment]
@javacspring can you elaborate? thx.

**Comment by Tieske** [comment]
assuming accidentally created, closing this.
