### ISSUE TITLE
500 error for PUT and POST on 8000 and 8443, kong error log file empty

### ISSUE THREAD

**Issue by oviwankenobi** [Mashape/kong#1563]
### Summary
hi, I get 500 (internal server error) for POST and PUT (GET, DELETE, OPTIONS work fine), on both port 8000 and 8443, I Can see the 500 error in kong access log but nothing in kong error log; also the request is not reaching the server behind upstream url. any ideas where else can I look to figure out this problem? or what the problem actually is? 
the payload is Content-Length: 1280 and 
Accept: application/json, text/plain, */*
Content-Type: application/json;charset=utf-8

### Steps To Reproduce

1. set up kong to proxy an api which implement post and put
2. call post or put with payload bigger than 1200
3. notice the 500 error

### Additional Details & Logs

- Kong version  0.8.3
- Kong configuration (acl, rate limit, key-auth, cors)
- Kong error logs is empty
- Operating System: ubuntu 14.04

**Comment by oviwankenobi** [comment]
more details
1. kong cluser, 2 nodes
2. DB behind is Cassandra
3. I disabled all plugins except cors and still repros

**Comment by thibaultcha** [comment]
I was not able to reproduce this. Here is what I did:

- install Kong 0.8.3 (clean install)
```
$ kong start
...
[OK] Started
$ http :8001/apis upstream_url=http://httpbin.org request_host=httpbin.org
HTTP/1.1 201 Created
...
$ http -v POST :8000/post Host:httpbin.org \
    'Content-Type:application/json;charset=utf-8' \
    'Accept:application/json,text/plain,/' \
    value=`printf '.%.0s' {1..1280}`
POST /post HTTP/1.1
...
HTTP/1.1 200 OK
...
```

No errors.

Access logs:
```
127.0.0.1 - - [26/Aug/2016:15:15:39 -0700] "POST /post HTTP/1.1" 200 1746 "-" "HTTPie/0.9.6"
```

Could you provide us with at least some of the logs from `access.log` and `error.log`? Also, could you set the `error_log` level to `debug` in the Nginx configuraiton (in `kong.yml`)?

**Comment by oviwankenobi** [comment]
closing
because of bad logging on our side I could not see the request is actually reaching the server behind upstream url
