### ISSUE TITLE
External nginx_status for stats collection

### ISSUE THREAD

**Issue by BetaGrumm** [Mashape/kong#1564]
It would be quite handy if there was a way to collect stats from the nginx_status location via something like datadog. I am using these stats from all our API services while load testing, but when I looked into getting nginx status from Kong, I found that the nginx_status location was internal only.

I am using the datadog plugin and getting the stats from that (latency, count, size, etc). 
What I would like are the actual requests/s and connections stats from nginx.

Is there an alternative means that you intend for us to get these stats? 
Would it be possible to allow an externally accessible nginx_status?

Thanks.

**Comment by shashiranjan84** [comment]
@BetaGrumm Datadog agent collects Kong stats by calling /nginx_status endpoint on kong. Did you try enabling Kong on Datadog integration page.
