### ISSUE TITLE
from 0.8.3 update to 0.9.0 can't start

### ISSUE THREAD

**Issue by seedotlee** [Mashape/kong#1573]
kong form 0.8.3 update to 0.9.0 cant' start

```
kong start --trace
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:15: connection refused
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:15: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:81>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:42>
	/usr/local/bin/kong:11: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'pcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>
```

In 0.8.3 is all right.

- Kong version (`0.9.0`)
- ubuntu 14.04

**Comment by thibaultcha** [comment]
This means your postgres server is not reachable from Kong. The error will be more descriptive in 0.9.1.

**Comment by seedotlee** [comment]
how can I handle it? clean the psql?

**Comment by giammy2290** [comment]
+1 i have alredy check the connection with postgres and works

**Comment by mckn** [comment]
make sure you have a kong.conf file available. It says in the documentation that is should be generated on the fly but you still need to have the actual file present on the file system (even if it is empty).

**Comment by giammy2290** [comment]
but if i try to start the previous version all works fine, it's just with this version

**Comment by WALL-E** [comment]
see #1572

**Comment by thefosk** [comment]
We changed the default database from Cassandra to Postgres. If you were using Cassandra please make sure that it's still the default `database` in the configuration file, or run Kong with `KONG_DATABASE=cassandra kong start`

**Comment by mckn** [comment]
@giammy2290 well, the whole configuration of kong is changed so I guess you have to convert your config.

**Comment by thibaultcha** [comment]
Make sure your Postgres server is up and if you are using Cassandra, follow @thefosk's comment. As I said, this error will be more descriptive in 0.9.1.

**Comment by seedotlee** [comment]
The master branch can not start, I checkout `next` branch it can start.

**Comment by seedotlee** [comment]
And there is a very strange bug

I use the `kong.conf` start kong 

```
bin/kong start -c /etc/kong/kong.conf
```

The content is :

```
database = postgres           
pg_host = 127.0.0.1             # The PostgreSQL host to connect to.
pg_port = 5432                  # The port to connect to.
pg_user = kong                  # The username to authenticate if required.
pg_password = 123456              # The password to authenticate if required.
pg_database = kong 
```

But kong used `cassandra` database.

I must start with `KONG_DATABASE=postgres bin/kong start -c /etc/kong/kong.conf` than kong using `postgres` database

**Comment by Tieske** [comment]
@seedotlee are you sure you hadn't previously set the `KONG_DATABASE=cassandra`? all defaults are now 'postgres', and the environment variables override the config file.

**Comment by seedotlee** [comment]
I don't konw where can set `KONG_DATABASE=cassandra` except `kong.conf`

**Comment by seedotlee** [comment]
I'm sorry , I used wrong `kong.conf`.

Thanks @Tieske .
