### ISSUE TITLE
from 0.8.3 update to 0.9.0  every thing is bad....

### ISSUE THREAD

**Issue by seedotlee** [Mashape/kong#1574]
from 0.8.3 update to 0.9.0  every thing is bad....

Is there a guide to update?

### Additional Details & Logs

- Kong version (`0.9.0`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- OS X 10.11 AND UBUNTU

**Comment by WALL-E** [comment]
remove trailing comment all in the kong.conf,  this is my experience, you can try

Good luck!

**Comment by thibaultcha** [comment]
I see you opened #1573, and I have already replied to you there, please let's not create duplicate. Also "everything is bad" is not a very descriptive issue, please report the actual problems you are having, if different than #1573.

**Comment by seedotlee** [comment]
@thibaultcha Sorry,I will pay attention.
