### ISSUE TITLE
kong start fails -- serf executable not found -- serf_path envar not used

### ISSUE THREAD

**Issue by badfd** [Mashape/kong#1577]
### Summary

kong fails to start with the 'serf_path' correctly set: Error: could not find 'serf' executable

### Steps To Reproduce

```
$ ls -l /usr/local/bin/serf
-rwxr-xr-x 1 root root 13473496 Aug 19 21:08 /usr/local/bin/serf
$ export serf_path=/usr/local/bin
$ /usr/local/bin/kong start
Error: could not find 'serf' executable (is 'serf_path' correctly set?)

  Run with --trace to see traceback
$ /usr/local/bin/kong start --trace
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:20: could not find 'serf' executable (is 'serf_path' correctly set?)
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:20: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:81>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:42>
	/usr/local/bin/kong:11: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'pcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>
$ export PATH=$PATH:/usr/local/bin
$ /usr/local/bin/kong start
Kong started
```

**Workaround**: Add 'serf_path' to 'PATH' [ e.g. export PATH=$PATH:$serf_path ]

### Additional Details & Logs

- Kong version: 0.9.0
- Kong configuration (registered APIs/Plugins & configuration file): default + postgres
- Kong error logs (`<KONG_PREFIX>/logs/error.log`): nothing
- Operating System: CentOS Linux release 7.2.1511 (Core)

**Comment by thibaultcha** [comment]
`KONG_SERF_PATH` would be the proper usage of environment variables. Could you try?

**Comment by thibaultcha** [comment]
`serf_path` is the name of the property (if set in `kong.conf`), but as documented, env variables must be capitalized and prefixed with `KONG_`.

**Comment by badfd** [comment]
People do do "read the _____ manual", and error messages should be made for people. Google tells me that I am not the first person to be fooled by the error message quoted above.

In any case, setting KONG_SERF_PATH also does not work:
...
$ ls -l /usr/local/bin/serf
-rwxr-xr-x 1 root root 13473496 Aug 19 21:08 /usr/local/bin/serf
$ export KONG_SERF_PATH=/usr/local/bin
$ /usr/local/bin/kong start
Error: could not find 'serf' executable (is 'serf_path' correctly set?)

  Run with --trace to see traceback
...

But now it gets interesting. It seems that KONG_SERF_PATH takes precedence over PATH:

...
$ export PATH=$PATH:$KONG_SERF_PATH
$ /usr/local/bin/kong start
Error: could not find 'serf' executable (is 'serf_path' correctly set?)

  Run with --trace to see traceback
$ unset KONG_SERF_PATH
$ /usr/local/bin/kong start
Kong started
$
...

So, the workaround that I suggested is valid **only** while KONG_SERF_PATH is not set.

**Comment by thibaultcha** [comment]
> 'serf_path' means: KONG_SERF_PATH

It can be `serf_path` if specified in the config file, if by ENV variable, then it is the later.

> KONG_SERF_PATH must be set to the absolute pathname of the 'serf' executable

Indeed.

> If the above described behavior is "by design", then this issue can be closed.

Yes it is. Things will be fine when `serf` is in the `$PATH`, and that is the expected setup. This property was only introduced for systems with specific limitations, such as Travis containers ([.ci/run_tests.sh](https://github.com/Mashape/kong/blob/master/.ci/run_tests.sh#L4)).

**Comment by thibaultcha** [comment]
(will update the related notes in the source install instructions)
