### ISSUE TITLE
Add sample code in Java and .NET [gelato]

### ISSUE THREAD

**Issue by petrdvorak** [Mashape/kong#1580]
### Summary

Currently, the list of languages in Gelato samples misses the two big enterprise languages: Java and .NET. Please add sample source code in these languages, for example using Unirest library...

**Comment by thibaultcha** [comment]
Could you please report this to the Gelato developers instead? I'll FWD this issue, but closing it since it is not Kong related.

**Comment by petrdvorak** [comment]
I didn't find Gelato bug reporter... :( Thank you for forwarding the issue.
