### ISSUE TITLE
wildcard routing support?

### ISSUE THREAD

**Issue by iam-merlin** [Mashape/kong#1581]
There is in kong the ability to route upstream using wildcard?

For example : `http://api.com/me/organization/*/projects`

I'm pretty sure that is not possible... maybe this can be handle in a different way.

**Comment by thibaultcha** [comment]
Kong is a transparent proxy, it will proxy any incoming request (including the URI) to any upstream services if one matches. See the proxy reference for more details: https://getkong.org/docs/latest/proxy

Eventually `request_path=/me/organization` will allow you to proxy all incoming requests, regardless of the `/*/projects` and subsequent sections.

**Comment by iam-merlin** [comment]
@thibaultcha thx for the quick answer.
this can't be a viable solution in my point of view. If I have several endpoint like `http://api.com/me/organization/*/projects` and `http://api.com/me/organization/*/milestones` or more with different internal upstreams like 2 different microservice ... this can't be done actually so?

On the other hand, I know that there is one issue about uri mapping... this feature should do the trick but in the future...

am I right?

**Comment by thibaultcha** [comment]
Yeah, such use cases won't work for now indeed.

**Comment by iam-merlin** [comment]
ok, question closed xD

**Comment by 000panther** [comment]
For anybody reading this question in the Future: Kong seems to support Regexes now: https://getkong.org/docs/0.11.x/proxy/#using-regexes-in-uris
