### ISSUE TITLE
Not able to add custom plugin with current version 0.9.0

### ISSUE THREAD

**Issue by bhrt-DS** [Mashape/kong#1586]
### Summary

Hello,
   I'm trying to add custom plugin with latest 0.0.9 version by setting custom_plugins= my-plugin and  by adding necessary handler and schema files to plugin folder.
But I'm not getting added plugin in  http://localhost:8001/plugins/enabled

### Steps To Reproduce

1. set custom_plugins= my-plugin in configuration file
2. add my-plugin to plugins folder
3. update rockspec file

### Additional Details & Logs

- Kong version  - 0.0.9
- Operating System - ubuntu

**Comment by thibaultcha** [comment]
Could you try setting this property via the ENV variable (`KONG_CUSTOM_PLUGINS=my-plugin` until 0.9.1?

**Comment by bhrt-DS** [comment]
Sorry for spelling mistake, my current version is 0.9.0.
Thanks for the solution, it is working fine with setting ENV variable KONG_CUSTOM_PLUGINS, but why we need to override custom_plugins property of configuration file?

**Comment by thibaultcha** [comment]
0.9.0 has bug in the configuration file parsing. 0.9.1 will take care of it. Closing this then.

**Comment by bhrt-DS** [comment]
Thanks for Info.
FYI, before setting ENV variable stuff I debugged conf_loader.lua file and i found statement in -- merge plugins block,
 conf.custom_plugins = nil
so i just commented this line and it works for me.
But for this version, I'll go with setting ENV variable for now.

Thank You for your time :)

**Comment by ugurbost** [comment]
I think this bug is still open for 0.9.2, right?
