### ISSUE TITLE
can not luarocks install kong 0.9.1-0

### ISSUE THREAD

**Issue by gavinzhou** [Mashape/kong#1603]
### Summary

can not install with luarocks

### Steps To Reproduce

luarocks install kong 0.9.1-0

Error: No results matching query were found.

### Additional Details & Logs

- Kong version 0.9.1-0

**Comment by Tieske** [comment]
the rockspec hasn't been uploaded to LuaRocks yet. Meanwhile you can do;

```shell
luarocks install https://raw.githubusercontent.com/Mashape/kong/master/kong-0.9.1-0.rockspec
````

**Comment by gavinzhou** [comment]
thank you
