### ISSUE TITLE
New plugin - Antivirus scan

### ISSUE THREAD

**Issue by petrdvorak** [Mashape/kong#1604]
Since APIs can often be accessed from the public internet and can contain any payload, it would be nice to offer a way to scan the request payload for possible malware infection.

The plugin should take the whole request and send it to an AV analysis to an external AV server and if the validation passes, it would proceed with the request processing.

**Comment by petrdvorak** [comment]
_(... can connect you to the Avast guys, if that helps.)_

**Comment by sinzone** [comment]
There is a WAF plugin in the making for Kong Enterprise. Are you referring to WAF?

**Comment by petrdvorak** [comment]
Yes, WAF is a more generic solution than what I was referring to (I was looking to AV only) so it will do the job.

**Comment by samrose** [comment]
There is discussion happening in #1048 too

**Comment by coopr** [comment]
Closing in favor of #1048
