### ISSUE TITLE
Add API in other Docker containers

### ISSUE THREAD

**Issue by vistiyos** [Mashape/kong#1614]
### Summary

I'm using Kong installed on a Docker container. My microservices are in other containers. How can I add them to Kong if their IPs can be different?

All my microservices are working properly making request to them directly instead of doing it through Kong.

### Additional Details & Logs

- Kong version 0.9.1

**Comment by thefosk** [comment]
You should use Docker links, and then use the link name as the address of the `upstream_url`.
