### ISSUE TITLE
File upload causes Kong to hang when using OAuth2 plugin

### ISSUE THREAD

**Issue by Dibble** [Mashape/kong#1616]
### Summary

Attempting to upload even a small file to an API with the oauth2 plugin causes Kong to hang, it won't respond to any requests until it is restarted or reloaded. This typically occurs after the second attempt to upload the file.

Nginx uses ~50% CPU during this time, so it is alarmingly easy to overwhelm the machine.
### Steps To Reproduce
1. add `client_body_buffer_size` directive in nginx config as a workaround for the "request body in temp file" issue #1241 
2. create an API with an OAuth2 plugin
3. create an empty 2MB file: `dd if=/dev/zero of=2M.txt bs=2000000 count=1`
4. upload the file to the API (may need to make this request twice):  `curl -i -F name=2M.txt -F fileinfo=@2M.txt https://<kong>/<api>`
5. Kong will accept, but not respond to any requests
6. `kong restart` or `kong reload` to fix
### Additional Details & Logs
- Kong version: `0.8.3`
- Kong debug-level startup logs (`$ kong start --vv`): N/A
- Kong error logs (`<KONG_PREFIX>/logs/error.log`): No errors are logged
- Kong configuration (registered APIs/Plugins & configuration file): Any API with OAuth2 plugin enabled.
- Operating System: CentOS
- Hardware: Medium-sized virtual instance, 4 CPUs, 4GB RAM

**Comment by p0pr0ck5** [comment]
@Dibble do you still see this behavior with Kong 0.10.3? Note also that the need to manually define `client_body_buffer_size` will go away in 0.10.4, as this will now be a configurable property directly in the Kong config file.

**Comment by p0pr0ck5** [comment]
Closing following no response. As noted, body buffer handling is now configurable. If there is more detailed information we can see, we can help troubleshoot this further. Thanks!
