### ISSUE TITLE
Start kong in 'safe mode' in case of broken plugins

### ISSUE THREAD

**Issue by logronoide** [Mashape/kong#1624]
### Summary

In the current version when kong starts it tries to load all plugins with an API registered. If the plugin fails to load, kong stops and exists reporting the error. 

This logic sounds correct to me in a development environment, but it's risky in a production environment. My suggestion is to add a flag to tell the server that it should continue starting the server with the broken plugins disabled. This is my 'safe mode' flag.
### Steps To Reproduce
1. Start kong 
2. Register any API with a plugin (hello-world plugin for example)
3. Stop kong
4. Delete the lua files of the plugin, remove a dependency, whatever can broke the plugin.
5. Start kong
6. Kong cancels the startup process abruptly:
### Additional Details & Logs

```
2016/09/13 16:32:37 [debug] searching for OpenResty 'nginx' executable
2016/09/13 16:32:37 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.9.15.1'
2016/09/13 16:32:37 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2016/09/13 16:32:37 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2016/09/13 16:32:37 [verbose] could not start Kong, stopping services
2016/09/13 16:32:37 [verbose] leaving serf cluster
2016/09/13 16:32:37 [verbose] left serf cluster
2016/09/13 16:32:37 [verbose] stopping serf agent at /usr/local/kong/pids/serf.pid
2016/09/13 16:32:37 [verbose] serf agent stopped
2016/09/13 16:32:37 [verbose] stopping dnsmasq at /usr/local/kong/pids/dnsmasq.pid
2016/09/13 16:32:37 [verbose] stopped services
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:37: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong.lua:127: hello-world plugin is in use but not enabled
stack traceback:
    [C]: in function 'assert'
    /usr/local/share/lua/5.1/kong.lua:127: in function 'init'
    init_by_lua:4: in main chunk

stack traceback:
    [C]: in function 'error'
    /usr/local/share/lua/5.1/kong/cmd/start.lua:37: in function 'cmd_exec'
    /usr/local/share/lua/5.1/kong/cmd/init.lua:85: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:85>
    [C]: in function 'xpcall'
    /usr/local/share/lua/5.1/kong/cmd/init.lua:85: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:42>
    /usr/local/bin/kong:11: in function 'file_gen'
    init_worker_by_lua:38: in function <init_worker_by_lua:36>
    [C]: in function 'pcall'
    init_worker_by_lua:45: in function <init_worker_by_lua:43>
```
- Kong version 0.9.1
- Ubuntu 14.04 (Vagrant environment)

**Comment by kkindaface** [comment]
In this proposed safe-mode will Kong be serving any requests? I hope not.

**Comment by Tieske** [comment]
I think this is a very bad idea. What if the failed plugin is an authentication plugin?

errors are errors, and stuff should break on errors. If you do not stop, then the application will be in an undetermined state. No application should be allowed to run in that case.

**Comment by Tieske** [comment]
as per above, I'm in favour of closing this.
