### ISSUE TITLE
Admin API should support apikeys

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#1630]
When adding Key Authentication on top of the Admin API, it's currently not possible to query entities because the system fails with:

``` http
GET kong:8000/admin/consumers/?apikey=hello_world

{
   "apikey": "unknown field"
}
```

This check should only be disabled on the Admin API, but not at the DAO level.

**Comment by thefosk** [comment]
Or better, if the admin API supported some form of Basic Auth we wouldn't need to use the apikey workaround.

**Comment by halliej** [comment]
You can get around this by making an "Admin" api and applying the proper plugins to the new api. Then you can disable outside access to port 8001 forcing all admin request to go through the gateway with proper creds.

**Comment by p0pr0ck5** [comment]
Kong Enterprise now supports RBAC, obviating the need to cover over the Admin API with a separate Kong instance running key authentication. In addition, the `hide_credentials` configuration option of key-auth solves this. Closing as such!

**Comment by BrunoQuaresma** [comment]
I have a registered Plugin for an API:

```
{
    "total": 1,
    "data": [
        {
            "created_at": 1522873440000,
            "config": {
                "key_in_body": false,
                "hide_credentials": true,
                "anonymous": "",
                "run_on_preflight": true,
                "key_names": [
                    "apikey"
                ]
            },
            "id": "e8bf4929-078a-4aaa-9a00-19d540ada1a4",
            "name": "key-auth",
            "api_id": "25b52582-8f53-41c6-bf1b-a31e6eadac40",
            "enabled": true
        }
    ]
}
```

Even with hide_credentials equals true when I try to make a request the response is:

```
{
    "apikey": "apikey is an unknown field"
}
```

How can I solve this issue?
