### ISSUE TITLE
Assertion error in 0.9.1 / AWS Marketplace edition

### ISSUE THREAD

**Issue by chris-hailstorm** [Mashape/kong#1632]
### Summary

Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:17: bad argument #2 to 'assert' (string expected, got table)

### Steps To Reproduce

1. Provision the Kong AWS Marketplace image in us-west-2 region (ami-e3bf6f83)
2. Start the instance and connect to it as the ec2-user user ID
3. Run: kong start
4. Get the error noted above

### Additional Details & Logs

- Kong version (`$ kong version`) -- 0.9.1
- Kong debug-level startup logs (`$ kong start --vv`)

2016/09/14 16:25:00 [verbose] no config file found at /etc/kong.conf
2016/09/14 16:25:00 [verbose] no config file found at /etc/kong/kong.conf
2016/09/14 16:25:00 [verbose] no config file, skipping loading
2016/09/14 16:25:00 [debug] admin_listen = "0.0.0.0:8001"
2016/09/14 16:25:00 [debug] anonymous_reports = true
2016/09/14 16:25:00 [debug] cassandra_consistency = "ONE"
2016/09/14 16:25:00 [debug] cassandra_contact_points = {"127.0.0.1"}
2016/09/14 16:25:00 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2016/09/14 16:25:00 [debug] cassandra_keyspace = "kong"
2016/09/14 16:25:00 [debug] cassandra_port = 9042
2016/09/14 16:25:00 [debug] cassandra_repl_factor = 1
2016/09/14 16:25:00 [debug] cassandra_repl_strategy = "SimpleStrategy"
2016/09/14 16:25:00 [debug] cassandra_ssl = false
2016/09/14 16:25:00 [debug] cassandra_ssl_verify = false
2016/09/14 16:25:00 [debug] cassandra_timeout = 5000
2016/09/14 16:25:00 [debug] cassandra_username = "kong"
2016/09/14 16:25:00 [debug] cluster_listen = "0.0.0.0:7946"
2016/09/14 16:25:00 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2016/09/14 16:25:00 [debug] cluster_profile = "wan"
2016/09/14 16:25:00 [debug] cluster_ttl_on_failure = 3600
2016/09/14 16:25:00 [debug] custom_plugins = {}
2016/09/14 16:25:00 [debug] database = "postgres"
2016/09/14 16:25:00 [debug] dnsmasq = true
2016/09/14 16:25:00 [debug] dnsmasq_port = 8053
2016/09/14 16:25:00 [debug] log_level = "notice"
2016/09/14 16:25:00 [debug] lua_code_cache = "on"
2016/09/14 16:25:00 [debug] lua_package_cpath = ""
2016/09/14 16:25:00 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2016/09/14 16:25:00 [debug] lua_ssl_verify_depth = 1
2016/09/14 16:25:00 [debug] mem_cache_size = "128m"
2016/09/14 16:25:00 [debug] nginx_daemon = "on"
2016/09/14 16:25:00 [debug] nginx_optimizations = true
2016/09/14 16:25:00 [debug] nginx_worker_processes = "auto"
2016/09/14 16:25:00 [debug] pg_database = "kong"
2016/09/14 16:25:00 [debug] pg_host = "127.0.0.1"
2016/09/14 16:25:00 [debug] pg_port = 5432
2016/09/14 16:25:00 [debug] pg_ssl = false
2016/09/14 16:25:00 [debug] pg_ssl_verify = false
2016/09/14 16:25:00 [debug] pg_user = "kong"
2016/09/14 16:25:00 [debug] prefix = "/usr/local/kong/"
2016/09/14 16:25:00 [debug] proxy_listen = "0.0.0.0:8000"
2016/09/14 16:25:00 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2016/09/14 16:25:00 [debug] serf_path = "serf"
2016/09/14 16:25:00 [debug] ssl = true
2016/09/14 16:25:00 [verbose] prefix in use: /usr/local/kong
2016/09/14 16:25:00 [verbose] running datastore migrations
2016/09/14 16:25:00 [verbose] could not start Kong, stopping services
2016/09/14 16:25:00 [verbose] leaving serf cluster
2016/09/14 16:25:00 [verbose] stopping dnsmasq at /usr/local/kong/pids/dnsmasq.pid
cat: /usr/local/kong/pids/dnsmasq.pid: No such file or directory
2016/09/14 16:25:00 [verbose] stopped services
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:37: /usr/local/share/lua/5.1/kong/cmd/start.lua:17: bad argument #2 to 'assert' (string expected, got table)
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:37: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:81>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:42>
	/usr/local/bin/kong:11: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'pcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

Linux version 4.4.5-15.26.amzn1.x86_64 (mockbuild@gobi-build-60007) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Wed Mar 16 17:15:34 UTC 2016

**Comment by thibaultcha** [comment]
This has been taken care of in e04273f8af223a7cfb7e5077b79eec49699935b0. Will be part of a future release. If you wish to see the actual error, apply this patch or use the `master` branch. Thanks!
