### ISSUE TITLE
Postgres setup instructions incomplete

### ISSUE THREAD

**Issue by chris-hailstorm** [Mashape/kong#1634]
### Summary

This page: https://getkong.org/install/aws-linux/

Says to connect to Postgres and run:
CREATE USER kong;
CREATE DATABASE kong OWNER kong;

In my instance of Postgres, an additional step is required between the two steps given:
CREATE USER kong;
GRANT kong TO whatever-you-user-ID-is;
CREATE DATABASE kong OWNER kong;

The install instructions need to be updated (and probably for other OS / packaging variants too)

### Steps To Reproduce

1.  Run a Postgres server, version PostgreSQL 9.4.7 on x86_64-unknown-linux-gnu
2.  NOTE my Postgres server is running in Amazon RDS
3.  Try running: create user kong; create database kong owner kong;
4.  Observe the error: ERROR:  must be member of role "kong"

### Additional Details & Logs

- Kong version (`$ kong version`)  DOES NOT APPLY, operation is 100% Postgres
- Kong debug-level startup logs (`$ kong start --vv`)  DOES NOT APPLY, operation is 100% Postgres
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)  DOES NOT APPLY, operation is 100% Postgres
- Kong configuration (registered APIs/Plugins & configuration file)  DOES NOT APPLY, operation is 100% Postgres
- Operating System -- DOES NOT APPLY, operation is 100% Postgres

**Comment by thibaultcha** [comment]
Moved to the proper repo: https://github.com/Mashape/getkong.org/issues/278

Thanks for the report.
