### ISSUE TITLE
Updating Kong corrupts luarocks manifest when using CentOS 7 RPMs

### ISSUE THREAD

**Issue by kylegato** [Mashape/kong#1638]
### Summary

When upgrading Kong via RPM, it does not appear to be properly removing old lua module versions. This results in behavior that requires someone to manually fix their manifest files and clean up their luarocks/rocks/APP dir manually.
### Steps To Reproduce
1. Install Kong 0.9.0 on CentOS 7, with the RPM.
2. Install Kong 0.9.1 on the same CentOS 7 box, with the RPM.
3. Install a third party luarock (such as: luarocks install say)
4. Try to remove the luarock (ex: luarocks remove say)

```
[root@kong0 ~]# luarocks remove say
Checking stability of dependencies on the absence of
say 1.3-1...

Removing say 1.3-1...

Error: rock_manifest file not found for kong 0.9.0-0 - not a LuaRocks 2 tree?
[root@kong0 ~]# 
```

This appears to affect all mashape packages:

```
[root@kong0 kong]# pwd
/usr/local/lib/luarocks/rocks/kong
[root@kong0 kong]# ls -la
total 4
drwxr-xr-x  4 root root   34 Sep 14 14:51 .
drwxr-xr-x 31 root root 4096 Sep 14 14:51 ..
drwxr-xr-x  3 root root   16 Sep  7 16:01 0.9.0-0
drwxr-xr-x  3 root root   64 Sep  7 16:01 0.9.1-0
[root@kong0 kong]# mv 0.9.0-0 /tmp/
[root@kong0 kong]# luarocks install say
Warning: Failed searching manifest: Failed extracting manifest file
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/say-1.3-1.rockspec...
Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/say-1.3-1.rockspec... switching to 'build' mode
Updating manifest for /usr/local/lib/luarocks/rocks
say 1.3-1 is now built and installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)

[root@kong0 kong]# luarocks remove say
Checking stability of dependencies on the absence of
say 1.3-1...

Removing say 1.3-1...

Error: rock_manifest file not found for pgmoon-mashape 1.7.0-1 - not a LuaRocks 2 tree?
[root@kong0 kong]# 

```
### Additional Details & Logs
- Kong version 0.9.1
- Operating System CentOS Linux release 7.2.1511 (Core) - 3.10.0-327.28.3.el7.x86_64

**Comment by Tieske** [comment]
is this the right place? seems like a [LuaRocks](https://github.com/keplerproject/luarocks) issue to me?

**Comment by p0pr0ck5** [comment]
Closing, as noted above this looks like an issue to discuss with luarocks.
