### ISSUE TITLE
Datadog plugin to record 

### ISSUE THREAD

**Issue by kepheusikarius** [Mashape/kong#1642]
I'm running Kong 0.9.1 and looking at the Datadog plugin. It appears that Kong only uses the api name for the metric rather than the method and full route of the request. For instance, if I register the Datadog plugin at `/foo`, I don't get reporting at `/foo/bar` or even if I'm doing a POST or GET.

Is there a way to get more details in the metric? Having plugins apply to all child routes is really handy, but clumping together the results of a deep REST API is not.

**Comment by shashiranjan84** [comment]
@kepheusikarius did you try Galilleo Plugin? If not i would advise to give it a try. Its a powerful tool for API analytics.

https://getkong.org/plugins/galileo/

Regarding Datadog, metrics are based of statsd format and has limited flexibility regarding the amount of data that can be saved.  More API info can be added through Tags but that does not seem practical.

**Comment by kepheusikarius** [comment]
I agree that tags are impractical, which is why I suggested the metric name. And while I grant that Galileo does record the data I'm looking for, I find it somewhat telling that your initial response is to promote your own product.

**Comment by shashiranjan84** [comment]
@kepheusikarius I do not see any other way to put more details about API without using Tags. You can also try Syslog plugin which logs request/response detail to a specified Syslog server.
