### ISSUE TITLE
[warn] 3507#0: *334576 an upstream response is buffered to a temporary file /usr/local/kong/proxy_temp/6/14/0000000146 while reading upstream

### ISSUE THREAD

**Issue by dzhyw** [Mashape/kong#1652]
### Summary

- Kong version (`$ kong version`)
  kong 0.9.1

tail -f error.log
2016/09/18 18:27:58 [warn] 3505#0: *354358 an upstream response is buffered to a temporary file /usr/local/kong/proxy_temp/1/16/0000000161 while reading upstream, client: 172.21.12.2, server: kong, request: "GET

how to fix?

**Comment by thibaultcha** [comment]
This is Nginx's behavior, not Kong. See [nginx_http_proxy_module](http://nginx.org/en/docs/http/ngx_http_proxy_module.html)'s directives and how to configure them . See the `proxy_max_temp_file_size` and `proxy_buffers` in particular.

**Comment by dzhyw** [comment]
Thank you, according to your approach has been resolved

**Comment by geostant** [comment]
@dzhyw 
Can you please elaborate how did you fixed that ?
I've the same issue where the first request to kong is being written to the buffer while the second one goes without buffer needs.

**Comment by jiaomengchong** [comment]
Set the size of the parameter client_body_buffer_size in the kong.conf file. @geostant

**Comment by geostant** [comment]
@jiaomengchong 3 years ago in hitech nation... swapped several jobs since than :D

**Comment by jagerzhang** [comment]
how to fix it in a docker container?

**Comment by chris-aeviator** [comment]
> how to fix it in a docker container?

@jagerzhang use environment variables

```
NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE=250k
```
