### ISSUE TITLE
KONG Responds with 401 Unauthorized "The access token is missing" instead of reponding with "redirect_uri" while Creating OAuth APPlication

### ISSUE THREAD

**Issue by Arun-Trichy** [Mashape/kong#1655]
1) Created an OAuth2 Plugin
curl -X POST http://127.0.0.1:8001/apis/mongodb/plugins \
    --data "name=oauth2" \
    --data "config.enable_authorization_code=true" \
    --data "config.scopes=email,phone,address" \
    --data "config.mandatory_scope=true"
OUTPUT:
{
"api_id":"d5d2566c-c77c-4bad-8909-d007671dd711",
"id":"983bc23e-ec4e-4fcf-88fb-ec4e397d414e",
"created_at":1474095960000,
"enabled":true,
"name":"oauth2",
"config":
{
    "mandatory_scope":true,
    "token_expiration":7200,
    "enable_implicit_grant":false,
    "scopes"["email","phone","address"],
    "hide_credentials":false,
    "enable_password_grant":false,
    "accept_http_if_already_terminated":false,
    "provision_key":"6c10262f8f41478cbb76ccb75697e509",
    "enable_client_credentials":false,
    "enable_authorization_code":true
}
}

2)Created a Consumer:
curl -i -X POST --url http://localhost:8001/consumers/ --data "username=iot" --data "custom_id=IOT_02"
OUTPUT:
{"custom_id":"IOT_02","username":"iot","created_at":1474095029000,"id":"1859840f-b643-439f-8cbf-6810aff95236"}

3)Created an APPlication:
curl -X POST http://localhost:8001/consumers/iot/oauth2 \
    --data "name=Test%20Application" \
    --data "client_id=SOME-CLIENT-ID" \
    --data "client_secret=SOME-CLIENT-SECRET" \
    --data "redirect_uri=http://10.226.110.112:3000/api/products"
OUTPUT:
{"data":[{"consumer_id":"1859840f-b643-439f-8cbf-6810aff95236","client_id":"SOME-CLIENT-ID","id":"3e518bfa-97de-4a95-a611-e90498e67dbd","redirect_uri":["http:\/\/10.226.110.112:3000\/api\/products"],"name":"Test Application","created_at":1474095340000,"client_secret":"SOME-CLIENT-SECRET"}],"total":1}

4)Web App(Authorization Page) accesses the KONG for APP Name:
curl http://localhost:8001/oauth2?client_id=SOME-CLIENT-ID
OUTPUT:
{"data":[{"consumer_id":"1859840f-b643-439f-8cbf-6810aff95236","client_id":"SOME-CLIENT-ID","id":"3e518bfa-97de-4a95-a611-e90498e67dbd","redirect_uri":["http:\/\/10.226.110.112:3000\/api\/products"],"name":"Test Application","created_at":1474095340000,"client_secret":"SOME-CLIENT-SECRET"}],"total":1}

5)HTTPS Based POST request to KONG for getting the redirect URI:
curl -i -X POST https://localhost:8443/apis/mongodb/oauth2/authorize \
    --header "Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW" \
    --data 'client_id=SOME-CLIENT-ID' \
    --data 'client_secret=SOME-CLIENT-SECRET' \
    --data 'response_type=code' \
    --data 'scope=email' \
    --data 'provision_key=6c10262f8f41478cbb76ccb75697e509' \
    --data 'authenticated_userid=abcd' --insecure
OUTPUT:
HTTP/1.1 401 Unauthorized
Date: Mon, 19 Sep 2016 06:57:15 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: kong/0.9.1
WWW-Authenticate: Bearer realm="service"

{"error_description":"The access token is missing","error":"invalid_request"}

---

I expect something like this:
{
  "redirect_uri": "http://some/url"
}
(or) uri along with code
## http://getkong.org/?code=ad286cf6694d40aac06eff2797b7208d

Questions:
1) Why is the access token not getting generated?
2) Is my approach correct, Am I missing something?
### Additional Details & Logs
- Kong version (`$ kong version`)      - 0.9.1
- Kong debug-level startup logs (`$ kong start --vv`)      - No ERRORS
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)         - No ERRORS
- Kong configuration (registered APIs/Plugins & configuration file)      - Changed database to Cassandra
- Operating System     - CentOS

**Comment by kkindaface** [comment]
From my understanding of Oauth2:

#5 in your steps seems to be incorrect. Authorization token is generated as a first step token for which you don't need to pass the Authorization header and also the client_secret. 

After you get the 'code' is when you typically make a server to server call for the bearer token using the /token endpoint and which is where you pass in the grant_type, client_secret, code from previous step, etc.

HTH

**Comment by p0pr0ck5** [comment]
Closing after the response above. This doesn't seem to be a issue.
