### ISSUE TITLE
Question: how can I enable the ssl for kong?

### ISSUE THREAD

**Issue by jxcheng008** [Mashape/kong#1663]
### Summary
I would like to use curl https://localhost:8443 to access kong. I have setup the kong.conf but it pops up an error message: 
Error:
/usr/local/share/lua/5.1/kong/cmd/reload.lua:13: ssl_cert is not a string: 'table: 0x407ccad0'
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/reload.lua:13: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:81>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:42>
        /usr/local/bin/kong:11: in function 'file_gen'
        init_worker_by_lua:38: in function <init_worker_by_lua:36>
        [C]: in function 'pcall'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>

I have read some issues posted but cannot understand how to solve it.

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`) 0.9.0
- Kong debug-level startup logs (`$ kong start --vv`) 
2016/09/20 16:05:12 [verbose] no config file found at /etc/kong.conf
2016/09/20 16:05:12 [verbose] reading config file at /etc/kong/kong.conf
2016/09/20 16:05:12 [debug] admin_listen = "0.0.0.0:8001"
2016/09/20 16:05:12 [debug] anonymous_reports = true
2016/09/20 16:05:12 [debug] cassandra_consistency = "ONE"
2016/09/20 16:05:12 [debug] cassandra_contact_points = {"127.0.0.1"}
2016/09/20 16:05:12 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2016/09/20 16:05:12 [debug] cassandra_keyspace = "kong"
2016/09/20 16:05:12 [debug] cassandra_port = 9042
2016/09/20 16:05:12 [debug] cassandra_repl_factor = 1
2016/09/20 16:05:12 [debug] cassandra_repl_strategy = "SimpleStrategy"
2016/09/20 16:05:12 [debug] cassandra_ssl = false
2016/09/20 16:05:12 [debug] cassandra_ssl_verify = false
2016/09/20 16:05:12 [debug] cassandra_timeout = 5000
2016/09/20 16:05:12 [debug] cassandra_username = "kong"
2016/09/20 16:05:12 [debug] cluster_listen = "0.0.0.0:7946"
2016/09/20 16:05:12 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2016/09/20 16:05:12 [debug] cluster_profile = "wan"
2016/09/20 16:05:12 [debug] cluster_ttl_on_failure = 3600
2016/09/20 16:05:12 [debug] custom_plugins = {}
2016/09/20 16:05:12 [debug] database = "postgres"
2016/09/20 16:05:12 [debug] dnsmasq = true
2016/09/20 16:05:12 [debug] dnsmasq_port = 8053
2016/09/20 16:05:12 [debug] log_level = "notice"
2016/09/20 16:05:12 [debug] lua_code_cache = "on"
2016/09/20 16:05:12 [debug] lua_package_cpath = ""
2016/09/20 16:05:12 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2016/09/20 16:05:12 [debug] lua_ssl_verify_depth = 1
2016/09/20 16:05:12 [debug] mem_cache_size = "128m"
2016/09/20 16:05:12 [debug] nginx_daemon = "on"
2016/09/20 16:05:12 [debug] nginx_optimizations = true
2016/09/20 16:05:12 [debug] nginx_worker_processes = "auto"
2016/09/20 16:05:12 [debug] pg_database = "kong"
2016/09/20 16:05:12 [debug] pg_host = "127.0.0.1"
2016/09/20 16:05:12 [debug] pg_password = "******"
2016/09/20 16:05:12 [debug] pg_ssl = false
2016/09/20 16:05:12 [debug] pg_ssl_verify = false
2016/09/20 16:05:12 [debug] pg_user = "postgres"
2016/09/20 16:05:12 [debug] prefix = "/usr/local/kong/"
2016/09/20 16:05:12 [debug] proxy_listen = "0.0.0.0:8000"
2016/09/20 16:05:12 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2016/09/20 16:05:12 [debug] serf_path = "serf"
2016/09/20 16:05:12 [debug] ssl = true
2016/09/20 16:05:12 [verbose] prefix in use: /usr/local/kong
2016/09/20 16:05:12 [verbose] running datastore migrations
2016/09/20 16:05:12 [verbose] migrations up to date
2016/09/20 16:05:12 [verbose] preparing nginx prefix directory at /usr/local/kong
2016/09/20 16:05:12 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2016/09/20 16:05:12 [debug] searching for OpenResty 'resty' executable
2016/09/20 16:05:12 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.9.15.1'
2016/09/20 16:05:12 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2016/09/20 16:05:12 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2016/09/20 16:05:12 [verbose] SSL enabled, no custom certificate set: using default certificate
2016/09/20 16:05:12 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2016/09/20 16:05:12 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
2016/09/20 16:05:12 [verbose] dnsmasq not running, deleting /usr/local/kong/pids/dnsmasq.pid
2016/09/20 16:05:12 [debug] searching for 'dnsmasq' executable
2016/09/20 16:05:12 [debug] /usr/local/sbin/dnsmasq -v: ''
2016/09/20 16:05:12 [debug] 'dnsmasq' executable not found at /usr/local/sbin/dnsmasq
2016/09/20 16:05:12 [debug] /usr/local/bin/dnsmasq -v: ''
2016/09/20 16:05:12 [debug] 'dnsmasq' executable not found at /usr/local/bin/dnsmasq
2016/09/20 16:05:12 [debug] /usr/sbin/dnsmasq -v: 'Dnsmasq version 2.75  Copyright (c) 2000-2015 Simon Kelley'
2016/09/20 16:05:12 [debug] found 'dnsmasq' executable at /usr/sbin/dnsmasq
2016/09/20 16:05:12 [debug] starting dnsmasq: /usr/sbin/dnsmasq -p 8053 --pid-file=/usr/local/kong/pids/dnsmasq.pid -N -o --listen-address=127.0.0.1
2016/09/20 16:05:12 [verbose] serf agent not running, deleting /usr/local/kong/pids/serf.pid
2016/09/20 16:05:12 [debug] checking 'serf' executable from 'serf_path' config setting
2016/09/20 16:05:12 [debug] serf version: 'Serf v0.7.0'
2016/09/20 16:05:12 [debug] starting serf agent: nohup serf agent -profile 'wan' -rpc-addr '127.0.0.1:7373' -event-handler 'member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf/serf_event.sh' -bind '0.0.0.0:7946' -node 'apigw_0.0.0.0:7946_465a78ad93cc432ea8369824d49506d6' -log-level 'err' > /usr/local/kong/logs/serf.log 2>&1 & echo $! > /usr/local/kong/pids/serf.pid
2016/09/20 16:05:12 [verbose] waiting for serf agent to be running
2016/09/20 16:05:12 [verbose] serf agent started
2016/09/20 16:05:12 [verbose] auto-joining serf cluster
2016/09/20 16:05:12 [verbose] no other nodes found in the cluster
2016/09/20 16:05:12 [verbose] registering serf node in datastore
2016/09/20 16:05:12 [verbose] cluster joined and node registered in datastore
2016/09/20 16:05:12 [debug] searching for OpenResty 'nginx' executable
2016/09/20 16:05:12 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.9.15.1'
2016/09/20 16:05:12 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2016/09/20 16:05:12 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2016/09/20 16:05:12 [debug] nginx started
2016/09/20 16:05:12 [info] Kong started

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)

#------------------------------------------------------------------------------
# NGINX
#------------------------------------------------------------------------------

#proxy_listen = 0.0.0.0:8001     # Address and port on which Kong will accept
                                 # HTTP requests.
                                 # This is the public-facing entrypoint of
                                 # Kong, to which your consumers will make
                                 # requests to.
# Note: See http://nginx.org/en/docs/http/ngx_http_core_module.html#listen for
# a description of the accepted formats for this and other *_listen values.

#proxy_listen_ssl = 0.0.0.0:8443 # Address and port on which Kong will accept
                                 # HTTPS requests if `ssl` is enabled.

#admin_listen = 0.0.0.0:8001     # Address and port on which Kong will expose
                                 # an entrypoint to the Admin API.
                                 # This API lets you configure and manage Kong,
                                 # and should be kept private and secured.

#nginx_worker_processes = auto   # Determines the number of worker processes
                                 # spawned by Nginx.

#nginx_daemon = on               # Determines wether Nginx will run as a daemon
                                 # or as a foreground process. Mainly useful
                                 # for development or when running Kong inside
                                 # a Docker environment.

#mem_cache_size = 128m           # Size of the in-memory cache for database
                                 # entities. The accepted units are `k` and
                                 # `m`, with a minimum recommended value of
                                 # a few MBs.

#ssl = on                        # Determines if Nginx should be listening for
                                 # HTTPS traffic on the `proxy_listen_ssl`
                                 # address. If disabled, Nginx will only bind
                                 # itself on `proxy_listen`, and all SSL
                                 # settings will be ignored.

#ssl_cert = /home/bectech/403f9e647735e2a1.crt                     # If `ssl` is enabled, the absolute path to
                                 # the SSL certificate for the
                                 # `proxy_listen_ssl` address.

#ssl_cert_key = /home/bectech/lcms.io.key                  # If `ssl` is enabled, the absolute path to
                                 # the SSL key for the `proxy_listen_ssl`
                                 # address.

- Operating System  Ubuntu 16.04 LTS

**Comment by thibaultcha** [comment]
Your certificate and key must be in PEM format

**Comment by jxcheng008** [comment]
I have setup my api behind the gateway and I use a domain name. When I try to connect to my api, it pops up a timeout message as following: 
* upload completely sent off: 44 out of 44 bytes
< HTTP/1.1 504 Gateway Time-out
< Date: Wed, 21 Sep 2016 16:34:28 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Server: kong/0.9.0
<
{"message":"The upstream server is timing out"}
* Connection #0 to host 172.10.50.90 left intact
any recommendation for it?

**Comment by thefosk** [comment]
Does the upstream API work?

**Comment by jxcheng008** [comment]
yes, the upstream API works when directly connecting to it. But when I add my API to kong, it pops up the timeout message

**Comment by thefosk** [comment]
@jxcheng008 could there be any firewall restriction that prevents Kong from consuming the API? 

* Can you manually SSH into the Kong machine and, from that machine, consume the API directly without Kong?
* Does the API or firewall accept the additional headers that Kong is appending to the upstream request?

**Comment by jxcheng008** [comment]
I will check it. It seems like the problem is caused by the gateway. I will check the gateway restriction to see what is the reason. Thanks very much

**Comment by jxcheng008** [comment]
I have checked my upstream api and everything works well. The only problem is when I add cert and key to kong.conf, it pops up errors saying " Error: ssl_cert is not a string: 'table: 0x4038a500' ". I have convert my crt and key to pem format.
Error message with --trace:
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:10: ssl_cert is not a string: 'table: 0x41cefc08'
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:10: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:81>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:42>
        /usr/local/bin/kong:11: in function 'file_gen'
        init_worker_by_lua:38: in function <init_worker_by_lua:36>
        [C]: in function 'pcall'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>

**Comment by thefosk** [comment]
Can you try to update to latest 0.9.2?

**Comment by jxcheng008** [comment]
I have another question. I added the ssl plugin for an https API server to kong followed the instruction. But when I use curl cmd, it still says the cert is not valid. Here are error messages:
*   Trying ::1...
* connect to ::1 port 8443 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 694 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
* Closing connection 0
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by thefosk** [comment]
It seems like the certificate you uploaded is not valid, or doesn't include the bundle certificate. Make sure that the certificate has been created properly to work with nginx.

**Comment by shashiranjan84** [comment]
@jxcheng008 closing this ticket. Feel free to reopen if you still facing the issue.
