### ISSUE TITLE
Kong 0.9.2 Docker image not available on Docker Hub

### ISSUE THREAD

**Issue by nullfox** [Mashape/kong#1673]
### Summary

According to this repo and Mashape/docker-kong version 0.9.2 of Kong has been released, however when trying to pull 0.9.2 in my Dockerfile, it's not found in the repo.

### Steps To Reproduce

1. Put `FROM mashape/kong:0.9.2` in Dockerfile
2. Run docker build -t image/name .
3. Fails with error `Tag 0.9.2 not found in repository docker.io/mashape/kong`

### Additional Details & Logs

Docker log:

```
Sending build context to Docker daemon 21.02 MB
Step 1 : FROM mashape/kong:0.9.2
Pulling repository docker.io/mashape/kong
Tag 0.9.2 not found in repository docker.io/mashape/kong
```

**Comment by shashiranjan84** [comment]
Now we have official repo, please pull `kong`.

https://hub.docker.com/_/kong/
