### ISSUE TITLE
kong start does not obey the "-c" flag?

### ISSUE THREAD

**Issue by chris-hailstorm** [Mashape/kong#1675]
### Summary

I'm trying to run multiple instances of Kong on one box, using "kong start -c" to specify a config file for each.  II always get an error message: "Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: nginx is already running in /usr/local/kong"

Looking at the verbose logs, it appears the config file I'm specifying isn't being used.

### Steps To Reproduce

1.  create two Kong config files, kong.conf and dev-kong.conf
2.  ensure settings are different between the two: prefix (/usr/local/kong/ vs. /usr/local/dev-kong/), proxy_listen (8000 vs. 8001), admin_listen (9000 vs. 9001), and DB connection
3.  run: start kong -c /path/to/kong.conf -- works fine
4.  run: kong start -c /path/to-dev-kong.conf
5.  Error: "Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: nginx is already running in /usr/local/kong"

One clue: when I use "kong start -vv -c" to specify the config file to load, it appears kong reads the config file at /etc/kong.conf, instead which the kong installer created as a symlink that points to /etc/kong/kong.conf.  First few lines of the verbose log follow:

[ec2-user@ip-172-31-17-169 kong]$ kong start -vv -c ./dev-kong.conf 
2016/09/22 19:47:48 [verbose] reading config file at /etc/kong.conf
2016/09/22 19:47:48 [debug] admin_listen = "0.0.0.0:9000"  <-- from kong.conf, not dev-
...

Second clue: deleting /etc/kong.conf does not change matters. First few lines of verbose log:

[ec2-user@ip-172-31-17-169 kong]$ kong start -vv -c ./dev-kong.conf 
2016/09/22 19:53:13 [verbose] no config file found at /etc/kong.conf
2016/09/22 19:53:13 [verbose] reading config file at /etc/kong/kong.conf

Third clue: using a full path to the config file (kong start -vv -c /etc/kong/dev-kong.conf) does not change anything.

### Additional Details & Logs

- Kong version (`$ kong version`) -- 0.9.1
- Kong debug-level startup logs (`$ kong start --vv`)

[ec2-user@ip-172-31-17-169 kong]$ kong start -vv -c ./dev-kong.conf 
2016/09/22 19:47:48 [verbose] reading config file at /etc/kong.conf
2016/09/22 19:47:48 [debug] admin_listen = "0.0.0.0:9000"  <-- from kong.conf, not dev-
2016/09/22 19:47:48 [debug] anonymous_reports = true
2016/09/22 19:47:48 [debug] cassandra_consistency = "ONE"
2016/09/22 19:47:48 [debug] cassandra_contact_points = {"127.0.0.1"}
2016/09/22 19:47:48 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2016/09/22 19:47:48 [debug] cassandra_keyspace = "kong"
2016/09/22 19:47:48 [debug] cassandra_port = 9042
2016/09/22 19:47:48 [debug] cassandra_repl_factor = 1
2016/09/22 19:47:48 [debug] cassandra_repl_strategy = "SimpleStrategy"
2016/09/22 19:47:48 [debug] cassandra_ssl = false
2016/09/22 19:47:48 [debug] cassandra_ssl_verify = false
2016/09/22 19:47:48 [debug] cassandra_timeout = 5000
2016/09/22 19:47:48 [debug] cassandra_username = "kong"
2016/09/22 19:47:48 [debug] cluster_listen = "0.0.0.0:7946"
2016/09/22 19:47:48 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2016/09/22 19:47:48 [debug] cluster_profile = "wan"
2016/09/22 19:47:48 [debug] cluster_ttl_on_failure = 3600
2016/09/22 19:47:48 [debug] custom_plugins = {}
2016/09/22 19:47:48 [debug] database = "postgres"
2016/09/22 19:47:48 [debug] dnsmasq = true
2016/09/22 19:47:48 [debug] dnsmasq_port = 8053
2016/09/22 19:47:48 [debug] log_level = "notice"
2016/09/22 19:47:48 [debug] lua_code_cache = "on"
2016/09/22 19:47:48 [debug] lua_package_cpath = ""
2016/09/22 19:47:48 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2016/09/22 19:47:48 [debug] lua_ssl_verify_depth = 1
2016/09/22 19:47:48 [debug] mem_cache_size = "128m"
2016/09/22 19:47:48 [debug] nginx_daemon = "on"
2016/09/22 19:47:48 [debug] nginx_optimizations = true
2016/09/22 19:47:48 [debug] nginx_worker_processes = "auto"
2016/09/22 19:47:48 [debug] pg_database = "xxxxxxxx"
2016/09/22 19:47:48 [debug] pg_host = "xxxxxxxx"
2016/09/22 19:47:48 [debug] pg_password = "xxxxxxxx"
2016/09/22 19:47:48 [debug] pg_port = 5432
2016/09/22 19:47:48 [debug] pg_ssl = false
2016/09/22 19:47:48 [debug] pg_ssl_verify = false
2016/09/22 19:47:48 [debug] pg_user = "xxxxxxxx"
2016/09/22 19:47:48 [debug] prefix = "/usr/local/kong/"
2016/09/22 19:47:48 [debug] proxy_listen = "0.0.0.0:8000"
2016/09/22 19:47:48 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2016/09/22 19:47:48 [debug] serf_path = "serf"
2016/09/22 19:47:48 [debug] ssl = true
2016/09/22 19:47:48 [verbose] prefix in use: /usr/local/kong
2016/09/22 19:47:48 [verbose] running datastore migrations
2016/09/22 19:47:48 [verbose] migrations up to date
2016/09/22 19:47:48 [verbose] preparing nginx prefix directory at /usr/local/kong
2016/09/22 19:47:48 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2016/09/22 19:47:48 [debug] searching for OpenResty 'resty' executable
2016/09/22 19:47:48 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.9.15.1'
2016/09/22 19:47:48 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2016/09/22 19:47:48 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2016/09/22 19:47:48 [verbose] SSL enabled, no custom certificate set: using default certificate
2016/09/22 19:47:48 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2016/09/22 19:47:48 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
2016/09/22 19:47:48 [verbose] dnsmasq already running at /usr/local/kong/pids/dnsmasq.pid
2016/09/22 19:47:48 [verbose] serf agent already running at /usr/local/kong/pids/serf.pid
2016/09/22 19:47:48 [debug] searching for OpenResty 'nginx' executable
2016/09/22 19:47:48 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.9.15.1'
2016/09/22 19:47:48 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2016/09/22 19:47:48 [verbose] could not start Kong, stopping services
2016/09/22 19:47:48 [verbose] sending TERM signal to nginx running at /usr/local/kong/pids/nginx.pid
2016/09/22 19:47:48 [verbose] leaving serf cluster
2016/09/22 19:47:48 [verbose] left serf cluster
2016/09/22 19:47:48 [verbose] stopping serf agent at /usr/local/kong/pids/serf.pid
2016/09/22 19:47:48 [verbose] serf agent stopped
2016/09/22 19:47:48 [verbose] stopping dnsmasq at /usr/local/kong/pids/dnsmasq.pid
2016/09/22 19:47:48 [verbose] stopped services
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:37: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: nginx is already running in /usr/local/kong
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:37: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:81>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:42>
	/usr/local/bin/kong:11: in function 'file_gen'
	init_worker_by_lua:40: in function <init_worker_by_lua:38>
	[C]: in function 'pcall'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by thibaultcha** [comment]
Thanks for the report, I think I identified the issue.In the meantime and as a temporary fix, deleting the file at `/etc/kong/kong.conf` should allow Kong to honor the `-c` flag, if you want to give this a try.

**Comment by chris-hailstorm** [comment]
That does work around the issue, thank you.

**Comment by thibaultcha** [comment]
Fixed as per the PR. Expect 0.10 to be shipped with this fix, by the end of October.

**Comment by lsh-0** [comment]
+1
