### ISSUE TITLE
kong pagination does not work

### ISSUE THREAD

**Issue by trevortao** [Mashape/kong#1676]
### Summary

Access the Kong admin API to get all added apis with the pagination parameter (?size=n), Kong return a invalid 'next' value in its response body. 
The 'offset' field should be the UUID of the next availabe api, but currently it seems to be the current api offset.

### Steps To Reproduce

[root@localhost ~]# curl -X GET http://127.0.0.1:8001/apis?size=2 | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   587    0   587    0     0   4088      0 --:--:-- --:--:-- --:--:--  4076
{
  **"next": "http://127.0.0.1:8001/apis?size=2&offset=ABCNBErOcO5BnbjtgiVngdIFAA8ADHVwc3RyZWFtX3VybAB%2F%2F%2F%2F9",**
  "data": [
    {
      "upstream_url": "http://1.1.1.1",
      "strip_request_path": false,
      "id": "2b9df9f3-541c-4bc0-ac8c-07c4a55b9e93",
      "created_at": 1474596007000,
      "preserve_host": true,
      "name": "www.testkong70.com",
      "request_host": "www.testkong70.com"
    },
    {
      "upstream_url": "http://1.1.1.1",
      "strip_request_path": false,
      "id": "8d044ace-70ee-419d-b8ed-82256781d205",
      "created_at": 1474596006000,
      "preserve_host": true,
      "name": "www.testkong54.com",
      "request_host": "www.testkong54.com"
    }
  ],
  "total": 104
}

### Additional Details & Logs

- Kong version (`$ kong version`) 0.8.3 0.9.1
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file): No special
- Operating System: Linux(ubuntu, centos)

**Comment by trevortao** [comment]
It seems the Kong can not get correct 2nd params from the URL:
like:
http://localhost:8001/apis?size=2&offset=ABAgG0Cn%2F7FBV79w8S8QcTOOAA8ADHVwc3RyZWFtX3VybAB%2F%2F%2F%2F9

It can only get the first param that is size=2, but for the offset, it is nil
If the url is:http://localhost:8001/apis?offset=ABAgG0Cn%2F7FBV79w8S8QcTOOAA8ADHVwc3RyZWFtX3VybAB%2F%2F%2F%2F9&size=2,
it can get the first param for offset, but the size is nil which would be set to 100 again as the default value.

**Comment by thibaultcha** [comment]
I just tested this on Kong 0.9.1 and 0.9.2 and it works as expected on both Cassandra and PostgreSQL:
```
$ for i in {1..100}; do curl -X POST http://localhost:8001/apis -d name="api-n-$i" -d upstream_url="http://httpbin.org" -d request_host="api-n-$i.com" ; done;

$ curl -s 'http://127.0.0.1:8001/apis?size=2' | jq
{
  "next": "http://127.0.0.1:8001/apis?size=2&offset=Mg%3D%3D",
  "offset": "Mg==",
  "data": [
    {
      "upstream_url": "http://127.0.0.1:8001",
      "created_at": 1474254553000,
      "id": "92aa55b5-ec33-4c24-a2dd-32588c897f86",
      "name": "api-n-1",
      "preserve_host": false,
      "strip_request_path": false,
      "request_host": "api-1.com"
    },
    {
      "upstream_url": "http://127.0.0.1:8001",
      "created_at": 1474254553000,
      "id": "7ced6ae3-fe5b-422a-b848-9a0f2e3e857c",
      "name": "api-n-2",
      "preserve_host": false,
      "strip_request_path": false,
      "request_host": "api-2.com"
    }
  ],
  "total": 100
}

$ curl -s 'http://127.0.0.1:8001/apis?size=2&offset=Mg%3D%3D' | jq
{
  "next": "http://127.0.0.1:8001/apis?size=2&offset=Mw%3D%3D",
  "offset": "Mw==",
  "data": [
    {
      "upstream_url": "http://127.0.0.1:8001",
      "created_at": 1474254553000,
      "id": "a8bfabd9-fcc5-45c9-a220-727e1bcd26b0",
      "name": "api-n-3",
      "preserve_host": false,
      "strip_request_path": false,
      "request_host": "api-3.com"
    },
    {
      "upstream_url": "http://127.0.0.1:8001",
      "created_at": 1474254553000,
      "id": "fa9883ab-62fa-4387-b71a-e4a237826c76",
      "name": "api-n-4",
      "preserve_host": false,
      "strip_request_path": false,
      "request_host": "api-4.com"
    }
  ],
  "total": 100
}
```

And Cassandra:
```
$ curl -s 'http://127.0.0.1:8001/apis?size=2' | jq
{
  "next": "http://127.0.0.1:8001/apis?size=2&offset=ABAcPLaSe%2BJJqrknowb%2BrLTKAA8ADHVwc3RyZWFtX3VybAB%2F%2F%2F%2F9",
  "offset": "ABAcPLaSe+JJqrknowb+rLTKAA8ADHVwc3RyZWFtX3VybAB////9",
  "data": [
    {
      "upstream_url": "http://httpbin.org",
      "strip_request_path": false,
      "id": "8be5e7d2-1374-49f4-bddc-ab139055fa6e",
      "created_at": 1474901985000,
      "preserve_host": false,
      "name": "api-n-29",
      "request_host": "api-n-29.com"
    },
    {
      "upstream_url": "http://httpbin.org",
      "strip_request_path": false,
      "id": "1c3cb692-7be2-49aa-b927-a306feacb4ca",
      "created_at": 1474901984000,
      "preserve_host": false,
      "name": "api-n-13",
      "request_host": "api-n-13.com"
    }
  ],
  "total": 100
}

$ curl -s 'http://127.0.0.1:8001/apis?size=2&offset=ABAcPLaSe%2BJJqrknowb%2BrLTKAA8ADHVwc3RyZWFtX3VybAB%2F%2F%2F%2F9' | jq
{
  "next": "http://127.0.0.1:8001/apis?size=2&offset=ABBO%2FI7lmAtAGIjt7IYrK4kfAA8ADHVwc3RyZWFtX3VybAB%2F%2F%2F%2F7",
  "offset": "ABBO/I7lmAtAGIjt7IYrK4kfAA8ADHVwc3RyZWFtX3VybAB////7",
  "data": [
    {
      "upstream_url": "http://httpbin.org",
      "strip_request_path": false,
      "id": "14b8b456-977a-401c-9189-ca15e9795002",
      "created_at": 1474901984000,
      "preserve_host": false,
      "name": "api-n-11",
      "request_host": "api-n-11.com"
    },
    {
      "upstream_url": "http://httpbin.org",
      "strip_request_path": false,
      "id": "4efc8ee5-980b-4018-88ed-ec862b2b891f",
      "created_at": 1474901987000,
      "preserve_host": false,
      "name": "api-n-84",
      "request_host": "api-n-84.com"
    }
  ],
  "total": 100
}
```

Changing the order of the `size` and `offset` parameters in the querystring has no effect.

**Comment by thibaultcha** [comment]
One of the tests asserting this behavior can be found here: https://github.com/Mashape/kong/blob/master/spec/02-integration/03-admin_api/02-apis_routes_spec.lua#L283-L311

**Comment by trevortao** [comment]
Yes, I have tested in my local kong, it works.
The reason for the case produced in our environment may be due to our accidently comment on the sentence:
proxy_pass_header Server;
so we can not get the correct param from the accessing url when using a local loop

**Comment by csulrong** [comment]
Is the `offset` not formatted as a UUID? In your example, 

```
"offset": "ABAcPLaSe+JJqrknowb+rLTKAA8ADHVwc3RyZWFtX3VybAB////9",
```

What the value means to API user? I saw the documentation do use the UUID format for `offset`. Check https://getkong.org/docs/0.9.x/admin-api/#list-apis

**Comment by thibaultcha** [comment]
The documentation does not mention it is a UUID but an "object identifier" (?). While I do find that term confusing - we'll update it - the docs intention is to inform you that this value is a base64 encoded string, and that you should pass it back to the Admin API as it is. It is a cursor, and that should be how the documentation should refer to it.
