### ISSUE TITLE
Plugin Development Environment

### ISSUE THREAD

**Issue by driverpt** [Mashape/kong#1684]
### Summary

I want to be able to develop Standalone a Kong Plugin and be able to build it on Travis, run Unit/Integration Tests and deploy it to Lua Rocks.

Currently i'm not able to do so, see [here](https://github.com/driverpt/kong-redis-session) and [here](https://travis-ci.org/driverpt/kong-redis-session)

**Comment by Tieske** [comment]
how about; https://github.com/superpixelhq/kong-plugin-development

iirc @thibaultcha is also working on a setup for this.

**Comment by driverpt** [comment]
Does it work on Travis ?

**Comment by thibaultcha** [comment]
A testing module for Kong/Kong plugins will be available at https://github.com/Mashape/kong-spec, and will come with an example plugin; fully documented and tested on Travis CI. Closing this as I believe that answers the question, feel free to still ask any other question you may have on this thread though.

**Comment by driverpt** [comment]
@thibaultcha , you have any ETA on the Documentation?
