### ISSUE TITLE
Failed attempt to join a cluster terminates Serf

### ISSUE THREAD

**Issue by chris-hailstorm** [Mashape/kong#1685]
### Summary

Splitting from issue #1680.

Run instance (1) of Kong on a machine.  Attempt to run instance (2) that's configured to use the cluster ports used by (1) but is otherwise incompatible (different database config), on the same machine.  Attempt to run (2) fails, but Serf terminates on (1) without feedback.  Attempt to run (2) again, this time it works because ports are no longer in contention.
### Steps To Reproduce
1.  Create kong-1.conf.
2.  Create kong-2.conf.  Ensure proxy_listen, admin_listen, dnsmasq_port and the pg_ params are distinct from the -1 file.  Ensure cluster_listen and cluster_listen_rpc both MATCH the -1 file.
3.  Start the (1) instance: kong start -v -c /path/to/kong-1.conf -- observe which elements are running via: ps axu | grep -i -E 'kong|nginx|serf|dnsmasq' | grep -v grep -- note that serf is shown with parameters for the (1) instance
4.  Attempt to start the (2) instance via: kong start -v -c /path/to/kong-2.conf -- get this error: Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:22: could not start serf: Failed to start the Serf agent: Error creating Serf: Failed to create memberlist: Failed to start TCP listener. Err: listen tcp 0.0.0.0:7946: bind: address already in use
5.  Observe which elements are running via: `ps axu | grep -i -E 'kong|nginx|serf|dnsmasq' | grep -v grep` -- note that serf is no longer running, other elements of (1) are still running, and no elements of the failed (2) instance are running
6.  Attempt to start (2) again, this time succeeds: Kong started
7.  Observe which elements are running via: `ps axu | grep -i -E 'kong|nginx|serf|dnsmasq' | grep -v grep` -- note that elements of (1) other than serf are still running, and all elements of (2) including serf are running.
### Additional Details & Logs
- Kong version (`$ kong version`) -- 0.9.1
### Recommendation

-- When an instance tries and fails to join a cluster for any reason, don't allow that failure to kill serf (or other components) for the already-running instances. (The surprise was not that the new instance failed to join the cluster, but that in failing it killed serf for the OTHER instance.)

-- Determine which settings must be the same for an instance to join a cluster. Minimally that includes using the same database instance, maybe others (must be the same Kong version or ??). When a new node attempt to join a cluster, compare those items with a current cluster member. If the new instance doesn't match, abort the join from the new instance side.

**Comment by Tieske** [comment]
Still having this with 0.9.2? some fixes were made on failing startup behaviour.

**Comment by thefosk** [comment]
@chris-hailstorm 0.9.2 should terminate everything if a mandatory service like Serf fails to start.

Can you try?

**Comment by Tieske** [comment]
That's another fix, I was actually referring to the change that if you try to start an already started Kong instance, it errors, and then cleans up, effectively stopping the already running Kong instance. This was fixed in 0.9.2.

**Comment by p0pr0ck5** [comment]
Closing, since a). this is already listed as fixed a while ago, and b). serf is going away!
