### ISSUE TITLE
Kong cluster reconfiguration fails when admin_listen is set

### ISSUE THREAD

**Issue by rstreet-ossg** [Mashape/kong#1687]
Hello...

We found that with parameter admin_listen set the Kong cluster does not get signaled when an API is added or is changed.  Only a 'kong stop' and then 'kong start' makes the change live.

The cause of this is appears to be the generated serf_event.sh script.  It contains a call to 127.0.0.1 port 8001.  With admin_interface set to something other than 0.0.0.0, Kong is no longer listening on 127.0.0.1 and so the call fails. 

The code that generates the script pulls the port number from the configuration but does not handle the IP address.

A fix is to have the generated serf_event.sh use the admin_listen address if set, or fall back to 127.0.0.1 if '0.0.0.0' is used.

In prefix_handler.lua replace

  local script = fmt(script_template, "127.0.0.1", kong_config.admin_port, resty_bin)

with

   serf_admin_ip = kong_config.admin_ip
   if kong_config.admin_ip == '0.0.0.0' then
     serf_admin_ip = '127.0.0.1';
   end
   local script = fmt(script_template, serf_admin_ip, kong_config.admin_port, resty_bin)

Kong is then signalled and the API change propogates correctly.

Russell
### Steps To Reproduce
- Have a two node kong cluster  with a common (cassandra in our case) database.  Set 'admin_listen' to the IP address on each cluster node.

On kong1 have set
  admin_listen = 172.16.4.136:8001
and on kong2 have set
  admin_listen = 172.16.4.199:8001
-  Create API on kong1

$ curl -i -X POST --url http://172.16.4.136:8001/apis --data 'name=dummy' --data 'request_path=/dummy' --data 'upstream_url=http://172.16.4.136:8888/'
HTTP/1.1 201 Created
Date: Tue, 27 Sep 2016 03:05:17 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.9.2

{"upstream_url":"http:\/\/172.16.4.136:8888\/","strip_request_path":false,"request_path":"\/dummy","id":"24a3bb70-f133-4d5e-bd22-6088b36aa753","created_at":1474945517000,"preserve_host":false,"name":"dummy"}
- Validate new API appears in kong configuration of both nodes

$ curl http://172.16.4.136:8001/apis/dummy
{"upstream_url":"http:\/\/172.16.4.136:8888\/","strip_request_path":false,"request_path":"\/dummy","id":"24a3bb70-f133-4d5e-bd22-6088b36aa753","created_at":1474945517000,"preserve_host":false,"name":"dummy"}

$ curl http://172.16.4.199:8001/apis/dummy
{"upstream_url":"http:\/\/172.16.4.136:8888\/","strip_request_path":false,"request_path":"\/dummy","id":"24a3bb70-f133-4d5e-bd22-6088b36aa753","created_at":1474945517000,"preserve_host":false,"name":"dummy"}
- But can not access the API through port 8000

$ curl http://172.16.4.136:8000/dummy
{"request_path":"\/dummy","message":"API not found with these values","request_host":["172.16.4.136"]}

$ curl http://172.16.4.199:8000/dummy
{"request_path":"\/dummy","message":"API not found with these values","request_host":["172.16.4.199"]}
- Reload kong does not help...

$ kong reload
ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
Kong reloaded

$ curl http://172.16.4.136:8000/dummy
{"request_path":"\/dummy","message":"API not found with these values","request_host":["172.16.4.136"]}
- Restart kong does

$ kong restart
Kong stopped
ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
Kong started

$ curl http://172.16.4.136:8000/dummy
{"client":"172.16.4.136:36790","connection":"close","host":"172.16.4.136:8888","method":"GET","path":"/dummy","protocol":"HTTP/1.0"}

... but only for the node that I restarted.  Did not restart kong2 so it still does not know about /dummy

$ curl http://172.16.4.199:8000/dummy
{"request_path":"\/dummy","message":"API not found with these values","request_host":["172.16.4.199"]}

[Test after fix applied to prefix_handler.lua and restart]
- Create ...
  $ curl -i -X POST --url http://172.16.4.136:8001/apis --data 'name=dummy2' --data 'request_path=/dummy2' --data 'upstream_url=http://172.16.4.136:8888/'
  HTTP/1.1 201 Created
  Date: Tue, 27 Sep 2016 03:28:09 GMT
  Content-Type: application/json; charset=utf-8
  Transfer-Encoding: chunked
  Connection: keep-alive
  Access-Control-Allow-Origin: *
  Server: kong/0.9.2

{"upstream_url":"http:\/\/172.16.4.136:8888\/","strip_request_path":false,"request_path":"\/dummy2","id":"4d07f1de-be8b-421c-b27c-56c48dddee7c","created_at":1474946889000,"preserve_host":false,"name":"dummy2"}
- Check...

$ curl http://172.16.4.136:8001/apis/dummy2
{"upstream_url":"http:\/\/172.16.4.136:8888\/","strip_request_path":false,"request_path":"\/dummy2","id":"4d07f1de-be8b-421c-b27c-56c48dddee7c","created_at":1474946889000,"preserve_host":false,"name":"dummy2"}

$ curl http://172.16.4.199:8001/apis/dummy2
{"upstream_url":"http:\/\/172.16.4.136:8888\/","strip_request_path":false,"request_path":"\/dummy2","id":"4d07f1de-be8b-421c-b27c-56c48dddee7c","created_at":1474946889000,"preserve_host":false,"name":"dummy2"}
- Use ...

$ curl http://172.16.4.136:8000/dummy2
{"client":"172.16.4.136:37184","connection":"close","host":"172.16.4.136:8888","method":"GET","path":"/dummy2","protocol":"HTTP/1.0"}

$ curl http://172.16.4.199:8000/dummy2
{"client":"172.16.4.199:45350","connection":"close","host":"172.16.4.136:8888","method":"GET","path":"/dummy2","protocol":"HTTP/1.0"}
### Additional Details & Logs
- Kong version (`$ kong version`)
# kong version

0.9.2

Using 'kong-0.9.2.el7.noarch.rpm' build.
- Operating System
# cat /etc/redhat-release

CentOS Linux release 7.2.1511 (Core)

**Comment by HenryChelsea** [comment]
Hi, I have the same issues. When I changed the configs, kong can not make the changes live. And I need to use the commands "kong stoop" and "kong start" to make the changes live. Could you give some advices.(admin_listen is default)

**Comment by rstreet-ossg** [comment]
Hello....

The things that I looked at in detail:

Firewall on the servers set correctly for kong?  (And no firewalling on localhost/loopback connections!)

Does 'kong cluster members' and 'kong cluster reachability' work?

In the access_log file, do you see entries for /cluster/events as you make changes to the kong configuration?  Those were appearing on my working kong 0.8 cluster and not on the broken 0.9 cluster.


I traced my fault to the serf_event.sh script. The openresty connection it makes to localhost failed.

That was found by using strace on the kong processes and then trying to figure out what was failing that should not be failing. A lot of system calls come back with errors, so it takes some experience with strace to figure out which are normal and which ones are not.

The strace showed me a connect to localhost port 8001 that got a connection refused response. 
That was from the serf_event.sh script and that in turn was run by the serf program.

Russell

**Comment by thefosk** [comment]
Will be available with next Kong version (both 0.9.8 or 0.10.0)
