### ISSUE TITLE
Database migrations should not be automatic anymore

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#1692]
Automatic database migrations should not be automatic between upgrades.

If the keyspace is not empty, and a new versions of Kong is started that requires schema migrations, Kong should `exit(1)` with a warning message to the user, like:

```
Kong cannot start because the datastore is not empty and requires an explicit schema migration to support the new version.

Executing the schema migrations may break any existing Kong nodes that's currently relying on the old schema. Please follow the upgrade instructions at: https://github.com/Mashape/kong/blob/master/UPGRADE.md

To execute the migrations execute: "kong migrations up"
```

This is the first step in making upgrades between major versions more intuitive.

**Comment by brockmiller** [comment]
@thefosk - I'd love to see something like this as well.  Is this (or something similar) on the kong team's radar?

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [migrations](https://trello.com/c/qR57E5tv/13-migrations)

**Comment by thefosk** [comment]
@brockmiller you can check the PR ^

**Comment by brockmiller** [comment]
On it 👍
