### ISSUE TITLE
request_host and request_path

### ISSUE THREAD

**Issue by saithala** [Mashape/kong#1694]
### Summary

I have two API end points hosted in the same host and I want to proxy them through kong. I did the following
### Steps To Reproduce
1. curl -i -X POST \
   --url http://host1:8001/apis/ \
   --data 'name=api1' \
   --data 'upstream_url=http://backend:8765/' \
   --data 'request_host=host1'
2. The above worked fine
3. curl -i -X POST \
   --url http://host1:8001/apis/ \
   --data 'name=api2' \
   --data 'upstream_url=http://backend:8765/' \
   --data 'request_host=host1'
4. Step 3 failed because the request_host is same. It seems that either request_host or request path is mandatory. Is there a way to get around this?

**Comment by Tieske** [comment]
Obviously that doesn't work. If a request comes in for "http://host1/some/path", then Kong looks up what api it should use. Now should it be routing to api1 or api2?

Instead of using `request_host=host1` you could use `request_path=/path/to/api1` and similar for api2.

Not that the `request_path` is basically a `base path`, so a path `/path/to/api1/but/deeper/` will also be matched on api1.

**Comment by saithala** [comment]
thanks @Tieske for your response. If I dont configure the request host when I add the api, it does not work
so If I have multiple end points in the same host, depending upon the request uri, I need it to routed to api1 or api2. However it seems to me that the request_host is mandatory and does not work if I dont specify it

**Comment by saithala** [comment]
@Tieske @thefosk can someone please help me on this? I added two APIs without the request_host but with the request path and added an oauth2 plugin on top of one of them. After this, Im not getting the oauth2 tokens when I make the request.. All it returns is {"request_path":"\/oauth2\/token","message":"API not found with these values","request_host":["host"]}

**Comment by thefosk** [comment]
@saithala you need to append `/oauth2/token` to whatever `request_path` you have specified

**Comment by saithala** [comment]
Thanks @thefosk . The issue I have is if I follow that approach I will need to have one Token url for each API I add to Kong. Is there a way I can have just one token URL that I can use for all APIs?
Also, how can I add Oauth2 plugin for a single API? Right now, if I add an API for which I dont need oauth2 authentication, it fails and asks for valid token. As always thanks for your support

**Comment by rogoman** [comment]
Piggy-backing on the question, is it possible with Kong to route requests from the same host but different relative path to different proxy definitions? (e.g. handle static files differently than everything else)

**Comment by thibaultcha** [comment]
@rogoman Such routing capabilities are to be added in Kong 0.10. Closing this as I believe all the questions have been answered.
