### ISSUE TITLE
Inconsistencies(cli) default configuration file

### ISSUE THREAD

**Issue by WALL-E** [Mashape/kong#1697]
### Summary

when /etc/kong.conf and /etc/kong/kong.conf all exist, may cause confusion to the user

in kong/cmd/check.lua

```
local lapp = [[
Usage: kong check <conf>

Check the validity of a given Kong configuration file.

<conf> (default /etc/kong/kong.conf) configuration file
]]
```

in kong/conf_loader.lua

```
local DEFAULT_PATHS = {
  "/etc/kong.conf",
  "/etc/kong/kong.conf"
}
```

### Additional Details & Logs

- Kong version (0.9.2)

**Comment by thibaultcha** [comment]
`/etc/kong/kong.conf` is supposed to be the preferred way. Mind sending a PR chancing the order they are defined with in the `DEFAULT_PATHS` table?

**Comment by Tieske** [comment]
PR merged
