### ISSUE TITLE
Do not rely on configuration enabled_plugins order

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#17]
Currently we rely on the `enabled_plugins` property to determine which plugins must be executed, and the defined order matters in the execution (`authentication` must be executed before `ratelimiting` for example).

Execution order of the core plugins should be hard-coded, not depend on the user. And since they are core plugins, we could change this property to `disabled_plugins`, eventually.

**Comment by thefosk** [comment]
`enabled_plugins` is also a way for Kong to know which plugins to load besides the order of execution. I think removing it would be an improvement, but the system needs to make one more call to the datastore to load all the plugins enabled for a specific API or application before executing the request. This request would be something like:

```sql
SELECT DISTINCT name FROM plugins WHERE api_id = [ID]
```

and it could be cached when #15 has been implemented. And yes, the execution order needs to be hardcoded inside the plugin too.
