### ISSUE TITLE
Cassandra "set_keyspace" fails

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#170]
Under load, Kong returns a bunch occurrences of the following exception:

```
nginx: 2015/04/28 09:20:22 [error] 24637#0: *492903 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/cassandra.lua:243: Result expected
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/cassandra.lua:243: in function 'set_keyspace'
```
Does it need to try to set the keyspace every time? Can the operation be optimized?

**Comment by thibaultCha** [comment]
Yes it does need to because we are starting a new socket on every operation.

**Comment by thefosk** [comment]
I don't exactly know the internals, but I think it should use the nginx connection pool without restarting a new connection every time. Are we using http://wiki.nginx.org/HttpLuaModule#tcpsock:connect and http://wiki.nginx.org/HttpLuaModule#tcpsock:setkeepalive ?

**Comment by thibaultCha** [comment]
Yeah

**Comment by thefosk** [comment]
This can be mitigated by having a larger connection pool: http://wiki.nginx.org/HttpLuaModule#lua_socket_pool_size
