### ISSUE TITLE
How to integrate API Gateway to legacy app

### ISSUE THREAD

**Issue by istvano** [Mashape/kong#1702]
### Summary

I need some help on how I can integrate Kong into my technology landscpe

### Steps To Reproduce

1. I have a legacy application
2. I have a new REST API
3. I am about to develop a SPA App 

I need to do SSO

What is the best way to integrate Kong with an SSO product like Gluu or WSO2 Identity ?

Thanks for any ideas.

**Comment by thibaultcha** [comment]
Hi, 

Such broad questions would be a better fit for for the mailing list, rather than the GH issues which we would prefer to be related to actual issues/feature discussions about Kong itself. 

Thanks

**Comment by thefosk** [comment]
> What is the best way to integrate Kong with an SSO product like Gluu or WSO2 Identity ?

This will be possible once we support OpenID Connect (#522).

**Comment by istvano** [comment]
thanks
