### ISSUE TITLE
Calling another plugin from my plugin

### ISSUE THREAD

**Issue by elruwen** [Mashape/kong#1707]
Hi!

Is there any issue with me calling another plugin?

I want to offer multiple authentication methods and I would simply parse the auth header and would delegate to the correct plugin.

Cheers
Ruwen

**Comment by Tieske** [comment]
Well, first thought is that it probably can be done. Lua is a dynamic language that probably allows you to craft some code and data structures to do this.

That said; I'd expect the result to be rather brittle, as a change in any of the underlying plugins could break yours.

**Comment by thibaultcha** [comment]
I would not recommend unless you really know what you are doing. Considering this answered so closing this.
