### ISSUE TITLE
Plugin migrations not run when in a different path

### ISSUE THREAD

**Issue by ronan-skyscanner** [Mashape/kong#1708]
### Summary
Plugin migrations are not running when the plugins are in a folder outside the Kong core folders.
This seems to be because the lua path which is set up in the Nginx config has not been set up for Kong to run the migrations.

### Steps To Reproduce

1. Create a plugin with migrations in /opt/kong/plugins
2. Add `/opt/?.lua` to the lua_package_path directive in kong.yml/nginx.conf
3. Add the plugin to one or all APIs
4. do `kong migrations list` to show that the plugin migration has not been run.

### Additional Details & Logs

- Kong version: 0.8.3
- Kong error logs: No errors reported because Kong just assumes the plugin has no migrations
- Operating System: RedHat EL7

**Comment by thibaultcha** [comment]
Hi,

Would you try with 0.9? The migrations should be ran from inside Nginx with it.

**Comment by ronan-skyscanner** [comment]
Indeed it works in 0.9.2! 
Thanks
