### ISSUE TITLE
Angular2 + Kong 0.9.2 (Request problem)

### ISSUE THREAD

**Issue by geazioliveira** [Mashape/kong#1712]
Hello,

I'm developing an application in AngularJS 2 and am finding a problem using Kong. The problem is the following when I do one request for my application angle in the few moments kong does not send the content-length response and then generates an error ...

I can see the error because I made the same request without using the kong and did not have the problem.

I wonder if anyone ever had something like and how can I fix it.

Recalling that the version I'm using is 0.9.2

**Comment by thefosk** [comment]
Does the final API return the `Content-Length` header?

**Comment by geazioliveira** [comment]
Yes man... the API return de Content-Length header.

**Comment by thefosk** [comment]
Do you see the same problem happening from a different client (ie, curl) going through Kong? Very hard to debug and reproduce this since I don't have access to the final upstream API.

**Comment by thibaultcha** [comment]
Closing this from lack of update. Feel free to reopen.
