### ISSUE TITLE
"math.randomseed() must be called in init_worker" errior when using lua_cache=off in Docker

### ISSUE THREAD

**Issue by ronan-skyscanner** [Mashape/kong#1716]
### Summary
As discussed in the gitter channel, I have been receiving this error for any requests to the adminn_api (8001) server, in Docker, using Kong 0.9.2:
"math.randomseed() must be called in init_worker"

After investigation it turned out to be related to the `lua_cache` directive being set to `off`.

A workaround for the issue is to comment out line 22 (raising the error) in the `kong/core/globalpatches.lua` file.

### Steps To Reproduce

1. Using the docker-kong project, build a new image with the Dockerfile
2. Add the directive lua_cache=off to the kong.conf file
3. Link your local kong.conf to the instance's (in /etc/kong/) when running the container 
4. Start the container and open error logs (/usr/local/kong/logs/error.log)
5. Attempt to load http://localhost:8001/apis
6. Kong responds with a 500 and the logs show the error above.

### Additional Details & Logs

- Kong version 0.9.2
- Kong configuration has lua_cache=off
- Operating System Docker / docker-kong / Centos 7

**Comment by thibaultcha** [comment]
Fixed by #1717, thanks.
