### ISSUE TITLE
Changes to rate-limiting plugin configuration format (`fault_tolerant`, was `continue_on_error`)

### ISSUE THREAD

**Issue by DonMartin76** [Mashape/kong#1718]
Hello,

While doing migration tests to switch from 0.8.3 to Kong 0.9.2 for our wicked.haufe.io API Management System, I just realized the configuration options for the rate-limiting plugin had changed, e.g. the `config.async` was removed and `config.continue_on_error` options has (sort of) been renamed to `config.fault_tolerant`.

I suppose this is something you update in `kong migrations`, but that requires that Kong is long-running and is never re-created from scratch (in the phoenix deployment sense), or, alternatively, that the configuration JSON has to be updated.

My actual issue perhaps just boils down to: Is this something you think will be happening often, or was this a one-off? I realize you mentioned it in the detailed change-log, but had missed that (obviously).

Best regards,
Martin

**Comment by thefosk** [comment]
This was a one-off for the rate-limiting and response rate-limiting plugins. As we are approaching 1.0 we are making some changes that make more sense in the long-term.

**Comment by DonMartin76** [comment]
OK, so as of 1.0.0 you will go for to semantic versioning? If that's the case, I'll just have to pay more attention to your change logs... ;)

**Comment by thefosk** [comment]
I highly reccomend to carefully review both the [CHANGELOG](https://github.com/Mashape/kong/blob/master/CHANGELOG.md) and the [UPGRADE](https://github.com/Mashape/kong/blob/master/UPGRADE.md) path on every release.

> OK, so as of 1.0.0 you will go for to semantic versioning?

We will brainstorm on this once we get closer to 1.0.
