### ISSUE TITLE
Deleting a global rate-limiting plugin does not remove the rate-limit

### ISSUE THREAD

**Issue by williamhorstkamp** [Mashape/kong#1721]
### Summary

When deleting an enabled global rate-limiting plugin from kong, the rate-limits imposed on the APIs will continue to be in effect.

### Steps To Reproduce

1. Post to `/plugins` to enable `rate-limiting` globally with at least one limit in place
2. Delete to `/plugins/{plugin-id}` to delete the previous global rate-limiter
3. Hit any endpoint that kong is managing
4. Check headers to see rate-limiting headers are still there.

### Current Work-Around

1. Post to `/plugins` to enable `rate-limiting` globally with at least one limit in place
2. Put to `/plugins/{plugin-id}` to set `enabled` to false
3. Delete to `/plugins/{plugin-id}` to delete the previous global rate-limiter
4. Hit any endpoint that kong is managing
5. Check headers to see rate-limiting headers are no longer there

### Additional Details & Logs

- Kong version 0.9.1
- Using Cassandra with repl factor of 2

**Comment by thefosk** [comment]
Do you see any errors in `error.log` when deleting the plugin?
