### ISSUE TITLE
Unable to apply Runscope plugin to consumer

### ISSUE THREAD

**Issue by chris-hailstorm** [Mashape/kong#1722]
### Summary

Runscope plugin can be attached to API, but cannot be attached to a consumer.  The plugin doco says that consumer scope is available, although no consumer example given.

### Steps To Reproduce

1.  Create an API, a consumer, and a Runscope bucket key & token per the Kong doco

2.  Verify the consumer exists:
`$ curl -X GET http://localhost:9003/consumers/happy_stage
{"username":"happy_stage","created_at":1475778290000,"id":"25462da2-XXXX-XXXX-XXXX-XXXXXXXXXXXX"}`

3.  Try to apply the Runscope plugin to the consumer:
`$ curl -X POST http://localhost:9003/consumers/happy_stage/plugins/ --data "name=runscope" --data "config.bucket_key=gm9aXXXXXXXX" --data "config.access_token=8f06347c-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
{"message":"Not found"}

Try the same using consumer ID instead of name -- same result

4. Try to apply the Runscope plugin to the global API
`$ curl -X POST http://localhost:9003/plugins/ --data "name=runscope" --data "config.bucket_key=gm9aXXXXXXXX"     --data "config.access_token=8f06347c-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
{"id":"cecb1acb-XXXX-XXXX-XXXX-XXXXXXXXXXXX","created_at":1475866668000,"enabled":true,"name":"runscope","config":{"access_token":"8f06347c-XXXX-XXXX-XXXX-XXXXXXXXXXXX","api_endpoint":"https:\/\/api.runscope.com","keepalive":30,"timeout":10000,"bucket_key":"gm9aXXXXXXXX"}}`

### Additional Details & Logs

- Kong version (`$ kong version`) -- 0.9.1

**Comment by thefosk** [comment]
@chris-hailstorm to apply the plugin to a specific consumer, you need to execute the request to `http://localhost:9003/plugins/` passing a parameter called `consumer_id`.

**Comment by chris-hailstorm** [comment]
Confirmed.  Thanks.
