### ISSUE TITLE
Connect to non-zero Redis databases

### ISSUE THREAD

**Issue by logronoide** [Mashape/kong#1726]
### Summary

Some plugins (request/response rate limits) can use Redis as an external fast persistent storage. To connect to Redis, the parameters are host, port and password (optional). It's not possible to select a non-zero database in Redis. As result, it's not possible to share an existing Redis deployment if the zero database is already in use. 

I suggest to add a new parameter with the cardinal of the database in Redis, being zero by default. The resyt-redis author suggest to implement this feature as follows: https://github.com/openresty/lua-resty-redis/issues/53
### Steps To Reproduce
1. Configure a rate-limiting plugin to connect to an existing Redis database with zero database in use.
2. Both data sets will be stored in the same database.
3. There is a chance of data corruption.

**Comment by thibaultcha** [comment]
I can see the value in this indeed. We'd need a new configuration field in the plugin configuration I believe, and as mentioned: select a different database on first connection, and use a different connection pool for each database.

**Comment by flypenguin** [comment]
just to be sure - it is supported in Kong 0.9.9, and not yet [in the documentation](https://getkong.org/plugins/response-rate-limiting/), right?

and the field in the config is `config.redis_database`, right?

please clarify :)

**Comment by thefosk** [comment]
It's supported in 0.10 (you can play with the RC) but not in 0.9.x
