### ISSUE TITLE
429s written to statsd as 400s

### ISSUE THREAD

**Issue by bivdub** [Mashape/kong#1734]
Whenever the rate-limiting plugin is tripped, the user receives a 429 response, but by the time the Statsd plugin is run, the error code is logged as a 400. Is there a way to carry this 429 status over until the statsd plugin runs?

**Comment by shashiranjan84** [comment]
@bivdub before I start debugging this, did you notice where status code 429 getting updated to 400?

**Comment by p0pr0ck5** [comment]
@bivdub any update for us so we can debug this?

**Comment by p0pr0ck5** [comment]
Closing as stale. Please reopen if necessary.
