### ISSUE TITLE
Rate limiting on OAuth2 web application level (not end consumer) - How?

### ISSUE THREAD

**Issue by DonMartin76** [Mashape/kong#1740]
When configuration the `rate-limiting` plugin for an API, I currently have two options of doing it: Either for the entire API, or for a specific consumer (by specifying `consumer_id` when creating the plugin for the API).

When dealing with OAuth2 APIs using the Authorization Code Grant or Implicit Grant, things are a little more complicated though. Let's look at the implicit grant: There I have a web application (which has some kind of `client_id` to tell me who it is), and when I have authenticated and authorized the user (using my custom code), I will create a Kong Consumer with a registered OAuth2 application and issue a token (using the `/oauth2/authorize` Kong end point).

Now, if I want rate-limiting on this consumer, I add that using the method above (using `consumer_id`), and that's fine. But how would I go about rate limiting all consumers of this API for a specific web application? Given that I might have more than one web application which uses the same API?

Have I turned wrong in my thinking here somewhere, or is this nothing you would do? My use case is e.g. billed APIs on a per-web-app-basis, where I want to make sure each web app gets its "share" of the API, disregarding the amount of actual end users using it.

Would I solve this in a different way, granted I want to use the Implicit Grant Flow?

/Martin

**Comment by mleace** [comment]
I don't think I fully understand what you're trying to achieve, but the logic is that your consumer is the **web application**, not the end user (OAuth2 credentials - client_id, client_secret - are bound to application/API consumer, not to end user). When you set rate-limiting plugin to that application consumer, you actually limit usage of the API for all users of the application.

**Comment by DonMartin76** [comment]
Hm. I guess you could do it like that, but I actually *want* the consumer to be the end user, as I need his identity after the API call has gone through the gateway.

I want to achieve this:

* For each call to the API (which is a Web App API used from Angular 2), I want Kong to add the end user's identity (this I can make work)
* I want (to be able) to do rate limiting over all traffic from a specific Web App (this I have not managed/I don't know how to do)

To get it the other way around would be quite trivial (rate limiting per consuming web app via registering a single consumer per web app), but then I lose the end user's authenticated identity. Or where's my problem in thinking here?

**Comment by mleace** [comment]
There are actually 2 identities bound to Bearer token when using either code grant or implicit grant:

1. consumer identity (usually meaning API consumer, e.g. web app) - identified by client_id & client_secret. This is passed from Kong to upstream as header `X-Consumer-ID` (and `X-Consumer-Username` / `X-Consumer-Custom-ID` if set)

1.  end user identity (if you set your authentication accordingly), which is bind with token by calling /authorize Kong endpoint and is passed to upstream as `X-Authenticated-Userid` header.

Have a look at [OAuth2 plugin documentation](https://getkong.org/plugins/oauth2-authentication/), which describes the OAuth2 code grant flow.

**Comment by DonMartin76** [comment]
OK, thanks for clarifying this. Makes sense in a sense, but gives me a headache with something else. I would still like to be able to get both kinds of rate limiting. Both on a particular end user and on all users of a specific consumer (if you implement it the way you describe it).

I will have to go back to the drawing board a little for this one; if I do it the way I described it, I can pass along more information based on the access token (like licensing information in custom headers), otherwise I'd have to get that information from a different service in my backend.

Keep cake, eat it, keep cake, eat it,... grbmbmbgmrl.

**Comment by DonMartin76** [comment]
See also #1759.

**Comment by DonMartin76** [comment]
I don't quite know how I could miss that, but this is `config.limit_by=credential`.
