### ISSUE TITLE
A required package for installing Kong on Ubuntu is undocumented

### ISSUE THREAD

**Issue by erutherford** [Mashape/kong#1741]
### Summary
This requirement isn't listed in the documentation, so I'm not sure if this was intentional.  I'd prefer if it weren't required since it would make it much easier to use this package when creating a docker container.  If sudo is actually needed a recommended package can be used instead like [gosu](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/user).  If the requirement is going to be left in place the [documentation](https://getkong.org/install/ubuntu/#installation) should be updated.

### Steps To Reproduce

1. Download the .deb package
2. Attempt to install it without the sudo package installed

### Additional Details & Logs

- Kong version (`0.9.3`)
- Kong error logs 
```
Selecting previously unselected package kong.
(Reading database ... 9941 files and directories currently installed.)
Preparing to unpack kong-0.9.3.deb ...
Unpacking kong (0.9.3) ...
dpkg: dependency problems prevent configuration of kong:
 kong depends on sudo; however:
  Package sudo is not installed.

dpkg: error processing package kong (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 kong
```
- Operating System `Ubuntu Xenial`

**Comment by thefosk** [comment]
This could be a legacy dependency - let me double check.

**Comment by thefosk** [comment]
I have updated the distributions for 0.9.3 - can you please download it again?

**Comment by erutherford** [comment]
@thefosk, it looks like that did the trick.  Thank you for the quick turn around, I appreciate it.
