### ISSUE TITLE
Kong doesn't seem to be stopping when its started using the -c and --nginx-conf option on CentOS 6.8

### ISSUE THREAD

**Issue by kkindaface** [Mashape/kong#1743]
### Summary

On CentOS 6.8: (Stop doesn't work)

WORKS: kong start -c /home/test/kong.conf --nginx-conf /home/test/nginx-conf.template
DOESN'T WORK: kong stop

On Mac OSX 10.11.6: (Start and Stop work)

WORKS: kong start -c /home/test/kong.conf --nginx-conf /home/test/nginx-conf.template
WORKS: kong stop

- Kong version : 0.9.3
- Kong debug-level startup logs (On CentOS)

2016/10/13 10:39:03 [verbose] Kong: 0.9.3
2016/10/13 10:39:03 [debug] ngx_lua: 10005
2016/10/13 10:39:03 [debug] nginx: 1009015
2016/10/13 10:39:03 [debug] Lua: LuaJIT 2.1.0-beta2
2016/10/13 10:39:03 [verbose] no config file found at /etc/kong.conf
2016/10/13 10:39:03 [verbose] no config file found at /etc/kong/kong.conf
2016/10/13 10:39:03 [verbose] reading config file at /home/test/apikong/configs/kong.conf
2016/10/13 10:39:03 [debug] admin_listen = "0.0.0.0:8001"
2016/10/13 10:39:03 [debug] anonymous_reports = false
2016/10/13 10:39:03 [debug] cassandra_consistency = "ONE"
2016/10/13 10:39:03 [debug] cassandra_contact_points = {"127.0.0.1"}
2016/10/13 10:39:03 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2016/10/13 10:39:03 [debug] cassandra_keyspace = "kong"
2016/10/13 10:39:03 [debug] cassandra_port = 9042
2016/10/13 10:39:03 [debug] cassandra_repl_factor = 1
2016/10/13 10:39:03 [debug] cassandra_repl_strategy = "SimpleStrategy"
2016/10/13 10:39:03 [debug] cassandra_ssl = false
2016/10/13 10:39:03 [debug] cassandra_ssl_verify = false
2016/10/13 10:39:03 [debug] cassandra_timeout = 5000
2016/10/13 10:39:03 [debug] cassandra_username = "kong"
2016/10/13 10:39:03 [debug] cluster_listen = "0.0.0.0:7946"
2016/10/13 10:39:03 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2016/10/13 10:39:03 [debug] cluster_profile = "wan"
2016/10/13 10:39:03 [debug] cluster_ttl_on_failure = 3600
2016/10/13 10:39:03 [debug] custom_plugins = {}
2016/10/13 10:39:03 [debug] database = "postgres"
2016/10/13 10:39:03 [debug] dns_resolver = "10.250.1.12"
2016/10/13 10:39:03 [debug] dnsmasq = false
2016/10/13 10:39:03 [debug] dnsmasq_port = 8053
2016/10/13 10:39:03 [debug] log_level = "notice"
2016/10/13 10:39:03 [debug] lua_code_cache = "on"
2016/10/13 10:39:03 [debug] lua_package_cpath = ""
2016/10/13 10:39:03 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2016/10/13 10:39:03 [debug] lua_ssl_verify_depth = 1
2016/10/13 10:39:03 [debug] mem_cache_size = "128m"
2016/10/13 10:39:03 [debug] nginx_daemon = "on"
2016/10/13 10:39:03 [debug] nginx_optimizations = true
2016/10/13 10:39:03 [debug] nginx_worker_processes = "auto"
2016/10/13 10:39:03 [debug] pg_database = "kong"
2016/10/13 10:39:03 [debug] pg_host = "apidev02.testcorporation.local"
2016/10/13 10:39:03 [debug] pg_password = "******"
2016/10/13 10:39:03 [debug] pg_port = 5432
2016/10/13 10:39:03 [debug] pg_ssl = false
2016/10/13 10:39:03 [debug] pg_ssl_verify = false
2016/10/13 10:39:03 [debug] pg_user = "kong"
2016/10/13 10:39:03 [debug] prefix = "/home/test/apikong/apps"
2016/10/13 10:39:03 [debug] proxy_listen = "0.0.0.0:8000"
2016/10/13 10:39:03 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2016/10/13 10:39:03 [debug] serf_path = "serf"
2016/10/13 10:39:03 [debug] ssl = true
2016/10/13 10:39:03 [verbose] prefix in use: /home/test/apikong/apps
2016/10/13 10:39:03 [verbose] preparing nginx prefix directory at /home/test/apikong/apps
2016/10/13 10:39:03 [verbose] saving serf identifier to /home/test/apikong/apps/serf/serf.id
2016/10/13 10:39:03 [debug] searching for OpenResty 'resty' executable
2016/10/13 10:39:03 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.9.15.1'
2016/10/13 10:39:03 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2016/10/13 10:39:03 [verbose] saving serf shell script handler to /home/test/apikong/apps/serf/serf_event.sh
2016/10/13 10:39:03 [verbose] SSL enabled, no custom certificate set: using default certificate
2016/10/13 10:39:03 [verbose] default SSL certificate found at /home/test/apikong/apps/ssl/kong-default.crt
2016/10/13 10:39:03 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
2016/10/13 10:39:03 [verbose] running datastore migrations
2016/10/13 10:39:03 [verbose] migrations up to date
2016/10/13 10:39:03 [verbose] serf agent not running, deleting /home/test/apikong/apps/pids/serf.pid
2016/10/13 10:39:03 [debug] checking 'serf' executable from 'serf_path' config setting
2016/10/13 10:39:03 [debug] serf version: 'Serf v0.7.0'
2016/10/13 10:39:03 [debug] starting serf agent: nohup serf agent -profile 'wan' -rpc-addr '127.0.0.1:7373' -event-handler 'member-join,member-leave,member-failed,member-update,member-reap,user:kong=/home/test/apikong/apps/serf/serf_event.sh' -bind '0.0.0.0:7946' -node 'uservm01_0.0.0.0:7946_465a78ad93cc432ea8369824d49506d6' -log-level 'err' > /home/test/apikong/apps/logs/serf.log 2>&1 & echo $! > /home/test/apikong/apps/pids/serf.pid
2016/10/13 10:39:03 [verbose] waiting for serf agent to be running
2016/10/13 10:39:03 [debug] sending signal to pid at: /home/test/apikong/apps/pids/serf.pid
2016/10/13 10:39:03 [debug] kill -0 `cat /home/test/apikong/apps/pids/serf.pid` >/dev/null 2>&1
2016/10/13 10:39:03 [verbose] serf agent started
2016/10/13 10:39:03 [verbose] auto-joining serf cluster
2016/10/13 10:39:03 [verbose] successfully joined cluster at 10.250.50.96:7946
2016/10/13 10:39:03 [verbose] registering serf node in datastore
2016/10/13 10:39:03 [verbose] cluster joined and node registered in datastore
2016/10/13 10:39:03 [debug] searching for OpenResty 'nginx' executable
2016/10/13 10:39:03 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.9.15.1'
2016/10/13 10:39:03 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2016/10/13 10:39:03 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /home/test/apikong/apps -c nginx.conf
2016/10/13 10:39:03 [debug] nginx started
2016/10/13 10:39:03 [info] Kong started

- Kong debug-level shutdown logs (On CentOS)

2016/10/13 10:43:08 [verbose] Kong: 0.9.3
2016/10/13 10:43:08 [debug] ngx_lua: 10005
2016/10/13 10:43:08 [debug] nginx: 1009015
2016/10/13 10:43:08 [debug] Lua: LuaJIT 2.1.0-beta2
2016/10/13 10:43:08 [verbose] no config file found at /etc/kong.conf
2016/10/13 10:43:08 [verbose] no config file found at /etc/kong/kong.conf
2016/10/13 10:43:08 [verbose] reading config file at /usr/local/kong/kong.conf
2016/10/13 10:43:08 [debug] admin_listen = "0.0.0.0:8001"
2016/10/13 10:43:08 [debug] anonymous_reports = true
2016/10/13 10:43:08 [debug] cassandra_consistency = "ONE"
2016/10/13 10:43:08 [debug] cassandra_contact_points = {"127.0.0.1"}
2016/10/13 10:43:08 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2016/10/13 10:43:08 [debug] cassandra_keyspace = "kong"
2016/10/13 10:43:08 [debug] cassandra_port = 9042
2016/10/13 10:43:08 [debug] cassandra_repl_factor = 1
2016/10/13 10:43:08 [debug] cassandra_repl_strategy = "SimpleStrategy"
2016/10/13 10:43:08 [debug] cassandra_ssl = false
2016/10/13 10:43:08 [debug] cassandra_ssl_verify = false
2016/10/13 10:43:08 [debug] cassandra_timeout = 5000
2016/10/13 10:43:08 [debug] cassandra_username = "kong"
2016/10/13 10:43:08 [debug] cluster_listen = "0.0.0.0:7946"
2016/10/13 10:43:08 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2016/10/13 10:43:08 [debug] cluster_profile = "wan"
2016/10/13 10:43:08 [debug] cluster_ttl_on_failure = 3600
2016/10/13 10:43:08 [debug] custom_plugins = {}
2016/10/13 10:43:08 [debug] database = "postgres"
2016/10/13 10:43:08 [debug] dnsmasq = true
2016/10/13 10:43:08 [debug] dnsmasq_port = 8053
2016/10/13 10:43:08 [debug] log_level = "notice"
2016/10/13 10:43:08 [debug] lua_code_cache = "on"
2016/10/13 10:43:08 [debug] lua_package_cpath = ""
2016/10/13 10:43:08 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2016/10/13 10:43:08 [debug] lua_ssl_verify_depth = 1
2016/10/13 10:43:08 [debug] mem_cache_size = "128m"
2016/10/13 10:43:08 [debug] nginx_daemon = "on"
2016/10/13 10:43:08 [debug] nginx_optimizations = true
2016/10/13 10:43:08 [debug] nginx_worker_processes = "auto"
2016/10/13 10:43:08 [debug] pg_database = "kong"
2016/10/13 10:43:08 [debug] pg_host = "127.0.0.1"
2016/10/13 10:43:08 [debug] pg_port = 5432
2016/10/13 10:43:08 [debug] pg_ssl = false
2016/10/13 10:43:08 [debug] pg_ssl_verify = false
2016/10/13 10:43:08 [debug] pg_user = "kong"
2016/10/13 10:43:08 [debug] prefix = "/usr/local/kong"
2016/10/13 10:43:08 [debug] proxy_listen = "0.0.0.0:8000"
2016/10/13 10:43:08 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2016/10/13 10:43:08 [debug] serf_path = "serf"
2016/10/13 10:43:08 [debug] ssl = true
2016/10/13 10:43:08 [debug] ssl_cert = "/usr/local/kong/ssl/kong-default.crt"
2016/10/13 10:43:08 [debug] ssl_cert_key = "/usr/local/kong/ssl/kong-default.key"
2016/10/13 10:43:08 [verbose] prefix in use: /usr/local/kong
Error: 
/usr/local/share/lua/5.1/kong/cmd/stop.lua:21: nginx not running in prefix: /usr/local/kong
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/stop.lua:21: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:85: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:85>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:85: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:42>
	/usr/local/bin/kong:11: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'pcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>

**Comment by kkindaface** [comment]
Here is what Kong thinks is the config file while starting and stopping on CentOS

Start : 2016/10/13 10:39:03 [verbose] reading config file at /home/test/apikong/configs/kong.conf

Stop: 2016/10/13 10:43:08 [verbose] reading config file at /usr/local/kong/kong.conf

**Comment by thibaultcha** [comment]
Hi,

Any chance we could see the template you are using? What I can tell you right now which I suspect is what is happening, is that the template *must* be configured so that the Nginx pid is stored in `pids/nginx.pid` (with the `pid` directive). See the original template:

https://github.com/Mashape/kong/blob/master/kong/templates/nginx.lua#L5

That is because `pids/` is holding Serf, dnsmasq and the nginx pid, as per:

https://github.com/Mashape/kong/blob/master/kong/conf_loader.lua#L25

We're aware that this is kinda annoying though. It is said in the example template on [the CLI docs](https://getkong.org/docs/0.9.x/configuration/#custom-nginx-configuration) that this mandatory but that is barely noticeable, I agree.

The issue might be something else altogether, of course. In that case, if we could see the template then that would help.

**Comment by kkindaface** [comment]
Sorry, I should have mentioned. At this point I have not made any custom edits to my nginx template. I straight away took what was inside the default nginx-kong.conf and added the additional nginx.conf contents and created nginx-test.template. and it has the pids/ entry in there. I have attached the file just in case.
[nginx-test.template.zip](https://github.com/Mashape/kong/files/530096/nginx-test.template.zip)

The Start and Stop script seem to be looking at different kong.conf files (my previous comment)

**Comment by thibaultcha** [comment]
Notice this line in the starting logs:
```
2016/10/13 10:39:03 [verbose] prefix in use: /home/test/apikong/apps
```

And this one in the stop logs:
```
2016/10/13 10:43:08 [verbose] prefix in use: /usr/local/kong
```

Somehow you are specifying a different prefix path for `kong start` (probably from the configuration file). I just started and stopped Kong using your nginx config template without issues.

**Comment by kkindaface** [comment]
On Mac OSX it works like you said.

On CentOS 6.8 I see the issue, same files. Strange. I will try again just to confirm.

**Comment by thibaultcha** [comment]
`/home/test/apikong/apps` is coming from your settings, we obviously do not provide such a setting. Check your environment variable as well, you might have `KONG_PREFIX` set on the machine on which you are experiencing this.

**Comment by kkindaface** [comment]
Yes I set that in kong.conf. So how to I make 'kong stop' work?

**Comment by thibaultcha** [comment]
From:
```
Usage: kong stop [OPTIONS]

Stop a running Kong node (Nginx and other configured services) in given
prefix directory.

This command sends a SIGTERM signal to Nginx.

Options:
 -p,--prefix (optional string) prefix Kong is running at
 --v         verbose
 --vv        debug
```

You can either use:
```
kong stop --prefix /home/test/apikong/apps
```

Or:
```
KONG_PREFIX=/home/test/apikong/apps kong stop
```

**Comment by kkindaface** [comment]
ahh now i see.....I tried kong stop with -c and it failed and so I assumed 'kong stop' probably is now looking at the config file it was started with. Did not pay attention to the '-prefix' option. my mistake. It works with the -prefix option. Thanks!

**Comment by kkindaface** [comment]
To close the loop. The reason it works on Mac was that the prefix was not set on Mac in the kong.conf file.
