### ISSUE TITLE
Pass custom PostgresDB Password to Kong

### ISSUE THREAD

**Issue by saithala** [Mashape/kong#1746]
### Summary

When I start Postgres DB with a custom password.using docker, I used POSTGRES_USER=kong and POSTGRES_PASSWORD=kong as environment variables. Now how do I pass that custom password to Kong? If I use KONG_POSTGRES_USER=kong and KONG_POSTGRES_PASSWORD=kong
kong wont start and throws an error /usr/local/share/lua/5.1/pgmoon-mashape/init.lua:239: missing password, required for connect. Whats the correct ENV to pass the Postgres user name and password to Kong?

cc: @thefosk @Tieske

**Comment by thibaultcha** [comment]
`KONG_PG_PASSWORD` is the name of the environment variable you want to use. Same for the user: `KONG_PG_USER`.

See the settings in the config file:

https://github.com/Mashape/kong/blob/master/kong.conf.default#L111-L112

And the explanation on ENV variable in the same file:

https://github.com/Mashape/kong/blob/master/kong.conf.default#L10-L11

**Comment by akhy** [comment]
It's missing in docker install docs (https://getkong.org/install/docker/)

also worth noting that the following vars also available for configuration:

- KONG_PG_DATABASE
- KONG_PG_PASSWORD
- KONG_PG_USER

**Comment by thefosk** [comment]
Every configuration parameter in the Kong configuration file can be configured with environment variables by prefixing the parameter name with `KONG_` and everything uppercase. Ie, the `log_level` parameter can be set with `KONG_LOG_LEVEL=...`, same for every other property.
