### ISSUE TITLE
request_host AND|OR request_path 

### ISSUE THREAD

**Issue by JayCeeJr** [Mashape/kong#1750]
### Summary

It appears if you define a request_host and request_path, the api will forward for either condition. We would like to require both conditions.
### Example

I would like to allow access to this path with this hostname:
curl -i -X POST \
--url http://host1:8001/apis/ \
--data 'name=api1' \
--data 'upstream_url=http://backend:8765/' \
--data 'request_host=api-qa'
--data 'request_path=/api/thingone'

But not allow others, however since the hostname matches and it gets passed right through.
curl -i GET http://api-qa/api/thingtwo

Version: 0.9.3
OS: CentOS 7.2

**Comment by thibaultcha** [comment]
Such a feature is requested multiple times already and is planned for 0.10 by the end of this month.

**Comment by JayCeeJr** [comment]
That would be awesome, thanks for the quick reply.

**Comment by thibaultcha** [comment]
The plan is to also allow for routing by arbitrary header, and to make the router extensible to allow future implementations of regex matching too.

**Comment by HenryChelsea** [comment]
@thibaultcha  When will 0.10 release? Thanks for your good job!

**Comment by thefosk** [comment]
RC has been released. expect stable soon.
