### ISSUE TITLE
Kong nodes can't find each other and join cluster

### ISSUE THREAD

**Issue by PGBI** [Mashape/kong#1751]
### Summary

When spinning up 2 Kong instances, they do not join the cluster. 

Here are the symptoms:
- they can ping each other, First node IP is 10.200.25.25, second one is 10.200.4.216. Firewall is wide opened on both nodes. Cluster configuration on kong.conf is using the default values.
- both nodes are instantiated at the same time, on aws. They are behind a load balancer.
- they have access to the same datastore, postgres. When I query postgres (`SELECT * FROM nodes`) I always get one line:

| name | cluster_listening_address | created_at |
| ------------- | ------------- | -------------- |
| ip-10-200-7-52_0.0.0.0:7946_465a78ad93cc432ea8369824d49506d6  | 10.200.25.25:7946  | 2016-10-18 21:16:04  |

 - if I restart kong on 10.200.4.216 an re-query postgres, I get:

| name | cluster_listening_address | created_at |
| ------------- | ------------- | -------------- |
| ip-10-200-7-52_0.0.0.0:7946_465a78ad93cc432ea8369824d49506d6  | 10.200.4.216:7946  | 2016-10-18 21:16:04  |

So I believe the problem is that **the two nodes have the same name**. When digging into the code, I understand its their serf.id right?

`cat /usr/local/kong/serf/serf.id` outputs the same serf.id on both Kong nodes.

### Additional Details & Logs

- Kong version: 0.9.3
- Operating System: Ubuntu Trusty

**Comment by thefosk** [comment]
@thibaultcha was already debugging this problem and I think he has a fix in mind - we will publish 0.9.4 as soon as we confirm the fix works.

**Comment by thibaultcha** [comment]
Yes, there is such a fix which will be made available soon in the form of a PR.

**Comment by PGBI** [comment]
Yes, we are on AWS. Also, I realize we are actually spinning up our kong instances from an AMI image were Kong had already be started once. So no matter how good your random UUID generator is, in our specific case, I guess we'll encounter this issue even with 0.9.4.

Our deployment process can be improved on our side obviously. But you may want to consider regenerating this `/usr/local/kong/serf/serf.id` on each `kong start`?

**Comment by thibaultcha** [comment]
@PGBI,

I just pushed a hotfix to #1754 which should be applicable to `0.9.x`. We really want some feedback on it and making sure it works for other production deployments than the ones its been tested on. Do you think you'd be able to apply the provided patch and see if those go away?

Note: a behavior we saw in a production deployment is that forked VMs provide the same random bytes from `/dev/urandom` (from which OpenSSL gets its PRNG seed), since their entropy is too similar. We strongly suggest that if this is your case as well, you increase your cloned VMs entropy before starting Kong.

Much appreciated!

**Comment by PGBI** [comment]
@thibaultcha in our deployment script we fetch Kong package at https://github.com/Mashape/kong/releases/download/$KONG_VERSION/kong-$KONG_VERSION.trusty_all.deb

Would you mind building a package from your hotfix branch, and make it available at, let's say `https://github.com/Mashape/kong/releases/download/0.9.4-beta/kong-0.9.4-beta.trusty_all.deb`? This way we'll be able to test your hotfix in "real conditions" with our usual deployment script and let you know how it worked.

**Comment by thibaultcha** [comment]
@thefosk

**Comment by thefosk** [comment]
@PGBI here you go: https://cl.ly/1X0T3S3m3Z2p/kong-0.9.3hotfixurandomseed.trusty_all.deb

**Comment by thibaultcha** [comment]
@PGBI Any updates?

**Comment by PGBI** [comment]
Sorry, our provisioning script is totally messed up. So it's failing, but not because of your hotfix. We'll give it an other try tmo and let you guys know.

**Comment by PGBI** [comment]
Ok so we tried it, it still doesn't work with the provided package.

Our provisioning script first launch an ec2 instance, download kong package and starts it. Its IP was 10.200.5.139
```
cat /usr/local/kong/serf/serf.id
ip-10-200-5-139_0.0.0.0:7946_dd719e50bc2b44b28ff99e3f518eb4cd
```

Then a snapshot is taken from this first node, and an other one is created out of it. Its IP was 10.200.7.234. 
```
cat /usr/local/kong/serf/serf.id
ip-10-200-5-139_0.0.0.0:7946_dd719e50bc2b44b28ff99e3f518eb4cd
```
You can see its serf.id is still identical as the "mother node".

Here is the output of the kong start command in the second node:
```
...
2016/10/25 16:53:20 [verbose] serf agent not running, deleting /usr/local/kong/pids/serf.pid
2016/10/25 16:53:20 [debug] checking 'serf' executable from 'serf_path' config setting
2016/10/25 16:53:20 [debug] serf version: 'Serf v0.7.0'
2016/10/25 16:53:20 [debug] starting serf agent: nohup serf agent -profile 'wan' -rpc-addr '127.0.0.1:7373' -event-handler 'member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf/serf_event.sh' -bind '0.0.0.0:7946' -node 'ip-10-200-5-139_0.0.0.0:7946_dd719e50bc2b44b28ff99e3f518eb4cd' -log-level 'err' > /usr/local/kong/logs/serf.log 2>&1 & echo $! > /usr/local/kong/pids/serf.pid
2016/10/25 16:53:20 [verbose] waiting for serf agent to be running
2016/10/25 16:53:20 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2016/10/25 16:53:20 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2016/10/25 16:53:20 [verbose] serf agent started
2016/10/25 16:53:20 [verbose] auto-joining serf cluster
2016/10/25 16:53:20 [verbose] no other nodes found in the cluster
...
```

**Comment by thefosk** [comment]
@PGBI to better understand: if you start a new brand new node, and then you start another brand new node, the two `serf.id` values are identical?

Not sure if you are trying to replicate on an existing setup or not - just in case can you try to replicate this problem from scratch with two completely new nodes? (Maybe you are already doing this, not sure).

**Comment by PGBI** [comment]
@thefosk Nope. Our deployment process is as follow:

1. instantiate node 1: download last Kong package + dependencies, run migrations, start kong.
2. take snapshot of node 1.
3. add node 1 to load balancer - tear down previous kong node(s)
4. create node 2 from snapshot of node 1 - restart kong on node 2
5. add node 2 to load balancer
6. if heavy load, create node 3 from snapshot of node 1 - restart kong on node 3
7. add node 3 to load balancer
...

We build node 2, node 3, ... node n from a snapshot of node 1 instead of from scratch in order to speed up automatic scaling in case of heavy load.

What we observe: node2, node3, ... node n do all share the same serf.id, the one of node 1.

This is a pretty common way (apparently, i'm not the devops) or doing. See first diagram on https://aws.amazon.com/fr/blogs/devops/faster-auto-scaling-in-aws-cloudformation-stacks-with-lambda-backed-custom-resources/

I'm sure if we create node 2, node 3, ... node n from scratch it will solve our issue, but autoscaling would be slower.

Is there a reason why kong isn't regenerating a brand new serf.id on `kong restart`?

**Comment by danielrmeyer** [comment]
Hello, I am running into a very similar sounding issue.  

OS: Ubuntu Trusty
Kong version 0.9
provider: AWS

I have three nodes.  Here is ifconfig on each one:

```
eth0      Link encap:Ethernet  HWaddr 02:ae:da:23:a2:13  
          inet addr:172.31.32.51  Bcast:172.31.47.255  Mask:255.255.240.0
          inet6 addr: fe80::ae:daff:fe23:a213/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:753340 errors:0 dropped:0 overruns:0 frame:0
          TX packets:605682 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:326927107 (326.9 MB)  TX bytes:71977582 (71.9 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:122858 errors:0 dropped:0 overruns:0 frame:0
          TX packets:122858 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:10551517 (10.5 MB)  TX bytes:10551517 (10.5 MB)


eth0      Link encap:Ethernet  HWaddr 06:9a:9c:88:c3:af  
          inet addr:172.31.0.51  Bcast:172.31.15.255  Mask:255.255.240.0
          inet6 addr: fe80::49a:9cff:fe88:c3af/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:766293 errors:0 dropped:0 overruns:0 frame:0
          TX packets:599338 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:316099338 (316.0 MB)  TX bytes:73882918 (73.8 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:65325 errors:0 dropped:0 overruns:0 frame:0
          TX packets:65325 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:3504741 (3.5 MB)  TX bytes:3504741 (3.5 MB)


eth0      Link encap:Ethernet  HWaddr 0a:04:29:ff:db:a5  
          inet addr:172.31.16.51  Bcast:172.31.31.255  Mask:255.255.240.0
          inet6 addr: fe80::804:29ff:feff:dba5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:697913 errors:0 dropped:0 overruns:0 frame:0
          TX packets:528933 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:307236350 (307.2 MB)  TX bytes:66713154 (66.7 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:117627 errors:0 dropped:0 overruns:0 frame:0
          TX packets:117627 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6045706 (6.0 MB)  TX bytes:6045706 (6.0 MB)

```

I have the same kong.conf on each node:
```
database = cassandra
cassandra_contact_points = 172.31.32.51,172.31.0.51,172.31.16.51
cassandra_keyspace = kong
cassandra_consistency = ONE
cassandra_repl_strategy = SimpleStrategy
cassandra_repl_factor = 3
```

I am using terraform.  Here is my security group:

```
resource "aws_security_group" "kong" {
  name = "kong"
  vpc_id = "${aws_vpc.main.id}"

  ingress {
    from_port = 22
    to_port = 22
    protocol = "tcp"
    cidr_blocks = ["64.126.168.192/28", "64.126.168.95/32"]
  }

  ingress {
    from_port = 8001
    to_port = 8001
    protocol = "tcp"
    cidr_blocks = ["172.31.0.0/16"]
  }

  ingress {
    from_port = 8000
    to_port = 8000
    protocol = "tcp"
    cidr_blocks = ["172.31.0.0/16"]
  }

  ingress {
    from_port = 7946
    to_port = 7946
    protocol = "tcp"
    cidr_blocks = ["172.31.0.0/16"]
  }

  ingress {
    from_port = 7946
    to_port = 7946
    protocol = "udp"
    cidr_blocks = ["172.31.0.0/16"]
  }

  ingress {
    from_port = 8443
    to_port = 8443
    protocol = "tcp"
    cidr_blocks = ["172.31.0.0/16"]
  }

  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

The first kong node starts fine.  I can even stop and start it back up.  Here is the output after starting the first one:

```
kong start --v -c /tmp/provisioning/kong.conf 
2016/10/26 17:42:03 [verbose] Kong: 0.9.3
2016/10/26 17:42:03 [verbose] no config file found at /etc/kong.conf
2016/10/26 17:42:03 [verbose] no config file found at /etc/kong/kong.conf
2016/10/26 17:42:03 [verbose] reading config file at /tmp/provisioning/kong.conf
2016/10/26 17:42:03 [verbose] prefix in use: /usr/local/kong
2016/10/26 17:42:03 [verbose] preparing nginx prefix directory at /usr/local/kong
2016/10/26 17:42:03 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2016/10/26 17:42:03 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2016/10/26 17:42:03 [verbose] SSL enabled, no custom certificate set: using default certificate
2016/10/26 17:42:03 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2016/10/26 17:42:03 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
2016/10/26 17:42:04 [verbose] running datastore migrations
2016/10/26 17:42:04 [info] migrating rate-limiting for keyspace kong
2016/10/26 17:42:04 [info] rate-limiting migrated up to: 2015-08-03-132400_init_ratelimiting
2016/10/26 17:42:04 [info] rate-limiting migrated up to: 2016-07-25-471385_ratelimiting_policies
2016/10/26 17:42:04 [info] migrating response-ratelimiting for keyspace kong
2016/10/26 17:42:04 [info] response-ratelimiting migrated up to: 2015-08-21_init_response-rate-limiting
2016/10/26 17:42:04 [info] response-ratelimiting migrated up to: 2016-08-04-321512_response-rate-limiting_policies
2016/10/26 17:42:04 [info] 2 migrations ran
2016/10/26 17:42:04 [verbose] migrations up to date
2016/10/26 17:42:04 [verbose] dnsmasq not running, deleting /usr/local/kong/pids/dnsmasq.pid
2016/10/26 17:42:04 [verbose] serf agent not running, deleting /usr/local/kong/pids/serf.pid
2016/10/26 17:42:04 [verbose] waiting for serf agent to be running
2016/10/26 17:42:04 [verbose] serf agent started
2016/10/26 17:42:04 [verbose] auto-joining serf cluster
2016/10/26 17:42:04 [verbose] no other nodes found in the cluster
2016/10/26 17:42:04 [verbose] registering serf node in datastore
2016/10/26 17:42:04 [verbose] cluster joined and node registered in datastore
2016/10/26 17:42:04 [info] Kong started
```

When I try to start any of the other nodes I get this:
```
kong start --v -c /tmp/provisioning/kong.conf 
2016/10/25 23:21:21 [verbose] Kong: 0.9.3
2016/10/25 23:21:21 [verbose] no config file found at /etc/kong.conf
2016/10/25 23:21:21 [verbose] no config file found at /etc/kong/kong.conf
2016/10/25 23:21:21 [verbose] reading config file at /tmp/provisioning/kong.conf
2016/10/25 23:21:21 [verbose] prefix in use: /usr/local/kong
2016/10/25 23:21:21 [verbose] preparing nginx prefix directory at /usr/local/kong
2016/10/25 23:21:21 [verbose] could not start Kong, stopping services
2016/10/25 23:21:21 [verbose] leaving serf cluster
2016/10/25 23:21:21 [verbose] could not start Kong, stopping services
2016/10/25 23:21:21 [verbose] leaving serf cluster
2016/10/25 23:21:21 [verbose] could not start Kong, stopping services
2016/10/25 23:21:21 [verbose] leaving serf cluster
2016/10/25 23:21:21 [verbose] could not start Kong, stopping services
2016/10/25 23:21:21 [verbose] leaving serf cluster
2016/10/25 23:21:22 [verbose] could not start Kong, stopping services
2016/10/25 23:21:22 [verbose] leaving serf cluster
2016/10/25 23:21:22 [verbose] could not start Kong, stopping services
2016/10/25 23:21:22 [verbose] leaving serf cluster
2016/10/25 23:21:22 [verbose] could not start Kong, stopping services
2016/10/25 23:21:22 [verbose] leaving serf cluster
```

That last output goes on for pages before finally giving up.  Kong never starts up.

**Comment by danielrmeyer** [comment]
Sorry for the noise here.  I decided to go ahead and re-provision my ec2 instances.  After doing that everything just worked.  I'm hypothesizing that I had bad instances.  I'll update if I experience this issues again.

**Comment by daniele2112** [comment]
I went into the same issue trying to setup kong (0.9.8)  with the aws autoscaling group. I need to take advantage of the scaling features based on the server load.

The AMI have a saved id  /usr/local/kong/serf/serf.id and the new launched instances wont join the cluster because the duplicated ids in the "nodes" tables.

The workaround is to delete the serf.id file before to start kong, but that's wrong because restarting the service multiple time on the same host should not change the cluster id.

The best solution from the aws/Linux side is to put in the user data field "rm /usr/local/kong/serf/serf.id". That wills tart kong with a new id only when a new ec2 is launched.
 In this case I have an issue because if launched from systemd kong won't create a new serf.id. If the service is launched from cli the cluster go up correctly.
At the moment i'm running it with the ugly solution on user data:

```
#!/bin/bash
rm /usr/local/kong/serf/serf.id && service kong restart
```

From the kong side the best solution would be to renew the cluster id if a new hostname is detected.


.

**Comment by thefosk** [comment]
> The workaround is to delete the serf.id file before to start kong, but that's wrong because restarting the service multiple time on the same host should not change the cluster id.
