### ISSUE TITLE
Question: rate-limit and permissions

### ISSUE THREAD

**Issue by mytototo** [Mashape/kong#1753]
Hey! Is it possible to warn a consumer that he has reached his limit but still continuing proxying his requests?

**Comment by thibaultcha** [comment]
Hi,

I don't believe so. Your consumers can watch for the consumption headers set by the rate-limiting plugins: https://getkong.org/plugins/rate-limiting/

**Comment by mytototo** [comment]
Interesting. This answers my question then. Thank you.
