### ISSUE TITLE
JWT plugin has problem on IE11

### ISSUE THREAD

**Issue by hnq90** [Mashape/kong#1755]
### Summary

> I found that IE11 automatically changes authorization header if already present such as basic auth, and it's not occurred in locally hosting sites, but only occurred in public hosting sites...

There's a question on StackOverFlow: http://stackoverflow.com/questions/28615850/internet-explorer-11-replaces-authorization-header
### Additional Details & Logs
- Kong version: 0.9.3
- Operating System: Docker on CentOS 7

**Comment by thibaultcha** [comment]
Hi,

I'm not sure if this is really in the scope of Kong? And not sure what is your question exactly either. I also see multiple answers to that SO question, no I am not sure either what other answer you'd be expecting to get here? 

Let me know
