### ISSUE TITLE
Request transformation -- cannot have both Remove and Add for same body field

### ISSUE THREAD

**Issue by chris-hailstorm** [Mashape/kong#1756]
### Summary

POST an Add rule when a Remove rule already exists: Conflict message from OpenRest

### Steps To Reproduce

1.  Create a request transformation / remove rule on an API:

```
curl -X POST --url ADMINURL/apis/THEAPI --data 'name=request-transformer' --data 'config.remove.body=key'
```

OK

2.  Try to create a request transformation / add rule on the same API:

```
curl -X POST --url ADMINURL/apis/THEAPI --data 'name=request-transformer' --data 'config.add.body=key:NEWVALUE'
```

Get this error message:

```
<html>
<head><title>409 Conflict</title></head>
<body bgcolor="white">
<center><h1>409 Conflict</h1></center>
<hr><center>openresty/1.9.15.1</center>
</body>
</html>
```

3.  The documentation seems to say multiple rules are OK -- see https://getkong.org/plugins/request-transformer/:

```
Order of execution

Plugin performs the response transformation in following order

remove --> replace --> add --> append
```

That suggests you can have multiple rules -- why else worry about the order?

(The doco says "response" but the page is about requests -- a typo)

### Additional Details & Logs

- Kong version (`$ kong version`) -- 0.9.1
- Operating System -- Ubuntu

**Comment by DonMartin76** [comment]
I think you can't do it in two requests, you have to do it in one go:

```
curl -X POST --url ADMINURL/apis/THEAPI --data 'name=request-transformer' --data 'config.remove.body=key' --data 'config.add.body=key:NEWVALUE'
```

Does that work?

The `request-transformer` plugin can AFAIK only exist once on the API (that's the `409` you get), and has to configured as a whole.

**Comment by thibaultcha** [comment]
Thanks for reporting!

**Comment by chris-hailstorm** [comment]
Confirmed
