### ISSUE TITLE
Conflicting luasocket version dependencies in source build

### ISSUE THREAD

**Issue by rowanthorpe** [Mashape/kong#1761]
### Summary

When building kong `0.9.3-0` from source, the installation of kong with luarocks has a conflicting dependency:
- kong == `0.9.3-0` depends on lua-cassandra == `0.5.3` (using `0.5.3-0`)
- lua-cassandra == `0.5.3-0` depends on luasocket ~> `3.0-rc1` (using `3.0rc1-2`)
- kong == `0.9.3-0` depends on luasocket == **`2.0.2` (using `3.0rc1-2`)**

This causes luasocket to be rebuilt 3 times (flip-flopping versions between `2.0.2-6` and `3.0-rc1-2`) and for the kong install to finally throw a warning at the end about the unsatisfied luasocket dependency.
### Steps To Reproduce
1. `luarocks install kong 0.9.3-0`
2. read the logs
### Additional Details & Logs
- Kong version (`0.9.3-0`)
- Debian Jessie (GNU/Linux)

**Comment by thibaultcha** [comment]
Hi,

Thanks for reporting. This shouldn't be an issue as LuaSocket 3.0 is mainly about Lua 5.3 and IPv6 support. Besides, Kong only uses the `socket.url` module while lua-cassandra and pgmoon rely on LuaSockets themselves.

This should also be resolved in 0.10 anyways because lua-cassandra 1.x does not explicitly depend on LuaSocket anymore.

**Comment by rowanthorpe** [comment]
OK, thanks for clarifying. If your confidence in the "shouldn't be an issue" factor is high enough (probably yes) then feel free to close this. I'll leave it to your judgement in case you want the issue open as a reminder to check after the bump to 0.10

**Comment by thibaultcha** [comment]
Yes, we'll still leave it open until 0.10 is released since we'd rather avoid having bloated dependencies regardless of whether they create issues or not anyways.

Thanks!

**Comment by thibaultcha** [comment]
The luasocket dependency is now gone from lua-cassandra 1.x. Closing this, thanks!
