### ISSUE TITLE
Fix nginx conf, proxy_set_header X-Forwarded-For header

### ISSUE THREAD

**Issue by WALL-E** [Mashape/kong#1762]
### Summary

if use nginx module `ngx_http_realip_module`,   the following configuration statement is wrong

```
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

Correct configuration

```
proxy_set_header  X-Forwarded-For '$X-Forwarded-For,$origin_remote_addr';
```
### Reason

$proxy_add_x_forwarded_for be equal to '$X-Forwarded-For， $remote_addr', 
if use the module `ngx_http_realip_module`,  $remote_addr will be reset to real-ip,  while $realip_remote_addr keeps the original client address.

This issue will not affect `kong`,  just send the wrong header[X-Forwarded-For] to the upstream server, in general there will be no problem.

**Comment by thibaultcha** [comment]
Moved to @2202. Thanks!
