### ISSUE TITLE
Install Kong database inside a custom schema

### ISSUE THREAD

**Issue by mytototo** [Mashape/kong#1763]
Hey! I'd like to install Kong in a schema other than `public` inside my PostgreSQL. I couldn't find any info about it. Is it possible?

**Comment by thibaultcha** [comment]
That should be possible, see #1193 #1196.

**Comment by mytototo** [comment]
I saw those issues but it's weird to not find docs about it. There is no official explanation at all about how using it.

**Comment by mytototo** [comment]
@thibaultcha Do you have a link/resource explaining how to configure such a thing?

**Comment by thibaultcha** [comment]
You would need to configure the `search_path` of your Kong user, see: https://www.postgresql.org/docs/9.1/static/runtime-config-client.html

Contributions to make this configurable from the Kong side are welcomed!
