### ISSUE TITLE
No response body captured in Runscope, although log_body=true

### ISSUE THREAD

**Issue by chris-hailstorm** [Mashape/kong#1764]
### Summary

We use the Runscope plugin to monitor all traffic to one instance of Kong.  The requests and responses are captured, and headers are viewable in Runscope, but response body is not.
### Steps To Reproduce
1.  Create an API
2.  Configure the "runscope" plugin for all APIs / not just this one, e.g.

`curl -X POST http://localhost:ADMINPORT/plugins/ --data "name=runscope" --data "config.bucket_key=XXXXXXXXXXXX" --data "config.access_token=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" --data "config.log_body=true"`
1.  Call the API via Kong (a GET), look at the Runscope traffic page
2.  No request body as expected; but also no response body
### Additional Details & Logs
- Kong version (`$ kong version`)  0.9.1
- Operating System  Ubuntu

**Comment by p0pr0ck5** [comment]
@chris-hailstorm do you still see this behavior with Kong 0.10.x releases?

**Comment by p0pr0ck5** [comment]
Closing as stale following no response. Do let us know if you still see this in the 0.10.x release and we can reexamine this. Thanks!
