### ISSUE TITLE
Only the fist query parameter is sent

### ISSUE THREAD

**Issue by PierrickI3** [Mashape/kong#1765]
### Summary

When I call my API through kong, only the first query parameter is passed.

### Steps To Reproduce

1. Create a route: `curl -d 'name=ping&request_path=/api/v1/ping&upstream_url=http://ping:3000/' http://localhost:8001/apis/`
2. Test the route: `curl localhost:8000/api/v1/ping?host=www.google.fr&customerId=0`
3. Check what was received on the server side: `'No customerId specified' '/api/v1/ping/?host=www%2egoogle%2efr'`

Only the `host` query parameter was passed. The same issue if I switch the parameters, i.e. calling `curl localhost:8000/api/v1/ping?customerId=0&host=www.google.fr` only passes `customerId=0`to the service.

### Additional Details & Logs

- Kong version: `0.9.0`
- Kong error logs: no messages besides `info` and `notice`
- Kong access log:
```
127.0.0.1 - - [25/Oct/2016:09:37:15 +0000] "GET /api/v1/ping/?host=www.google.fr HTTP/1.1" 400 48 "-" "curl/7.29.0"
127.0.0.1 - - [25/Oct/2016:09:41:24 +0000] "GET /api/v1/ping?customerId=0 HTTP/1.1" 400 42 "-" "curl/7.29.0"
```
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System: using `mashape/kong:cassandra3` docker image

Am I missing something while creating the route? Why is only the first query parameter being passed?

**Comment by Tieske** [comment]
can you retry with the `curl` argument quoted, eg;
```shell
curl "localhost:8000/api/v1/ping?host=www.google.fr&customerId=0"
```

**Comment by PierrickI3** [comment]
That worked. Thanks!
