### ISSUE TITLE
How to configure an API behind a proxy

### ISSUE THREAD

**Issue by jonathan-macke** [Mashape/kong#1766]
### Summary

I want to use Kong to expose an API which is behind a proxy. 
I'm trying with env variable like http_proxy but Kong is not able to access my API.
Is there a way to configure Kong so that it goes through a proxy when accessing an API ?
### Additional Details & Logs

Kong version 0.9.3

**Comment by thibaultcha** [comment]
Simply set your API's `upstream_url` to the address where the proxy can be reached at?
