### ISSUE TITLE
Sentinel protocol not supported for Redis

### ISSUE THREAD

**Issue by logronoide** [Mashape/kong#1768]
### Summary

To run a highly available redis master-slave architecture the preferred solution is to deploy several 'Sentinel' agents (http://redis.io/topics/sentinel). To failover between the master and slave redis processes the clients must connect to a sentinel endpoint and not the direcly to any redis.

If I am not wrong, it's not possible to tell Kong plugins to use the sentinel protocol instead of redis. In order to have a highly available service architecture, Kong should connect to a sentinel agent. lua-resty-redis supports sentinel out of the box.
### Additional Details & Logs
- Kong version (0.9.3)
- Kong configuration (Rate Limiting plugin)
- Ubuntu 16.04 + Kubernetes 1.3.7 + Docker 1.12.X.Beta + Redis 3.2.4 + Cassandra 2.x

**Comment by thefosk** [comment]
@logronoide we are using [`lua-resty-redis`](https://github.com/openresty/lua-resty-redis) to connect to Redis, and connecting using its `connect` method (https://github.com/Mashape/kong/blob/master/kong/plugins/rate-limiting/policies.lua#L68).

**Comment by logronoide** [comment]
I have to double check why sentinel is not working properly. it's not recovering properly when a redis master fails.

**Comment by thefosk** [comment]
okay, please keep me updated on the progress

**Comment by logronoide** [comment]
I can confirm lua-resty-redis does not support redis failover with Sentinel or Clustering. Hence, using Redis as it is for a resilient architecture is not possible.

There are several options here:
1) Sentinel support with [lua-resty-redis-connector](https://github.com/pintsized/lua-resty-redis-connector). This wrapper of lua-resty-redis enables Sentinel for master-slave failover, but not for clustering.
2) Use a third party clustering and failover solution for Redis like [Twemproxy](https://github.com/twitter/twemproxy).
3) Wait for lua-resty-redis to support clustering and sentinel. It seems they will do it sooner than later https://github.com/openresty/lua-resty-redis/issues/43

As a short term solution, I think Twemproxy can be a good option.

**Comment by peter-evans** [comment]
I was also planning on using Redis Sentinel for a HA Redis cluster. Hoping this will be supported in future.
In the meantime I will check out the options mentioned by @logronoide. Thank you!

**Comment by p0pr0ck5** [comment]
Thanks to all for the discussion here. Redis Sentinal is currently supported in Kong Enterprise. Please see https://www.mashape.com/enterprise/ for more details. Thank you!
