### ISSUE TITLE
Replace cjson

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#177]
[cjson](https://github.com/mpx/lua-cjson) seems like a dormant project, with a lot of pending issues and PRs that have never been accepted, or replied to. Our main issue currently is encoding empty arrays, as already reported in 2013 [here](https://github.com/mpx/lua-cjson/issues/11).

1. We are currently doing some ugly stuff to get an empty array when we need it. It will be even uglier for plugins doing extensive JSON work (API analytics is an example, as I already wrote it, and can affirm it is terrible to have to deal with that).

2. With contributors and users potentially writing new plugins, we should prevent the huge [confusion](http://openmymind.net/Lua-JSON-turns-empty-arrays-into-empty-hashes/) around this issue and have our plugins showing a decent way of dealing with JSON in Lua.

One one hand, cjson is supposed to be the fastest ([source 1](https://github.com/mpx/lua-cjson/blob/master/performance.txt), [source 2](http://lua-users.org/wiki/JsonModules)), but on the other hand, having to do extremely ugly stuff (search and replace for API analytics) to force empty objects to be array doesn't not worth the performance anymore.

Suggested replacements:
- [libcjson](https://github.com/bungle/lua-resty-libcjson): handles encoding of empty tables to arrays or objects. (no speed tests)
- [dkjson](http://dkolf.de/src/dkjson-lua.fsl/): empty arrays supported too (slower than cjson)
- [th-LuaJSON](http://luaforge.net/projects/luajson/): empty arrays supported too (slower than dkjson)

**Comment by thibaultCha** [comment]
One the plugins are moved out of Kong, it would also be easier for them to use another JSON library than cjson. If a plugin needs heavy JSOn manipulation, it can use a plugin that handles the needed edgecases.

**Comment by thefosk** [comment]
It is to note that among other uses `cjson` is also extensively used for serializing and deserializing items from the in-memory cache: speed is a **main** factor and any replacement will directly determine Kong's request throughput.

**Comment by thefosk** [comment]
An alternative could be https://github.com/cloudflare/lua-resty-json which they claim is faster than cjson.

**Comment by thibaultCha** [comment]
It does not have an encoder. This was more for the limitations of cjson in terms of encoding (of empty arrays) for plugins rather than speed (for in memory cache), which should not use any expensive serialization at all.
