### ISSUE TITLE
Kong does not pickup port information in upstream url while creating an api

### ISSUE THREAD

**Issue by rsachdeva9355** [Mashape/kong#1771]
### Summary

Kong does not pickup port information in upstream url while creating an api. Defaults it to 80.
### Steps To Reproduce
1. Create a new api with upstream_url as "http://abc.com:8080".
2. Try opening the same on kong and it will redirect you to "http://abc.com" and trim the port information
### Additional Details & Logs
- Kong version (`0.9.3`)
- Operating System [Amazon Linux]

**Comment by thibaultcha** [comment]
Thanks for the report, this should be fixed in the upcoming 0.10 release.

**Comment by rsachdeva9355** [comment]
@thibaultcha : Can I help with the fix?
I can start if no one is working on it.

**Comment by thibaultcha** [comment]
Thanks for the offer but this is already being taken care of :) This won't be a fix but part of the router rewrite (already in progress).

**Comment by rsachdeva9355** [comment]
Okay sure

**Comment by Tieske** [comment]
@rsachdeva9355 you could test the new RC and check whether it is still the case.

**Comment by lokeshlal** [comment]
Hi, By when this will be part of the docker image offer by Kong https://getkong.org/install/docker/

**Comment by Rikhart** [comment]
I have the same error, in the last Kong version, please fix that.

**Comment by kikito** [comment]
@Rikhart please open a new issue with more details (your exact config, steps to reproduce, etc). If you want, you can link to this issue on the new one if you think they are related. But the code has changed a lot on the last 6 months so that is unlikely.

**Comment by feelgoodman** [comment]
Same issue with Docker here. Is it not a common use case, to route to containers on ports other than 80?
