### ISSUE TITLE
remove heroku installation instructions

### ISSUE THREAD

**Issue by colllin** [Mashape/kong#1775]
It looks like the heroku kong [app](https://github.com/heroku/heroku-kong) and [buildpack](https://github.com/heroku/heroku-buildpack-kong) are outdated and no longer maintained.  It might be good to remove it from the Readme in this repo, and from the [installation docs](https://getkong.org/install/heroku/).

**Comment by thibaultcha** [comment]
Thanks, we noticed the PR on getkong.org but are still waiting for updates on it.
