### ISSUE TITLE
JWT Plugin: Why do I need to store private key with consumer?

### ISSUE THREAD

**Issue by DonMartin76** [Mashape/kong#1779]
When reading the documentation of the JWT Plugin (https://getkong.org/plugins/jwt/), specifically the section on using RSA Public/Private key pairs, it puzzles me a little why I would need to upload the private key to Kong?

I have understood the thing with JWT tokens is that they enable you to verify the authenticity of the token using a public key, without needing to distribute the private key to other places than just the Authorization Server (which crafts the JWT).

Is this a documentation flaw and it works as expected, or why does the plugin need the private key? The private key should only be needed when signing the token, and that's not done in Kong.

**Comment by DonMartin76** [comment]
I can confirm it's just a documentation bug. It works to only pass in the public key to Kong.

**Comment by thefosk** [comment]
@DonMartin76 could you submit a patch to https://github.com/Mashape/getkong.org ?

**Comment by DonMartin76** [comment]
Will do. Somebody from the JWT maintainers should look over it though.

**Comment by thibaultcha** [comment]
Thanks for reporting! I created Mashape/getkong#292.
