### ISSUE TITLE
[request] Kong Heroku Buildpack

### ISSUE THREAD

**Issue by corbanb** [Mashape/kong#178]
This is exactly the kind of thing I'd love to see as a Heroku build pack. Anyone interested in working on that with me?

https://elements.heroku.com/buildpacks

**Comment by thefosk** [comment]
+1

@corbanb I am not familiar yet with Heroku build packs, but I can give my contribution to create one.

**Comment by sinzone** [comment]
I think @ahmadnassri has some good experience with Heroku

**Comment by ahmadnassri** [comment]
perhaps a good starting point is to use https://github.com/leafo/heroku-buildpack-lua since Kong is starts with Lua + LuaRocks

**Comment by PierreKircher** [comment]
first problem with heroku would be the single http port limit .. how are you going to controll the api ? 
the mesh is not able to pick that up

**Comment by PierreKircher** [comment]
@ahmadnassri are you proposing to actualy run a full blown cedar14 for the plugins alone ?

**Comment by ahmadnassri** [comment]
@PierreKircher oh no, i'm just saying it would make more sense to use something like [heroku-buildpack-lua](https://github.com/leafo/heroku-buildpack-lua) to auto compile your plugins (and include in pre-installed / packaged kong-core) for development / debugging purposes.

**Comment by PierreKircher** [comment]
problem as i mentioned befor with a paas like heroku is the single port http limit while you could comp. the lua files in the buildpack .. its "static" since you cant alter anything .. you lose the power of controlling the api gateway .. and in terms of different versions thats a show stopper

the only sane solution here would be a dockerfile with 2 procs .. (double the cost of course)

**Comment by ahmadnassri** [comment]
@PierreKircher not sure what the problem you are referring to with the "single port" limit? Kong can be configured to listen to a specific port on launch, which you can map to the heroku specified port.

as for admin port, you wouldn't want that to be externally available anyways. best to keep that local and only call it from the heroku shell

**Comment by PierreKircher** [comment]
good point i totaly missed the cli opion ..my bad

**Comment by corbanb** [comment]
This is great conversation. My guess is there are some good starting points here. As I am not as familiar to kong as most of you I am sure someone would be able to kickoff the buildpack much faster. But I am happy to dig in with you all. This would be huge for our team.

**Comment by ahmadnassri** [comment]
@corbanb perhaps we can do a quick hangout/skype session to discuss & share ideas, please throw me an email `ahmad [at] mashape.com` to setup a time.

**Comment by PierreKircher** [comment]
oh i join !

**Comment by ahmadnassri** [comment]
@PierreKircher of course, lets sync up a time through email :)

**Comment by sinzone** [comment]
Someone is on it?

**Comment by ahmadnassri** [comment]
@sinzone yes, we have a call tomorrow to discuss.

@corbanb you still good to chat tomorrow at agreed time?

**Comment by corbanb** [comment]
@sinzone @ahmadnassri due to an influx of work during my days I am unable to make time. I should be able to help build and code at night if you guys get things setup I will be happy to provide that time when I can. sorry for the delays.

**Comment by sinzone** [comment]
we can have a setup call at night too.

**Comment by marianudo** [comment]
Hi guys, catching up on this; any ideas from that hangout? Any progress? What else would you need to get it done? Maybe I could help during the next few months or by the beginning of 2016.

**Comment by ahmadnassri** [comment]
@marianudo I got as far as experimenting with [kong-dist-heroku](https://github.com/mashape/kong-dist-heroku) which uses [heroku-buildpack-lua](https://github.com/leafo/heroku-buildpack-lua) but have not gotten it quite to work yet, love any feedback / contribution :)

**Comment by mars** [comment]
A proposal is now open #928 which discusses the main challenge to running Kong on Heroku.

**Comment by mars** [comment]
The buildpack & app repos we've be developing at Heroku over the past couple months just went open-source:

* [Heroku app](https://github.com/heroku/heroku-kong): [v1.0.0-beta.2](https://github.com/heroku/heroku-kong/releases)
* [Heroku buildpack](https://github.com/heroku/heroku-buildpack-kong): [v2.0.0](https://github.com/heroku/heroku-buildpack-kong/releases)

Note: **This is pre-release/beta software.**

**Comment by ahmadnassri** [comment]
@mars :clap: well done, this looks amazing, we're gonna start playing with this and will make an update to point to this on our installation pages.

very nicely done.

quick note, I can see a Librato plugin in there, would you like to make a separate PR to get this into the main repo? we can work on assets / docs for the site afterwards.

**Comment by ahmadnassri** [comment]
closing this issue thread, any further issues can be tracked on the appropriate repos:

* [Heroku app](https://github.com/heroku/heroku-kong)
* [Heroku buildpack](https://github.com/heroku/heroku-buildpack-kong)

**Comment by sinzone** [comment]
we should put it here now: 

![](http://cl.ly/2I1r171R240l/Image%202016-02-17%20at%205.57.50%20PM.png)

**Comment by ahmadnassri** [comment]
@sinzone already done.

**Comment by sinzone** [comment]
that was fast.

**Comment by thibaultCha** [comment]
:pray:

**Comment by mars** [comment]
@ahmadnassri  I just checked the [Heroku Install on getkong.org](https://getkong.org/install/heroku/). Thanks for putting that together.

We just updated the [heroku-kong README](https://github.com/heroku/heroku-kong/blob/master/README.md) with some corrections to Usage & Cassandra sections re: Instaclustr provisioning & automatic schema setup.

Please update getkong.org when you have a chance. :beers:

**Comment by ahmadnassri** [comment]
@mars sure thing. will get to that shortly. also, the site in itself is open-source, so if you ever found something to update: github.com/Mashape/getkong.org
