### ISSUE TITLE
Replace output before passing on using regex

### ISSUE THREAD

**Issue by danielvijge** [Mashape/kong#1780]
Is it possible to find-and-replace parts of the response before sending it on? Not just completely a json key, but do something smarter with regex replace.

For example, lets say Kong is proxying the Facebook Graph API. The response contains the JSON keys paging.previous and paging.next with URLs the get the next set of results. These URLs include the full domain. Obviously, if Kong is in front of Facebook, the URL for Kong is different. The previous and next URL should then also be Kong proxied URLs.

I have done some hacking on the response-transformer plugin, and added a config.replace.body[] parameter. This can contain a regex pattern/replace, so it is very flexible in what you can replace with it. However, I am not sure this is the correct solution, and if this would be a desired feature for Kong.

**Comment by thibaultcha** [comment]
Should be possible. See the lua-nginx-module documentation for scripting purposes:
https://github.com/openresty/lua-nginx-module

**Comment by BenJaziaSadok** [comment]
Hello @danielvijge, i'm facing the same issue, did you find a way to do that?
