### ISSUE TITLE
Any plugin could do EIP(enterprise integration patterns) easier?

### ISSUE THREAD

**Issue by kala888** [Mashape/kong#1787]
### Summary

I consider a API tools with a lightweight ESB. Kong is so awesome, easy to use and less dependents. But i still need a lightweight tools to do  route(EIP,  like what Apache Camel do). Here is a case

### Steps To Reproduce

1. Kong receive a request
2. Route the request to App1 and at the same time copy the request send to App2.
3. Send the App1 repsonse to client

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by DonMartin76** [comment]
You already mention Apache Camel as a potent EIP library. Why would you want to couple that functionality with Kong? I do understand why it would look like a good idea (leveraging Kong as a base for an ESB), but from an architectural point of view I would highly recommend leaving it uncoupled, and treat your EIP implementation as a service end point (API) served by Kong, and not mash them together.

Getting the EIP functionality into Kong will eventually bloat Kong in such a way that it is no longer lean, fast and awesome.

I would go for things like Camel in Docker behind Kong; combine that with a dedicated queuing system like Rabbit MQ, and you have your building blocks ready. Doing configuration based EIP implementing is seldom fun for all but the most basic use cases.

**Comment by p0pr0ck5** [comment]
Going to close this, as moving forward we want to keep Github issues reserved for actual issues running Kong; community discussion can be continued on the [Kong mailing list](https://groups.google.com/forum/#!forum/konglayer) or
[Gitter](https://gitter.im/Mashape/kong). Thank you for the initial question and discussion!
