### ISSUE TITLE
Prevent direct access to the API behing Kong

### ISSUE THREAD

**Issue by aubm** [Mashape/kong#1789]
Hey, sorry if this question has already been asked before but I can't find it in the issue tracker.

### Summary

I wonder how you guys would do to prevent direct access to an API which is hosted on App Engine.
I want to use Kong in front of my API to handle the user authentication for me, but what if the user finds out the URL of the API and decides to bypass Kong?

**Comment by Tieske** [comment]
If the backend is publicly accessible, you simply can't...

A quick way might be using basic-auth (or requiring a special header or something like that) on the backend, which you insert in Kong. Anything bypassing Kong wouldn't have the proper credentials/settings and be refused by your app. But this smells like 'security by obscurity'...

**Comment by aubm** [comment]
I see... that is what I was thinking. Thank you for the answer.
