### ISSUE TITLE
Clean up the package build process and create tests

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#179]
Clean up the code and make tests.

**Comment by thibaultCha** [comment]
We should also move the package builder outside of this repo. They could live on their own, with their own git history, test suite etc...

**Comment by ahmadnassri** [comment]
:+1: to both points.

**Comment by thibaultCha** [comment]
Is this coming?

**Comment by thefosk** [comment]
Done. Forgot to close the issue.

**Comment by thefosk** [comment]
The only thing that I didn't do was moving out the distributions creation, which now live in their `distributions` folder which can be easily moved somewhere else (there is no folder/file dependency to any other file, everything is in `distributions`).
