### ISSUE TITLE
Kong fails to restart from AMIMarketplace Install

### ISSUE THREAD

**Issue by peterbsmith2** [Mashape/kong#1790]
### Summary

I used the command `kong restart` and got the following:
```bash
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: [postgres error] connection refused

  Run with --v (verbose) or --vv (debug) for more details
```
### Steps To Reproduce

1. Install kong from AWS Marketplace
2. `kong restart`

### Additional Details & Logs

- Kong version (`$ kong version`)
0.9.3
- Kong debug-level startup logs (`$ kong start --vv`)
2016/11/02 14:40:16 [verbose] Kong: 0.9.3
2016/11/02 14:40:16 [debug] ngx_lua: 10005
2016/11/02 14:40:16 [debug] nginx: 1009015
2016/11/02 14:40:16 [debug] Lua: LuaJIT 2.1.0-beta2
2016/11/02 14:40:16 [verbose] no config file found at /etc/kong.conf
2016/11/02 14:40:16 [verbose] no config file found at /etc/kong/kong.conf
2016/11/02 14:40:16 [verbose] reading config file at /usr/local/kong/kong.conf
2016/11/02 14:40:16 [debug] admin_listen = "0.0.0.0:8001"
2016/11/02 14:40:16 [debug] anonymous_reports = true
2016/11/02 14:40:16 [debug] cassandra_consistency = "ONE"
2016/11/02 14:40:16 [debug] cassandra_contact_points = {"127.0.0.1"}
2016/11/02 14:40:16 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2016/11/02 14:40:16 [debug] cassandra_keyspace = "kong"
2016/11/02 14:40:16 [debug] cassandra_port = 9042
2016/11/02 14:40:16 [debug] cassandra_repl_factor = 1
2016/11/02 14:40:16 [debug] cassandra_repl_strategy = "SimpleStrategy"
2016/11/02 14:40:16 [debug] cassandra_ssl = false
2016/11/02 14:40:16 [debug] cassandra_ssl_verify = false
2016/11/02 14:40:16 [debug] cassandra_timeout = 5000
2016/11/02 14:40:16 [debug] cassandra_username = "kong"
2016/11/02 14:40:16 [debug] cluster_listen = "0.0.0.0:7946"
2016/11/02 14:40:16 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2016/11/02 14:40:16 [debug] cluster_profile = "wan"
2016/11/02 14:40:16 [debug] cluster_ttl_on_failure = 3600
2016/11/02 14:40:16 [debug] custom_plugins = {}
2016/11/02 14:40:16 [debug] database = "postgres"
2016/11/02 14:40:16 [debug] dnsmasq = true
2016/11/02 14:40:16 [debug] dnsmasq_port = 8053
2016/11/02 14:40:16 [debug] log_level = "notice"
2016/11/02 14:40:16 [debug] lua_code_cache = "on"
2016/11/02 14:40:16 [debug] lua_package_cpath = ""
2016/11/02 14:40:16 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2016/11/02 14:40:16 [debug] lua_ssl_verify_depth = 1
2016/11/02 14:40:16 [debug] mem_cache_size = "128m"
2016/11/02 14:40:16 [debug] nginx_daemon = "on"
2016/11/02 14:40:16 [debug] nginx_optimizations = true
2016/11/02 14:40:16 [debug] nginx_worker_processes = "auto"
2016/11/02 14:40:16 [debug] pg_database = "kong"
2016/11/02 14:40:16 [debug] pg_host = "127.0.0.1"
2016/11/02 14:40:16 [debug] pg_port = 5432
2016/11/02 14:40:16 [debug] pg_ssl = false
2016/11/02 14:40:16 [debug] pg_ssl_verify = false
2016/11/02 14:40:16 [debug] pg_user = "kong"
2016/11/02 14:40:16 [debug] prefix = "/usr/local/kong"
2016/11/02 14:40:16 [debug] proxy_listen = "0.0.0.0:8000"
2016/11/02 14:40:16 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2016/11/02 14:40:16 [debug] serf_path = "serf"
2016/11/02 14:40:16 [debug] ssl = true
2016/11/02 14:40:16 [debug] ssl_cert = "/usr/local/kong/ssl/kong-default.crt"
2016/11/02 14:40:16 [debug] ssl_cert_key = "/usr/local/kong/ssl/kong-default.key"
2016/11/02 14:40:16 [verbose] prefix in use: /usr/local/kong
2016/11/02 14:40:16 [verbose] no config file found at /etc/kong.conf
2016/11/02 14:40:16 [verbose] no config file found at /etc/kong/kong.conf
2016/11/02 14:40:16 [verbose] no config file, skipping loading
2016/11/02 14:40:16 [debug] admin_listen = "0.0.0.0:8001"
2016/11/02 14:40:16 [debug] anonymous_reports = true
2016/11/02 14:40:16 [debug] cassandra_consistency = "ONE"
2016/11/02 14:40:16 [debug] cassandra_contact_points = {"127.0.0.1"}
2016/11/02 14:40:16 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2016/11/02 14:40:16 [debug] cassandra_keyspace = "kong"
2016/11/02 14:40:16 [debug] cassandra_port = 9042
2016/11/02 14:40:16 [debug] cassandra_repl_factor = 1
2016/11/02 14:40:16 [debug] cassandra_repl_strategy = "SimpleStrategy"
2016/11/02 14:40:16 [debug] cassandra_ssl = false
2016/11/02 14:40:16 [debug] cassandra_ssl_verify = false
2016/11/02 14:40:16 [debug] cassandra_timeout = 5000
2016/11/02 14:40:16 [debug] cassandra_username = "kong"
2016/11/02 14:40:16 [debug] cluster_listen = "0.0.0.0:7946"
2016/11/02 14:40:16 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2016/11/02 14:40:16 [debug] cluster_profile = "wan"
2016/11/02 14:40:16 [debug] cluster_ttl_on_failure = 3600
2016/11/02 14:40:16 [debug] custom_plugins = {}
2016/11/02 14:40:16 [debug] database = "postgres"
2016/11/02 14:40:16 [debug] dnsmasq = true
2016/11/02 14:40:16 [debug] dnsmasq_port = 8053
2016/11/02 14:40:16 [debug] log_level = "notice"
2016/11/02 14:40:16 [debug] lua_code_cache = "on"
2016/11/02 14:40:16 [debug] lua_package_cpath = ""
2016/11/02 14:40:16 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2016/11/02 14:40:16 [debug] lua_ssl_verify_depth = 1
2016/11/02 14:40:16 [debug] mem_cache_size = "128m"
2016/11/02 14:40:16 [debug] nginx_daemon = "on"
2016/11/02 14:40:16 [debug] nginx_optimizations = true
2016/11/02 14:40:16 [debug] nginx_worker_processes = "auto"
2016/11/02 14:40:16 [debug] pg_database = "kong"
2016/11/02 14:40:16 [debug] pg_host = "127.0.0.1"
2016/11/02 14:40:16 [debug] pg_port = 5432
2016/11/02 14:40:16 [debug] pg_ssl = false
2016/11/02 14:40:16 [debug] pg_ssl_verify = false
2016/11/02 14:40:16 [debug] pg_user = "kong"
2016/11/02 14:40:16 [debug] prefix = "/usr/local/kong/"
2016/11/02 14:40:16 [debug] proxy_listen = "0.0.0.0:8000"
2016/11/02 14:40:16 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2016/11/02 14:40:16 [debug] serf_path = "serf"
2016/11/02 14:40:16 [debug] ssl = true
2016/11/02 14:40:16 [verbose] prefix in use: /usr/local/kong
2016/11/02 14:40:16 [verbose] preparing nginx prefix directory at /usr/local/kong
2016/11/02 14:40:17 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2016/11/02 14:40:17 [debug] searching for OpenResty 'resty' executable
2016/11/02 14:40:17 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.9.15.1'
2016/11/02 14:40:17 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2016/11/02 14:40:17 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2016/11/02 14:40:17 [verbose] SSL enabled, no custom certificate set: using default certificate
2016/11/02 14:40:17 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2016/11/02 14:40:17 [verbose] running datastore migrations
2016/11/02 14:40:17 [verbose] could not start Kong, stopping services
2016/11/02 14:40:17 [verbose] leaving serf cluster
2016/11/02 14:40:17 [verbose] stopping dnsmasq at /usr/local/kong/pids/dnsmasq.pid
2016/11/02 14:40:17 [debug] sending signal to pid at: /usr/local/kong/pids/dnsmasq.pid
2016/11/02 14:40:17 [debug] no pid file at: /usr/local/kong/pids/dnsmasq.pid
2016/11/02 14:40:17 [verbose] stopped services
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:37: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: [postgres error] connection refused
stack traceback:
       	[C]: in function 'error'
       	/usr/local/share/lua/5.1/kong/cmd/start.lua:37: in function 'execute'
       	/usr/local/share/lua/5.1/kong/cmd/restart.lua:13: in function 'cmd_exec'
       	/usr/local/share/lua/5.1/kong/cmd/init.lua:85: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:85>
       	[C]: in function 'xpcall'
       	/usr/local/share/lua/5.1/kong/cmd/init.lua:85: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:42>
       	/usr/local/bin/kong:11: in function 'file_gen'
       	init_worker_by_lua:38: in function <init_worker_by_lua:36>
       	[C]: in function 'pcall'
       	init_worker_by_lua:45: in function <init_worker_by_lua:43>
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by shashiranjan84** [comment]
You would need to set the Kong environment variables,

`KONG_DATABASE=cassandra kong restart`

Also please make sure Cassandra DB is running .

**Comment by peterbsmith2** [comment]
How does that fix the underlying issue? Your instructions DO work though, thanks!

**Comment by shashiranjan84** [comment]
Kong default DB is Postgres, so we have to update configuration file or add environment variable to override the default setting.

**Comment by peterbsmith2** [comment]
Also, I needed to `cp` the kong.conf file into `/etc/kong/kong.conf` for this to work

**Comment by shashiranjan84** [comment]
You don't need to if you just set the environment variable.  But you can always update the config and save it /etc/kong/kong.conf.

Here is the guide how to configure Kong

https://getkong.org/docs/0.9.x/configuration/
