### ISSUE TITLE
[Feature Request] Database outage resiliency  

### ISSUE THREAD

**Issue by kamran-rahmani** [Mashape/kong#1791]
I did a test today, looks like Kong completely stops working if the db is not available (returning error for the API call), and it will continue working when it's back -this was on Postgres. As all the nodes cache the configuration and endpoints in memory, It would be great if Kong could continue to work maybe with a limited set of functionality - like disabling rate limiting temporarily until the db is back as it needs to write to the database.

Is anyone working on something like this? Is there any plan to do this improvement?

**Comment by Tieske** [comment]
have you tried the `fault_tolerant` option? see https://getkong.org/plugins/rate-limiting/

**Comment by kamran-rahmani** [comment]
Thanks for the pointer. I tested without that plugin enabled and the api call failed. Looks like Kong itself is not resilient in this case. This is what it returns when I bring down the db:

{"message":"An unexpected error occurred"}

**Comment by thefosk** [comment]
@kamran-rahmani can you please provide the steps to replicate your issue? In my tests Kong the proxy port of Kong (`8000`) keeps working even if the DB is down. The Admin API won't work, but that's expected, and the proxy port will only work if you have already requested the API before the DB interruption, not on a brand new consumption (because Kong needs to have a chance to cache the data in memory on the first request).

**Comment by kamran-rahmani** [comment]
I run it using docker on my machine (Mac) as it's described here:
https://getkong.org/install/docker/

Then call an API and it works (endpoint should be cached at this point). Then manually stop the Postgres container, and call the API again and get that error. Start the Postgres container again and after few second things continue to work.

**Comment by p0pr0ck5** [comment]
@kamran-rahmani are you able to reproduce this issue on the most recent version of kong (0.10.2)? Are you able to see any useful information in the error log? What plugins do you have configured on the API in question? The more details the better we can investigate this claim. Thanks!

**Comment by p0pr0ck5** [comment]
Closing as stale, no response provided to request for more info. Please feel free to reopen if there are still pending questions or more information you can provide. Thank you!
