### ISSUE TITLE
The key-auth plugin adds the key parameter authentication to the post request and does not take effect

### ISSUE THREAD

**Issue by ti-yoyo** [Mashape/kong#1795]
The key-auth plug-in adds the key authentication to the post request and does not take effect. I do not want to add the key parameter in the http header. What should I do?

**Comment by thefosk** [comment]
@ti-yoyo the key authentication plugin doesn't add anything to the request - I am not sure what's the issue you are experiencing.

**Comment by ti-yoyo** [comment]
If the key authentication plug-in does not add anything to the request, then the apikey needs to be added to the http header, for example
Curl http: // kong: 8000 / {api path} -H 'apikey: <some_key>

We now want to add the apikey parameter to the get or post request, and if the apikey value does not exist in the get parameter, then the post is evaluated.

Get
Curl http: // kong: 8000 / {api path}? Apikey = xxx

Post
Curl --data "apikey = xxx" http: // kong: 8000 / {api path}

**Comment by ti-yoyo** [comment]
@thefosk 

Now we want to count the frequency of each customer request for each interface in the consumer dimension, but do not want the customer to change the code. We have an interface for each enterpriseId parameter, if key-auth can access the post request parameters will be able to solve our current problem.

**Comment by thibaultcha** [comment]
Sorry, the key-auth plugin does not look for the key in the request body and that is by design. You will need to pass it into the querystring, a header, or implement your own solution.

**Comment by ti-yoyo** [comment]
I now amend the source code which can be found in the body of the corresponding documents?

**Comment by ti-yoyo** [comment]
I modified the key-auth / handler.lua source code to start the old failure.
