### ISSUE TITLE
How to retrieve access token

### ISSUE THREAD

**Issue by acpower7** [Mashape/kong#1799]
I am using Kong as an API gateway for my web application, I am using the Oauth2 plugin. I have a question regarding the documentation, step 8:

`The client appication will take it from here, and will continue the flow with Kong with no other interaction with your web application. Like exchaging the authorization code for an access token if it's an Authorization Code Grant flow
`

My question how exactly do you retrieve the access token once you have the authorization code once you've been redirected to the redirect_uri?

ps you have some spelling errors in the docs, there is a typo with the word "application" and "exchanging" as seen in the [above](https://getkong.org/plugins/oauth2-authentication/) paragraph. thanks

**Comment by thefosk** [comment]
@acpower7 you need to flow the regular OAuth 2.0 for exchanging an authorization code with a token.
