### ISSUE TITLE
admin API "/plugins/schema/key-auth"  got a wrong shema

### ISSUE THREAD

**Issue by koolay** [Mashape/kong#1801]
The default value of filed `key_names` should be "apikey".

```
{
"fields": {
"key_names": {
"type": "array",
"required": true,
"default": "function"
},
"hide_credentials": {
"type": "boolean",
"default": false
}
},
"no_consumer": true
}
```

**Comment by thibaultcha** [comment]
I remember this being by design back in the day because the default value was a function and I think we didn't want to run it for a reason I forgot, but it can probably be improved as of now. PRs welcome!
