### ISSUE TITLE
Dynamic SSL global plugin doesn't load unless host rule is matched

### ISSUE THREAD

**Issue by jaygorrell** [Mashape/kong#1803]
### Summary

First off, the documentation is a bit unclear. If you look at the [Dynamic SSL](https://getkong.org/plugins/dynamic-ssl/) plugin page it mentions the global rule via environment variables, followed by the api-specific configuration, then finally _another_ global setting using the top-level plugins endpoint. I'm going to refer to these as "Global Environment", "Plugin", and "Global Plugin" for clarity.

Given that, my expectation was that the Global Environment and Global Plugin options are equivalent. I've been using the Global Environment method with no problems but I now need to apply a certificate to a different domain name coming in, leading me to believe that the Global Environment method squashes everything else and perhaps the Global Plugin option provides more flexibility, allowing for overrides.

Trying out that line of thought, I killed off the Global Environment certificate and moved it to a Global Plugin, with my new domain being an API level SSL Plugin entry. Makes sense, but unfortunately this didn't work either. Interestingly, the API-level override *did* work, but the defaults did not. It's probably worth noting here that the default routes I use are request paths while the override is a request host.

My best guess here is that the Global Plugin method still requires a host match to function correctly... is that true? If so, how can I have a default certificate in place with request host overrides for a different certificate? It would make sense to me that a global plugin would not need to match paths *OR* that the environment variable approach would not override API-level SSL plugins.

### Steps To Reproduce

1. Apply a certificate to global plugins
2. Define API routes using request paths
3. Define another API mapped by request host with an SSL plugin for it's own certificate
4. See that the global plugin does not work for the request path APIs.
5. Enable Global Environment SSL with environment variables
6. See that the API-specific plugin with host matching no longer loads the correct SSL certificate

### Additional Details & Logs

- Kong version 0.9.0

**Comment by jaygorrell** [comment]
I'm starting to think I had some incorrect assumptions about the problem here. I've tried dropping the Global Environment and Global Plugin both in favor of being explicit. This has resulted in only APIs defined by a `request_host` receiving a certificate, which at least is a much more isolated problem.

In the simplest terms, it seems that the SSL plugin on a specific API does not apply when request_path is used instead of request_host.

**Comment by thefosk** [comment]
> it seems that the SSL plugin on a specific API does not apply when request_path is used instead of request_host.

This is correct, it can only apply to APIs that have been specified with a `request_host`, as stated in the docs at https://getkong.org/plugins/dynamic-ssl/

The reason is the SSL handshake happens before the actual request is being sent, and the only value that's being shared with the server is the Host being request (thanks to the [TLS/SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) extension). 

The actual path/endpoint is part of the real HTTP request, not part of the SSL handshake, but that is only visible after the SSL handshake has been terminated and an SSL certificate already provisioned.

**Comment by jaygorrell** [comment]
Thanks @thefosk. That covers the api-specific option, but what about the non api-specific options -- either environment variables OR the plugin itself on the root config. Can that not serve a default certificate to *all* requests that don't match a request_host mapping -- then have request_host matches serve a different certificatate?

That would be the ideal. A default certificate for everything (including request_path matches), but the ability to set a specific cert for request_host matches on those APIs.

I also wouldn't mind specifying the host in addition to the path for all APIs, but that's not an option due to #845 as I understand it.

**Comment by jaygorrell** [comment]
Apologies for the double-post but I think I understand the implementation and what I'd like to see a little better now. If the API plugin simply matches on `request_host` only, it's likely that the global plugin follows that same rule. I expected it to be a global default rather than a globally applied API plugin, if that makes sense.

My primary ask with this issue, then, would be that if a cert is specified with the environment variables at runtime, that `request_host` matches from the plugins would override that.

**Comment by jaygorrell** [comment]
Triple post! :(

After all of this, I went back to the environment variable solution with API-specific plugins -- had the same problem but restarting Kong (containers in this case), things appear to be working. Is there something with the dynamic SSL plugin that may require a process bounce?

Again, apologies for the multiple posts.

**Comment by thefosk** [comment]
> Is there something with the dynamic SSL plugin that may require a process bounce?

That shouldn't be required. I will need to double check.
