### ISSUE TITLE
Consumers: mapping Kong with users in existing database

### ISSUE THREAD

**Issue by ozitraveller** [Mashape/kong#1805]
How do I map kong to users in an existing database?

**Comment by thefosk** [comment]
You can populate the `custom_id` field when creating a consumer on Kong. The `custom_id` can be any value, like the ID of your user in another database.

**Comment by wanderleisouza** [comment]
Can I use an already existing Consumer table in a distinct database instead of Kong Postgres DB? (eg. a pre-existing Consumer/User table in my legacy Oracle database)
