### ISSUE TITLE
[Question] Disable auth plugin for a resource inside a service.

### ISSUE THREAD

**Issue by mohamedrez** [Mashape/kong#1807]
I have a service that serves public and protected resources, when I enable an auth plugin for this services all resources become protected. Is there a way to exclude some paths ?

**Comment by Tieske** [comment]
define as 2 api's one with the other without auth.

**Comment by mohamedrez** [comment]
With that do I have to add a security layer myself inside the service that checks from where the request is coming to protect the the private parts inside the public api?

**Comment by thefosk** [comment]
@mohamedrez I would setup a firewall rule that only accepts connections from your Kong cluster. Then on Kong you can have different APIs, with different `request_path` properties, and each one of them can have different plugins.

As long as your service only allows requests through Kong, then you can make the assumption that Kong has already validated the request with no additional checks on your side.

**Comment by thibaultcha** [comment]
I think this has been answered. Disabling authentication on custom resources of a service is in our TODO list, but not doable at the moment. Closing this.

**Comment by thibaultcha** [comment]
With the separation of the API entity in Services and Routes since 0.13, we consider this resolved. See more details in this blog post: https://konghq.com/blog/kong-ce-0-13-0-released/
