### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by geostant** [Mashape/kong#1808]
### Summary

Setting an option to redirect kong's 401 response with another API or a default unprotected API

### Steps To Reproduce

1. Enable JWT on your API
2. Send a request with a proper token and get your requested API
3. Send a request with invalid token (or missing) and get a redirection to another API or default API instead of 401

That would be really awesome,
in example - user authentication in front of your web application.

When not providing a token, they will be redirected to a login page.

**Comment by Tieske** [comment]
doubles with/extension of #972
