### ISSUE TITLE
kong start -c does not work?

### ISSUE THREAD

**Issue by HenryChelsea** [Mashape/kong#1811]
### Summary

As you can see. Kong does not start with '/path/to/kong.conf'. kong uses default config file '/etc/kong/kong.conf'?
Thanks all.

### Steps To Reproduce

1. kong start -c /path/to/kong.conf (-conf /path/to/kong.conf )

### Additional Details & Logs

- Kong version (`9.2`)

- Kong debug-level startup logs (`$ kong start --vv`)

[token@localhost etc]$ kong start -c /home/token/pin_plugins/kong/pin_spec/kong.conf --v

2016/11/11 06:08:10 [verbose] Kong: 0.9.4
2016/11/11 06:08:10 [verbose] no config file found at /etc/kong.conf
2016/11/11 06:08:10 [verbose] reading config file at /etc/kong/kong.conf
2016/11/11 06:08:10 [verbose] prefix in use: /home/token/kong
2016/11/11 06:08:10 [verbose] preparing nginx prefix directory at /home/token/kong
2016/11/11 06:08:10 [verbose] saving serf identifier to /home/token/kong/serf/serf.id
2016/11/11 06:08:10 [verbose] saving serf shell script handler to /home/token/kong/serf/serf_event.sh
2016/11/11 06:08:10 [verbose] SSL enabled, no custom certificate set: using default certificate
2016/11/11 06:08:10 [verbose] default SSL certificate found at /home/token/kong/ssl/kong-default.crt
2016/11/11 06:08:10 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
2016/11/11 06:08:10 [verbose] running datastore migrations
2016/11/11 06:08:10 [verbose] migrations up to date
2016/11/11 06:08:10 [verbose] dnsmasq not running, deleting /home/token/kong/pids/dnsmasq.pid
2016/11/11 06:08:10 [verbose] serf agent not running, deleting /home/token/kong/pids/serf.pid
2016/11/11 06:08:10 [verbose] waiting for serf agent to be running
2016/11/11 06:08:10 [verbose] serf agent started
2016/11/11 06:08:10 [verbose] auto-joining serf cluster
2016/11/11 06:08:10 [verbose] no other nodes found in the cluster
2016/11/11 06:08:10 [verbose] registering serf node in datastore
2016/11/11 06:08:10 [verbose] cluster joined and node registered in datastore
2016/11/11 06:08:10 [info] Kong started

- centos 7.0

**Comment by thibaultcha** [comment]
Please try with a more recent version of Kong such as 0.9.5. I believe this is due to #1681. Feel free to reopen if you are still experiencing this.

**Comment by HenryChelsea** [comment]
@thibaultcha 
Thanks for your great works.
I have checkout to branch "next" and it works well. Hope you can merge to master (0.9.5).(Maybe you need to check).
Thanks !
