### ISSUE TITLE
[feature-request] Forward JWT token inside upstream header

### ISSUE THREAD

**Issue by gendigbadig** [Mashape/kong#1815]
### Summary

Forward JWT token inside upstream header. So upstream can also read the token for other purpose. 

### Steps To Reproduce

1. Install JWT plugin on API
2. Call API with jwt token
3. Send token to upstream via header, like sending consumer username

**Comment by thibaultcha** [comment]
Do you experience the token not being sent to the upstream service? Because that is the intended behavior, as asserted by this test:
https://github.com/Mashape/kong/blob/master/spec/03-plugins/06-jwt/03-access_spec.lua#L132-L147

**Comment by thibaultcha** [comment]
There is also a mention of such a feature in the documentation:
https://getkong.org/plugins/jwt/

(See the "Note:" part in the "send a request" section).

**Comment by gendigbadig** [comment]
no, but i think its cool to read all the payload from jwt. so i can add some field to payload and read it from upstream service :)

**Comment by gendigbadig** [comment]
oh i miss that part, thanks :)
