### ISSUE TITLE
Request path url containing NULL (%00) character results in OpenResty response (400 HTTP Response code)

### ISSUE THREAD

**Issue by marcubus** [Mashape/kong#1816]
### Summary

A request path which contains an encoded NULL (%00) character results in Kong returning an HTTP 400 Response code with an HTML payload.

Example:
`$ curl -i -X GET   --url http://localhost:8000/%00   --header 'Host: mockbin.com'`

Response:
```
HTTP/1.1 400 Bad Request
Server: openresty/1.9.15.1
Date: Sun, 13 Nov 2016 22:33:49 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 179
Connection: close

<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>openresty/1.9.15.1</center>
</body>
</html>
```

### Steps To Reproduce

1. Configure upstream API:
`$ curl -i -X POST   --url http://localhost:8001/apis/   --data 'name=mockbin'   --data 'upstream_url=http://mockbin.com/'   --data 'request_host=mockbin.com'`
2. Perform a GET request from upstream API with `%00` in the URL
`$ curl -i -X GET   --url http://localhost:8000/%00   --header 'Host: mockbin.com'`

### Additional Details & Logs

- Kong version: `0.9.2`
- Kong start up logs: [kong-start.txt](https://github.com/Mashape/kong/files/588146/kong-start.txt)
- Kong error logs - this request doesn't spawn any logs
- Operating System
```
vagrant@vagrant-ubuntu-trusty-64:/usr/local/kong/logs$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-96-generic #143-Ubuntu SMP Mon Aug 29 20:15:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thibaultcha** [comment]
Hi,

Thanks for reporting. Have you tried doing the same request on a raw OpenResty, or even better, Nginx instance?

**Comment by marcubus** [comment]
Hey @thibaultcha, I've just tried a couple of requests to an unconfigured nginx instance - details below.

``%00`` in the path results in a 400.
```
vagrant@vagrant-ubuntu-trusty-64:~$ curl -v http://10.0.2.15/%00123
* Hostname was NOT found in DNS cache
*   Trying 10.0.2.15...
* Connected to 10.0.2.15 (10.0.2.15) port 80 (#0)
> GET /%00123 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 10.0.2.15
> Accept: */*
>
< HTTP/1.1 400 Bad Request
* Server nginx/1.4.6 (Ubuntu) is not blacklisted
< Server: nginx/1.4.6 (Ubuntu)
< Date: Thu, 17 Nov 2016 23:33:24 GMT
< Content-Type: text/html
< Content-Length: 181
< Connection: close
<
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
* Closing connection 0
```

``%01`` in the path results in 404 (expected).
```
vagrant@vagrant-ubuntu-trusty-64:~$ curl -v http://10.0.2.15/%01123
* Hostname was NOT found in DNS cache
*   Trying 10.0.2.15...
* Connected to 10.0.2.15 (10.0.2.15) port 80 (#0)
> GET /%01123 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 10.0.2.15
> Accept: */*
>
< HTTP/1.1 404 Not Found
* Server nginx/1.4.6 (Ubuntu) is not blacklisted
< Server: nginx/1.4.6 (Ubuntu)
< Date: Thu, 17 Nov 2016 23:34:03 GMT
< Content-Type: text/html
< Content-Length: 177
< Connection: keep-alive
<
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
* Connection #0 to host 10.0.2.15 left intact
```

**Comment by thibaultcha** [comment]
It seems to me this behavior is then due to Nginx, and not Kong itself. It does make sense for Nginx to return HTTP 400 since I believe null characters are not valid in a URI (maybe check the related RFC (3986?) about that).

**Comment by marcubus** [comment]
Hi @thibaultcha, my view is the HTTP 400 is correct - the URL is invalid.

What my security team have been reporting/complaining about is that they get a response from Kong with the OpenResty version reported in the 400 payload. Ideally any underlying implementation details are not exposed in response payloads - even in the case of a valid error (i.e in this case).

**Comment by thibaultcha** [comment]
Feel free to tune the nginx configuration to hide any headers that you'd like. 

Should we close this?

**Comment by marcubus** [comment]
This solves part of the problem. My remaining concern is that the HTML reponse payload also contains details about the OpenResty version.

There was a [recent pull request](https://github.com/Mashape/kong/commit/f84216ba01886439efc6000d8236246a6029fbe5) for #1552 and #1553 which altered which codes the Kong error handler responded to. These issues also exposed similar OpenResty version info in the header and response body. We had originally thought the fix for these issues would have also resolved this issue - but I can see the list does not contain '400' for the 4xx response code set.

I'll have a go at altering the list locally and see if it makes a difference to what I get back in from Kong.

**Comment by marcubus** [comment]
@thibaultcha I did manage to get the behavior I was expecting by adding 400 to the list of codes handled by the kong error handler, like the pull request for #1552 and #1553. Do you want be to submit a pull request for this?

Patch:
```
$ git diff
diff --git a/kong/core/error_handlers.lua b/kong/core/error_handlers.lua
index 751ee68..ce1be11 100644
--- a/kong/core/error_handlers.lua
+++ b/kong/core/error_handlers.lua
@@ -12,6 +12,7 @@ local xml_template = '<?xml version="1.0" encoding="UTF-8"?>\n<error><message>%s
 local html_template = '<html><head><title>Kong Error</title></head><body><h1>Kong Error</h1><p>%s.</p></body></html>'

 local BODIES = {
+  s400 = "Bad request",
   s404 = "Not found",
   s408 = "Request timeout",
   s411 = "Length required",
@@ -55,4 +56,4 @@ return function(ngx)
   ngx.header["Server"] = SERVER_HEADER
   ngx.header["Content-Type"] = content_type
   ngx.say(format(template, message))
-end
\ No newline at end of file
+end
diff --git a/kong/templates/nginx_kong.lua b/kong/templates/nginx_kong.lua
index 6454e91..2fd44f7 100644
--- a/kong/templates/nginx_kong.lua
+++ b/kong/templates/nginx_kong.lua
@@ -58,7 +58,7 @@ init_worker_by_lua_block {
 server {
     server_name kong;
     listen ${{PROXY_LISTEN}};
-    error_page 404 408 411 412 413 414 417 /kong_error_handler;
+    error_page 400 404 408 411 412 413 414 417 /kong_error_handler;
     error_page 500 502 503 504 /kong_error_handler;

 > if ssl then
```

Behavior after patch:
```
vagrant@vagrant-ubuntu-trusty-64:/usr/local/kong$ curl http://localhost:8000/%00 -vvvv
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /%00 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8000
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Date: Tue, 22 Nov 2016 04:22:24 GMT
< Content-Type: text/plain; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: close
* Server kong/0.9.2 is not blacklisted
< Server: kong/0.9.2
<
Bad request
* Closing connection 0
```

**Comment by bungle** [comment]
Hiding Kong `Server` and `Via` response headers is implemented in #2259.

**Comment by p0pr0ck5** [comment]
@marcubus thanks for the initial diff, this has been merged in. Closing as this seems to be resolved now.

**Comment by marcubus** [comment]
That's great @p0pr0ck5 - thanks for merging the patch.
