### ISSUE TITLE
kongserver and    consul/etcd

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1820]
I now have a docker environment kong, need to achieve and etcd or consul update discovery (registrator) found the container api, but I do not know how kong and etcd, consul interactive api information (delete, change, add)

**Comment by sashahilton00** [comment]
Please take a moment to read over that jumble of words, imagine you are not the one who wrote the question, then try and work out what it is that is being asked. When done with that, please take a moment to reorganise the question into something intelligible.

**Comment by huyifanstar** [comment]
Does kong have auto-discover, register components?

**Comment by sashahilton00** [comment]
No, you would need to have something like registrator running, which will auto register docker containers with Consul, then you could point Kong at the Consul DNS server which will then connect Kong to the relevant instances.

**Comment by huyifanstar** [comment]
Ability to automatically update health APIs?  There are no plug-ins to do it? It is best to help manual ! thanks

**Comment by sashahilton00** [comment]
Registrator will check the health of the instances and remove them from the pool if they are failing. Read about it here: http://gliderlabs.com/registrator/latest/user/backends/#consul

**Comment by huyifanstar** [comment]
I also used the Registrator, but the Registrar did not seem to be able to collect the host ip and port (container port and host port inconsistent)

**Comment by thefosk** [comment]
We have something similar running on our official Docker Compose stack, that leverages [Container Pilot](https://www.joyent.com/containerpilot) instead of Registrator.

You can take a look at it: https://github.com/Mashape/docker-kong/tree/master/compose

**Comment by huyifanstar** [comment]
@thefosk   Container Pilot I have no use; Registrator not recommended? Docker-kong-compose able to automatically update kong from consul api?

**Comment by huyifanstar** [comment]
Nginx role is to do load balancing kongserver?

**Comment by huyifanstar** [comment]
Compose up-d later, apis did not see any api record ah, but consul ui can see the record.  api has been registered to consul, but not updated to kong

**Comment by huyifanstar** [comment]
docker logs c6bb66b449cf 
2016/11/17 08:36:59 Unexpected response code: 500 (CheckID does not have associated TTL)
Service not registered, registering...
2016/11/17 08:36:59 Unexpected response code: 500 (CheckID does not have associated TTL)
Service not registered, registering...
2016/11/17 08:36:59 Unexpected response code: 500 (CheckID does not have associated TTL)
Service not registered, registering...

**Comment by thefosk** [comment]
@huyifanstar this questions are not Kong-specific, rather more broad questions on how Registrator or Container Pilot work. This is not the right place to ask this questions. If you want to take it from here, know that the official Docker Compose linked above properly adds Kong nodes behind the load balancer.

**Comment by thefosk** [comment]
But again, if you feel like the existing documentation and material is not enough for you, and you'd like more extensive support and assistance, check out the [Enterprise subscription](mashape.com/enterprise) which can allocate more extensive support resources for your case.

That said, both Container Pilot and Registrator work with Kong, it's up to you. A working example of Kong + Consul behind a LB is available in the [official Docker Compose stack](https://github.com/Mashape/docker-kong/tree/master/compose). You can use that stack to run a scalable Kong deployment, that you can easily scale with commands like `docker-compose scale kong=3`.

I would reccomend first understanding how Registrator and Container Pilot work.

**Comment by huyifanstar** [comment]
OK ，Consul + registrator has no problem, and now kong can not get from the consul server node, the latest available API. I saw the issue said kong need to load dns module to achieve?

**Comment by huyifanstar** [comment]
OK ，Consul + registrator has no problem, and now kong can not get from the consul server node, the latest available API. I saw the issue said kong need to load dns module to achieve?

**Comment by phuthinh2202** [comment]
I think:
 - registrator still used to register a service instance with name service, ip address and port to Consul.
 - Write a little code which can query to Consul, list service and register to Kong when something change at Consul.
 - Use consul-template watch Consul and execute your code which register to Kong. :+1:
