### ISSUE TITLE
must only contain alphanumeric and '., -, _, ~, /, %' characters

### ISSUE THREAD

**Issue by ti-yoyo** [Mashape/kong#1822]
Request path: /interfaceAction/cdrIbInterface!listCdrIb.action， Is there any good solution?

**Comment by Tieske** [comment]
very cryptic. What is the full message you get?

**Comment by ti-yoyo** [comment]
When adding an api, the request path can not include the! Special symbol  Request path: /interfaceAction/cdrIbInterface!listCdrIb.action

**Comment by Tieske** [comment]
iirc think the `!` is a reserved character so you'd have to percent encode it

**Comment by thibaultcha** [comment]
This is by design indeed, in regard to RFC 3986's set of reserved characters. Please try to follow @Tieske's suggestion.
