### ISSUE TITLE
Kong overwrites X-Forwarded-Proto header when already present

### ISSUE THREAD

**Issue by DonMartin76** [Mashape/kong#1823]
### Summary

In case you use some other means of doing SSL termination than Kong itself, and that layer introduces the `X-Forwarded-Proto: https` header, Kong will still, by the default configuration, overwrite that header with `X-Forwarded-Proto: $scheme`, whereas `$scheme` is `http`.

This makes it almost impossible to e.g. proxy a website using node.js `express-session` session handling, as it relies on `X-Forwarded-Proto: https` to decide whether it allows Cookie retrieval or not.

It also makes it difficult to create HAL type APIs which create hyperlinks in the responses, where the hyperlinks should be fully qualified and thus include both the correct front facing host, protocol and prefix.

### Steps To Reproduce

1. Proxy Kong via e.g. `HAproxy` (which introduces `X-Forwarded-Proto: https` by default)

### Additional Details & Logs

- Kong version 0.9.4
- Kong configuration (registered APIs/Plugins & configuration file): All defaults
- Operating System: Linux/Docker

### Expected behaviour

Kong, IMHO, should not change those headers in case they are already present.

Are there (simple) workarounds?

**Comment by thibaultcha** [comment]
Hi,

Since that behavior comes from the Kong nginx configuration (https://github.com/Mashape/kong/blob/master/kong/templates/nginx_kong.lua#L84), I believe the simplest workaround as of now would be to use a custom nginx configuration. Documentation on the matter can be found at:
https://getkong.org/docs/0.9.x/configuration/#custom-nginx-configuration

Note: since this is part of the *Kong* Nginx configuration, you would need to create a main `nginx.conf` file with the contents of [templates/nginx.lua](https://github.com/Mashape/kong/blob/master/kong/templates/nginx.lua), and inline the contents of [templates/nginx_kong.lua](https://github.com/Mashape/kong/blob/master/kong/templates/nginx_kong.lua) )without the Lua part, of course). You can then make any modification you'd like to the Nginx configuration used by Kong.

**Comment by thibaultcha** [comment]
As a more definitive fix, this logic could be handled in the Lua code. 2 solutions:
- set `$scheme` with `set_by_lua`, which will set a value or re-use the existing one if present
- use the `ngx.req.get_headers()` and `ngx.req.set_header()` API, which could be a bit more costly? Not sure.

**Comment by rogoman** [comment]
One needs to be careful when implementing this. It should be a switchable option to accept the incoming `X-Forwarded-Proto` header. If you have another load balancer before Kong and you trust it, then sure - honoring the passed header is ok. But if Kong is your edge server then it's potentially dangerous to trust `X-Forwarded-Proto` in the incoming requests.

**Comment by bungle** [comment]
I have used this in my reverse proxies:

```nginx
map $http_x_forwarded_proto $x_forwarded_proto {
    default $http_x_forwarded_proto;
    '' $scheme;
}

map $http_x_forwarded_port $x_forwarded_port {
    default $http_x_forwarded_port;
    '' $server_port; 
}

map $http_x_forwarded_ssl $x_forwarded_ssl {
    default $http_x_forwarded_ssl;
    '' $https; 
}
```

And in proxy configs:

```nginx
proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
proxy_set_header    X-Forwarded-Proto $x_forwarded_proto;
proxy_set_header    X-Forwarded-Port  $x_forwarded_port;
proxy_set_header    X-Forwarded-Ssl   $x_forwarded_ssl;
````

I'm not sure if this would work for Kong, so I just put it here as an example that could be valuable (or not).

**Comment by thibaultcha** [comment]
@bungle Thanks! I think we will certainly use this :)

> One needs to be careful when implementing this. It should be a switchable option to accept the incoming X-Forwarded-Proto header. If you have another reverse proxy before Kong and you trust it, then sure - honoring the passed header is ok. But if Kong is your edge server then it's potentially dangerous to trust X-Forwarded-Proto in the incoming requests.

@rogoman This is very much my concern as well. There will be a configuration option for this behavior.

**Comment by thibaultcha** [comment]
Moved to @2202. Thanks!
