### ISSUE TITLE
Will kongserver how to achieve dynamic api update with the etcd or consul

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1825]
Now I have the latest docker environment and a kong container that needs to be updated automatically with the etcd or consul components. Valid API functionality, I am considering using consul, what should I do now? Or kong recommended and docker with what to find and register components

**Comment by sashahilton00** [comment]
I believe this has been answered here: https://github.com/Mashape/kong/issues/1095. In short, point Kong's DNS to the server provided by Consul, or if you have multiple Consul instances, Kong -> Load Balancer -> Consul. Then just register your services on Consul as normal.

**Comment by thefosk** [comment]
If you are running Kong in a Docker environment, please take some time to look at the official Docker Compose distribution which already registers Kong nodes automatically to both Consul and the LB: https://github.com/Mashape/docker-kong/tree/master/compose

**Comment by huyifanstar** [comment]
Nginx role is to do load balancing kongserver?
