### ISSUE TITLE
 kongserver and consul

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1829]
1 docker-compose kong , Nginx role is to do load balancing kongserver?
2 Compose up-d later, apis did not see any api record ah, but consul ui can see the record. api has been registered to consul, but not updated to kong
3 docker logs c6bb66b449cf 
2016/11/17 08:36:59 Unexpected response code: 500 (CheckID does not have associated TTL)
Service not registered, registering...
2016/11/17 08:36:59 Unexpected response code: 500 (CheckID does not have associated TTL)
Service not registered, registering...
2016/11/17 08:36:59 Unexpected response code: 500 (CheckID does not have associated TTL)
Service not registered, registering...

**Comment by thibaultcha** [comment]
What is your question? Why do you expect Kong to work with Consul? Please refine.

**Comment by thefosk** [comment]
[This](https://github.com/Mashape/docker-kong/blob/master/compose/docker-compose.yml#L23) is the LB that sits in front of your [Kong nodes](https://github.com/Mashape/docker-kong/blob/master/compose/docker-compose.yml#L54).

Checkout that repo and execute:

```shell
$ docker-compose up # Starts the compose
$ docker-compose scale kong=3 # Scales Kong to 3 nodes
$ curl 127.0.0.1:8001 # Makes a request to Kong, through the LB
```

Give it some seconds to allow the nodes to register with Kong and nginx.
