### ISSUE TITLE
Which authentication plugin should I use?

### ISSUE THREAD

**Issue by mytototo** [Mashape/kong#1830]
Hey,

I want to use Kong as API gateway for my services. Every services can be requested through a front-end website, available for my consumers.

Which authentication plugin should I use so both the services and the front-end are secure?

Thanks.

**Comment by DonMartin76** [comment]
Depends a lot on a lot of things. E.g., what type of web app is your front end? SPA? Classical stateful web site? If yes, a simple `key-auth` might be enough. But it's not possible to tell with the description you give here unfortunately.

E.g., who is requesting what? Are you talking about "requesting an API subscription", or what does "request through a front end" mean to you?

You can use Kong for many different things, but I would need some more details to be able to give some kind of recommendation.

**Comment by mytototo** [comment]
Hey @DonMartin76,

Thanks for your feedback. More simply put, the goal is to secure the requests between a front-end application where consumers will be able to make some calls to the API proxied by Kong. Consumers will be registered on the website and they have the possibilities, via the front-end, to trigger some services through Kong. How can I secure those requests that come from the front-end?

**Comment by DonMartin76** [comment]
Sorry, that did not really help. I think you have to flesh it out a little. You have multiple types of APIs here, and I still don't get what you are trying to achieve? Are you planning to implement an API portal? Or do you just want to secure access to backend APIs? 

* What type of front end application do you have (that's actually really important to know to be able to advise on this)?
* What's a "Consumer" for you?
* What does "registering a consumer" mean to you? (the term "consumer" has a special meaning in Kong terms, is this what you mean?)
* What kind of "service" do you want to "trigger" via Kong?
* Do you have an end user data store you need to integrate with?

**Comment by mytototo** [comment]
Sorry about that and thanks for the questions.

- The front-end application for the portal will be a Node.js / Angular application. It's used as an admin panel for the Kong gateway where we can manage plugin, consumers and APIs.
- A consumer is a registered project allowed to request the Kong gateway. So a consumer can be a Node.js application like an iOS application or even a React application. Any kind of applications.
- Registering a consumer is actually add an allowed project to request the Kong gateway and therefore request the registered APIs.
- Since consumers are actually projects, our clients will make any kind of front-end applications to request the registered APIs. It's not up to us.

**Comment by DonMartin76** [comment]
May I point you to this: http://wicked.haufe.io, https://github.com/Haufe-Lexware/wicked.haufe.io. That's our open source API Portal doing quite that, based on Kong, node.js and docker. It's mature enough that it might serve you quite well. Example portal: https://wicked-demo.haufe.io.

**Comment by mytototo** [comment]
This is a great example, thanks a lot for the link @DonMartin76. Also, thanks for the details, I wasn't sure about ACL and CORS but CORS are obviously useless here.
