### ISSUE TITLE
Custom configuration file is not loaded if one exist on the default paths

### ISSUE THREAD

**Issue by mihaur** [Mashape/kong#1831]
### Summary

Upon starting kong with custom configuration using --conf, it first tries to read configuration files on the default paths (/etc/kong.conf, /etc/kong/kong.conf). If one is found. than it reads it instead of a custom one. 

### Steps To Reproduce
1. have a valid configuration file on default path
2. have a valid configuration file on custom path
3. cd to custom path
4. kong compile --conf ./kong.conf
=> one on the default path is read

### Additional Details & Logs

- Kong version 0.9.5
With configuration file at /etc/kong/kong.conf
`$ kong compile --conf ./kong.conf`
- Kong debug-level startup logs (`$ kong start --vv`)
```
2016/11/18 09:41:49 [verbose] no config file found at /etc/kong.conf
2016/11/18 09:41:49 [verbose] reading config file at /etc/kong/kong.conf
```
Without configuration file at /etc/kong/kong.conf
`$ kong compile --conf ./kong.conf`
```
2016/11/18 09:34:30 [verbose] no config file found at /etc/kong.conf
2016/11/18 09:34:30 [verbose] no config file found at /etc/kong/kong.conf
2016/11/18 09:34:30 [verbose] reading config file at ./kong.conf
```

**Comment by thibaultcha** [comment]
Thanks for reporting this. It was taken care of in #1681 but wasn't released in a 0.9.x release yet. This should now be taken care of by 0.9.6:
    https://github.com/Mashape/kong/releases/tag/0.9.6

You can install 0.9.6 if you have a previous installation of Kong via:

```
$ luarocks install kong 0.9.6
```

Or via Homebrew. The other distribution packages will be updated shortly.
