### ISSUE TITLE
Admin API: attempt to index a userdata value

### ISSUE THREAD

**Issue by ronan-skyscanner** [Mashape/kong#1840]
### Summary
We have found an issue when making requests to the Kong admin API:

```2016/11/22 11:00:33 [error] 14161#0: *1068436 lua entry thread aborted: runtime error: content_by_lua(nginx-kong.conf:107):9: attempt to index a userdata value
stack traceback:
coroutine 0:
	content_by_lua(nginx-kong.conf:107): in function <content_by_lua(nginx-kong.conf:107):1>, client: 127.0.0.1, server: kong_admin, request: "POST /cluster/events/ HTTP/1.1", host: "127.0.0.1:8001"
```
The matching nginx.conf and nginx-kong.conf can be seen here: https://gist.github.com/ronan-skyscanner/741da62c0c2d6d7d8186383db48b1809#file-nginx-kong-conf

This error appears inconsistently on our servers (all the same specs and deployed app), and once it has appeared on one, all requests to the admin API return a 500 error.

We have a plugin creating some custom admin API routes, which can be seen here:
https://gist.github.com/ronan-skyscanner/741da62c0c2d6d7d8186383db48b1809#file-api-lua

Debugging has been made difficult because running a kong reload seems to solve the problem.

We run Kong version 0.9.5 on Amazon Linux, with various custom plugins.

**Comment by Tieske** [comment]
First glance;

What I can make of this is; `nginx-kong.conf:107` means the directive on line (or in this case ending on line) 107, which is the Lua code. The additional `:1` means the error appears on the first line of that block, which is the opening `{`.

So that's really odd.

**Comment by Tieske** [comment]
nope, the above info isn't correct, you skipped the initial line.

according to your [gitter message](https://gitter.im/Mashape/kong?at=583422e87f83e6c9771add4c), it's line `:9`, which is;

```lua
require('lapis').serve('kong.api')
```

**Comment by Tieske** [comment]
considering the error; `attempt to index a userdata value` 

it appears that the result of `require('lapis')` is a userdata. Which is wrong as that should be a table, see [this lapis code](https://github.com/leafo/lapis/blob/master/lapis/init.lua#L30-L35).

Can you try to take the lines apart, as in;
```lua
local lapis = require('lapis')
assert(type(lapis) == 'table', 'lapis should have been a table')
local serve = lapis.serve
assert(type(serve) == 'function', 'lapis.serve should have been a function')
serve('kong.api')
```

That might narrow it down

**Comment by ronan-skyscanner** [comment]
Regarding the line number, we have seen both errors, with line :9 and line :1, with instances using the same nginx-kong.conf (even on the same instance). 

I have tried replacing the require('lapis').serve('kong.api') line with the code above, but because Kong must be reloaded, the error disappears, and the asserts pass fine.

**Comment by Tieske** [comment]
Can you keep it running until it hits again?

**Comment by thefosk** [comment]
Could you update to latest 0.9.8 and check if it happens again?

**Comment by ronan-skyscanner** [comment]
We have identified the issue to be related to a library we were using for protocol buffers: https://github.com/Neopallium/lua-pb

It seems that the clever things this library does with imports was messing the Kong imports.
I have opened an issue in that project and will close this one:

https://github.com/Neopallium/lua-pb/issues/28
