### ISSUE TITLE
LUA-resty-DNS + kong + consul-server

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1844]
I want to use the LUA-resty-DNS plugin, but how do I get the plugin to load automatically when kong starts

I would like to achieve through this plug-in，  kong regularly updated consul-server API

**Comment by Tieske** [comment]
no idea what you mean by this. The resty dns resolver module is a resty module, not a Kong plugin.

what do you mean by "kong regularly updated consul-server API"?

Note that the forthcoming 0.10 release uses the resty dns resolver module to do dns resolution. You can try it from the current `next` branch.

**Comment by huyifanstar** [comment]
@Tieske   Consul-serevr is the registrar,  found the components to collect the docker port and ip, and then I would like to use kong to get consul-server in the api

**Comment by huyifanstar** [comment]
I was told to use LUA-resty-DNS

**Comment by Tieske** [comment]
ok, so what I think you're trying to do is;

1. setup some docker based services
2. register those with consul, under eg. service-xyz
3. consul now provides dns services for the hostname service-xyz
4. configure kong to use your consul server as its dns server
5. configure kong with an api using the `upstream_url` as `http://service-xyz/some/path`

right?

**Comment by huyifanstar** [comment]
Yes, consul-server dns, kong how automatic update?

**Comment by huyifanstar** [comment]
Kongserver how to get consul information? Dns module how to use?

**Comment by huyifanstar** [comment]
@Tieske  Now consul able to regularly check the effective api records, now want consul-dns and kong! Want to achieve kong regularly update api records (consu api provide dns interface)

**Comment by Tieske** [comment]
If you have consul setup and your services registered and monitored by Consul, then consul will update its dns records to only report the available services.

If Kong is setup to use consul as dns server, it will automatically get the updates, as consul updates its dns.

use consuls configuration to specify the `ttl` property of the dns record if there are invalid entries.

anyway, this is really how consul works, and it is not Kong related. Closing this.

**Comment by huyifanstar** [comment]
Yes, kong has been running, so how should I correctly use consul (configuration ttl) to ensure the correct operation of kong and consul ！  thanks
