### ISSUE TITLE
Statsd plugin uses gauge instead of timer for latencey metrics

### ISSUE THREAD

**Issue by endeepak** [Mashape/kong#1845]
### Summary

Statsd plugin uses gauge instead of timer for for lateney and upstream_latency

### Steps To Reproduce

1. Add an API called 'testApi'
2. Enable statsd plugin for the API
3. Access the API via kong proxy
4. Capture the metric posted via statsd plugin

### Actual output

```
kong.testAPi.latency:23|g
kong.testAPi.upstream_latency:19|g
```

### Expected output

```
kong.testAPi.latency:23|ms
kong.testAPi.upstream_latency:19|ms
```
### Additional Details & Logs

- Kong version (`$ kong version`) : 0.9
- Operating System : ubuntu

**Comment by Tieske** [comment]
have you seen #1562 and #1704 ?

**Comment by endeepak** [comment]
Sorry I hadn't seen those.. Those PRs didn't come up in issues search https://github.com/Mashape/kong/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20statsd

**Comment by Tieske** [comment]
np, closing this as a duplicate
