### ISSUE TITLE
Some explanations 

### ISSUE THREAD

**Issue by vautrinr** [Mashape/kong#1848]
### Description
Hello All!
First of all, awesome jobs, guys. I already like Kong API Gateway.
It's not a bug, but a feature request or a doc explanation.

I would like to know if it is possible to : 
- Monetize the API
- OR remove the developer portal

- Is it possible to 
- Is it possible to rewrite URL without changing nginx configuration:

I.E. : /post/data/id/1
--> /posts/1
How does work the CNAME from the doc, with the Host parameter (In the going to production sentences)

Thanks a lot.

Rémi
### Additional Details & Logs

- Kong version 0.9

**Comment by Tieske** [comment]
there are currently no plugins for monetization available.

Not sure what you mean by "remove the developer portal"? do you mean the Kong management API? (default on port 8001)? You should protect your infrastructure in such a way that the big-bad-world only has access to the proxy port (8000 default), and only internal access to the Kong management api is possible.

Regarding rewriting the url, have a look at the `strip_request_path` parameter, that might help. 

what CNAME refrence in what docs? link?

**Comment by vautrinr** [comment]
Hey !

Thanks for the answer. I am currently "benchmarking" some solutions, so this is very helpful.
This is not exactly what I meant. I currently use Gelato && galileo for my tests. There is a documentation generated for the developpers ... ect but nevermind, I think this is not the appropriate place to ask. I will contact gelato support.

I already looked at the strip_request_path parameter. However, I think this is not for entire rewriting. Should I write my own plugin? Is it easy to integrate a plugin from git/svn?


> "Going to production: If you're planning to go into production with your setup, you'll most likely not want your consumers to manually set the "Host" header on each request. You can let Kong and DNS take care of it by simply setting an A or CNAME record on your domain pointing to your Kong installation. Hence, any request made to `example.org` will already contain a `Host: example.org` header."

These stuff I just quoted from the doc, mentions A or CNAME. Is it related to Kong or to my host?

Thank you again.

Rémi

**Comment by Tieske** [comment]
as mentioned on gitter, see #1426 for som inspiration for rewriting the path. The `strip_request_path` can quite often be used, but for more complex ones it won't work.

Regarding the CNAME; Most of the example `curl` commands explicitly set the `host` header. Eg. requesting `http://1.2.3.4/some/path` with explicitly set header `Host=myhostname`.
You probably do not want your client to do this. Hence the advice is to setup your DNS with an A record or CNAME record that refers `myhostname` to `1.2.3.4`, after which (most) clients simply allow you to request `http://myhostname/some/path` and the client will then automatically set the `host` header for you.

So that's just an infrastructure thing, not specific to the Kong configuration.

**Comment by vautrinr** [comment]
Thank you!

However, I still don't get it on the CNAME:

If I have two backend, and one Kong Api; what should I do to support the two backend?

I.E. : 

Backend 1 : http://petstore.swagger.io/v2/
Backend 2 : http://httpbin.org/
API Kong : /bin : httpbin.org
/pet : petstore.swagger.io ?

**Comment by Tieske** [comment]
so you are setting up the apis using a `request_path` with either `/bin` or `/pet`. Correct?

then in this case the host header is not relevant for Kong. SO neither are the CNAME and A records in the dns.

When Kong matches an incoming request to the apis that have been configured, it will first try to match the host header (from the incoming request) to the `request_host` parameters of the api definitions. If this fails to deliver one, it will start matching the incoming path to the configured `request_path` properties.

**Comment by vautrinr** [comment]
Wow Ok ! Thank you, now it is clear.

👍
