### ISSUE TITLE
Now consul able to regularly check the effective api records, now want consul-dns and kong!

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1849]
Now consul able to regularly check the effective api records, now want consul-dns and kong! Want to achieve kong regularly update api records (consu api provide dns interface)

**Comment by Tieske** [comment]
If you have Consul set up as your DNS server, the `ttl` property of your DNS records will determine how often Kong (or actually the underlying nginx) will query for dns record updates. That's all consul.

On the Kong side, just configure the dns server used to point to consul (set the dns server, and disable dnsmasq)

**Comment by huyifanstar** [comment]
How specific configuration? I may need a manual

**Comment by Tieske** [comment]
see https://getkong.org/docs/0.9.x/configuration/#dns-resolver-section

set `dnsmasq=off` and `dns_resolver=x.x.x.x:xxx`, where x.x.x.x:xxx obviously is your consul dns server.

Other than that, there is nothing to configure on Kong, it's all consul from here

**Comment by huyifanstar** [comment]
Thanks, url visit changed? Or before the www.test.com:8000/tomcat (routing)

**Comment by huyifanstar** [comment]
@Tieske  2016/11/29 05:08:50 [verbose] Kong: 0.9.5
2016/11/29 05:08:50 [debug] ngx_lua: 10006
2016/11/29 05:08:50 [debug] nginx: 1011002
2016/11/29 05:08:50 [debug] Lua: LuaJIT 2.1.0-beta2
2016/11/29 05:08:50 [debug] PRNG seed: 892407414310
2016/11/29 05:08:50 [verbose] no config file found at /etc/kong.conf
2016/11/29 05:08:50 [verbose] reading config file at /etc/kong/kong.conf
2016/11/29 05:08:50 [debug] KONG_PG_HOST ENV found with "kong-database"
2016/11/29 05:08:50 [debug] KONG_DATABASE ENV found with "postgres"
2016/11/29 05:08:50 [debug] admin_listen = "0.0.0.0:8001"
2016/11/29 05:08:50 [debug] anonymous_reports = true
2016/11/29 05:08:50 [debug] cassandra_consistency = "ONE"
2016/11/29 05:08:50 [debug] cassandra_contact_points = {"127.0.0.1"}
2016/11/29 05:08:50 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2016/11/29 05:08:50 [debug] cassandra_keyspace = "kong"
2016/11/29 05:08:50 [debug] cassandra_port = 9042
2016/11/29 05:08:50 [debug] cassandra_repl_factor = 1
2016/11/29 05:08:50 [debug] cassandra_repl_strategy = "SimpleStrategy"
2016/11/29 05:08:50 [debug] cassandra_ssl = false
2016/11/29 05:08:50 [debug] cassandra_ssl_verify = false
2016/11/29 05:08:50 [debug] cassandra_timeout = 5000
2016/11/29 05:08:50 [debug] cassandra_username = "kong"
2016/11/29 05:08:50 [debug] cluster_listen = "0.0.0.0:7946"
2016/11/29 05:08:50 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2016/11/29 05:08:50 [debug] cluster_profile = "wan"
2016/11/29 05:08:50 [debug] cluster_ttl_on_failure = 3600
2016/11/29 05:08:50 [debug] custom_plugins = {}
2016/11/29 05:08:50 [debug] database = "postgres"
2016/11/29 05:08:50 [debug] dns_resolver = "consul:53"
2016/11/29 05:08:50 [debug] dnsmasq = false
2016/11/29 05:08:50 [debug] dnsmasq_port = 8053
2016/11/29 05:08:50 [debug] log_level = "notice"
2016/11/29 05:08:50 [debug] lua_code_cache = "on"
2016/11/29 05:08:50 [debug] lua_package_cpath = ""
2016/11/29 05:08:50 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2016/11/29 05:08:50 [debug] lua_ssl_verify_depth = 1
2016/11/29 05:08:50 [debug] mem_cache_size = "128m"
2016/11/29 05:08:50 [debug] nginx_daemon = "on"
2016/11/29 05:08:50 [debug] nginx_optimizations = true
2016/11/29 05:08:50 [debug] nginx_worker_processes = "auto"
2016/11/29 05:08:50 [debug] pg_database = "kong"
2016/11/29 05:08:50 [debug] pg_host = "kong-database"
2016/11/29 05:08:50 [debug] pg_port = 5432
2016/11/29 05:08:50 [debug] pg_ssl = false
2016/11/29 05:08:50 [debug] pg_ssl_verify = false
2016/11/29 05:08:50 [debug] pg_user = "kong"
2016/11/29 05:08:50 [debug] prefix = "/usr/local/kong/"
2016/11/29 05:08:50 [debug] proxy_listen = "0.0.0.0:8000"
2016/11/29 05:08:50 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2016/11/29 05:08:50 [debug] serf_path = "serf"
2016/11/29 05:08:50 [debug] ssl = true
2016/11/29 05:08:50 [verbose] prefix in use: /usr/local/kong
2016/11/29 05:08:50 [verbose] preparing nginx prefix directory at /usr/local/kong
2016/11/29 05:08:50 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2016/11/29 05:08:50 [debug] searching for OpenResty 'resty' executable
2016/11/29 05:08:50 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.1'
2016/11/29 05:08:50 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2016/11/29 05:08:50 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2016/11/29 05:08:50 [verbose] SSL enabled, no custom certificate set: using default certificate
2016/11/29 05:08:50 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2016/11/29 05:08:50 [verbose] running datastore migrations
2016/11/29 05:08:50 [verbose] migrations up to date
2016/11/29 05:08:50 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2016/11/29 05:08:50 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2016/11/29 05:08:50 [verbose] serf agent already running at /usr/local/kong/pids/serf.pid
2016/11/29 05:08:50 [debug] searching for OpenResty 'nginx' executable
2016/11/29 05:08:50 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.11.2.1'
2016/11/29 05:08:50 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2016/11/29 05:08:50 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2016/11/29 05:08:50 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
2016/11/29 05:08:50 [verbose] could not start Kong, stopping services
2016/11/29 05:08:50 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2016/11/29 05:08:50 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
2016/11/29 05:08:50 [verbose] sending TERM signal to nginx running at /usr/local/kong/pids/nginx.pid
2016/11/29 05:08:50 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2016/11/29 05:08:50 [debug] kill -s TERM `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
2016/11/29 05:08:50 [verbose] leaving serf cluster

**Comment by huyifanstar** [comment]
dns_resolver = "consul:53"

**Comment by huyifanstar** [comment]
@Tieske  {"message":"An unexpected error occurred"}

**Comment by huyifanstar** [comment]
2016/11/29 05:02:15 Unexpected response code: 500 (CheckID does not have associated TTL)
Service not registered, registering...
2016/11/29 05:02:15 Unexpected response code: 500 (CheckID does not have associated TTL)
Service not registered, registering...
2016/11/29 05:02:15 Unexpected response code: 500 (CheckID does not have associated TTL)
Service not registered, registering...
2016/11/29 05:03:04 Deregistering service: kong-8000
2016/11/29 05:03:04 signal: terminated
2016/11/29 05:03:08 Unexpected response code: 500 (CheckID does not have associated TTL)
Service not registered, registering...
Kong started
Kong started
2016/11/29 05:08:45 signal: terminated
Kong started

**Comment by huyifanstar** [comment]
What happened, what should I do

**Comment by Tieske** [comment]
This does not seem related to Kong...

first log above;

> 2016/11/29 05:08:50 [verbose] serf agent already running at /usr/local/kong/pids/serf.pid

Seems you're trying to start Kong while it was already running

> dns_resolver = "consul:53"

shouldn't that be an ip address? how would the system resolve the name "consul"?

> 2016/11/29 05:02:15 Unexpected response code: 500 (CheckID does not have associated TTL)
Service not registered, registering...
2016/11/29 05:02:15 Unexpected response code: 500 (CheckID does not have associated TTL)
Service not registered, registering...
2016/11/29 05:02:15 Unexpected response code: 500 (CheckID does not have associated TTL)
Service not registered, registering...

These are not Kong messages... seems consul to me

**Comment by huyifanstar** [comment]
Docker overlay network
Consul-server you familiar with this?

**Comment by Tieske** [comment]
nope
