### ISSUE TITLE
Specifying Cassandra hosts on different ports

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#185]
Sometimes different hosts might have different ports. Right now the port must be the same for each host, while instead it should support the `host:port` format like:

```yaml
hosts:
   - "1.1.1.1:9042"
   - "2.2.2.2:3451"
```

**Comment by thibaultCha** [comment]
That depends on the driver, not me. Please stop assigning.

**Comment by thefosk** [comment]
It is assigned to you because you are the best person to close this issue since you implemented the DAO and you are a main contributor of the Cassandra driver that Kong is using.

**Comment by thibaultCha** [comment]
Unfortunately the driver only supports an array of hosts coupled with a single port as deducible from the [connect](https://github.com/jbochi/lua-resty-cassandra/blob/master/src/cassandra.lua#L95) method. An update can be considered but we'll have to ask the owner first.

**Comment by thefosk** [comment]
Related to https://github.com/jbochi/lua-resty-cassandra/issues/55

**Comment by thibaultCha** [comment]
PR opened on the driver jbochi/lua-resty-cassandra#56
