### ISSUE TITLE
kong  and consul

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1852]
Kong Enable dns (dns_resolver) and consul-dns services with the use of routing address will change? The original is www.test.com:8000/tomcat, there will be changes? (For example: tomcat.www.test.com:8000)

**Comment by Tieske** [comment]
Kong is only available at an IP address. In the DNS server you map a hostname/domainname to an ip address.

So if Kong is on `1.2.3.4`

Then you could easily use consul to point both `www.test.com` AND `tomcat.www.test.com` to ip address `1.2.3.4`

Please read up on how DNS in general works. And in general those type of questions are more suitable on the [gitter channel](https://gitter.im/Mashape/kong). So please discuss there first, and if applicable only raise an issue here if necessary.
