### ISSUE TITLE
{"request_path":"already exists with value '\/console'"}

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1855]
I use kong, I would like to add a number of the same api record to protect the service load balancing, suggesting that I have recorded the existence of (such as the title)

**Comment by Tieske** [comment]
You can't.

If you have multiple apis configured, say A and B, both with `/console` as path, and a request comes in, how would Kong know which of those two it would have to pick?

**Comment by huyifanstar** [comment]
Can  poll? Or there are other options to configure the load balancing?
