### ISSUE TITLE
Kong's forwarding performance improvement

### ISSUE THREAD

**Issue by trevortao** [Mashape/kong#1861]
### Summary

As we know, Kong's forwarding performance are greatly limited when there are a large number routes installed, such as more than 5,000-20,000 routes. This issue would greatly restrict the Kong's use in production environment. 
As far as I investigated, the performance bottleneck lies on the cache-based route lookup mechanism in  kong/core/resolver.lua. So I changed its implementation by using an extra small cache before checking /loading the large cache. 
My personal Kong's performance repo address is:
https://github.com/trevortao/Kong-perf
Now it's just based on an old version of kong-0.8.3, if there is a need for porting it latest release(0.9.x as now), I think I or anyone else can do it rather easily.
You could check and test its performance comparing with the current community version. A simple test result is given in its README.md.

- Kong version (`$ kong version`) -- currently only 0.8.3, should be easy to port to 0.9.x
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by thibaultcha** [comment]
Hey, thanks for taking a look at this and sharing your experiments. FIY, in 0.10 we are planning on releasing a new router with more flexible routing capabilities and improved performance, see the current implementation (still work in progress) on the [feat/new-router](https://github.com/Mashape/kong/tree/feat/new-router) branch.

I will take a look at your implementation soon; we know the current router has its flaws as it is quite legacy as of today :)

**Comment by thibaultcha** [comment]
Oh, I forgot but there is also #1688 which is a temporary improvement over the current router and uses a Lua-land cache instead of relying on the shm zone as well. I believe it is similar to your implementation and what you refer to as "small cache" is the Lua land cache of this PR.

The improvement is also observed because it avoids the deserialization (JSON decoding) of the APIs list on each request, which is a killer for performance.

**Comment by trevortao** [comment]
OK, thanks, it's great to hear that the Kong's performance is improved. I would check it.
