### ISSUE TITLE
Missing query string parameters, when more than 100 parameters

### ISSUE THREAD

**Issue by grepsr** [Mashape/kong#1862]
A parameter goes missing at the upstream, after KONG forwards to upstream. This happens when there are more than **100 query string key/value pairs**, due to the following restriction on the lua-nginx-module:

https://github.com/openresty/lua-nginx-module#ngxreqget_uri_args

Is there an easy way to globally increase this number, perhaps a config variable somewhere? No matter what I do, can't seem to change it.

Thanks!

**Comment by Tieske** [comment]
currently there is no way around it. What you could try is modifying this line; https://github.com/Mashape/kong/blob/b0021821bca896944ece8a09427611805e16dc9b/kong/core/handler.lua#L46

change `ngx.req.get_uri_args()` to `ngx.req.get_uri_args(1000)` (overrides the default limit of 100 and sets it to 1000)

It's not a final solution as many plugins also use the same function, all using the default 100, so additional issues might be expected there. (search the code base for "get_uri_args" to get an indication of which plugins would be affected)

please report back any results.

**Comment by grepsr** [comment]
@Tieske thanks for the reply!

Do I need to re-compile anything after I change those lines? Or just restarting Kong would be enough?

**Comment by grepsr** [comment]
Also, 100 parameters in GET/POST is certainly not a good idea, but I rely on a remote service to POST data to my webhooks, and I can't change their system :(

**Comment by Tieske** [comment]
No need to rebuild anything, just find the file, modify it and reload Kong.

You can use the cli command `restart` (which effectively is a `stop`-`start` sequence) or just use `reload` for a seamless update.
