### ISSUE TITLE
[plugin] file-log plugin don't create a global file

### ISSUE THREAD

**Issue by marceldiass** [Mashape/kong#1863]
### Summary

I'm trying to create a global file-log to my APIs. I'm able to create the global file-log entry but Kong don't create the file after I consume an API successfully.

I've tested the `file-log` plugin to an individual API an it's working fine. Just in the global config is not creating the file.

### Steps To Reproduce
1. Create API
``` bash
❯ curl -X POST http://kong:8001/apis/ \
     -d 'name=Mockbin-API' \
     -d 'request_path=/bin' \
     -d 'upstream_url=http://mockbin.com'
```
2. Configure the global file-log plugin
```bash
❯ curl -X POST http://kong:8001/plugins -d "name=file-log" \
     -d "config.path=/usr/local/kong/logs/all.log"
{
  "id":"d9d74794-f1b2-42a9-bea7-9552bd6fe969",
  "created_at":1480598957000,
  "enabled":true,
  "name":"file-log",
  "config":{"path":"\/usr\/local\/kong\/logs\/all.log"}}
```
3. Consume api
```bash
❯ curl http://kong:8000/bin/e96a03c3-8486-4659-a309-1e98891eb4e8
{
"code":"auth-12345",
"message":"This is a test message!"
}
```  
4. Check the log file 
```bash
❯ ls /usr/local/kong/logs/
access.log
error.log
serf.log
```
5. The log file `all.log` do not exist.

### Additional Details & Logs

- Kong version
  - 0.9.5
- Operating System
  - using the docker official image

**Comment by p0pr0ck5** [comment]
@marceldiass I'm unable to reproduce this behavior. Can you check the permissions of `/usr/local/kong/logs/` and ensure that you have write access to that directory?

**Comment by p0pr0ck5** [comment]
Closing as stale after no response. Feel free to re-open this if you're still having issues here. Thanks!
