### ISSUE TITLE
Kong's Nginx configuration: moving logs directives

### ISSUE THREAD

**Issue by pamiel** [Mashape/kong#1864]
The new way to manage the Nginx configuration (introduced in Kong 0.9.x) through the nginx.conf and nginx-kong.conf files is really convenient to isolate the Kong-specific configuration part of Nginx.
Ideally, my feeling is that the nginx-kong.conf file should remain untouched, and any update shall be made on the nginx.conf (so that, for example, when upgrading Kong, only the nginx.conf of previous version needs to be reused).

However, the configuration of the error logs and the access logs is contained in the nginx-kong.conf. It means that if it is required to change the location of the output file or to define a custom access log format, then it is required either to update the nginx-kong.conf (but I would not like to do this) or to inline the content of this file into the nginx.conf (as recommended in https://getkong.org/docs/0.9.x/configuration/#custom-nginx-configuration). In both cases, we lose the advantage of having the full Kong's Nginx configuration be isolated into a separated file.

Don’t you think that the following lines should be moved from the nginx-kong.conf to the nginx.conf so that it could be updated more easily (and keeping the nginx-kong.conf untouched)?
```
error_log logs/error.log notice;
access_log logs/access.log;
error_log syslog:server=kong-hf.mashape.com:61828 error;
```
By the way, it looks that with the 3rd line, the error logs are by default sent to a Mashape server?! Why??
(those  lines are extracted from the official Docker image of Kong)

**Comment by thibaultcha** [comment]
Hi,

Yes, I believe the new way to customize the Nginx configuration is convenient too, although it could definitely still be improved, I have a few ideas about it, such as arbitrarily provide and customize ngx_lua directives, for example. Those improvements might come later. Another idea is to make Kong entirely configurable through the Nginx configuration via Kong-specific directives (`kong_postgres_address 120.0.0.1;` etc...). We'll see about those.

Considering the error logs, please also consider that the way the configuration is built is also to allow people to "embed" Kong in an existing Nginx/OpenResty instance. Say an Nginx server is running in your architecture, but you want Kong: in that case, install OpenResty, copy-paste your Nginx servers into the main Kong nginx config (which also includes `nginx-kong.conf`) and voilà: Nginx with any server you used to run, + Kong.

For this reason, the logs are specific to the Kong part of the configuration. One of the aforementioned 2 other solutions (there are others) would allow to configure the error and access logs more easily, for sure. Yet another solution, more on the short term, would be to simply make those directives configurable via the Kong configuration, just like the `log_level` property is doing right now.

> By the way, it looks that with the 3rd line, the error logs are by default sent to a Mashape server?! Why??

This directive was introduced with the `anonymous_reports` property. If you turn off the reports, it should not be included when Kong "compiles" the Nginx configuration template.

**Comment by thibaultcha** [comment]
Feel free to continue this discussion, closing this as currently resolved.
