### ISSUE TITLE
errors on kong startup

### ISSUE THREAD

**Issue by peacemakr** [Mashape/kong#1869]
### Summary

I am getting the following errors as soon as I start kong (kong start).
```
/usr/local/openresty/bin/../nginx/sbin/nginx: 1: /usr/local/openresty/bin/../nginx/sbin/nginx: ?: not found
/usr/local/openresty/bin/../nginx/sbin/nginx: 1: /usr/local/openresty/bin/../nginx/sbin/nginx: ELF: not found
/usr/local/openresty/bin/../nginx/sbin/nginx: 3: /usr/local/openresty/bin/../nginx/sbin/nginx: 0?: not found
/usr/local/openresty/bin/../nginx/sbin/nginx: 1: /usr/local/openresty/bin/../nginx/sbin/nginx: Syntax error: "|" unexpected (expecting ")")
```
I tried running with sudo as well but same error. Also,  /usr/local/openresty/bin/../nginx/sbin/nginx file exists and I've uninstalled nginx too.

### Steps To Reproduce

1. Install Kong using the instruction in manual on Ubuntu Linux Trusty
2. Install PostgreSQL
3. Try running kong

### Additional Details & Logs

- Kong version: kong-0.9.5.trusty_all.deb
- Kong debug-level startup logs (`$ kong start --vv`): same err as above (perhaps it does not get a chance to write logs)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`): where are they located on Ubuntu?
- Kong configuration (registered APIs/Plugins & configuration file): default config starting the first time
- Operating System: 
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Comment by Tieske** [comment]
logs are in the same place (or should be)

The output from `kong start --vv` should tell you the prefix in use

**Comment by peacemakr** [comment]
Output of -vv is exactly the same as mentioned in my post already. Based on that and your comment, I ran the following 
```
sudo find /usr/local/openresty/ -type f  | egrep -i log
/usr/local/openresty/pod/nginx/ngx_http_session_log_module.pod
/usr/local/openresty/pod/nginx/debugging_log.pod
/usr/local/openresty/pod/nginx/syslog.pod
/usr/local/openresty/pod/nginx/ngx_http_log_module.pod
```
None of them appear to be log files. Also, /usr/local/kong/ is empty

**Comment by Tieske** [comment]
can you provide full output of `kong start --vv`?

**Comment by peacemakr** [comment]
```
kong start --vv
/usr/local/openresty/bin/../nginx/sbin/nginx: 1: /usr/local/openresty/bin/../nginx/sbin/nginx: ?: not found
/usr/local/openresty/bin/../nginx/sbin/nginx: 1: /usr/local/openresty/bin/../nginx/sbin/nginx: ELF: not found
/usr/local/openresty/bin/../nginx/sbin/nginx: 3: /usr/local/openresty/bin/../nginx/sbin/nginx: 0?: not found
/usr/local/openresty/bin/../nginx/sbin/nginx: 1: /usr/local/openresty/bin/../nginx/sbin/nginx: Syntax error: "|" unexpected (expecting ")")
```

**Comment by depay** [comment]
seems something wrong with sys arch. why not compiling kong yourself ?

**Comment by Tieske** [comment]
@peacemakr have you been able to resolve this? Did you try to compile it yourself, as @depay suggested?

**Comment by EdwinTSalcedo** [comment]
I have run into a similar problem. In my case it's just one line: /usr/local/openresty/bin/../nginx/sbin/nginx: 1: /usr/local/openresty/bin/../nginx/sbin/nginx: Syntax error: "(" unexpected

**Comment by lheuninck** [comment]
Encountered similar issue as @peacemakr .  Whatever argument I give along with kong, same message. Running on Ubuntu 12.04 LTS within Virtualbox. Currently stuck  I fear that recompiling might bring me further away in stead of closer.  Any suggestions ?

**Comment by blaazetech** [comment]
Same for me as well, here is the output
```
root@ubuntu-1gb-blr1-01:~# kong start --vv
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
/usr/local/openresty/bin/../nginx/sbin/nginx: 1: /usr/local/openresty/bin/../nginx/sbin/nginx: ?: not found
/usr/local/openresty/bin/../nginx/sbin/nginx: 1: /usr/local/openresty/bin/../nginx/sbin/nginx: ELF: not found
/usr/local/openresty/bin/../nginx/sbin/nginx: 4: /usr/local/openresty/bin/../nginx/sbin/nginx: 0?: not found
/usr/local/openresty/bin/../nginx/sbin/nginx: 1: /usr/local/openresty/bin/../nginx/sbin/nginx: Syntax error: "|" unexpected (expecting ")")
```

Am using `kong-0.10.3.trusty_all.deb` on `Ubuntu 14.04 LTS`

**Comment by amatosc** [comment]
I've got the same error that @peacemakr using` kong-0.10.3.trusty_all.deb` on `Ubuntu 16.04 LTS`
Any idea how to fix it? @Tieske

**Comment by amatosc** [comment]
I've fixed it installed a 64bits instance of ubuntu, but I open an issue #2658
