### ISSUE TITLE
An invalid response was received from the upstream server.

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1874]
![8j3 ssflav l b2cs 2ye86](https://cloud.githubusercontent.com/assets/15685376/20877799/0a5fe796-bb06-11e6-99d4-41f6d0d7c67b.png)

Now my application is available，I will add this api to kongserver
![9yu5 dxye8o2 25jw1_dsqt](https://cloud.githubusercontent.com/assets/15685376/20877803/10b4b1e4-bb06-11e6-87cc-bf95a5f26ee1.png)

![j h_ t0i98ucm gq c 1 w](https://cloud.githubusercontent.com/assets/15685376/20877813/19013642-bb06-11e6-83e6-6d0e5fe8db60.png)

Kong Error

An invalid response was received from the upstream server.
Is this what the problem , what should I do

**Comment by Tieske** [comment]
closing this, [answer is on gitter](https://gitter.im/Mashape/kong?at=584548a844f3e83528dd6869)
