### ISSUE TITLE
Support of content based routing

### ISSUE THREAD

**Issue by jonathan-macke** [Mashape/kong#1875]
Hi,

Do you plan to support content based routing in Kong ?
We would like to route requests to our backend API depending on an HTTP header or a field in the body. 
We have multi tenant system and we would like to have dedicated API backend per customer. But we want to expose the same API for all the customers. The redirection to the right backend must transparent for the customer.

I hope my request is clear enough.

Jonathan

**Comment by thibaultcha** [comment]
We indeed have plans to route incoming requests to different upstream services based on arbitrary HTTP headers in the future.

**Comment by thibaultcha** [comment]
Closing this for now as the question is considered answered.
