### ISSUE TITLE
Can I add some additional info while using OAuth2 ?

### ISSUE THREAD

**Issue by catscarlet** [Mashape/kong#1881]
### Summary

Can I add some additional info while using OAuth2 ?

I'm using Resource Owner Password Credentials now.

Client gets the `access_token`, and when request is sent to Kong, a Upstream Headers will have `X-Authenticated-Userid`. That is how it works now.

The API server receives the `X-Authenticated-Userid`, and now it has to request the User-Database to find which "Username" is related to the `Userid`.

My question is, Can I add some additional info just like "Username" to OAuth2 so that the Upstream Headers will have both `X-Authenticated-Userid` and more additional info like `X-Authenticated-Username`.

### Additional Details & Logs

- Kong version 0.9.5

**Comment by DonMartin76** [comment]
Currently, no, but what you actually can do is encoding more information into the `X-Authenticated-Userid`, e.g. `"authenticated_userd":"userid=1234567;username=catscarlet"`. This works just fine. I have not yet found the upper bound of characters, but I wouldn't overdo it.

See also #522 for a discussion of OpenID Connect which would also need some tweaking of the OAuth2 plugin.

**Comment by catscarlet** [comment]
That's a interesting way. Thank you for help.

**Comment by thefosk** [comment]
This is the right approach, `authenticated_userid` is effectively a free form field that allows you to set whatever data you want to pass to identify the user.
