### ISSUE TITLE
Global plugin except specific APIs

### ISSUE THREAD

**Issue by ntin90** [Mashape/kong#1882]
Hi team,

Global plugin is now applied to all APIs. I prefer a way global plugin will be applied to all APIs, except those which have their same named plugin (either enabled or disabled).

For example: API A has a disabled JWT plugin, won't be affected by global JWT plugin.

Does it make sense?

**Comment by thibaultcha** [comment]
While this makes sense, Kong does not support such a use case and does not have plans to do so in the near future, sorry.
