### ISSUE TITLE
the difference between consumer_id and custom_id

### ISSUE THREAD

**Issue by ssholder** [Mashape/kong#1884]
### Summary

You can add a plugin in four different ways. For every API and a specific Consumer. Only set consumer_id,but when I create a consumer, I can only set the parameters such as username and custom_id.So, the question is that where is the parameter named consumer_id?

**Comment by DonMartin76** [comment]
You get that back from Kong; it's the internal id/GUID used by Kong to identify your consumer. The result of the POST to `/consumer` will contain an `id`, this is your `consumer_id` when referring to the consumer in plugins.

**Comment by Tieske** [comment]
assuming this answered (thx @DonMartin76 ), closing. Please feel free to reopen if necessary.
