### ISSUE TITLE
Extending the objects metadata (API and Consumer) with more attributes

### ISSUE THREAD

**Issue by joaodrp** [Mashape/kong#1885]
### Summary

First of all, the work that you guys have been doing here is great, thanks to all of you.

I'm looking at using Kong for a large project. Its features are really appealing, but I find the objects metadata to be very limited. As the number of APIs grows, more data becomes necessary to describe/categorize/organize them, as well as the consumers.

Implementing a layer on top of Kong would be possible of course, but that would imply duplicated data and possibly out of sync issues between the custom data extension layer and Kong.

Given this I compiled a list of attributes that I think would be really useful to have in Kong's DAO (while keeping them optional, so we wouldn't break compatibility and those who are ok with the current set of attributes will continue to be happy too).

I'm not a Lua programmer but I'm willing to give it a try and implement it, if the community finds that it's worth it.

Bellow I list the current attributes and the ones I would add for each object.

#### Currently:
- `name`
- `request_host`
- `request_path`
- `strip_request_path`
- `preserve_host`
- `upstream_url`

#### Addition:
- `tags`: Array of tags.
- `description`: A short description (name is not enough I think).
- `group`: The logical/functional group (e.g. network, hosting, billing, etc).
- `maintainer`: The name of the maintainer.
- `maintainer_contact`: The contact of the maintainer (e.g. phone or email).
- `publisher`: The user who published.
- `repository`: The URL of the repository.
- `version`: API version (e.g. v1).
- `destination_system`: The system to which the API connects to (if any).

#### Currently:
- `username`
- `custom_id`

#### Addition:
- `type`: If the consumer is a `system` or an end `user`.
- `contact`: The consumer contact (e.g. phone or email).
- `contact_name`: The contact name.

So what do you think about it? Any other suggestions?

**Comment by warroyo** [comment]
Is there any interest in this from others? I also have a need for something similar

**Comment by p0pr0ck5** [comment]
Thanks for the explanation and thought here. Adding this in has been on our radar for quite a while. We're trying to keep GitHub issues reserved for actual problems/bug reports for Kong, so we're closing this, and we'll keep this in mind moving forward. Thank you!
