### ISSUE TITLE
JWT plugin does not create credentials for consumer identified with UUID

### ISSUE THREAD

**Issue by codeocelot** [Mashape/kong#1886]
### Summary

SUMMARY_GOES_HERE
JWT plugin does not create credentials when passed a uuid that identifies a user (either username or custom_id).  

### Steps To Reproduce

1. Register a new user:
`curl -X POST kong:8001/consumers --data "username=ad005c48-508a-41d0-b303-8921e97609c3"`
2. Create credentials
`curl -X POST kong:8001/consumers/ad005c48-508a-41d0-b303-8921e97609c3/jwt`
3. Expected Result: 200, Actual Result: 404 

### Additional Details & Logs

- Kong version: 0.9.6
- Kong debug-level startup logs (`$ kong start --vv`)
2016/12/09 14:08:37 [verbose] Kong: 0.9.6
2016/12/09 14:08:37 [debug] ngx_lua: 10006
2016/12/09 14:08:37 [debug] nginx: 1011002
2016/12/09 14:08:37 [debug] Lua: LuaJIT 2.1.0-beta2
2016/12/09 14:08:37 [debug] PRNG seed: 842135533129
2016/12/09 14:08:37 [verbose] no config file found at /etc/kong.conf
2016/12/09 14:08:37 [verbose] no config file found at /etc/kong/kong.conf
2016/12/09 14:08:37 [verbose] no config file, skipping loading
2016/12/09 14:08:37 [debug] admin_listen = "0.0.0.0:8001"
2016/12/09 14:08:37 [debug] anonymous_reports = true
2016/12/09 14:08:37 [debug] cassandra_consistency = "ONE"
2016/12/09 14:08:37 [debug] cassandra_contact_points = {"127.0.0.1"}
2016/12/09 14:08:37 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2016/12/09 14:08:37 [debug] cassandra_keyspace = "kong"
2016/12/09 14:08:37 [debug] cassandra_port = 9042
2016/12/09 14:08:37 [debug] cassandra_repl_factor = 1
2016/12/09 14:08:37 [debug] cassandra_repl_strategy = "SimpleStrategy"
2016/12/09 14:08:37 [debug] cassandra_ssl = false
2016/12/09 14:08:37 [debug] cassandra_ssl_verify = false
2016/12/09 14:08:37 [debug] cassandra_timeout = 5000
2016/12/09 14:08:37 [debug] cassandra_username = "kong"
2016/12/09 14:08:37 [debug] cluster_listen = "0.0.0.0:7946"
2016/12/09 14:08:37 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2016/12/09 14:08:37 [debug] cluster_profile = "wan"
2016/12/09 14:08:37 [debug] cluster_ttl_on_failure = 3600
2016/12/09 14:08:37 [debug] custom_plugins = {}
2016/12/09 14:08:37 [debug] database = "postgres"
2016/12/09 14:08:37 [debug] dnsmasq = true
2016/12/09 14:08:37 [debug] dnsmasq_port = 8053
2016/12/09 14:08:37 [debug] log_level = "notice"
2016/12/09 14:08:37 [debug] lua_code_cache = "on"
2016/12/09 14:08:37 [debug] lua_package_cpath = ""
2016/12/09 14:08:37 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2016/12/09 14:08:37 [debug] lua_ssl_verify_depth = 1
2016/12/09 14:08:37 [debug] mem_cache_size = "128m"
2016/12/09 14:08:37 [debug] nginx_daemon = "on"
2016/12/09 14:08:37 [debug] nginx_optimizations = true
2016/12/09 14:08:37 [debug] nginx_worker_processes = "auto"
2016/12/09 14:08:37 [debug] pg_database = "kong"
2016/12/09 14:08:37 [debug] pg_host = "127.0.0.1"
2016/12/09 14:08:37 [debug] pg_port = 5432
2016/12/09 14:08:37 [debug] pg_ssl = false
2016/12/09 14:08:37 [debug] pg_ssl_verify = false
2016/12/09 14:08:37 [debug] pg_user = "kong"
2016/12/09 14:08:37 [debug] prefix = "/usr/local/kong/"
2016/12/09 14:08:37 [debug] proxy_listen = "0.0.0.0:8000"
2016/12/09 14:08:37 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2016/12/09 14:08:37 [debug] serf_path = "serf"
2016/12/09 14:08:37 [debug] ssl = true
2016/12/09 14:08:37 [verbose] prefix in use: /usr/local/kong
2016/12/09 14:08:37 [verbose] preparing nginx prefix directory at /usr/local/kong
2016/12/09 14:08:37 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2016/12/09 14:08:37 [debug] searching for OpenResty 'resty' executable
2016/12/09 14:08:37 [debug] /usr/local/openresty/bin/resty -V: 'sh: /usr/local/openresty/bin/resty: No such file or directory'
2016/12/09 14:08:37 [debug] OpenResty 'resty' executable not found at /usr/local/openresty/bin/resty
2016/12/09 14:08:37 [debug] resty -V: 'nginx version: openresty/1.11.2.1'
2016/12/09 14:08:37 [debug] found OpenResty 'resty' executable at resty
2016/12/09 14:08:37 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2016/12/09 14:08:37 [verbose] SSL enabled, no custom certificate set: using default certificate
2016/12/09 14:08:37 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2016/12/09 14:08:37 [verbose] running datastore migrations
2016/12/09 14:08:37 [verbose] migrations up to date
2016/12/09 14:08:37 [verbose] dnsmasq not running, deleting /usr/local/kong/pids/dnsmasq.pid
2016/12/09 14:08:37 [debug] searching for 'dnsmasq' executable
2016/12/09 14:08:37 [debug] /usr/local/sbin/dnsmasq -v: 'Dnsmasq version 2.76  Copyright (c) 2000-2016 Simon Kelley'
2016/12/09 14:08:37 [debug] found 'dnsmasq' executable at /usr/local/sbin/dnsmasq
2016/12/09 14:08:37 [debug] starting dnsmasq: /usr/local/sbin/dnsmasq -p 8053 --pid-file=/usr/local/kong/pids/dnsmasq.pid -N -o --listen-address=127.0.0.1
2016/12/09 14:08:37 [verbose] serf agent not running, deleting /usr/local/kong/pids/serf.pid
2016/12/09 14:08:37 [debug] checking 'serf' executable from 'serf_path' config setting
2016/12/09 14:08:37 [debug] serf version: 'Serf v0.8.0'
2016/12/09 14:08:37 [debug] starting serf agent: nohup serf agent -profile 'wan' -rpc-addr '127.0.0.1:7373' -event-handler 'member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf/serf_event.sh' -bind '0.0.0.0:7946' -node 'Joeys-MacBook-Pro.local_0.0.0.0:7946_7899b7ed127b434cb9a95a32c6e08f37' -log-level 'err' > /usr/local/kong/logs/serf.log 2>&1 & echo $! > /usr/local/kong/pids/serf.pid
2016/12/09 14:08:37 [verbose] waiting for serf agent to be running
2016/12/09 14:08:38 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2016/12/09 14:08:38 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2016/12/09 14:08:38 [verbose] serf agent started
2016/12/09 14:08:38 [verbose] auto-joining serf cluster
2016/12/09 14:08:38 [verbose] no other nodes found in the cluster
2016/12/09 14:08:38 [verbose] registering serf node in datastore
2016/12/09 14:08:38 [verbose] cluster joined and node registered in datastore
2016/12/09 14:08:38 [debug] searching for OpenResty 'nginx' executable
2016/12/09 14:08:38 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'sh: /usr/local/openresty/nginx/sbin/nginx: No such file or directory'
2016/12/09 14:08:38 [debug] OpenResty 'nginx' executable not found at /usr/local/openresty/nginx/sbin/nginx
2016/12/09 14:08:38 [debug] nginx -v: 'nginx version: openresty/1.11.2.1'
2016/12/09 14:08:38 [debug] found OpenResty 'nginx' executable at nginx
2016/12/09 14:08:38 [debug] starting nginx: nginx -p /usr/local/kong -c nginx.conf
2016/12/09 14:08:38 [debug] nginx started
2016/12/09 14:08:38 [info] Kong started

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

- Kong configuration (registered APIs/Plugins & configuration file)
Registered apis:  mockbin (see 5 min start guide).  
- Operating System
MacOS Sierra

**Comment by DonMartin76** [comment]
Known issue. Kong checks the format of the :id parameter of the /consumers/:id end point, and if it is a GUID/UUID it assumes you refer to a Kong internal ID, which is not the case here. Hence the 404, as the UUID is not a Kong ID, but one you passed in from the outside.

Workaround is to either prepend your ID with some fixed prefix, like `user-<uuid>`, or to have an actual username in the username, and use the `custom_id` for your own UUID.

**Comment by Tieske** [comment]
considering this answered. Thx @DonMartin76 :+1:
