### ISSUE TITLE
I can't starting kong

### ISSUE THREAD

**Issue by szlzhm** [Mashape/kong#1888]
### Summary

I can't starting kong.

### Steps To Reproduce

1.After finish intall kong,I try kong start cmd to run kong,but it failed. This is error message at blow;
2、I have installed postgresql in my computer，create database kong and create user named kong
3、I never install cassandra .
4、OS is centos 6 

### Additional Details & Logs
[root@localhost local]# kong start --vv
2016/12/10 22:07:44 [verbose] Kong: 0.9.5
2016/12/10 22:07:44 [debug] ngx_lua: 10006
2016/12/10 22:07:44 [debug] nginx: 1011002
2016/12/10 22:07:44 [debug] Lua: LuaJIT 2.1.0-beta2
2016/12/10 22:07:44 [debug] PRNG seed: 210200182431
2016/12/10 22:07:44 [verbose] no config file found at /etc/kong.conf
2016/12/10 22:07:44 [verbose] reading config file at /etc/kong/kong.conf
2016/12/10 22:07:44 [debug] admin_listen = "0.0.0.0:8001"
2016/12/10 22:07:44 [debug] anonymous_reports = true
2016/12/10 22:07:44 [debug] cassandra_consistency = "ONE"
2016/12/10 22:07:44 [debug] cassandra_contact_points = {"127.0.0.1"}
2016/12/10 22:07:44 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2016/12/10 22:07:44 [debug] cassandra_keyspace = "kong"
2016/12/10 22:07:44 [debug] cassandra_port = 9042
2016/12/10 22:07:44 [debug] cassandra_repl_factor = 1
2016/12/10 22:07:44 [debug] cassandra_repl_strategy = "SimpleStrategy"
2016/12/10 22:07:44 [debug] cassandra_ssl = false
2016/12/10 22:07:44 [debug] cassandra_ssl_verify = false
2016/12/10 22:07:44 [debug] cassandra_timeout = 5000
2016/12/10 22:07:44 [debug] cassandra_username = "kong"
2016/12/10 22:07:44 [debug] cluster_listen = "0.0.0.0:7946"
2016/12/10 22:07:44 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2016/12/10 22:07:44 [debug] cluster_profile = "wan"
2016/12/10 22:07:44 [debug] cluster_ttl_on_failure = 3600
2016/12/10 22:07:44 [debug] custom_plugins = {}
2016/12/10 22:07:44 [debug] database = "postgres"
2016/12/10 22:07:44 [debug] dnsmasq = true
2016/12/10 22:07:44 [debug] dnsmasq_port = 8053
2016/12/10 22:07:44 [debug] log_level = "notice"
2016/12/10 22:07:44 [debug] lua_code_cache = "on"
2016/12/10 22:07:44 [debug] lua_package_cpath = ""
2016/12/10 22:07:44 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2016/12/10 22:07:44 [debug] lua_ssl_verify_depth = 1
2016/12/10 22:07:44 [debug] mem_cache_size = "128m"
2016/12/10 22:07:44 [debug] nginx_daemon = "on"
2016/12/10 22:07:44 [debug] nginx_optimizations = true
2016/12/10 22:07:44 [debug] nginx_worker_processes = "auto"
2016/12/10 22:07:44 [debug] pg_database = "kong"
2016/12/10 22:07:44 [debug] pg_host = "127.0.0.1"
2016/12/10 22:07:44 [debug] pg_password = "******"
2016/12/10 22:07:44 [debug] pg_port = 5432
2016/12/10 22:07:44 [debug] pg_ssl = false
2016/12/10 22:07:44 [debug] pg_ssl_verify = false
2016/12/10 22:07:44 [debug] pg_user = "kong"
2016/12/10 22:07:44 [debug] prefix = "/usr/local/kong/"
2016/12/10 22:07:44 [debug] proxy_listen = "0.0.0.0:8000"
2016/12/10 22:07:44 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2016/12/10 22:07:44 [debug] serf_path = "serf"
2016/12/10 22:07:44 [debug] ssl = false
2016/12/10 22:07:44 [verbose] prefix in use: /usr/local/kong
2016/12/10 22:07:44 [verbose] preparing nginx prefix directory at /usr/local/kong
2016/12/10 22:07:44 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2016/12/10 22:07:44 [debug] searching for OpenResty 'resty' executable
2016/12/10 22:07:44 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.1'
2016/12/10 22:07:44 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2016/12/10 22:07:44 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2016/12/10 22:07:44 [verbose] running datastore migrations
2016/12/10 22:07:44 [verbose] could not start Kong, stopping services
2016/12/10 22:07:44 [verbose] leaving serf cluster
2016/12/10 22:07:44 [verbose] stopping dnsmasq at /usr/local/kong/pids/dnsmasq.pid
2016/12/10 22:07:44 [debug] sending signal to pid at: /usr/local/kong/pids/dnsmasq.pid
2016/12/10 22:07:44 [debug] no pid file at: /usr/local/kong/pids/dnsmasq.pid
2016/12/10 22:07:44 [verbose] stopped services
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:37: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: [postgres error] ERROR: function to_regclass(unknown) does not exist (8)
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:37: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:89>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:15: in function 'file_gen'
        init_worker_by_lua:38: in function <init_worker_by_lua:36>
        [C]: in function 'pcall'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>

**Comment by Tieske** [comment]
Seems you have a wrong version of Postgres. Please check the requirement.

**Comment by mytototo** [comment]
I have the same issue after upgrading from v0.9.5 to v0.9.6 using Homebrew....

**Comment by depay** [comment]
requires postgre >= 9.4.9

postgresql 9.5.5 works well for me.

**Comment by thibaultcha** [comment]
Considering this resolved.
