### ISSUE TITLE
GraphQL admin

### ISSUE THREAD

**Issue by mytototo** [Mashape/kong#1889]
Hey,

Do you have plans about a GraphQL endpoint admin so we can consume it instead of the REST API ? Way much easier for a dashboard.

Thanks.

**Comment by Tieske** [comment]
no plans right now. GraphQL is great to reduce "over-fetching" of REST apis on mobile clients considering bandwidth etc. But on the Kong management api those issues are less pressing.

So for now the implementation effort doesn't seem proportional to the benefits. That said; we welcome contributions 😄
