### ISSUE TITLE
Allow adding plugins at top level, not API specific

### ISSUE THREAD

**Issue by gitomato** [Mashape/kong#1891]
### Summary

Thank you for your great work on Kong. Integrating some plugins like OAuth2 in our microservices is very staightforward. However, the fact that each plugin is tied to a specific API is limiting.

### Use case
- use OAuth2 plugin
- authenticate the user with username/passord and generate an access token through API `x.domain.com`
- authenticate the user with the same access token through APIs `y.domain.com`, `z.domain.com`, ...

From what I understand, unifying such a process should be one of the purposes of an API Gateway. Or did I miss something?

**Comment by thefosk** [comment]
Have you tried to create the plugin by executing a `POST /plugins` without specifying any `api_id`. Would that work?

**Comment by gitomato** [comment]
Thank you! I don't how I could miss this in the docs.
