### ISSUE TITLE
X-Forwarded-Host and X-Forwarded-Proto should be passed regardless of resolution strategy

### ISSUE THREAD

**Issue by mpsmith** [Mashape/kong#1896]
### Summary

The HTTP Headers 'X-Forwarded-Host' and 'X-Forwarded-Proto' should be passed to the upstream server regardless of whether Kong resolved the destination of a request by request_host or by request_path.

Reference:  https://en.wikipedia.org/wiki/List_of_HTTP_header_fields (search on those two names)

I have a Kong server routing a request based on request_path.   The application fulfilling that request still needs access to the original hostname and protocol for generating a callback URL for the client.  That callback URL needs to point at the the Kong Server instead of pointing at the internal server.

Looking at resolver.lua, it looks like the X-Forwarded-Host Header is passed through if the request destination was resolved through a request_host match, but not for a request_path match.

I believe these headers are general purpose and their addition to the forwarded request should not be tied to what strategy Kong uses internally to resolve the destination of a request (request_host vs request_path).

### Steps To Reproduce

1.  Configure an API using request_path routing w/ empty request_host pointing at a service.
2. Submit a request to the Kong url for that API.
3. Observe the Http Headers on the request Kong forwards to the service.
4. X-Forwarded-Host and X-Forwarded-Proto are not set.

### Additional Details & Logs

- Kong 0.9.5

Workarounds:  Configure a request transformers to add the header or use a custom nginx config that sets it for every request

**Comment by DonMartin76** [comment]
See also #1823.

**Comment by thibaultcha** [comment]
Moved to @2202. Thanks!
