### ISSUE TITLE
Rate limiting plugin - limit per consumer and IP.

### ISSUE THREAD

**Issue by IvanVas** [Mashape/kong#1899]
It would be great to rate-limit requests per (consumer, IP) pair. Right now it can only limit per consumer or IP.

Thanks

**Comment by ShinEDL** [comment]
I think it will be great to rate-limit requests by setting a sum.

**Comment by Tieske** [comment]
@ShinEDL can you please elaborate on what you mean by "sum"

**Comment by ShinEDL** [comment]
Thank you for your response.
I was really mean whether we can limit requests with a specific number, no matter what IP or consumer.

**Comment by ShinEDL** [comment]
@Tieske Thank you for your response.
I was really mean whether we can limit requests with a specific number, no matter what IP or consumer？

**Comment by thibaultcha** [comment]
We have this own our radar, thanks for the suggestion!
