### ISSUE TITLE
How to add load balancer?

### ISSUE THREAD

**Issue by HenryChelsea** [Mashape/kong#1900]
### Summary

Hi,all
   I knew that kong based on 'serf'. So how can I add a load balancer between kong cluster and client requests? Do I need to tell LB the static ip in my kong cluster?
Thanks.

**Comment by Tieske** [comment]
Generally a Kong infra looks like this:

- In front of Kong there is a loadbalancer to distribute the incoming traffic over the Kong nodes
- Kong will simply be configured with hostnames for upstream services
- The upstream services are added to the DNS using discovery tools or similar (Consul is popular these days)
- Based on the DNS the load will now be balanced to the upstream services (SRV records are not supported)

in 0.10 Kong will do internal balancing on dns records (including SRV), or by specifically creating a balancer (an 'upstream') and adding/removing 'targets' to/from it dynamically.

**Comment by HenryChelsea** [comment]
@Tieske 
serf + haproxy + kong ?
This serf demo: [web load balance](https://github.com/hashicorp/serf/tree/master/demo/web-load-balancer).
When I join a kong node, loadbalancer could automatically fetch the new node?
Thanks.

**Comment by Tieske** [comment]
@HenryChelsea Kong does not automatically update the loadbalancer in front of it. And the upcoming version will include support for loadbalancing from Kong to the upstreams.

Maybe @thefosk knows whether you can listen in on the Serf cluster (underlying to Kong) and automatically trigger an update of the haproxy when a Kong node is added/removed

**Comment by HenryChelsea** [comment]
@Tieske Thanks, I knew the new feature in upcoming version (loadbalancing from kong to upstreams).

    `A Kong cluster allows you to scale the system horizontally by adding more machines to handle a bigger load of incoming requests, and they all share the same data since they point to the same datastore.` -- kong cluster info

I think if kong cluster support this, load balancer needs to know the new nodes or the failed nodes. 
Thanks for your reply!

**Comment by HenryChelsea** [comment]
@thefosk Hope you can give some advice. 
Thanks.

**Comment by thefosk** [comment]
I wouldn't rely on Serf for doing LB.

**Comment by HenryChelsea** [comment]
@thefosk Thanks for your reply.
So how to make the LB automatically knew the nodes in cluster? Get all the static ip and register in LB (like ELB) by myself?
Thanks.

**Comment by thefosk** [comment]
@HenryChelsea like you would do with other services: by using an Auto Scaling Group that automatically adds the nodes to the ELB, or by automating the process in your devops workflow.

**Comment by HenryChelsea** [comment]
@thefosk 
Thanks! Got that.
I'll close this issue.
