### ISSUE TITLE
Testing plugins with docker container

### ISSUE THREAD

**Issue by AntonioCS** [Mashape/kong#1901]
Hey guys,

I am quite knew to kong and the lua environment. I have followed your tutorials and have made successfully made a plugin.
I would like to add some tests to this and in the documentation there is a reference to a specs folder and also to the test framework busted. I can see the specs folder in the git repo but in the container at

- /usr/local/share/lua/5.1/kong/

There is no specs folder nor is busted installed. Is there a container that provides all of this or is this is something I have to do manually so that I can get tests to work?

Thanks.

- Kong version 0.9.5
- Ubuntu 16

**Comment by Tieske** [comment]
the development/test stuff is not in the distributions, only in the source repo.

Generally; 

1. install Kong as usual
1. clone the repo
1. `make dev`
1. from the repo start kong with `./bin/kong start` (to make sure you start the local dev one)

Don't have them handy, but iirc there are a view dev setups available, using either vagrant or docker, please use you google foo on that first

**Comment by AntonioCS** [comment]
Hey,

Thanks for the quick reply.
Some of the repos I found regarding a kong dev version are the following:

- https://github.com/konobi/kong-dev-docker
- https://github.com/superpixelhq/kong-plugin-development

The first one seems to create a container from the ground up and install everything needed for kong (not sure if it does the steps you recommend as there are a lot of instructions and I am also a bit new to docker).
The second I used in the past and its quite old. It uses kong 0.8.x which makes it useless for me.

I was hoping to find something from Mashape for plugin developers. Has my google foo failed me?

**Comment by thibaultcha** [comment]
We have plans to release a suite of testing tools that would be independent of the main Kong repository for plugins developers in the future, but nothing so far. In the meanwhile, you would have to familiarize yourself with Lua testing frameworks and build your own solution (you can get inspiration from the Kong testing suite).

**Comment by AntonioCS** [comment]
@thibaultcha Great.... thanks for the help.

**Comment by Tieske** [comment]
@Dinah-C-J situation remains unchanged for Docker. Those distro's are for running Kong, not for developing.

May I suggest you use the [Kong-Vagrant box](https://github.com/Kong/kong-vagrant)? It includes everything you need, and the instructions are step by step including testing the [template plugin](https://github.com/Kong/kong-plugin).

**Comment by AntonioCS** [comment]
@Tieske This is the wrong approach. 
Relying on vagrant when also using docker is horrible in windows (you normally can only run one or the other).
When I was working on kong I was using exclusively the docker version for my development as I had other things running on my machine and couldn't run something as heavy as vagrant (the machine wasn't great)

**Comment by Tieske** [comment]
@AntonioCS 

> This is the wrong approach.

By what measure?

I do see your point in that it is not the optimal solution for you. That said, we cannot help that you have limitations; docker+vagrant, windows in general, and too little hardware.

What we have available is the vagrant box, and we support it in the best way we can (many of our own engineers use it). As I said, it contains detailed step-by-step instructions to get anyone going.

Now if your limitations prevent you from using it, then that's too bad. Maybe you can use the repo for inspiration to create a similar Dockerfile for example, if that works better for you. If you do, then please share it with the community so it can benefit others with similar limitations.

**Comment by Dinah-C-J** [comment]
Thanks @Tieske.  I am using kong-vagrant locally and it works perfectly fine. But our actual instances are docker containers so was fishing something for it. I shall explore something new and see if I can get to something on it

**Comment by AntonioCS** [comment]
@Tieske It's not the optimal solution for me nor is it for most people.
If you are using docker why would you use vagrant?

You can do everything that you do in vagrant in docker but it is much more lightweight and does not break down as much. Most of the times when I used vagrant, there would be something wrong with it (some update of something that ran in the machine).

With docker you have a sense of all the parts that are important to what you actually want to do, with vagrant you are just using another full blown OS.

And your remark regarding the hardware limitation would probably "hit" other devs as well. When we join a company we work with what is given, it is rare for a dev to make demands regarding his hardware.

It is foolish for the kong team not to provide docker alternatives for everything.

**Comment by Tieske** [comment]
@Dinah-C-J glad to hear it works for you. If you come up with something docker based, that would be a welcome contribution 👍 

@AntonioCS This is an open source project, provided for free. Maybe try your luck with some other open source projects and see how willing they are to provide _"alternatives for everything"_. The gist here is that there is a set up for it. If you don't like it for some reason, feel free to contribute an alternative.

If you contribute a docker based development environment, I'll try my best to help you out with any issues you encounter. But please do not ask us to do things (for free) to solve your problems, because you don't want to contribute them yourself.

**Comment by Presto412** [comment]
@Tieske Is there any progress on the dockerized testing suite? quoting ([above reply](https://github.com/Kong/kong/issues/1901#issuecomment-271364663)).
 I found an equivalent version here - https://github.com/inspectorioinc/docker-kong-plugin-tests that maintains a dockerfile that has the dependencies like busted and the spec.helpers file.  I couldn't get it to work however.

@Dinah-C-J If you don't mind me asking, could you please tell me what you went with finally?

**Comment by Tieske** [comment]
@Presto412 have you tried Pongo? https://github.com/Kong/kong-pongo

**Comment by Presto412** [comment]
I figured I could use it, but i don't want to have it run docker-in-docker mode (since we're intending to use k8s pods as Jenkins agents).

**Comment by Tieske** [comment]
best there is is https://github.com/Kong/kong-pongo#running-pongo-in-docker ...

**Comment by Presto412** [comment]
Alright, I'll see what I can do with it. If we get a VM agent, should work
