### ISSUE TITLE
Unable to re-compile Kong. Corrupted rock lualogging-1.3.0-1.src.rock ?

### ISSUE THREAD

**Issue by pamiel** [Mashape/kong#1902]
### Summary

I’m trying to recompile Kong under Alpine.
The compilation and configuration of the pre-requisites (OpenResty, Luarocks, Serf) is working fine, but when reaching the installation of Kong, I face the following error (using the “--verbose"):

```
Missing dependencies for luasyslog:
lualogging >= 1.1.4

Using https://luarocks.org/lualogging-1.3.0-1.src.rock... switching to 'build' mode

os.execute:     unzip -n '/tmp/luarocks_luarocks-rock-lualogging-1.3.0-1-3759/lualogging-1.3.0-1.src.rock'
Archive:  /tmp/luarocks_luarocks-rock-lualogging-1.3.0-1-3759/lualogging-1.3.0-1.src.rock
  inflating: lualogging-1.3.0-1.rockspec
unzip: invalid zip magic 8CB48D2E
Results: 1
  1 (number): 256

Error: Failed installing dependency: https://luarocks.org/luasyslog-1.0.0-2.src.rock - Failed installing dependency: https://luarocks.org/lualogging-1.3.0-1.src.rock - Failed unpacking rock file: /tmp/luarocks_luarocks-rock-lualogging-1.3.0-1-3759/lualogging-1.3.0-1.src.rock

```
This happens whatever using the “luarocks install” or the “git clone” and then “make install”

Is the lualogging-1.3.0-1.src.rock corrupted?

### Steps To Reproduce

1. Install Openresty
2. Install Luarocks
3. Install Serf

4. git clone git@github.com:Mashape/kong.git
5. make install

or
4. luarocks install kong 0.9.6-0

(full installation script available on demand)
### Additional Details & Logs

- Kong version 0.9.6
- Operating System: Alpine

**Comment by Tieske** [comment]
This is what I get:

```shell
mashapes-mbp-2:kong thijs$ luarocks install lualogging
Installing https://luarocks.org/lualogging-1.3.0-1.src.rock
lualogging 1.3.0-1 is now installed in /usr/local (license: MIT/X11)

mashapes-mbp-2:kong thijs$
```
My first guess is that the underlying zip utility deviates from what LuaRocks expects. Mainly because that specific rock is a pure-Lua rock.

probably best to check the luarocks mailing list.
