### ISSUE TITLE
kong and  kong-postgresql

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1904]
Kongserver must rely on postgresql database? Postgresql database failure, kong is still able to provide services?

**Comment by Tieske** [comment]
Kong will cache most if its data in memory, so it will continue to work if the situation meets some requirements;

 - data must have been requested at least once before
 - too much data might cause elements to be eveicted from the in memory cache, and cause failures anyway
 - any plugin that requires database access (eg. cluster wide ratelimiting will probably fail its functionality)

In case you're worrying about production scenario's you might want to checkout Cassandra as a datastore as it provides excellent redundancy if operated in a proper cluster.
