### ISSUE TITLE
File Log Plugin not write the detail of response

### ISSUE THREAD

**Issue by sanmingzi** [Mashape/kong#1905]
### Summary

Hi, I am using File Log Plugin to write log of kong to disk.
I can see the status/size and some other thing in the reponse, but I can not found a detail of the response message.
For example, result message like that

```
{:error_code => 200, :error_msg => 'Some thing wrong'}
```

I can not found this in the log.
Thank you!

**Comment by thefosk** [comment]
@sanmingzi the logging plugins are not currently logging the bodies of request/responses. It seems like you would need that.

**Comment by sanmingzi** [comment]
Should I modify the source code in logging plugins to support the feature ?
Do you have source to do it or add it into the roadmap ?

**Comment by thefosk** [comment]
Reading the bodies can be very expensive. You can fork the plugin and update it if you want. Or you can use the Galileo plugin which already provides a way of logging bodies.
