### ISSUE TITLE
Custom plugins not getting loaded in 0.9.6

### ISSUE THREAD

**Issue by prabhakar-pal** [Mashape/kong#1906]
### Summary

Custom plugins not getting loaded in 0.9.6 when configured in the kong configuration file

### Steps To Reproduce

As per the documentation, we need to do the following to enable a custom plugin

lua_package_path = <path of the plugin modules>
custom_plugins = <PluginName>

But we are seeing that the custom plugin is not getting loaded with the following configuration.

### Additional Details & Logs

- Kong version is 0.9.6
- Tested on Ubuntu 16.04 

### Further analysis: 

- if we edit kong/templates/kong_defaults.lua to add the custom plugin to "custom_plugins", we  see that the plugin is getting loaded, but this is not a good solution

- This is my observation:

Phase 1: when --conf option is set in cli arguments, it is processed by kong CLI. Kong then generates /usr/local/kong/kong.conf (path decided by "prefix" setting) . This conf file does not have custom-plugin settings.
Phase 2: It then invokes nginx which will init kong module. But for this, kong uses /usr/local/kong/kong.conf which does not have the information about the custom plugins.
But adding to kong/templates/kong_defaults.lua worked because at the second phase, we read kong_defaults.lua again and merge with settings in /usr/local/kong/kong.conf .

### Workaround

diff --git a/kong/conf_loader.lua b/kong/conf_loader.lua
index 276fd05..a4ea21c 100644
--- a/kong/conf_loader.lua
+++ b/kong/conf_loader.lua
@@ -335,7 +335,7 @@ local function load(path, custom_conf)
custom_plugins[plugin_name] = true
end
conf.plugins = tablex.merge(constants.PLUGINS_AVAILABLE, custom_plugins, true)
conf.custom_plugins = nil
--conf.custom_plugins = nil
setmetatable(conf.plugins, nil) -- remove Map mt
end

**Comment by Tieske** [comment]
see also discussion here; https://gitter.im/Mashape/kong?at=5855c5ce058ca967375d58ff

**Comment by thibaultcha** [comment]
Thanks for reporting, #1910 takes care of that.
