### ISSUE TITLE
List APIs pagination does not work with postgres DB backend

### ISSUE THREAD

**Issue by endeepak** [Mashape/kong#1912]
### Summary
Kong configured with postgres DB has these issues

1. The offset returned in 'List APIs' api remains same regardless of page size 
2. Call to url returned by previous call `response['next']` returns same response as previous url

### Steps To Reproduce

* The offset returned in 'List APIs' api remains same regardless of page size

```sh
// call with size=1
$ curl localhost:8001/apis?size=1
{
  "total": 87,
  "data": [
    {
      "name": "api1",
      .......
    }
  ],
  "offset": "Mg==",
  "next": "http://localhost:8001/apis?size=1&offset=Mg%3D%3D"
}

// call with size=2
$ curl localhost:8001/apis?size=2
{
  "total": 87,
  "data": [
    {
      "name": "api1",
      .......
    },
    {
      "name": "api2",
      .......
    },
  ],
  "offset": "Mg==",
  "next": "http://localhost:8001/apis?size=2&offset=Mg%3D%3D"
}
``` 

* Call to url returned by previous call `response['next']` returns same response as previous url

```
curl http://localhost:8001/apis?size=1&offset=Mg%3D%3D
{
  "total": 87,
  "data": [
    {
      "name": "ap1",
      ..........
    }
  ],
  "offset": "Mg==",
  "next": "http://localhost:8001/apis?size=1&offset=Mg%3D%3D"
}
```

### Additional Details & Logs

- Kong version : 0.9.3
- Operating System: Ubuntu 14.04

**Comment by thefosk** [comment]
@endeepak The offset can be, and sometimes even expected to be, what changes is the `size` property value and the combination of `size` and `offset` should be unique.

Regarding your second point I don't understand the problem. Could you clarify?

**Comment by endeepak** [comment]
Clarification for 2nd point:
* There are 'N' apis on boarded in kong with name api1, api2,....,apiN
* Make a request to kong admin `GET /apis?size=1`. This API returns paginated response with `data: [{name: "api1"}]` and url for the next page as `next: "/apis?size=1&offset=xyz"`
* When a request is made to `/apis?size=1&offset=xyz` (the next page url returned in previous call response), it returns "api1" again. The correct behaviour would be to return one of the "api2" to "apiN"

Regarding first point, I don't understand how an offset can be same for various page size. I tried making this request with page size as 1,5,10,50. All of them returned same offset. The offset remains same even after making call to next page.

Also the offset value `Mg==` returned by this API is quite interesting. Is there any documentation on how an offset value like `Mg==` will be converted to offset in postgres sql query?

**Comment by Tieske** [comment]
> Regarding first point, I don't understand how an offset can be same for various page size. I tried making this request with page size as 1,5,10,50. All of them returned same offset. The offset remains same even after making call to next page.

It depends whether the `offset` represents a record number, or a page number. From what @thefosk  wrote before, I understand it represents a page number.

That said; simple test with 2 apis and `size=1` does fail for me as described

**Comment by Tieske** [comment]
Not a bug, but a user error. When adding more than 1 query argument, the ampersand `&` needs to be escaped or in quotes for the shell interpreter.

I've had one like this before, man I'm an idiot for not seeing it right away. :angry:
