### ISSUE TITLE
multi slashes between host and path

### ISSUE THREAD

**Issue by HenryChelsea** [Mashape/kong#1924]
### Summary
Kong admin api: /v1 (`kong 0.9.5`)

`http://api.xxx.com//v1`can not be routed
`http://api.xxx.com/v1 ` is ok.

I knew that nginx allows multi slashes.(`host//path`)

**Comment by Tieske** [comment]
Didn't check it, but the double slash is not a legal uri iirc.

My estimate of the impact of changing this is rather high. So I'd classify this as a 'won't fix'.

Unless I'm missing something?

**Comment by HenryChelsea** [comment]
@Tieske 
My api is `/v1`.
When I call `http://api.mine.com//v1`, it returns :
`{"request_path":"\/\/v1","message":"API not found with these values","request_host":["192.168.88.10"]}`

And I have checked the nginx conf.( [merge_slashed](http://nginx.org/en/docs/http/ngx_http_core_module.html))

```
   Syntax:	merge_slashes on | off;
   Default:	
   merge_slashes on;
   Context:	http, server
```
Thanks.

**Comment by HenryChelsea** [comment]
@Tieske 
I have another issue.
When I call `http://api.mine.com/v1?z=1&a=2`, my backend received as follow.
```
"url": "/v1?a=2&z=1"
```

As you can see,  wrong order. In my apis, order is very important!

**Comment by HenryChelsea** [comment]
@Tieske I knew the reason.
`ngx.var.request_uri` 
`ngx.var.uri`

Thanks for your help.
