### ISSUE TITLE
Kong postgresql and Cassandra recommend which? What's the difference?

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1925]
I am currently using the postgresql, and Cassandra What is the difference (high availability)?

**Comment by thefosk** [comment]
Postgres is relation master-slave DB, Cassandra is eventually consistent master-less DB. Different models. If Postgres is working good for you, stick with it.

**Comment by huyifanstar** [comment]
Ok ， thanks！ what is recommended? Both can?
