### ISSUE TITLE
question about security

### ISSUE THREAD

**Issue by peacemakr** [Mashape/kong#1926]
I apologize in advance if this may have been asked before. I had an existing publicly accessible express-style app and I now included a Kong API gateway (OAuth2 protected) to access the same API endpoints (for 3rd party apps/consumers).

My question is: On the API endpoints, how do I verify if the request actually came from Kong and not from any other source (ie. through direct public access)? I understand that Kong sets certain headers etc but anyone can do it using CURL etc (correct me if I'm wrong). Is there a special header param I should be checking that cannot be forged? 

Do I have to make any design changes on the app side or use any special plugins?  

I have CORS plugin enabled.

- Kong version 0.9.5
- Operating System Linux Ubuntu

**Comment by Tieske** [comment]
that is mainly an infrastructure question. You should shield your internal servers from outside access. Nothing else you can do, besides providing each server/app with their own authentication.

**Comment by peacemakr** [comment]
Yes, I know its infrastructure but its related to Kong ie. I want to know if Kong provides a solution or any other possibilities.

Here is what I'm thinking of doing and would appreciate feedback (might be helpful for others too):

I have put HAproxy infront of the API endpoints and now both Kong and end-users can access the endpoints through HAproxy.
I'd now be checking for x-forwarded-for and if its coming through Kongs' IP addresses, I'd accept other OAuth params else ignore them.

**Comment by peacemakr** [comment]
Can I make Kong forward some other extra params like password etc to make sure its Kong is sending the req?

**Comment by Tieske** [comment]
> Can I make Kong forward some other extra params like password etc to make sure its Kong is sending the req?

You can use the request transformer to add a header with a key-phrase

And that is the only way, as Kong will be the only one knowing the secret, any other generic artefact can be inserted by an external imposter as well and hence will never be secure.

**Comment by peacemakr** [comment]
yep, thanks. I had figured it out and works like a charm :)
