### ISSUE TITLE
Mac os 10.12.1 build kong test error

### ISSUE THREAD

**Issue by robert2020** [Mashape/kong#1927]
localhost:kong-0.9.7 user$ make test
●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●◼◼●●●●●◼◼●●●◼◼●◼◼◼◼◼◼◼◼◼◼◼◼◼◼●◼●●◌●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
197 successes / 21 failures / 0 errors / 1 pending : 0.731849 seconds

Pending → spec/01-unit/04-utils_spec.lua @ 33
Utils is_valid_uuid() invalidates UUIDs with invalid variants

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 22
NGINX conf compiler gen_default_ssl_cert() auto-generates SSL certificate and key
spec/01-unit/03-prefix_handler_spec.lua:23: could not generate default SSL certificate: Generating RSA private key, 1024 bit long modulus
....++++++
..++++++
e is 65537 (0x10001)

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:23: in function <spec/01-unit/03-prefix_handler_spec.lua:22>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 27
NGINX conf compiler gen_default_ssl_cert() does not re-generate if they already exist
spec/01-unit/03-prefix_handler_spec.lua:28: could not generate default SSL certificate: Generating RSA private key, 1024 bit long modulus
........................................................++++++
...............++++++
e is 65537 (0x10001)

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:28: in function <spec/01-unit/03-prefix_handler_spec.lua:27>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 89
NGINX conf compiler compile_kong_conf() compiles without anonymous reports
spec/01-unit/03-prefix_handler_spec.lua:94: bad argument #2 to 'matches' (string or object convertible to a string expected, got (nil))

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:94: in function <spec/01-unit/03-prefix_handler_spec.lua:89>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 96
NGINX conf compiler compile_kong_conf() compiles with anonymous reports
spec/01-unit/03-prefix_handler_spec.lua:101: bad argument #2 to 'matches' (string or object convertible to a string expected, got (nil))

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:101: in function <spec/01-unit/03-prefix_handler_spec.lua:96>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 127
NGINX conf compiler compile_nginx_conf() compiles with opinionated nginx optimizations
spec/01-unit/03-prefix_handler_spec.lua:132: bad argument #2 to 'matches' (string or object convertible to a string expected, got (nil))

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:132: in function <spec/01-unit/03-prefix_handler_spec.lua:127>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 151
NGINX conf compiler prepare_prefix() creates inexistent prefix
spec/01-unit/03-prefix_handler_spec.lua:159: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:159: in function <spec/01-unit/03-prefix_handler_spec.lua:151>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 175
NGINX conf compiler prepare_prefix() creates pids folder
spec/01-unit/03-prefix_handler_spec.lua:176: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:176: in function <spec/01-unit/03-prefix_handler_spec.lua:175>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 179
NGINX conf compiler prepare_prefix() creates serf folder
spec/01-unit/03-prefix_handler_spec.lua:180: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:180: in function <spec/01-unit/03-prefix_handler_spec.lua:179>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 183
NGINX conf compiler prepare_prefix() creates NGINX conf and log files
spec/01-unit/03-prefix_handler_spec.lua:184: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:184: in function <spec/01-unit/03-prefix_handler_spec.lua:183>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 190
NGINX conf compiler prepare_prefix() dumps Kong conf
spec/01-unit/03-prefix_handler_spec.lua:191: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:191: in function <spec/01-unit/03-prefix_handler_spec.lua:190>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 195
NGINX conf compiler prepare_prefix() dump Kong conf (custom conf)
spec/01-unit/03-prefix_handler_spec.lua:201: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:201: in function <spec/01-unit/03-prefix_handler_spec.lua:195>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 205
NGINX conf compiler prepare_prefix() writes custom plugins in Kong conf
spec/01-unit/03-prefix_handler_spec.lua:211: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:211: in function <spec/01-unit/03-prefix_handler_spec.lua:205>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 217
NGINX conf compiler prepare_prefix() dumps Serf script
spec/01-unit/03-prefix_handler_spec.lua:218: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:218: in function <spec/01-unit/03-prefix_handler_spec.lua:217>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 223
NGINX conf compiler prepare_prefix() dumps Serf identifier
spec/01-unit/03-prefix_handler_spec.lua:224: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:224: in function <spec/01-unit/03-prefix_handler_spec.lua:223>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 229
NGINX conf compiler prepare_prefix() preserves Serf identifier if already exists
spec/01-unit/03-prefix_handler_spec.lua:231: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:231: in function <spec/01-unit/03-prefix_handler_spec.lua:229>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 241
NGINX conf compiler prepare_prefix() ssl does not create SSL dir if disabled
spec/01-unit/03-prefix_handler_spec.lua:247: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:247: in function <spec/01-unit/03-prefix_handler_spec.lua:241>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 250
NGINX conf compiler prepare_prefix() ssl does not create SSL dir if using custom cert
spec/01-unit/03-prefix_handler_spec.lua:258: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:258: in function <spec/01-unit/03-prefix_handler_spec.lua:250>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 261
NGINX conf compiler prepare_prefix() ssl generates default SSL cert
spec/01-unit/03-prefix_handler_spec.lua:267: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:267: in function <spec/01-unit/03-prefix_handler_spec.lua:261>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 277
NGINX conf compiler prepare_prefix() custom template accepts a custom NGINX conf template
spec/01-unit/03-prefix_handler_spec.lua:278: 

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:278: in function <spec/01-unit/03-prefix_handler_spec.lua:277>

Failure → spec/01-unit/03-prefix_handler_spec.lua @ 286
NGINX conf compiler prepare_prefix() custom template errors on non-existing file
spec/01-unit/03-prefix_handler_spec.lua:289: Expected objects to be equal.
Passed in:
(string) ''
Expected:
(string) 'no such file: spec/fixtures/inexistent.template'

stack traceback:
        spec/01-unit/03-prefix_handler_spec.lua:289: in function <spec/01-unit/03-prefix_handler_spec.lua:286>

Failure → spec/01-unit/04-utils_spec.lua @ 12
Utils get_system_infos() retrieves various host infos
spec/01-unit/04-utils_spec.lua:14: Expected objects to be the same.
Passed in:
(nil)
Expected:
type number

stack traceback:
        spec/01-unit/04-utils_spec.lua:14: in function <spec/01-unit/04-utils_spec.lua:12>

make: *** [test] Error 1

**Comment by Tieske** [comment]
@robert2020 This is not realy helpful. Can you please provide all the infos as requested? os/version/etc.

First thing that comes to mind is a permission failure

**Comment by Tieske** [comment]
> Can you please provide all the infos as requested? os/version/etc.

oops sorry, just noted them in the issue description

**Comment by robert2020** [comment]
os macOS Sierra  10.12.1 (16B2555)
kong code version: 0.9.7 
openresty:  1.11.2.2
lua :5.1
luarocks:5.1
sudo luarocks make  pass
sudo make dev  pass
sudo make test error

thanks

**Comment by Tieske** [comment]
Can't reproduce this, but then again I'm not on OS X Sierra.

Maybe @thibaultcha or @thefosk can

**Comment by thefosk** [comment]
I am on Sierra and I cannot reproduce this error. I am using `OpenSSL 1.1.0c`.

**Comment by thibaultcha** [comment]
> I am using OpenSSL 1.1.0c.

That is quite unlikely since OpenResty is not compatible with OpenResty 1.1.0. You might think so because maybe you are hitting the EL Captain + clang issue.

@robert2020 It seems you have some issues with your environment/installation but it is unclear what is wrong exactly. Maybe some more investigation on your side form a few of the failing tests in `prefix_handler_spec` could help us narrow this down.

**Comment by Tieske** [comment]
closing this due to lack of response
