### ISSUE TITLE
How to send multiple scope data for getting authorization code?

### ISSUE THREAD

**Issue by joyfulkid** [Mashape/kong#1930]
I tried to send multiple scope for getting access_code via "https://kong_url:8443/oauth2/authorize"
When sending just one scope is OK, but multiple scope, that is separated by '**,**', I just got the message "invalid_scope".

I think I missed something to send multiple scope, what's wrong with my request.
But I could not found some good solution.

The string below is my request for getting access_code.
**$ curl -X POST https://my_kong_api_url/oauth2/authorize \
    --data "client_id=dcf9c1e96ad448578f97187a12d6e655" \
    --data "response_type=code" \
    --data "scope=UserName,Email" \
    --data "provision_key=my_provision_key_here" \
    --data "authenticated_userid=testuser01"**

And this is a plugin information of Kong I used.
{
    "api_id": "c1dbb860-47d2-499a-8be0-dba49c3e9aa9",
    "id": "7e990ce4-5155-4141-8e23-544350483ffb",
    "created_at": 1482465680000,
    "enabled": true,
    "name": "oauth2",
    "config": {
        "mandatory_scope": false,
        "token_expiration": 7200,
        "enable_implicit_grant": false,
        "scopes": [
            "UserName",
            "Email"
        ],
        "hide_credentials": false,
        "provision_key": "my_provision_key_here",
        "accept_http_if_already_terminated": false,
        "enable_authorization_code": true,
        "enable_client_credentials": false,
        "enable_password_grant": false
    }
}

Please help me to escape my insoluble problem.
thanks.

### Additional Details 

- Kong version (0.9.5)
- Linux on AWS
- with Docker

**Comment by joyfulkid** [comment]
I found how to send more than 2 scopes for getting authorization code in the source of Kong.
thanks~

**Comment by Tieske** [comment]
@joyfulkid Glad it works. As a suggestion; maybe next time post how you did it in case someone else stumbles on the issue. Thx.

**Comment by eyalkenig** [comment]
You should use `space` separator for multiple scopes.
for example:
--data "scope=UserName Email"

**Comment by shaikmeeran** [comment]
Hi as i am new to kong and came across a variable names scopes in config.  i was wondering how does config.scopes used in OAuth in Kong and how should it be utilized under my application based on what need.

someone kindly help me out 

thank you.

**Comment by janrsilva** [comment]
Hi @Tieske, 

I can see in the doc the specification to OAuth2 Plugin, just [here](https://getkong.org/plugins/oauth2-authentication/#configuration)

So in Configuration section it said about **Scope** _"Describes an array of comma separated scope names that will be available to the end user"_
OK yet ;)

But in the **OAuth 2.0 Flows** right [here](https://getkong.org/plugins/oauth2-authentication/#oauth-2-0-flows) it show in the step 5 a sample request to get a token with the scope `scope=XXX`.

The case is, I did not find any doc explain about the format that **must** be sent the scope in the authorize step.

I got the same problem of @joyfulkid, read this issue, saw the [code](https://github.com/Mashape/kong/blob/0742c3447fddb8721758273e21108fc3910e8beb/kong/plugins/oauth2/access.lua#L105) and get the [solution](https://github.com/Mashape/kong/issues/1930#issuecomment-279688353) (scope of space separated names)

Can anyone add a section in the doc about how use the scope of space separated names in authorize steps?

Thank you by Kong.

**Comment by Tieske** [comment]
@janrsilva would you mind sending a PR? the doc s are here: https://github.com/Mashape/getkong.org/blob/master/app/plugins/oauth2-authentication.md
