### ISSUE TITLE
kong admin status endpoint causes cluster outage

### ISSUE THREAD

**Issue by ThorArakis** [Mashape/kong#1931]
### Summary

We have a cluster that has a couple of tables that are very large (rate limit tables) and if we hit the `/status` endpoint it can take down our entire cluster. I'm guessing that this is due to the `count(*)` statement that's being run on each of the tables which is a very heavy operation to run on a distributed data base. When trying to run the count* from cqlsh the operation was taking minutes before I killed it.

### Current set up
We are currently running kong 8 using cassandra as our DB. 
Current size of one of our rate limit tables (from nodetool cfstats):
 Number of keys (estimate): 16948049

### Additional Details & Logs
- kong version: 0.8.3
- Operating System: Ubuntu 14.04.5 LTS

**Comment by shivasurya** [comment]
@thefosk any points or suggestions on this ? I'll try to work on this bug.

**Comment by mbugeia** [comment]
Hi, I have I think a similar issue with the /status endpoint. It's very (very) slow and every request generate warning logs in cassandra:

WARN  [SharedPool-Worker-1] 2017-03-20 14:05:53,970 SelectStatement.java:253 - Aggregation query used without partition key

I'm running kong 0.10.0 BTW

@ThorArakis do you observe the same log in cassandra ?

**Comment by shivasurya** [comment]
counting is expensive operation when data set is too large. The engineering solution is to index the database properly to speed up the query performance. so we must look for indexing the database i hope.

**Comment by mbugeia** [comment]
Yes, but does the count need to be done on every tables ? 
Given the sample response following (which take ~8s in my case) I have trouble to understand what can take so much time. The "server" section is retrieved from the local nginx_status route and the "database" from some kong table but none that should be very large. kong.ratelimiting_metrics does not need to be counted for exemple. 
```
curl "http://localhost:8001/status" |jq
{
  "server": {
    "connections_handled": 35714,
    "connections_reading": 0,
    "connections_active": 2,
    "total_requests": 35714,
    "connections_accepted": 35714,
    "connections_writing": 1,
    "connections_waiting": 1
  },
  "database": {
    "oauth2_credentials": 0,
    "jwt_secrets": 0,
    "plugins": 10,
    "keyauth_credentials": 1,
    "oauth2_authorization_codes": 0,
    "ssl_servers_names": 0,
    "acls": 1,
    "basicauth_credentials": 0,
    "apis": 3,
    "hmacauth_credentials": 0,
    "consumers": 1,
    "oauth2_tokens": 0,
    "targets": 0,
    "nodes": 2,
    "upstreams": 0,
    "ssl_certificates": 0
  }
}
```

**Comment by p0pr0ck5** [comment]
This was fixed in https://github.com/Mashape/kong/pull/2567.
