### ISSUE TITLE
Kong  working flow ，(preserve_host=true)

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1932]
1. user request kongserver LB
2.Kongserver through pre-configured API records to request the actual node 
3.Kongserver returns to the user 

My guess is correct？
thanks！

**Comment by depay** [comment]
the same working flow as normal nginx

- request:  client -> kong(openresty/nginx) -> realserver
- response:  realserver -> kong(openresty/nginx) -> client

it has no relationship with `preserve_host` arg which decides whether keeping `Host` header in http request.

**Comment by huyifanstar** [comment]
preserve_host=true  ,  What is the function?

thanks!

**Comment by depay** [comment]
when nginx forwarding request `mock.domain` to real server, e.g. `node-01.xxx`, the header `Host` will be `node-01.xxx` by default, while some real server or next proxy requires that header `Host=mock.domain` strictly for filtering or other purpose. `preserve_host` solves that problem.

**Comment by huyifanstar** [comment]
OK, thank  you！
