### ISSUE TITLE
Using external list of authorized domains for CORS

### ISSUE THREAD

**Issue by MaineKampfCoon** [Mashape/kong#1933]
Hi there! I'm lookin for right way to construct CORS headers by getting domain list from Consul API for example. I'm trying to find out is it right way to getting list domains from Consul https://www.consul.io/docs/agent/http/catalog.html and if domain that Kong should redirect to according to one of them, construct CORS with allowing this domain or not.
CORS plugin stacked me, does he allow to static definition only? It's hard to support plugin's data in actual state. Does my thoughts have meaning?

**Comment by thibaultcha** [comment]
The documentation for the CORS plugin (that you have probably already consulted) is available at: https://getkong.org/plugins/cors/

It is complete and the plugin does what is documented, aka enabling CORS headers on the API on which it is enabled on. Beyond that, I am unsure what is your actual question, so please elaborate on what is your use-case.

**Comment by MaineKampfCoon** [comment]
Ok, I'll try to explain, 
According to CORS plugin documentation, I have to fill out "config.origin=mockbin.com" where domains as static string. My question is about way to use any dynamic list of Origin domains, for example – Consul API that contains of all of my front-ends. Other way is changing Origin domains every time new front-ends comes to the system.

**Comment by Tieske** [comment]
considering this answered, closing
