### ISSUE TITLE
query dns from consul without port,upstream_url will be wrong!

### ISSUE THREAD

**Issue by darren-fu** [Mashape/kong#1937]
### Summary
I register my service to Consul, and Kong query dns from Consul , but Kong just get IP of the service from consul.
so the upstream_url will be like this: http://ip_from_consul:80/request_path.
the port will always be 80, any help here?

- Kong version (`0.9.7`)

**Comment by Tieske** [comment]
Kong does not support SRV records, hence it will not even get the port from Consul.

That said, the `next` branch already has SRV support, which is scheduled to be released shortly.
