### ISSUE TITLE
Token already exists with value

### ISSUE THREAD

**Issue by carbeman** [Mashape/kong#1938]
### Summary

A strange thing occurs on my system. Currently i'm using Kong with oAuth2 plugin. After many tests, Kong started to give me back this error:

2017/01/03 17:35:28 [error] 4220#0: *9830 [lua] responses.lua:101: generate_token(): [postgres error] id=already exists with value 'e89fa920-e952-4883-89b8-e52d27c19141', client: 10.65.3.9, server: kong, request: "POST /token/oauth2/token HTTP/1.1", host: "my.kong.host:443"

The client receive a HTTP response with code: 200 and body: {"message":"An unexpected error occurred"}

I have looked around the code and seems that the UUID creation is demanded to postgres. At the moment i don't know what to check.

Any suggestions?

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version: 0.9.5
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System: Debian 8.6

**Comment by thibaultcha** [comment]
How many nodes do you run ?

**Comment by carbeman** [comment]
Only one node

Il mar 3 gen 2017, 18:58 Thibault Charbonnier <notifications@github.com> ha
scritto:

**Comment by carbeman** [comment]
Anyone has a suggestion?

**Comment by thibaultcha** [comment]
@carbeman Could you make a request to `/` on the Admin API and verify the `prng_seeds` values? All of the seeds in there should be different to ensure the uniqueness of the generated UUIDs.

**Comment by carbeman** [comment]
Thanks @thibaultcha for the response.
Everything seems ok.

`"prng_seeds" : {
      "pid: 16739" : 124150942361
   },
`

**Comment by p0pr0ck5** [comment]
@carbeman do you still see this behavior when using Kong 0.10+?

**Comment by thibaultcha** [comment]
@carbeman Make sure that you have the following directive in your Nginx configuration (especially if you are using a custom template):
```nginx
lua_shared_dict kong 4m;
```

**Comment by carbeman** [comment]
@p0pr0ck5 with 0.10 version the problem does not seem to appear.

**Comment by carbeman** [comment]
@thibaultcha with the previous version 0.9.5 i had already fixed the problem by adding the missing dict to the nginx template.

Currently with the latest version the issue has not been presented yet.

**Comment by thibaultcha** [comment]
Good to know, it should be fixed. Let us know if it happens again. Thanks!
