### ISSUE TITLE
Attempt to index field 'upstream' (a nil value) (Kong v0.10.0rc1)

### ISSUE THREAD

**Issue by sisp** [Mashape/kong#1944]
When setting an invalid upstream URL (e.g. ``http://mockbincom`` - I accidentally forgot the "." when I discovered this bug), Kong responded with an internal error and the following message in the error log:

```
2017/01/06 13:50:03 [error] 89#0: *1842 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/core/handler.lua:119: attempt to index field 'upstream' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/core/handler.lua: in function 'before'
	/usr/local/share/lua/5.1/kong.lua:240: in function 'access'
	access_by_lua(nginx-kong.conf:80):2: in function <access_by_lua(nginx-kong.conf:80):1>, client: 172.20.0.1, server: kong, request: "GET /my/test/uri HTTP/1.1", host: "my.test.host"
```

Looking at the file ``core/handler.lua``, I believe that ``balancer_address.upstream.host`` should be ``balancer_address.host``.

Could anyone have a look at this issue?

Thanks,
Sigurd

**Comment by Tieske** [comment]
@sisp thx! fixed in the `new-router` branch, waiting for that to get merged into `next`
