### ISSUE TITLE
Kong v0.10.0rc1 start with cassandra,  raised error

### ISSUE THREAD

**Issue by liu0013** [Mashape/kong#1949]
I try to run https://github.com/Mashape/docker-kong/blob/_0.10.0rc1_/Dockerfile with Cassandra(v2.2.8) 
Here is a error.log from kong
2017/01/08 04:26:59 [warn] 76#0: [lua] globalpatches.lua:228: randomseed(): math.randomseed() must be called in init_worker context
stack traceback:
	/usr/local/openresty/lualib/resty/dns/resolver.lua:951: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/kong/core/globalpatches.lua:358: in function </usr/local/share/lua/5.1/kong/core/globalpatches.lua:3>
	/usr/local/share/lua/5.1/kong.lua:27: in main chunk
	[C]: in function 'require'
	init_by_lua:3: in main chunk

2017/01/08 04:26:59 [error] 88#0: init_worker_by_lua error: /usr/local/openresty/lualib/resty/lock.lua:153: API disabled in the context of init_worker_by_lua*
stack traceback:
	[C]: in function 'sleep'
	/usr/local/openresty/lualib/resty/lock.lua:153: in function 'lock'
	/usr/local/share/lua/5.1/resty/cassandra/cluster.lua:625: in function 'get_or_prepare'
	/usr/local/share/lua/5.1/resty/cassandra/cluster.lua:833: in function 'execute'
	/usr/local/share/lua/5.1/cassandra/init.lua:411: in function '(for generator)'
	/usr/local/share/lua/5.1/kong/dao/db/cassandra.lua:339: in function 'find_all'
	/usr/local/share/lua/5.1/kong/dao/dao.lua:178: in function 'find_all'
	/usr/local/share/lua/5.1/kong/core/handler.lua:32: in function 'build_router'
	/usr/local/share/lua/5.1/kong/core/handler.lua:61: in function 'before'
	/usr/local/share/lua/5.1/kong.lua:186: in function 'init_worker'
	init_worker_by_lua:2: in main chunk

2017/01/08 04:27:08 [error] 89#0: *6 [lua] events.lua:88: errlog(): worker-events: dropping event; waiting for event data timed ou
t, id: 2, context: ngx.timer
2017/01/08 04:27:15 [warn] 88#0: *4 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key
, context: ngx.timer
2017/01/08 04:27:15 [warn] 88#0: *19 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition ke
y, context: ngx.timer
2017/01/08 04:27:15 [warn] 88#0: *11 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition ke
y, context: ngx.timer
2017/01/08 04:27:16 [warn] 88#0: *30 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition ke
y, context: ngx.timer
2017/01/08 04:27:19 [warn] 88#0: *39 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition ke
y, context: ngx.timer
2017/01/08 04:27:22 [warn] 88#0: *47 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition ke
y, context: ngx.timer
2017/01/08 04:27:25 [warn] 88#0: *55 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition ke
y, context: ngx.timer
2017/01/08 04:27:28 [warn] 88#0: *63 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition ke
y, context: ngx.timer
2017/01/08 04:27:31 [warn] 88#0: *73 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition ke
y, context: ngx.timer
2017/01/08 04:27:34 [warn] 88#0: *81 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition ke
y, context: ngx.timer
2017/01/08 04:27:37 [warn] 88#0: *89 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition ke
y, context: ngx.timer

- Kong version (0.10.0rc1)
- Kong default configuration

kong git:(next) curl -i -X POST \
                     --url http://localhost:8001/apis/ \
                     --data 'name=test' \
                     --data 'upstream_url=http://test:8081/apis/' \
                     --data 'request_host=test.com'

HTTP/1.1 400 Bad Request
Date: Sun, 08 Jan 2017 04:27:18 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.10.0rc1

**Comment by Tieske** [comment]
The first one (randomseed) is just a warning. The second is a bug that has been fixed in a commit I just pushed. The last ones are also warnings.

Thx for the report 👍

**Comment by Tieske** [comment]
fixed in the next rc, closing this

**Comment by SzymonKlimuk** [comment]
Hi, 

I'm getting the same error on kong 0.10.1 and cassandra 3.0.9 installed on centos 7.3.1611:

2017/03/30 09:16:38 [error] 4238#0: *8 [lua] events.lua:88: errlog(): worker-events: dropping event; waiting for event data timed out, id: 3, context: ngx.timer
2017/03/30 09:16:38 [error] 4236#0: *4 [lua] events.lua:88: errlog(): worker-events: dropping event; waiting for event data timed out, id: 2, context: ngx.timer
2017/03/30 09:16:38 [error] 4236#0: *4 [lua] events.lua:88: errlog(): worker-events: dropping event; waiting for event data timed out, id: 3, context: ngx.timer
2017/03/30 09:16:38 [error] 4236#0: *4 [lua] events.lua:88: errlog(): worker-events: dropping event; waiting for event data timed out, id: 4, context: ngx.timer
2017/03/30 09:16:38 [error] 4238#0: *8 [lua] events.lua:88: errlog(): worker-events: dropping event; waiting for event data timed out, id: 4, context: ngx.timer
2017/03/30 09:16:39 [error] 4237#0: *15 [lua] events.lua:88: errlog(): worker-events: dropping event; waiting for event data timed out, id: 4, context: ngx.timer
2017/03/30 09:16:39 [warn] 4236#0: *5 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/03/30 09:16:40 [warn] 4236#0: *22 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/03/30 09:16:45 [warn] 4237#0: *38 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/03/30 09:16:46 [warn] 4237#0: *57 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/03/30 09:16:49 [warn] 4237#0: *73 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/03/30 09:16:52 [warn] 4237#0: *89 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer

I installed the kong and cassandra on the fresh VM:

$ java -version
openjdk version "1.8.0_121" // OK

$ cd  /etc/yum.repos.d/
$ sudo vi datastax.repo

[datastax] 
name = DataStax Repo for Apache Cassandra
baseurl = http://rpm.datastax.com/community
enabled = 1
gpgcheck = 0

$ sudo yum install dsc30
$ sudo yum install cassandra30-tools
$ sudo chkconfig cassandra on
$ sudo service cassandra start
$ sudo yum install epel-release
$ sudo wget https://bintray.com/mashape/kong-rpm-el7-0.10.x/rpm -O bintray-mashape-kong-rpm-el7-0.10.x.repo
$ sudo yum install kong-0.10.1
$ sudo cp /etc/kong/kong.conf.default /etc/kong/kong.conf

$ sudo vi /etc/kong/kong.conf
database = cassandra

$ kong start
