### ISSUE TITLE
[oauth2] Error when POST a file with multipart/form-data

### ISSUE THREAD

**Issue by oktapodia** [Mashape/kong#1952]
### Summary

Hello, I have a little problem with kong, when I try to send a request with the content-type multipart/form-data (oauth2 plugins for the authentication), I received that error in the log and it's impossible to perform the request, my version is 0.9.5, what can I do please?
![pasted image at 2017_01_09 03_01 pm](https://cloud.githubusercontent.com/assets/2752200/21769609/7236f238-d677-11e6-9d47-3aef2fd6b18f.png)

### Steps To Reproduce

1. Configure an oauth2 plugin
2. Add an Api behind
3. Upload a file with the content-type `multipart/form-data`

### Additional Details & Logs
![pasted image at 2017_01_09 02_49 pm 1](https://cloud.githubusercontent.com/assets/2752200/21774517/b735ca90-d68a-11e6-8eee-2c5bb18f4121.png)
![pasted image at 2017_01_09 02_49 pm](https://cloud.githubusercontent.com/assets/2752200/21774523/b8a47e3a-d68a-11e6-98dc-90314ba187aa.png)

- Kong version (0.9.5)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by p0pr0ck5** [comment]
Looks like we need to tread a bit more lightly when `hide_credentials` is configured.

**Comment by thibaultcha** [comment]
Thanks for the fix @p0pr0ck5! Merged, hence closing this.
