### ISSUE TITLE
Enable multiple Authentication plugins

### ISSUE THREAD

**Issue by rajskhanna** [Mashape/kong#1955]
### Summary

We are trying to enable both Key authentication for trusted clients and oauth2 for end users. I am not able to configure authentication plugin for a consumer. May be this is a restriction but it would be nice to have both enabled and authenticate depending on the client. 

### Steps To Reproduce

http post :8001/apis/HelloWorld/plugins name=oauth2 config.enable_authorization_code=true config.scopes=read consumer_id=<consumer id>

Getting the error
 "message": "No consumer can be configured for that plugin"

### Additional Details & Logs

- Kong version 0.9.6
- Operating System OS X 10.11.6 (Docker)

**Comment by Tieske** [comment]
have you seen https://github.com/Mashape/kong/pull/1666 ?

**Comment by Tieske** [comment]
@rajskhanna ping

**Comment by rajskhanna** [comment]
Thanks Tieske. So it looks like if I want to have 2 different type of authentication of an API its not possible Excluding the anonymous access. So as I see it we should be defining 2 paths to accomplish this. right?

**Comment by Tieske** [comment]
Well you cannot add an auth plugin for a specific consumer, as the auth plugin needs to run before you even know which consumer the request is coming from.

An option could be to write a custom plugin that does nothing but preventing anonymous access. Configure it to run after the other plugins and block all unauthenticated requests. Could that work for you?

**Comment by Tieske** [comment]
@rajskhanna ping

**Comment by Tieske** [comment]
closing due to lack of response

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [anonymous users / multiple-auth](https://trello.com/c/EPEDGoDc/36-anonymous-users-multiple-auth)

**Comment by virogenesis** [comment]
It would work for me if this is still a thing @Tieske

**Comment by virogenesis** [comment]
Just for completeness sake, kong solved this with: https://docs.konghq.com/hub/kong-inc/request-termination/

In case anyone else bumps into this thread.

**Comment by rahulgoel27** [comment]
https://docs.konghq.com/0.10.x/auth/
See Multiple Authentication

> Just for completeness sake, kong solved this with: https://docs.konghq.com/hub/kong-inc/request-termination/
> 
> In case anyone else bumps into this thread.
