### ISSUE TITLE
Kong with consul dns to query SRV (consul dns) records

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1956]
#1095 

Kong will be out in 0.1.0 SRV query support?
I now through the allocation
dns_resolver: server
dns_resolvers_available:
   server:
   address: "10.0.0.2:53"

Configuration, how do I fill in 'upstream_url'?
Now whether kong support SRV query?  
kong version:0.9.7

**Comment by thefosk** [comment]
This will be supported in 0.10.0. There is an RC1 available that you can try to use now if you want, but it's not stable yet.

**Comment by huyifanstar** [comment]
Is there more than one instance of the same service name that is also supported in version 0.1.0?
RC1 Do you have an address ？

**Comment by Tieske** [comment]
@huyifanstar here's a description of how it works; https://github.com/Mashape/kong/issues/157#issuecomment-238205952

**Comment by huyifanstar** [comment]
@thefosk   I have seen version 0.10.0rc1. Is there a dockerfile?

**Comment by Tieske** [comment]
not that I know of
