### ISSUE TITLE
Is there a micro service architecture case? Including Kong (api gateway), with application aggregation, discovery, registration of micro-service architecture

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1957]
Now has used the registrato and consul, the lack of application aggregation class components. And also with kongserver together to achieve micro-service architecture.
Implementing the application container from the kong's service entry request backend (and the architecture is dynamically federated)
This framework is reasonable? Is there a better suggestion?
thank you all  !

lb<--->kong<--->consul<--->registrator

**Comment by Tieske** [comment]
Kong does not have aggregation yet, it is a popular feature request though.

**Comment by Tieske** [comment]
see #155
