### ISSUE TITLE
0.10.0 official release time

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1964]
1   Kong in 0.1.0 joined the SRV query, how do I fill in 'upstream_url'?
2   0.10.0 version of what release time is when

**Comment by Tieske** [comment]
1.  SRV is just dns. So just the same as before but make sure that the hostname you use has an SRV record in the dns. 
2. When the next RC is bug free for two weeks, we'll release it. Otherwise another RC follows.

**Comment by huyifanstar** [comment]
OK! Is there a 0.10.0 documentation

**Comment by Tieske** [comment]
In the works. See https://github.com/Mashape/getkong.org/pull/275, https://github.com/Mashape/getkong.org/pull/300 and https://github.com/Mashape/getkong.org/pull/301

more will follow.

**Comment by huyifanstar** [comment]
yes ， There is no way to support? I need to evaluate functionality
