### ISSUE TITLE
0.10.0 Need postgresql support?

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1965]
kong version:0.10.0 
postgresql  9.6

Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] Error during migration 2016-11-11-151900_new_apis_router_2: [postgres error] ERROR: column "https_only" does not exist (142)

**Comment by Tieske** [comment]
`kong migrations reset` will clear the database

does that work for you?, iirc upgrading an existing database is not yet supported by the RC
