### ISSUE TITLE
Kong can automatically update the API via SRV (consul dns)?

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1966]
Kong has consul DNS (SRV) docking, not being given
But how do I write 'upstream_url'?
Kong can automatically update the API via SRV (consul dns)?

curl -i -X POST   --url http://localhost:8001/apis/   --data 'name=testserver' --data 'preserve_host=true'  --data 'request_path=/test' --data 'upstream_url=https://192.168.100.1:8934/'

{"request_path":"request_path is an unknown field"}

kongversion：0.10.0rc1

**Comment by Tieske** [comment]
as explained on gitter; the new 0.10.0 release no longer has `request_path` but a field `uris` instead
