### ISSUE TITLE
One oauth2 plugin can not shared by many apis.

### ISSUE THREAD

**Issue by hongkang** [Mashape/kong#1967]
### Summary

kong's Oauth2 plugin can only support all apis using one plugin, or one api using one plugin, but it does not support one plugin shared by many apis, which has led to the unavailability of Oauth2 plugin in practice. What a pity.

**Comment by Tieske** [comment]
duplicate #1488

**Comment by hoffin** [comment]
I wouldn't see this as a duplicate of #1488 

I agree it's beneficial to be able to assign oauth to a number of api's, not just everyone as this prevents mixing different authorisation methods on the same url. It's does cause huge issues in designing microservice solutions where kong is acting as a sole api gateway.
