### ISSUE TITLE
Kong admin API cannot find consumers when the username contains spaces.

### ISSUE THREAD

**Issue by CyExy** [Mashape/kong#1968]
### Steps To Reproduce

1. Add a consumer with a space in their username e.g. "foo bar"
2. Accessing the consumer by username `/consumers/foo%20bar` returns `404`

### Workaround

Access the consumer by its ID

**Comment by Tieske** [comment]
fixed in the 0.10.0 release branch. Closing.

**Comment by CyExy** [comment]
@Tieske Thanks!
