### ISSUE TITLE
Docs for kong.tools.responses.send() reference removed 'raw' param

### ISSUE THREAD

**Issue by ryancutter** [Mashape/kong#1969]
### Summary

https://getkong.org/docs/0.9.x/lua-reference/modules/kong.tools.responses/ includes a method signature that no longer exists.

```
send (status_code, body, raw, headers)
```

It appears the 'raw' param was [removed 5 months ago](https://github.com/Mashape/kong/commit/82ba5400403b703606796150c60406f5b10a3470#diff-26f55b6db09cbf61679635991f5fa218).

Is there a way to send a raw string response using this method?  For instance, I'd like to return pretty-printed JSON, so:

```content```

not

```cjson.encode {message = content})```

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`0.9`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by thibaultcha** [comment]
Thanks for the report.

You could use the plain `ngx.say()` method to send your responses as-is for now.

**Comment by ryancutter** [comment]
Thanks!  I'm a casual user and don't have the backstory on the removal of 'raw' but my naive feeling is it would be nice to have that option.

**Comment by thibaultcha** [comment]
It is mostly that I am not a fan of necessary abstractions... Until we come up with a proper plugin development API promising backwards compatibility, we'd rather avoid such abstractions.
