### ISSUE TITLE
Release version 0.10 

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1971]
Kongserver Release  version0.10.0, including what features?
Is there a monitoring (health)  check function that I see supporting load balancing and SRV
What other features(RC1)?

This version will join the keepalive health check function?

Does kong support getting the state of the back-end container from the consul's DNS interface and automatically updating the kong API record?

**Comment by thibaultcha** [comment]
https://github.com/Mashape/kong/releases/tag/0.10.0rc1
https://github.com/mashape/kong/compare/0.9.7...0.10.0rc1
https://github.com/Mashape/kong/pull/1587
https://github.com/Mashape/kong/pull/1735

A better and much more complete changelog for 0.10 will follow soon.

As much as we appreciate your interest in Kong, please slow down on the number of issues you are opening in this repository. Many of the questions you asked can be answered by yourself should you do your homework and spend some time documenting yourself and watching the activity in this repository. @Tieske has recently dedicated a lot of his time patiently answering your questions but really you are taking a lot of his time that would be better spent actually working on this project or answering other users...

Thank you.

**Comment by thibaultcha** [comment]
You have opened almost 20 issues in the last month: https://github.com/Mashape/kong/issues?q=is%3Aissue+author%3Ahuyifanstar

**Comment by huyifanstar** [comment]
ok , thanks!
