### ISSUE TITLE
[OAuth2] Secret unique check

### ISSUE THREAD

**Issue by codebien** [Mashape/kong#1972]
Kong: 0.8.3

If I try to add an OAuth2 application with a client_secret that already exists it fails. What is the motivation for this behavior? IMHO, only client_id must be unique, not secrets.

I haven't tried with new versions but code seems not to be changed:
https://github.com/Mashape/kong/blob/master/kong/plugins/oauth2/daos.lua#L37

Thanks

**Comment by p0pr0ck5** [comment]
^ this was merged in last week. Thanks @codebien for the report!
