### ISSUE TITLE
Kong DB queries for plugins are not always cached

### ISSUE THREAD

**Issue by ronan-skyscanner** [Mashape/kong#1974]
[plugins_iterator.txt](https://github.com/Mashape/kong/files/701777/plugins_iterator.txt)
### Summary

We have found that caching of results of plugins DB queries was broken in some cases, resulting in the same DB query being made over and over again.

In kong/kong/core/plugins_iterator.lua in the load_plugin_configuration method, a call to cache.get_or_set() is used to ensure that the DB query will be performed if and only if the value doesn't already exist in the cache.
This works in most cases, but the following case is not handled properly:
Assume plugin X is enabled for API with api_id A only.
On every request to any API, Kong requests from the DAO the list of plugins it should trigger. 
Part of this is to look up the plugins which are enabled globally (api_id = nil and consumer_id = nil).

In the case of plugin X, the DB query will return a single row with api_id=A (#rows > 0). This row then gets filtered out in the subsequent lines (L29), and the for loop is existed without returning any values, and the else clause is never reached, which means no value will be added to the cache, and the same DB query will be made next time, as oppose to find in the cache.

### Steps To Reproduce
1. Create an API and enable a plugin for it
2. Add a breakpoint or debug message in the callback function https://github.com/Mashape/kong/blob/master/kong/core/plugins_iterator.lua#L18. This should show when a call to the DB is made as opposed to using cache
3. Run the same query multiple times
4. Observe that for the plugin enabled above, the call to the datastore is made repeatedly.

### Proposed change
A patch is attached as plugins_iterator.txt
We propose to handle this issue by storing a default value in the cache in both cases where:
 - No rows are returned from the datastore (current behaviour)
 - Rows are returned from the datastore, but no row matches the given parameters
This can be done by replacing this code (lines 27-37):
`    if #rows > 0 then
      for _, row in ipairs(rows) do
        if api_id == row.api_id and consumer_id == row.consumer_id then
          return row
        end
      end
    else
      -- insert a cached value to not trigger too many DB queries.
      return {null = true}
    end
end)`

with this code:
`    if #rows > 0 then
      for _, row in ipairs(rows) do
        if api_id == row.api_id and consumer_id == row.consumer_id then
          return row
        end
      end
    end
    -- insert a cached value to not trigger too many DB queries.
    return {null = true}
end)`

### Additional Details & Logs

- Kong version 0.9.7
- Operating System Amazon Linux

**Comment by ronan-skyscanner** [comment]
[plugins_iterator.txt](https://github.com/Mashape/kong/files/701778/plugins_iterator.txt)

**Comment by Tieske** [comment]
Have you seen this one https://github.com/Mashape/kong/pull/1841 ?

**Comment by ronan-skyscanner** [comment]
This is the same issue indeed. I see you have now merged the changes into the 'next' branch. Will that be part of the release after 0.10.0?

**Comment by Tieske** [comment]
@ronan-skyscanner They will be part of 0.10.0
