### ISSUE TITLE
Feature to unset/revoke all tokens for an authenticated_userid

### ISSUE THREAD

**Issue by shivamkh90** [Mashape/kong#1979]
### Summary

Need an api to unset/revoke all tokens for a single authenticated_userid.

### Additional Details

- Kong version (`0.9`)
- Operating System (Linux :- Ubuntu)

**Comment by Tieske** [comment]
Delete the consumer?

**Comment by shivamkh90** [comment]
No,  for grant_type password, i would like to delete all tokens issued to a particular user(with authenticated_userid).

Consumer must not be deleted.

**Comment by shivamkh90** [comment]
@thefosk , Do you have any suggestions to achieve this.

**Comment by thefosk** [comment]
You can search the tokens by `authenticated_userid` and then iterate over those tokens and `DELETE` them with an HTTP request.

ie: `/oauth2_tokens/?authenticated_userid=XXX`.
