### ISSUE TITLE
Kongserver 0.10.0 version, the use of the problem

### ISSUE THREAD

**Issue by taojinxin** [Mashape/kong#1980]
Very grateful to 0.10.0RC version, I decided to test this version of the function. However, the following two questions:
1. 0.10.0 version of the API add the way, and 0.9.7 to add different?
 ![image](https://cloud.githubusercontent.com/assets/25077580/21923512/867f2d88-d9af-11e6-9a26-87cf4bf87da6.png)
2. kong support SRV (DNS record) if my SRV consul from the consul component does not have more dynamic records from API to kong?
Please give me some help and I may need to evaluate these features. Thank you!
Although there is no documentation, I would like to test whether these features meet the micro-service architecture needs！

**Comment by Tieske** [comment]
1. see #1970 it explains the new router, also in 0.10.0.
2. I do not understand your question. Can you elaborate a bit?

**Comment by taojinxin** [comment]
kong support SRV (DNS record) if my SRV consul from the consul component does not have more dynamic records from API to kong?
Please give me some help and I may need to evaluate these features. Thank you!
Although there is no documentation, I would like to test whether these features meet the micro-service architecture needs！

**Comment by taojinxin** [comment]
Kong supports SRV if my SRV record comes from consul. Kong can consul the DNS interface to dynamically update the API?

**Comment by Tieske** [comment]
let's say you have registered two instances of the same service with consul. Then set up consul to expose those as an SRV record.

For example a service `service.xyz`, running on `10.10.10.1:123` (weight 10) and `10.10.10.2:456` (weight 5)

Now if consul provides a DNS record of SRV type for `service.xyz`, then you can configure Kong with an `upstream_url=http://service.xyz/some/path`.

Kong will now resolve `service.xyz` (using the SRV record it gets from consul) to the 2 ip+port as mentioned above, and will loadbalance the incoming requests over those 2 services (with total weight 15)

Make sure you configure Kong properly to use your consul installation for dns!

**Comment by Tieske** [comment]
additionally: whenever consul gets updated, and ip/ports are added/removed from the `service.xyz` then Kong will automatically refresh and integrate those changes (after the `ttl` value of the `SRV` record expires)

**Comment by taojinxin** [comment]
OK, thank you, whether to automatically update the API to kong (dynamic update)?
kong Call consul the dns, recommend what way?
Modify the configuration file?

**Comment by Tieske** [comment]
If you use consul, then letting Kong automatically update through the SRV dns records would be the right choice imo.

But if you only use consul for service registry, then you might cut out consul and do it directly with kong through `upstreams` and `targets`. See https://github.com/Mashape/kong/issues/157#issuecomment-238205952

**Comment by taojinxin** [comment]
thanks  you ！

The idea is that the kong and consul dns interfaces interact to dynamically update the API, and the registrator provides container information. Implement the dynamic update API

**Comment by Tieske** [comment]
considering this resolved.
