### ISSUE TITLE
kongserver keepalive

### ISSUE THREAD

**Issue by taojinxin** [Mashape/kong#1983]
Hey, there is a problem in an article I see kong will do health check function (keepalive) have this plan?

**Comment by Tieske** [comment]
there is anew setting in 0.10.0: https://github.com/Mashape/kong/blob/next/kong.conf.default#L112-L117

but this is only for keepalive on tcp connections, especially helpful for tls.

There is no upstream-healthcheck yet. Expect that for 0.11

**Comment by taojinxin** [comment]
Health check 0.11 version will be out?

**Comment by Tieske** [comment]
nothing set yet, don't hold your breath.

**Comment by taojinxin** [comment]
hi , #upstream_keepalive = 60 
I see configuration items, is the use of the cluster?
