### ISSUE TITLE
[feature] Create *ratelimiting* tables as UNLOGGED

### ISSUE THREAD

**Issue by ergo70** [Mashape/kong#1986]
Since the content of the *\*ratelimiting\** tables is volatile, I suggest to change their creation mode to UNLOGGED for PostgreSQL.

This would substantially increase the rate of possible update operations on those tables, with 'substantial' being something between 10% and 90%, depending on configuration, storage system etc.

So:

```
CREATE TABLE IF NOT EXISTS ratelimiting_metrics

CREATE TABLE IF NOT EXISTS response_ratelimiting_metrics
```

would become:

```
CREATE UNLOGGED TABLE IF NOT EXISTS ratelimiting_metrics

CREATE UNLOGGED TABLE IF NOT EXISTS response_ratelimiting_metrics
```

and that's it.

Please note that this would introduce a dependency to PostgreSQL >= 9.1,x.

**Comment by Tieske** [comment]
Unlogged tables do not replicate iirc. So that makes it impossible to use unlogged tables. No?

btw. Kong already requires PostgreSQL >= 9.4

**Comment by ergo70** [comment]
If you use physical or logical replication UNLOGGED tables are not replicated, since they never touch the WAL which is the replication source. Trigger-based replication, e.g. buracdo, should be able to replicate them, but I can't find any definitive _yes_ or _no_ in the documentation.

However, I'm not clear about the role of PostgreSQL in a Kong cluster? You could use a standby server for failover, but in this case it should be a lesser problem losing the data in the counter tables compared to losing e.g. the configuration, the plugin would just start at zero again.

You also could horizontally scale reads over a master + _n_ slaves, but then you have to deal with replication lag between the nodes. Write-wise, all writes will have to hit the master anyway.

I thought Cassandra and Redis are supported exactly for cases when you need to horizontally scale writes to the datastore?

**Comment by Tieske** [comment]
No postgres expert myself. The main use-case I'm referring to is multi-datacenter setups, where each DC has it's own local datastore (that syncs with the other DC datastores)

So unless there is a definitive answer that this works, we cannot change to UNLOGGED tables imo.

@thefosk @thibaultcha any thoughts or wisdom to share on this?

**Comment by ergo70** [comment]
Me too. At least not with distributed setups. So, I see your point and agree, better safe than sorry. At least it is no problem of manually setting them to UNLOGGED in a single server installation.

**Comment by Tieske** [comment]
@ergo70 You tested this, with manually changing the tables to UNLOGGED? and the results were ok? If so can you post a bit on how and what for future reference? Thx!

**Comment by ergo70** [comment]
Yes, it seems to be working without problems.

As said here before, UNLOGGED tables do not write to the WAL and therefore feature faster writes. However, in case of a database crash, their data cannot be restored, so they will come up empty. They are also not replicated with all replication mechanisms that use the WAL, trigger based replication mechanisms should work.

So the are mainly suitable for applications, where write speed beats data safety, e.g. caches or staging tables.

I saved the original table creation scripts, dropped the tables and re-created them with CREATE TABLE changed to CREATE UNLOGGED TABLE and that was it.

With PostgreSQL >= 9.5, you could also do ALTER TABLE SET UNLOGGED directly on the existing tables. In both cases, Kong should be stopped while doing this.

**Comment by Tieske** [comment]
👍  thx!
