### ISSUE TITLE
[plugin] Allow usage of the X-Forwarded-For header in the ip-restriction plugin

### ISSUE THREAD

**Issue by Tieske** [Mashape/kong#1995]
When behind a proxy the `ip-restriction` plugin will act upon the ip address of the proxy, instead of the original client, passed in the `X-Forwarded-For` header.

Requires an option to be added to the schema to (dis)allow this.

**Comment by jammm** [comment]
It would be useful if this can be done for the rate limiting plugin as well, in case it falls back to IP as the identifier for rate limiting.

**Comment by thefosk** [comment]
@Tieske I have tried to replicate, unsuccessfully. Can you take a look at the test? #2019

**Comment by bungle** [comment]
I'm pretty sure this is handled with #2236 / #2202.

**Comment by bungle** [comment]
@Tieske is this relevant anymore as the we have merged the above?

**Comment by Tieske** [comment]
let's close this.
