### ISSUE TITLE
How to distribute (release process) Kong?

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#2]
Find a way to ship Kong and an easy way to install/run Cassandra for test purposes.

Ideas to experiment:
- See if Kong can be bundled in Openresty
- Deb/RPM packages
- Chef cookbook?
- Bash script for installation
- Use the Makefile
- Docker/Vagrant
- Ship a Cassandra test cluster in Docker/Vagrant

Things required to run Kong:
- Lua
- Luarocks
- Openresty
- Cassandra
- Our luarocks dependencies to install
- A Cassandra cluster

An idea could be that on the website, the user lands on a Download page asking him what is his distribution, he selects, we display the way to install Kong on his distribution (Deb vs RPM for example) as a list of commands he can copy/paste.

**Comment by thefosk** [comment]
Take a look at the various Dockerfiles to see exactly what dependencies Kong needs.

**Comment by montanaflynn** [comment]
I'll just throw these in for consideration:

- https://www.packer.io/ 
- https://github.com/jordansissel/fpm

**Comment by ahmadnassri** [comment]
:+1: fpm, throw that in Travis, package it and store it back in github releases.

**Comment by ahmadnassri** [comment]
also, github releases in itself is a distribution method, compile versions for different environments and store in github releases ... 

https://github.com/Mashape/kong/releases/tag/0.0.1-beta

all can be done in Travis, with proper tagging and setup.

**Comment by thibaultCha** [comment]
We still need an environment-specific way to install on a server. Aka copy-paste of commands in an ssh session, using different package managers for dependencies. 


Putting stuff in GH releases doesn't really help, we are not shipping a binary, but a Luarocks module, so... It's install from source or Luarocks.

**Comment by montanaflynn** [comment]
When Niji suggested an installation shell script yesterday I remembered that's how Boundary supports a ton of platforms with the same quick installation guide. Here's their script: https://github.com/boundary/boundary_scripts/blob/master/setup_meter.sh

**Comment by thibaultCha** [comment]
The problem with installation script is that you have to read it to know what it's going to do on your machine. When giving the user a list of commands feels safer and les time consuming (if you care about your setup).

**Comment by Nijikokun** [comment]
only if you're extremely paranoid

**Comment by thibaultCha** [comment]
It's about being paranoid, but knowing how and where it installs stuff. I know where my package managers install stuff. It's not paranoid, it's more about setup.

**Comment by Nijikokun** [comment]
Its actually fine, because it's in plain text so you can read what its doing :+1:

**Comment by thibaultCha** [comment]
I think we can close this issue for now. Install process has been discussed and is mocked.

###### For release
- Platform-specific install method from source
- Docker

###### In the future
- Install script (preferred way)
- Package managers (per platform)
- Platform-specific install method from source
- Docker
