### ISSUE TITLE
[request] sqlite support

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#200]
Not everybody needs a distributed cluster, we could also support sqlite for single-node, single-users Kong instances. This would probably give a **significant performance and usability boost** for those instances, considering the data would physically be on the same node, and eventually even in memory. No more Cassandra cluster to manage.

Supporting sqlite would also mean being close to support MySQL or PostgreSQL

**Comment by bobrik** [comment]
That would be very nice.

**Comment by sinzone** [comment]
+1

**Comment by sandstrom** [comment]
Other storage would be something like Consul key/value store, or Etcd. Don't know enough about kong to be certain that they would fit, but I think they would.

**Comment by thibaultCha** [comment]
Ideally databases supported by Kong need to be relational, because of the structure of the data stored in it.
