### ISSUE TITLE
request_path and strip_request_path are unknown fields

### ISSUE THREAD

**Issue by benedict1986** [Mashape/kong#2006]
### Summary

request_path, request_host and strip_request_path becomes unknown in 0.10.0rc2 docker version

Also is there any document support for 0.10.0? I would like to try the websocket function. Not sure at this moment how to add ws as api protocol. Thanks

### Steps To Reproduce

1. run curl -i -X POST --data 'name=HelloWorld' --data 'request_path=/api/helloworld' --data 'upstream_url=http://172.17.0.6:60000/' --data 'strip_request_path=false' --url http://localhost:8001/apis/ in command line
2.
3.
4.

### Additional Details & Logs

- Kong version (`0.10.0rc2`)
- Kong debug-level startup logs (`$ kong start --vv`)

2017/01/22 01:42:24 [verbose] Kong: 0.10.0rc2
2017/01/22 01:42:24 [debug] ngx_lua: 10007
2017/01/22 01:42:24 [debug] nginx: 1011002
2017/01/22 01:42:24 [debug] Lua: LuaJIT 2.1.0-beta2
2017/01/22 01:42:24 [debug] PRNG seed: 171273891651
2017/01/22 01:42:24 [verbose] no config file found at /etc/kong/kong.conf
2017/01/22 01:42:24 [verbose] no config file found at /etc/kong.conf
2017/01/22 01:42:24 [verbose] no config file, skipping loading
2017/01/22 01:42:24 [debug] KONG_CASSANDRA_CONTACT_POINTS ENV found with "kong-database"
2017/01/22 01:42:24 [debug] KONG_PG_HOST ENV found with "kong-database"
2017/01/22 01:42:24 [debug] KONG_DATABASE ENV found with "cassandra"
2017/01/22 01:42:24 [debug] admin_listen = "0.0.0.0:8001"
2017/01/22 01:42:24 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/01/22 01:42:24 [debug] admin_ssl = true
2017/01/22 01:42:24 [debug] anonymous_reports = true
2017/01/22 01:42:24 [debug] cassandra_consistency = "ONE"
2017/01/22 01:42:24 [debug] cassandra_contact_points = {"kong-database"}
2017/01/22 01:42:24 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/01/22 01:42:24 [debug] cassandra_keyspace = "kong"
2017/01/22 01:42:24 [debug] cassandra_lb_policy = "RoundRobin"
2017/01/22 01:42:24 [debug] cassandra_port = 9042
2017/01/22 01:42:24 [debug] cassandra_repl_factor = 1
2017/01/22 01:42:24 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/01/22 01:42:24 [debug] cassandra_ssl = false
2017/01/22 01:42:24 [debug] cassandra_ssl_verify = false
2017/01/22 01:42:24 [debug] cassandra_timeout = 5000
2017/01/22 01:42:24 [debug] cassandra_username = "kong"
2017/01/22 01:42:24 [debug] cluster_listen = "0.0.0.0:7946"
2017/01/22 01:42:24 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/01/22 01:42:24 [debug] cluster_profile = "wan"
2017/01/22 01:42:24 [debug] cluster_ttl_on_failure = 3600
2017/01/22 01:42:24 [debug] custom_plugins = {}
2017/01/22 01:42:24 [debug] database = "cassandra"
2017/01/22 01:42:24 [debug] dns_hostsfile = "/etc/hosts"
2017/01/22 01:42:24 [debug] dns_resolver = {}
2017/01/22 01:42:24 [debug] log_level = "notice"
2017/01/22 01:42:24 [debug] lua_code_cache = "on"
2017/01/22 01:42:24 [debug] lua_package_cpath = ""
2017/01/22 01:42:24 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/01/22 01:42:24 [debug] lua_ssl_verify_depth = 1
2017/01/22 01:42:24 [debug] mem_cache_size = "128m"
2017/01/22 01:42:24 [debug] nginx_daemon = "on"
2017/01/22 01:42:24 [debug] nginx_optimizations = true
2017/01/22 01:42:24 [debug] nginx_worker_processes = "auto"
2017/01/22 01:42:24 [debug] pg_database = "kong"
2017/01/22 01:42:24 [debug] pg_host = "kong-database"
2017/01/22 01:42:24 [debug] pg_port = 5432
2017/01/22 01:42:24 [debug] pg_ssl = false
2017/01/22 01:42:24 [debug] pg_ssl_verify = false
2017/01/22 01:42:24 [debug] pg_user = "kong"
2017/01/22 01:42:24 [debug] prefix = "/usr/local/kong/"
2017/01/22 01:42:24 [debug] proxy_listen = "0.0.0.0:8000"
2017/01/22 01:42:24 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2017/01/22 01:42:24 [debug] serf_path = "serf"
2017/01/22 01:42:24 [debug] ssl = true
2017/01/22 01:42:24 [debug] upstream_keepalive = 60
2017/01/22 01:42:24 [verbose] prefix in use: /usr/local/kong
2017/01/22 01:42:24 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2017/01/22 01:42:24 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:14: Kong is already running in /usr/local/kong
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:14: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:89>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:5: in function 'file_gen'
        init_worker_by_lua:38: in function <init_worker_by_lua:36>
        [C]: in function 'pcall'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

sh-4.2# cat /usr/local/kong/logs/error.log
2017/01/22 01:16:32 [notice] 68#0: using the "epoll" event method
2017/01/22 01:16:32 [notice] 68#0: openresty/1.11.2.2
2017/01/22 01:16:32 [notice] 68#0: built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)
2017/01/22 01:16:32 [notice] 68#0: OS: Linux 4.9.4-moby
2017/01/22 01:16:32 [notice] 68#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2017/01/22 01:16:32 [notice] 68#0: start worker processes
2017/01/22 01:16:32 [notice] 68#0: start worker process 79
2017/01/22 01:16:32 [notice] 68#0: start worker process 80
2017/01/22 01:16:37 [warn] 80#0: *7 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/01/22 01:16:38 [warn] 80#0: *17 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/01/22 01:16:41 [warn] 80#0: *25 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/01/22 01:16:44 [warn] 80#0: *33 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/01/22 01:16:47 [warn] 80#0: *42 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/01/22 01:16:50 [warn] 80#0: *50 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/01/22 01:16:54 [warn] 80#0: *58 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/01/22 01:16:56 [warn] 80#0: *69 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/01/22 01:16:57 [warn] 79#0: *65 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, client: 172.17.0.1, server: kong_admin, request: "GET /apis HTTP/1.1", host: "localhost:8001", referrer: "http://localhost:32768/"
2017/01/22 01:16:59 [warn] 80#0: *77 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/01/22 01:17:02 [warn] 80#0: *87 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/01/22 01:17:05 [warn] 80#0: *96 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, context: ngx.timer
2017/01/22 01:18:01 [warn] 79#0: *65 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, client: 172.17.0.1, server: kong_admin, request: "GET /apis HTTP/1.1", host: "localhost:8001", referrer: "http://localhost:32774/"
2017/01/22 01:18:04 [warn] 79#0: *65 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query used without partition key, client: 172.17.0.1, server: kong_admin, request: "GET /apis HTTP/1.1", host: "localhost:8001", referrer: "http://localhost:32774/"

- Kong configuration (registered APIs/Plugins & configuration file)

Default configuration. Run 0.10.0rc2 docker image and add api

- Operating System

host: Windows 10
docker: mashape/kong:0.10.0rc2

**Comment by pouledodue** [comment]
https://github.com/Mashape/kong/pull/1970

**Comment by Tieske** [comment]
The names changed in 0.10.0, as @pouledodue pointed out docs are in #1970 for now.

**Comment by benedict1986** [comment]
Thank you. I will read it.
