### ISSUE TITLE
In front of kong how to realize the load balance

### ISSUE THREAD

**Issue by shaowin16** [Mashape/kong#2009]
I have realized the kong cluster,
but I don't know what's the use.
In addition，i want to know how to realize the agent to another node
when a kong node have failed.

I‘m sorry for my english.

**Comment by Tieske** [comment]
You need to have a loadbalancer that distributes incoming traffic over the Kong nodes in your Kong cluster. Whatever suits your needs.

Regarding a Kong node failing: the nodes are identical, such that you can just spin up a new Kong node whenever one fails

**Comment by shaowin16** [comment]
@Tieske 
Thank you for your answer.
What is your advice of a loadbalancer?
And how to  realize spin up a new Kong node whenever one fails? 
Can you give me an example?

**Comment by Tieske** [comment]
That depends on your infrastructure and tooling you use. 

Probably best to ask those types of question on the [Gitter channel](https://gitter.im/Mashape/kong), plenty of users there that run all sorts of setups.
