### ISSUE TITLE
Invalid response code from kong 

### ISSUE THREAD

**Issue by shavo007** [Mashape/kong#2010]
### Summary

Hi,

I am creating a customer using request outlined in admin api locally.

POST /consumers/

{ "custom_id": "12345678" }

I did not define the content type of application/json. Instead it was text/plain.

I received a bad request (400) instead of unsupported media type (415)

### Steps To Reproduce

1. Postman, create a post request with URI http://localhost:8001/consumers
2. Request body is raw with value { "custom_id": "12345678" }, content type text/plain
3. Response is 
`
{
  "custom_id": "At least a 'custom_id' or a 'username' must be specified",
  "username": "At least a 'custom_id' or a 'username' must be specified"
}
`
4.

### Additional Details & Logs

- Kong version 0.9.8
- Operating System OSX

**Comment by p0pr0ck5** [comment]
This doesn't seem like a bug to me. The request wasn't valid, as the proper content type wasn't specified. @shavo007 is there other behavior youre looking for?

**Comment by p0pr0ck5** [comment]
Closing as stale after no response. Feel free to re-open this issue if there are still questions. Thanks!
