### ISSUE TITLE
kong.conf file location is confused

### ISSUE THREAD

**Issue by eit** [Mashape/kong#2011]
### Summary
The default kong.conf location is at /etc/kong.conf, but sample file is at /etc/kong/kong.conf.default.

I think it will cause user confusion.

- Kong version (`$ kong version`)
0.9.7

**Comment by p0pr0ck5** [comment]
@eit thanks for opening this. Both `/etc/kong.conf` and `/etc/kong/kong.conf` will be checked: https://github.com/Mashape/kong/blob/master/kong/conf_loader.lua#L322.

Do let us know if you have any other questions here!

**Comment by Tieske** [comment]
note: starting Kong with `kong start --vv` will show the locations where Kong looks for the config file.
