### ISSUE TITLE
[plugin] Allow usage of the X-Forwarded-For header in the rate-limiting plugin

### ISSUE THREAD

**Issue by jammm** [Mashape/kong#2012]
Similar to https://github.com/Mashape/kong/issues/1995, but for a different plugin (rate-limiting).

One approach I can think of is having an extra (optional) parameter specifying which header (real IP or X-FORWARDED-FOR) to use in case it falls back to IP as the identifier.

**Comment by bungle** [comment]
I'm pretty sure this is handled with #2236 / #2202.

**Comment by p0pr0ck5** [comment]
Closing since #1995 was closed, as this was handled thanks to @bungle!
