### ISSUE TITLE
Html response instead of json

### ISSUE THREAD

**Issue by shavo007** [Mashape/kong#2014]
### Summary

Receive html response from kong instead of json.

### Steps To Reproduce

1. Attempt to enable the same plugin for an api (i already enabled key-auth for api)
2. 
`http://localhost:8001/apis/locations/plugins
{
	"name": "key-auth",
	"config.key_names": "AUTH-KEY"
}`
3. get 409 conflict with html response instead of json

### Additional Details & Logs

- Kong version 0.9.8
- Operating System OSX

**Comment by Tieske** [comment]
fixed with #2171. Will be in next release, hence closing this.

**Comment by shavo007** [comment]
release 0.10.0

**Comment by thibaultcha** [comment]
🥇
