### ISSUE TITLE
kong migrations is not running correctly on 0.10.0rc2 with Cassandra

### ISSUE THREAD

**Issue by se** [Mashape/kong#2015]
### Summary

Kong trying to migrate when I remove Kong's keyspace from Cassandra. I don't want to do that. I tried to use kong migrate reset but still same.

[UPDATE]
Migration scripts fails or run wrong order I think.

### Steps To Reproduce

1. Start cassandra 
2. Start kong
3. Remove kong's db from cassandra
4. Start kong 

### Additional Details & Logs

```
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [cassandra error] Error during migration 2015-01-12-175310_init_schema: [Invalid] No column definition found for column request_host
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:89>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:5: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'pcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>
```
- Kong version 0.10.0rc2
- OS : RedHat 7.3

**Comment by Tieske** [comment]
> I don't want to do that.

What do you want to do? Can't help without knowing what you're trying to accomplish

**Comment by se** [comment]
Just I want to do new kong installation.

**Comment by Tieske** [comment]
Then clear the Cassandra namespace for Kong. Iirc the default is called Kong.

Upon starting Kong again, it will automatically recreate it and run the migrations.

**Comment by Tieske** [comment]
Btw Kong needs the migrations, to create the data structures it needs in the datastore

**Comment by se** [comment]
Yeap I understand. But It seems broken on Cassandra 3 and 0.10.0rc2.

I will try to fix and share the solution here.

**Comment by se** [comment]
@Tieske I think order is not correct in cassandra migration file or in code?

**Comment by se** [comment]
Another log;

```
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong.lua:133: [cassandra error] Error during migration 2016-09-05-212515_retries_step_1: [Invalid] Invalid column name retries because it conflicts with an existing column
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong.lua:133: in function 'init'
	init_by_lua:4: in main chunk

stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:89>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:5: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'pcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>
```

**Comment by se** [comment]
Do you guys have any idea or fix on rc3 that I can try?
@Tieske @thefosk

**Comment by se** [comment]
I found my workaround. It is weird but It works.

I will explain my architecture and solution.

I am using;

Cassandra 3 x2 (Clustered)
Kong 0.10.0rc2 (Clustered)

When 2 Cassandra nodes are up, Kong installation fails.

Workaround is;
Stop second node of **Cassandra**.

And try start your Kong (I said try because It wont work, don't worry);
(--vv for debug -- more log)
`kong start --vv`

When installation step comes to;
`[info] migrating core for keyspace kong`

Start second node with `cassandra start`(Or with your way `service cassandra start` etc.)

And It is done.

```
2017/01/26 15:25:23 [debug] nginx started
2017/01/26 15:25:23 [info] Kong started
```

I hope this can help to fix this issue.

If you guys need more I am happy to assist.

**Comment by Tieske** [comment]
@se that seems a bug indeed. RC3 will be released today probably, would you mind giving that one a try?

**Comment by thefosk** [comment]
RC3 has been released.
