### ISSUE TITLE
response rate limiting plugin year length is 360 days

### ISSUE THREAD

**Issue by peterbsmith2** [Mashape/kong#2021]
### Summary

[The number of seconds for year translates to 360 days in policies line 20](https://github.com/Mashape/kong/blob/master/kong/plugins/response-ratelimiting/policies.lua#L20). `31104000` is 360 days, not 365.

**Comment by thefosk** [comment]
You are correct, it should be `31536000`. The mistake was done because for MONTH we are assuming `30` days and we just multiplied by `12` the month value, which turns out is `31104000 `.

**Comment by Tieske** [comment]
so basically the month value should also be updated. If the period starts 15-Feb, it should measure 15-Februari up to 14-March. Not just a default of 30 days.

**Comment by thefosk** [comment]
Yes currently it's a default of 30 days that begins at the beginning of the month (and beginning of second, minute, hour, and so on). This allows us to keep our data structure very simple, otherwise it would be too complex to store. 

Generally speaking seems to be a good compromise.
