### ISSUE TITLE
CORS pluig not working

### ISSUE THREAD

**Issue by BMLande** [Mashape/kong#2027]
hello..
i provide u what i did:
 1.i create one admin api as following
curl -i -X POST \
  --url http://localhost:8001/apis/ \
  --data 'name=demo' \
  --data 'upstream_url=http://172.17.0.6:8080' \                            
  --data 'request_host=api.com'

-172.1720.6 is my api container which contain all apis such as get user ,put user, post user and delete user information through apis
2.now i am trying to add CORS plugin, i did following.
curl -X POST localhost:8001/apis/8fd851d2-f72e-4fa5-b466-e4a5dc25129b/plugins \
    --data "name=cors" \
    --data "config.origin=api.com" \
    --data "config.methods=GET, POST, PUT , DELETE" \
    --data "config.headers=Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Auth-Token" \
    --data "config.exposed_headers=X-Auth-Token" \
    --data "config.credentials=true" \
    --data "config.max_age=3600"

-----------------------------------------------------------------------------------------------------------------------------
-i need hepl in how i provide origin
-i provided container host name now
-else tell me how to add CORS plug in 
THANKS ..................

**Comment by BMLande** [comment]
i solved this issues thanks,,,,,,,,,,,,,

**Comment by Sunil28071987** [comment]
can you tell me how did you solve it

**Comment by BMLande** [comment]
hi sunil, i am here sorry for late reply
in my case i miss following things:
first thing, u need to use requested path option (not requested url) while creating kong api.
second, i use authentication on my api and forget to add 'authentication' attribute in cors plug-in,in
data "config.headers.
this might helps u....

**Comment by Sunil28071987** [comment]
Hey thanks for the reply. I am not using authentication. As you mentioned that I have to use requested path and not the requested url. So I have following questions.
1) when should I use the property of request path while creating the admin API or while creating the cors plugin ?
2)  Also I don't see any such property called requested path.... Can you give me an example of the curl query..

**Comment by BMLande** [comment]
hie sunil , 
if you u new to this stuff,i think to install KONG UI,
https://github.com/PGBI/kong-dashboard
this is a graphical interface for creating Kong Admin api , and for all other thing.

1)this is description for how to define kong admin api:
https://getkong.org/docs/0.10.x/getting-started/adding-your-api/
while creating api dont mention Host property

1) as given on the website they said: kong cors plugin only worked with requested path
https://getkong.org/plugins/cors/
read the lomitations for apply cors api

> CORS Limitations
If the client is a browser, there is a known issue with this plugin caused by a limitation of the CORS specification that doesn't allow to specify a custom Host header in a preflight OPTIONS request.

**Comment by Sunil28071987** [comment]
Thanks a lot. I will definitely give it a shot.

**Comment by BMLande** [comment]
welcome...if any qurey ping me on 
landebm@gmail.com

**Comment by kumarinstor** [comment]
i am struggling here, i am calling kong api from browser with header "Host" i added cors plugin to that api but i am getting preflight error

**Comment by athlonUA** [comment]
SOS! I need help!!!!!! I set `Preflight continue` to the true and i still get CORS error on the OPTION request

```
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access. The response had HTTP status code 404.
```

![image](https://user-images.githubusercontent.com/9050727/33763220-4e5beea2-dc18-11e7-98bd-2425f22537be.png)

**Comment by SunilTiwari28071987** [comment]
Hi,
There are many ways to resolve that issue.

1) Don't send the request directly from the browser. from browser send it to another nodejs server and from there send it to kong.

2) Install the cors extension in chrome ([]( https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en)) and then try to send OR manually set the parameter for  **Allow-Control-Allow-Origin: * **

3) Add the trusted origin in your code using the libraries.
For Example here is the code for nodejs.
//origin : Set any host that you trust, in your case this should be your frontend running in the browser
// credentials: This option is for session , you can even remove it.
const cors = require('cors');

var corsOptions = {
    origin: 'http://localhost:3001', 
    credentials: true, // This option is for session , you can even remove it.
}

app.use(cors(corsOptions));

I hope this will be helpfull.

**Comment by Sunil28071987** [comment]
4) you can also set the header manually before sending the request. here is the sample code in nodejs

/ middleware to route all requests
router.use(function(req, res, next) {
    //Access Control
 res.setHeader('Access-Control-Allow-Origin', '*');
 res.setHeader('Access-Control-Allow-Credentials', 'true');
 res.setHeader('Access-Control-Allow-Methods', 'GET,HEAD,OPTIONS,POST,PUT,DELETE');
 res.setHeader('Access-Control-Allow-Headers', 'Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers');
//and remove cacheing so we get the most recent comments
 res.setHeader('Cache-Control', 'no-cache');
    // do logging
    console.log('Something is happening.');
    next(); // make sure we go to the next routes and don't stop here
});

**Comment by BMLande** [comment]
https://www.npmjs.com/package/cors
use this package on serber side code , this is the npm package i above
provided link , initialize it and add ith function as provided in above link
