### ISSUE TITLE
Kong verbose Oauth2 logging

### ISSUE THREAD

**Issue by rcyrus** [Mashape/kong#2029]
### Summary

I am running 0.98 default Docker image. I have kong behind a load balancer where SSL is terminated. I want to use Kong's Oauth2 plugin however I am having trouble getting it to bypass the SSL check. 

I have the Oauth2 plugin for my API configured with `"accept_http_if_already_terminated": true,` and I'm certain the edge router is setting `x-forwarded-proto: https` header. 

However whenever I send a client credential token request though my load balancer I am greeted with:

`{
  "error": "access_denied",
  "error_description": "You must use HTTPS"
}`

I'm not sure if this is a problem with Kong's Oauth2 plugin or not. I'd like to verify that `x-forwarded-proto` is being sent to `/oauth2/token` first. However when ever I check the kong access.log it only reports that a client hit that endpoint. What I really want to see is the entire request, headers and all. 

Is there a way to get more insight into requests sent to the oauth endpoint? I have tried turning on verbose logging on kong startup but that does not seem to effect access logs. 

I have also enabled the file logger plugin, but that only reports when APIs are hit and does not record Oauth2 transactions.

**Comment by frederik79** [comment]
Hey, did you ever find a way to get get the logs for this... I set accept_http_if_already_terminated to true in the OAuth2plugin and set the x-forwarded-proto: https header. However, I also get the {"error_description":"You must use HTTPS","error":"access_denied"} message when I request the oauth token.

**Comment by rcyrus** [comment]
I honestly can't remember. I closed this without comment, I typically only do that if I was doing something wrong. Ultimately though I was not able to solve this problem without modifying the Oauth2 plugin to skip the checks. I have not been involved with a Kong project since Feb though so my knowledge is rusty
