### ISSUE TITLE
[request] Multiple ratelimiting options per API

### ISSUE THREAD

**Issue by tamizhgeek** [Mashape/kong#205]
Here is our usecase: 

For an API, we impose a monthly limit of 100,000 calls. Also there is a second level throttling of 5 requests/second to avoid too many concurrent requests. Currently, this is not possible with kong. 

I think we can allow to have multiple rate limits per API provided they have different period values. And while throttling the requests, we can verify all of them and throw a 429 even if any one has crossed the quota. I would like a send a PR to fix this. But, before I would like to have the feedback. 

Thanks!

**Comment by thibaultCha** [comment]
:+1:

**Comment by melihmucuk** [comment]
+1

**Comment by sinzone** [comment]
+1

**Comment by tamizhgeek** [comment]
Thanks for the :+1: 

Currently the rate limiting config is like:

--data "value.limit=100" and --data "value.period=hour"

There are two ways I can think of supporting multiple configurations. 
1. --data "value.limits=5,1000" and --data "value.periods=second,hour" (Having limit and periods as separate options and rely on the order supplied by the user to match them). 
2. --data "value.limits=5:second, 1000:hour" (Much cleaner, but removing a existing option from API)

which one do you guys prefer?

**Comment by thibaultCha** [comment]
I think the second solution is much cleaner, it sounds great.

**Comment by sinzone** [comment]
note: these kind of plugins are currently "per API" only, but in the very near future will be and should be per endpoint too.

**Comment by tamizhgeek** [comment]
@sinzone Agreed., this addition wouldn't stand in the way of supporting per endpoint level configs.

**Comment by thefosk** [comment]
I like option 2, but with the key=value pairs inverted like `second:5, hour:10`. 

This is because we are using Lua tables internally so having the same `limit` for different `period` wouldn't be possible and the last one would override the previous ones, for example if we had `5:second, 5:hour` then `5:hour` would be the only one available since the unique key `5` is being used two times.

**Comment by thibaultCha** [comment]
That's just a matter of how you parse them.

**Comment by tamizhgeek** [comment]
PR for documentation/website change is here : https://github.com/ind9/getkong.org/pull/1

**Comment by lucamaraschi** [comment]
:+1:

**Comment by thefosk** [comment]
Closed with #382.
