### ISSUE TITLE
 Edit New issue Set upstream_url based on Http method

### ISSUE THREAD

**Issue by navidnabavi** [Mashape/kong#2050]
I wanted to set upstream based on HTTP method for same URLs, for example I have /posts URL and wanted to send request to different hosts when the method is GET,POST,DELETE or something else. As I read the docs there are options based on URL or host.
Is it any possibility to have this kind of routes?

**Comment by Tieske** [comment]
Part of release 0.10. Check out the latest RC if you want to test it.
