### ISSUE TITLE
Can I inject some actions before API handling?

### ISSUE THREAD

**Issue by kirikak2** [Mashape/kong#2053]
### Summary

Hi, Team.
I am integrating KONG with Cloud Foundry, and I created service broker for KONG which configured Fully-Brokered Service model.
For details, Cloud Foundry service overview in [here](https://docs.cloudfoundry.org/services/route-services.html). 

According to Cloud Foundry route service specification, When we request Cloud Foundry App which bound KONG service, CF router forwards and transforms request to KONG as follows.

```
GET /
Host: apps.cf.host
X-Cf-Forwarded-Url: https://apps.cf.host/real/request_path
```

For example, when I set KONG API as follows, KONG cannot handling forwarded request.

```
Request Host: apps.cf.host
Request Path: /real/
Upstream URL: https://apps.cf.host/
Strip request path: false
Preserve Host: false 
```

To solve this problem, KONG should support injectable action before API handling and rewrite request path. I tried to write lua script which copy url from X-Cf-Forwarded-Url to ngx.ctx.upstream_url in custom_nginx.template, but it seems to impossible.

Now, I solved this problem with proxy server which transform the forwarded request between CF router and KONG. However it is not simple architecture and I worry performance problem.

If you have good idea, please tell me.

### Additional Details & Logs

- Kong version (0.9.5)
- Ubuntu 16.04 LTS

**Comment by p0pr0ck5** [comment]
@kirikak2,

Does the Request Transformer plugin (https://getkong.org/plugins/request-transformer/) not meed your needs here?

**Comment by kirikak2** [comment]
@p0pr0ck5 Thanks for your suggest. but it is not resolve this problem.
In my understanding, this plugin works after API handling, and KONG cannot handle this request to API.

Currently, I am running reverse proxy on nginx which forwards and transforms request. It seems to be working fine.

**Comment by p0pr0ck5** [comment]
Ok if we close this issue then?

**Comment by kirikak2** [comment]
Sure.
In the future, I  would like to use  some hook point in KONG if I can.

**Comment by thibaultcha** [comment]
@kirikak2 Check out #2354 which is aimed at this precise use-case (currently a very rough implementation).
