### ISSUE TITLE
Kong fails to start: Missing PRIMARY KEY field

### ISSUE THREAD

**Issue by beniwtv** [Mashape/kong#2055]
### Summary

I just installed Kong via the Ubuntu Xenial package - and it is failing to start with strange error:

Error:
```
/usr/local/share/lua/5.1/kong/serf.lua:58: Missing PRIMARY KEY field
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/dao/dao.lua:312: in function 'delete'
        /usr/local/share/lua/5.1/kong/serf.lua:58: in function 'leave'
        /usr/local/share/lua/5.1/kong/cmd/utils/serf_signals.lua:119: in function 'stop'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:32: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:89>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:13: in function 'file_gen'
        init_worker_by_lua:38: in function <init_worker_by_lua:36>
        [C]: in function 'pcall'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>
```

### Steps To Reproduce

1. Install Kong from Xenial package
2. Install OpenResty
3. Configure Kong
3. Execute sudo kong start

### Additional Details & Logs

- Kong version: 0.9.9
- Kong debug-level startup logs (see below)
- Kong error logs: Are empty :(
- Operating System: Ubuntu 16.04

> $ sudo kong start -vv
> 2017/02/08 12:00:10 [verbose] Kong: 0.9.9
> 2017/02/08 12:00:10 [debug] ngx_lua: 10007
> 2017/02/08 12:00:10 [debug] nginx: 1011002
> 2017/02/08 12:00:10 [debug] Lua: LuaJIT 2.1.0-beta2
> 2017/02/08 12:00:10 [debug] PRNG seed: 159121772551
> 2017/02/08 12:00:10 [verbose] reading config file at /etc/kong.conf
> 2017/02/08 12:00:10 [debug] admin_listen = "0.0.0.0:8001"
> 2017/02/08 12:00:10 [debug] anonymous_reports = false
> 2017/02/08 12:00:10 [debug] cassandra_consistency = "ONE"
> 2017/02/08 12:00:10 [debug] cassandra_contact_points = {"127.0.0.1"}
> 2017/02/08 12:00:10 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
> 2017/02/08 12:00:10 [debug] cassandra_keyspace = "kong"
> 2017/02/08 12:00:10 [debug] cassandra_port = 9042
> 2017/02/08 12:00:10 [debug] cassandra_repl_factor = 1
> 2017/02/08 12:00:10 [debug] cassandra_repl_strategy = "SimpleStrategy"
> 2017/02/08 12:00:10 [debug] cassandra_ssl = false
> 2017/02/08 12:00:10 [debug] cassandra_ssl_verify = false
> 2017/02/08 12:00:10 [debug] cassandra_timeout = 5000
> 2017/02/08 12:00:10 [debug] cassandra_username = "kong"
> 2017/02/08 12:00:10 [debug] cluster_listen = "0.0.0.0:7946"
> 2017/02/08 12:00:10 [debug] cluster_listen_rpc = "127.0.0.1:7373"
> 2017/02/08 12:00:10 [debug] cluster_profile = "wan"
> 2017/02/08 12:00:10 [debug] cluster_ttl_on_failure = 3600
> 2017/02/08 12:00:10 [debug] custom_plugins = {}
> 2017/02/08 12:00:10 [debug] database = "postgres"
> 2017/02/08 12:00:10 [debug] dnsmasq = true
> 2017/02/08 12:00:10 [debug] dnsmasq_port = 8053
> 2017/02/08 12:00:10 [debug] log_level = "notice"
> 2017/02/08 12:00:10 [debug] lua_code_cache = "on"
> 2017/02/08 12:00:10 [debug] lua_package_cpath = ""
> 2017/02/08 12:00:10 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
> 2017/02/08 12:00:10 [debug] lua_ssl_verify_depth = 1
> 2017/02/08 12:00:10 [debug] mem_cache_size = "128m"
> 2017/02/08 12:00:10 [debug] nginx_daemon = "on"
> 2017/02/08 12:00:10 [debug] nginx_optimizations = true
> 2017/02/08 12:00:10 [debug] nginx_worker_processes = "auto"
> 2017/02/08 12:00:10 [debug] pg_database = "kong"
> 2017/02/08 12:00:10 [debug] pg_host = "kong-datastore"
> 2017/02/08 12:00:10 [debug] pg_password = "******"
> 2017/02/08 12:00:10 [debug] pg_port = 5432
> 2017/02/08 12:00:10 [debug] pg_ssl = false
> 2017/02/08 12:00:10 [debug] pg_ssl_verify = false
> 2017/02/08 12:00:10 [debug] pg_user = "kong"
> 2017/02/08 12:00:10 [debug] prefix = "/usr/local/kong/"
> 2017/02/08 12:00:10 [debug] proxy_listen = "0.0.0.0:8000"
> 2017/02/08 12:00:10 [debug] proxy_listen_ssl = "0.0.0.0:8443"
> 2017/02/08 12:00:10 [debug] serf_path = "serf"
> 2017/02/08 12:00:10 [debug] ssl = true
> 2017/02/08 12:00:10 [verbose] prefix in use: /usr/local/kong
> 2017/02/08 12:00:10 [verbose] preparing nginx prefix directory at /usr/local/kong
> 2017/02/08 12:00:10 [verbose] could not start Kong, stopping services
> 2017/02/08 12:00:10 [verbose] leaving serf cluster
> Error:
> /usr/local/share/lua/5.1/kong/serf.lua:58: Missing PRIMARY KEY field
> stack traceback:
>         [C]: in function 'error'
>         /usr/local/share/lua/5.1/kong/dao/dao.lua:312: in function 'delete'
>         /usr/local/share/lua/5.1/kong/serf.lua:58: in function 'leave'
>         /usr/local/share/lua/5.1/kong/cmd/utils/serf_signals.lua:119: in function 'stop'
>         /usr/local/share/lua/5.1/kong/cmd/start.lua:32: in function 'cmd_exec'
>         /usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:89>
>         [C]: in function 'xpcall'
>         /usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
>         /usr/local/bin/kong:13: in function 'file_gen'
>         init_worker_by_lua:38: in function <init_worker_by_lua:36>
>         [C]: in function 'pcall'
>         init_worker_by_lua:45: in function <init_worker_by_lua:43>
> 

I also tried "kong migrations up" - and that was successfull.

**Comment by beniwtv** [comment]
Well, debugging through the code solved the problem: Truns out you exactly need OpenResty 1.11.2.**1**. Fails very silently with the slightly newer 1.11.2.**2**.

**Comment by Tieske** [comment]
Kong does version checks, but obviously cannot check for newer versions if they break the version check... catch 22.

Hence our provided packages include openresty et al to prevent this.

**Comment by beniwtv** [comment]
Yeah, that version broke it completely - you'd think in a slight version number increment in the 4th position there would be no breaking changes...
