### ISSUE TITLE
Can't use a cassandra datacenter with an hyphen in the name

### ISSUE THREAD

**Issue by mbugeia** [Mashape/kong#2056]
### Summary

When using: `cassandra_lb_policy = DCAwareRoundRobin`
If I use `cassandra_local_datacenter = europe-west1-b`

```
kong start -v
2017/02/08 17:33:14 [verbose] Kong: 0.10.0rc3
2017/02/08 17:33:14 [verbose] reading config file at /etc/kong/kong.conf
2017/02/08 17:33:14 [verbose] prefix in use: /usr/local/kong
Error: 
...ocal/share/lua/5.1/resty/cassandra/policies/lb/dc_rr.lua:26: local_dc must be a string
stack traceback:
	[C]: in function 'assert'
	...ocal/share/lua/5.1/resty/cassandra/policies/lb/dc_rr.lua:26: in function 'new'
	/usr/local/share/lua/5.1/kong/dao/db/cassandra.lua:74: in function 'new'
	/usr/local/share/lua/5.1/kong/dao/factory.lua:98: in function 'new'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:18: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:89>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:5: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'pcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>
```

This is indeed a string and a valid cassandra datacenter name. Strangely when using: `cassandra_lb_policy = RoundRobin` 
i get a different result, cassandra_local_datacenter is not used anymore, but I still have this in my conf:
`cassandra_data_centers = europe-west1-b:1`
This do not fail immediatly but the keyspace is created in cassandra with datacenter "b" which cause an error when tying to reach the keyspace after, basicaly everything before the last hyphen is discarded.

Note that in all case `kong check` say that everything is ok. I already tried using environment variables instead of the conf file with the same result.

### Steps To Reproduce

1. Put a sample conf with an hyphen in cassandra_local_datacenter
2. Try to start kong

### Additional Details & Logs

- Kong version 0.10.0rc3
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) non more log, it's not started
- Kong configuration (registered APIs/Plugins & configuration file) none, kong doesn't start
- Operating System Ubuntu 16.04 (using the debian package)

**Comment by thibaultcha** [comment]
Hi,

Thanks for the report. However, this issue belongs to lua-cassandra, and not Kong. I'll take care of it over there, leaving this open for tracking purposes only for now.

**Comment by thibaultcha** [comment]
I may have spoken too fast, after some tests with lua-cassandra, it seems this is rather due to Kong not parsing this field properly!

**Comment by thibaultcha** [comment]
> Note that in all case kong check say that everything is ok. I already tried using environment variables instead of the conf file with the same result.

`kong check` is certainly not going that deep into the verification it is performing. It only checks for running daemons.

**Comment by thibaultcha** [comment]
Both fixes are now in #2060, thanks.

**Comment by thibaultcha** [comment]
Both fixes are now in #2060, thanks.

**Comment by mbugeia** [comment]
Thanks for this very fast fix! Tested it and everything works well now. Is there a chance for the incoming 0.10 release to include it ?

**Comment by thibaultcha** [comment]
Yes, it shall, including the upcoming rc4 of 0.10.0
