### ISSUE TITLE
Dynamic SSL configuration does not take effect

### ISSUE THREAD

**Issue by cookandy** [Mashape/kong#2057]
### Summary

Dynamic SSL does not update.  Instead, continues to serve up default cert for kong .  Same as [this issue](https://github.com/Mashape/kong/issues/1464), which was closed without any explanation as to why.

### Steps To Reproduce

1. create a service:

`curl -i -X POST --url http://localhost:8001/apis/ --data 'name=test' --data 'upstream_url=http://test.service.consul/' --data 'request_host=test.myhost.bz'`

2. update the endpoint with my certs:

`curl -X POST --url http://localhost:8001/apis/test/plugins --form "name=ssl" --form "config.cert=@ssl/wildcard.myhost.bz.crt" --form "config.key=@ssl/wildcard.myhost.bz.key" --form "config.only_https=true"`

3. curl the service and get the default cert for my kong instance (`*.myhost.com`), instead of my `*.myhost.bz` certificate:

```
❯ curl -k -v https://xxx.xxx.xxx.xxx -H "Host: test.myhost.bz"

* Rebuilt URL to: https://xxx.xxx.xxx.xxx/
*   Trying xxx.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to xxx.xxx.xxx.xxx (xxx.xxx.xxx.xxx) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.myhost.com
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
```

You'll notice the server responds with ***.myhost.com** instead of ***.myhost.bz**.

I don't see any logs saying the certificate is invalid, and when I look at `localhost:8001/plugins` I can see my plugin loaded and enabled.  The certificate I loaded contains the intermediate cert - so the whole chain is present.  

### Additional Details & Logs

Using Kong in Docker.  Started with the following run command:

`docker run -d --name kong --net host -e "KONG_DATABASE=cassandra" -e "KONG_CASSANDRA_CONTACT_POINTS=xxx.xxx.xxx.xxx" -e "KONG_CASSANDRA_PORT=9042" -e "KONG_ADMIN_LISTEN=xxx.xxx.xxx.xxx:8001" -e "KONG_PROXY_LISTEN=0.0.0.0:80" -e "KONG_PROXY_LISTEN_SSL=0.0.0.0:443" -e "KONG_SSL_CERT=/ssl/wildcard.myhost.com.crt" -e "KONG_SSL_CERT_KEY=/ssl/wildcard.myhost.com.key" -e "KONG_DNSMASQ=off" -e "KONG_DNS_RESOLVER=xxx.xxx.xxx.xxx" -p 80:80 -p 443:443 -p 8001:8001 -p 7946:7946 -p 7946:7946/udp -v $(pwd)/ssl:/ssl kong
`

**Comment by thibaultcha** [comment]
Hi,

Your client needs to support SNI. I believe curl is performing the client hello with the host provided in the URL. I am not sure how to enforce a custom SNI from curl, but it seems that online resources point to using the `--resolve` option. Could you give it a try?

**Comment by cookandy** [comment]
Ah, you're right!  I added a quick entry to `/etc/hosts` and did the curl again and it served the correct cert.  Appreciate the quick reply!

**Comment by tpanagos** [comment]
@cookandy Can you spell-out what you changed in /etc/hosts, please? I am working through a similar problem.

**Comment by cookandy** [comment]
Hi @tpanagos,

In my case, I added a entry in my local `/etc/hosts` file (on the machine I ran curl from) with the IP address of kong, and the hostname I set with `request_host` in kong (and `Host:` in curl):

```
# cat /etc/hosts

xxx.xxx.xxx.xxx   test.myhost.bz
```

and then run curl again (this time no need to set `Host` header): 

```
❯ curl -k -v "https://test.myhost.bz"
```
