### ISSUE TITLE
Request Path , API Not Found with these values - Kong 0.9.5

### ISSUE THREAD

**Issue by robertgraye** [Mashape/kong#2058]
Any Ideas?

I have setup two other Kong 0.9.5 API Servers on Redhat Linux that work correctly, I have followed the same routine to setup a third and all of a sudden I am getting the following exception:
Any Ideas, I have compared my other two servers and it's and exact match except of the host names.

curl http://SERVER1.org:8000/F1-Check

{"request_path":"\/F1-Check","message":"API not found with these values","request_host":["SERVER1.org"]}

"upstream_url": "http://SERVER2.org:7100/webservices",
         "strip_request_path": false,
         "request_path": "/F1-Check",
         "id": "ad980da4-8e3e-4bae-a2e5-3e3c3e9536a1",
         "created_at": 1486156211000,
         "preserve_host": false,
         "name": "F1-Check"

**Comment by thefosk** [comment]
@robertgraye, can you please update to latest 0.9.9? Maybe that won't fix it, but at least we are sure you are running all the latest patches.

**Comment by robertgraye** [comment]
Thanks. I updated to 0.9.9 and kong repeats the same exception. Any Ideas?

**Comment by Tieske** [comment]
@robertgraye so iiuc you have setup a Kong cluster, 2 nodes work fine, 3rd added and returns that error message?

If you request the api configurations from the management api on each of the three nodes, do you get the same responses?

**Comment by kelvinatstreetline** [comment]
First install on ubuntu 14.04 and ran into the same issue.

**Comment by thefosk** [comment]
@kelvinatstreetline did you setup an API first?

**Comment by kelvinatstreetline** [comment]
Yes, but it didn't work. Followed the config instruction at their 5-minute set up link (https://getkong.org/docs/latest/getting-started/quickstart) but it didn't work.  Ripped it out, thought to try an older version thinking it may be more stable; ran into all kinds of dependency issues on an Ubuntu 14.04.5 LTS host.

**Comment by Tieske** [comment]
@kelvinatstreetline can you provide more details?

- the exact api config
- Curl command used to access the api
- error message returned

@robertgraye have you been able to resolve this issue, or is it still present?

**Comment by Tieske** [comment]
ping @robertgraye @kelvinatstreetline
