### ISSUE TITLE
Basic auth creation with duplicate username for more than one consumer

### ISSUE THREAD

**Issue by shavo007** [Mashape/kong#2061]
### Summary

i tested creating basic auth for a consumer. i then created basic auth for another consumer with the same username. it did not fail.

### Steps To Reproduce

1. http://localhost:8001/consumers/{consumer_id}/basic-auth

{
	"username": "shanelee007"

}
Get a 201 when i create the above request for two different consumers.

### Additional Details & Logs

- Kong version 0.9.8
- Operating System OSX

**Comment by thibaultcha** [comment]
Hi,

Thanks for the report. This was fixed in 23389d616831ebc21c155fbed34545025a98cc94 and will be part of 0.10.0.

**Comment by shavo007** [comment]
thanks @thibaultcha  any chance you can update the plugin doc to explain the username is unique? And what error responses can return?
https://getkong.org/plugins/basic-authentication/

Also, i do not see an example request/response to verify the credentials work. can that be added in?

**Comment by Tieske** [comment]
@shavo007 the docs are in https://github.com/Mashape/getkong.org/tree/master/app/plugins. Can you please send a PR?

**Comment by gottfrois** [comment]
If i may ask, what are the reasons for the consumer username to be uniq? I would like to have the same username but different password for 2 consumers and it's currently not possible (v0.11)
