### ISSUE TITLE
migration fails with Cassandra cluster 

### ISSUE THREAD

**Issue by frederik79** [Mashape/kong#2063]
Hi,

I got a problem that the kong start fails on a fresh installation of kong.

A kong schema migration step fails after  spinning up a kong docker container running against a Cassandra cluster with multiple nodes. Cassandra and kong are running as docker containers within OpenShift.

Kong version 0.10.0RC3
docker container of kong based on: https://github.com/Mashape/docker-kong
cassandra version: 2.2 and 3 
 
The Cassandra cluster is in a healthy state and no keyspace kong exists

nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.1.4.5   83.11 KiB  32           100.0%            1bf1c845-d9c3-494b-893a-d39bfd576b2d  rack1
UN  10.1.2.12  65.66 KiB  32           100.0%            b0a33b1d-7dda-4b01-9984-f4cbff6608c3  rack1

The cluster is blank and no kong keyspace exist

cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.9 | CQL spec 3.4.2 | Native protocol v4]
Use HELP for help.
cqlsh> describe keyspaces

system_traces  system_schema  system_auth  system  system_distributed

cqlsh>

If I spin up a kong container it fails during the migration process
W0209 16:26:43.790349    2097 cmd.go:269] log is DEPRECATED and will be removed in a future version. Use logs instead.
2017/02/09 03:25:37 [verbose] Kong: 0.10.0rc3
2017/02/09 03:25:37 [debug] ngx_lua: 10007
2017/02/09 03:25:37 [debug] nginx: 1011002
2017/02/09 03:25:37 [debug] Lua: LuaJIT 2.1.0-beta2
2017/02/09 03:25:37 [debug] PRNG seed: 136166126287
2017/02/09 03:25:37 [verbose] no config file found at /etc/kong/kong.conf
2017/02/09 03:25:37 [verbose] no config file found at /etc/kong.conf
2017/02/09 03:25:37 [verbose] no config file, skipping loading
2017/02/09 03:25:37 [debug] KONG_CASSANDRA_CONTACT_POINTS ENV found with "cassandra-cluster"
2017/02/09 03:25:37 [debug] KONG_PG_HOST ENV found with "cassandra-cluster"
2017/02/09 03:25:37 [debug] KONG_NGINX_DAEMON ENV found with "off"
2017/02/09 03:25:37 [debug] KONG_DATABASE ENV found with "cassandra"
2017/02/09 03:25:37 [debug] admin_listen = "0.0.0.0:8001"
2017/02/09 03:25:37 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/02/09 03:25:37 [debug] admin_ssl = true
2017/02/09 03:25:37 [debug] anonymous_reports = true
2017/02/09 03:25:37 [debug] cassandra_consistency = "ONE"
2017/02/09 03:25:37 [debug] cassandra_contact_points = {"cassandra-cluster"}
2017/02/09 03:25:37 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/02/09 03:25:37 [debug] cassandra_keyspace = "kong"
2017/02/09 03:25:37 [debug] cassandra_lb_policy = "RoundRobin"
2017/02/09 03:25:37 [debug] cassandra_port = 9042
2017/02/09 03:25:37 [debug] cassandra_repl_factor = 1
2017/02/09 03:25:37 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/02/09 03:25:37 [debug] cassandra_ssl = false
2017/02/09 03:25:37 [debug] cassandra_ssl_verify = false
2017/02/09 03:25:37 [debug] cassandra_timeout = 5000
2017/02/09 03:25:37 [debug] cassandra_username = "kong"
2017/02/09 03:25:37 [debug] cluster_listen = "0.0.0.0:7946"
2017/02/09 03:25:37 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/02/09 03:25:37 [debug] cluster_profile = "wan"
2017/02/09 03:25:37 [debug] cluster_ttl_on_failure = 3600
2017/02/09 03:25:37 [debug] custom_plugins = {}
2017/02/09 03:25:37 [debug] database = "cassandra"
2017/02/09 03:25:37 [debug] dns_hostsfile = "/etc/hosts"
2017/02/09 03:25:37 [debug] dns_resolver = {}
2017/02/09 03:25:37 [debug] log_level = "notice"
2017/02/09 03:25:37 [debug] lua_code_cache = "on"
2017/02/09 03:25:37 [debug] lua_package_cpath = ""
2017/02/09 03:25:37 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/02/09 03:25:37 [debug] lua_ssl_verify_depth = 1
2017/02/09 03:25:37 [debug] mem_cache_size = "128m"
2017/02/09 03:25:37 [debug] nginx_daemon = "off"
2017/02/09 03:25:37 [debug] nginx_optimizations = true
2017/02/09 03:25:37 [debug] nginx_worker_processes = "auto"
2017/02/09 03:25:37 [debug] pg_database = "kong"
2017/02/09 03:25:37 [debug] pg_host = "cassandra-cluster"
2017/02/09 03:25:37 [debug] pg_port = 5432
2017/02/09 03:25:37 [debug] pg_ssl = false
2017/02/09 03:25:37 [debug] pg_ssl_verify = false
2017/02/09 03:25:37 [debug] pg_user = "kong"
2017/02/09 03:25:37 [debug] prefix = "/usr/local/kong/"
2017/02/09 03:25:37 [debug] proxy_listen = "0.0.0.0:8000"
2017/02/09 03:25:37 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2017/02/09 03:25:37 [debug] serf_path = "serf"
2017/02/09 03:25:37 [debug] ssl = true
2017/02/09 03:25:37 [debug] upstream_keepalive = 60
2017/02/09 03:25:37 [verbose] prefix in use: /usr/local/kong
2017/02/09 03:25:37 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/02/09 03:25:37 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2017/02/09 03:25:37 [debug] searching for OpenResty 'resty' executable
2017/02/09 03:25:37 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.2'
2017/02/09 03:25:37 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2017/02/09 03:25:37 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2017/02/09 03:25:37 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/02/09 03:25:37 [verbose] generating default SSL certificate and key
2017/02/09 03:25:38 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2017/02/09 03:25:38 [verbose] generating admin SSL certificate and key
2017/02/09 03:25:38 [verbose] running datastore migrations
2017/02/09 03:25:38 [info] migrating core for keyspace kong
2017/02/09 03:25:40 [info] core migrated up to: 2015-01-12-175310_skeleton
2017/02/09 03:26:03 [info] core migrated up to: 2015-01-12-175310_init_schema
2017/02/09 03:26:06 [info] core migrated up to: 2015-11-23-817313_nodes
2017/02/09 03:26:07 [info] core migrated up to: 2016-02-25-160900_remove_null_consumer_id
2017/02/09 03:26:07 [info] core migrated up to: 2016-02-29-121813_remove_ttls
2017/02/09 03:26:09 [info] core migrated up to: 2016-09-05-212515_retries_step_1
2017/02/09 03:26:09 [info] core migrated up to: 2016-09-05-212515_retries_step_2
2017/02/09 03:26:14 [info] core migrated up to: 2016-09-16-141423_upstreams
2017/02/09 03:26:23 [info] core migrated up to: 2016-12-14-172100_move_ssl_certs_to_core
2017/02/09 03:26:27 [info] core migrated up to: 2016-11-11-151900_new_apis_router_1
2017/02/09 03:26:28 [info] core migrated up to: 2016-11-11-151900_new_apis_router_2
2017/02/09 03:26:34 [info] core migrated up to: 2016-11-11-151900_new_apis_router_3
2017/02/09 03:26:35 [info] core migrated up to: 2016-09-16-141423_upstreams
2017/02/09 03:26:35 [info] migrating request-transformer for keyspace kong
2017/02/09 03:26:35 [info] request-transformer migrated up to: 2016-03-10-160000_req_trans_schema_changes
2017/02/09 03:26:35 [info] migrating rate-limiting for keyspace kong
2017/02/09 03:26:37 [info] rate-limiting migrated up to: 2015-08-03-132400_init_ratelimiting
2017/02/09 03:26:37 [info] rate-limiting migrated up to: 2016-07-25-471385_ratelimiting_policies
2017/02/09 03:26:37 [info] migrating jwt for keyspace kong
2017/02/09 03:26:42 [info] jwt migrated up to: 2015-06-09-jwt-auth
2017/02/09 03:26:43 [info] jwt migrated up to: 2016-03-07-jwt-alg
2017/02/09 03:26:43 [info] migrating hmac-auth for keyspace kong
2017/02/09 03:26:50 [info] hmac-auth migrated up to: 2015-09-16-132400_init_hmacauth
2017/02/09 03:26:50 [info] migrating ip-restriction for keyspace kong
2017/02/09 03:26:50 [info] ip-restriction migrated up to: 2016-05-24-remove-cache
2017/02/09 03:26:50 [info] migrating response-ratelimiting for keyspace kong
2017/02/09 03:26:51 [info] response-ratelimiting migrated up to: 2015-08-21_init_response-rate-limiting
2017/02/09 03:26:52 [info] response-ratelimiting migrated up to: 2016-08-04-321512_response-rate-limiting_policies
2017/02/09 03:26:52 [info] migrating galileo for keyspace kong
2017/02/09 03:26:52 [info] galileo migrated up to: 2016-04-15_galileo-import-mashape-analytics
2017/02/09 03:26:52 [info] migrating acl for keyspace kong
2017/02/09 03:26:59 [info] acl migrated up to: 2015-08-25-841841_init_acl
2017/02/09 03:26:59 [info] migrating basic-auth for keyspace kong
2017/02/09 03:27:04 [info] basic-auth migrated up to: 2015-08-03-132400_init_basicauth
2017/02/09 03:27:04 [info] migrating oauth2 for keyspace kong
2017/02/09 03:27:22 [info] oauth2 migrated up to: 2015-08-03-132400_init_oauth2
2017/02/09 03:27:23 [info] oauth2 migrated up to: 2015-08-24-215800_cascade_delete_index
2017/02/09 03:27:24 [info] oauth2 migrated up to: 2016-02-29-435612_remove_ttl
2017/02/09 03:27:24 [info] oauth2 migrated up to: 2016-04-14-283949_serialize_redirect_uri
2017/02/09 03:27:25 [info] oauth2 migrated up to: 2016-07-15-oauth2_code_credential_id
2017/02/09 03:27:26 [info] oauth2 migrated up to: 2016-09-19-oauth2_code_index
2017/02/09 03:27:30 [info] oauth2 migrated up to: 2016-09-19-oauth2_api_id
2017/02/09 03:27:31 [info] oauth2 migrated up to: 2016-12-15-set_global_credentials
2017/02/09 03:27:31 [info] migrating response-transformer for keyspace kong
2017/02/09 03:27:31 [info] response-transformer migrated up to: 2016-03-10-160000_resp_trans_schema_changes
2017/02/09 03:27:31 [info] migrating key-auth for keyspace kong
2017/02/09 03:27:34 [info] key-auth migrated up to: 2015-07-31-172400_init_keyauth
2017/02/09 03:27:34 [info] 35 migrations ran
2017/02/09 03:27:34 [verbose] migrations up to date
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong.lua:133: [cassandra error] Error during migration 2016-09-05-212515_retries_step_1: [Invalid] Invalid column name retries because it conflicts with an existing column
stack traceback:
       	[C]: in function 'assert'
       	/usr/local/share/lua/5.1/kong.lua:133: in function 'init'
       	init_by_lua:4: in main chunk

stack traceback:
       	[C]: in function 'error'
       	/usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
       	/usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:89>
       	[C]: in function 'xpcall'
       	/usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
       	/usr/local/bin/kong:5: in function 'file_gen'
       	init_worker_by_lua:38: in function <init_worker_by_lua:36>
       	[C]: in function 'pcall'
       	init_worker_by_lua:45: in function <init_worker_by_lua:43>
2017/02/09 03:27:34 [verbose] serf agent not running, deleting /usr/local/kong/pids/serf.pid
2017/02/09 03:27:34 [debug] checking 'serf' executable from 'serf_path' config setting
2017/02/09 03:27:35 [debug] serf version: 'Serf v0.8.0'
2017/02/09 03:27:35 [debug] starting serf agent: nohup serf agent -profile 'wan' -rpc-addr '127.0.0.1:7373' -event-handler 'member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf/serf_event.sh' -bind '0.0.0.0:7946' -node 'kong-4-2qaic_0.0.0.0:7946_60c14944a09e40509143f9f4dd282a36' -log-level 'err' > /usr/local/kong/logs/serf.log 2>&1 & echo $! > /usr/local/kong/pids/serf.pid
2017/02/09 03:27:35 [verbose] waiting for serf agent to be running
2017/02/09 03:27:35 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/02/09 03:27:35 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/02/09 03:27:35 [verbose] serf agent started
2017/02/09 03:27:35 [verbose] auto-joining serf cluster
2017/02/09 03:27:35 [verbose] no other nodes found in the cluster
2017/02/09 03:27:35 [verbose] registering serf node in datastore
2017/02/09 03:27:35 [verbose] cluster joined and node registered in datastore
2017/02/09 03:27:35 [debug] searching for OpenResty 'nginx' executable
2017/02/09 03:27:35 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.11.2.2'
2017/02/09 03:27:35 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2017/02/09 03:27:35 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2017/02/09 03:27:37 [verbose] could not start Kong, stopping services
2017/02/09 03:27:37 [verbose] leaving serf cluster
2017/02/09 03:27:37 [verbose] left serf cluster
2017/02/09 03:27:37 [verbose] stopping serf agent at /usr/local/kong/pids/serf.pid
2017/02/09 03:27:37 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/02/09 03:27:37 [debug] kill -15 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/02/09 03:27:37 [verbose] serf agent stopped
2017/02/09 03:27:37 [verbose] stopped services

**Comment by brianoverton** [comment]
Hmm.. I'm getting the same error:
2017/02/16 17:47:57 [verbose] Kong: 0.9.8
2017/02/16 17:47:57 [verbose] no config file found at /etc/kong.conf
2017/02/16 17:47:57 [verbose] reading config file at /etc/kong/kong.conf
2017/02/16 17:47:57 [verbose] prefix in use: /usr/local/kong
2017/02/16 17:47:57 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/02/16 17:47:57 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2017/02/16 17:47:57 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2017/02/16 17:47:57 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/02/16 17:47:57 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2017/02/16 17:47:57 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
2017/02/16 17:47:57 [verbose] running datastore migrations
2017/02/16 17:47:57 [warn] 10233#0: *2 [lua] log.lua:22: warn(): No cluster infos in shared dict cassandra, context: ngx.timer
2017/02/16 17:47:57 [info] migrating core for keyspace kong
2017/02/16 17:47:57 [info] core migrated up to: 2015-01-12-175310_skeleton
2017/02/16 17:47:58 [info] core migrated up to: 2015-01-12-175310_init_schema
2017/02/16 17:47:58 [info] core migrated up to: 2015-11-23-817313_nodes
2017/02/16 17:47:58 [info] core migrated up to: 2016-02-25-160900_remove_null_consumer_id
2017/02/16 17:48:00 [info] core migrated up to: 2016-02-29-121813_remove_ttls
2017/02/16 17:48:00 [info] migrating jwt for keyspace kong
2017/02/16 17:48:00 [info] jwt migrated up to: 2015-06-09-jwt-auth
2017/02/16 17:48:00 [verbose] could not start Kong, stopping services
2017/02/16 17:48:00 [verbose] leaving serf cluster
2017/02/16 17:48:00 [verbose] left serf cluster
2017/02/16 17:48:00 [verbose] stopping serf agent at /usr/local/kong/pids/serf.pid
2017/02/16 17:48:00 [verbose] serf agent stopped
2017/02/16 17:48:00 [verbose] stopping dnsmasq at /usr/local/kong/pids/dnsmasq.pid
2017/02/16 17:48:00 [verbose] stopped services
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:37: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: Error during migration 2016-03-07-jwt-alg: [Invalid] Invalid column name algorithm because it conflicts with an existing column
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:37: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:89>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:13: in function 'file_gen'
        init_worker_by_lua:38: in function <init_worker_by_lua:36>
        [C]: in function 'pcall'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>

**Comment by jammm** [comment]
One workaround is to change number of replicas of your container to 1, let it finish migrating, then scale back up to two and try again.

Has this worked for you?

**Comment by frederik79** [comment]
One workaround is to change the number of replicas of your container to 1, let it finish migrating, then scale back up to two and try again.

Obviously, this works initially. However, a restart of the Kong containers results in the same migration issue...

**Comment by jammm** [comment]
Try dropping the kong keyspace and try again maybe? Make sure the Cassandra containers are using persistent storage too.

**Comment by brucemartins** [comment]
I see the same error as well, dropping the keyspace cant be an answer to resolving this issue, this should be a bug, seems to be a persistent issue with many people, we have a cluster for cassandra using persistent storage and this still happens, it's a nasty bug which doesn't seem to be getting much attention

**Comment by brianoverton** [comment]
Thanks everyone for your input.
We tried deleting and re-adding the keystore. That did not resolve the problem for us. However, we did realize that our servers were reporting different times. It's early but after fixing NTP it looks like we are no longer seeing the duplicate entry issue.

**Comment by thibaultcha** [comment]
Hi,

If you are encountering this problem and you are on a 0.10 RC, would you mind trying out the patch available at #2145? I believe it should greatly help (with both consistency and speed of the migrations).

Feedback is greatly appreciated on this PR.

Thanks!

**Comment by thibaultcha** [comment]
Considering this fixed with #2145 since there was no reply.
