### ISSUE TITLE
Question: How can I have custom proxy pass configuration for my API?

### ISSUE THREAD

**Issue by k3rn3l-p4n1c** [Mashape/kong#2065]
Hi,
I am using kong for my project. My microservices are Django applications. I used to redirect requests to a uWSGI socket by Nginx uWSGI plugin. In the current state, I have one Nginx instance per Django project. Kong redirects requests to Nginx's instances and they give it to uWSGI. It is working fine but I feel it's a bad practice. Is there any way to remove Nginx's instances and redirect requests from Kong directly to uWSGI? Should I write a plugin? or it can be handled by some changes in Kong's configurations somewhere?
Thanks for your great product

**Comment by Tieske** [comment]
see https://getkong.org/docs/0.9.x/configuration/#custom-nginx-configuration for how to customize it.

**Comment by thibaultcha** [comment]
Closing this as I believe pointing you to how to customize the Nginx configuration is the most we can do right now. Feel free to come back if you have any other question.
