### ISSUE TITLE
Cache consistency for ngx.shared.cache

### ISSUE THREAD

**Issue by Vermeille** [Mashape/kong#2067]
Hello,

The "local" policy for the rate-limiting plugin uses ["cache"](https://github.com/Mashape/kong/blob/master/kong/plugins/rate-limiting/policies.lua#L29) which is a "kong.tools.database_cache". This is implemented as a [ngx.shared.cache](https://github.com/Mashape/kong/blob/master/kong/tools/database_cache.lua#L3). And those caches [are global to all nginx's worker processes](https://github.com/openresty/lua-nginx-module/blob/5028d63536ac795dc56a996416f79279f2f13d5d/doc/HttpLuaModule.wiki#L5106).

Given that worker processes execute concurently, this may be, if I'm not missing anything, a real concurrency concern as it impacts the consistency of the local cache and allows to exceed rate limits.

If the issue is real, several solutions exists. From the worst to the best (that come to my mind):

1. Use a mutex. But performances will greatly suffer.
2. Change the code of ngx.shared.DICT so that it provides an atomic operation. Atomic add, or atomic test and set.
3. Have a way to uniquely identify a worker process, and add that ID to the cache key. Despite being located in shared memory, each worker process will access its own private cache, ensuring consistency. This, however, does not really solve the problem, and makes it a tricky piece of code that needs careful commenting.

Is the problem real? If so, what would be the preferred fix? I'm willing to do it.

Thanks!

**Comment by Tieske** [comment]
@Vermeille I have a hard time following where the issue would be related to the concurrency?

Can you explain in more detail?

**Comment by Vermeille** [comment]
Sure!

[Here](https://github.com/Mashape/kong/blob/master/kong/plugins/rate-limiting/handler.lua#L43), the shared cache is read. Several workers can access this value simultaneously and get the same usage, possibly exceeding the limit.

Reading the code again, it's better than I first thought since cache.incr() is used instead of cache.rawset(count + 1) to increment the requests counter (assuming ngx.shared.incr is safe). The consistency of the counter is ensured. Sorry for having been misleading on that point.

**Comment by Tieske** [comment]
np. The increment is safe.
