### ISSUE TITLE
Kong fails to start due to serf 0.8.1

### ISSUE THREAD

**Issue by atonse** [Mashape/kong#2070]
### Summary

Kong (latest from homebrew) requires `serf 0.8.0` – but I have `serf 0.8.1` – this should work but instead it's not running. I'm not able to install serf 0.8.0 from homebrew. Shouldn't Kong accept any minor version?

### Steps To Reproduce

1. brew update & brew install kong
2. kong start

### Additional Details & Logs

- Kong version (0.9.9)
- Kong debug-level startup logs (`$ kong start --vv`)
```
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:37: /usr/local/share/lua/5.1/kong/cmd/start.lua:22: incompatible serf found. Kong requires version 0.7.0 to 0.8.0, got 0.8.1
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:37: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:89>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:13: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'pcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>
```

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

- Kong configuration (registered APIs/Plugins & configuration file)

- Operating System
macOS Sierra

**Comment by Tieske** [comment]
due to past issues we're rather strict with those. 

That said, its easy to modify the constraints, see https://github.com/Mashape/kong/blob/master/kong/meta.lua

Please try and post back the results.

**Comment by atonse** [comment]
I'd rather not build from source if possible. Isn't it possible to just modify the home-brew formula to just force version 0.8.0 then?

**Comment by thibaultcha** [comment]
Have you tried: 

```
$ brew switch serf 0.8.0
```

To use Serf 0.8.0 in the meantime? I am not sure if we can lock a dependency version from a Formula.

**Comment by atonse** [comment]
Thanks – I tried it, looks like the recipe itself doesn't have 0.8.0. Here's the fun part – I can manually install serf but `brew` complains when I try to uninstall homebrew's `serf` because kong requires it :) I'll force uninstall and then install the older serf manually.

**Comment by Tieske** [comment]
> I'd rather not build from source if possible.

No need to, the Lua files are compiled by LuaJIT on Kong start. So the plain files are in your system, you can simply update it there and start Kong.

**Comment by atonse** [comment]
@Tieske There is only one file in the homebrew installed kong: `bin/kong` – i didn't see any lua.

I manually installed `serf 0.8.0` from serf.io and made it work.

But the issue is still valid for others: if anyone uses homebrew today to install kong, I believe it's actually going to break and there might be similar issues opened on github.

**Comment by thibaultcha** [comment]
@atonse Happy to accept a patch that would lock the version [here](https://github.com/Mashape/homebrew-kong/blob/master/Formula/kong.rb#L19).

**Comment by atonse** [comment]
@thibaultcha Ok sure – will do a bit of research and look into it.

**Comment by atonse** [comment]
Awaiting the pull request referenced above so then we can just point to serf from the mashape-kong tap, to keep versions always in sync.

**Comment by thibaultcha** [comment]
Serf was downgraded back to 0.7.0 in Kong 0.10.1, thanks for the report.
