### ISSUE TITLE
Kong Dynamic header

### ISSUE THREAD

**Issue by midudhula1234** [Mashape/kong#2071]
### Summary

I was wandering if there is a way to add dynamic header (as static content is vulnerable to replay attacks) to Kong. Or any other suggestions on identifying requests have been sent from Kong.  Would appreciate your help.  (Kong version 0.9.9 , OS fedora

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by shashiranjan84** [comment]
Currently we don't have any such plugin for your use case and SSL sounds more appropriate solution for your case.  You can update Nginx conf to secure the transaction between Kong and upstream server(s), eventually it will be supported as Kong configuration. Please refer https://github.com/Mashape/kong/issues/1547 for more updates.  

Also you can always write a custom plugin to handle desired flow. Please check following links for more insight 

[Plugin development]( https://getkong.org/docs/0.9.x/plugin-development/)
[Request transformer plugin](https://github.com/Mashape/kong/tree/master/kong/plugins/request-transformer)
