### ISSUE TITLE
The path portion of the upstream_url is missing

### ISSUE THREAD

**Issue by javeme** [Mashape/kong#2073]
### Summary

When we create an API, and set its upstream_url with a path, then we request this API, we can't  access the upstream_url with path, but only access the root url.

### Steps To Reproduce

1.create an API by client like this:

    {
      name = 'python-kong',
      uris = '/python-kong',
      upstream_url = 'https://github.com/vikingco/python-kong',
    }

2.visit the following URL from my browser:
`https://{nginx-host}/python-kong/`

3.the result is not the page of URL `https://github.com/vikingco/python-kong/`, but the home page`https://github.com/`!

### Additional Details & Logs

- Kong version (0.10.0rc3)
- Operating System (centos6.3)

**Comment by thibaultcha** [comment]
Thank you for the report! See #2077 for an updated patch (+ reasons)

**Comment by thibaultcha** [comment]
Closing this now that RC4 is out. Thanks for the report!
