### ISSUE TITLE
Authenticating 3rd party API with Request Transformer and Authorization header

### ISSUE THREAD

**Issue by grantlucas** [Mashape/kong#2075]
### Summary

I'm not 100% sure if what I'm trying to do is possible or if I've maybe found a bug with request transformer plugin.

My overall setup is an app, Kong, and a 3rd party API. I'd like to authenticate my app with Kong using `key-auth` which works great. I'd then like to authenticate with the 3rd part API using HTTP Basic auth by overriding/setting the Authorization header with my desired one for this 3rd party API.

Using Loggly's logging to debug I can see that the Authorization header *is* being set but it's not 
having any effect on the endpoint.

### Few observations

- If I set the auth header from the app, it's passed through Kong just find and the request succeeds.
- If I **replace** the valid auth header with the request transformer with a garbage header value, I see that it's overridden in Loggly but the request still succeeds when I expect it not to.
- If I *don't* pass an Auth header from the app, I see it showing up when inspecting the request in Loggly but the authentication doesn't succeed as if it wasn't there at all.

### Steps To Reproduce

1. Add Request Transformer plugin to an API that expects Basic Auth
2. Set the Authorization header in the request transformer
3. Try to access the API through Kong *without* passing any authorization
4. I would have expected it to succeed but it fails for my setup

### Additional Details & Logs

- Kong version (0.9.9)
- Operating System: CentOS 7

**Comment by p0pr0ck5** [comment]
@grantlucas can you elaborate a bit more on what you're seeing here? What specifically is Kong not accomplishing, that you're not seeing? When you see the request succeeds, do you mean the request from your client to Kong, or from Kong to Loggly (or something else entirely)?

**Comment by thibaultcha** [comment]
@grantlucas Just a side-note, have you considered using https://luarocks.org/modules/revolsys/kong-plugin-upstream-auth-basic ?

**Comment by grantlucas** [comment]
@p0pr0ck5 A few things have changed since this issue was posted *but* the overall solution was if we wanted to add a header to a request, using the request transformer plugin, we first had to "remove" the header, and then "append" the header. Replacing never seemed to work.

@thibaultcha Thanks for the link! That looks like it'd help a lot instead of having to use request transforming.

**Comment by grantlucas** [comment]
Yup, thanks

**Comment by debu99** [comment]
but why Request Transformer is not work on adding auth header?
