### ISSUE TITLE
Getting error while installing kong "Column family ID mismatch "

### ISSUE THREAD

**Issue by akhildangore** [Mashape/kong#2084]
Hello Team,

I am getting error while installing kong via docker method.

Please find the below error :

```
root@user1-virtual-machine:/home/user1# docker logs d9f6547446d8
2017/02/13 11:07:47 [warn] 6#0: *2 [lua] log.lua:22: warn(): No cluster infos in shared dict cassandra, context: ngx.timer
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: Error during migration 2015-01-12-175310_init_schema: [Server error] java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found ad9dd500-f1dc-11e6-8746-89812c2630d5; expected aaa09a90-f1dc-11e6-8746-89812c2630d5)

  Run with --v (verbose) or --vv (debug) for more details
migrating core for keyspace kong
core migrated up to: 2015-01-12-175310_skeleton
2017/02/13 11:42:06 [warn] 6#0: *2 [lua] log.lua:22: warn(): No cluster infos in shared dict cassandra, context: ngx.timer
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: Error during migration 2015-01-12-175310_init_schema: [Server error] java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found ad9dd500-f1dc-11e6-8746-89812c2630d5; expected aaa09a90-f1dc-11e6-8746-89812c2630d5)

  Run with --v (verbose) or --vv (debug) for more details
migrating core for keyspace kong
2017/02/13 11:42:25 [warn] 6#0: *2 [lua] log.lua:22: warn(): No cluster infos in shared dict cassandra, context: ngx.timer
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: Error during migration 2015-01-12-175310_init_schema: [Server error] java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found ad9dd500-f1dc-11e6-8746-89812c2630d5; expected aaa09a90-f1dc-11e6-8746-89812c2630d5)
```
Please let me know, what is wrong here.

**Comment by revandarth** [comment]
I am also facing the same issue. 

I did spin up single node kong app against cassandra cluster on openshift platform. 

Kong version: 0.9.9
Cassandra: 2.2
Environment: openshift

**Comment by akhildangore** [comment]
Hello, Please any reply on this.

**Comment by hutchic** [comment]
Can confirm I can reproduce the error using the instructions as documented at https://getkong.org/install/docker/

```
docker run -d --name kong-database \
>               -p 9042:9042 \
>               cassandra:2.2
f9248c79ace8e061771bf136ddc5fe6705fa55e1de3bd438c54c21e3f0d14767

docker run -d --name kong \
>               --link kong-database:kong-database \
>               -e "KONG_DATABASE=cassandra" \
>               -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
>               -e "KONG_PG_HOST=kong-database" \
>               -p 8000:8000 \
>               -p 8443:8443 \
>               -p 8001:8001 \
>               -p 7946:7946 \
>               -p 7946:7946/udp \
>               kong
df3b9f1b478d72467f0871e869b102147a6f35836ff16f078db083e2ebf30d08

docker logs kong
2017/02/27 21:29:50 [warn] 11#0: *2 [lua] log.lua:22: warn(): No cluster infos in shared dict cassandra, context: ngx.timer
2017/02/27 21:29:50 [warn] 11#0: *2 [lua] log.lua:22: warn(): No cluster infos in shared dict cassandra, context: ngx.timer
```

```
docker --version
Docker version 1.13.1, build 092cba3
```

```
docker images | grep kong
kong         latest           958a49da171a        2 weeks ago         318 MB
```

**Comment by thibaultcha** [comment]
Which error are we talking about here? Are you referring to:

```
2017/02/27 21:29:50 [warn] 11#0: *2 [lua] log.lua:22: warn(): No cluster infos in shared dict cassandra, context: ngx.timer
```

If so, this is not an error. Future versions of Kong won't include this warning.

**Comment by akhildangore** [comment]
i was getting error Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: Error during migration 2015-01-12-175310_init_schema: [Server error] java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch

but i did refresh installation, it works.

**Comment by hutchic** [comment]
K looks resolved :+1:

**Comment by akhildangore** [comment]
@hutchic,

I have experienced same issue today.

**Comment by hutchic** [comment]
@akhildangore can you post the steps you used to run into the issue and all relevant versions (docker, kong, postgres/cassandra)

**Comment by thibaultcha** [comment]
Mind giving #2145 a try?

**Comment by akhildangore** [comment]
@hutchic,

With reference https://github.com/Mashape/kong/issues/2139.

I was installing KONG with kubernetes this time  but I faced same issue via docker installation.

1. Prerequisites:- Kubernetes cluster initiated please refer https://kubernetes.io/docs/getting-started-guides/kubeadm/ 
2. Run kubectl create -f cassandra.yaml
3. Run kubectl create -f new_kong.yml

Note: Please find above file in zip. [kong _file.zip](https://github.com/Mashape/kong/files/812909/kong._file.zip)

**Comment by akhildangore** [comment]
@thibaultcha, 

sorry, i am from testing background.

Can you provide me rpm file, so i can build docker image on it and test your patch ?

**Comment by Tieske** [comment]
ran into this today: https://github.com/kswapd/kong-kube#tips

could that explain the error?

**Comment by akhildangore** [comment]
@hutchic , Please reopen this issue.

**Comment by hutchic** [comment]
This looks Kubernetes related

Original issue was for Docker
> I am getting error while installing kong via docker method.

Using the docker installation as documented here https://getkong.org/install/docker/ I don't have any issue. I'd suggest creating a new ticket for the Kubernetes problem with `Expected Result`, `Actual Result` and how to reproduce the issue

**Comment by gdrouet** [comment]
Hi,

reproduced today `Column family ID mismatch` with `Kong 0.9.9` and `Cassandra 2.2` installed on `Centos 7`. Is it an issue that is not reproduced with the latest `Kong` version? Was a bug confirmed?

Thanks

**Comment by hutchic** [comment]
Unable to reproduce
```
docker run -d --name kong-database \               
              -p 9042:9042 \
              cassandra:2.2
```

```
docker run -it \                                   
              -e "KONG_DATABASE=cassandra" \
              -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
              -e "KONG_PG_HOST=kong-database" \
              centos:7
```

```
curl -O -L https://github.com/Mashape/kong/releases/download/0.10.0/kong-0.10.0.el7.noarch.rpm
yum install epel-release
yum install kong-0.10.0.*.noarch.rpm --nogpgcheck
kong start
curl 127.0.0.1:8001
```

**Comment by gdrouet** [comment]
Ok sounds related du `Kong` version.
Just to be sure: I have this problem when I have several nodes in my `Cassandra` version.

**Comment by thibaultcha** [comment]
Yes, please update to the latest 0.10.0 to resolve.

**Comment by mgiorgio** [comment]
@thibaultcha, thanks for your answer. So, it looks like the bug is related to the 0.9.x version. Is there any workaround for that version so I don't need to migrate right now?

**Comment by thibaultcha** [comment]
No, this is inherent to how Kong runs its migrations, so unless you are running a single Cassandra node, you *might* (I insist on *might*) encounter this race condition.

**Comment by mgiorgio** [comment]
I see. We're running multiple Cassandra instances so it looks like I will be migrating soon. Out of curiosity, has Kong changed how it manages migrations on 0.10.X?

**Comment by thibaultcha** [comment]
See #2145. Although, note that we were unsuccessful at reproducing this issue on our side btw. Maybe your cluster is mis-configured in the first place?

**Comment by mgiorgio** [comment]
Well, I had Kong running in one datacenter and then deployed exactly the same Docker images in the exact same way, and it failed in the second datacenter.

I initially saw this issue when I installed Kong locally but then I deleted it, installed it again and it worked. I thought that I had done something wrong but now it does look like a race condition. I hope #2145 fixes it.
