### ISSUE TITLE
File-Log plugin to provde request and response bodies

### ISSUE THREAD

**Issue by shobhitver91** [Mashape/kong#2095]
### Summary

I have been using the file-log plugin for a while now. I would like to know if there is a way to add request and response bodies in the logging as well. I have never written lua. So if you can provide me with some pointers to modify this plugin so as to add request and response bodies, I would be grateful.

**Comment by thibaultcha** [comment]
Hi,

You can browse the file-log plugin source code for some inspiration:

https://github.com/Mashape/kong/blob/master/kong/plugins/file-log/handler.lua

**Comment by shobhitver91** [comment]
HI,
I have been there and could not get the variables required for request and response body. 
Can you provide me pointers to a plugin which works with request and response body so that I can take help from there

**Comment by thibaultcha** [comment]
Please consult the ngx_lua documentation to better understand how to use Lua in Nginx: https://github.com/openresty/lua-nginx-module

**Comment by robotnic** [comment]
Have a look at the runscope plugin. They log request und response body.
