### ISSUE TITLE
Kong-OAuth2-Authorization problem

### ISSUE THREAD

**Issue by midudhula1234** [Mashape/kong#2097]
Hi
We recently started using Kong(open Source version). I see that if we add OAuth to an api it’s not consumer specific. Any consumer created with OAuth credentials in Kong can access the api. And the generated OAuth tokens are not api specific as well.  Let’s say I generated an OAuth token for Api1, I can use it for Api2 which needs OAuth authentication. Is there any reason it was designed this way? IS it not a problem for scaling? We use Fedora as OS and kong version 0.9.9. I would really appreciate your help on this. Thanks, in advance.

**Comment by DonMartin76** [comment]
Hi,

Usually you combine the `oauth2` plugin with the `acl` plugin to decide which consumers are allowed to access which API.

Essentially, and this is important to understand, `oauth2` is just a specific way of recognizing which consumer is trying to access the API. Whether he's allowed ("authorized") to has to be dealt with either in a separate authorization server, and/or by leveraging the access control lists with the `acl` plugin.

Best regards,
Martin
