### ISSUE TITLE
Make "bin/kong" work when installed globally with Luarocks

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#21]
The problem is that when kong is being installed with Luarocks, the `kong` command doesn't know which `KONG_HOME` to use.

**Comment by thefosk** [comment]
Not sure we still want to do this, since we prefer other distribution modes for installing Kong, like `rpm` or `deb` packages.

**Comment by thibaultCha** [comment]
With #88, luarocks is now the recommended way to install Kong.
