### ISSUE TITLE
No Way to Use "#" in `kong.conf` File

### ISSUE THREAD

**Issue by wojtek-oledzki** [Mashape/kong#2101]
### Summary

You can not use "#" in kong.conf

### Steps To Reproduce

1. set pg_password to test#123
2. restart kong

### Additional Details & Logs

- Kong version 0.9.*

https://github.com/Mashape/kong/blob/692caa9dc2db22f83743e63373da6fab45c174f4/kong/conf_loader.lua#L288

using `trim_quotes` might help.

**Comment by woledzki** [comment]
`trim_quotes` did not helped :D

Looks like a major limitation for kong (and pl.config)

**Comment by thefosk** [comment]
@woledzki seems like this has been fixed in 0.10 by updating the penlight library to latest.

**Comment by p0pr0ck5** [comment]
Doesn't look like a Penlight issue, but rather how we treated octothorpes (assuming all characters following one are comments). We can ammend this behavior by allowing escaped octothorpes in config directives (e.g. `test\#123`)
