### ISSUE TITLE
Rename the copied kong.conf file used internally

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#2103]
When starting up Kong we dump the configuration of Kong into `/usr/local/kong/kong.conf` for internal use. 

The system will check if a real configuration file exists at `/etc/kong/kong.conf`, it will then check any environment variable that has been set, value any missing property with the default values, and dump the resulting output into `/usr/local/kong/kong.conf`.

The problem is that some users will execute a `find / type -name kong.conf -type f` on an instance with Kong running, they will assume that `/usr/local/kong/kong.conf` is the real configuration file.

# Solution

Rename `/usr/local/kong/kong.conf` to something else, like `/usr/local/kong/.cli_conf`.

**Comment by thibaultcha** [comment]
#2136

**Comment by p0pr0ck5** [comment]
Closing as this was done as noted above.
