### ISSUE TITLE
Kong sort the query string of URI by alphabet.

### ISSUE THREAD

**Issue by justinchia0910** [Mashape/kong#2113]
### Summary

When Kong get request, Kong is going to sort query string of URI by alphabet before redirecting request to upstream.

### Steps To Reproduce

1. Adding an API to Kong with upstream_url and request_path, for expamle 'upstrame_url=http://abc.com' and 'request_path=/v2/customers'
2. To send request to Kong, the url is http://kong_host/v2/customers?bb=1&aa=2
3. Finally API is going to get request with URI: /v2/customers?aa=2&bb=1

### Additional Details & Logs

- Kong version
Kong version: 0.9.7

- Kong configuration
Added Plugins: Galileo, File Log

- Operating System
CentOS 6.8

**Comment by thibaultcha** [comment]
Hi,

Yes indeed. Is that an issue for you? If so, why?

Could you please try 0.10, where I believe such a behavior should not occur anymore. Thanks!

**Comment by justinchia0910** [comment]
Hi ,

Thanks for your reply. It's a issue for our end since some of our API use URI to be a parameter of HASH for authentication, Kong rearranges query string which will cause the failed authentication.

I found the latest version is 0.10RC4, I am going to check this issue on 0.10RC4.  May I know when 0.10 will release? Thanks.

**Comment by kirikak2** [comment]
:+1:

I have same problem. Now I created kong plugin which copy original url from another header.
If it solves in KONG 0.10, it's great news.

**Comment by justinchia0910** [comment]
Hi,

I have verified this issue on KONG 0.10RC4. Per my verification, this issue has been solved. Thanks a lot.
