### ISSUE TITLE
PR proposal: Global rate-limiting with caching

### ISSUE THREAD

**Issue by Vermeille** [Mashape/kong#2116]
Hello,

I am working on a rate-limiting algorithm combining the benefits of the "local" and "cluster" policy:

1. A global limit is defined by the user for the whole Kong cluster
2. Each Kong instance then defines a local limit being global_limit / nb_instances. This assumes a round robin-like load balancing between instances, which is a very likely scenario.
3. Every n-seconds (currently, n=30), the number of kong instance is fetched from Serf, and the local limit is adjusted according to (2). This make this approach resilient to node failures / spawns.
4. Every n-seconds, the local usage for the periods hour, day, month, year is updated to the database (it doesn't make sense for smaller time periods with n=30s), and the global usage is redistributed among the nodes. This way, we try to balance an un-even distribution of usage.

This has the obvious benefit of having a globally defined limit, while having approximately the performance of a local policy. It also has the downside of sending non monotonic decreasing usage metrics to the client, and having a node say that the limit is exceeded while some other still have requests remaining. Note: Those downsides are the same as the local policy, but we alleviate them with resyncs.

Would you be interested in having this as a PR? What would be your constraints or requirements?

Best regards.

**Comment by Tieske** [comment]
see also discussion in #2127

**Comment by Vermeille** [comment]
https://github.com/Mashape/kong/pull/2169 Here is the associated PR.

**Comment by Tieske** [comment]
closing this in favor of discussion in #2169
