### ISSUE TITLE
How to install Kong on Fedora 21? Requires: lua = 5.1.4 , but already 5.2.2

### ISSUE THREAD

**Issue by juncoding** [Mashape/kong#212]
Hi,  When I install Kong, I met below issues, please advise: Thanks!

--> Finished Dependency Resolution
Error: Package: kong-0.2.0_2-1.noarch (/kong-0.2.0_2.el7.noarch)
           Requires: lua = 5.1.4
           Installed: compat-lua-5.1.5-2.fc21.x86_64 (@fedora)
               lua = 5.1
           Installed: lua-5.2.2-8.fc21.x86_64 (@anaconda)
               lua = 5.2.2-8.fc21
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

[root@ip-172-30-0-136 ~]# yum install lua
Failed to set locale, defaulting to C
Package lua-5.2.2-8.fc21.x86_64 already installed and latest version
Nothing to do

**Comment by thibaultCha** [comment]
Kong needs lua 5.1, so you'll have to remove 5.2 and use 5.1.

**Comment by juncoding** [comment]
Ok. thanks.
