### ISSUE TITLE
OAuth 2.0 plugin and Kong documentation

### ISSUE THREAD

**Issue by githoub** [Mashape/kong#2126]
### Summary

In OAuth2 plugin docs, I didn't find any chapter about OAuth2 token generation except the 'Migrating Access Tokens' chapter: https://getkong.org/plugins/oauth2-authentication/#migrating-access-tokens

### cURL request
I can generate access tokens using the 'oauth2_tokens' path:

curl -i -X POST http://localhost:8001/oauth2_tokens/ --data "credential_id=dd141531-04bb-48c6-8920-1fd7ee2e9e10" --data "expires_in=3600"
 
HTTP/1.1 201 Created
Date: Thu, 23 Feb 2017 16:02:09 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.9.9
 
{"token_type":"bearer","id":"edaa469e-57e9-4677-a44d-759635f3fe93","expires_in":3600,"credential_id":"dd141531-04bb-48c6-8920-1fd7ee2e9e10","created_at":1487865729000,"access_token":"5a2782be7dfd439482e0ca039afccfad"}

### Question
**To generate an OAuth2 token for a consumer, should we use /oauth2_tokens path ? 
This path is not reserve for migrating access tokens?**

### Additional Details & Logs

- Kong version: 0.9.9
- Operating System: Ubuntu

**Comment by thefosk** [comment]
These are the endpoints using for requesting a new authorization code/token https://getkong.org/plugins/oauth2-authentication/#endpoints

**Comment by tigerich** [comment]
Looks the endpoints are not working for me
/oauth2/token

it returns  the follows:
{
  "message": "Not found"
}

what is going on here?

**Comment by thefosk** [comment]
You need to consume those endpoints on top of the API that you are targeting.

ie: if you have an API on Kong that maps to a specific "request_path" or "uris", for example, `/test`, then the endpoints will be available at `/test/oauth2/token`.

If instead you are using a `Host` header to map your APIs, you will have to pass the appropriate `Host` header value to trigger the specific API you are targeting while requesting `/oauth2/token`.

**Comment by tigerich** [comment]
Thanks @thefosk 

After I added Host header, the response changes somewhat.
But still it returns the following error message. What can I do?

{
  "error": "unsupported_grant_type",
  "error_description": "Invalid grant_type"
}

**Comment by thefosk** [comment]
You need to pass a valid `grant_type` parameter, as per OAuth 2.0 specification.

**Comment by thibaultcha** [comment]
This discussion for this is at #2219, considering this as answered :)
