### ISSUE TITLE
Multiple SSL Certs

### ISSUE THREAD

**Issue by patrickbaber** [Mashape/kong#2128]
Is there a way to define multiple SSL certificates for different common names? In the docs I only find the option to define one certificate and private key pair.

URL: https://getkong.org/docs/0.9.x/configuration/#ssl_cert

**Comment by konrade** [comment]
If it works the same way in 0.10 as in 0.9 then you can add several snis entries referencing the same certificate entry.

Do GET http://kong:8001/certificates to find the id of your already defined certificate and use that in POST http://kong:8001/snis {"name": "another.domain", "ssl_certificate_id" : "id_from_get"}

**Comment by thibaultcha** [comment]
In 0.9, you would have to configure an API with a `request_host` being your SNI, and then configure the `ssl` plugin for it. See https://getkong.org/plugins/dynamic-ssl/

In 0.10, dynamic SSL certificated are directly handled in the core, and thus you can use the Admin API endpoints pointed out by @konrade. You can also find more info about it in the new [proxy guide](https://github.com/Mashape/getkong.org/blob/d2297ee661f8b535fa2605ba8fd0e0d8e28b3229/app/docs/0.10.x/proxy2.md) (still a draft).
