### ISSUE TITLE
How KONG connect to remote postgres

### ISSUE THREAD

**Issue by guankai** [Mashape/kong#2130]
How `KONG` connect to remote postgres?

write the `KONG_PG_HOST` like 

postgres://user:pass@ipaddress:port ?

**Comment by thibaultcha** [comment]
It connects through TCP. pg_host should only be the host (or ip address) of your server.

**Comment by guankai** [comment]
@thibaultcha 
I have connect it by these Environment
```
docker run -d --name kong \
              -e "KONG_DATABASE=postgres" \
	      -e "KONG_PG_USER=kong" \
	      -e "KONG_PG_PASSWORD=kong" \
	      -e "KONG_PG_DATABASE=kong" \
              -e "KONG_PG_HOST=192.168.56.101" \
              -e "KONG_PG_PORT=5432" \
              -p 8000:8000 \
              -p 8443:8443 \
              -p 8001:8001 \
              -p 7946:7946 \
              -p 7946:7946/udp \
              kong
```
suggest that these Environments should be write clearly in the readme.md

**Comment by thibaultcha** [comment]
I think it's clear enough in the config file.

**Comment by guankai** [comment]
ok,thank you
