### ISSUE TITLE
Fail to parse SSL certificate after upgrading to 0.10

### ISSUE THREAD

**Issue by suclogger** [Mashape/kong#2133]
kong version: 0.10 RC4
Operating System: centos

>The SSL plugin has been removed and dynamic SSL capabilities have been added to Kong core, and are configurable via new properties on the API entity.

I tried to configure a certificate for an api using:
```
curl -X POST http://localhost:8001/certificates \
  -d "cert=/opt/App/kong/example.pem" \
  -d "key=/opt/App/kong/example.key" \
  -d "snis=example.com"
```

But it seems `ssl.parse_pem_cert` failed to parse my certificate:
```
2017/02/28 11:03:50 [error] 20690#0: *613 [lua] certificate.lua:15: log(): [ssl] could not parse PEM certificate: PEM_read_bio_X509_AUX() failed, context: ssl_certificate_by_lua*, client: 192.168.1.1, server: 0.0.0.0:443
2017/02/28 11:03:50 [crit] 20690#0: *612 SSL_do_handshake() failed (SSL: error:1408A179:SSL routines:ssl3_get_client_hello:cert cb error) while SSL handshaking, client: 192.168.1.1, server: 0.0.0.0:443
```

Before 0.10 it worked well using SSL plugins with the same certificate, and I've verified my certificate using openssl command:`openssl req -text -noout -verify -in example.pem` without any complain.

**Comment by thibaultcha** [comment]
Either your certificate is invalid, either the value given to `ssl.parse_pem_cert()` is not what we expect it to be. Could you check what the configured `cert` is from the Admin API? And if possible, give us steps to reproduce this.

**Comment by suclogger** [comment]
@thibaultcha Thanks for replay.

Certificate API shows as follow:
```
[
{
cert: "/opt/App/kong/example.pem",
id: "4b247df5-bef9-4b7a-bf0a-e8116d079f23",
snis: [
"example.com"
],
key: "/opt/App/kong/example.key",
created_at: 1488082607000
}
]
```

Snis API shows as follow:
```
{
data: [
{
name: "example.com",
created_at: 1488082607000,
ssl_certificate_id: "4b247df5-bef9-4b7a-bf0a-e8116d079f23"
}
],
total: 1
}
```

I'm pretty sure my certificate works well before upgreading to 0.10.

Steps to reproduce:

1. Add an api:
```
curl -X POST http://localhost:8001/apis \
  -d "name=example" \
  -d "hosts=example.com" \
  -d "https_only=true" \
  -d "upstream_url=http://172.21.1.1"
```
2.  Assign a certificate to it:
```
curl -X POST http://localhost:8001/certificates \
  -d "cert=/opt/App/kong/example.pem" \
  -d "key=/opt/App/kong/example.key" \
  -d "snis=example.com"
```
3. error log complains about `could not parse PEM certificate`.

**Comment by thibaultcha** [comment]
You sent your cert/key pair as a strings containing their path on your machine. You need to send the actual content of the file, aka the `-F "file=@path"` curl argument. Please let us know.

**Comment by thibaultcha** [comment]
Maybe the Admin API could display that such certificates are invalid before insertion. Do you feel like contributing to such a feature?

**Comment by suclogger** [comment]
@thibaultcha Thanks very much, it did solve my problem.
I would try to dig into it, hope I could help to contribute some day.

**Comment by fancy512** [comment]
@suclogger   嗨, we also encountered the same problem with you, please let your is how to deal with, my email address is 2589490057 @qq.com, thank you

**Comment by suclogger** [comment]
@fancy512 As @thibaultcha mentioned above, cert should be upload while requesting the certificate api rather than specific a path point to cert position.
