### ISSUE TITLE
Plugin proposal: gRPC

### ISSUE THREAD

**Issue by skunkwerk** [Mashape/kong#2137]
### Summary

Add support for gRPC to complement JSON REST, for higher-performance with lower overhead.

Reference: http://www.grpc.io/

**Comment by sonicaghi** [comment]
https://github.com/Mashape/kong/issues/413

**Comment by p0pr0ck5** [comment]
Closed as dup

**Comment by dineshkumar-cse** [comment]
#413 is REST to RPC, Does kong have direct gRPC support? Intercepting a request and forward to backend, like a proxy.

**Comment by Tieske** [comment]
@dineshkumar-cse No. On the radar, but not available for now.

**Comment by bungle** [comment]
Soonish it will come to Nginx (not sure about OpenResty though): https://trac.nginx.org/nginx/roadmap

**Comment by xunchangguo** [comment]
gRPC whil Support with NGINX 1.13.10. https://www.nginx.com/blog/nginx-1-13-10-grpc/. Does kong or OpenResty will support ?

**Comment by bungle** [comment]
@xunchangguo I am sure they will. Latest OpenResty uses Nginx 1.13.6. So it is not that much behind. Kong will be updated to 1.13.6 tomorrow with 0.13 release. It will take some time, but eventually we get that.

**Comment by jbergstroem** [comment]
Perhaps time to reopen?

**Comment by jeremyjpj0916** [comment]
gRPC is something I am very curious on as based on some initial readings it seems to be the next stepping stone for how to move data around within companies via web transactions in the  most performant manner. I think it will take the market awhile to catch up but if Kong gets a head start on this and we can get some decent auth plugins around gRPC with Kong too that will be incredible.

**Comment by jyane** [comment]
This issue seems not to be duplicated, IMHO.
https://github.com/Kong/kong/issues/413 is "REST support" for gRPC and this issue is "direct support" for gRPC.

**Comment by naturallight** [comment]
+1
