### ISSUE TITLE
0.10 new API router as a more granular acl

### ISSUE THREAD

**Issue by mbande** [Mashape/kong#2140]
### Summary

it seems that [new router api](https://github.com/Mashape/kong/pull/1970) make it available to define acl rules per uri+method combination, is it true?
can somebody provide an example of how to use this new router. e.g. to allow 'user' group to view /foo list (GET /foo), but not to create foo(POST /foo). at the same time to allow 'staff' group to create a new one

**Comment by Tieske** [comment]
when creating an api you can specify the methods, so the GET would be a different api than the POST or example. Each can have its own plugins.

for unreleased docs see https://github.com/Mashape/getkong.org/blob/d3c400701233b2c99635e90653a1dada0a5273ce/app/docs/0.10.x/proxy.md
