### ISSUE TITLE
Question: why use host to target api?

### ISSUE THREAD

**Issue by William-Sang** [Mashape/kong#2141]
As a api gateway, when we add apis to it, we need one way to target specific api.
There're 2 way to target apis in kong for clients:

1. Proxy an API by its DNS value

``` 
# send a request
$ curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: mockbin.com'
```

2. Proxy an API by its request_path value

```
# send a request
$ curl -i -X GET \
  --url http://localhost:8000/status/200
```

Then one question comes to me that why clients need know host behind gateway? I think clients shouldn't know host behind gateway. In which Scenario, will we use the first way? 
Thinks

**Comment by Tieske** [comment]
when using multiple apis, each on their own domain? served by a single Kong cluster

the new 0.10 release allows more flexibility by combining http methods, hosts and request paths.
