### ISSUE TITLE
Kong serf check needs some cleanup

### ISSUE THREAD

**Issue by p0pr0ck5** [Mashape/kong#2147]
### Summary

Serf version checking has some mismatched function signatures that obscure invalid Serf version errors

### Steps To Reproduce

N/A

### Additional Details & Logs

local function `check_serf_bin` (https://github.com/Mashape/kong/blob/release/0.10.0/kong/cmd/utils/serf_signals.lua#L47) compares only a boolean result of the first value of `check_version`; however, `check_version` returns a nil and an error string on version mismatch (https://github.com/Mashape/kong/blob/release/0.10.0/kong/cmd/utils/serf_signals.lua#L31). This error is not bubbled up or logged, instead, the user is only told the serf executable could not be found (https://github.com/Mashape/kong/blob/release/0.10.0/kong/cmd/utils/serf_signals.lua#L55). Systems running an invalid Serf version are never informed about this condition.

Additionally, the current version of Serf available for download (v0.8.1) is not compatible based on (https://github.com/Mashape/kong/blob/master/kong/meta.lua#L22), yet this is not clearly identified. https://getkong.org/install/source/ indicates v0.8 should be installed, but if Serf follows semantic versioning, should v0.8.1 not also be available? Either Kong should more flexibly respect semantically-versioned dependencies, or the strict version checking should be more clearly documented.

**Comment by Tieske** [comment]
we've been defensive with versions, only versions we know that work. Hence the strictness.

not sure wether it's worthwhile to update while we progressing to drop Serf...

**Comment by p0pr0ck5** [comment]
Sounds like we should:

- Document that semver isn't followed
- Log and let the user know when an invalid serf version is found
- Audit other dependency checkers and make sure they aren't swallowing up errors

I'll have a PR for the second item up shortly. First item sounds like it might fit on getkong.org/install/source? Third item sounds like a backlogged bug ;)

**Comment by thibaultcha** [comment]
> not sure wether it's worthwhile to update while we progressing to drop Serf...

+1

However, 

> we've been defensive with versions, only versions we know that work. Hence the strictness.

As recently discussed, I think we should be less strict with those and avoid trying to prevent forward compatibility. We should only enforce versions we never tested (< 0.7), but we shouldn't enforce users from using future releases. If they're not tested against, they are on their own, but at least we should be permissive enough to allow it.

**Comment by p0pr0ck5** [comment]
https://github.com/Mashape/kong/commit/803646a56376003ad2b1377da34914509db17d30 addresses concerns about dep versions, but I'm not sure where to point the PR given the imminent release of 0.10. Same with https://github.com/Mashape/kong/commit/44c63455c5285e31e6849622d997847353b38c5a and serf search path logging.

**Comment by Tieske** [comment]
btw Serf is in the 0.x phase, hence SemVer does not apply. Only works from 1.x onwards, 0.x is considered unstable.

but if we want the Serf dependency to be less strict then simply specify
```lua
serf = {"0.7.0", "0.8.999"},
```
or even better (but this requires changes elsewhere)
```lua
serf = version.set("0.7.0","0.9.0"):disallowed("0.9.0")
```
the latter has a better error message.

**Comment by p0pr0ck5** [comment]
semver doesn't apply to openresty either ;) does this mean we cant imply any sort of minimum version requirement?

**Comment by Tieske** [comment]
we recently saw a breaking change in an y.y.y.x release (enabling lua 5.2 compatibility)

I'm confident that for Serf allowing the whole 7.x and 8.x should be ok though.

**Comment by p0pr0ck5** [comment]
Given that Serf is going to be dropped, and the following PRs handled the immediate-term work to be done here:

https://github.com/Mashape/kong/pull/2156
https://github.com/Mashape/kong/pull/2157

Any objections to closing this?

**Comment by thibaultcha** [comment]
All good, thanks! :)
