### ISSUE TITLE
Update a plugin without api_id

### ISSUE THREAD

**Issue by niyue** [Mashape/kong#2148]
### Summary

According to Kong's documentation, we can add a plugin for every API and Consumer and we don't need to set api_id and consumer_id in this case. My question is, after creating a plugin for every API and consumer, how we can update the configuration for such an API.

### Steps To Reproduce

1. Create a plugin for every API. 
```
curl -i -X POST \
  		--url http://localhost:8001/plugins/ \
  		--data 'name=my-plugin'
```
The plugin is correctly created because we can see it when listing all plugins, and there is no api_id associated with this plugin.

2. Try to update plugin configuration using PATCH (https://getkong.org/docs/0.9.x/admin-api/#update-plugin)
```
curl -X PATCH http://localhost:8001/plugins \
    	--data "name=my-plugin" \
    	--data "config.k1=v1"
```
HTTP 405 Method not allowed is reported with the following response body:
```
{"message":"Method not allowed"}
```
So using PATCH doesn't work in this case.

3. Try to update plugin configuration using PUT (https://getkong.org/docs/0.9.x/admin-api/#update-or-add-plugin)
```
curl -X PUT http://localhost:8001/plugins \
    	--data "name=my-plugin" \
    	--data "config.k1=v1"
``` 
HTTP 409 Conflict is reported with the following response body:
```
<html>
<head><title>409 Conflict</title></head>
<body bgcolor="white">
<center><h1>409 Conflict</h1></center>
<hr><center>openresty/1.11.2.1</center>
</body>
</html>
```
So using PUT doesn't work neither.

**Expectation:**
Actually I expect both PATCH and PUT API work when updating plugin configuration task. There are all relevant REST APIs I can find in the doc, am I missing something?

PS:
It works if I create the plugin initially with the configuration, but that doesn't help if I need to update an existing plugin's configuration. 

### Additional Details & Logs

- Kong version: 0.9.5

**Comment by p0pr0ck5** [comment]
@niyue can you try upgrading to kong v0.10 RC4 and let us know if you experience the same behaviors?

**Comment by thibaultcha** [comment]
@niyue You should be able to make your PATCH request to `/plugins/{plugin_id}`. The documentation is wrong in showing that `/apis/{api}/plugins` is the base URI for all plugins. It is `/plugins`.

Side note: our PUT requests sadly do not comply to the HTTP specs, in the sense that they are not applied on the URI containing that entity (`/plugins/123`) but rather on the resource URI (`/plugins`).

**Comment by niyue** [comment]
@thibaultcha Thanks, I gave it a try, `PATCH /plugins/{plugin_id}` did work for me, and `PUT /plugins/{plugin_id}` gave me a HTTP 405 method not allowed response.

But the solution is less than ideal since it requires me to know the plugin_id instead of plugin name to update a plugin. Does this mean I have to retrieve a plugin id using its name before doing the update? It seems there is no API that can do the filtering and I have to list all plugins and do the filtering on the client, is it correct?

**Comment by thibaultcha** [comment]
> PUT /plugins/{plugin_id} gave me a HTTP 405 method not allowed

Because you need to `PUT /plugins`, and specify the id in the request body. As I said, our PUT implementation does not respect the actual HTTP specs.

> it requires me to know the plugin_id instead of plugin name to update a plugin

This is mandatory, since different plugins can have the same name. You need their id to distinguish them.

> Does this mean I have to retrieve a plugin id using its name before doing the update?

It means you need to know the plugin id in advance. Or retrieve it by distinguish it from all the other plugins with the same name.

> It seems there is no API that can do the filtering and I have to list all plugins and do the filtering on the client, is it correct?

Yes. You can use the query strings parameters documented [here](https://getkong.org/docs/0.9.x/admin-api/#list-all-plugins) to do so and narrow down your search.

**Comment by niyue** [comment]
> You can use the query strings parameters documented here to do so and narrow down your search.
Thanks, that is really useful. I somehow didn't notice this previously. 

> This is mandatory, since different plugins can have the same name. You need their id to distinguish them.
The doc gave me a different impression initially. In the doc [here](https://getkong.org/docs/0.9.x/admin-api/#update-or-add-plugin), to update an plugin, it seems we only need to provide `api_id` and `plugin_in`'s name to identify a plugin, which seems not the case according to what you said here. Probably we need to update the doc to make it more clear. 

Thanks a lot for the reply. It is much more clear how I can use the API for updating a plugin configuration.

**Comment by niyue** [comment]
> Because you need to PUT /plugins, and specify the id in the request body. As I said, our PUT implementation does not respect the actual HTTP specs.

This seems to introduce some inconvenience for API clients, for example, the client may want to update a plugin's configuration, but the plugin may or may not exist, depending on if a plugin exists or not, the client needs to call different APIs:
```
GET /plugins?name=my-plugin
if my-plugin exists then
  PATCH /plugins/{plugin_id}
else
  PUT /plugins
end
```
If the PUT API can handle this, clients will be easier to write.

**Comment by thibaultcha** [comment]
Agreed. I too would like to properly use PUT.
