### ISSUE TITLE
kong deployment files  in kubenetes environment

### ISSUE THREAD

**Issue by kswapd** [Mashape/kong#2150]
### Summary
Hi, 
     I added kubernetes deployment files for kong, git url:
           https://github.com/kswapd/kong-kube.git
     Hope this can hope someone else. :)

**Comment by shashiranjan84** [comment]
Thanks, but no need to create a issue to inform other ppl. You cam post in our Gitter channel or Mailing group.

Meanwhile you can refer this too https://github.com/Mashape/kong-dist-kubernetes
