### ISSUE TITLE
how to properly add custom `ssl_*` config

### ISSUE THREAD

**Issue by tumluliu** [Mashape/kong#2153]
### Summary

I want to add some custom ssl_* config e.g. `ssl_session_cache`, `ssl_session_timeout`, `ssl_prefer_server_ciphers` and `ssl_ciphers` to Kong's config. What's the proper way to do that? Thanks!

### Additional Details & Logs

- Kong version 0.9.8
- Operating System: Ubuntu 16.04

**Comment by thibaultcha** [comment]
Hi,

Currently, you would have to create your own Nginx configuration template as instructed here:
    https://getkong.org/docs/0.9.x/configuration/#custom-nginx-configuration

In this template, you can introduce any Nginx directives that you'd like.
