### ISSUE TITLE
Unable to start kong

### ISSUE THREAD

**Issue by timsakshi** [Mashape/kong#2175]
I am getting below error when i try to start Kong.

[apiadm@lesbdnasv03 ~]$ kong start --v kong.conf
2017/03/08 11:23:38 [verbose] Kong: 0.9.9
2017/03/08 11:23:38 [verbose] no config file found at /etc/kong.conf
2017/03/08 11:23:38 [verbose] reading config file at /etc/kong/kong.conf
2017/03/08 11:23:38 [verbose] prefix in use: /usr/local/kong
2017/03/08 11:23:38 [verbose] preparing nginx prefix directory at /usr/local/kon                                                                                        g
2017/03/08 11:23:38 [verbose] saving serf identifier to /usr/local/kong/serf/ser                                                                                        f.id
2017/03/08 11:23:38 [verbose] saving serf shell script handler to /usr/local/kon                                                                                        g/serf/serf_event.sh
2017/03/08 11:23:38 [verbose] SSL enabled, no custom certificate set: using defa                                                                                        ult certificate
2017/03/08 11:23:38 [verbose] default SSL certificate found at /usr/local/kong/s                                                                                        sl/kong-default.crt
2017/03/08 11:23:38 [verbose] running datastore migrations
2017/03/08 11:23:38 [warn] 29284#0: *2 [lua] log.lua:22: warn(): No cluster info                                                                                        s in shared dict cassandra, context: ngx.timer
2017/03/08 11:23:38 [verbose] could not start Kong, stopping services
2017/03/08 11:23:38 [verbose] leaving serf cluster
2017/03/08 11:23:38 [warn] 29284#0: *2 [lua] log.lua:22: warn(): No cluster info                                                                                        s in shared dict cassandra, context: ngx.timer
2017/03/08 11:23:43 [verbose] stopping dnsmasq at /usr/local/kong/pids/dnsmasq.pid
2017/03/08 11:23:43 [verbose] stopped services
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:37: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: [cassandra error] All hosts tried for query failed. 127.0.0.1: connection refused for socket with peer 127.0.0.1.
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:37: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:89>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:13: in function 'file_gen'
        init_worker_by_lua:39: in function <init_worker_by_lua:37>
        [C]: in function 'pcall'
        init_worker_by_lua:46: in function <init_worker_by_lua:44>

Please let me know how to get this issue resolved.

**Comment by ccyphers** [comment]
@timsakshi do you have DAO setup in /etc/kong/kong.conf?  apparently no connection to cassandra could be established.

**Comment by timsakshi** [comment]
@ccyphers Please find the attached kong.conf 
[kong (2).txt](https://github.com/Mashape/kong/files/829641/kong.2.txt)

**Comment by timsakshi** [comment]
I am getting same error when i try to restart kong using command "kong restart --c /etc/kong/kong.conf"

Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: [cassandra error] All hosts tried for query failed. 127.0.0.1: connection refused for socket with peer 127.0.0.1.

**Comment by Tieske** [comment]
Appears Kong cannot connect to the Cassandra database.

can you use cqlsh to connect to the cassandra database from the Kong machine? once that works use the same connection info in the kong configuration file.

**Comment by timsakshi** [comment]
@Tieske  I got below error with cqlsh
**-bash: cqlsh: command not found**

i got below as output whrn i try to start cassandra using **bin/cassandra -f**
INFO  [main] 2017-03-09 06:25:42,874 StorageService.java:2248 - Node localhost/127.0.0.1 state jump to NORMAL
INFO  [main] 2017-03-09 06:25:42,977 NativeTransportService.java:70 - Netty using native Epoll event loop
INFO  [main] 2017-03-09 06:25:43,032 Server.java:155 - Using Netty Version: [netty-buffer=netty-buffer-4.0.39.Final.38bdf86, netty-codec=netty-codec-4.0.39.Final.38bdf86, netty-codec-haproxy=netty-codec-haproxy-4.0.39.Final.38bdf86, netty-codec-http=netty-codec-http-4.0.39.Final.38bdf86, netty-codec-socks=netty-codec-socks-4.0.39.Final.38bdf86, netty-common=netty-common-4.0.39.Final.38bdf86, netty-handler=netty-handler-4.0.39.Final.38bdf86, netty-tcnative=netty-tcnative-1.1.33.Fork19.fe4816e, netty-transport=netty-transport-4.0.39.Final.38bdf86, netty-transport-native-epoll=netty-transport-native-epoll-4.0.39.Final.38bdf86, netty-transport-rxtx=netty-transport-rxtx-4.0.39.Final.38bdf86, netty-transport-sctp=netty-transport-sctp-4.0.39.Final.38bdf86, netty-transport-udt=netty-transport-udt-4.0.39.Final.38bdf86]
INFO  [main] 2017-03-09 06:25:43,033 Server.java:156 - Starting listening for CQL clients on localhost/127.0.0.1:9042 (unencrypted)...
INFO  [main] 2017-03-09 06:25:43,074 CassandraDaemon.java:528 - Not starting RPC server as requested. Use JMX (StorageService->startRPCServer()) or nodetool (enablethrift) to start it

**Comment by Tieske** [comment]
cqlsh is a cassandra utility to query the database, so you'd have to install it.

**Comment by thibaultcha** [comment]
Considering this resolved.
