### ISSUE TITLE
Unable to delete target 

### ISSUE THREAD

**Issue by KRajadurai** [Mashape/kong#2181]
### Summary

404 Not Found message comes when i try to delete target from upstream

request
GET http://10.20.0.225:8001/upstreams/MailerService/targets

response
{
  "data": [
    {
      "target": "10.18.208.151:9898",
      "id": "21444ca0-5964-4dd5-b51c-d0919e314649",
      "weight": 100,
      "created_at": 1489053103691,
      "upstream_id": "0afe1b67-9079-4959-9d2a-92992679993b"
    },
    {
      "target": "10.20.0.225:9898",
      "id": "fcae9ff9-146b-435e-bdbb-42cb12f335f4",
      "weight": 100,
      "created_at": 1489048141685,
      "upstream_id": "0afe1b67-9079-4959-9d2a-92992679993b"
    }
  ],
  "total": 2
}

request
DELETE http://10.20.0.225:8001/upstreams/MailerService/targets/fcae9ff9-146b-435e-bdbb-42cb12f335f4

response
{
  "message": "Not found"
}

### Additional Details & Logs

- Kong version 0.10.0
- Operating System ubuntu 14

**Comment by Tieske** [comment]
You cannot delete it, just set the weight to 0. See https://getkong.org/docs/0.10.x/admin-api/#target-object

**Comment by KRajadurai** [comment]
I can't able to update the existing target weight.

Request
PATCH http://10.20.0.225:8001/upstreams/MailerService/targets/fcae9ff9-146b-435e-bdbb-42cb12f335f4

weight=50

Response
{
"message": "Not found"
}

**Comment by Tieske** [comment]
This seems a clear case of rtfm to me. It keeps a history of changes, so you're adding an entry to the history, hence you should make a POST request.

**Comment by zmx312502865** [comment]
@Tieske   When i delete one target , it  will add new record with weight=0..Can you help me?
