### ISSUE TITLE
Cannot start KONG

### ISSUE THREAD

**Issue by ushaheu** [Mashape/kong#2187]
I am trying to install Kong on my Mac Sierra 10.12.3. I downloaded the .pkg file and after installation, I went to the terminal to type kong start but got the following error:

Error: error loading module 'crypto' from file '/usr/local/lib/lua/5.1/crypto.so':
	dlopen(/usr/local/lib/lua/5.1/crypto.so, 6): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/lib/lua/5.1/crypto.so
  Reason: image not found

  Run with --v (verbose) or --vv (debug) for more details

Please I need assistance on running KONG

- Kong version (`0.10.0`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by Tieske** [comment]
have you tried googling for "kong crypto.so"?

**Comment by p0pr0ck5** [comment]
@ushaheu ping, have you had time to research your missing dependency issue?

**Comment by ushaheu** [comment]
@p0pr0ck5 Not at all. I rather installed using homebrew.

**Comment by p0pr0ck5** [comment]
Okay, shall we close this issue then?
