### ISSUE TITLE
Migration failure: relation "consumers_custom_id_key" already exists

### ISSUE THREAD

**Issue by corradio** [Mashape/kong#2193]
### Summary

I had kong 0.10RC3 installed, and I just upgraded to 0.10. I use postgres as database, and get the following error:

ERROR:  relation "consumers_custom_id_key" already exists

### Additional Details & Logs

debug-level startup logs:

kong_1           | 2017/03/10 10:19:41 [verbose] Kong: 0.10.0
kong_1           | 2017/03/10 10:19:41 [debug] ngx_lua: 10007
kong_1           | 2017/03/10 10:19:41 [debug] nginx: 1011002
kong_1           | 2017/03/10 10:19:41 [debug] Lua: LuaJIT 2.1.0-beta2
kong_1           | 2017/03/10 10:19:41 [verbose] no config file found at /etc/kong/kong.conf
kong_1           | 2017/03/10 10:19:41 [verbose] no config file found at /etc/kong.conf
kong_1           | 2017/03/10 10:19:41 [verbose] no config file, skipping loading
kong_1           | 2017/03/10 10:19:41 [debug] KONG_PG_HOST ENV found with "kong-database"
kong_1           | 2017/03/10 10:19:41 [debug] KONG_NGINX_DAEMON ENV found with "off"
kong_1           | 2017/03/10 10:19:41 [debug] KONG_DATABASE ENV found with "postgres"
kong_1           | 2017/03/10 10:19:41 [debug] admin_listen = "0.0.0.0:8001"
kong_1           | 2017/03/10 10:19:41 [debug] admin_listen_ssl = "0.0.0.0:8444"
kong_1           | 2017/03/10 10:19:41 [debug] admin_ssl = true
kong_1           | 2017/03/10 10:19:41 [debug] anonymous_reports = true
kong_1           | 2017/03/10 10:19:41 [debug] cassandra_consistency = "ONE"
kong_1           | 2017/03/10 10:19:41 [debug] cassandra_contact_points = {"127.0.0.1"}
kong_1           | 2017/03/10 10:19:41 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
kong_1           | 2017/03/10 10:19:41 [debug] cassandra_keyspace = "kong"
kong_1           | 2017/03/10 10:19:41 [debug] cassandra_lb_policy = "RoundRobin"
kong_1           | 2017/03/10 10:19:41 [debug] cassandra_port = 9042
kong_1           | 2017/03/10 10:19:41 [debug] cassandra_repl_factor = 1
kong_1           | 2017/03/10 10:19:41 [debug] cassandra_repl_strategy = "SimpleStrategy"
kong_1           | 2017/03/10 10:19:41 [debug] cassandra_ssl = false
kong_1           | 2017/03/10 10:19:41 [debug] cassandra_ssl_verify = false
kong_1           | 2017/03/10 10:19:41 [debug] cassandra_timeout = 5000
kong_1           | 2017/03/10 10:19:41 [debug] cassandra_username = "kong"
kong_1           | 2017/03/10 10:19:41 [debug] cluster_listen = "0.0.0.0:7946"
kong_1           | 2017/03/10 10:19:41 [debug] cluster_listen_rpc = "127.0.0.1:7373"
kong_1           | 2017/03/10 10:19:41 [debug] cluster_profile = "wan"
kong_1           | 2017/03/10 10:19:41 [debug] cluster_ttl_on_failure = 3600
kong_1           | 2017/03/10 10:19:41 [debug] custom_plugins = {}
kong_1           | 2017/03/10 10:19:41 [debug] database = "postgres"
kong_1           | 2017/03/10 10:19:41 [debug] dns_hostsfile = "/etc/hosts"
kong_1           | 2017/03/10 10:19:41 [debug] dns_resolver = {}
kong_1           | 2017/03/10 10:19:41 [debug] log_level = "notice"
kong_1           | 2017/03/10 10:19:41 [debug] lua_code_cache = "on"
kong_1           | 2017/03/10 10:19:41 [debug] lua_package_cpath = ""
kong_1           | 2017/03/10 10:19:41 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
kong_1           | 2017/03/10 10:19:41 [debug] lua_socket_pool_size = 30
kong_1           | 2017/03/10 10:19:41 [debug] lua_ssl_verify_depth = 1
kong_1           | 2017/03/10 10:19:41 [debug] mem_cache_size = "128m"
kong_1           | 2017/03/10 10:19:41 [debug] nginx_daemon = "off"
kong_1           | 2017/03/10 10:19:41 [debug] nginx_optimizations = true
kong_1           | 2017/03/10 10:19:41 [debug] nginx_worker_processes = "auto"
kong_1           | 2017/03/10 10:19:41 [debug] pg_database = "kong"
kong_1           | 2017/03/10 10:19:41 [debug] pg_host = "kong-database"
kong_1           | 2017/03/10 10:19:41 [debug] pg_port = 5432
kong_1           | 2017/03/10 10:19:41 [debug] pg_ssl = false
kong_1           | 2017/03/10 10:19:41 [debug] pg_ssl_verify = false
kong_1           | 2017/03/10 10:19:41 [debug] pg_user = "kong"
kong_1           | 2017/03/10 10:19:41 [debug] prefix = "/usr/local/kong/"
kong_1           | 2017/03/10 10:19:41 [debug] proxy_listen = "0.0.0.0:8000"
kong_1           | 2017/03/10 10:19:41 [debug] proxy_listen_ssl = "0.0.0.0:8443"
kong_1           | 2017/03/10 10:19:41 [debug] serf_path = "serf"
kong_1           | 2017/03/10 10:19:41 [debug] ssl = true
kong_1           | 2017/03/10 10:19:41 [debug] upstream_keepalive = 60
kong_1           | 2017/03/10 10:19:41 [verbose] prefix in use: /usr/local/kong
kong_1           | 2017/03/10 10:19:41 [verbose] preparing nginx prefix directory at /usr/local/kong
kong_1           | 2017/03/10 10:19:41 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
kong_1           | 2017/03/10 10:19:41 [debug] searching for OpenResty 'resty' executable
kong_1           | 2017/03/10 10:19:41 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.2'
kong_1           | 2017/03/10 10:19:41 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
kong_1           | 2017/03/10 10:19:41 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
kong_1           | 2017/03/10 10:19:41 [verbose] SSL enabled, no custom certificate set: using default certificate
kong_1           | 2017/03/10 10:19:41 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
kong_1           | 2017/03/10 10:19:41 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
kong_1           | 2017/03/10 10:19:41 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
kong_1           | 2017/03/10 10:19:41 [verbose] running datastore migrations
kong_1           | 2017/03/10 10:19:41 [info] migrating core for database kong
kong_1           | 2017/03/10 10:19:41 [verbose] could not start Kong, stopping services
kong_1           | 2017/03/10 10:19:41 [verbose] leaving serf cluster
kong_1           | 2017/03/10 10:19:41 [verbose] left serf cluster
kong_1           | 2017/03/10 10:19:41 [verbose] stopping serf agent at /usr/local/kong/pids/serf.pid
kong_1           | 2017/03/10 10:19:41 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
kong_1           | 2017/03/10 10:19:41 [debug] no pid file at: /usr/local/kong/pids/serf.pid
kong_1           | 2017/03/10 10:19:41 [verbose] serf agent stopped
kong_1           | 2017/03/10 10:19:41 [verbose] stopped services
kong_1           | Error:
kong_1           | /usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] Error during migration 2016-01-25-103600_unique_custom_id: ERROR: relation "consumers_custom_id_key" already exists
kong_1           | stack traceback:
kong_1           | 	[C]: in function 'error'
kong_1           | 	/usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
kong_1           | 	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
kong_1           | 	[C]: in function 'xpcall'
kong_1           | 	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
kong_1           | 	/usr/local/bin/kong:5: in function 'file_gen'
kong_1           | 	init_worker_by_lua:38: in function <init_worker_by_lua:36>
kong_1           | 	[C]: in function 'pcall'
kong_1           | 	init_worker_by_lua:45: in function <init_worker_by_lua:43>

**Comment by p0pr0ck5** [comment]
Looks like a dup of https://github.com/Mashape/kong/issues/2088
