### ISSUE TITLE
running Kong on Flynn.

### ISSUE THREAD

**Issue by hadifarnoud** [Mashape/kong#2195]
I'm trying to figure out if Kong can be installed on [Flynn](https://github.com/flynn/flynn). Can you please advice?

**Comment by Tieske** [comment]
Well I don't know Flynn, but it runs all things linux from what I read, so probably it should be able to.

Essentially Kong is a Nginx installation, so if that works, Kong probably works.

**Comment by hadifarnoud** [comment]
Flynn is open source alternative for Heroku which runs on docker essentially. maybe @lmars can help explain a bit more.

would be great if you add support for Flynn too

**Comment by Tieske** [comment]
see #2196 

if you tell us what you run into, we might be able to help...
