### ISSUE TITLE
Kong installation steps for Openshift

### ISSUE THREAD

**Issue by infinitebyte** [Mashape/kong#2196]
### Summary

Looking for kong installation on Openshift. This is an enhancement/feature request.
I could only find steps for Kubernetes https://github.com/Mashape/kong-dist-kubernetes
Those steps are not tailored for Openshift hence not running properly.

### Steps To Reproduce

1. This is an enhancement request or new feature request.

### Additional Details & Logs

- Kong version (`$ kong version`) 0.10.0
- Operating System RHEL 7.3
- Installation steps required for Openshift.

**Comment by Tieske** [comment]
we cannot possibly support all platforms, hence Openshift is one that is not covered. As we do not know openshift, we'd be unable to provide you with those steps.

Now if you tell us what you're specifically running in to, we might be able to help, as we do know Kong...

**Comment by infinitebyte** [comment]
Hi,

When running postgres.yaml in Openshift for creating postgres container, it failed to start with this error: 
"initdb: could not look up effective user ID 1000310000: user does not exist"

postgres.yaml is taken from https://github.com/Mashape/kong-dist-kubernetes/blob/master/postgres.yaml


Details:
Openshift:  v3.3.1.7
kubernetes v1.3.0+52492b4

**Comment by Tieske** [comment]
well, that's not a Kong question, but a postgres one...

Postgres seems to be supported https://developers.openshift.com/databases/postgresql.html but keep in mind that Kong requires 9.4+

**Comment by shashiranjan84** [comment]
@infinitebyte as @Tieske we currently do not support Openshift. It is something we can look into in future but not sure when.

**Comment by xqianwang** [comment]
I need this feature also. I think a lot of people need this feature currently in the cloud world.

**Comment by sanderkooger** [comment]
We would love to deploy Kong in openshift as well.

**Comment by steven-terrana** [comment]
That's an openshift specific issue.  Openshift runs containers with arbitrary UID's so as to not run as root... you need to configure the postgres image to allow this. 

read here: https://docs.openshift.com/enterprise/3.0/creating_images/guidelines.html

there's a section on enabling arbitrary UIDs.

**Comment by sanderkooger** [comment]
Is there a specific reason that the container runs root? from a security standpoint that is unwise i think. but correct me if i am wrong please.

**Comment by code2design** [comment]
@sanderkooger @xqianwang It works on openshift origin now. I deployed Kong on Openshift today. However, you'll have to modify the base image to run using non-root user. Also, have to update database contact point in an environment variable.

**Comment by EfraimLA** [comment]
@code2design how did you? 
Why there's no support for Openshift now? It's a very growing and trusted technology. Would be very useful have native support and official installations for Kong

**Comment by jbadeau** [comment]
Installing k8s software via helm into openshift works pretty well. One normally needs to:

- fork the docker image(s) and remove root usage
- fork the chart(s) and change ingress to routes
