### ISSUE TITLE
How to disable access.log?

### ISSUE THREAD

**Issue by deefha** [Mashape/kong#2210]
Is it possible to disable Nginx acces.log in Kong 0.10.0?

There is no such option in default kong.conf, although in auto-generated .kong_env file is `nginx_acc_logs` parameter set to `/usr/local/kong/logs/access.log`. From where comes this value? Adding `nginx_acc_logs = off` or `nginx_acc_logs = /dev/null` into kong.conf and restarting Kong has no effect.

**Comment by mbugeia** [comment]
AFAIK you need to use a custom nginx template to do this.

**Comment by deefha** [comment]
IMHO a little bit overkill just for disabling an access log. Parameter would come in handy... Nevertheless I tested custom Nginx template and it worked obviously well. Thank you.

**Comment by mbugeia** [comment]
I agree, I use a custom nginx template just to handle nginx logs the way I want too.

**Comment by p0pr0ck5** [comment]
Correct, currently the way to handle this is through a custom template. As we discuss changes to distributing and configuring Kong moving forward (see #2355), this may change, but for now this is the appropriate way.

**Comment by RobSerafini** [comment]
Update:  with commit https://github.com/Kong/kong/commit/23585aad6db6bc4dfc7436965369ed2199e3d44a and Kong version 1.3.0 (OpenResty version 1.15.8.1) access logs may be disabled with `KONG_PROXY_ACCESS_LOG=off`
