### ISSUE TITLE
Upstream HTTP Basic Auth Plugin

### ISSUE THREAD

**Issue by pauldaustin** [Mashape/kong#2216]
### Summary

I'm looking at writing an upstream-auth-basic plugin that would take a username and password as parameters. It would then add a Authorization:Basic... header to the upstream request.

At the moment I simulate this using the request-transformer plugin with the Authorization header added.

If I write this plugin will you consider adding it to the core?

In the future we could add additional plugins for upstream-auth-digest, upstream-auth-api-key etc.

I think having individual plugins for each is better as then they don't need to do a lot of if this then else checks to decide how to change the upstream request.

**Comment by Tieske** [comment]
> If I write this plugin will you consider adding it to the core?

Don't know. We're seeing quite some plugins being proposed and the general issue for us is, that if we add them, we also get the support burden...

Hence we're looking into the possibility of a repository where anyone could share plugins like this. (There already are some on LuaRocks). That said, if there is value for you, there is probably value for others, so if we don't merge it, just post it on Luarocks...

> I think having individual plugins for each is better as then they don't need to do a lot of if this then else checks to decide how to change the upstream request.

Untested comment: if you create multiple functions that each provide a single auth method, then on the first call, you can do all the if-then things, and then store the selected function in the `conf` table, as that is cached in Lua memory.
On each subsequent call, you grab and execute that function from the `conf` table.

**Comment by pauldaustin** [comment]
Thanks for the luarocks suggestion I'll  create the plugin on github and upload to luarocks.

Paul Austin
Revolution Systems Inc.

**Comment by pauldaustin** [comment]
I've deployed the plugin to luarocks. I'm now closing this issue.

[https://revolsys.github.io/kong-plugin-upstream-auth-basic/](https://revolsys.github.io/kong-plugin-upstream-auth-basic/)
[https://github.com/revolsys/kong-plugin-upstream-auth-basic](https://github.com/revolsys/kong-plugin-upstream-auth-basic)
[http://luarocks.org/modules/revolsys/kong-plugin-upstream-auth-basic](http://luarocks.org/modules/revolsys/kong-plugin-upstream-auth-basic)

**Comment by Tieske** [comment]
:+1:

**Comment by dzung1nguyen** [comment]
:+1:
