### ISSUE TITLE
How much data can be stored in customer custom_id?

### ISSUE THREAD

**Issue by acorbel** [Mashape/kong#2220]
Hi,

First, thank you for Kong, it is awesome!
For my project, I have a user DB and multiple services behind Kong. Instead of using a separate DB and have to sync them, I'm wondering if it is possible to store some metadata along with the Kong customer.

A Kong customer has the following attributes: id, custom_id and username. 
I use the username for auth and id is autogenerated. But, how much data can I store in custom_id? (JSON format).

Thank you!

**Comment by Tieske** [comment]
check out the [migration files](https://github.com/Mashape/kong/tree/77e58d1fd1f52a4cc3a7af742a6de64a54aba61e/kong/dao/migrations), that's where the tables are created. 

and the [schema file](https://github.com/Mashape/kong/blob/77e58d1fd1f52a4cc3a7af742a6de64a54aba61e/kong/dao/schemas/consumers.lua) that validates the entry.

Use at your own risk....

 - no backward compatibility guarantees
 - consumers are cached in memory, adding to much data might exhaust it quicker
 - data will not be searchable

That said; curious what you come up with :smile:

**Comment by acorbel** [comment]
Thanks! It seems that there is no low limit for Cassandra and Postgres.
The schema is not restrictive.

Links:
Cassandra: https://wiki.apache.org/cassandra/CassandraLimitations
Postgres (text type): https://www.postgresql.org/docs/current/static/datatype-character.html

I've forgotten the memory issue :/

Thank you! I think I'll stay with my 3 DBs for now.
