### ISSUE TITLE
[feature] List in use group names and grants for each 

### ISSUE THREAD

**Issue by pauldaustin** [Mashape/kong#2223]
### Summary

It would be useful to see what group names are used in acls and for each group to see which consumers have been granted an acl for that group. For example /groups and /groups/:groupName

### Steps To Reproduce

Here is some sample code that achieves what I'm looking for.

NOTE: /groups is not efficient. It would be better to be able to use a distinct within the cassandra or postgresql select statement. However the dao find_all or crud.paginated_set doesn't support custom select fields such as DISTINCT fieldName. The underlying DB classes do as it's used for COUNT(*) but it's not exposed.

Let me know if you'd consider a pull request for this.

```lua
local cjson = require "cjson"
local crud = require "kong.api.crud_helpers"
local responses = require "kong.tools.responses"

return {
  ["/groups"] = {
    GET = function(self, dao_factory)
      local dao = dao_factory.acls;
      local rows, err = dao_factory.acls:find_all()
      if err then
        return helpers.yield_error(err)
      else
      local distinct_groups = {}
        
        local group_map = {}
        for _, row in ipairs(rows) do
          if not group_map[row.group] then
            group_map[row.group] = { group = row.group }
            distinct_groups[#distinct_groups+1] = { group = row.group }
          end
        end
        
        return responses.send_HTTP_OK {
          data = #distinct_groups > 0 and distinct_groups or cjson.empty_array,
          total = #distinct_groups,
        }
        
      end
      
    end,
  },

  ["/groups/:group"] = {
    GET = function(self, dao_factory)
      crud.paginated_set(self, dao_factory.acls)
    end,
  },

}
```

**Comment by p0pr0ck5** [comment]
@pauldaustin will you consider submitting a PR (with tests) for this? Thanks!

I'll go ahead and close this, as we can have more discussion in the PR :)

**Comment by pauldaustin** [comment]
Robert,

I'll work on a PR for this. It might be a few weeks as I'm working on some other projects right now.

**Comment by p0pr0ck5** [comment]
Much appreciated! In the meantime I'll bring it up in conversation :) thanks again for all your contributions! We love the community participation.
