### ISSUE TITLE
Faild to configure ACL plugin

### ISSUE THREAD

**Issue by benbenqiang** [Mashape/kong#2224]
### Summary

add ACL plugin ss described in the document

curl -X POST http://localhost:8001/apis/flowPadJob/plugins--data "name=acl"--data "config.whitelist=White_flowPadJob" 

but i got this:

<html>
<head><title>415 Unsupported Media Type</title></head>
<body bgcolor="white">
<center><h1>415 Unsupported Media Type</h1></center>
<hr><center>openresty/1.11.2.2</center>
</body>
</html>
curl: (52) Empty reply from server
curl: (52) Empty reply from server

### Additional Details & Logs

- Kong version (`0.10`)
- Centos7

**Comment by Tieske** [comment]
This is a known issue, see #1182
