### ISSUE TITLE
API versions

### ISSUE THREAD

**Issue by markgaywood** [Mashape/kong#2226]
### Summar
Support multiple versions of APIs

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by Tieske** [comment]
@markgaywood can you please take some time to elaborate on what your asking? Kong already supports many versions, so you have to be more specific. So please give a proper use case description, or user story.

**Comment by markgaywood** [comment]
Hi,

So perhaps I've been I'll informed. The requirement from me is that i can
support multiple version of the same API. If you can do this already can
you point me to the relevant plugin or documentation.

Thanks Mark

**Comment by tumluliu** [comment]
I don't think Kong works at this level. Actually, you can configure your multiple versions of api at different uris like `/v1/yourservice`, `/v2/yourservice`, etc. as many as you want. As far as I know, it's not Kong's responsibility to help you manage such versioning stuff. If this version management feature is really what you want, you need some other software/service running on top of Kong. For example, [Gelato](https://gelato.io/).

**Comment by markgaywood** [comment]
Ok thank you

You can cancel my ticket if required

**Comment by Tieske** [comment]
In any case I think it doubles with https://github.com/Mashape/kong/issues/402
