### ISSUE TITLE
Where to store additional configuration information?

### ISSUE THREAD

**Issue by rgottumu** [Mashape/kong#2229]
where should I store additional details related to API's like developer contact etc? Can I use same database that Kong is configured to use or use a different database? What are the pros and cons with each approach?

Thank you.

**Comment by coopr** [comment]
Are you asking about something like https://gelato.io ?

Or are you asking about storing metadata about the consumers of your APIs? 

Or something else?

**Comment by Tieske** [comment]
I think you could use the same database, biggest issue I can think of is migrating to newer versions or migrating to a new cluster or something like that.

Another database is cleaner, but requires more management

**Comment by p0pr0ck5** [comment]
In the future, we'll likely provide a mechanism to tie metadata into consumer (and other) objects in the admin API; for now, as @Tieske mentioned you could manually use either the existing, or a separate, data store to manage this metadata.

Feel free also to continue this discussion on the mailing list, or Gitter. Thank you!

**Comment by rgottumu** [comment]
Thank you @p0pr0ck5 . Is this on the road map or is this something that you want to do at some point of time?
