### ISSUE TITLE
Brew install on OS X 10.12.3 having issues with serf version

### ISSUE THREAD

**Issue by john-paul-keenan** [Mashape/kong#2233]
### Summary

Installing Kong 0.10 on OS X 10.12.3 using Homebrew: 
`brew tap mashape/kong`
`brew install kong`
And then starting Kong with `kong start' I keep getting this error:

`Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:22: incompatible serf found. Kong requires version 0.7.0 to 0.8.0, got 0.8.1
Run with --v (verbose) or --vv (debug) for more details`

I thought maybe I could just remove serf all together and let kong install the version it wanted, so I tried 
  			`brew uninstall --force serf`
  And then re-installing Kong but got the same output

 I was able to get it working using the .pkg installer. After it worked properly, when I check the serf version, I see 8.0

### Steps To Reproduce

1. Be on a computer with OS X 10.12.3
2. `brew tap mashape/kong`
3. `brew install kong`
4. `kong start`

### Additional Details & Logs

- Kong version (`$ kong version`)
0.10.0

**Comment by thibaultcha** [comment]
(Belongs to Mashape/homebrew-kong)

**Comment by p0pr0ck5** [comment]
(also, dup of https://github.com/Mashape/kong/issues/2070?)
