### ISSUE TITLE
Confirmation of no_consumer plugin flags

### ISSUE THREAD

**Issue by pauldaustin** [Mashape/kong#2235]
### Summary

I think there might be some additional plugins that wouldn't be for consumers (e.g. ldap-auth, logging plugins). Can you add no_consumer=true to those that aren't meant to be included for consumers.

It might also be nice to expose the no_consumer flag in the /plugins/schema/{pluginName} response.

The following table shows those plugins that have no_consumer=true.

|Plugin Name|No Consumer|
|-|-|
|acl|true|
|aws-lambda||
|basic-auth|true|
|bot-detection|true|
|correlation-id||
|cors|true|
|datadog||
|file-log||
|galileo||
|hmac-auth|true|
|http-log||
|ip-restriction||
|jwt|true|
|key-auth|true|
|ldap-auth||
|log-serializers||
|loggly||
|oauth2|true|
|rate-limiting||
|request-size-limiting||
|request-transformer||
|response-ratelimiting||
|response-transformer||
|runscope||
|statsd||
|syslog||
|tcp-log||
|udp-log||

**Comment by Tieske** [comment]
thx for checking that.

Though I don't see why the logging plugins should be 'no-consumer' ?

**Comment by pauldaustin** [comment]
You're right I can see cases for per consumer logging
