### ISSUE TITLE
Proxy protocol support

### ISSUE THREAD

**Issue by shamil** [Mashape/kong#2240]
Hi, this is not a bug, but a feature request.
Instead of manually providing `nginx.conf` file. Is it possible to add native proxy protocol support in Kong?

**Comment by bungle** [comment]
@shamil, do you mean to provide a configuration variable for that?

**Comment by shamil** [comment]
@bungle, yes. A configuration option

**Comment by bungle** [comment]
@shamil, the small problem I see here is that `proxy protocol` is exclusive (correct me if I'm wrong), and if you still want to support non-`proxy-protocol` that practically means two different server blocks (?). What do you think?

**Comment by shamil** [comment]
@bungle yes, it's exclusive.

Having another port just for `proxy_protocol` is good idea, but IMHO it's nice to have, not must. But at least `kong` should have a possibility to let users enable `proxy_protocol` for all APIs

In my opinion in most cases when you want `proxy_protocol`, in those cases `kong` proxy usually sits behind load-balancer like ELB or Haproxy,  so you will want it for all APIs.

**Comment by shamil** [comment]
@bungle what you think? Is it reasonable?

Also `real_ip_header` should be set to `proxy_protocol`, so the real IP can be retrieved properly, which I think is already beeing addresed here: https://github.com/Mashape/kong/pull/2236

**Comment by bungle** [comment]
@shamil I think it is reasonable and it is easy to implement. Yes, I was thinking the same that if `real_ip_header` is set to `proxy_protocol` we could just generate the associated listen directives, and that's it.

**Comment by bungle** [comment]
@shamil, if you have time to test #2236 for Proxy protocol functionality and give us feedback, that would be greatly appreciated!

**Comment by shamil** [comment]
@bungle thanks, as soon as I got from vacation (Thursday) I will run tests and report

**Comment by shamil** [comment]
@bungle tested, works as expected. Setting `real_ip_header` to `proxy_protocol` will update the `listen` directive accordingly.

Thanks a lot...

**Comment by thibaultcha** [comment]
#2236 is merged, closing this now, thanks @bungle! :)
