### ISSUE TITLE
JWT auth plugin - any way to exclude login path

### ISSUE THREAD

**Issue by markgandy** [Mashape/kong#2244]
When JWT auth is enabled on an API it would be nice if you could specify the login path, so that auth is not required .

My scenario is an API with endpoints like:
```
my.api.com/projects/{projectId}/login
my.api.com/projects/{projectId}/protected
```

This API should be protected by JWT auth, but I can't find an easy way to exclude the login path from auth (because of the path parameter)
I'm happy to submit a PR if someone can point me in right direction.

**Comment by coopr** [comment]
I'm guessing you are essentially asking for https://github.com/Mashape/kong/issues/677 so that your /login endpoint can be left without authentication, while your /protected endpoint is protected by the JWT auth plugin - is that right?

**Comment by markgandy** [comment]
@coopr yeah pretty much. But I thought it would be a pretty cool feature of the JWT plugin itself

**Comment by coopr** [comment]
What would your unprotected /login endpoint do in this scenario? Some explanation would be great, thanks!

**Comment by coopr** [comment]
Oh, and I don't suppose your two endpoints have different HTTP methods, do they?

**Comment by markgandy** [comment]
/login is a POST that takes some user credentials (which map to a consumer in Kong). If the credentials are valid, then a JWT is created (using jwtSecret of the kong consumer) and sent back in the response.

Subsequent calls to the protected endpoint will include the JWT as Authorization header.

There are actually lots of unprotected endpoints (with different HTTP methods)

**Comment by Tieske** [comment]
If you create an api that specifies both `method` and the `uris` for the login, then that will have a higher precedence than an api that only matches on `uris`. So the second one could then get the jwt auth plugin attached to it, and the first not.

But the path parameter problem cannot be solved right now. If you could drop the path parameter from the `login` endpoint, then it could work. But then obviously the users would be shared on all 'projects', not sure whether that is acceptable.

**Comment by markgandy** [comment]
@Tieske Thanks for suggestion, but we actually have multiple protected endpoints (with different HTTP methods) so matching on `method` and `uri` won't work.

We are thinking about moving the `projectId` from the path to the payload to work around this, but not really ideal

**Comment by Tieske** [comment]
as a request this doubles with https://github.com/Mashape/kong/issues/677

closing this.
