### ISSUE TITLE
Kong service not resolving the hostname

### ISSUE THREAD

**Issue by MikeRileyGTRI** [Mashape/kong#2250]
### Summary
I am having an issue resolving the hostname for my kong API machine. Access to the service through the direct IP works, but using the hostname resolves to:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

I believe that the issue is with the dnsmasq service kong uses, but I have turned off dnsmasq and I still have this issue.

A run of kong health verifies that dnsmasq is no longer being used.

```
serf........running
nginx.......running
```

my kong-version is 0.9.8

**Comment by MikeRileyGTRI** [comment]
I was able to fix the issue by moving kong to version 0.10.0. That of course does not fix the issue, but it's worth noting here.

**Comment by p0pr0ck5** [comment]
Thanks for the report @MikeRileyGTRI. If it's working as expected with 0.10, I think we're good :)

**Comment by MikeRileyGTRI** [comment]
Hi kong development/support. I guess this is a good time to ask about version support.

I suppose the best idea is to just keep up with the kong version right now. Especially because the platform is so new. But what is the policy for legacy version support going forward? Some of the tools I like to use, like kong-dashboard, don’t support 0.10 yet, so I am losing some functionality along the way of upgrading.

Michael K Riley
Research Scientist 1
Georgia Tech Research Institute

Michael.Riley@gtri.gatech.edu<mailto:Michael.Riley@gtri.gatech.edu>
Phone (404) 285-3054
