### ISSUE TITLE
i can't add api

### ISSUE THREAD

**Issue by koyuhau** [Mashape/kong#2251]
### Summary

I can't add apis for kong ;
when i do like that:
- $ curl -i -X POST \
-   --url http://localhost:8001/apis/ \
-   --data 'name=example-api' \
-   --data 'hosts=example.com' \
-   --data 'upstream_url=http://httpbin.org'

it return:
- curl: (52) Empty reply from server

### Additional Details & Logs

- Kong version  0.10.0
- Kong debug-level startup logs (`$ kong start --vv`)
2017/03/24 09:53:58 [verbose] Kong: 0.10.0
2017/03/24 09:53:58 [debug] ngx_lua: 10007
2017/03/24 09:53:58 [debug] nginx: 1011002
2017/03/24 09:53:58 [debug] Lua: LuaJIT 2.1.0-beta2
2017/03/24 09:53:58 [verbose] reading config file at /etc/kong/kong.conf
2017/03/24 09:53:58 [debug] admin_listen = "0.0.0.0:8001"
2017/03/24 09:53:58 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/03/24 09:53:58 [debug] admin_ssl = true
2017/03/24 09:53:58 [debug] anonymous_reports = true
2017/03/24 09:53:58 [debug] cassandra_consistency = "ONE"
2017/03/24 09:53:58 [debug] cassandra_contact_points = {"127.0.0.1"}
2017/03/24 09:53:58 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/03/24 09:53:58 [debug] cassandra_keyspace = "kong"
2017/03/24 09:53:58 [debug] cassandra_lb_policy = "RoundRobin"
2017/03/24 09:53:58 [debug] cassandra_port = 9042
2017/03/24 09:53:58 [debug] cassandra_repl_factor = 1
2017/03/24 09:53:58 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/03/24 09:53:58 [debug] cassandra_ssl = false
2017/03/24 09:53:58 [debug] cassandra_ssl_verify = false
2017/03/24 09:53:58 [debug] cassandra_timeout = 5000
2017/03/24 09:53:58 [debug] cassandra_username = "kong"
2017/03/24 09:53:58 [debug] cluster_listen = "0.0.0.0:7946"
2017/03/24 09:53:58 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/03/24 09:53:58 [debug] cluster_profile = "wan"
2017/03/24 09:53:58 [debug] cluster_ttl_on_failure = 3600
2017/03/24 09:53:58 [debug] custom_plugins = {}
2017/03/24 09:53:58 [debug] database = "postgres"
2017/03/24 09:53:58 [debug] dns_hostsfile = "/etc/hosts"
2017/03/24 09:53:58 [debug] dns_resolver = {}
2017/03/24 09:53:58 [debug] log_level = "notice"
2017/03/24 09:53:58 [debug] lua_code_cache = "on"
2017/03/24 09:53:58 [debug] lua_package_cpath = ""
2017/03/24 09:53:58 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/03/24 09:53:58 [debug] lua_socket_pool_size = 30
2017/03/24 09:53:58 [debug] lua_ssl_verify_depth = 1
2017/03/24 09:53:58 [debug] mem_cache_size = "128m"
2017/03/24 09:53:58 [debug] nginx_daemon = "on"
2017/03/24 09:53:58 [debug] nginx_optimizations = true
2017/03/24 09:53:58 [debug] nginx_worker_processes = "auto"
2017/03/24 09:53:58 [debug] pg_database = "kong"
2017/03/24 09:53:58 [debug] pg_host = "127.0.0.1"
2017/03/24 09:53:58 [debug] pg_password = "******"
2017/03/24 09:53:58 [debug] pg_port = 5432
2017/03/24 09:53:58 [debug] pg_ssl = false
2017/03/24 09:53:58 [debug] pg_ssl_verify = false
2017/03/24 09:53:58 [debug] pg_user = "kong"
2017/03/24 09:53:58 [debug] prefix = "/usr/local/kong/"
2017/03/24 09:53:58 [debug] proxy_listen = "0.0.0.0:8000"
2017/03/24 09:53:58 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2017/03/24 09:53:58 [debug] serf_path = "serf"
2017/03/24 09:53:58 [debug] ssl = true
2017/03/24 09:53:58 [debug] upstream_keepalive = 60
2017/03/24 09:53:58 [verbose] prefix in use: /usr/local/kong
2017/03/24 09:53:58 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/03/24 09:53:58 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2017/03/24 09:53:58 [debug] searching for OpenResty 'resty' executable
2017/03/24 09:53:58 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.2'
2017/03/24 09:53:58 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2017/03/24 09:53:58 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2017/03/24 09:53:58 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/03/24 09:53:58 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2017/03/24 09:53:58 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2017/03/24 09:53:58 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2017/03/24 09:53:58 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
2017/03/24 09:54:02 [verbose] running datastore migrations
2017/03/24 09:54:02 [verbose] migrations up to date
2017/03/24 09:54:02 [verbose] serf agent not running, deleting /usr/local/kong/pids/serf.pid
2017/03/24 09:54:02 [debug] searching for 'serf' executable
2017/03/24 09:54:02 [debug] serf version: 'Serf v0.8.0'
2017/03/24 09:54:02 [debug] found 'serf' executable at serf
2017/03/24 09:54:02 [debug] starting serf agent: nohup serf agent -profile 'wan' -bind '0.0.0.0:7946' -log-level 'err' -rpc-addr '127.0.0.1:7373' -event-handler 'member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf/serf_event.sh' -node 'precise64_0.0.0.0:7946_f0140ec5a1164e108f7aa174530e0019' > /usr/local/kong/logs/serf.log 2>&1 & echo $! > /usr/local/kong/pids/serf.pid
2017/03/24 09:54:02 [verbose] waiting for serf agent to be running
2017/03/24 09:54:02 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/03/24 09:54:02 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/03/24 09:54:02 [verbose] serf agent started
2017/03/24 09:54:02 [verbose] auto-joining serf cluster
2017/03/24 09:54:02 [verbose] no other nodes found in the cluster
2017/03/24 09:54:02 [verbose] registering serf node in datastore
2017/03/24 09:54:02 [verbose] cluster joined and node registered in datastore
2017/03/24 09:54:02 [debug] searching for OpenResty 'nginx' executable
2017/03/24 09:54:02 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.11.2.2'
2017/03/24 09:54:02 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2017/03/24 09:54:02 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2017/03/24 09:54:04 [debug] nginx started
2017/03/24 09:54:04 [info] Kong started

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System
ubuntu12

**Comment by Tieske** [comment]
works for me;

```shell
192:kong thijs$ curl -i -X POST \
> --url http://localhost:8001/apis/ \
> --data 'name=example-api' \
> --data 'hosts=example.com' \
> --data 'upstream_url=http://httpbin.org'
HTTP/1.1 201 Created
Date: Fri, 24 Mar 2017 09:57:32 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Server: kong/0.10.0

{"http_if_terminated":true,"id":"b9ad1303-da55-42ff-a446-d9d69d7a37e5","retries":5,"preserve_host":false,"created_at":1490349452000,"upstream_connect_timeout":60000,"upstream_url":"http:\/\/httpbin.org","upstream_read_timeout":60000,"https_only":false,"upstream_send_timeout":60000,"strip_uri":true,"name":"example-api","hosts":["example.com"]}
192:kong thijs$
```

how did you install Kong?

**Comment by koyuhau** [comment]
@Tieske  
$ kong health
serf........running
nginx.......running

Is this normal?

**Comment by Tieske** [comment]
yep that's normal

You could try to explicitly set the `admin_listen` address to 127.0.0.1:8001

**Comment by koyuhau** [comment]
@Tieske thank you for your help
i install the ubuntu and the kong again,the issuse is not exist.
