### ISSUE TITLE
out-of-sync password for Postgress

### ISSUE THREAD

**Issue by Tieske** [Mashape/kong#2254]
defaults are out of sync for postgres database password

see these lines:

 - https://github.com/Mashape/kong/blob/172f26764a660c602cde805660b332498f2a9246/kong/templates/kong_defaults.lua#L28
 - https://github.com/Mashape/kong/blob/172f26764a660c602cde805660b332498f2a9246/kong.conf.default#L136

which is causing confusion.

see #1672

**Comment by mateusluizfb** [comment]
I've download this version and the problem is persist https://bintray.com/kong/kong-community-edition-deb/download_file?file_path=dists/kong-community-edition-0.11.2.xenial.all.deb
