### ISSUE TITLE
Lambda support for us-west-2 

### ISSUE THREAD

**Issue by mynameisgv** [Mashape/kong#2257]
Hello

Lambda plugin is not supported in us-west-2. Is  there any specific reason for this limitation.
Will this region be supported in near future.

Thanks
### Steps To Reproduce

1. Create a pi and attach a lambda plugin. In the configuration when i mention us-west-2 i get a error that region is not supported.

### Additional Details & Logs

- Kong version (`0.10.0`)
- Operating System : Centos

**Comment by Tieske** [comment]
fixed by #2257
