### ISSUE TITLE
How to create and add custom plug-ins ?

### ISSUE THREAD

**Issue by koyuhau** [Mashape/kong#2261]
### Summary

How to create and add custom plug-ins ?

### Steps To Reproduce

1. I refer to this article(http://streamdata.io/blog/developing-an-helloworld-kong-plugin/) and use the plugin code provided by him.

2.I create a folder in kong/plugins/helloworld,and added plugin code.

3.I configured the file /etc/kong/kong.conf :
     custom_plugins = helloworld 
4.when i reload the kong and send:
$ curl -i -X POST --url http://localhost:8001/apis/example-api/plugins/ --data 'name=helloworld'
   , it return:
HTTP/1.1 400 Bad Request
Date: Mon, 27 Mar 2017 01:57:20 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Server: kong/0.10.0

{"config":"Plugin \"helloworld\" not found"}

I would like to ask, where is wrong, or tell me how to add plug-ins please.

### Additional Details & Logs

- Kong version (`$ kong version`)
0.10.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System
ubuntu14

**Comment by Tieske** [comment]
see https://github.com/Mashape/kong-vagrant
see https://github.com/Mashape/kong-plugin
see https://github.com/Mashape/getkong.org/pull/349
