### ISSUE TITLE
Error Run Kong from Ubuntu 16.04

### ISSUE THREAD

**Issue by dzung1nguyen** [Mashape/kong#2262]
Hi Guys,

Can you share for me the required package to run Kong.

I tried to install from: https://getkong.org/install/ubuntu/

Error:
```
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:20: could not find OpenResty 'resty' executable. Kong requires version 1.11.2.1 to 1.11.2.2

stack traceback:

        [C]: in function 'error'

        /usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'

        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function 

</usr/local/share/lua/5.1/kong/cmd/init.lua:88>

        [C]: in function 'xpcall'

        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function 

</usr/local/share/lua/5.1/kong/cmd/init.lua:45>

        /usr/local/bin/kong:5: in function 'file_gen'

        init_worker_by_lua:38: in function <init_worker_by_lua:36>

        [C]: in function 'pcall'

        init_worker_by_lua:45: in function <init_worker_by_lua:43>
```

I need to install Nginx, postgresql, ... before. Right? or only Kong package?

Thank you.

**Comment by Tieske** [comment]
the Kong package should be enough. Update your system path to include the location of the `resty` executable.

Usually it is located somewhere like `/usr/local/openresty/bin`

**Comment by thefosk** [comment]
The system should already check in that location by default: https://github.com/Mashape/kong/blob/master/kong/cmd/utils/prefix_handler.lua#L48

**Comment by thefosk** [comment]
@dzung1nguyen can you run `kong start --vv` and paste the output here?

**Comment by dzung1nguyen** [comment]
That 's issue has fix. 

Thank you so much.
