### ISSUE TITLE
Too much db connections

### ISSUE THREAD

**Issue by depay** [Mashape/kong#2273]
I'm using Kong-0.10.0 with postgresql. Then i found that each nginx worker create a connection to postgresql, while the `max_connections` of postgresql is not finite. Too many connections also cost a lot. What is worse, Kong can only use the master db node for both R/W, while the read-only standby db node is idle.

Is there any better solution, besides putting a db connect pool (such as pg-pool) before the real db ?

**Comment by thibaultcha** [comment]
Not as of today. This is a current limitation of ngx_lua/OpenResty. There are plans on our side to overcome those "manually", but while on our radar, they are not on our current roadmap.

**Comment by depay** [comment]
@thibaultcha thanks for your reply. PG-POOL and HA of postgresql are not that easy for normal user. that's really a pity. I will try to do something on it.

**Comment by thibaultcha** [comment]
Considering this question answered for now. Closing this in the meantime.

**Comment by zhangxing406** [comment]
is this question resolved? I have met the same question.
