### ISSUE TITLE
Create api with a dynamic id

### ISSUE THREAD

**Issue by dzung1nguyen** [Mashape/kong#2276]
Hi guys,

Can you help me create API with dynamic id?

GET: 
example.com/products/12
=> my.api.com/products/12

example.com/products/14
=> my.api.com/products/14

I am using Kong 0.10.0

Thank you.

**Comment by coopr** [comment]
Closing as duplicate of #677

**Comment by Tieske** [comment]
as a side not: in this case (parameter is the last part) you could set up an api with just a hostname or the path up to the parameter. That would work.
