### ISSUE TITLE
JWT authentication get  access token.

### ISSUE THREAD

**Issue by dzung1nguyen** [Mashape/kong#2278]
Hello everyone,

On Kong document: https://getkong.org/plugins/jwt/#create-a-jwt-credential

After that step, how to i can get  access token?

it's like: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhMzZjMzA0OWIzNjI0OWEzYzlmODg5MWNiMTI3MjQzYyIsImV4cCI6MTQ0MjQzMDA1NCwibmJmIjoxNDQyNDI2NDU0LCJpYXQiOjE0NDI0MjY0NTR9.AhumfY35GFLuEEjrOXiaADo7Ae6gt_8VLwX7qffhQN4

My issue:

- User request Kong server get a access_token
- Kong server result a access_token
- User use that access_token to verify authentication on hosts (ex: kong:8000/products), after verified successfully, Kong server will points upstream_url (ex: my.api.com/products)

Please help to clear that.

Thank you so much

**Comment by b-rajesh** [comment]
KONG doesn't give you access token if you enable an API with JWT credential. It is expected your code produce JWT and sign it. Public key will have to be sent to kong to verify the sign when consumer presents the JWT token. In this flow, KONg doesn't produce any token. 

If it is openid connect implementation, then we can expect KONG to give access token.

**Comment by p0pr0ck5** [comment]
Thanks @b-rajesh for the response. Closing based on this response, as the current JWT plugin is different from an OpenID connect implementation.
