### ISSUE TITLE
API not immediately created despite the 201 Created received to the POST /apis request

### ISSUE THREAD

**Issue by pamiel** [Mashape/kong#2279]
### Summary

If an API is created and is immediately called (for example within a script that runs the 2 curl requests in a row), then it is most likely that the `{"message":"no API found with those values"}` error will be raised when calling the API (i.e. the second call), despite the fact that the POST to the `/apis` admin endpoint (i.e. the 1st call) has returned a `HTTP/1.1 201 Created`

If you wait a little bit between the API creation and the API call, then it will work !

### Steps To Reproduce

1. Create a script with the 2 following curl:
```
curl -i -X POST --url 'http://kong:8001/apis' --data 'name=testAPI' --data 'uris=/test' --data 'upstream_url=http://rest-service.guides.spring.io/greeting' --data 'strip_uri=true'
curl -i -X GET --url http://kong:8000/test
```
2. Call the script
3. You will get a response like the following:
```
HTTP/1.1 201 Created
Date: Tue, 28 Mar 2017 15:35:06 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Server: kong/0.10.0

{"http_if_terminated":true,"strip_uri":true,"retries":5,"preserve_host":false,"created_at":1490715306623,"upstream_connect_timeout":60000,"upstream_url":"http:\/\/rest-service.guides.spring.io\/greeting","uris":["\/test"],"https_only":false,"upstream_send_timeout":60000,"upstream_read_timeout":60000,"name":"testAPI","id":"23ba5dbf-3c66-4623-8919-a82489967cdd"}

HTTP/1.1 404 Not Found
Date: Tue, 28 Mar 2017 15:35:06 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Server: kong/0.10.0

{"message":"no API found with those values"}

```

If you insert a small sleep in between the 2 calls in the script, then the API call will work normally (starting from a `sleep 0.8` sec on my environment !)

### Additional Details & Logs

- Kong version : 0.10.0
- Kong configuration (registered APIs/Plugins & configuration file): Default ones only
- Operating System: Alpine

**Comment by thibaultcha** [comment]
This is an expected behavior. Nothing much we can do in a distributed environment, although when calling the same node again it could be improved, but not with the current design.

**Comment by pamiel** [comment]
Ok, understood.
Here, test is made with a single instance => both calls are on the same node.

As I did not face the issue with the previous release (0.8 and 0.9), I thought it might be an issue introduced on the 0.10.

**Comment by thibaultcha** [comment]
There is indeed a change in 0.10 making this "eventually consistent", although the promise is the same as it was in 0.8 and 0.9, and probable more so in the future with the removal of serf. We'll do our best to keep those to a minimum.

**Comment by thefosk** [comment]
> As I did not face the issue with the previous release (0.8 and 0.9), I thought it might be an issue introduced on the 0.10.

@pamiel maybe it's unrelated, but in Kong 0.10.0 we upgraded Serf to 0.8.1 (Kong 0.9.x was using Serf 0.7), but in the latest Kong 0.10.1 we downgraded back to Serf 0.7 because it was causing some other problems. So you could give it a try with Kong 0.10.1 with the same Serf version as we used to have before.

**Comment by thibaultcha** [comment]
That would be unrelated, this is a single node so there is no invalidation events in play. It has to do with a 0.10 change that we cannot fully overcome yet.

**Comment by thefosk** [comment]
@thibaultcha sure, but if @pamiel was happy with 0.9.x, then it may just be that Serf 0.8.x adds some latency that Serf 0.7 didn't add, therefore upgrading to 0.10.1 could bring that latency back to an acceptable value. 

The current design, as you explained, didn't change between 0.9.x and 0.10.x, but since Serf changed, the latency might have too. Worth a try IMHO.

**Comment by pamiel** [comment]
Just tested: same behavior with Kong 0.10.1 (so with Self 0.7)
(`{"message":"no API found with those values"}` error is raised)

**Comment by thibaultcha** [comment]
Like I said, this isn't about the serf version but about an internal design change. 0.10.1 will indeed have the same behavior

**Comment by pamiel** [comment]
Yes it has !
Thanks for your help.

**Comment by ChaimaeELL** [comment]
what was the soluton of this problem? thanks
