### ISSUE TITLE
OAuth 2 plugin documentation mistake: resource owner flow

### ISSUE THREAD

**Issue by schikin** [Mashape/kong#2280]
### Summary

Try to request the access token from Kong using the POST request `$ curl https://your.api.com/oauth2/token` per the documentation here https://getkong.org/plugins/oauth2-authentication/#resource-owner-password-credentials

You get the error message saying "wrong grant_type". When calling POST one have to explicitly specify additional data field "grant_type=password" for it to work.

Also, not sure why does the Kong API require to pass username and password. I wonder what it could use it for?

### Steps To Reproduce

1. Call API POST https://your.api.com/oauth2/token as per the documentation
2. Receive error message about grant type

### Additional Details & Logs

- Kong version 0.9.7
- MacOS Sierra, Docker distro of Kong from Dockerhub official

**Comment by thibaultcha** [comment]
Hi, thanks for the report.

The website is open sourced at Mashape/getkong.org, where such issues belong to. Thanks!

**Comment by thibaultcha** [comment]
Please re-open on the website repository as Mashape/getkong.org, thanks!
