### ISSUE TITLE
Update the documentation.

### ISSUE THREAD

**Issue by sgcourage** [Mashape/kong#2282]
### Summary

SUMMARY_GOES_HERE
It seams that the cors plugin documentation is incorrect, i believe that the limitations aren't there for the current version of kong.
Another thing is the config.origins is in previous versions actually config.origin, so please highlight that since is may create a-lot of confusion.

**Comment by coopr** [comment]
@sgcourage we'd welcome a PR on https://github.com/Mashape/getkong.org/pulls thanks!

**Comment by thibaultcha** [comment]
Sadly, plugins documentations are not versioned on getkong.org

**Comment by thibaultcha** [comment]
(Closing this in the meantime as it belongs to getkong.org)

**Comment by sgcourage** [comment]
This is a documentation change, so i don't believe that i'm able to create a pull-request on this.

**Comment by coopr** [comment]
@sgcourage indeed you are able to create PRs on https://github.com/Mashape/getkong.org/pulls - at least you should be able to - let us know if you have some issue doing so (ideally by opening an issue in that repo https://github.com/Mashape/getkong.org/issues - thanks!
