### ISSUE TITLE
400 Bad Request when get information 

### ISSUE THREAD

**Issue by dzung1nguyen** [Mashape/kong#2289]
Hi guys

I added a api 

http://api.zingzing.com:8001/apis

data:
name: get_products
hosts: api.zingzing.com
uris: /json/v1/dz/products
upstream_url: https://beta.zingzing.com/wp-json/wc/v1/products

=> Info
{
  "methods": [
    "GET"
  ],
  "http_if_terminated": true,
  "id": "b68e6892-6337-4211-92a5-6150b73c6071",
  "retries": 5,
  "preserve_host": false,
  "created_at": 1490754001000,
  "upstream_connect_timeout": 60000,
  "upstream_url": "https://beta.zingzing.com/wp-json/wc/v1/products",
  "upstream_read_timeout": 60000,
  "upstream_send_timeout": 60000,
  "https_only": true,
  "strip_uri": true,
  "uris": [
    "/json/v1/dz/products"
  ],
  "name": "get_products",
  "hosts": [
    "api.zingzing.com"
  ]
}

But when i get:
https://api.zingzing.com/json/v1/dz/products

Error 400 appear

`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
    <head>
        <title>400 Bad Request</title>
    </head>
    <body>
        <h1>Bad Request</h1>
        <p>Your browser sent a request that this server could not understand.
            <br />
        </p>
        <hr>
        <address>Apache/2.4.12 (Ubuntu) Server at beta.zingzing.com Port 443</address>
    </body>
</html>`

I added SSL for 2 servers.

Please help me have a look at. 

Thank you.

**Comment by p0pr0ck5** [comment]
The server token in the error above indicates that Apache handled the request, not Kong. What's in the Kong error log?

**Comment by dzung1nguyen** [comment]
I just fixed it from:
https://github.com/Mashape/kong/issues/2129

Thank you.
