### ISSUE TITLE
Can't add api (mac os)

### ISSUE THREAD

**Issue by orliesaurus** [Mashape/kong#229]
Okay so this is what I did.

Installed Kong through the homebrew method.
* Added an api and returned:
`{"public_dns":"google.com","id":"32152cfb-2d82-473c-c768-c17ec65b5594","created_at":1431420742000,"name":"loc","target_url":"localhost:9999"}`

* made sure I got an API running on `localhost:9999`

* tried to run a cURL
`curl -i -X GET --url localhost:8000 --header 'Host: google.com'`

and I get:
```
HTTP/1.1 500 Internal Server Error
Date: Tue, 12 May 2015 18:14:38 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
Server: kong/0.2.0-2
```

**Comment by thibaultCha** [comment]
Why is the target URL missing a protocol? Like mentioned in the docs, it should start with http(s). Related to #149.

Can you try?

**Comment by orliesaurus** [comment]
Given: 
```
{"public_dns":"google.com","target_url":"http:\/\/localhost:9999","id":"163b2187-ff2f-49f5-c969-1145420d5cd5","created_at":1431507384000,"name":"lol"}
``` 

Tried and got this:

```
HTTP/1.1 502 Bad Gateway
Server: openresty/1.7.10.2rc0
Date: Wed, 13 May 2015 08:58:32 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 182
Connection: keep-alive
Via: kong/0.2.0-2

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty/1.7.10.2rc0</center>
</body>
</html>
```

**Comment by thefosk** [comment]
Can you please trigger the error again and parse the logs at `/usr/local/kong/logs/error.log` ?

**Comment by orliesaurus** [comment]
When trying to install with brew the new version:

`Error: Failed installing dependency: https://luarocks.org/multipart-0.1-3.rockspec - Permission denied
make: *** [install] Error 1`

**Comment by thibaultCha** [comment]
It's your computer, if you have to use `sudo`, it's not our issue.

**Comment by orliesaurus** [comment]
It's not my computer - it's because of having installed the earlier PKG file has messed up the whole configuration with luarocks.
I give up on Kong OS X and move onto docker.

**Comment by thefosk** [comment]
Can you use the new [Kong package](https://github.com/Mashape/kong/releases/download/0.2.1/kong-0.2.1.pkg) and let me know if it works?
