### ISSUE TITLE
Error with key auth: attempt to  concatenate local 'id' (a nil value)

### ISSUE THREAD

**Issue by PauloGDPeixoto** [Mashape/kong#2293]
### Summary

In one cluster Kong, while behaving correctly, does not give the appropriate response when key auth is activated and no key is supplied.

### Steps To Reproduce

1. Start Kong, activate key auth;
2. Access the api url, without passing the api key;
3. Instead of displaying the default "No API key found in headers or querystring" message, an error is displayed. From a curl request the output is "An unexpected error occurred". From a web browser it is 
> **Kong Error**
> 
> An unexpected error occurred.

### Additional Details & Logs

- Kong version 0.10.1
- Operating System: Debian
- Error log pertaining to this request:
```
2017/03/29 17:10:09 [error] 12523#0: *12227 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/tools/database_cache.lua:223: attempt to concatenate local 'id' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/tools/database_cache.lua: in function 'consumer_key'
	/usr/local/share/lua/5.1/kong/plugins/key-auth/handler.lua:135: in function 'access'
	/usr/local/share/lua/5.1/kong.lua:256: in function 'access'
	access_by_lua(nginx-kong.conf:80):2: in function <access_by_lua(nginx-kong.conf:80):1>, client: 127.0.0.1, server: kong, request: "GET /app HTTP/1.1", host: "localhost:8000"
```

**Comment by p0pr0ck5** [comment]
Looks like this would be fixed by https://github.com/Mashape/kong/pull/2266?

**Comment by PauloGDPeixoto** [comment]
Indeed it fixed the issue! Thanks!
