### ISSUE TITLE
Document how to delete JWT token

### ISSUE THREAD

**Issue by therealgambo** [Mashape/kong#2295]
### Summary

Add documentation on how to delete a JWT token for a consumer

```
curl -X DELETE http://kong/consumers/{consumer}/jwt/{token id}
```

**Comment by coopr** [comment]
@therealgambo your PR to improve the docs https://getkong.org/plugins/jwt/ would be welcome - you'll find the source file for that page here https://github.com/Mashape/getkong.org/blob/master/app/plugins/jwt.md

**Comment by therealgambo** [comment]
PR: https://github.com/Mashape/getkong.org/pull/367
