### ISSUE TITLE
Add Authorization for up_stream

### ISSUE THREAD

**Issue by dzung1nguyen** [Mashape/kong#2299]
Hi guys,

We can set a default Authorization Basic on up_stream?

My issue:

Client call api_url -> KONG -> upstream_url

Step 1- Client call api_url -> KONG: i use JWT plugin to check

Step 2- KONG -> upstream_url:  add a Authorization Basic and define key:secret (username:password)

Because i am using woocommerce REST Api,  to connect apis, i need Authorization basic with consumer_key and consumer_secret

I am using Kong 0.10.0

Thank so much.

**Comment by dzung1nguyen** [comment]
https://github.com/Mashape/kong/issues/590

**Comment by thefosk** [comment]
You can use the Request Transform plugin to add a header on the fly to the request.

**Comment by thibaultcha** [comment]
I believe someone recently published a community plugin on luarocks for that. You should check it out (on mobile now).

**Comment by thibaultcha** [comment]
https://revolsys.github.io/kong-plugin-upstream-auth-basic/

**Comment by dzung1nguyen** [comment]
The plugin Request Transform help me that.

Thank you
