### ISSUE TITLE
[BUG] Proxy to API with "URIs only" performs exact match

### ISSUE THREAD

**Issue by jeanpralo** [Mashape/kong#2308]
### Summary

If you create a new API in Kong which only references a list of uris as the routing capability, it seems to perform an exact match on the URI.

For example if we create an api for `/v0/myproject` this will get routed to the upstream server, but a request with `/v0/myproject/toto` won't.

### Steps To Reproduce

1. Add a kong admin endpoint: `curl -X POST http://$(docker-machine ip microservice):8001/apis -d 'name=kong-admin' -d 'hosts=kong-admin.service.consul' -d 'uris=/' -d 'upstream_url=http://127.0.0.1:8001'`
2. Create an API on Kong: `curl -X POST http://kong:8001/apis -d 'name=myproject' -d 'uris=/v0/myproject' -d 'upstream_url=http://myproject.service.consul'`
3. Query the newly created api on the exact URI: `curl http://kong/v0/myproject` -> 200 Ok
4. Query the newly created api with extract path in the URI: `curl http://kong/v0/myproject/toto` -> 404 -> {"message":"no API found with those values"}

Mitigation:

If you want to solve the problem you can add a a host and/or a method the query will go through:

1. curl -X PATCH http://10.66.100.101:8001/apis/myproject -d 'hosts=toto.com'
2. Query the api one more time with extract path in the URI: `curl -H 'Host: toto.com' http://kong/v0/myproject/toto` -> 200 ok

### Additional Details & Logs

- Kong version 0.10.1

**Comment by jeanpralo** [comment]
After doing a bit of it seems that this behavior comes from that block of code https://github.com/Mashape/kong/blob/master/kong/core/router.lua#L518


Since it matches on the / from the first api it just break and stops looking. Problem is that the header won't match so we end up with  no api found. Might be worth to keep going on something like `if req_category & MATCH_RULES.HOST` ?

**Comment by thibaultcha** [comment]
Hi! This should have been fixed with #2343, please give it a try and re-open if the issue still occurs, thanks!
