### ISSUE TITLE
 server configuration for advice

### ISSUE THREAD

**Issue by manyixu** [Mashape/kong#2312]
### Summary

SUMMARY_GOES_HERE
My company now install the kong api gateway. Select the postgres for database and install openresty for web platform.There is  two server for  database with  a master and  a slave. There is 3 server for a cluster which will install kong api gateway application.
  now can you give a detail  of the servers for advice.
  
### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by Tieske** [comment]
seems like a typical enterprise question to me, see https://www.mashape.com/enterprise/

**Comment by manyixu** [comment]
what i want to ask is the type of cpu and the memory of the database server。
and more,can you give a good advice of the tool of lua devloping
