### ISSUE TITLE
110: Connection timed out

### ISSUE THREAD

**Issue by hongkang** [Mashape/kong#2316]
Hello.
I got it from error.log. 

upstream timed out (110: Connection timed out) while reading response header from upstream, client: xx.xx.xx.xx, server: kong, request: "GET /console/dashboard/real-time/connections-pool HTTP/1.1", upstream: "http://10.0.0.8:8944/console/dashboard/real-time/connections-pool", host: "xxx.xxx.xxx"

It happens randomly.

Please tell me what does it mean?

**Comment by Tieske** [comment]
what does your api configuration look like?

**Comment by hongkang** [comment]
<img width="1171" alt="2017-04-01 7 39 15" src="https://cloud.githubusercontent.com/assets/3444613/24578446/0d318b28-1713-11e7-8693-5a62fd36f954.png">
<img width="1124" alt="2017-04-01 7 41 18" src="https://cloud.githubusercontent.com/assets/3444613/24578456/3bc484b8-1713-11e7-8367-da3dd6d8bbd2.png">

These are from a dashboard written by myself.

**Comment by hongkang** [comment]
when I send a request to kong 0.10.0, sometimes, viewing  access.log, kong did not resend this request immediately until one minute later. this problem sometimes occurs and trouble me .
After this happen ,next call will be normal .
Does it because of the https connection?

**Comment by Tieske** [comment]
Might be a dns issue. 

See https://github.com/Mashape/kong/issues/2290
In that case there were 5 dns servers configured, and the last 2 were included but shouldn't have been. One of those returned errors.

Please ensure you have only valid working nameservers listed in your `resolv.conf`

**Comment by Tieske** [comment]
@hongkang have you been able to resolve this?

**Comment by harryparmar** [comment]
@hongkang @Tieske Try changing default 60k ms upstream_*_timeouts to bigger value on your endpoint.

**Comment by p0pr0ck5** [comment]
Closing as a stale issue. Feel free to reopen if there are unanswered questions regarding this.
