### ISSUE TITLE
Client credentials

### ISSUE THREAD

**Issue by midudhula1234** [Mashape/kong#2323]
In OAuth 2 client credentials flow as client secret is almost equivalent to a password should it be encrypted? 
Does kong provide any such encryptions?

**Comment by Tieske** [comment]
use ssl?

**Comment by midudhula1234** [comment]
Oops sorry I phrased the question incorrectly....I was planning to use ssl but I was thinking more interms of storing comparing client secret(passed by the client App) with hashed one(hashed using any of the algorithms SHA3 etc) in the datastore.....so that the client secrets are safe in the datastore

**Comment by coopr** [comment]
I believe this is represented by #1237

**Comment by ginnavaram** [comment]
are there any plans by Mashape/Kong community in implementing #1237
