### ISSUE TITLE
Complex Routing

### ISSUE THREAD

**Issue by Vad1mo** [Mashape/kong#2324]
### Summary

I wonder if I could do some more complex routing. My scenario works nginx but not with API Gateways known to me. 

I have two services behind one Url (_app.company.com_). Lets call one service "_Website_" and the other "_API Service_"

The "_API Service_" should receiver traffic for

app.company.com/v2/*

The "_Website_" should receive traffic for

app.company.com/*
app.company.com/v2/token
app.company.com/v2/webhook

So the tricky part here is that `/v2/token` and `/v2/webhook` should go to "Website" instead to service. 

In nginx I have to create 4 locations to make this work, it does not work with only 2 locations and regex magic.
 
### Additional Details & Logs

- I would like to use the latest Kong version 

If found the PR #1970 which explains the router but does not answer my question.

**Comment by Tieske** [comment]
yes, you can do that. Longer uris are matched before shorted ones.

The down side is that the website will consist of 3 apis in Kong terminology. You might also consider exposing a different path on the outside, and internally forward to the proper ones. eg. `app.company.com/api/v2` to internal upstream `internal_host/v2/`. That would be doable with 2 apis

**Comment by coopr** [comment]
@Vad1mo in your desired configuration, will Kong be proxying requests for your website content (eg. images, HTML, CSS, JS, etc)?

**Comment by Vad1mo** [comment]
Thank you for the clarification. 

> @Vad1mo in your desired configuration, will Kong be proxying requests for your website content (eg. images, HTML, CSS, JS, etc)?

Yes. The situation is the following, there is a Admin Dashboard. In my simplified example I call it "_Website_". In reality that the Web application serves HTML,JS Content and also a REST API.  
`/v2/token` `/v2/webhook` are the provided API services of the web application. The "_Api Service_" is consumed by the end user. The "_Api Service_" is using the token service.


> You might also consider exposing a different path on the outside, and internally forward to the proper ones. eg. 

Unfortunately It isn't possible to expose a different path to the outside as @Tieske suggested. All clients out there expect a v1 or v2 path and there are many clients. What I could do is to change the web application and its api path.

**Comment by thibaultcha** [comment]
> I know that Kong, wasn't designed for this, but I guess it isn't a problem even if the gateway is also proxying to a website. Or Are there any other solutions without to many applications involved.

Nginx on the other hand, is definitely built to handle such use-cases. I would suggest using a custom Nginx configuration with a location block for serving your website, and one for serving Kong. Your website location block can definitely use settings that are more appropriate for such reverse-proxying of assets files, thus giving you the best of both worlds: a Kong instance able to both proxy your APIs and your website in an efficient manner.

**Comment by Vad1mo** [comment]
Before closing the the issue. One final question for clarificatigon
@thibaultcha 
>  I would suggest using a custom Nginx configuration with a location block for serving your website

Am I right that you personally would recommend to create a cascading proxy hierarchy, where a second nginx instance is located in front of kong and is serving the static website and otherwise forwarding to kong. Doesn't it make the whole setup overly complex as you need to take care of load balancing on two instances and.

Or do you mean (if that it is possible/recommended?) to provide kong with an additional custom nginx.conf with location and tuning for the static website/content?

I am asking the reassurance question to better understand the best/common practice approaches when working with kong.

**Comment by thibaultcha** [comment]
> Or do you mean (if that it is possible/recommended?) to provide kong with an additional custom nginx.conf with location and tuning for the static website/content?

This is what I mean. The goal is indeed *not* to have to maintain a second Nginx instance, and use at your advantage the fact that Kong is built on top of Nginx and is a drop-in replacement (or will be).

**Comment by Vad1mo** [comment]
🥇 **Drop-in replacement for nginx** 

Thank you very much for clarification.

**Comment by salazar** [comment]
Related documentation added [here](https://getkong.org/docs/0.10.x/configuration/#serving-both-a-website-and-your-apis-from-kong).
