### ISSUE TITLE
File log

### ISSUE THREAD

**Issue by ginnavaram** [Mashape/kong#2325]
I started using the file log plugin in kong. Is there a way to rotate the logs based on threshold (once it reaches 5mb or so) or rotate the log file daily?

**Comment by p0pr0ck5** [comment]
A simple logrotate config could handle this for you (http://www.linuxcommand.org/man_pages/logrotate8.html).

**Comment by cosmopetrich** [comment]
What's the correct method to signal to Kong that it should reopen the log file post-rotation?

Kong will continue to write to the same file until nginx is restarted or reloaded. A SIGUSR1 will cause nginx to reopen its own logs, but Kong will continue to write to the old one. The file-log plugin [appears to only determine the file descriptor the first time it writes a log message](https://github.com/Mashape/kong/blob/master/kong/plugins/file-log/handler.lua#L45-L62).

**Comment by p0pr0ck5** [comment]
@cosmopetrich currently there is support for Kong to close and re-open the FD. We are discussing the appropriate approaches here: in the meantime, you could use the `copytruncate` logrotate directive to avoid the stale descriptor problem.

**Comment by deepshrift** [comment]
@p0pr0ck5 HI. if we use copytruncate,there is a very small time slice between copying the file and truncating it, so some logging data might be lost. How to solve this problem?

**Comment by Tieske** [comment]
@deepshrift by not using the file log plugin

> It is not recommended to use this plugin in production, it would be better to use another logging plugin, for example syslog, in those cases. Due to system limitations this plugin uses blocking file i/o, which will hurt performance, and hence is an anti-pattern for Kong installations.

see https://getkong.org/plugins/file-log/

**Comment by satishmane** [comment]
@Tieske 
Hi,
Issue with syslog plug-in is that syslog truncates messages. I tried using rsyslog, it improved message length, but still same problem of truncation. I found that this is due to message string length hard coded in alpine linux image libc. I tried increasing MaxMessageSize in rsyslog.conf, but no luck. Kong says this is syslog issue. And we can not fix alpine docker image issue. In short, logging in kong is an issue one way or another. I would have gone with file-log kong plug-in even in production if it supported log rotate. 
Do you have any workaround/solution for syslog like logging or resolve syslog issue

**Comment by Tieske** [comment]
@satishmane I wasn't aware of that limitation, have you tried the CentOS image?

**Comment by satishmane** [comment]
@Tieske 
Yes tried centos image too. But same issue.

**Comment by Tieske** [comment]
seems to me this is a syslog issue. There is nothing Kong can do to work around those limitations. You could try any of the other logging solutions, tcp/http based?

PS. What Kong version are you using?

**Comment by satishmane** [comment]
@Tieske 
Kong version : 1.0.3
Other logging solutions introduce another moving part. Hence needed local logging option like syslog.

**Comment by Tieske** [comment]
taking this to https://discuss.konghq.com/t/syslog-pluging-does-not-log-anything/3029
