### ISSUE TITLE
Question on lambda integration

### ISSUE THREAD

**Issue by shavo007** [Mashape/kong#2329]
### Summary

Hi,

Just recently read the plugin doc for lambda. 

I am using serverless as an example here (but it could be any fwk to create and deploy lambda functions).

If I have a CRUD Api and I create four lambda functions like in the example below, how will that work with lambda integration?

Based on the doc, it seems you can only have one lambda function per api. 

> --data "config.function_name=LAMBDA_FUNCTION_NAME"

And I believe that in AWS you usually have one handler per function.

The example I use is from serverless:

```
endpoints:
  POST - https://45wf34z5yf.execute-api.us-east-1.amazonaws.com/dev/todos
  GET - https://45wf34z5yf.execute-api.us-east-1.amazonaws.com/dev/todos
  GET - https://45wf34z5yf.execute-api.us-east-1.amazonaws.com/dev/todos/{id}
  PUT - https://45wf34z5yf.execute-api.us-east-1.amazonaws.com/dev/todos/{id}
  DELETE - https://45wf34z5yf.execute-api.us-east-1.amazonaws.com/dev/todos/{id}
functions:
  serverless-rest-api-with-dynamodb-dev-update: arn:aws:lambda:us-east-1:488110005556:function:serverless-rest-api-with-dynamodb-dev-update
  serverless-rest-api-with-dynamodb-dev-get: arn:aws:lambda:us-east-1:488110005556:function:serverless-rest-api-with-dynamodb-dev-get
  serverless-rest-api-with-dynamodb-dev-list: arn:aws:lambda:us-east-1:488110005556:function:serverless-rest-api-with-dynamodb-dev-list
  serverless-rest-api-with-dynamodb-dev-create: arn:aws:lambda:us-east-1:488110005556:function:serverless-rest-api-with-dynamodb-dev-create
  serverless-rest-api-with-dynamodb-dev-delete: arn:aws:lambda:us-east-1:488110005556:function:serverless-rest-api-with-dynamodb-dev-delete
```

### Additional Details & Logs

- Kong version 0.10.0
- Operating System OSX

Thanks,
Shane.

**Comment by coopr** [comment]
I believe you need to create 5 APIs in Kong (one for each of your 5 functions), apply the AWS Lambda plugin to each of them, and use a combination of `methods` and `uris` to match and route your incoming requests https://getkong.org/docs/0.10.x/proxy/#routing-capabilities

**Comment by shavo007** [comment]
Thanks for the response @coopr  I have been mulling over this for a while!!!

I dont really like the concept of regarding an api in kong world as one lambda function. (**aka one http method/same resource**).

Going this route, you would have five apis created in kong. Example:
API 1 - function:serverless-rest-api-with-dynamodb-dev-update
API 2 - function:serverless-rest-api-with-dynamodb-dev-get
API 3 - function:serverless-rest-api-with-dynamodb-dev-list
API 4 - function:serverless-rest-api-with-dynamodb-dev-create
API 5- function:serverless-rest-api-with-dynamodb-dev-delete

 ```
curl -X POST http://kong:8001/apis/1/plugins \
    --data "name=aws-lambda" \
    --data "config.aws_key=AWS_KEY" \
    --data "config.aws_secret=AWS_SECRET" \
    --data "config.aws_region=AWS_REGION" \
    --data "config.function_name=serverless-rest-api-with-dynamodb-dev-update"
```

I had a quick read of the proxy documentation.

What if somehow you can tie the http method and function name to one api . JSON Map per se

Example:
```
config.function_names:
{
  "patch" : "function:serverless-rest-api-with-dynamodb-dev-update",
  "get" : "function:serverless-rest-api-with-dynamodb-dev-get",
"post" : "function:serverless-rest-api-with-dynamodb-dev-create",
"delete": "function:serverless-rest-api-with-dynamodb-dev-delete"
}
```

WOuld that be feasible!!?

Kong would be able to decipher based on http method what function to go to... ;-)

In my example unfortunately it does not handle the list function. But that could be defined in a seperate api.

Another idea i seen with aws gateway is proxy mode. Whereby one handler (one function) handles all requests. You have conditional logic in your handler to check the event type (request method) that came in. 

Similar to what is defined in article below:
http://www.goingserverless.com/blog/routing-api-gateway-traffic-through-one-lambda-function

Let me know your thoughts.



```

**Comment by coopr** [comment]
> I don't really like the concept of regarding an API in kong world as one lambda function. (aka one HTTP method/same resource).

@shavo007 it'd be great if you could elaborate _why_ you don't like this ^^ - that'd be helpful for me to understand your thinking. I'm not at all suggesting you _should_ like this - I'm truly curious! (It is pretty much my job to be curious ; )

**Comment by p0pr0ck5** [comment]
@shavo007 we'd love to have more of your opinion here, as @coopr mentioned.

In the mean time, we're going to close this issue, as there's no actionable work here. Feel free to use the mailing list or Gitter as a vehicle to continue moving this discussion forward as necessary.

**Comment by olconstant** [comment]
Hi guys,

In my company, we are implementing Kong with the AWS Lambda Plugin.
But we written our lambda handlers to process same inputs as AWS API Gateway in Proxy mode:
```
{
  "httpMethod": "POST",
  "path": "/",
  "body": "{\"test\":\"body\"}",
  "queryStringParameters": {
    "foo": "bar"
  },
  "headers": {
    "Content-Type": "application/json"
  }
}
```

I am wondering if Kong AWS Lambda Plugin can support RequestResponse in Proxy mode as well?
It will allow to forward the query string to the lambda function, and to manage routing and middleware inside the handler.

I tried to use Kong Request Transformer Plugin, but it doesn't allow to dynamically lookup the request values.

What do you think? Any other approach to suggest?
