### ISSUE TITLE
Setting up Kong Cluster in different Docker machines

### ISSUE THREAD

**Issue by harryparmar** [Mashape/kong#2330]
### Summary

I found the official documentation for docker can be supplemented with separate section for someone setting up cluster on different machines as Ports are not exposed on host preventing cluster mode if someone follows official guide.

### Steps To Reproduce

1. Use official documentation for setting up kong in docker

### Additional Details & Logs

If someone follows steps from official guide, they will not be able to form cluster.

### Solution

docker run -d --name kong \
--net=host \
-e "KONG_DATABASE=cassandra" \
-e "KONG_CASSANDRA_CONTACT_POINTS=127.0.0.1" \
-e "KONG_PG_HOST=kong-database" \
-p 8000:8000 \
-p 8443:8443 \
-p 8001:8001 \
-p 7946:7946 \
-p 7946:7946/udp \
kong

Where KONG_CASSANDRA_CONTACT_POINTS points to wherever you decide to use DB. Link has been removed to avoid conflict with --net=host

**Comment by coopr** [comment]
@harryparmar is this the page that needs adjusting https://getkong.org/install/docker/ ? If so, we welcome PRs - you'll find the source for that page here https://github.com/Mashape/getkong.org/blob/master/app/install/docker.md

**Comment by harryparmar** [comment]
yes that is it, will do

**Comment by p0pr0ck5** [comment]
Closing as this will be fixed elsewhere. Thanks!
