### ISSUE TITLE
Default response type for error messages

### ISSUE THREAD

**Issue by therealgambo** [Mashape/kong#2332]
### Feature

We are currently developing a new json orientated API, at the moment when a request is made and no `Accept` headers are present, Kong will always return the error in the format of 'text/plain' as seen on this block of code (https://github.com/Mashape/kong/blob/master/kong/core/error_handlers.lua#L35).

What a propose is the ability in the configuration to define a fallback response type for these error messages, which will be used when the `Accept` header is not present.

### Additional Details & Logs

- Kong version: 0.10.1

**Comment by p0pr0ck5** [comment]
Hello,

Would you be willing to submit a PR for this behavior?

**Comment by therealgambo** [comment]
Sure
