### ISSUE TITLE
Router fails to resolve when longer path shadows another

### ISSUE THREAD

**Issue by cheald** [Mashape/kong#2334]
### Summary

We're seeing an issue where one API definition which includes (path, host) is conflicting with another API definition that includes (path, host). What it feels like is that Kong is selecting the first API definition as a candidate based on path, but then failing to match it based on host, resulting in a "No API matches those values" message.

### Steps To Reproduce

Here is a failing test case. I added it to 01-unit/11-router_spec.lua

      it("does supersede another API with a longer URI prefix on a different host", function()
        local use_case = {
          {
            name = "api-1",
            uris = { "/v1/path"  },
            headers = {
              ["host"] = { "host1.com" },
            }
          },
          {
            name = "api-2",
            uris = { "/" },
            headers = {
              ["host"] = { "host2.com" },
            }
          }
        }

        local router = assert(Router.new(use_case))
        local headers = { ["host"] = use_case[1].headers.host[1] }

        local api_t = router.select("OPTIONS", "/v1/path", headers)
        assert.truthy(api_t)
        assert.same(use_case[1], api_t.api)

        headers.host = use_case[2].headers.host[1]
        api_t = router.select("GET", "/v1/path-with-extra/resource.json", headers)
        assert.truthy(api_t)
        assert.same(use_case[2], api_t.api)
      end)

This fails with:

```
Failure → spec/01-unit/11-router_spec.lua @ 177
Router select() [uri] as a prefix does supersede another API with a longer URI prefix on a different host
spec/01-unit/11-router_spec.lua:204: Expected to be truthy, but value was:
(nil)
```

If you alter the spec so that the paths match:

```
        local use_case = {
          {
            name = "api-1",
            uris = { "/v1/path"  },
            headers = {
              ["host"] = { "host1.com" },
            }
          },
          {
            name = "api-2",
            uris = { "/v1/path" },
            headers = {
              ["host"] = { "host2.com" },
            }
          }
        }
```

then it passes.

Clearly, we don't want path prefixes to have to be unique across APIs. I haven't figured out what's causing the behavior yet, but hopefully this helps track down the issue.

This passes on the 0.10.0rc3 branch. Bisecting with the above unit test gives me:

```
4ebaa6efd4c9629bf8a5a91df968c40bba3e7305 is the first bad commit
commit 4ebaa6efd4c9629bf8a5a91df968c40bba3e7305
Author: Thibault Charbonnier <thibaultcha@me.com>
Date:   Fri Feb 10 15:27:32 2017 -0800

    fix(router) avoid HTTP method to supersede non-plain URI

    Assuming 2 APIs:
    * one with `methods = GET`
    * the other with `uris = /httpbin`

    And the following request:

        GET /httpbin/foo HTTP/1.1
        Host:

    The router would match API 1 and discard the URI matching. However, URI
    matching should have a higher priority than HTTP method matching. This
    happens because the prefix-URI matching happens *after* plain URI and
    plain HTTP method matching.

    This patch makes sure that the URI-prefix matching happens before the
    "last-resort" HTTP method matching.

:040000 040000 a6ddefea9675ee6f6730f96ac124a8f1309240d8 a281ad501cde932ee3c647924aa38a12ec2b2b90 M      kong
:040000 040000 c9949c59b600ea93696083b9dd471ca858510c9b 4def5c05c786137877bcbe040dac6b670aaefc79 M      spec
```

### Additional Details & Logs

- Kong version 0.10.1 (in production) / git HEAD (020de3ed6f70c9f5cf3c052345a679f4ff94f0e2)

**Comment by thibaultcha** [comment]
Thanks for the detailed report, I'll look into this.

**Comment by thibaultcha** [comment]
Alright, I have a fix on my side but I will think of more regression tests before proposing a PR. Thanks again!

**Comment by bungle** [comment]
@thibaultcha would you like to share your patch, I just hit similar bug, and I have a integration test that triggers that already.

E.g. some trailing slash tests:

```
-- upstream url    uris            request path    expected path           strip uri
{  "/",            "/foo/bar/",    "/foo/bar/",    "/",                    nil       },
{  "/foo/bar",     "/",            "/foo/bar",     "/foo/bar/foo/bar",     nil       }
```

These work fine alone, but together I do get:

```
{"message":"no API found with those values"}
```

**Comment by bungle** [comment]
@cheald, thanks for this report. I got @thibaultcha's work-in-progress patch for this issue and I did test it with my PR's (#2315) unit tests and integration tests and I can confirm that it fixes the issues with those as well.

**Comment by BetaGrumm** [comment]
I also am experiencing exactly what @cheald described.
I'm so glad someone else ran into this. 
I was going crazy trying to figure out what was wrong. 
Thanks for the quick response on this, @thibaultcha. 👍

**Comment by thibaultcha** [comment]
Patch submitted at #2343! I could not come up with any specific additional regression tests, as I had a hunch this edge-case could maybe exist for wildcard hosts matching as well, but apparently those avoid it since they behave slightly differently.

@cheald Feel free to try that patch if you wish. Thanks again for the report and, most of all *the minimal test case to reproduce the issue, as it was most helpful ;)

@bungle Could you try it again (as it was updated) and make sure that your tests still succeed with it? Thanks!

**Comment by cheald** [comment]
Thanks for the quick turnaround! I'll see if I can get the patch into testing - we ran into this while testing a transition to Kong, so we just backed off of that for the time being pending this fix. I'll let you know if I run into further issues with it.
