### ISSUE TITLE
Not able to retrieve consumers

### ISSUE THREAD

**Issue by gauravsinghania** [Mashape/kong#2338]
### Summary
When a consumer is created with a user name as a guid the consumer is successfully created. After creation when you try to retrieve the consumer using the username, it says consumer not found. 

### Steps To Reproduce

1. Create a consumer with consumer name as a guid like 'ff305d54-85b4-341b-da2f-eb6b9e5460fc'. 
**REQUEST:** curl -i -X POST  --url http://localhost:8001/consumers/  --data "username=ff305d54-85b4-341b-da2f-eb6b9e5460fc" 
2. Try to retrieve the consumer . 
**REQUEST:** curl http://localhost:8001/consumers/ff305d54-85b4-341b-da2f-eb6b9e5460fc
3. Expected Result: consumer details are returned

4. Actual Result: Got : {"message":"Not found"}

### Additional Details & Logs
While retrieving consumer there is a validation "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$" to select the data as username or id. If guid is not a valid consumer name, there should be a validation restricting the same.

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by Tieske** [comment]
this is by design, if it is a uuid, then it is considered the Kong ID, not the consumer name. An alternative might be to use `custom_id`.

**Comment by gauravsinghania** [comment]
Should we consider not allowing uuid for consumer name?
