### ISSUE TITLE
Routing API's to right upstream URL

### ISSUE THREAD

**Issue by ksachdeva11** [Mashape/kong#2339]
### Summary
Is there a way we can route right API to right upstream URL? Eg. - There are 2 different API's

1. **`/v1/users/:id/items`**  ---> Upstream URL: 10.5.6.7:2000

--> **`/v1/users/12345/items`**

2. **`/v1/users/:id/preferences`** ---> Upstream URL: 10.5.6.7:3000

--> **`/v1/users/12345/preferences`**

:id is variable here. 

Currently we have added a logic in the code to grep for ":" and route it accordingly. But if we have large number of API's it might lead to slowness as it will iterate through the whole list.

Is there a way we can handle this better?  or is there any pre-loaded plugin which does this ?

### Additional Details & Logs

- Kong version (`$ kong version`) - 0.10
- Operating System - MacOS

**Comment by Tieske** [comment]
Kong does not (yet) support variables in the uri.

**Comment by ksachdeva11** [comment]
@Tieske Hi, Do you have any plans of supporting it in near future or any work around? Thanks.

**Comment by Tieske** [comment]
It's on the radar, but not planned yet. So no eta.

**Comment by coopr** [comment]
See https://github.com/Mashape/kong/issues/677

**Comment by kumarinstor** [comment]
i added this in upstream url -- http://localhost:1111/student/:student_id
then in urIs i added /student/:student_id
when i run this http://localhost:8000/student/123 its showing no API found with those values

**Comment by Tieske** [comment]
@kumarinstor please take those type of questions to [Kong Nation](https://discuss.konghq.com/)
