### ISSUE TITLE
Kong 0.10.0

### ISSUE THREAD

**Issue by dzung1nguyen** [Mashape/kong#2340]
Hi Guys,

I am using Kong 0.10.0, and add an api 

upstream_url: https://beta.zingzing.com/orders

method: POST

But, i  call that api, upstream_url auto add "/" at end url 

=> https://beta.zingzing.com/orders/

I can not access on beta server.

Please help me a solution.

Thank you so much.

**Comment by Tieske** [comment]
see https://github.com/Mashape/kong/pull/2315
