### ISSUE TITLE
Question on hiding proxy response headers

### ISSUE THREAD

**Issue by shavo007** [Mashape/kong#2341]
### Summary

Hi,

Is it possible to hide the header 

> Via: kong/x.x.x?

 Details defined in the doc below:
https://getkong.org/docs/0.10.x/proxy/#proxy-response

### Additional Details & Logs

- Kong version 0.10.0

**Comment by bungle** [comment]
In next version it is. Should be released soon (week or two).

**Comment by shavo007** [comment]
Good to hear. Can you please label the milestone to the issue please?

**Comment by abdken** [comment]
Hi,
is that possible to hide via:kong/2.0.5 from response headers!!
