### ISSUE TITLE
DNS Failure for Kubernetes Service as upstream_url

### ISSUE THREAD

**Issue by stevesloka** [Mashape/kong#2342]
### Summary

I have Kong deployed into a Kubernetes cluster. I want to use Kong as my API gateway in front of services in the cluster. When I create an API, and use the DNS name of the k8s service as the `upstream_url`, I get `{"message":"An unexpected error occurred"}` as the response. 

If I use the IP of the k8s service (instead of the name), then the request goes through just fine. 

I verified that I can curl the service from the kong pod, so dns is working properly inside my cluster. 

Kong error:

> 2017/04/05 18:54:12 [error] 77#0: *19193 [lua] responses.lua:101: before(): failed the initial dns/balancer resolve for 'go-microservice' with: dns server error; 2 server failure, client: 10.2.100.1, server: kong, request: "GET / HTTP/1.1", host: "service-go.apps.arch.mydomain.net:8000"

### Steps To Reproduce

1. Create an API with k8s dns service as upstream

> curl -i -X POST \
>     --url http://localhost:8005/apis/ \
>     --data 'name=go-microservice' \
>     --data 'hosts=service-go.apps.arch.mydomain.net' \
>     --data 'upstream_url=http://go-microservice:8080'

### Additional Details & Logs

- Kong version: 0.10.1

**Comment by stevesloka** [comment]
I just found if I use the fully qualified name of the service in k8s it works:

```
curl -i -X POST \
    --url http://localhost:8005/apis/ \
    --data 'name=go-microservice' \
    --data 'hosts=service-go.apps.arch.mydomain.net' \
    --data 'upstream_url=http://go-microservice.default.svc.cluster.local:8080'
```

**Comment by Tieske** [comment]
Yes, fqdn is required. There is an issue for implementing the dns `search` and `ndots` configuration options.

**Comment by stevesloka** [comment]
Thanks for confirming @Tieske!
