### ISSUE TITLE
Why no validation of request body in Hmac-Auth Plugin

### ISSUE THREAD

**Issue by vaibhavatul47** [Mashape/kong#2346]
### Summary

Why no validation of request body in Hmac-Auth Plugin. I used Hmac-Auth plugin in my project to validate users and to verify tampering of the request body. The provided Hmac-Auth plugin is good only for user credential validation. 

I used `content-md5` header as shown in the example but this md5 hash is not verified during authentication. This means, if someone tampers request body but sent same `content-md5` header, the request would still be authorized by Kong.

I had two options:
* Verify content md5 hash in my project. This would be required inside every API which expects a request body
* Create a new plugin which would also validate the integrity of request body along with validation of user credentials. ( I used this approach as it was more convenient than validation md5 hash everywhere in project)

### Steps To Reproduce

1. Create a Consumer, a Hmac credential and a POST API.
2. Enable Hmac-auth on this API and use `date` and `content-md5` values in `headers` for the **Authorization** header.
3. Create valid hmac headers: `date`, `content-md5`,  `Authorization` headers using POST request body.
4. Now Create a HTTP request with above headers but change request body. Now, content-md5 of new request body would change but don't update this in the header. When this request is sent it is validated by KONG even though content-md5 hash is not of the current request body.

### Additional Details & Logs

- Kong version: Happens in both 0.9 & 0.10

#### Note
This is the link to my Hmac plugin which does request integrity validation: https://github.com/vaibhavatul47/kong-custom-plugins 
Can we merge this logic in Hmac-Auth plugin of KONG ?

**Comment by vaibhavatul47** [comment]
PR: https://github.com/Mashape/kong/pull/2407

**Comment by p0pr0ck5** [comment]
Changes regarding this have been merged in 0.11!
