### ISSUE TITLE
Allow a single rate limit to be applied across all registered APIs

### ISSUE THREAD

**Issue by smitchelus** [Mashape/kong#2347]
### Summary

Hi, in our use case we have many different services that will all be fronted by an API gateway (preferably Kong). For our end user's standpoint there is only 1 offering so we would like to ensure that they 1 global rate limit across all of the registered APIs. While the `rate-limiting` plugin can be registered globally in Kong via the `/plugins` API, it still computes a rate limit per API. 

It would be nice if this plugin could be enhanced to allow it to be applied cross-API via configuration options.

### Steps To Reproduce

1. Register the rate-limiting plugin
```
curl -X POST http://localhost:8001/plugins \
    --data "name=rate-limiting" \
    --data "config.minute=10" \
    --data "config.limit_by=ip"
```
2. Register a couple of APIs
```
curl -i -X POST \
  --url http://localhost:8001/apis/ \
  --data 'name=api' \
  --data 'uris=/api' \
  --data 'upstream_url=http://api:3000'

curl -i -X POST \
  --url http://localhost:8001/apis/ \
  --data 'name=api2' \
  --data 'uris=/api2' \
  --data 'upstream_url=http://api:3000'
```
3. Run some requests across both APIs
```
curl  http://localhost:8000/api/boo
curl  http://localhost:8000/api2/boo
```
4. Note that the rate limiting headers in the response are tracking per API instead of pulling from 1 rate limit
```
/api response:
< X-RateLimit-Limit-minute: 10
< X-RateLimit-Remaining-minute: 9

/api2 response:
< X-RateLimit-Limit-minute: 10
< X-RateLimit-Remaining-minute: 9
```

### Additional Details & Logs

- Kong version (0.10.1)
- Kong debug-level startup logs (N/A)
- Kong error logs (N/A)
- Kong configuration (see above)
- Operating System: Docker/Linux

**Comment by smitchelus** [comment]
Just occurred to me that implementing this might be pretty simple. New config property to specify that you want a single limit across all APIs. Then [in the handler](https://github.com/Mashape/kong/blob/master/kong/plugins/rate-limiting/handler.lua#L75), set the api_id = 0 if this property is set. From that point on I think everything would flow naturally with no further changes.

**Comment by coopr** [comment]
Thanks to all for the discussion here. This feature is now available as part of the advanced rate limiting functionality in Kong Enterprise Edition. Please see https://www.mashape.com/enterprise/ for more details. Thank you!
