### ISSUE TITLE
No Replace Example

### ISSUE THREAD

**Issue by lnryan** [Mashape/kong#2349]
### Summary

The examples for the documentation are incomplete there is no example specifying the format for a replace transformation and there are no specification in the docs for the format either

### Steps To Reproduce

1. Read docs. See gap.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by Tieske** [comment]
docs are in https://github.com/Mashape/getkong.org , feel free to submit a PR. Would be most welcome!

**Comment by p0pr0ck5** [comment]
Closing this, as it pertains to the getkong.org repo; please feel free to open an issue or PR there. Thank you!

**Comment by zkenstein** [comment]
Hi @lnryan , do you get this replace example? I need this too
