### ISSUE TITLE
clean output of kong stop when no process is running

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#235]
should probably remove the second and third (empty) lines:

```
[INFO] Using configuration: /etc/kong/kong.yml
sh: 1: kill: No such process

[INFO] Removing pid at: /usr/local/kong/kong.pid
[ERR] Not running. Could not find pid: 176
```

**Comment by thefosk** [comment]
I think it's this line: https://github.com/Mashape/kong/blob/master/kong/cli/utils/signal.lua#L338

**Comment by thibaultCha** [comment]
This is what I see now:

```bash
kong|master ⇒ kong stop
[INFO] Using configuration: /etc/kong/kong.yml
[ERR] Not running. Could not find pid at: /usr/local/kong/kong.pid
```

has this been resolved?

**Comment by thefosk** [comment]
It happens on an edge case scenario (not sure, but maybe when Kong is being killed but the PID file still has the old process id), and it also happens in the test: https://travis-ci.org/Mashape/kong/builds/69369029#L1028
