### ISSUE TITLE
Check that shared dictionaries exist before starting Kong

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#2350]
I have seen many issue of people customizing the nginx configuration file, and mistakenly removing the shared dictionaries which will then cause an error at runtime.

Implement a startup check that makes sure all the dictionaries have been defined, otherwise don't start Kong.

**Comment by Tieske** [comment]
@thefosk where to do this check? in the CLI (hard) or in the Lua initialization (easy)...

**Comment by thibaultcha** [comment]
This should be checked in init_by_lua and instruct the user to add the directive in the error message which builds the directive strong for the user to copy-paste)
