### ISSUE TITLE
KONG Admin API Query language

### ISSUE THREAD

**Issue by rgottumu** [Mashape/kong#2351]
Is there a query language supported by KONG api? How can I search for an API by request path?

I would like to query apis added to the system on request_path or hosts or combination of other fields. Is this possible now? If not, any plans to implement this feature?

**Comment by Tieske** [comment]
nothing active. We're considering changing some of this, but early stages, and don't expect a 'query language'.

Consensus so far has been that Kong provides a raw api, and GUI tools can be build in front of that to do the more granular stuff.

**Comment by rgottumu** [comment]
I guess, ability query based on different fields (not just name or id) should be part of raw api or is there a way to achieve this with out getting the list of api's and iterating?
