### ISSUE TITLE
kong start error:[postgres error] ERROR: function to_regclass(unknown) does not exist

### ISSUE THREAD

**Issue by dinymis** [Mashape/kong#2357]
### Summary
just kong-0.10.0, start 
SUMMARY_GOES_HERE
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] ERROR: function to_regclass(unknown) does not exist (8)
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	./kong:5: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'pcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>

### Steps To Reproduce
1. ./kong start --vv

### Additional Details & Logs
- Kong version 0.10.0
- Kong debug-level startup logs (`$ kong start --vv`)
[root@localhost bin]# ./kong start --vv
2017/04/07 18:02:23 [verbose] Kong: 0.10.1
2017/04/07 18:02:23 [debug] ngx_lua: 10007
2017/04/07 18:02:23 [debug] nginx: 1011002
2017/04/07 18:02:23 [debug] Lua: LuaJIT 2.1.0-beta2
2017/04/07 18:02:23 [verbose] reading config file at /etc/kong/kong.conf
2017/04/07 18:02:23 [debug] KONG_PREFIX ENV found with "/home/dy/kong/openresty/nginx"
2017/04/07 18:02:23 [debug] admin_listen = "0.0.0.0:8001"
2017/04/07 18:02:23 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/04/07 18:02:23 [debug] admin_ssl = true
2017/04/07 18:02:23 [debug] anonymous_reports = true
2017/04/07 18:02:23 [debug] cassandra_consistency = "ONE"
2017/04/07 18:02:23 [debug] cassandra_contact_points = {"127.0.0.1"}
2017/04/07 18:02:23 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/04/07 18:02:23 [debug] cassandra_keyspace = "kong"
2017/04/07 18:02:23 [debug] cassandra_lb_policy = "RoundRobin"
2017/04/07 18:02:23 [debug] cassandra_port = 9042
2017/04/07 18:02:23 [debug] cassandra_repl_factor = 1
2017/04/07 18:02:23 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/04/07 18:02:23 [debug] cassandra_ssl = false
2017/04/07 18:02:23 [debug] cassandra_ssl_verify = false
2017/04/07 18:02:23 [debug] cassandra_timeout = 5000
2017/04/07 18:02:23 [debug] cassandra_username = "kong"
2017/04/07 18:02:23 [debug] cluster_listen = "0.0.0.0:7946"
2017/04/07 18:02:23 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/04/07 18:02:23 [debug] cluster_profile = "wan"
2017/04/07 18:02:23 [debug] cluster_ttl_on_failure = 3600
2017/04/07 18:02:23 [debug] custom_plugins = {}
2017/04/07 18:02:23 [debug] database = "postgres"
2017/04/07 18:02:23 [debug] dns_hostsfile = "/etc/hosts"
2017/04/07 18:02:23 [debug] dns_resolver = {}
2017/04/07 18:02:23 [debug] log_level = "notice"
2017/04/07 18:02:23 [debug] lua_code_cache = "on"
2017/04/07 18:02:23 [debug] lua_package_cpath = ""
2017/04/07 18:02:23 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/04/07 18:02:23 [debug] lua_socket_pool_size = 30
2017/04/07 18:02:23 [debug] lua_ssl_verify_depth = 1
2017/04/07 18:02:23 [debug] mem_cache_size = "128m"
2017/04/07 18:02:23 [debug] nginx_daemon = "on"
2017/04/07 18:02:23 [debug] nginx_optimizations = true
2017/04/07 18:02:23 [debug] nginx_worker_processes = "auto"
2017/04/07 18:02:23 [debug] pg_database = "kong"
2017/04/07 18:02:23 [debug] pg_host = "127.0.0.1"
2017/04/07 18:02:23 [debug] pg_port = 5432
2017/04/07 18:02:23 [debug] pg_ssl = false
2017/04/07 18:02:23 [debug] pg_ssl_verify = false
2017/04/07 18:02:23 [debug] pg_user = "kong"
2017/04/07 18:02:23 [debug] prefix = "/home/dy/kong/openresty/nginx"
2017/04/07 18:02:23 [debug] proxy_listen = "0.0.0.0:8000"
2017/04/07 18:02:23 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2017/04/07 18:02:23 [debug] serf_path = "serf"
2017/04/07 18:02:23 [debug] ssl = true
2017/04/07 18:02:23 [debug] upstream_keepalive = 60
2017/04/07 18:02:23 [verbose] prefix in use: /home/dy/kong/openresty/nginx
2017/04/07 18:02:23 [verbose] preparing nginx prefix directory at /home/dy/kong/openresty/nginx
2017/04/07 18:02:23 [verbose] saving serf identifier to /home/dy/kong/openresty/nginx/serf/serf.id
2017/04/07 18:02:23 [debug] searching for OpenResty 'resty' executable
2017/04/07 18:02:23 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.2'
2017/04/07 18:02:23 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2017/04/07 18:02:23 [verbose] saving serf shell script handler to /home/dy/kong/openresty/nginx/serf/serf_event.sh
2017/04/07 18:02:23 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/04/07 18:02:23 [verbose] default SSL certificate found at /home/dy/kong/openresty/nginx/ssl/kong-default.crt
2017/04/07 18:02:23 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2017/04/07 18:02:23 [verbose] admin SSL certificate found at /home/dy/kong/openresty/nginx/ssl/admin-kong-default.crt
2017/04/07 18:02:24 [verbose] running datastore migrations
2017/04/07 18:02:24 [verbose] could not start Kong, stopping services
2017/04/07 18:02:24 [verbose] leaving serf cluster
2017/04/07 18:02:24 [verbose] stopped services

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] ERROR: function to_regclass(unknown) does not exist (8)
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	./kong:5: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'pcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>
- Operating System :centos 6.6

other:
[root@localhost bin]# psql -h 127.0.0.1 -p 5432 -U kong
psql (8.4.20)
Type "help" for help.

kong=> \du
            List of roles
 Role name | Attributes  | Member of 
-----------+-------------+-----------
 dyy       |             | {}
 kong      |             | {}
 postgres  | Superuser   | {}
           : Create role   
           : Create DB     

kong=> \l
                                  List of databases
   Name    |  Owner   | Encoding |  Collation  |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 dyy       | dyy      | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 kong      | kong     | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/kong
                                                             : kong=CTc/kong
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres
                                                             : postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres
                                                             : postgres=CTc/postgres
(5 rows)

**Comment by Tieske** [comment]
usually this means you're running an incompatible postgres version

Feel free to reopen if it persists.
