### ISSUE TITLE
 Cannot delete upstreams on Kong 0.10.1

### ISSUE THREAD

**Issue by SzymonKlimuk** [Mashape/kong#2358]
### Summary

Hi,

I'm playing with upstreams on Kong 0.10.1 and I'm getting some strange errors while I'm trying to delete them.

### Steps To Reproduce

**# curl -X POST --url http://localhost:8001/upstreams/ --data "name=test"**
{"orderlist":[84,52,17,22,14,35,15,98,72,42,83,27,92,86,24,26,76,16,74,11,6,85,18,20,63,29,5,43,9,7,70,79,94,19,25,60,45,61,96,32,49,65,53,46,77,100,31,67,2,81,40,44,82,95,37,90,12,47,48,33,13,54,55,89,58,71,68,93,50,39,91,87,78,64,8,97,30,34,57,69,10,51,99,1,21,80,75,28,3,59,56,38,41,66,73,4,88,36,62,23],"slots":100,"id":"eac5ea6d-4b09-4447-8319-5816d0f8fcdf","name":"test","created_at":1491564431504}

**# curl --url http://localhost:8001/upstreams/test**
{"orderlist":[84,52,17,22,14,35,15,98,72,42,83,27,92,86,24,26,76,16,74,11,6,85,18,20,63,29,5,43,9,7,70,79,94,19,25,60,45,61,96,32,49,65,53,46,77,100,31,67,2,81,40,44,82,95,37,90,12,47,48,33,13,54,55,89,58,71,68,93,50,39,91,87,78,64,8,97,30,34,57,69,10,51,99,1,21,80,75,28,3,59,56,38,41,66,73,4,88,36,62,23],"slots":100,"id":"eac5ea6d-4b09-4447-8319-5816d0f8fcdf","name":"test","created_at":1491564431504}

**# curl -X DELETE --url http://localhost:8001/upstreams/test**
{"message":"An unexpected error occurred"}

### Additional Details & Logs

- Kong version 0.10.1
- Operating System CentOS Linux release 7.3.1611 (Core)
- Cassandra [cqlsh 5.0.1 | Cassandra 3.0.9 | CQL spec 3.4.0 | Native protocol v4]

and in the error.log I'm getting:

2017/04/07 11:27:24 [error] 4542#0: *324112 [lua] responses.lua:101: handler(): could not prepare query: [Invalid] Non PRIMARY KEY columns found in where clause: name , client: 127.0.0.1, server: kong_admin, request: "DELETE /upstreams/test HTTP/1.1", host: "localhost:8001"

I have some debug logs from other attempts:
2017/04/07 14:29:59 [debug] 20602#0: *2639 [lua] cluster.lua:602: prepare(): [lua-cassandra] preparing DELETE FROM upstreams WHERE name = ? AND id = ? on host
2017/04/07 14:29:59 [error] 20602#0: *2639 [lua] responses.lua:101: handler(): could not prepare query: [Invalid] Non PRIMARY KEY columns found in where clause: name , client: , server: kong_admin, request: "DELETE /upstreams/test HTTP/1.1", host: ":8001"

**Comment by corentin59** [comment]
Hello,

Same problem for me with a fresh setup.

**Comment by JingWZ** [comment]
also problem when PATCH /upstreams/{name or id}
