### ISSUE TITLE
Kong Admin API for Search

### ISSUE THREAD

**Issue by rgottumu** [Mashape/kong#2368]
This is an extension to my other question (which is closed) asked here #2351 

I am trying to build a UI where I want to restrict users from re-using uris (request_path before 0.10). So whenever a dev want to add an API, i want to check for duplicate uri. Current Admin API for list do not support query on URIs.  So I have few questions:

1. Is there a plan to add uri as a query parameter?
2. List currently supports exact match on query parameter value. Is there any plan to add a wild card search?
3. If there is no plan to add any of the above, is there a way i can query api's with out retrieving the full list and iterating?

Thanks you so much.

**Comment by p0pr0ck5** [comment]
As mentioned in #2351, there are no active plans to provide such a dynamic mechanism. Kong's API provides raw access to the data as necessary, giving users the flexibility to do granular work. You could build your UI with a caching mechanism to avoid needing to scan the entire database for every query, and then build the search functionality on top of that. IMO adding that into Kong's API mechanism smells too much of "and the kitchen sink" philosophy.
