### ISSUE TITLE
HMAC Authentication Fails with request-line header

### ISSUE THREAD

**Issue by nguilford** [Mashape/kong#2369]
### Summary

Authentication using hmac fails when including the `request-line` header.

### Steps To Reproduce

1.) Configure an kong proxy api to authenticate with hmac
2.) Create a user with hmac
3.) Create an hmac-authenticated request for this user to your proxy api using only `date` and `host` headers

Result: Request is authenticated and proxied to the upstream

4.) Create an hmac-authenticated request for this user to your proxy api using `date`, `host` and `request-line` headers

Result: `{"message":"HMAC signature does not match"}`

### Additional Details & Logs

Kong Version: 0.9.2
Operating System: centos:7 (from kong docker image)
Kong Error Logs: empty
Client: nodejs with `crypto`

Client Code:

```javascript
var util = require('util');
var crypto = require('crypto');
var request = require('request');

var util = require('util');
var crypto = require('crypto');
var request = require('request');

var username = 'my-username';
var secret = 'my-secret';
var apiUrl = 'http://my-kong-api.com';
var host = 'my-kong-api.com';
var path = '/my-path';
var method = 'GET';
var date = new Date().toUTCString();
var requestLine = method + ' ' + path + ' HTTP/1.1';

// Create the Authorization Header
var stringToSign = 'date: ' + date.trim() + '\n' +
                   'host: ' + host + '\n' +
                   requestLine;
var encodedSignature = crypto.createHmac("sha1", secret).update(stringToSign).digest("base64");
var hmacAuth = 'hmac username="' + username + '",algorithm="hmac-sha1",headers="date host request-line",signature="' + encodedSignature + '"';

// Make the request
request({
  method: method,
  url: util.format("%s%s", apiUrl, path),
  headers: {
    date: date,
    host: host,
    Authorization: hmacAuth,
  }
}, function (error, response, body) {
  if (error) {
    console.error(error);
  } else {
    console.log(body);
  }
});
```

I have tried this with `request-line` as both the first and last header in the list, making sure to mimic the order in my signature, and the result is the same (`console.log(body)` prints  `{"message":"HMAC signature does not match"}`). I am certain that the text in `requestLine` is correct, as `console.log` on the `response` object shows the request-line as it is formatted above.

As mentioned, if I remove `request-line` from the list of headers and from the signature, the request is properly authenticated.

**Comment by vaibhavatul47** [comment]
I am using `request-line` header in my project and its working fine for me. Can you share your exact HTTP call that you are hitting to Kong.

**Comment by vaibhavatul47** [comment]
Your `apiUrl` is pointing to '**https**://my-kong-api.com' whereas in request line generation you have hard coded `HTTP/1.1`. Change this to `HTTPS/1.1` and then try again.

**Comment by nguilford** [comment]
<b>https</b> was a typo in this report. I am indeed matching the protocol. I have edited the description to reflect this. Will post the exact HTTP call shortly.

**Comment by nguilford** [comment]
```bash
20:30 $ curl -vv -H "date: Thu, 13 Apr 2017 20:30:40 GMT" \
		 -H "Authorization: hmac username=\"hmac-user\",algorithm=\"hmac-sha1\",headers=\"date host request-line\",signature=\"QXU7FvZfAMJTJwbKYa6xg8DwR74=\"" \
		 http://my-kong-api.com/my-path
                                                                                                                                    
* Hostname was NOT found in DNS cache
*   Trying X.X.X.X…
* Connected to my-kong-api.com (X.X.X.X) port 80 (#0)
> GET /my-path HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> date: Thu, 13 Apr 2017 20:30:40 GMT
> Authorization: hmac username="hmac-user",algorithm="hmac-sha1",headers="request-line date host",signature="QXU7FvZfAMJTJwbKYa6xg8DwR74="
> Host: my-kong-api.com
> 
< HTTP/1.1 403 Forbidden
* Server nginx/1.10.1 is not blacklisted
< Server: nginx/1.10.1
< Date: Thu, 13 Apr 2017 20:31:39 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 44
< Connection: keep-alive
< 
{"message":"HMAC signature does not match"}
```


I used the code above to generate date, signature and authorization header. Printed them to console and then assembled curl request to get you the raw http request. Some details have been changed to obfuscate secrets. Again, this works fine when omitting request-line from signature and list of headers.

**Comment by vaibhavatul47** [comment]
I ran your script on my machine and it worked without any problem, hmac-auth is working as expected.
I only changed following variables in your code: `username` `secret` `apiUrl` `host` `path`
Make sure the user exists and the same secret is being used in Kong DB and your client side script.

**Comment by nguilford** [comment]
The username and secret must be configured correctly because everything works as expected so long as I omit `request-line` from the signature but leave `date` and `host`. I would expect failure in all cases if there were a problem with username and/or secret. But just in case, I ran the queries to verify and from what I can tell everything matches:

```bash
17:25 $ curl https://kong-admin-api.com/consumers/my-username/hmac-auth | jq '.'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   214  100   214    0     0    751      0 --:--:-- --:--:-- --:--:--   750
{
  "total": 1,
  "data": [
    {
      "consumer_id": "9f37f153-84df-413a-8853-d31f83cb3fba",
      "created_at": 1491853200000,
      "username": "my-username",
      "id": "a04b715b-f292-479c-bcf9-f1938ff22acf",
      "secret": “my-secret"
    }
  ]
}

17:26 $ curl https://kong-admin-api.com/apis/my-kong-api | jq '.'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   292  100   292    0     0   1004      0 --:--:-- --:--:-- --:--:--  1003
{
  "request_host": "my-kong-api.com",
  "strip_request_path": false,
  "preserve_host": false,
  "name": “my-kong-api",
  "id": "530e67c2-6c0e-4f00-86ac-e8fcfc9c5195",
  "created_at": 1475009390000,
  "upstream_url": "http://my-kong-api.com"
}

17:27 $ curl https://kong-admin-api.com/apis/my-kong-api/plugins | jq '.'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   229  100   229    0     0   5961      0 --:--:-- --:--:-- --:--:--  6026
{
  "total": 1,
  "data": [
    {
      "config": {
        "clock_skew": 300,
        "hide_credentials": false
      },
      "name": "hmac-auth",
      "enabled": true,
      "created_at": 1491853500000,
      "id": "43582710-c5c6-4745-aa21-8d18ae6f7f14",
      "api_id": "530e67c2-6c0e-4f00-86ac-e8fcfc9c5195"
    }
  ]
}
```

Perhaps this is a problem isolated to the version of kong i'm running? We are looking to ugprade to 0.10.x so I will be spinning up a test cluster soon. When I do, I will check there to see if there is any issue.

**Comment by vaibhavatul47** [comment]
I am using `request-line` in both **0.9** and **0.10** versions of Kong, and both works fine for me. If I was at your place I would add following logs to kong source ( /usr/local/Cellar/luarocks/2.4.0/share/lua/5.1/kong/plugins/hmac-auth/access.lua - in Mac OS ) and then debug the issue:

1. Match signing string generated at Kong and Client.
2. Match Username/secret.
3. Match final sha hash.

You will have to restart kong to reflect any changes you make to source.

**Comment by p0pr0ck5** [comment]
@nguilford have you been able to do any debugging on this issue? Seems there's be trouble reproducing your results.

**Comment by nguilford** [comment]
@p0pr0ck5 I reproduce this 100% on our kong cluster running v0.9.2. I am in the middle of upgrading to 0.10.1 and am scheduled to complete that upgrade tomorrow afternoon. Once this is complete, I will try to reproduce with the latest version and let you know what I find.

**Comment by y-zono** [comment]
@nguilford Hi, have you solved? I have the same issue on our kong cluster running v0.10.1. I'm looking into it now.

**Comment by nguilford** [comment]
@y-zono @p0pr0ck5

Apologies for the delay in checking this again; other things had taken priority. 

I did figure this out. It turns out that the load balancer I have in front of kong, is changing my `HTTP/1.1` request to an `HTTP/1.0` request. So, even though my client is sending `HTTP/1.1`, kong is receiving it with a different protocol on the request line. Indeed, when I change the request-line to `HTTP/1.0` in the signature, the request is authenticated. You might check to see if the same thing is happening for you.

**Comment by y-zono** [comment]
@nguilford Thank you. My issue was same as you. It seems my L4 load balancer also changes from HTTP/1.1 to HTTP/1.0. You saved me!

**Comment by p0pr0ck5** [comment]
Thanks for the update here!

**Comment by junjie-bianjie** [comment]
I already occurs this error.
Because my url: https, so I change HTTP/1.1 -> HTTP/2.0
