### ISSUE TITLE
Typo in migration step

### ISSUE THREAD

**Issue by regiskuckaertz** [Mashape/kong#2372]
Hello. We were in the process of migrating our Kong instances to 0.10.1 at the guardian when we noticed [this small typo](https://github.com/Mashape/kong/pull/2313/files#diff-a08627b15ce5c381a4a1de0321028957R392) in #2313 : `if not row.config.anonymnous then` will always be `true` and reset the `anonymous` key to the empty string.

**Comment by Tieske** [comment]
fixed!
