### ISSUE TITLE
{"message":"no API found with those values"}

### ISSUE THREAD

**Issue by ChaimaeELL** [Mashape/kong#2376]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1. i added My API to Kong by executing the following command :
curl -i -X POST http://localhost:8001/apis/ \
   -d 'name=logService' \
   -d 'upstream_url=http://localhost/logService/public/index.php' \
  -d 'uris=/logging' \
   -d 'hosts=logService' \
   -d 'methods=GET,HEAD,POST,DELETE'

**it gives this response :**
HTTP/1.1 201 Created
Date: Tue, 11 Apr 2017 14:13:24 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Server: kong/0.10.0

{"methods":["GET","HEAD","POST","DELETE"],"http_if_terminated":true,"id":"416e477b-c20c-4efd-8993-b312f6d49974","retries":5,"preserve_host":false,"created_at":1491920005000,"upstream_connect_timeout":60000,"upstream_url":"http:\/\/localhost\/logService\/public\/index.php","upstream_read_timeout":60000,"upstream_send_timeout":60000,"https_only":false,"strip_uri":true,"uris":["\/logging"],"name":"logService","hosts":["logService"]}

2.  curl -i -X GET localhost:8001/apis/logService

HTTP/1.1 200 OK
Date: Tue, 11 Apr 2017 15:03:59 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Server: kong/0.10.0

{"methods":["GET","HEAD","POST","DELETE"],"uris":["\/","\/logging"],"id":"416e477b-c20c-4efd-8993-b312f6d49974","hosts":["logService"],"preserve_host":false,"created_at":1491920005000,"upstream_connect_timeout":60000,"upstream_url":"http:\/\/localhost\/logService\/public\/index.php","strip_uri":true,"name":"logService","https_only":false,"http_if_terminated":true,"retries":5,"upstream_send_timeout":60000,"upstream_read_timeout":60000}

3. curl -i -X GET  --url  http://localhost:8000/  --header 'Host: logService'

HTTP/1.1 404 Not Found
Date: Tue, 11 Apr 2017 15:05:14 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: kong/0.10.0

{"message":"no API found with those values"}
4.

### Additional Details & Logs

- Kong version (`0.10.0`)

**Comment by Tieske** [comment]
try
```
curl -i -X GET --url http://localhost:8000/logging --header 'Host: logService'
```

since you specified both a `uri` and a `host` value, the request must match both to match that api definition

**Comment by ChaimaeELL** [comment]
thanks for your response, i did it but i got the same response

**Comment by thibaultcha** [comment]
Note the path in the URL provided in @Tieske's example. I just gave it a try locally and it worked on 0.10.1.

**Comment by thibaultcha** [comment]
I strongly suggest that you read the routing/proxying guide if you haven't already:

    https://getkong.org/docs/0.10.x/proxy

**Comment by ChaimaeELL** [comment]
thank you @thibaultcha for your help, i read it but i still not able to resolve this problem

**Comment by ChaimaeELL** [comment]
Hi, can you give me some mistakes that lead to this error ? i searshed alot but i didn't find what is the problem.

**Comment by bungle** [comment]
@ChaimaeELL, did you already try adding `logging` to the `url` parameter of your failed `curl` command? Just to be sure that you read @Tieske's comment correctly?

**Comment by bungle** [comment]
Also, could you try with `0.10.1` as well?

**Comment by ChaimaeELL** [comment]
okay, thanks, i have added tow Apis, the first one works correctely, but the second one that i specified above won't be like the first, i asked if there is possible to add more than one api or not, because i tried all what you did give me but still not able to find what is the problem

**Comment by thibaultcha** [comment]
@ChaimaeELL We can't help you if we don't see what APIs you have configured and the calls you are actually making.

**Comment by ChaimaeELL** [comment]
ah yes, thanks for your help, i think that i didn't explain my problem very well

**Comment by Elfatimaz** [comment]
I have the same problem..i added an api named storage that works perfectly but all the api i added after it do not work ..i even tried to add an other api sharing the same upstream url with the storage api with different name and host name but the call to this new api returns " no api found with these values"..is there any constraints on the parameters we register the api with ?

**Comment by ChaimaeELL** [comment]
thanks for you all, i have removed all apis that i added before and retried finally it works.

**Comment by kumarinstor** [comment]
I added this to upstream URL -- http://localhost:1111/student/:student_id
then in urIs i added /student/:student_id
when I run this http://localhost:8000/student/123 it's showing no API found with those values

**Comment by Tieske** [comment]
@kumarinstor please do not cross-post, use [Kong Nation](https://discuss.konghq.com/) for those type of questions.
