### ISSUE TITLE
Kong 0.10 and table with schema.flexible creates string elements in addition to table elements

### ISSUE THREAD

**Issue by jdarling** [Mashape/kong#2378]
### Summary

**NOTE** I posted this to the google group, but after a few days of no replies trying here.  Still trying to decide if this is a "undocumented feature" or a "bug"

I noticed what seems to be a strange behavior when using a flexible table in a custom plugin, wondering if this is one of those "As designed" or if I found a bug.

Rather than try to explain, here is my example:

### Steps To Reproduce

Starting with the schema:

```
{
  fields = {
    routes = {
      type = "table",
      schema = {
        flexible = true,
        fields = {
          method = { type = "string", default = "" },
          request_method = { type = "string", default = "" },
          request_querystring = { type = "string", default = "" },
          request_text = { type = "string", default = "" },
          request_json = { type = "string", default = "" },
          request_headers = { type = "string", default = "" },
          response_text = { type = "string", default = "" },
          response_json = { type = "string", default = "" },
          response_headers = { type = "string", default = "" },
        }
      }
    }
  }
}
```

Then posting to create a plugin on an API (well I captured the PUT but same for the POST):

```
{
  "api_id": "464977c1-06f3-449c-a290-430f8cc33ff5",
  "id": "8559c6d7-3b22-45cc-97a5-3705d463b5e8",
  "created_at": 1491855608824,
  "enabled": true,
  "name": "rewrite",
  "config": {
    "routes": {
      "\/post": {
        "request_text": "",
        "response_json": "",
        "method": "",
        "request_querystring": "",
        "response_headers": "table.extend(src, {res = \"Foo header2 ftw!\"})",
        "request_method": "post",
        "request_headers": "table.extend(src, {req = \"Foo header2 ftw!\"})",
        "response_text": "",
        "request_json": ""
      },
      "\/get": {
        "request_text": "",
        "response_json": "",
        "method": "",
        "request_querystring": "table.extend(src, {Foo = \"Foo QS ftw!\"})",
        "response_headers": "",
        "request_method": "",
        "request_headers": "",
        "response_text": "",
        "request_json": ""
      }
    }
  }
}
```

What I get back is not what I would expect:

```
{
  "api_id": "464977c1-06f3-449c-a290-430f8cc33ff5",
  "id": "8559c6d7-3b22-45cc-97a5-3705d463b5e8",
  "created_at": 1491855608824,
  "enabled": true,
  "name": "rewrite",
  "config": {
    "routes": {
      "\/post": {
        "request_method": "post",
        "request_json": "",
        "method": "",
        "response_headers": "table.extend(src, {res = \"Foo header2 ftw!\"})",
        "request_querystring": "",
        "request_text": "",
        "request_headers": "table.extend(src, {req = \"Foo header2 ftw!\"})",
        "response_text": "",
        "response_json": ""
      },
      "request_method": "",
      "\/get": {
        "request_method": "",
        "request_json": "",
        "method": "",
        "response_headers": "",
        "request_querystring": "table.extend(src, {Foo = \"Foo QS ftw!\"})",
        "request_text": "",
        "request_headers": "",
        "response_text": "",
        "response_json": ""
      },
      "request_json": "",
      "method": "",
      "request_querystring": "",
      "response_text": "",
      "request_text": "",
      "request_headers": "",
      "response_headers": "",
      "response_json": ""
    }
  }
}
```

Notice every element for the root schema appears as an entity on the table in addition to the actual members I posted.  Seems like in the validator it is copying the values from the schema back into what gets stored and then appending each element into the table.  If this is an as designed thing, I would love to know why, because seems like a bad opportunity for a collision.

I also noticed that if I try and use nested tables inside of a flexible table it gets worse, thought that maybe nesting wasn't supported, would love to know if it is as that would make this much easier to read/maintain.

### Additional Details & Logs

- Kong version 0.10.x

**Comment by thibaultcha** [comment]
The `schema.flexible` flag is more of a hack, or undocumented solution and should probably not be used in the first place, especially by third-party plugins. There will be a time when we'll release a stable/officially supported better modelling API for entities and plugins configs.

For now, `schema.flexible` is doing its job in the response-ratelimiting plugin and I think you should restrain yourself from using it.

**Comment by p0pr0ck5** [comment]
Closing, following Thibault's response. Thanks!

**Comment by jdarling** [comment]
Considering there isn't really any documentation around schema types and utilization you might want to note in the code of existing plugins what parts are "Don't do this" type things.  While a dictionary would be easier in my case, I can switch over to an Array and just check for unique keys on sub schemas.
