### ISSUE TITLE
Lambda Plugin Headers

### ISSUE THREAD

**Issue by adamlc** [Mashape/kong#2379]
Hey guys, great work on Kong! I have been evaluating the Lambda plugin for Kong.

During my testing I've found that none of the headers get passed over from Kong. I would have thought that any headers from the original request would be forwarded to lambda through the event? This seems to work for post data, but not headers :(

This would be particularly useful we so can extract the auth headers and http method 👍

**Comment by Tieske** [comment]
Sounds to me as a great PR opportunity :smile:

**Comment by adamlc** [comment]
Could well be! Although can't say I've ever developed with LUA before.

Do we think we should allow for custom headers, bodies / responses to be set too? I know in API gateway you can set mapping so that custom headers and responses can be sent. Not sure what the best way to do this would be and remain backwards compatible with the current behaviour.

**Comment by p0pr0ck5** [comment]
@adamlc we'd certainly be happy to entertain various ideas and discussions in a PR, or on the mailing list or Gitter. GitHub issues, however, should be reserved for issues/problems/bugs while running Kong. Feel free to open a PR for this, or bring it up in the mailing list for further discussion. Thanks!
