### ISSUE TITLE
Kong in Azure

### ISSUE THREAD

**Issue by jiteshBhate** [Mashape/kong#2380]
### Summary
I am facing following issue, to deploy Kong in Azure portal 
New-AzureRmResourceGroupDeployment : 10:12:57 AM - Resource Microsoft.Compute/virtualMachines 'MyAzureKongVM' failed with message '{
  "error": {
    "code": "InvalidParameter",
    **"target": "linuxConfiguration.ssh.publicKeys.path",
    "message": "The value of parameter linuxConfiguration.ssh.publicKeys.path is invalid."**
  }
}' 

I followed https://github.com/Mashape/kong-dist-azure
And generated ssh key using
ssh-keygen -t rsa -b 2048 
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys

key is getting saved in file is C:\users\@username\ .ssh\id_rsa.pub
and I updated sshKeypath and sshKeyData as per intruction
I am using windows 7.

Thanks,
Jitesh

**Comment by jiteshBhate** [comment]
getting this issue now
--------------------------------------------------------
OPERATION IDF5CD5350AA9B59B3
TRACKING IDb0c4d94c-85d4-4c8b-bd72-132586d4a3e7
STATUSConflict
PROVISIONING STATEFailed
TIMESTAMP4/13/2017, 3:47:43 PM
DURATION21 seconds
TYPEMicrosoft.Compute/virtualMachines
RESOURCE ID/subscriptions/04fa752d-299b-4df5-974f-fd3b77537377/resourceGroups/latestkong/providers/Microsoft.Compute/virtualMachines/MyAzureKongVM
STATUSMESSAGE{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'install'. Error message: \"Command returned an error.\n---stdout---\n (2.1.8) ...\nProcessing triggers for man-db (2.6.7.1-1ubuntu1) ...\nProcessing triggers for ureadahead (0.100.0-16) ...\nProcessing triggers for mime-support (3.54ubuntu1.1) ...\nSetting up libcurl3:amd64 (7.35.0-1ubuntu2.10) ...\nSetting up curl (7.35.0-1ubuntu2.10) ...\nSetting up libopts25:amd64 (1:5.18-2ubuntu2) ...\nSetting up ntp (1:4.2.6.p5+dfsg-3ubuntu2.14.04.10) ...\n * Starting NTP server ntpd\n   ...done.\nSetting up libmnl0:amd64 (1.0.3-3ubuntu1) ...\nSetting up libnetfilter-conntrack3:amd64 (1.0.4-1) ...\nSetting up openssl (1.0.1f-1ubuntu2.22) ...\nSetting up dnsmasq-base (2.68-1ubuntu0.1) ...\nSetting up dnsmasq (2.68-1ubuntu0.1) ...\n * Starting DNS forwarder and DHCP server dnsmasq\n   ...done.\nSetting up liberror-perl (0.17-1.1) ...\nSetting up git-man (1:1.9.1-1ubuntu0.4) ...\nSetting up git (1:1.9.1-1ubuntu0.4) ...\nSetting up lua5.1 (5.1.5-5ubuntu0.1) ...\nupdate-alternatives: using /usr/bin/lua5.1 to provide /usr/bin/lua (lua-interpreter) in auto mode\nupdate-alternatives: using /usr/bin/luac5.1 to provide /usr/bin/luac (lua-compiler) in auto mode\nSetting up make (3.81-8.2ubuntu3) ...\nSetting up netcat-traditional (1.10-40) ...\nSetting up netcat (1.10-40) ...\nSetting up python-support (1.0.15) ...\nSetting up unzip (6.0-9ubuntu1.5) ...\nSetting up cassandra (2.1.8) ...\nAdding group `cassandra' (GID 113) ...\nDone.\nvm.max_map_count = 1048575\nnet.ipv4.tcp_keepalive_time = 300\nProcessing triggers for libc-bin (2.19-0ubuntu6.6) ...\nProcessing triggers for ureadahead (0.100.0-16) ...\nProcessing triggers for python-support (1.0.15) ...\nCassandra installed\n * Restarting Cassandra cassandra\n   ...done.\nHit http://security.ubuntu.com trusty-security InRelease\nIgn http://azure.archive.ubuntu.com trusty InRelease\nHit http://azure.archive.ubuntu.com trusty-updates InRelease\nHit http://azure.archive.ubuntu.com trusty Release.gpg\nHit http://azure.archive.ubuntu.com trusty Release\nHit http://security.ubuntu.com trusty-security/main Sources\nHit http://azure.archive.ubuntu.com trusty-updates/main Sources\nHit http://azure.archive.ubuntu.com trusty-updates/universe Sources\nHit http://azure.archive.ubuntu.com trusty-updates/main amd64 Packages\nHit http://security.ubuntu.com trusty-security/universe Sources\nHit http://azure.archive.ubuntu.com trusty-updates/universe amd64 Packages\nHit http://azure.archive.ubuntu.com trusty-updates/main Translation-en\nHit http://azure.archive.ubuntu.com trusty-updates/universe Translation-en\nHit http://security.ubuntu.com trusty-security/main amd64 Packages\nHit http://azure.archive.ubuntu.com trusty/main Sources\nHit http://azure.archive.ubuntu.com trusty/universe Sources\nHit http://security.ubuntu.com trusty-security/universe amd64 Packages\nHit http://azure.archive.ubuntu.com trusty/main amd64 Packages\nHit http://azure.archive.ubuntu.com trusty/universe amd64 Packages\nHit http://azure.archive.ubuntu.com trusty/main Translation-en\nHit http://security.ubuntu.com trusty-security/main Translation-en\nHit http://azure.archive.ubuntu.com trusty/universe Translation-en\nHit http://security.ubuntu.com trusty-security/universe Translation-en\nIgn http://debian.datastax.com stable InRelease\nHit http://debian.datastax.com stable Release.gpg\nHit http://debian.datastax.com stable Release\nHit http://debian.datastax.com stable/main amd64 Packages\nIgn http://debian.datastax.com stable/main Translation-en\nReading package lists...\nReading package lists...\nBuilding dependency tree...\nReading state information...\nnetcat is already the newest version.\nlibpcre3 is already the newest version.\nopenssl is already the newest version.\ndnsmasq is already the newest version.\nlua5.1 is already the newest version.\n0 upgraded, 0 newly installed, 0 to remove and 192 not upgraded.\nSelecting previously unselected package kong.\n(Reading database ... 53472 files and directories currently installed.)\nPreparing to unpack current-kong.deb ...\nUnpacking kong (0.10.1) ...\nSetting up kong (0.10.1) ...\nProcessing triggers for man-db (2.6.7.1-1ubuntu1) ...\nulimit is currently set to \"1024\". For better performance set it to at least \"4096\" using \"ulimit -n\"\n\n---errout---\n5% 51.6M 0s\n 14950K .......... .......... .......... .......... .......... 86% 9.96M 0s\n 15000K .......... .......... .......... .......... .......... 86%  123M 0s\n 15050K .......... .......... .......... .......... .......... 86%  101M 0s\n 15100K .......... .......... .......... .......... .......... 86%  125M 0s\n 15150K .......... .......... .......... .......... .......... 87%  121M 0s\n 15200K .......... .......... .......... .......... .......... 87%  127M 0s\n 15250K .......... .......... .......... .......... .......... 87%  116M 0s\n 15300K .......... .......... .......... .......... .......... 88%  125M 0s\n 15350K .......... .......... .......... .......... .......... 88%  125M 0s\n 15400K .......... .......... .......... .......... .......... 88% 2.79M 0s\n 15450K .......... .......... .......... .......... .......... 88% 85.1M 0s\n 15500K .......... .......... .......... .......... .......... 89%  126M 0s\n 15550K .......... .......... .......... .......... .......... 89%  126M 0s\n 15600K .......... .......... .......... .......... .......... 89% 6.88M 0s\n 15650K .......... .......... .......... .......... .......... 90% 29.7M 0s\n 15700K .......... .......... .......... .......... .......... 90%  123M 0s\n 15750K .......... .......... .......... .......... .......... 90%  118M 0s\n 15800K .......... .......... .......... .......... .......... 90%  123M 0s\n 15850K .......... .......... .......... .......... .......... 91%  102M 0s\n 15900K .......... .......... .......... .......... .......... 91%  122M 0s\n 15950K .......... .......... .......... .......... .......... 91%  125M 0s\n 16000K .......... .......... .......... .......... .......... 92%  126M 0s\n 16050K .......... .......... .......... .......... .......... 92%  116M 0s\n 16100K .......... .......... .......... .......... .......... 92% 5.33M 0s\n 16150K .......... .......... .......... .......... .......... 92% 60.7M 0s\n 16200K .......... .......... .......... .......... .......... 93% 2.43M 0s\n 16250K .......... .......... .......... .......... .......... 93% 52.2M 0s\n 16300K .......... .......... .......... .......... .......... 93% 10.6M 0s\n 16350K .......... .......... .......... .......... .......... 94%  123M 0s\n 16400K .......... .......... .......... .......... .......... 94%  118M 0s\n 16450K .......... .......... .......... .......... .......... 94%  116M 0s\n 16500K .......... .......... .......... .......... .......... 94%  124M 0s\n 16550K .......... .......... .......... .......... .......... 95%  117M 0s\n 16600K .......... .......... .......... .......... .......... 95%  123M 0s\n 16650K .......... .......... .......... .......... .......... 95% 6.55M 0s\n 16700K .......... .......... .......... .......... .......... 96%  119M 0s\n 16750K .......... .......... .......... .......... .......... 96%  125M 0s\n 16800K .......... .......... .......... .......... .......... 96%  123M 0s\n 16850K .......... .......... .......... .......... .......... 96%  117M 0s\n 16900K .......... .......... .......... .......... .......... 97% 6.00M 0s\n 16950K .......... .......... .......... .......... .......... 97%  121M 0s\n 17000K .......... .......... .......... .......... .......... 97%  126M 0s\n 17050K .......... .......... .......... .......... .......... 98%  103M 0s\n 17100K .......... .......... .......... .......... .......... 98%  129M 0s\n 17150K .......... .......... .......... .......... .......... 98%  121M 0s\n 17200K .......... .......... .......... .......... .......... 98%  122M 0s\n 17250K .......... .......... .......... .......... .......... 99%  114M 0s\n 17300K .......... .......... .......... .......... .......... 99% 4.39M 0s\n 17350K .......... .......... .......... .......... .......... 99%  116M 0s\n 17400K .......... .......... .......                         100%  107M=1.8s\n\n2017-04-13 19:29:21 (9.47 MB/s) - 'current-kong.deb' saved [17845684/17845684]\n\nError: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] connection refused\n\n  Run with --v (verbose) or --vv (debug) for more details\n\n\"."
      }
    ]
  }
}
RESOURCEMyAzureKongVM

**Comment by p0pr0ck5** [comment]
Looks like the Azure script hasn't been updated to install Postgres, which is the default data store in Kong now.

**Comment by p0pr0ck5** [comment]
@jiteshBhate would you mind opening an issue with the upstream provider at https://github.com/jdevillard/kong-azure? Thank you!
