### ISSUE TITLE
Kong 0.10 LB (upstream) + consul

### ISSUE THREAD

**Issue by IgorN** [Mashape/kong#2381]
Hi!
Kong version 0.10
I have a small question.
In my project I have some microservices and consol for discover them
For old kong version I could use Nginx + consul in front of my microservises
But now in kong 0.10 LB functionality exist.
But if i want to use kong also how LB i should create upstream and target but i don't want to do (create target) it because i have consul
In config file I have dns_resolve option and i can use it for integration with consul but as a result it will looks like dns load balancing not nginx upstream
How can i use kong with LOB (upstream) with consul?
Maybe someone could give me config example...

Thanks!

**Comment by thibaultcha** [comment]
Hi,

Do you mean that you wish the load balancing part to be done by Nginx, as an `upstream` block would do? If so, that won't be how the integration between Kong and Consul is currently thought. Kong has its own load balancing algorithms built in Lua. If you use Kong and Consul without anything in between, Kong will do some weighted round robin LB, in the Lua-land, based on your Consul DNS records.

**Comment by Tieske** [comment]
0.10 supports 2 loadbalancing methods. DNS based, which works out-of-the-box with Consul, just point your `upstream_url` to hostname that resolves to a Consul SRV record. (you must set Consul as the dns server in that case), Kong will do a weighted round robin on that record.

When using the other method (upstreams and targets), you have to add each service to the list of targets. How you do that is up to you. You could write a script that pulls from Consul and updates Kong upon changes. Or you can do it without Consul, and have each service (on startup) register itself with Kong as a target.

**Comment by IgorN** [comment]
Thanks.

> Do you mean that you wish the load balancing part to be done by Nginx, as an upstream block would do? 
No I don't I want use kong with consul but not like DNS based

> When using the other method (upstreams and targets), you have to add each service to the list of targets. How you do that is up to you. You could write a script that pulls from Consul and updates Kong upon changes. Or you can do it without Consul, and have each service (on startup) register itself with Kong as a target.

Thanks I understand you. If i want the same logic like Nginx upstream + consul I will create some script for integration between consul api and kong api.
 

> point your upstream_url to hostname that resolves to a Consul SRV record. (you must set Consul as the dns server in that case)

Do you mean I should set dns_resolver option?

**Comment by IgorN** [comment]
> 0.10 supports 2 loadbalancing methods. 
But what is the faster method from this 2?
1 more simple as for me
What are pros and cons of this methods?
If we talk about second method (upstream with target) we can set weight but if we have the same microservices we don't need to set weight

**Comment by Tieske** [comment]
@IgorN both methods support weights. The difference is the `ttl` if using consul the `ttl` is the delay you have before updates reach Kong. 

If you have your services register themselves with Kong as a `target`, they will instantly get traffic, no delays. Additionally you might skip having Consul installed at all in that case.

In the future the `upstreams`/`targets` method will get health checks, consistent hashing, etc.

> But what is the faster method from this 2?

that depends if using consul with a `ttl=0` then the upstream/target approach will definitely be faster (assuming you register services by their IP) as it doesn't have to do dns lookups. With higher ttl values, the difference will obviously be smaller to non-existent.

**Comment by Tieske** [comment]
closing due to lack of response
