### ISSUE TITLE
rate-limiting plugin which is unable to reach Redis leads to 500s even if fault_tolerant = true

### ISSUE THREAD

**Issue by ryancutter** [Mashape/kong#2382]
### Summary

rate-limiting plugin with "redis" policy and fault_tolerant = true leads to Internal Server Errors if Redis not accessible.  Works as expected if Redis is accessible.

### Steps To Reproduce

1. Add rate-limiting plugin backed by Redis.  Note fault_tolerant = true.

`
    {
      "consumer_id": "a48fa9b9-db83-4435-81f3-fae9fade79c6",
      "id": "dc4ca24a-e522-44f2-8136-7c657089c0bf",
      "created_at": 1492027775000,
      "enabled": true,
      "name": "rate-limiting",
      "config": {
        "minute": 100000,
        "fault_tolerant": true,
        "redis_host": "cache",
        "policy": "redis",
        "limit_by": "consumer",
        "redis_timeout": 2000,
        "redis_port": 6380
      }
    },`

2. Run application while Redis at defined location (cache:6380) unaccessible.
3. Requests return 500 Internal Server Error with the following in the logs:

`2017/04/12 20:09:38 [debug] 125#0: *677 [lua] base_plugin.lua:17: access():  executing plugin "rate-limiting": access
`
`
2017/04/12 20:09:40 [error] 125#0: *677 [lua] policies.lua:115: usage(): failed to connect to Redis: timeout, client: 172.18.0.1, server: kong, request: "GET /echo HTTP/1.1", host: "localhost"
`
`
2017/04/12 20:09:40 [error] 125#0: *677 lua entry thread aborted: runtime error: ...cal/share/lua/5.1/kong/plugins/rate-limiting/handler.lua:49: attempt to perform arithmetic on local 'current_usage' (a nil value)
stack traceback:
coroutine 0:
	...cal/share/lua/5.1/kong/plugins/rate-limiting/handler.lua: in function 'get_usage'
	...cal/share/lua/5.1/kong/plugins/rate-limiting/handler.lua:80: in function 'access'
	/usr/local/share/lua/5.1/kong.lua:164: in function 'access'
	access_by_lua(nginx.conf:65):2: in function <access_by_lua(nginx.conf:65):1>, client: 172.18.0.1, server: kong, request: "GET /echo HTTP/1.1", host: "localhost"
`

### Additional Details & Logs

- Kong version 0.9.6

**Comment by ryancutter** [comment]
I'm looking at the code in 0.9.6 vs 0.10.0 and it looks like this was an issue that was resolved with 0.10.0.  Will upgrade and let people know if this fixes it.

**Comment by thefosk** [comment]
@ryancutter it should also have been fixed with 0.9.9

**Comment by ryancutter** [comment]
@thefosk works as expected with 0.9.9, thanks!

**Comment by p0pr0ck5** [comment]
Closing this, as it works as expected!
