### ISSUE TITLE
Could Kong just proxy request but not wait for response from proxied servers?

### ISSUE THREAD

**Issue by ShinEDL** [Mashape/kong#2387]
What I need just proxy request, but wait for response make QPS slow.
Looking forward your answer ! thank you !

**Comment by Tieske** [comment]
how would that deal with an error?

**Comment by p0pr0ck5** [comment]
One could write a plugin hat makes an asynchronous HTTP call upstream, ignores the response, and sends a synthetic response downstream. But I doubt any feature like this will ever make it into Kong core ;)

**Comment by ShinEDL** [comment]
@Tieske It does't matter, because our business don't need response. haha...

**Comment by ShinEDL** [comment]
@p0pr0ck5 If it could make into Kong core, that would be so great.

**Comment by thibaultcha** [comment]
@ShinEDL No more plugin will make it into Kong core, sorry! In fact, the current plugins will actually be taken away from the core, and the later will stay lean. 

We will *bundle* a set of default plugins instead :)

**Comment by ShinEDL** [comment]
@thibaultcha Thank for your response.
What I think is if this feature could be implement by Kong? It is useful for some kind of business, such as `time-limited sales on second`.
sorry for my poor English...

**Comment by bungle** [comment]
This could possibly make into a plugins API. Outside of core it is just about requiring `lua-resty-http` and running it in `timer`. It already has the `proxy` function built-in.

**Comment by p0pr0ck5** [comment]
@ShinEDL kong's core functionality is to use nginx's built-in proxying mechanism to proxy the request. as mentioned, short-circuiting this is certainly doable with a plugin, but it doesn't belong in a core proxying framework- indeed, this is what plugins are for! :) we provide a reference at https://getkong.org/docs/0.10.x/plugin-development/ for writing, testing, and deploying your own plugins, and we'd love to hear about your experience writing new plugins for your environment via Gitter, the mailing list, etc. Thanks!
