### ISSUE TITLE
Kong's ssl bidirectional authentication certificate should be used?

### ISSUE THREAD

**Issue by flyabc** [Mashape/kong#2388]
Kong can use two-way ssl certification certificate ? How to use it
1.Use openssl to generate a custom ssl certificate, the server certificate, the client certificate,
Generated certificate files included
    ca.crt;   ca.key;  server.crt;    server.key   client.crt;   client.key
2.Add a server certificate:
curl -i -X POST localhost:8001/certificates
-F 'cert=@/usr/ssl/myssl/server.crt' \
-F 'cert=@/usr/ssl/myssl/server.key' \
-F 'snis=web.com'
3.Test one-way certification:  curl -k -v https://localhost:8443 -H 'host:web2.com'
HTTP/1.1 200 OK
But how can two-way certification?

- Kong version 0.10.1

**Comment by Tieske** [comment]
something like https://github.com/Mashape/kong/issues/2048 ?

**Comment by flyabc** [comment]
@Tieske thank you! I have read the contents of #2048 ，but I can not find some of the corresponding parameters or plug-in kong ，such as : **ssl-auth** plugin，The **client_certificate** parameter of certificates ，the **verify_clien** and **vertify-depth** parameter of apis. My kong version is 0.10.1，Do you have any other way?

**Comment by p0pr0ck5** [comment]
Closing this as a dup of #2048. @flyabc the above issue is not a native solution in Kong, but is a feature request and discussion about a community implementation that fits your needs. Since you're communicating with OP on that thread, I'll close this out now. Thanks!
