### ISSUE TITLE
suggestion:add a enable property to api and consumers

### ISSUE THREAD

**Issue by workcheng** [Mashape/kong#2392]
希望给api和消费者添加一个是否启用的属性，如果启用，说明可以通过kong访问；如果没有启用它，就不能通过kong访问。这样当你暂时不需要一个api的时候，就可以通过禁用来设置，而不是直接删掉，这样可以方便管理。

**Comment by thibaultcha** [comment]
Hi,

Yes, this is an already debated topic in multiple places. See #1725, #1837, and #1279. There is also the new request-termination plugin that takes care of this in #2051.

Also, sorry, but none of us speak chinese here :)
