### ISSUE TITLE
Ring-balancer helloworld test

### ISSUE THREAD

**Issue by toby2** [Mashape/kong#2398]
i try to test Ring-balancer function in my mac. 
it doesn't work, all request on one node, never balance request to other node.
maybe somewhere i misunderstand. could anybody give me some help? thanks a lot!

prerequisite:
os:      mac 10.12
kong : 0.10.1
api1： http://localhost:8555
api2： http://localhost:8556
kong admin:   http://localhost:8001
Kong listens for traffic:  http://localhost:8000

### Steps To Reproduce
1. api.toby.local which config in /etc/hosts file .  api information from admin api(http://localhost:8001/apis):

{
  "http_if_terminated": true,
  "id": "f7ea38a5-b3c8-47e9-8e16-0ecf573c60e9",
  "retries": 5,
  "preserve_host": false,
  "created_at": 1492358745000,
  "upstream_connect_timeout": 60000,
  "upstream_url": "http://api.toby.local:8885",
  "upstream_read_timeout": 60000,
  "upstream_send_timeout": 60000,
  "https_only": false,
  "strip_uri": true,
  "uris": [
    "/"
  ],
  "name": "kongtest",
  "hosts": [
    "localapi"
  ]
}

2.upstream information form admin api(http://localhost:8001/upstreams/):

{
  "data": [
    {
      "orderlist": [
        54,
        51,
        64,
        95,
        90,
        48,
        50,
        57,
        20,
        39,
        91,
        35,
        49,
        75,
        40,
        7,
        41,
        26,
        16,
        27,
        5,
        29,
        3,
        55,
        88,
        94,
        100,
        38,
        89,
        65,
        53,
        6,
        69,
        78,
        62,
        98,
        17,
        96,
        23,
        34,
        99,
        14,
        86,
        12,
        97,
        76,
        84,
        42,
        58,
        85,
        67,
        79,
        73,
        32,
        18,
        83,
        56,
        31,
        8,
        36,
        10,
        46,
        63,
        43,
        87,
        60,
        37,
        1,
        30,
        72,
        68,
        74,
        45,
        4,
        25,
        19,
        93,
        28,
        70,
        15,
        82,
        9,
        21,
        80,
        11,
        61,
        24,
        33,
        13,
        22,
        92,
        52,
        47,
        2,
        59,
        81,
        66,
        77,
        71,
        44
      ],
      "slots": 100,
      "id": "c27635a3-f917-4de3-8443-67e3dd054163",
      "name": "kongtest",
      "created_at": 1492343090730
    }
  ],
  "total": 1
}

3.targets information from admin api(http://localhost:8001/upstreams/kongtest/targets): 

{
  "data": [
    {
      "weight": 100,
      "id": "6699ad79-b25e-4ccd-8a8d-070eb09cb602",
      "target": "localhost:8885",
      "created_at": 1492352515179,
      "upstream_id": "c27635a3-f917-4de3-8443-67e3dd054163"
    },
    {
      "weight": 100,
      "id": "ca045cf3-1260-4323-98ad-bf0bd12c264c",
      "target": "localhost:8886",
      "created_at": 1492352520806,
      "upstream_id": "c27635a3-f917-4de3-8443-67e3dd054163"
    }
  ],
  "total": 2
}

4. access api .

curl -i -X GET --url http://localhost:8000/ --header 'Host: localapi'
HTTP/1.1 200 
Date: Sun, 16 Apr 2017 16:16:57 GMT
Content-Type: text/plain;charset=UTF-8
Content-Length: 12
Connection: keep-alive
X-Kong-Upstream-Latency: 3
X-Kong-Proxy-Latency: 10004
Via: kong/0.10.1

**Comment by toby2** [comment]
also find other issue,  list targets api could not work. :

 curl -i -X GET --url http://localhost:8000/upstreams/testkong/targets/active
HTTP/1.1 405 Not Allowed
Date: Mon, 17 Apr 2017 08:07:31 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Server: kong/0.10.1

{"message":"Method not allowed"}

**Comment by toby2** [comment]
simply change upstream url from http://api.toby.local:8885 to http://kongtest,  balancer functionality could work well.

**Comment by thefosk** [comment]
> curl -i -X GET --url http://localhost:8000/upstreams/testkong/targets/active

You need to use the Admin API which by default is on port `8001`.

**Comment by p0pr0ck5** [comment]
@toby2 the `name` field of the upstream object must match that of the `upstream_url` of the associated API. Have a read over the following docs:

https://getkong.org/docs/0.10.x/admin-api/#upstream-object
https://getkong.org/docs/0.10.x/loadbalancing/#ring-balancer

When the `upstream_url` doesn't match a given `upstream` object, it attempts to resolve the `upstream_url` directly, which explains the behavior you've described. Thanks!

**Comment by toby2** [comment]
@thefosk thanks for reply. I attached incorrect url before. actually  list targets api still could not work.

curl -i -X GET --url http://localhost:8001/upstreams/testkong/targets/active
HTTP/1.1 405 Not Allowed
Date: Tue, 18 Apr 2017 01:00:03 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Server: kong/0.10.1

{"message":"Method not allowed"}

**Comment by Tieske** [comment]
@toby2 iirc that endpoint 'active' wasn't yet added in 0.10.1 and the initial implementation had a bug that required a trailing `/`

**Comment by toby2** [comment]
@Tieske  tricky trailing ~
