### ISSUE TITLE
installation from source: missing dependency: luasec, libpcre3-dev

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#24]
#### luasec

failed at:

```shell
Error: Failed installing dependency: http://luarocks.org/repositories/rocks/busted-2.0.rc6-0.rockspec - Failed installing dependency: http://luarocks.org/repositories/rocks/mediator_lua-1.1-3.rockspec - Error fetching file: Failed downloading https://github.com/Olivine-Labs/mediator_lua/archive/v1.1.tar.gz - Unsupported protocol - install luasec to get HTTPS support.
```

attempting to install with:

```shell
sudo luarocks install luasec
```

results in the following error:

```shell
Error: Could not find expected file libssl.a, or libssl.so, or libssl.so.* for OPENSSL -- you may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_LIBDIR to the luarocks command. Example: luarocks install luasec OPENSSL_DIR=/usr/local
```

this is resolved with:

```shell
sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/`gcc -print-multiarch`
```

#### libpcre3-dev

failed at:

```shell
Error: Failed installing dependency: http://luarocks.org/repositories/rocks/lrexlib-pcre-2.7.2-1.src.rock - Could not find expected file pcre.h for PCRE -- you may have to install PCRE in your system and/or pass PCRE_DIR or PCRE_INCDIR to the luarocks command. Example: luarocks install lrexlib-pcre PCRE_DIR=/usr/local
```

this is resolved with:

```shell
sudo apt-get install libpcre3-dev
```

**Comment by thefosk** [comment]
@ahmadnassri On MacOSX ?

**Comment by ahmadnassri** [comment]
@thefosk no Linux!

**Comment by ahmadnassri** [comment]
you know ... as in where this will run in the real world.

**Comment by Nijikokun** [comment]
What is the Linux Distro and Version are you doing this on?

**Comment by ahmadnassri** [comment]
Linux Mint 17.1

**Comment by thefosk** [comment]
I've updated the dependencies list in the README file. We require also `pcre-devel` and `openssl-devel` to successfully build the project.

**Comment by thibaultCha** [comment]
They have been added to the README but not all platforms need it. We need a different approach:

### Install

#### Linux

#### OS X

etc...

**Comment by thefosk** [comment]
We need something that can automatically install dependencies. Once Kong is being released in `rpm` or `deb` format it's going to be easier to install everything since the installation package will also automatically install the dependencies.

I'm pretty sure the README dependencies list is not complete too.

**Comment by thibaultCha** [comment]
We need to install dependencies only if those are not built-in in the system we are installing it in. In OS X, no need to install those libs. In debian, need to install them through `apt-get`, in CentOS, probably with `yum`, etc...

**Comment by thefosk** [comment]
By using a package manager if the dependencies are already installed they won't be reinstalled.

**Comment by thibaultCha** [comment]
How do you know which package manager to use? How do you know if the dependency is not already install for this platform? 

We need to just specify platform-specific installation processes. Like... Everybody else in the world.

**Comment by thibaultCha** [comment]
Installation from source with OS X + Homebrew is now entirely documented: ddfc482

**Comment by thibaultCha** [comment]
We now know what is needed to install kong, and we will update our `INSTALL.md` with missing platforms.
