### ISSUE TITLE
Always need to restart the data update

### ISSUE THREAD

**Issue by koyuhau** [Mashape/kong#2406]
I write a custom plug-in, when I use the PATCH to update the CONFIG parameter, found that the data is modified, but must restart to take effect.
So, don't can restart?

**Comment by p0pr0ck5** [comment]
@koyuhau we will need much more detail to understand your situation. But, a GitHub issue may not be the most appropriate vehicle for this; you may find more success working with plugin developers on the [mailing list](https://groups.google.com/forum/#!forum/konglayer) or on [Gitter](https://gitter.im/Mashape/kong).

**Comment by koyuhau** [comment]
I may have found the cause of the problem, it may be because I didn't set the hooks file, the cause of the cache didn't update in time.Thank you for your help

**Comment by thefosk** [comment]
If you are using the cache, you will always have to implement a `hooks.lua` file to invalidate that cache on an invalidation event.
