### ISSUE TITLE
Kong: Requested URL return 204 instead of 200

### ISSUE THREAD

**Issue by Bl4ckM** [Mashape/kong#241]
Hi,
i try to forward all request from my client to my tomcat/http backend at 8081. I try to migrate kong into my project. ~~If i POST a request to auth myself, i should get 200 with content-length:0 but i 'll get a 204 no content back~~. My POSTs pass through, but my Options went back with 204. I think it could be something wrong with your nginx.conf and your proxy_ settings. Any Ideas how to forward my requests to my api and get my originall 200 code instead of 204?

P.S: All went right @ access.log / error.log no problems at all.

Kong_proxy: running @ 8080
admin: running @ 8001

my restapp is deployed under:
http://localhost:8081/app
for requests:
http://localhost:8081/app/*

P.S2: Found and fix something, only Options get now 204, Posts get 200... Any Ideas?

api_config:

``` json
{
    "data": [
        {
            "public_dns": "localhost:8080",
            "id": "apikey",
            "target_url": "http://localhost:8081/",
            "name": "auth",
            "created_at": 1431682247000
        }
    ]
}
```

Plugin_config:

``` json
{
    "data": [
        {
            "api_id": "apikey",
            "id": "apikey",
            "value": {},
            "enabled": true,
            "name": "filelog",
            "created_at": 1431684868000
        },
        {
            "api_id": "apikey",
            "id": "apikey",
            "value": {
                "methods": "GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, PATCH",
                "credentials": true,
                "exposed_headers": "Options,X-Auth-Token,Content-Type,Authorization,Accept,Accept-Version,Content-Length,Content-MD5,Date",
                "origin": "*",
                "preflight_continue": false,
                "headers": "Content-Type,X-Auth-Token,Authorization,Accept,Accept-Version,Content-Length,Content-MD5,Date,Options"
            },
            "enabled": true,
            "name": "cors",
            "created_at": 1431684414000
        }
    ]
}
```

normal Server-Return Header:

```
Accept: */*
Access-Control-Allow-Headers: Content-Type,X-Auth-Token,Authorization
Access-Control-Allow-Methods: POST, PUT, GET, OPTIONS, DELETE
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3600
Allow: GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, PATCH
Content-Length: 0
Date: Fri, 15 May 2015 10:39:31 GMT
Server: Apache-Coyote/1.1
access-control-allow-credentials: true
```

Return Header with Kong-enabled:

```
Access-Control-Allow-Headers: Content-Type,X-Auth-Token,Authorization,Accept,Accept-Version,Content-Length,Content-MD5,Date,Options
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, PATCH
Access-Control-Allow-Origin: localhost
Connection: keep-alive
Date: Fri, 15 May 2015 10:30:48 GMT
Server: kong/0.2.1
Vary: Origin
Via: kong/0.2.1
access-control-allow-credentials: true
```

**Comment by thibaultCha** [comment]
I see your config `preflight_continue` is set to false. By reading the code we can see the request is not being proxied but directly replies when this is set to false: https://github.com/Mashape/kong/blob/master/kong/plugins/cors/access.lua#L62

It is missing from the plugin's documentation but I guess you should set it to true if you want to preflight request to be proxied.

**Comment by thibaultCha** [comment]
Even tho because of #203, I don't think the preflight requests can really be proxied, I will test this.

**Comment by UnknownBird** [comment]
AngularJS acts that way, before calling POST, OPTIONS is called, if one isn't successfull, Promise fails and turns into error state. My Post (200) went through, the OPTIONS request fails with 204 (no content).

**Comment by Bl4ckM** [comment]
Even with preflight_true i'll get only OPTIONS my post won't be sent through Kong..

**Comment by p0pr0ck5** [comment]
My guess is this issue is so old there's nothing to be done here?
