### ISSUE TITLE
kong 0.8.3 -->0.9.7-->0.10.1 Upgrade problem

### ISSUE THREAD

**Issue by xulongju** [Mashape/kong#2413]
Has been upgraded from version 0.8.3 to version 0.9.7. Now need to upgrade from 0.9.7 to 0.10.1, the following error, the previous solution is invalid.
error.log:
migrating core for database kong
core migrated up to: 2016-09-05-212515_retries
core migrated up to: 2016-09-16-141423_upstreams
core migrated up to: 2016-12-14-172100_move_ssl_certs_to_core
core migrated up to: 2016-11-11-151900_new_apis_router_1
core migrated up to: 2016-11-11-151900_new_apis_router_2
core migrated up to: 2016-11-11-151900_new_apis_router_3
core migrated up to: 2016-01-25-103600_unique_custom_id
core migrated up to: 2017-01-24-132600_upstream_timeouts
core migrated up to: 2017-01-24-132600_upstream_timeouts_2
migrating cors for database kong
cors migrated up to: 2017-03-14_multiple_orgins
migrating oauth2 for database kong
oauth2 migrated up to: 2016-12-22-283949_serialize_redirect_uri
oauth2 migrated up to: 2016-09-19-oauth2_api_id
oauth2 migrated up to: 2016-12-15-set_global_credentials
migrating basic-auth for database kong
basic-auth migrated up to: 2017-01-25-180400_unique_username
14 migrations ran
Error: ...bsuite/openresty/luajit/share/lua/5.1/kong/cmd/start.lua:23: nginx: [error] init_by_lua error: /opt/websuite/openresty/luajit/share/lua/5.1/kong.lua:134: [postgres error] Error during migration 2016-09-19-oauth2_api_id: ERROR: column "api_id" of relation "oauth2_authorization_codes" already exists
stack traceback:
        [C]: in function 'assert'
        /opt/websuite/openresty/luajit/share/lua/5.1/kong.lua:134: in function 'init'
        init_by_lua:4: in main chunk

  Run with --v (verbose) or --vv (debug) for more details

**Comment by p0pr0ck5** [comment]
@xulongju are you able to work around this by manually removing the `oauth2_authorization_codes <-> api_id` relationship and re-running the migration?

**Comment by p0pr0ck5** [comment]
@xulongju any update?

**Comment by p0pr0ck5** [comment]
Closing as stale after no update. Feel free to re-open if there are still unanswered questions.
