### ISSUE TITLE
Update 0.10 metrics documentation to list upstream_latency

### ISSUE THREAD

**Issue by mgiorgio** [Mashape/kong#2416]
### Summary

upstream_latency is a metric that is currently being sent by the logging plugins but such metric isn't listed in the documentation. See https://getkong.org/plugins/statsd/#metrics.

**Comment by coopr** [comment]
Hi @mgiorgio - please open an issue on that website's repo https://github.com/Mashape/getkong.org/issues or make a PR to improve the relevant pages, like https://github.com/Mashape/getkong.org/blob/master/app/plugins/statsd.md - thanks!
