### ISSUE TITLE
Metric missing in Statsd plugin documentation

### ISSUE THREAD

**Issue by ivanpondal** [Mashape/kong#2417]
### Summary

The 'upstream_latency' metric is not being listed in the plugin's documentation (https://getkong.org/plugins/statsd/).

**Comment by p0pr0ck5** [comment]
Hi @ivanpondal  - please open an issue on that website's repo https://github.com/Mashape/getkong.org/issues or make a PR to improve the relevant pages, like https://github.com/Mashape/getkong.org/blob/master/app/plugins/statsd.md - thanks!

**Comment by shashiranjan84** [comment]
@ivanpondal we made some changes in plugin wand planning to release it in next major release. Doc will also updated with the new metrics `upstream_latency`

**Comment by ivanpondal** [comment]
cool, thanks for the quick reply!
