### ISSUE TITLE
kong cannot start with error

### ISSUE THREAD

**Issue by workcheng** [Mashape/kong#2423]
### Summary

kong cannot start

### Steps To Reproduce

1.cassandra start
2.kong start
3.vagrant@precise64:~$ kong start
migrating core for keyspace kong
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [cassandra error] Error during migration 2016-12-14-172100_move_ssl_certs_to_core: [Already exists] Cannot add already existing table "ssl_certificates" to keyspace "kong"

  Run with --v (verbose) or --vv (debug) for more details

### Additional Details & Logs

- Kong version (`$ kong version`)
0.10.1
- Kong debug-level startup logs (`$ kong start --vv`)
vagrant@precise64:~$ kong start --vv
2017/04/20 06:32:27 [verbose] Kong: 0.10.1
2017/04/20 06:32:27 [debug] ngx_lua: 10007
2017/04/20 06:32:27 [debug] nginx: 1011002
2017/04/20 06:32:27 [debug] Lua: LuaJIT 2.1.0-beta2
2017/04/20 06:32:27 [verbose] reading config file at /etc/kong/kong.conf
2017/04/20 06:32:27 [debug] admin_listen = "0.0.0.0:8001"
2017/04/20 06:32:27 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/04/20 06:32:27 [debug] admin_ssl = true
2017/04/20 06:32:27 [debug] anonymous_reports = true
2017/04/20 06:32:27 [debug] cassandra_consistency = "ONE"
2017/04/20 06:32:27 [debug] cassandra_contact_points = {"10.0.1.144"}
2017/04/20 06:32:27 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/04/20 06:32:27 [debug] cassandra_keyspace = "kong"
2017/04/20 06:32:27 [debug] cassandra_lb_policy = "RoundRobin"
2017/04/20 06:32:27 [debug] cassandra_port = 9042
2017/04/20 06:32:27 [debug] cassandra_repl_factor = 1
2017/04/20 06:32:27 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/04/20 06:32:27 [debug] cassandra_ssl = false
2017/04/20 06:32:27 [debug] cassandra_ssl_verify = false
2017/04/20 06:32:27 [debug] cassandra_timeout = 5000
2017/04/20 06:32:27 [debug] cassandra_username = "kong"
2017/04/20 06:32:27 [debug] cluster_listen = "10.0.1.128:7946"
2017/04/20 06:32:27 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/04/20 06:32:27 [debug] cluster_profile = "wan"
2017/04/20 06:32:27 [debug] cluster_ttl_on_failure = 3600
2017/04/20 06:32:27 [debug] custom_plugins = {}
2017/04/20 06:32:27 [debug] database = "cassandra"
2017/04/20 06:32:27 [debug] dns_hostsfile = "/etc/hosts"
2017/04/20 06:32:27 [debug] dns_resolver = {}
2017/04/20 06:32:27 [debug] log_level = "notice"
2017/04/20 06:32:27 [debug] lua_code_cache = "on"
2017/04/20 06:32:27 [debug] lua_package_cpath = ""
2017/04/20 06:32:27 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/04/20 06:32:27 [debug] lua_socket_pool_size = 30
2017/04/20 06:32:27 [debug] lua_ssl_verify_depth = 1
2017/04/20 06:32:27 [debug] mem_cache_size = "128m"
2017/04/20 06:32:27 [debug] nginx_daemon = "on"
2017/04/20 06:32:27 [debug] nginx_optimizations = true
2017/04/20 06:32:27 [debug] nginx_worker_processes = "auto"
2017/04/20 06:32:27 [debug] pg_database = "kong"
2017/04/20 06:32:27 [debug] pg_host = "127.0.0.1"
2017/04/20 06:32:27 [debug] pg_port = 5432
2017/04/20 06:32:27 [debug] pg_ssl = false
2017/04/20 06:32:27 [debug] pg_ssl_verify = false
2017/04/20 06:32:27 [debug] pg_user = "kong"
2017/04/20 06:32:27 [debug] prefix = "/usr/local/kong/"
2017/04/20 06:32:27 [debug] proxy_listen = "0.0.0.0:8000"
2017/04/20 06:32:27 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2017/04/20 06:32:27 [debug] serf_path = "serf"
2017/04/20 06:32:27 [debug] ssl = true
2017/04/20 06:32:27 [debug] upstream_keepalive = 60
2017/04/20 06:32:27 [verbose] prefix in use: /usr/local/kong
2017/04/20 06:32:27 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/04/20 06:32:27 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2017/04/20 06:32:27 [debug] searching for OpenResty 'resty' executable
2017/04/20 06:32:28 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.2'
2017/04/20 06:32:28 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2017/04/20 06:32:28 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2017/04/20 06:32:28 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/04/20 06:32:28 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2017/04/20 06:32:28 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2017/04/20 06:32:28 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2017/04/20 06:32:28 [verbose] running datastore migrations
2017/04/20 06:32:28 [info] migrating core for keyspace kong
2017/04/20 06:32:28 [verbose] could not start Kong, stopping services
2017/04/20 06:32:28 [verbose] leaving serf cluster
2017/04/20 06:32:28 [verbose] left serf cluster
2017/04/20 06:32:28 [verbose] stopping serf agent at /usr/local/kong/pids/serf.pid
2017/04/20 06:32:28 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/04/20 06:32:28 [debug] no pid file at: /usr/local/kong/pids/serf.pid
2017/04/20 06:32:28 [verbose] serf agent stopped
2017/04/20 06:32:28 [verbose] stopped services
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [cassandra error] Error during migration 2016-12-14-172100_move_ssl_certs_to_core: [Already exists] Cannot add already existing table "ssl_certificates" to keyspace "kong"
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:5: in function 'file_gen'
        init_worker_by_lua:38: in function <init_worker_by_lua:36>
        [C]: in function 'pcall'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>

**Comment by thefosk** [comment]
Seem like the keyspace is in an inconsistent state - we recommend executing Cassandra migrations from one node only, avoiding having multiple nodes doing migrations at the same time.

**Comment by thibaultcha** [comment]
This should be fixed with 0.10.1 and the upcoming 0.10.2. In any case, make sure you are *always* running your migrations from a *single* node. No 2 nodes can start at the same time on a fresh Cassandra keyspace.
