### ISSUE TITLE
Kong remains stuck at dnsmasq when using persistence storage for mongo

### ISSUE THREAD

**Issue by ksachdev1** [Mashape/kong#2426]
### Summary
I have a docker swarm cluster on which a single instance of Kong is deployed in a container and  a single instance of postgres is deployed as a container. It works fine if my postgres does not write to a container volume. In short, everytime I delete the docker service stack and start, there is nothing in the DB left, this works fine. However, when I let postgres presist data across reloads of service, when I deploy kong, it remains stuck at dnsmasq as per the logs. It never proceeds. Hiere the end part of the log. I am on kong kong:0.9.9
2017/04/20 14:36:37 [verbose] generating default SSL certificate and key
2017/04/20 14:36:41 [verbose] running datastore migrations
2017/04/20 14:36:41 [verbose] migrations up to date
2017/04/20 14:36:41 [verbose] dnsmasq not running, deleting /usr/local/kong/pids/dnsmasq.pid
2017/04/20 14:36:41 [debug] searching for 'dnsmasq' executable
2017/04/20 14:36:41 [debug] /usr/local/sbin/dnsmasq -v: ''
2017/04/20 14:36:41 [debug] 'dnsmasq' executable not found at /usr/local/sbin/dnsmasq
2017/04/20 14:36:41 [debug] /usr/local/bin/dnsmasq -v: ''
SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by p0pr0ck5** [comment]
Any way to upgrade  to 0.10, where dnsmasq is no longer necessary?

**Comment by ksachdev1** [comment]
Thanks @p0pr0ck5 
At this point we would prefer to stick with this version of Kong as we had few other issues with 0.10. Are you suggesting that this problem can happen on the version we are using? Is there a way around it?

**Comment by thefosk** [comment]
@ksachdev1 is that the full log? Also I'd like to hear about those other issues in 0.10.0.

**Comment by ksachdev1** [comment]
@thefosk , i am pasting the full log, our container waits for little over a minute after which the container shuts down, i can wait for longer, but after a minute long wait the log is as follows:
+ kong start -vv
2017/04/20 14:36:37 [verbose] Kong: 0.9.9
2017/04/20 14:36:37 [debug] ngx_lua: 10006
2017/04/20 14:36:37 [debug] nginx: 1011002
2017/04/20 14:36:37 [debug] Lua: LuaJIT 2.1.0-beta2
2017/04/20 14:36:37 [debug] PRNG seed: 102301461851
2017/04/20 14:36:37 [verbose] no config file found at /etc/kong.conf
2017/04/20 14:36:37 [verbose] no config file found at /etc/kong/kong.conf
2017/04/20 14:36:37 [verbose] no config file, skipping loading
2017/04/20 14:36:37 [debug] KONG_PG_HOST ENV found with "kongdb"
2017/04/20 14:36:37 [debug] KONG_NGINX_DAEMON ENV found with "off"
2017/04/20 14:36:37 [debug] admin_listen = "0.0.0.0:8001"
2017/04/20 14:36:37 [debug] anonymous_reports = true
2017/04/20 14:36:37 [debug] cassandra_consistency = "ONE"
2017/04/20 14:36:37 [debug] cassandra_contact_points = {"127.0.0.1"}
2017/04/20 14:36:37 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/04/20 14:36:37 [debug] cassandra_keyspace = "kong"
2017/04/20 14:36:37 [debug] cassandra_port = 9042
2017/04/20 14:36:37 [debug] cassandra_repl_factor = 1
2017/04/20 14:36:37 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/04/20 14:36:37 [debug] cassandra_ssl = false
2017/04/20 14:36:37 [debug] cassandra_ssl_verify = false
2017/04/20 14:36:37 [debug] cassandra_timeout = 5000
2017/04/20 14:36:37 [debug] cassandra_username = "kong"
2017/04/20 14:36:37 [debug] cluster_listen = "0.0.0.0:7946"
2017/04/20 14:36:37 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/04/20 14:36:37 [debug] cluster_profile = "wan"
2017/04/20 14:36:37 [debug] cluster_ttl_on_failure = 3600
2017/04/20 14:36:37 [debug] custom_plugins = {}
2017/04/20 14:36:37 [debug] database = "postgres"
2017/04/20 14:36:37 [debug] dnsmasq = true
2017/04/20 14:36:37 [debug] dnsmasq_port = 8053
2017/04/20 14:36:37 [debug] log_level = "notice"
2017/04/20 14:36:37 [debug] lua_code_cache = "on"
2017/04/20 14:36:37 [debug] lua_package_cpath = ""
2017/04/20 14:36:37 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/04/20 14:36:37 [debug] lua_ssl_verify_depth = 1
2017/04/20 14:36:37 [debug] mem_cache_size = "128m"
2017/04/20 14:36:37 [debug] nginx_daemon = "off"
2017/04/20 14:36:37 [debug] nginx_optimizations = true
2017/04/20 14:36:37 [debug] nginx_worker_processes = "auto"
2017/04/20 14:36:37 [debug] pg_database = "kong"
2017/04/20 14:36:37 [debug] pg_host = "kongdb"
2017/04/20 14:36:37 [debug] pg_port = 5432
2017/04/20 14:36:37 [debug] pg_ssl = false
2017/04/20 14:36:37 [debug] pg_ssl_verify = false
2017/04/20 14:36:37 [debug] pg_user = "kong"
2017/04/20 14:36:37 [debug] prefix = "/usr/local/kong/"
2017/04/20 14:36:37 [debug] proxy_listen = "0.0.0.0:8000"
2017/04/20 14:36:37 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2017/04/20 14:36:37 [debug] serf_path = "serf"
2017/04/20 14:36:37 [debug] ssl = true
2017/04/20 14:36:37 [verbose] prefix in use: /usr/local/kong
2017/04/20 14:36:37 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/04/20 14:36:37 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2017/04/20 14:36:37 [debug] searching for OpenResty 'resty' executable
2017/04/20 14:36:37 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.1'
2017/04/20 14:36:37 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2017/04/20 14:36:37 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2017/04/20 14:36:37 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/04/20 14:36:37 [verbose] generating default SSL certificate and key
2017/04/20 14:36:41 [verbose] running datastore migrations
2017/04/20 14:36:41 [verbose] migrations up to date
2017/04/20 14:36:41 [verbose] dnsmasq not running, deleting /usr/local/kong/pids/dnsmasq.pid
2017/04/20 14:36:41 [debug] searching for 'dnsmasq' executable
2017/04/20 14:36:41 [debug] /usr/local/sbin/dnsmasq -v: ''
2017/04/20 14:36:41 [debug] 'dnsmasq' executable not found at /usr/local/sbin/dnsmasq
2017/04/20 14:36:41 [debug] /usr/local/bin/dnsmasq -v: ''

**Comment by ksachdev1** [comment]
@thefosk , for 0.10.0 issues and logs, here is where the issue was reported and opened and we are facing it so we moved to lower version
https://github.com/Mashape/kong/issues/2360

**Comment by p0pr0ck5** [comment]
Kong 0.9 is far out of data (we have just release an RC for 0.11); migrating is 0.10 or 0.11 should be on your roadmap in the future.

This sounds like an issue with the local dnsmasq bin execution, but for obvious reasons isn't an issue going forward.

**Comment by thefosk** [comment]
dnsmasq has been removed since 0.10 - we recommend to upgrade, closing this issue. Please feel free to comment again on #2360 if it's still a blocker for you.
