### ISSUE TITLE
Kong cluster

### ISSUE THREAD

**Issue by ginnavaram** [Mashape/kong#2427]
### Summary
Will machines set up as a kong cluster distribute load equally? Is there any way to configure the load distribution?
SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by p0pr0ck5** [comment]
Hi,

You will need to configure a load balancer in front of your Kong cluster to distribute the load for you. Each cluster node runs on a unique IP address (for obvious reasons), so the network architecture downstream will be responsible for forwarding traffic to the cluster.

BTW, this sort of question really belongs on [Gitter](https://gitter.im/Mashape/kong) or the [mailing list](https://groups.google.com/forum/#!forum/konglayer). GitHub issues should be used for issues, following the template made available :)

**Comment by ginnavaram** [comment]
Thanks for the reply. Will use mailing lists or gitter in the future. Thanks though.
