### ISSUE TITLE
rate-limiting  consumer_id is an unknown field

### ISSUE THREAD

**Issue by JoshuaAndrew** [Mashape/kong#2431]
### Summary
rate-limiting  plugin 

The CONSUMER ID that this plugin configuration will target. This value can only be used if authentication has been enabled so that the system can identify the user making the request.

config.consumer_id": "consumer_id is an unknown field"  ???

why  consumer_id is an unknown field?

SUMMARY_GOES_HERE

### Steps To Reproduce

[joshua@joshua ~]$ curl  -X POST \
    --url http://localhost:8001/apis/ \
    --data 'name=example-api' \
    --data 'hosts=example.com' \
    --data 'upstream_url=http://httpbin.org'

[joshua@joshua ~]$ curl -X POST http://localhost:8001/apis/example-api/plugins \
--data "name=basic-auth" \
--data "config.hide_credentials=true"

[joshua@joshua ~]$  curl -XPOST -i   -d "username=weiwei&custom_id=1" http://localhost:8001/consumers

[joshua@joshua ~]$ curl -X POST http://localhost:8001/consumers/{consumer}/basic-auth  \ 
    --data "username=Aladdin" \ 
    --data "password=OpenSesame"

[joshua@joshua ~]$ curl -XGET http://localhost:8000/ip -H 'Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l' -H 'Host: example.com' | jq .
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 43 100 43 0 0 20 0 0:00:02 0:00:02 --:--:-- 20
{
"origin": "10.0.2.2, 124.205.110.50"
}

[joshua@joshua ~]$ curl  -X POST \
>   --url http://localhost:8001/apis/example-api/plugins/ \
>   --data 'name=rate-limiting'  \
>   --data "config.minute=3"     \
>   --data "config.consumer_id=295cf1d9-739b-4e7c-b87d-73d083835741" \
>   --data "config.limit_by=consumer"\
>   --data "config.policy=cluster" |jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194    0    57  100   137  18322  44037 --:--:-- --:--:-- --:--:-- 45666
{
  **"config.consumer_id": "consumer_id is an unknown field"**
}

### Additional Details & Logs

- Kong version (`$ kong version`)
  vagrant@precise64:/kong$ bin/kong version
  0.10.1
- Kong debug-level startup logs (`$ kong start --vv`)

vagrant@precise64:/kong$ bin/kong start --vv
2017/04/21 11:37:10 [verbose] Kong: 0.10.1
2017/04/21 11:37:10 [debug] ngx_lua: 10007
2017/04/21 11:37:10 [debug] nginx: 1011002
2017/04/21 11:37:10 [debug] Lua: LuaJIT 2.1.0-beta2
2017/04/21 11:37:10 [verbose] no config file found at /etc/kong/kong.conf
2017/04/21 11:37:10 [verbose] no config file found at /etc/kong.conf
2017/04/21 11:37:10 [verbose] no config file, skipping loading
2017/04/21 11:37:10 [debug] KONG_CUSTOM_PLUGINS ENV found with "qps"
2017/04/21 11:37:10 [debug] admin_listen = "0.0.0.0:8001"
2017/04/21 11:37:10 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/04/21 11:37:10 [debug] admin_ssl = true
2017/04/21 11:37:10 [debug] anonymous_reports = true
2017/04/21 11:37:10 [debug] cassandra_consistency = "ONE"
2017/04/21 11:37:10 [debug] cassandra_contact_points = {"127.0.0.1"}
2017/04/21 11:37:10 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/04/21 11:37:10 [debug] cassandra_keyspace = "kong"
2017/04/21 11:37:10 [debug] cassandra_lb_policy = "RoundRobin"
2017/04/21 11:37:10 [debug] cassandra_port = 9042
2017/04/21 11:37:10 [debug] cassandra_repl_factor = 1
2017/04/21 11:37:10 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/04/21 11:37:10 [debug] cassandra_ssl = false
2017/04/21 11:37:10 [debug] cassandra_ssl_verify = false
2017/04/21 11:37:10 [debug] cassandra_timeout = 5000
2017/04/21 11:37:10 [debug] cassandra_username = "kong"
2017/04/21 11:37:10 [debug] cluster_listen = "0.0.0.0:7946"
2017/04/21 11:37:10 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/04/21 11:37:10 [debug] cluster_profile = "wan"
2017/04/21 11:37:10 [debug] cluster_ttl_on_failure = 3600
2017/04/21 11:37:10 [debug] custom_plugins = {"qps"}
2017/04/21 11:37:10 [debug] database = "postgres"
2017/04/21 11:37:10 [debug] dns_hostsfile = "/etc/hosts"
2017/04/21 11:37:10 [debug] dns_resolver = {}
2017/04/21 11:37:10 [debug] log_level = "notice"
2017/04/21 11:37:10 [debug] lua_code_cache = "on"
2017/04/21 11:37:10 [debug] lua_package_cpath = ""
2017/04/21 11:37:10 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/04/21 11:37:10 [debug] lua_socket_pool_size = 30
2017/04/21 11:37:10 [debug] lua_ssl_verify_depth = 1
2017/04/21 11:37:10 [debug] mem_cache_size = "128m"
2017/04/21 11:37:10 [debug] nginx_daemon = "on"
2017/04/21 11:37:10 [debug] nginx_optimizations = true
2017/04/21 11:37:10 [debug] nginx_worker_processes = "auto"
2017/04/21 11:37:10 [debug] pg_database = "kong"
2017/04/21 11:37:10 [debug] pg_host = "127.0.0.1"
2017/04/21 11:37:10 [debug] pg_port = 5432
2017/04/21 11:37:10 [debug] pg_ssl = false
2017/04/21 11:37:10 [debug] pg_ssl_verify = false
2017/04/21 11:37:10 [debug] pg_user = "kong"
2017/04/21 11:37:10 [debug] prefix = "/usr/local/kong/"
2017/04/21 11:37:10 [debug] proxy_listen = "0.0.0.0:8000"
2017/04/21 11:37:10 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2017/04/21 11:37:10 [debug] serf_path = "serf"
2017/04/21 11:37:10 [debug] ssl = true
2017/04/21 11:37:10 [debug] upstream_keepalive = 60
2017/04/21 11:37:10 [verbose] prefix in use: /usr/local/kong
2017/04/21 11:37:10 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/04/21 11:37:10 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2017/04/21 11:37:10 [debug] searching for OpenResty 'resty' executable
2017/04/21 11:37:10 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.2'
2017/04/21 11:37:10 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2017/04/21 11:37:10 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2017/04/21 11:37:10 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/04/21 11:37:10 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2017/04/21 11:37:10 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2017/04/21 11:37:10 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2017/04/21 11:37:10 [verbose] running datastore migrations
2017/04/21 11:37:10 [verbose] migrations up to date
2017/04/21 11:37:10 [verbose] serf agent not running, deleting /usr/local/kong/pids/serf.pid
2017/04/21 11:37:10 [debug] searching for 'serf' executable
2017/04/21 11:37:10 [debug] serf version: 'Serf v0.7.0'
2017/04/21 11:37:10 [debug] found 'serf' executable at serf
2017/04/21 11:37:10 [debug] starting serf agent: nohup serf agent -profile 'wan' -bind '0.0.0.0:7946' -log-level 'err' -rpc-addr '127.0.0.1:7373' -event-handler 'member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf/serf_event.sh' -node 'precise64_0.0.0.0:7946_54600c29db8547bd994fa7c25d665d78' > /usr/local/kong/logs/serf.log 2>&1 & echo $! > /usr/local/kong/pids/serf.pid
2017/04/21 11:37:11 [verbose] waiting for serf agent to be running
2017/04/21 11:37:11 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/04/21 11:37:11 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/04/21 11:37:11 [verbose] serf agent started
2017/04/21 11:37:11 [verbose] auto-joining serf cluster
2017/04/21 11:37:11 [verbose] no other nodes found in the cluster
2017/04/21 11:37:11 [verbose] registering serf node in datastore
2017/04/21 11:37:11 [verbose] cluster joined and node registered in datastore
2017/04/21 11:37:11 [debug] searching for OpenResty 'nginx' executable
2017/04/21 11:37:11 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.11.2.2'
2017/04/21 11:37:11 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2017/04/21 11:37:11 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2017/04/21 11:37:11 [debug] nginx started
2017/04/21 11:37:11 [info] Kong started

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

- Kong configuration (registered APIs/Plugins & configuration file)

- Operating System
Ubuntu 12.04   precise64

**Comment by thibaultcha** [comment]
The value for this form parameter is `consumer_id`, and not `config.consumer_id`.
