### ISSUE TITLE
Upgrade APIKey Plugin to restrict from unauthorised access for Web, Android and ios

### ISSUE THREAD

**Issue by b-rajesh** [Mashape/kong#2438]
### Summary

When a APIKey is created in KONG, it is unrestricted. Anyone in the web can get the APIKey from browser header. A new plugin is needed while creating APIKey to prevent unauthorised use and quota theft. 

While creating APIKey following options can be provided

### For Web
A field to capture "http referrers" which is different from origins.
A field to capture ip addresses
### For Android
A field to capture package name and SHA-1 certificate fingerprint
### For ios
A field to capture bundle identifiers

**Comment by thibaultcha** [comment]
Hi

> Anyone in the web can get the APIKey from browser header.

What do you mean? I hope you are encrypting your traffic and not using plain HTTP for production usage...

**Comment by b-rajesh** [comment]
Hi , 

Of course yes. This scenario happens even before that - users uses javascript web applications to call an api which uses apikey.
###Scenario
 A company deployed a javascript web application for address lookup which needs to talk to an api - requires apikey for verification. That java script web app will be used by end users who can get the apikey from browser (by inspecting the network) and misuse the apikey (quota theft)

**Comment by thibaultcha** [comment]
I see, you are sharing your API key between all of your users then? Ideally, you should probably consider another way of structuring your application and use an appropriate authentication scheme for your end-users. Why not using OAuth2? JWT? Even assigning a unique API key per end-user would make more sense.

If you really are worried about quota theft only (and not security implications?) then, *maybe* you could rate-limit the usage per IP address?

**Comment by b-rajesh** [comment]
Restructuring the system is not an option for us. For any other Auth mechanism, we will be forcing them to authenticate against some idp. This complicates user experience.
Imagine a Realestate website needs to talk to an api for address lookup. This doesn't need end user to login to do address look up from a realestate website. 

Mostly, APIkey is used to identify our client not clients end user.

**Comment by thibaultcha** [comment]
Alright, then such a discussion probably does not belong to Kong OSS because it's about supporting a custom requirement. I believe you are discussing the implementation of such a plugin with the Mashape Enterprise support team. If so, such discussions should not transpire in this public repository. Shall we close this?

**Comment by thibaultcha** [comment]
Closing this now, this discussion is to be continued on the Enterprise support channels.
