### ISSUE TITLE
when using oauth2,i always get the message "{"message":"Unauthorized"}"

### ISSUE THREAD

**Issue by colinbetter** [Mashape/kong#2439]
Hello,i use the kong and enabled the oauth2 plugin.in the last step,i get zhe access_token from kong,but i can not pass kong to visit my service with the access_token.i can refresh the token with the refresh_token that kong told me.but after i refreshed,i use the new token to access kong and also get zhe message "{"message":"Unauthorized"}"

here is my steps:
（1）、add API

# request
curl -X POST http://127.0.0.1:8001/apis --data "name=myhttpbin" \
--data "upstream_url=https://httpbin.org" \
--data "hosts=myyufan.me" \
--data "preserve_host=true"
#response
{
    "http_if_terminated": true,
    "id": "676b7bd1-4dbf-4f39-930f-3946f6f7df13",
    "retries": 5,
    "preserve_host": true,
    "created_at": 1492999999972,
    "upstream_connect_timeout": 60000,
    "upstream_url": "https://httpbin.org",
    "upstream_send_timeout": 60000,
    "https_only": false,
    "upstream_read_timeout": 60000,
    "strip_uri": true,
    "name": "myhttpbin",
    "hosts": [
        "myyufan.me"
    ]
}
（2）、API config oAuth2

curl -X POST http://127.0.0.1:8001/apis/676b7bd1-4dbf-4f39-930f-3946f6f7df13/plugins \
--data "name=oauth2" \
--data "config.scopes=email,phone,address" \
--data "config.enable_authorization_code=true" \
--data "config.mandatory_scope=true"
#response
{
    "api_id": "676b7bd1-4dbf-4f39-930f-3946f6f7df13",
    "id": "a4336262-0684-4a07-9b59-b28916e6d076",
    "created_at": 1493000151353,
    "enabled": true,
    "name": "oauth2",
    "config": {
        "mandatory_scope": true,
        "token_expiration": 7200,
        "anonymous": "",
        "enable_implicit_grant": false,
        "scopes": [
            "email",
            "phone",
            "address"
        ],
        "hide_credentials": false,
        "provision_key": "78291a12373648a08d4f56024fa6f2df",
        "enable_password_grant": false,
        "accept_http_if_already_terminated": false,
        "global_credentials": false,
        "enable_client_credentials": false,
        "enable_authorization_code": true
    }
}

（3）、add developer
curl -X POST http://127.0.0.1:8001/consumers \
--data "username=mytestuser" \
--data "custom_id=my12345"
#response
{
    "custom_id": "my12345",
    "username": "mytestuser",
    "created_at": 1493000267683,
    "id": "93900481-e6b4-4c1b-a258-00d9fb933bcc"
}

（4）、add app

curl -X POST http://127.0.0.1:8001/consumers/93900481-e6b4-4c1b-a258-00d9fb933bcc/oauth2 \
--data "name=MyTestApplication" \
--data "redirect_uri=https://httpbin.org/get"
#response
{
    "consumer_id": "93900481-e6b4-4c1b-a258-00d9fb933bcc",
    "client_id": "ca0649b9d2f34458b09d4a2d23aa45ef",
    "id": "72dfc31a-3396-4c06-8b76-d6f3db964c5d",
    "redirect_uri": [
        "https://httpbin.org/get"
    ],
    "name": "MyTestApplication",
    "created_at": 1493000350497,
    "client_secret": "bcebeb6f17894bc8a060d94f73a0f9e7"
}
（5）、get code

curl -X POST https://127.0.0.1:8443/oauth2/authorize \
-H "Host: myyufan.me" \
--data "client_id=ca0649b9d2f34458b09d4a2d23aa45ef" \
--data "response_type=code" \
--data "scope=email" \
--data "authenticated_userid=myyufan" \
--data "provision_key=78291a12373648a08d4f56024fa6f2df" \
--insecure
#response
{
    "redirect_uri": "https://httpbin.org/get?code=a6e1af81b3cc435ea70670f5e51c0755"
}

（6）、get token
curl -X POST https://127.0.0.1:8443/oauth2/token \
-H "Host: myyufan.me" \
--data "client_id=ca0649b9d2f34458b09d4a2d23aa45ef" \
--data "client_secret=bcebeb6f17894bc8a060d94f73a0f9e7" \
--data "grant_type=authorization_code" \
--data "code=a6e1af81b3cc435ea70670f5e51c0755" \
--insecure
#response
{
    "refresh_token": "b0debe5246d34a9c9aefa869b297d2d5",
    "token_type": "bearer",
    "access_token": "6931516b9e7243e3aa76173acdb3273d",
    "expires_in": 7200
}
（7）、API request

curl -X POST https://127.0.0.1:8443/post \
-H "Host: myyufan.me" \
--data "access_token=6931516b9e7243e3aa76173acdb3273d" \
--insecure
#response
{"message":"Unauthorized"}

is there some problem?i am confused for some days and can not get reason.so i come here for your help,thanks!
- Kong version (`0.10.1`)
- Operating System Centos-7.2

**Comment by colinbetter** [comment]
i am sorry to bother you,i found the reason.it is all my fault.

**Comment by opyate** [comment]
> i am sorry to bother you,i found the reason.it is all my fault.

Sharing (the reason) is caring.

**Comment by fabianrdz** [comment]
What was the reason, i'm facing something similar.
The response is allways unauthorized even with the doc examples

**Comment by mnofresno** [comment]
Pls share the reason it doesn't worked
