### ISSUE TITLE
Is there a way to specify http_version for upstream server while adding apis ?

### ISSUE THREAD

**Issue by bpatelcs** [Mashape/kong#2440]
Seems like by default kong uses HTTP/1.0 for upstream server, was wondering if we can specify HTTP/1.1 while adding new apis through kong.

**Comment by thibaultcha** [comment]
Hi,

Which version of Kong are you using? 0.10 and higher should be using [HTTP/1.1](https://github.com/Mashape/kong/blob/master/kong/templates/nginx_kong.lua#L103).

**Comment by bpatelcs** [comment]
0.9.7

**Comment by p0pr0ck5** [comment]
the proxy_http_version was added in commit b468e59547db4e42b5c1d3f8b865f2b235ccd401; before that, it was undefined (defaulting to HTTP/1.0), and wasnt configurable

**Comment by thibaultcha** [comment]
Please update to the latest Kong version, or specify the version yourself in a custom Nginx template. Closing this and considering it answered.

**Comment by bpatelcs** [comment]
Thanks , updating Nginx template works.
