### ISSUE TITLE
Kong 0.10.2

### ISSUE THREAD

**Issue by jtuthehien** [Mashape/kong#2444]
Hi all.
Just wondering when 0.10.2 will be released, there's a current blocking bug with trailing slash that's stopping us from upgrading from 0.9x

**Comment by p0pr0ck5** [comment]
Hi,

10.2 is planned to be released this or next week.

BTW, please try to reserve GitHub issue only for issues running Kong. Support and discussion questions like this should be sent to the mailing list, or Gitter, as the issue template boilerplate notes. Thank you!
