### ISSUE TITLE
OAuth2 plugin client credentials checking

### ISSUE THREAD

**Issue by cedum** [Mashape/kong#2446]
### Summary

While integrating the oauth2 flow with CloudFlare Apps (https://www.cloudflare.com/apps/developers) we found an issue in the last step of the three-step Authorization Code flow implemented in Kong.

The `POST /oauth2/token` request has issues with client credentials checking when having:
- `client_id:client_secret` passed via the authorization header;
- and `client_id` passed as a request body parameter.

The issue seems to be caused by this [kong/plugins/oauth2/access.lua#L234](https://github.com/Mashape/kong/blob/3312481a4cd48d3674707fac22746baf1b5552e6/kong/plugins/oauth2/access.lua#L234) 
The `if` control sets `client_id` and `client_secret` by checking only if there's a `client_id` parameter, otherwise it falls back to the authorization header.
In cases where the client credentials are passed via the authorization header and only `client_id` is passed via the req.body parameters, the first `if` returns `true` and it tries to set the credentials from the parameters.

### Steps To Reproduce

1. create an API
```
curl -X POST \
  http://localhost:8001/apis/ \
  -H 'content-type: application/x-www-form-urlencoded' \
  -d 'name=my-api&hosts=localhost&upstream_url=http%3A%2F%2Flocalhost'
```
Response body:
```
{"http_if_terminated":true,"id":"b02c7c66-3c0c-423e-96ec-0d363a82fee6","retries":5,"preserve_host":false,"created_at":1493031179000,"upstream_connect_timeout":60000,"upstream_url":"http:\/\/localhost","upstream_read_timeout":60000,"https_only":false,"upstream_send_timeout":60000,"strip_uri":true,"name":"my-api","hosts":["localhost"]}
```
2. enable oauth2 plugin (w/ authorization code flow)
```
curl -X POST \
  http://localhost:8001/apis/b02c7c66-3c0c-423e-96ec-0d363a82fee6/plugins \
  -H 'content-type: application/x-www-form-urlencoded' \
  -d 'name=oauth2&config.enable_authorization_code=true&config.accept_http_if_already_terminated=true'
```
Response body:
```
{"api_id":"b02c7c66-3c0c-423e-96ec-0d363a82fee6","id":"cd6521df-a556-4800-ba48-8bf836d92203","created_at":1493031371000,"enabled":true,"name":"oauth2","config":{"enable_authorization_code":true,"token_expiration":7200,"anonymous":"","enable_implicit_grant":false,"hide_credentials":false,"mandatory_scope":false,"enable_password_grant":false,"accept_http_if_already_terminated":true,"global_credentials":false,"enable_client_credentials":false,"provision_key":"e1a799d9ca0d4ca3bef7b7c9136abd05"}}
```

3. create a consumer
```
curl -X POST \
  http://localhost:8001/consumers \
  -H 'content-type: application/x-www-form-urlencoded' \
  -d 'custom_id=1&username=cloudflare'
```
Response body:
```
{"custom_id":"1","username":"cloudflare","created_at":1493031460000,"id":"056a7d46-7d8a-4977-89a2-ddf7fdcdbd12"}
```

4. create oauth2 application
```
curl -X POST \
  http://localhost:8001/consumers/056a7d46-7d8a-4977-89a2-ddf7fdcdbd12/oauth2 \
  -H 'content-type: application/x-www-form-urlencoded' \
  -d 'name=Cloudflare&redirect_uri=http%3A%2F%2Flocalhost%3A3010%2Foauth-callback'
```
Response body:
```
{"consumer_id":"056a7d46-7d8a-4977-89a2-ddf7fdcdbd12","client_id":"5de443d7a43a4282a9b206ea9c31cc8a","id":"3d5bec06-edcd-4ad5-a89e-3531254b19b7","created_at":1493031520000,"redirect_uri":["http:\/\/localhost:3010\/oauth-callback"],"name":"Cloudflare","client_secret":"21917677f4c44409b31b835ada01754e"}
```

5. request an authorization code
```
curl -X POST \
  http://localhost:8000/oauth2/authorize \
  -H 'authorization: Basic NWRlNDQzZDdhNDNhNDI4MmE5YjIwNmVhOWMzMWNjOGE6MjE5MTc2NzdmNGM0NDQwOWIzMWI4MzVhZGEwMTc1NGU=' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'host: localhost' \
  -H 'x-forwarded-proto: https' \
  -d 'client_id=5de443d7a43a4282a9b206ea9c31cc8a&response_type=code&provision_key=e1a799d9ca0d4ca3bef7b7c9136abd05&authenticated_userid=1'
```
Response body:
```
{"redirect_uri":"http:\/\/localhost:3010\/oauth-callback?code=2b9ebdf135354132a913e32dd3c9a5cc"}
```

5.a request an access token (by passing client_id:client_secret auth header + client_id param in req.body)
```
curl -v -X POST \
  http://localhost:8000/oauth2/token \
  -H 'authorization: Basic NWRlNDQzZDdhNDNhNDI4MmE5YjIwNmVhOWMzMWNjOGE6MjE5MTc2NzdmNGM0NDQwOWIzMWI4MzVhZGEwMTc1NGU=' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'host: localhost' \
  -H 'x-forwarded-proto: https' \
  -d 'client_id=5de443d7a43a4282a9b206ea9c31cc8a&code=2b9ebdf135354132a913e32dd3c9a5cc&grant_type=authorization_code'
``` 
Reponse body (HTTP/1.1 400 Bad Request):
```
{"error_description":"Invalid client authentication","error":"invalid_client"}
```

5.b request an access token (without `client_id` param in the request body):
```
curl -v -X POST \
  http://localhost:8000/oauth2/token \
  -H 'authorization: Basic NWRlNDQzZDdhNDNhNDI4MmE5YjIwNmVhOWMzMWNjOGE6MjE5MTc2NzdmNGM0NDQwOWIzMWI4MzVhZGEwMTc1NGU=' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'host: localhost' \
  -H 'x-forwarded-proto: https' \
  -d 'code=2b9ebdf135354132a913e32dd3c9a5cc&grant_type=authorization_code'
```
Response body (HTTP/1.1 200 OK)
```
{"refresh_token":"93384f1b50a54263946d0294688e7dcd","token_type":"bearer","access_token":"c7720e88cac641e182fa036db318f8a8","expires_in":7200}
```

### Additional Details & Logs

- Kong version `0.10.0`
- Operating System Ubuntu 16.04 (kernel `4.4.0-72-generic`)

**Comment by thefosk** [comment]
> and client_id passed as a request body parameter.

Can't `client_id` be removed from the request body since you are already authenticating using the `Authorization` header?

**Comment by cedum** [comment]
@thefosk sure, unfortunately in this case we don't have control of the client (it's Cloudflare acting as oauth2 client using their internal implementation). I'm forwarding also to them this issue.

In the meantime, we solved by changing this line:
https://github.com/Mashape/kong/blob/master/kong/plugins/oauth2/access.lua#L234
to:
```
if parameters[CLIENT_ID] and parameters[CLIENT_SECRET] then
```

Is there a reason why there's checked only client id (https://github.com/Mashape/kong/blob/master/kong/plugins/oauth2/access.lua#L234)? Hence it seems Kong doesn't allow to create an oauth2 application without client secret: when creating, if `client_secret` is empty or null, it autogenerates a `client_secret`. I assume that there must be always a `client_secret`.

**Comment by thefosk** [comment]
@cedum Would you like to submit a PR with your change?
