### ISSUE TITLE
Marshall is spelled with one 'L'

### ISSUE THREAD

**Issue by peterbsmith2** [Mashape/kong#2450]
*Note: GitHub issues should be reserved only for bug reports. Please use the
[Kong mailing list](https://groups.google.com/forum/#!forum/konglayer) or
[Gitter](https://gitter.im/Mashape/kong) for user support, development
questions, feature requests, etc.*

### Summary

In the kong repository, in several places, the term "marshall_event" is used. While the meaning is clear and accurate, the spelling of "marshall" in the [dictionary has only one "l"](http://www.dictionary.com/browse/marshal?s=t)

**Comment by thibaultcha** [comment]
Hi,

Here we are referring to "marshalling", a technical term that takes two "L": https://en.wikipedia.org/wiki/Marshalling_(computer_science).

**Comment by peterbsmith2** [comment]
Fair enough @thibaultcha

**Comment by thibaultcha** [comment]
Clicked on "close" a bit too fast, sorry :) I suppose you are suggesting we either rename this to `marshalling` or `marshal_event`? Which is appropriate I believe? However, those properties will soon disappear due to the incoming Serf removal :)
