### ISSUE TITLE
Can't get oauth2 authorization code 

### ISSUE THREAD

**Issue by Mukulch15** [Mashape/kong#2454]
I have a localhost api on my machine and after setting up the oauth 2 client plugin on that when I try to get the authorization code I get the error cannot get /undefined. I am using  the kong hello world node js client.
Kong version - 0.10.x

**Comment by thefosk** [comment]
Can you please write down the commands to replicate?

**Comment by Mukulch15** [comment]
@thefosk  Hi I was able to resolve the issue. The uri field that I gave while cerating the api and the api url that I gave while asking for the auth code were not matching.
