### ISSUE TITLE
Unable to get 'File Log' plugin installed using curl

### ISSUE THREAD

**Issue by anniecruz13** [Mashape/kong#2458]
Environment:
Dev workstation: Windows 7 64-bit
kong version: 0.10.1
VirtualBox version: 5.1.10r112026
box type: bento/centos-7.2
Using Docker? -No
Using OpenResty: -No
Vagrant version: 1.9.3

### Summary
Unable to add 'File Log' plugin using curl.
After adding the application, I tried to add the plugin with a curl call from my localhost:
curl -X POST http://localhost:8001/apis/{api id}/plugins --data "name=file-log" --data "config.path=/logs/log-file.log"
Kong responded with this message:
 {"config.path":"Cannot create file: C:\/Program Files\/Git\/logs\/log-file.log: No such file or directory"}
Why does it think I'm adding a this plugin with a config.path on my local machine?

I was able to add the plugin using the Kong Dashboard.
[KongStartupLog.txt](https://github.com/Mashape/kong/files/956073/KongStartupLog.txt)
[KongStartupLog.txt](https://github.com/Mashape/kong/files/956078/KongStartupLog.txt)

### Steps To Reproduce

1. Add the api to Kong which is running on a Unix VirtualBox
2. Run this curl call from my local dev machine: 
curl -X POST http://localhost:8001/apis/{api id}/plugins --data "name=file-log" --data "config.path=/logs/log-file.log" 
3. Note the error message that tries to point to a subdirectory on my local Windows 7 machine.
4.

### Additional Details & Logs

- Kong version: 0.10.1
- Kong debug-level startup logs (`$ kong start --vv`): see attached

[troubleshooting.zip](https://github.com/Mashape/kong/files/956091/troubleshooting.zip)

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by p0pr0ck5** [comment]
If anything, this sounds more like an issue with Windows <-> Vagrant behavior, not Kong?

**Comment by p0pr0ck5** [comment]
Closing as stale. Feel free to re-open if there are unanswered questions regarding this.
