### ISSUE TITLE
Do Kong support Consul Template？

### ISSUE THREAD

**Issue by andChow** [Mashape/kong#2460]
We need automatically change Nginx's upstream info use Consul Template's feature.

**Comment by p0pr0ck5** [comment]
Hi,

Upstreams are controlled using the load balancing functionality of Kong: https://getkong.org/docs/0.10.x/loadbalancing/. This provides a RESTful interface to manage upstreams for your APIs; you can then use your config management of choice to interact with this API.

BTW, please reserve GitHub issues for actual issues running Kong.  Please use the
[Kong mailing list](https://groups.google.com/forum/#!forum/konglayer) or
[Gitter](https://gitter.im/Mashape/kong) for user support, development
questions, feature requests, etc.*. Thank you!
