### ISSUE TITLE
What

### ISSUE THREAD

**Issue by workcheng** [Mashape/kong#2464]
I want to develop a plugins base kong.With which tools to develop？

**Comment by thibaultcha** [comment]
Hi, 

Please ask such general questions on the mailing list. As pointed out by the issue template (that you saw opening this issue), this place is for bug reports only. FYI, you'll find that same question answered there already.

https://groups.google.com/forum/?hl=en#!forum/konglayer

https://getkong.org/docs/latest/plugin-development/
