### ISSUE TITLE
APIs POST/PATCH error response is not conforming to other endpoint error responses

### ISSUE THREAD

**Issue by nijikokun** [Mashape/kong#2468]
### Summary

When you make a `POST` request to `/consumers` without any data provided you will get back a hash of `field: error-message` response:

```http
POST /consumers/

{
  "custom_id": "At least a 'custom_id' or a 'username' must be specified",
  "username": "At least a 'custom_id' or a 'username' must be specified"
}
```

Doing the same request on `/apis` returns a non-conforming response where it is instead `"message": error-message`:

```http
POST /apis/

{
  "message": "at least one of 'hosts', 'uris' or 'methods' must be specified"
}
```

The `/consumers` response is preferable due to the potential of multiple fields having errors.

### Steps To Reproduce

1. `POST /consumers`
2. `POST /apis`
3. Compare

### Additional Details & Logs

- Kong version (`0.10.1`)
- OS (`macOS`)

**Comment by bungle** [comment]
I do think that generic `message` is useful as well. In to `POST /apis` case none of hosts, uris or methods are wrong by per se, so it might not be correct to mark them all with red in UI for example, but generic message before those fields is alright.

The `self_check` and custom field validators are also something bit of a pain. E.g. with POST things like `hosts`, `uris`, or `methods` is needed, but with PATCH you can actually remove them. That is actually alright, and maybe we could consider if that `self_check` is needed at all there.

**Comment by Tieske** [comment]
closing based on @nijikokun feedback.
