### ISSUE TITLE
[cli] Kong check default path

### ISSUE THREAD

**Issue by codebien** [Mashape/kong#2472]
`kong check` command from CLI searches default conf only in `/etc/kong.conf`. Is right? Why not also `/etc/kong/kong.conf` like [here](https://getkong.org/docs/0.10.x/configuration/#configuration-loading).

**Comment by thibaultcha** [comment]
I'm not sure what you mean. Please provide the command you ran, the result and the result you expected.

```
$ kong check --help
Usage: kong check <conf>

Check the validity of a given Kong configuration file.

<conf> (default /etc/kong/kong.conf) configuration file
 --v         verbose
 --vv        debug
```

**Comment by codebien** [comment]
Sorry, my mistake. I have runned the command from `0.9.9`. In 0.10.x the behavior is right but the doc is not updated.

```bash
docker run --rm kong:0.9.9 kong check
[error] no file at: /etc/kong.conf
```

1. This issue is releated to 0.9.9
2. The [.10.x doc](https://getkong.org/docs/0.10.x/cli/#kong-check) for the `kong check` command is old.

**Comment by Tieske** [comment]
@codebien PR on https://github.com/Mashape/getkong.org would be nice 😄
