### ISSUE TITLE
Serf issue

### ISSUE THREAD

**Issue by sredXNY** [Mashape/kong#2479]
Hi, I just installed Kong 0.10.1 in CentOS 7. Now I'm trying to execute Kong but I got a Serf agent error, this one:
`
Error: could not start serf: Failed to start the Serf agent: Error creating Serf: Failed to create memberlist: No private IP address found, and explicit IP not provided
`
I read that this problem can be fixed setting up a explicit IP on the clusters properties, so I setted:

```
cluster_listen = My.public.I.P:7946
cluster_advertise =My.public.I.P
```

Then, I tried to run it again but the problem persist. Did I something wrong? What am I missing?

**Edited:**
Also, I am using Postgres, the migrations were executed correctly the first time and inmediatly I get that error of Serf, so when I configured the kong.conf I am getting a really weird situation:

1.  **Situation 1:** If I set the cluster_advertise =My.public.I.P then I get that I have to set a port. Then, If I set a port  I get this:

```
ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong.lua:134: [postgres error] could not get current migrations: [postgres error] FATAL: password authentication failed for user "postgres"
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong.lua:134: in function 'init'
        init_by_lua:4: in main chunk

```
So, I don't understand why am getting an error with the database connection when that parameters are ok, I already re-checked the parameters.

1. **Situation 2:** If I dont' set the IP on cluster_advertise then the connection to the db is ok but I get the Serf issue. To me sound like a bad parsing of the conf file?

**Comment by thefosk** [comment]
Can you run with `cluster_advertise=ADDRESS:PORT` ?

**Comment by sredXNY** [comment]
@thefosk Hi! no, I cant't, btw which port should be specified there? 

I edited the post, I was trying to fix it and now I have that situations. Thank you

**Comment by harryparmar** [comment]
@sredXNY @thefosk install docker and run kong and cassandra through docker, wont have to deal with that serf issue

**Comment by thefosk** [comment]
The error log you are showing tells that you are trying to connect to Postrgres with an invalid password - so let's fix one problem at a time. Can you check that your Postgres settings are valid?

**Comment by sredXNY** [comment]
@thefosk yes, they're correct, even they migrations were created the first time. But then,when I add the IP in cluster:advertise I get the error, if I delete the IP I only get the Serf error. The database configs are correct

**Comment by sredXNY** [comment]
@harryparmar Hi, correct! it was successful installing Kong with Docker. Thank you

**Comment by harryparmar** [comment]
@sredXNY if you are setting up kong with docker and want to setup cluster with other nodes on other machines, make sure install with net=host , you can read full command on the link below ->
https://github.com/Mashape/kong/issues/2330

**Comment by p0pr0ck5** [comment]
Sounds like this was resolved? Are there any remaining issues here?

**Comment by p0pr0ck5** [comment]
Closing since there has been no noise here in a while.
