### ISSUE TITLE
plugin rate-limiting policies redis get usage add redis database select

### ISSUE THREAD

**Issue by lamphp** [Mashape/kong#2483]
when use plugin rate-limiting, if set policy redis and set redis database，There will be a problem，in plugins/rate-limiting/policies/init.lua, The database is not set in the usage method. it will be setting by default 0 sometime,I do not know why not contain database setting, but when we get the value， it will be null @thibaultcha

**Comment by lamphp** [comment]
@thibaultcha  https://github.com/lamphp/kong/commit/c7172b5ed138c29aa2a438c24b226c3536b2b38a

**Comment by lamphp** [comment]
or my use is wrong

**Comment by thefosk** [comment]
@lamphp I have pushed a PR yesterday to fix this problem https://github.com/Mashape/kong/pull/2481

**Comment by p0pr0ck5** [comment]
@lamphp ping, are you able to test against Kong 0.10.3, which contains this change?

**Comment by p0pr0ck5** [comment]
Closing, no update, and this has since been resolved. Thanks @lamphp for the report!
