### ISSUE TITLE
Not able to consume API using postman

### ISSUE THREAD

**Issue by sredXNY** [Mashape/kong#2486]
Hi, I have installed Kong, registered an example API to test and assigned an Auth Plugin. From the server I can consume the endpoint using curl, with:

 `curl -i -X GET --url http://My.public.I.P:8000 --header 'Host:api.demo.com' --header 'X-AUTH:12345`

And that is working fine, however, then from my local machine I tried to consume the API using Postman, basically this is what I am sending:
```
GET / HTTP/1.1
Host: api.demo.com
X-AUTH: 12345 
X-Host-Override: api.demo.com   (I added this one just to test)
Cache-Control: no-cache
Postman-Token: e0d01f28-b6ec-da42-bd6b-dda09bd0221f
```
and in the URL I set: `My.Public.I.P:8000/` but now I am getting:
```

{
  "message": "no API found with those values"
}
```

So, why if essentially is the same request?

**Comment by p0pr0ck5** [comment]
@sredXNY please try to reserve Github issues for actual bugs and problems running Kong, not just support. Please use the [Kong mailing list](https://groups.google.com/forum/#!forum/konglayer) or
[Gitter](https://gitter.im/Mashape/kong) for user support, development questions, feature requests, etc.*

For now, what is the result of retrieving the `/apis` route of the admin API (port 8001)?

**Comment by sredXNY** [comment]
@p0pr0ck5 Ok, I get it!

This is what I get:
```

{
   "data":[
      {
         "http_if_terminated":true,
         "id":"f09528f1-4469-462e-a5ea-05da9126e24c",
         "upstream_read_timeout":60000,
         "preserve_host":false,
         "created_at":1493732112000,
         "upstream_connect_timeout":60000,
         "upstream_url":"http:\/\/httpbin.org",
         "strip_uri":true,
         "https_only":false,
         "name":"example-api",
         "retries":5,
         "upstream_send_timeout":60000,
         "hosts":[
            "example.com"
         ]
      },
      {
         "http_if_terminated":true,
         "id":"768f2475-f502-4d08-897b-02d24e77c3b9",
         "upstream_read_timeout":60000,
         "preserve_host":false,
         "created_at":1493737511000,
         "upstream_connect_timeout":60000,
         "upstream_url":"http:\/\/www.mockbin.org\/request",
         "strip_uri":true,
         "https_only":false,
         "name":"mockbin",
         "retries":5,
         "upstream_send_timeout":60000,
         "hosts":[
            "api.demo.com"
         ]
      }
   ],
   "total":2
}
```

**Comment by thefosk** [comment]
`X-Host-Override` has been removed - @thibaultcha can extend on it. Previous conversation at https://github.com/Mashape/kong/issues/2365.

You will have to use a `Host` header.

**Comment by sredXNY** [comment]
@thefosk yes, however without X-Host-Override header I am getting the same result. I get the correct response using curl but no when I use postman. This is how I am requesting with Postman http://prntscr.com/f564gq

And this is how I have defined the endpoint in Kong, using Kong Dashboard: http://prntscr.com/f565jv

**Comment by p0pr0ck5** [comment]
Do you see this behavior only with Postman, or can you reproduce the results with a command line curl request as well?

**Comment by p0pr0ck5** [comment]
@sredXNY any update based on the above?

**Comment by sredXNY** [comment]
@p0pr0ck5 no, I got still the same. I tried with Postman and command line curl, with curl work great but no with Postman. I will try with javascript

**Comment by p0pr0ck5** [comment]
If curl is working, this sounds like a problem with postman? I don't see any issue with kong here.

**Comment by sredXNY** [comment]
@p0pr0ck5 yes, correct. But I don't see which is the difference in the request. I will close this issue as is more related to a Postman issue than Kong

**Comment by kumarinstor** [comment]
i added this in upstream url -- http://localhost:1111/student/:student_id 
then in urIs i added /student/:student_id 
when i run this http://localhost:8000/student/123  its showing no API found with those values

**Comment by kumarinstor** [comment]
please someone help me

**Comment by thibaultcha** [comment]
@kumarinstor Hi,

Please do not post to closed issues nor cross post to multiple ones, thank you.

Also, the issues are reserved for bugs, please post to [our Discourse forum](https://discuss.konghq.com/) for questions.

To answer it, please spend some time reading the [documentation](https://getkong.org/docs/0.12.x/proxy/) related to proxying.
