### ISSUE TITLE
Rate-limiting plugin doesn't work properly

### ISSUE THREAD

**Issue by ShinEDL** [Mashape/kong#2495]
### Summary

I created a rate-limiting plugin which limit by consumer and set policy to "redis", but it doesn't work properly.

### Steps To Reproduce

1.Create a api named "api_test"
2.Create a consumer named "consumer_test" and add a key of key-auth for it.
3.Create a key-auth plugin apply to "api_test".
4.Create a rate-limiting plugin which apply to "consumer_test" and "api_test", set policy to "redis".

```
some configuration:
config.minute = 1
config.redis_database = 1
config.limit_by = consumer
config.policy = redis
```

Other configuration is default, and redis_host and redis_password is correct.

5.Run two request to "api_test", it can work properly (one proxy, one limited). However, one second later, I run another request to "api_test", it can proxy. 

ps:  1. the interval is one minute；
       2. redis server can't find the key about rate-limiting.

### Additional Details & Logs

- Kong version (0.10.1 & 0.10.2)
- Kong debug-level startup logs (N/A)
- Kong error logs (N/A)
- Kong configuration (nature)
- Operating System (docker/ubuntu)

**Comment by ShinEDL** [comment]
Whether postgres will affect this?

**Comment by ShinEDL** [comment]
Sometimes it even dosen't work anymore...let all request be proxied...

**Comment by p0pr0ck5** [comment]
There was a recent PR that seems related; can you have a look at https://github.com/Mashape/kong/pull/2481 and see if this solves your problem?

**Comment by ShinEDL** [comment]
@p0pr0ck5 At last, I found that if I set redis_database to 0, it work fine.
