### ISSUE TITLE
Unable to receive a response from a spring jar to to my API

### ISSUE THREAD

**Issue by tcho16** [Mashape/kong#2505]
*Note: GitHub issues should be reserved only for bug reports. Please use the
[Kong mailing list](https://groups.google.com/forum/#!forum/konglayer) or
[Gitter](https://gitter.im/Mashape/kong) for user support, development
questions, feature requests, etc.*

### Summary
I am trying to connect Kong with my Spring MVC app. The spring app listens and sends request on port localhost:8080. When going to certain paths, my spring app will load up html pages just like a normal webapp. On one of my html pages, it has a form. Once the user presses submit on that form, its supposed to send the data back to data back to the spring app using HTTP method POST on localhost:8080. What actually happens however in my plugin that I created, once the user presses submit, it tries to send the data to port 8000 as opposed to port 8080. This is the error that gets generated:
`{"request_path":"\/home","message":"API not found with these values","request_host":["localhost"]}`.
This is the code of my plugin:

```
local BasePlugin = require "kong.plugins.base_plugin"
local helper = require "kong.common.helper"
local http = require("socket.http")

local basicPlugin = BasePlugin:extend()
basicPlugin.PRIORITY = 500

function basicPlugin:new()
  basicPlugin.super.new(self, "basicPlugin")
end

function basicPlugin:access(conf)
 basicPlugin.super.access(self)
  ngx.log(ngx.DEBUG,"basicPlugin start.")
  
  local body, code, headers, status = http.request("https://localhost:8080/home")
ngx.header.content_type = "text/html"
ngx.say(body)
  
  ngx.log(ngx.WARN, body)
  

end

return basicPlugin
```

SUMMARY_GOES_HERE

### Steps To Reproduce

1. Create a basic spring mvc app that contains a form and request mappings for GET and POST
2. Create a plugin with in which it simply calls the app (localhost:8080/form for example)
3. Press the submit button on the form
4.

### Additional Details & Logs

- Kong version (`$ 0.7`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs : 

2017/05/08 20:04:56 [error] 12456#0: *7 failed to run body_filter_by_lua*: /usr/local/share/lua/5.1/kong/core/handler.lua:96: attempt to perform arithmetic on field 'KONG_HEADER_FILTER_STARTED_AT' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/kong/core/handler.lua:96: in function 'after'
	/usr/local/share/lua/5.1/kong.lua:194: in function 'body_filter'
	body_filter_by_lua:2: in function <body_filter_by_lua:1>, client: 127.0.0.1, server: _, request: "GET /ownplugin HTTP/1.1", host: "localhost:8000"

- Kong configuration (registered APIs/Plugins & configuration file)
Name of API = `ownplugin`
Request path of API= `/ownplugin`
upstreamurl = `https://google.com`
strip request path = true
Only 1 plugin inside this API but has no configs.

- Operating System
Centos7

**Comment by p0pr0ck5** [comment]
A few thoughts:

- you're using a very old version of kong (0.7). Any particular reason for that?
- It seems you're abusing the plugin environment. Rather than using a socket library to make an HTTP request, just define the URl you want to consume as an API (https://getkong.org/docs/0.10.x/getting-started/adding-your-api/).
- as for the wrong port being returned, that's a function of the HTML that your app is generating, you can modify the port in the target element of the `<form>` tag as you wish. but this is not kong's fault or responsibility :)

**Comment by p0pr0ck5** [comment]
Closing following no response. Do let us know if we can answer other questions, though for plugin development questions please use the [Kong mailing list](https://groups.google.com/forum/#!forum/konglayer) or [Gitter](https://gitter.im/Mashape/kong). Thanks.
