### ISSUE TITLE
kong-0.10.1 and openresty-1.11.2.2 start an error

### ISSUE THREAD

**Issue by xulongju** [Mashape/kong#2510]
kong.conf configuration:

[root@api openresty]# kong start --vv
2017/05/10 15:36:47 [verbose] Kong: 0.10.1
2017/05/10 15:36:47 [debug] ngx_lua: 10007
2017/05/10 15:36:47 [debug] nginx: 1011002
2017/05/10 15:36:47 [debug] Lua: LuaJIT 2.1.0-beta2
2017/05/10 15:36:47 [verbose] reading config file at /opt/config/openresty/kong.conf
2017/05/10 15:36:47 [debug] admin_listen = "172.16.2.172:8001"
2017/05/10 15:36:47 [debug] admin_listen_ssl = "172.16.2.172:8444"
2017/05/10 15:36:47 [debug] admin_ssl = true
2017/05/10 15:36:47 [debug] anonymous_reports = true
2017/05/10 15:36:47 [debug] cluster_advertise = "172.16.2.172:7946"
2017/05/10 15:36:47 [debug] cluster_listen = "172.16.2.172:7946"
2017/05/10 15:36:47 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/05/10 15:36:47 [debug] cluster_profile = "wan"
2017/05/10 15:36:47 [debug] cluster_ttl_on_failure = 3600
2017/05/10 15:36:47 [debug] custom_plugins = {}
2017/05/10 15:36:47 [debug] database = "postgres"
2017/05/10 15:36:47 [debug] dns_hostsfile = "/etc/hosts"
2017/05/10 15:36:47 [debug] dns_resolver = {}
2017/05/10 15:36:47 [debug] log_level = "error"
2017/05/10 15:36:47 [debug] lua_code_cache = "on"
2017/05/10 15:36:47 [debug] lua_package_cpath = ""
2017/05/10 15:36:47 [debug] lua_socket_pool_size = 30
2017/05/10 15:36:47 [debug] lua_ssl_verify_depth = 1
2017/05/10 15:36:47 [debug] mem_cache_size = "128m"
2017/05/10 15:36:47 [debug] nginx_optimizations = true
2017/05/10 15:36:47 [debug] pg_database = "kongv1"
2017/05/10 15:36:47 [debug] pg_host = "172.16.2.172"
2017/05/10 15:36:47 [debug] pg_password = "******"
2017/05/10 15:36:47 [debug] pg_port = 5432
2017/05/10 15:36:47 [debug] pg_ssl = false
2017/05/10 15:36:47 [debug] pg_ssl_verify = false
2017/05/10 15:36:47 [debug] pg_user = "kong"
2017/05/10 15:36:47 [debug] prefix = "/opt/config/openresty/kong"
2017/05/10 15:36:47 [debug] proxy_listen = "0.0.0.0:80"
2017/05/10 15:36:47 [debug] proxy_listen_ssl = "0.0.0.0:443"
2017/05/10 15:36:47 [debug] serf_path = "/opt/websuite/openresty/bin/serf"
2017/05/10 15:36:47 [debug] ssl = true
2017/05/10 15:36:47 [debug] ssl_cert = "/opt/config/openresty/kong/ssl/api.ttpai.cn.pem"
2017/05/10 15:36:47 [debug] ssl_cert_key = "/opt/config/openresty/kong/ssl/api.ttpai.cn.key"
2017/05/10 15:36:47 [debug] upstream_keepalive = 60
2017/05/10 15:36:47 [verbose] prefix in use: /opt/config/openresty/kong
2017/05/10 15:36:47 [verbose] preparing nginx prefix directory at /opt/config/openresty/kong
2017/05/10 15:36:47 [verbose] saving serf identifier to /opt/config/openresty/kong/serf/serf.id
2017/05/10 15:36:47 [debug] searching for OpenResty 'resty' executable
2017/05/10 15:36:47 [debug] /usr/local/openresty/bin/resty -V: 'sh: /usr/local/openresty/bin/resty: 没有那个文件或目录'
2017/05/10 15:36:47 [debug] OpenResty 'resty' executable not found at /usr/local/openresty/bin/resty
2017/05/10 15:36:47 [debug] resty -V: 'nginx version: openresty/1.11.2.2'
2017/05/10 15:36:47 [debug] found OpenResty 'resty' executable at resty
2017/05/10 15:36:47 [verbose] saving serf shell script handler to /opt/config/openresty/kong/serf/serf_event.sh
2017/05/10 15:36:47 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2017/05/10 15:36:47 [verbose] admin SSL certificate found at /opt/config/openresty/kong/ssl/admin-kong-default.crt
2017/05/10 15:36:47 [verbose] running datastore migrations
2017/05/10 15:36:47 [verbose] migrations up to date
2017/05/10 15:36:47 [verbose] serf agent not running, deleting /opt/run/openresty/serf.pid
2017/05/10 15:36:47 [debug] searching for 'serf' executable
2017/05/10 15:36:47 [debug] /opt/websuite/openresty/bin/serf version: 'Serf v0.7.0'
2017/05/10 15:36:47 [debug] found 'serf' executable at /opt/websuite/openresty/bin/serf
2017/05/10 15:36:47 [debug] starting serf agent: nohup /opt/websuite/openresty/bin/serf agent -profile 'wan' -bind '172.16.2.172:7946' -log-level 'err' -rpc-addr '127.0.0.1:7373' -event-handler 'member-join,member-leave,member-failed,member-update,member-reap,user:kong=/opt/config/openresty/kong/serf/serf_event.sh' -advertise '172.16.2.172:7946' -node 'localhost.localdomain_0.0.0.0:7946_874e0520ed504856a9de526344a0f515' > /opt/logs/openresty/serf.log 2>&1 & echo $! > /opt/run/openresty/serf.pid
2017/05/10 15:36:47 [verbose] waiting for serf agent to be running
2017/05/10 15:36:47 [debug] sending signal to pid at: /opt/run/openresty/serf.pid
2017/05/10 15:36:47 [debug] kill -0 `cat /opt/run/openresty/serf.pid` >/dev/null 2>&1
2017/05/10 15:36:47 [verbose] serf agent started
2017/05/10 15:36:47 [verbose] auto-joining serf cluster
2017/05/10 15:36:47 [verbose] no other nodes found in the cluster
2017/05/10 15:36:47 [verbose] registering serf node in datastore
2017/05/10 15:36:47 [verbose] cluster joined and node registered in datastore
2017/05/10 15:36:47 [debug] searching for OpenResty 'nginx' executable
2017/05/10 15:36:47 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'sh: /usr/local/openresty/nginx/sbin/nginx: 没有那个文件或目录'
2017/05/10 15:36:47 [debug] OpenResty 'nginx' executable not found at /usr/local/openresty/nginx/sbin/nginx
2017/05/10 15:36:47 [debug] nginx -v: 'nginx version: openresty/1.11.2.2'
2017/05/10 15:36:47 [debug] found OpenResty 'nginx' executable at nginx
2017/05/10 15:36:47 [debug] starting nginx: nginx -p /opt/config/openresty/kong -c nginx.conf
2017/05/10 15:36:48 [debug] nginx started
2017/05/10 15:36:48 [info] Kong started

I restart or start kong would produce a this kind of error log：
[root@api openresty]# more error.log 
2017/05/10 13:30:37 [error] 4180#4180: *16 recv() failed (111: Connection refused), context: ngx.timer
2017/05/10 13:30:37 [error] 4181#4181: *15 recv() failed (111: Connection refused), context: ngx.timer
2017/05/10 15:30:36 [error] 4178#4178: *30706 recv() failed (111: Connection refused), context: ngx.timer
2017/05/10 15:36:48 [error] 5207#5207: *15 recv() failed (111: Connection refused), context: ngx.timer
2017/05/10 15:36:48 [error] 5210#5210: *18 recv() failed (111: Connection refused), context: ngx.timer

**Comment by p0pr0ck5** [comment]
Hi,

Please make sure you compile OpenResty with the `--without-luajit-lua52` flag. This flag is currently necessary to ensure proper operability with the Penlight library.

**Comment by xulongju** [comment]
Hi, - without-luajit-lua52 has been added, but see the details of the compiler parameters do not show

my configure：
./configure \
--prefix=/opt/websuite/openresty \
--error-log-path=/opt/logs/openresty/error.log \
--conf-path=/opt/config/openresty/nginx.conf \
--pid-path=/opt/run/openresty/openresty.pid \
--sbin-path=/opt/websuite/openresty/sbin/nginx \
--with-pcre=/opt/fpmserver/kong-0.10.1/package/pcre \
--with-pcre-opt=-fPIC \
--with-pcre-jit \
--with-ipv6 \
--with-threads \
--with-file-aio \
--with-cc-opt='-O3' \
--with-http_realip_module \
--with-http_ssl_module \
--with-http_stub_status_module \
--with-http_v2_module \
--without-luajit-lua52 \
--with-google_perftools_module \
--with-openssl=/opt/fpmserver/kong-0.10.1/package/openssl

**Comment by p0pr0ck5** [comment]
Correct, this OpenResty configure param does not show in the output of `nginx -V`, but it does make a difference for this usage.

**Comment by xulongju** [comment]
Hi,

[root@api master]# /opt/websuite/openresty/sbin/nginx -V
nginx version: openresty/1.11.2.2
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) 
built with OpenSSL 1.0.2k  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/opt/websuite/openresty/nginx --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.60 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.06 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.7 --add-module=../ngx_lua_upstream-0.06 --add-module=../headers-more-nginx-module-0.32 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.17 --add-module=../redis2-nginx-module-0.13 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-nginx-module-0.07 --with-ld-opt='-Wl,-rpath,/opt/websuite/openresty/luajit/lib' --with-pcre=/opt/fpmserver/kong-0.10.1/package/pcre --with-pcre-opt=-fPIC --with-pcre-jit --with-ipv6 --with-http_realip_module --with-http_ssl_module --with-http_stub_status_module --with-http_v2_module --with-google_perftools_module --with-openssl=/opt/fpmserver/kong-0.10.1/package/openssl


--without-luajit-lua52 has been added, but see the details of the compiler parameters do not show

**Comment by p0pr0ck5** [comment]
@xulongju yes, I just explained, this is expected behavior. You _will not_ see `--without-luajit-lua52` in the output of `nginx -V`. this is normal. Please try to reproduce the original problem reported in this issue and let us know.

**Comment by p0pr0ck5** [comment]
@xulongju are you able to reproduce this issue after building OpenResty with the flag mentioned above?

**Comment by p0pr0ck5** [comment]
Closing following no response. @xulongju let us know if you still have trouble after compiling with `--without-luajit-lua52`
