### ISSUE TITLE
Kong (latest)  Basic Authitication Not working in case of invalid base64  input string 

### ISSUE THREAD

**Issue by anupam4881** [Mashape/kong#2511]
Hi Team,

I am new for Kong, I enabled basic authentication for my API.

Ref: https://getkong.org/plugins/basic-authentication

I have created consumers & user for my API using below query. 

curl -X POST http://localhost:8001/consumers/HCL/basic-auth --data "username=Aladdin" --data "password=OpenSesame" 
curl -X POST http://localhost:8001/consumers/PS/basic-auth --data "username=anupam" --data "password=anupam" 

my basic auth is working fine, but there is a serious issue when I modified the 64bit encrypt which makes the string invalid and lead my  API automatic to get exposed. 

reproduced:  API are secure when the credential is correct (Working as per expectation)  
 
[root@psld-ggn-176 ~]# echo -n 'anupam:anupam' | base64
YW51cGFtOmFudXBhbQ==

[root@psld-ggn-176 ~]#  curl -i -X GET  --url http://192.168.0.124:8000/A/emp  --header 'Host:api1.domain.com'  -H 'Authorization: Basic YW51cGFtOmFudXBhbQ=='
HTTP/1.1 200 OK

[{"id":"1","name":"a","dept":"e"},{"id":"4","name":"anupamq","dept":"IT"}]

API get exposed when the credential is change in such a way lead "invalid input” like below just add "1" at last of encrypt string.  ( it should decline the request but accept when error happened as invalid input)

[root@psld-ggn-176 ~]# echo -n YW51wewecGFtOmFudXBhbQ==1 |  base64 -d
anu▒▒pam:anupambase64: invalid input
[root@psld-ggn-176 ~]#

[root@psld-ggn-176 ~]#  curl -i -X GET  --url http://192.168.0.124:8000/A/emp  --header 'Host:api1.domin.com'  -H 'Authorization: Basic YW51cGFtOmFudXBhbQ==1'
HTTP/1.1 200 OK

[{"id":"1","name":"a","dept":"e"},{"id":"4","name":"anupamq","dept":"IT"}][root@psld-ggn-176 ~]#

Your help will be appriciated, as I am  not getting any resolution anywhere.

Rest details :  
cassandra
Server: Apache/2.4.6 (CentOS) PHP/7.0.7 OpenSSL/1.0.1e-fips mod_auth_kerb/5.4 mod_nss/2.4.6 NSS/3.16.2.3 Basic ECC mod_wsgi/3.4 Python/2.7.5
X-Powered-By: PHP/7.0.7
X-Kong-Upstream-Latency: 25
X-Kong-Proxy-Latency: 0
Via: kong/0.10.1

Regards
Anupam Narayan

**Comment by p0pr0ck5** [comment]
@anupam4881 how have you defined your plugin configs? Has the basic-auth plugin been assigned to a specific consumer, a specific API, or globally?

**Comment by anupam4881** [comment]
yes, by using below command
[root@psld-ggn-176 kong]# curl -X POST http://localhost:8001/apis/2e7961e2-1b50-4fa7-be08-c9eb1e84f916/plugins --data "name=basic-auth" --data "config.hide_credentials=true"

It is prompt for username & password, it working fine. the problem starts if I modify the base64 encrypt string directly.

**Comment by p0pr0ck5** [comment]
Just for clarity, what is the output of `curl localhost:8001/apis/`? Just to ensure the plugin is applied appropriately.

**Comment by anupam4881** [comment]
I am sharing you, will appreciate if we are able to conclude same.  
Step-1 : ( two entries) 
[root@psld-ggn-176 ~]# curl  -X GET  http://localhost:8001/apis
{"data":[{"http_if_terminated":true,"id":"d5c49c43-6549-4a7d-ace6-f528ed977ce8","retries":5,"preserve_host":false,"created_at":1494392073366,"upstream_connect_timeout":60000,"upstream_url":"http:\/\/api1.peoplestrong.com\/codeigniter\/index.php\/A\/emp","upstream_send_timeout":60000,"https_only":false,"upstream_read_timeout":60000,"strip_uri":true,"name":"A","hosts":["api1.peoplestrong.com"]},{"http_if_terminated":true,"id":"1fe9b1e2-21b4-4ec0-bde9-59a22fa0438d","retries":5,"preserve_host":false,"created_at":1494467317582,"upstream_connect_timeout":60000,"upstream_url":"http:\/\/api1.peoplestrong.com\/codeigniter\/index.php","upstream_send_timeout":60000,"https_only":false,"upstream_read_timeout":60000,"strip_uri":true,"name":"validator2","hosts":["api2.peoplestrong.com"]}],"total":2}

Step -2 (  Add '1' at last of base64 encrypt string showing invalid credentials )
[root@psld-ggn-176 ~]# curl  http://localhost:8000/  --header 'Host:api1.peoplestrong.com'    -H 'Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l1'
{"message":"Invalid authentication credentials"}

Step-3 (  with right credentail outcome as expected ) 
[root@psld-ggn-176 ~]# curl  http://localhost:8000/  --header 'Host:api1.peoplestrong.com'    -H 'Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l'
[{"id":"1","name":"a","dept":"e"},{"id":"4","name":"anupamq","dept":"IT"}]

Setp-4 ( Again append two "==" at last of base64 encrypt string and this time inplace of invalidcredentials api outcome printed , which should not be. 

[root@psld-ggn-176 ~]# curl  http://localhost:8000/  --header 'Host:api1.peoplestrong.com'    -H 'Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l=='
[{"id":"1","name":"a","dept":"e"},{"id":"4","name":"anupamq","dept":"IT"}]

**Comment by anupam4881** [comment]
Will appreciate if you  help me to fix this basic authentication

**Comment by p0pr0ck5** [comment]
This sounds if anything like the base64 decode implementation in Nginx is a bit forgiving by default. Depending on the implementation, the input may be considered "invalid" but still produce valid output. For example:

```echo -en 'QWxhZGRpbjpPcGVuU2VzYW1l' | base64 -d
Aladdin:OpenSesame```

```echo -en 'QWxhZGRpbjpPcGVuU2VzYW1l==' | base64 -d
Aladdin:OpenSesamebase64: invalid input
```

"invalid input" doesn't mean that nothing was returned as a result. I don't think this is a bug, just a function of how Base64 decoding works. I'll take more of a look.

**Comment by p0pr0ck5** [comment]
Oh, silly me. `=` is padding. This is simply stripped off when the token is decoded. This is how Base64 works. :)

If you want to really test this, don't rely on munging data after `=` chars in a b64 encoded string. Try appending any other char, or prepending, or making literally any other change to the string besides appending padding.

**Comment by anupam4881** [comment]
Thanks fix now. It was actually not an issue/bug, Thanks for such wonderful product. 
really appreciate.

Regards
Anupam Narayan
