### ISSUE TITLE
Kong is adding URL encoding before sending upstream

### ISSUE THREAD

**Issue by tecnobrat** [Mashape/kong#2512]
### Summary

In Kong 0.10.2 it is adding additional URL encoding before sending a request upstream.

### Steps To Reproduce

1. Make a request to kong with `/auth%7C123` (`/auth|123`, url-encoded).
2. Kong will make the request to your upstream as: `/auth%257C123`

### Additional Details & Logs

- Kong version 0.10.2

This was not the case in Kong 0.9.9, it didn't further encode these URLs.

**Comment by p0pr0ck5** [comment]
Was this possibly resolved in https://github.com/Mashape/kong/pull/2377? Would you be able to try with that PR?

**Comment by thibaultcha** [comment]
Hi,

Thanks for the report. That might indeed very well be the case, we'll investigate. 

@bungle Did you see this?

**Comment by bungle** [comment]
The relevant tests:
https://github.com/Mashape/kong/blob/master/spec/01-unit/11-router_spec.lua#L819-L833
https://github.com/Mashape/kong/blob/master/spec/02-integration/05-proxy/01-router_spec.lua#L175-L184

The possible bug:
https://github.com/Mashape/kong/blob/master/kong/core/router.lua#L687

I guess you that you may need to url decode the uri before supplying it to `ngx.set_uri`.

Docs say:

```
Rewrite the current request's (parsed) URI by the uri argument. 
```

So either it is a bug in OpenResty, or it is expected behavior and requires you to decode before setting it.

**Comment by bungle** [comment]
@tecnobrat If you have time mind you changing the line:
https://github.com/Mashape/kong/blob/master/kong/core/router.lua#L687

that has code:

```lua
ngx.req.set_uri(new_uri)
```

with

```lua
ngx.req.set_uri(ngx.unescape_uri(new_uri))
```

And report back if it had any effect.

**Comment by tecnobrat** [comment]
@bungle I'll try giving it a shot, I'll need to do some docker-fu and report back :)

**Comment by tecnobrat** [comment]
Hey @bungle yep, that worked.

**Comment by dag24** [comment]
This also worked for me, thanks.

**Comment by thibaultcha** [comment]
I have created a regression test at #2519, but this test exposes that the currently proposed fix is incomplete. I believe that with this fix, Kong is making the upstream request with *unescaped* URIs (`/auth|123`) instead. Could you check? Thanks!

**Comment by p0pr0ck5** [comment]
@thibaultcha isn't the point here that the upstream request should be unescaped? @tecnobrat isn't that what you're looking for?

**Comment by thibaultcha** [comment]
No, the point is that Kong needs to be as transparent as possible, and an escaped request from downstream should be forwarded upstream as an escaped request as well. This is the expectation we set when we qualify Kong as a "transparent proxy".

**Comment by tecnobrat** [comment]
@thibaultcha is correct.

The request was pre-escaped.  It should be escaped when it hits the resulting upstream.  Currently its escaping it TWICE.  But it most certainly should not be unescaped completely.

However the request was made to kong, it should be made to the upstream.

**Comment by thibaultcha** [comment]
Thanks for confirming that @tecnobrat.

> However the request was made to kong, it should be made to the upstream.

That is indeed the expectation one might have, and certainly the one we'd like to promise, but we are limited by the current APIs that Nginx/OpenResty are offering us. We are investigating fixes, but so far we don't have a definitive one.

**Comment by pklingem** [comment]
is there any news on this?  it's preventing us from upgrading from 0.9.x.

**Comment by thibaultcha** [comment]
I just updated #2519 with a fix that ensures we transparently proxy request URIs (without further escaping/un-escaping). Could you give it a try on your side and let us know? Thanks!
