### ISSUE TITLE
Incorrect documentation regarding Supported Content Types

### ISSUE THREAD

**Issue by npetzall** [Mashape/kong#2516]
### Summary
Documentation is incorrect.

https://getkong.org/docs/0.10.x/admin-api/

Section: Supported Content Types

`x-www-form-urlencoded` is not supported
`application/x-www-form-urlencoded` is supported

### Steps To Reproduce

1, Do a post with "Content-Type: x-www-form-urlencoded"
2, Look confused
3, Use curl --data without headers
4, It works.....but why
5, Run curl with -v
6, Notice it says "Content-Type: application/x-www-form-urlencoded"

### Additional Details & Logs

Docker image: kong:0.10.1

**Comment by p0pr0ck5** [comment]
Thanks @npetzall. The docs are open sourced and available at https://github.com/mashape/getkong.org. Feel free to create a PR to adjust this. Thank you!
