### ISSUE TITLE
issue with routing order for APIs define with method and uri

### ISSUE THREAD

**Issue by leonzz** [Mashape/kong#2522]
### Summary

if 2 APIs are defined with an overlapping base path and the same method. kong router won't be able to make the correct route.

### Steps To Reproduce

1. define one API as: `name: "base"`, `uris: "/basepath"` and `methods: "GET"`
2. define another API as `name: "subdir"`, `uris: "/basepath/subdir"` and `methods: "GET"`
3. make a request to `GET /basepath/subdir/xyz`, which should be routed to the second API `subdir`, but kong would incorrectly route it to the first API `base`.

### Additional Details & Logs

- Kong version 0.10.1
- Operating System Ubuntu 16.04

**Comment by thibaultcha** [comment]
Fixed with #2523, thank you!
