### ISSUE TITLE
Websocket Upgrade issue

### ISSUE THREAD

**Issue by gottfrois** [Mashape/kong#2525]
### Summary

Kong respond with a `HTTP/1.1 426 Upgrade Required` on WebSocket requests

### Steps To Reproduce

1. Configure an API into Kong with the following parameters:

```
curl -i -X PATCH \
  --url http://kong.local:8001/apis/ \
  --data 'name=ws-api' \
  --data 'preserve_host=true' \
  --data 'upstream_url=http://ws-api.mywebsite.com:8989' \
  --data 'strip_uri=false' \
  --data 'preserve_host=true' \
  --data 'https_only=false' \
  --data 'hosts=ws-api.mywebsite.com'
```

2. Issue the following Curl command:

```
$ curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: ws-api.mywebsite.com" https://ws-api.mywebsite.com/ws
HTTP/1.1 426 Upgrade Required
Cache-Control: no-store, no-cache, must-revalidate, max-age=0
Content-Type: text/plain; charset=UTF-8
Date: Mon, 15 May 2017 09:36:48 GMT
Pragma: no-cache
Server: nginx
Via: kong/0.10.2
X-Kong-Proxy-Latency: 90
X-Kong-Upstream-Latency: 5
Content-Length: 16
Connection: keep-alive

Upgrade Required%
```

### Additional Details & Logs

```
uname -a
Linux 8de9c6abf39d 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
kong version
0.10.2
tail -f /usr/local/kong/logs/access.log
90.86.62.209 - - [15/May/2017:09:45:50 +0000] "GET /ws HTTP/1.1" 426 27 "-" "curl/7.51.0"
```

- default nginx configuration
- no logs in `error.log`
- CORS plugin setup but disabled

**Comment by p0pr0ck5** [comment]
@gottfrois just to clarify, what do you see when you issue the same request to the upstream directly instead of going through Kong?

Also, can you enable debug log levels in Kong and replay this attack, and post the results?

**Comment by p0pr0ck5** [comment]
@gottfrois ping?

**Comment by gottfrois** [comment]
Sorry about that, I actually figured this one out and it was an issue on the LB before ;)

**Comment by mlehner616** [comment]
@gottfrois what was the issue with the LB before? i think I’m running into this with an AWS Alb in front of Kong which terminates TLS.

**Comment by gottfrois** [comment]
@mlehner616 yes we had to customize the AWS LB listeners to use TCP instead of HTTP
