### ISSUE TITLE
Plugins cannot be manipulated by name 

### ISSUE THREAD

**Issue by lostphilosopher** [Mashape/kong#2527]
### Summary

Per the Kong (0.10.x) documentation a user should be able to [delete a Plugin](https://getkong.org/docs/0.10.x/admin-api/#delete-plugin) or [update a Plugin](https://getkong.org/docs/0.10.x/admin-api/#update-plugin) by "{plugin name or id}". [Note: The docs may change reflect this issue.]

However, as of [0.10.2](https://github.com/Mashape/kong/tree/0.10.2) the [router](https://github.com/Mashape/kong/blob/0.10.2/kong/api/routes/apis.lua) only supports [finding the plugin by id](https://github.com/Mashape/kong/blob/0.10.2/kong/api/routes/apis.lua#L58). 

### Steps To Reproduce

1. Create an API and add a Plugin to it.
2. Try to delete (for example) that Plugin from that API by name, **not id**.
3. Your response body will include `"<plugin name> is not a valid uuid"`.

### Additional Details & Logs

- Kong version `0.10.2` (issue relevant to `0.10.x`)

**Comment by lostphilosopher** [comment]
See also: https://github.com/Mashape/getkong.org/pull/419 this would update the docs to accurately reflect features.

**Comment by p0pr0ck5** [comment]
Marking this as a bug until the docs are noted otherwise.

**Comment by p0pr0ck5** [comment]
Sorry, I'm a dummy, this was already done in https://github.com/Mashape/kong/pull/2252 and will be released in Kong 0.11. Thanks for the report!
