### ISSUE TITLE
Request logs include Authorization header contents in plain text

### ISSUE THREAD

**Issue by braedon** [Mashape/kong#2532]
### Summary

Request logs produced by the logging plugins include the request headers, including the `Authorization` header which often includes sensitive auth information, e.g. basic auth credentials or bearer tokens. These should be removed/redacted/hashed(?) before logging.

Note that some systems may put sensitive information in other places that end up in these logs. A generic way to configure which headers/parameters/etc. to suppress would be useful.

### Steps To Reproduce

1. Configure a logging plugin,
2. Make a request with an Authorization header set,
3. Check logs for Authorization header contents.

### Additional Details & Logs

- Kong version 0.10.2
- UDP logging plugin (I presume it affects the other plugins too, but didn't check)

**Comment by p0pr0ck5** [comment]
@braedon each authentication plugin has a field `hide_credentials` that prevents the query param (or header) from being passed upstream; this would also remove the associated key from the log serializer.

**Comment by braedon** [comment]
@p0pr0ck5 I did consider this. Unfortunately I need to pass the header upstream so that isn't an option.

**Comment by p0pr0ck5** [comment]
Ok, just picking at the low hanging fruit :)

This would likely fall into the discussion of making log serializers a configurable facet of kong, which is being tracked and discussed at https://github.com/Mashape/kong/issues/1758, among other places.

**Comment by braedon** [comment]
No worries.

Fully configurable log serialization would be great for solving this. I would point out, however, this that this specific case, being related to security, seems like it should have significantly higher priority than https://github.com/Mashape/kong/issues/1758 in general. i.e. if https://github.com/Mashape/kong/issues/1758 isn't happening soon, I'd like to see a less generic fix for this,

**Comment by p0pr0ck5** [comment]
If you'd like to submit a patch, we'd be happy to take a look. :)

However, from a risk management and mitigation standpoint, if one is truly concerned about the contents of log files being shipped, they're either a). sent over a controlled, trusted network (notwithstanding a defense-in-depth argument), or b). encrypting before shipping contents over a public pipe (i.e. via HTTPS via the http-log plugin), and as for at-rest data, the reception endpoint could be configured to sieve sensitive data as appropriate.

Not saying you don't have a valid point, just offering a separate infosec view :)

**Comment by p0pr0ck5** [comment]
I realized this was brought up in #913, so going to close this as a dup. Thanks @braedon for the conversation contribution!
