### ISSUE TITLE
Querystring format in Request Transformer

### ISSUE THREAD

**Issue by harryparmar** [Mashape/kong#2534]
Querystring format in documentation says to use format new-param:some_value but in practice only works when new-param=some_value. This is causing third party tools to break as well for example Kongfig and Konga

### Steps To Reproduce

1. Setup RT plugin on kong endpoint

### Additional Details & Logs

- Kong version (`0.10.1`)

**Comment by p0pr0ck5** [comment]
Sounds like the docs need to be updated; would you mind opening a PR at https://github.com/mashape/getkong.org? Thank you!
