### ISSUE TITLE
load balancer is abnormal when the uris=["/"]  ?

### ISSUE THREAD

**Issue by shaowin16** [Mashape/kong#2542]
The Kong version is kong:0.10.2 and the database is postgres:9.4.
When i add the follow API,upstream,target to load balance,it has some exceptions.

First,i add the api:

```
POST:http://${kong_ip}:8001/apis

{
	
"methods": [
               "POST",
		"PUT",
		"GET",
		"DELETE"
  ],
  "upstream_url": "http://ab-web",
  "https_only": false,
  "name": "ab-web",
	"uris":["/"],
	"strip_uri":false
}
```
the upstream:

```
POST:http://${kong_ip}:8001/upstreams

{"name":"ab-web"}
```
and the target:

```
POST:http://${kong_ip}:8001/upstreams/ab-web/targets

{
	"target": "139.1.2.12:3006",
	"weight": 2
}
```
Now,i request the url:  http://${kong_ip}:8000 and it can proxy normally the url: http://139.1.2.12:3006(a microService)

Second,i add the api

```
POST:http://${kong_ip}:8001/apis

{
	
   "methods": [
                "POST",
		"PUT",
		"GET",
		"DELETE"
  ],
  "upstream_url": "http://ab-system",
  "https_only": false,
  "name": "ab-system",
	"uris":["/system"],
	"strip_uri":false
}
```
the upstream:

```
POST:http://${kong_ip}:8001/upstreams

{"name":"ab-system"}
```
and the target:

```
POST:http://${kong_ip}:8001/upstreams/ab-system/targets

{
	"target": "139.1.2.12:8323",
	"weight": 2
}
```
Now, i request the url:  http://${kong_ip}:8000/system/api/v1/users and it can't proxy normally the url: http://139.1.2.12:8323/system/api/v1/users

The second step can proxy normally sometime and  can't proxy normally sometime.

When the  apis is not include uris=["/"], the all api can proxy normally.

why?

**Comment by p0pr0ck5** [comment]
Can you please provide some more detail about

> The second step can proxy normally sometime and can't proxy normally sometime.

What do you mean "can't proxy"? Do you receive an error? A timeout? What specifically is the problem you're seeing? How often does this occur?

**Comment by psarrazin** [comment]
I guess that the "/" rule has the highest priority.
Check the order of the rules when you request the apis list.

Regards

**Comment by p0pr0ck5** [comment]
Also @sarraz1 it sounds like this was possibly resolved with https://github.com/Mashape/kong/pull/2523. Can you try your environment with Kong 0.10.3 and let us know if you still see any issues?

**Comment by p0pr0ck5** [comment]
sarraz1 ping :)

**Comment by sarraz1** [comment]
I will try, but not yet. For the moment, I can't update my kong environment with the 0.10.3.

**Comment by p0pr0ck5** [comment]
Would you be able to try with the patch noted in #2523?

**Comment by p0pr0ck5** [comment]
I was able to duplicate this behavior in 0.10.2, and not able to duplicate it with the patch noted above (or on 0.10.3). @sarraz1 let us know if you still see this behavior on 0.10.3 and we can reexamine this issue, but I believe your problem has been resolved in the latest release. Thanks!
