### ISSUE TITLE
kong redirect 'SELECT upsert_ttl' to slave through pgpool2

### ISSUE THREAD

**Issue by toby2** [Mashape/kong#2550]
### version info
- Kong version 0.10.2
- pgpool2 version 3.6.3
- postgres version  9.4.11

### host info
- kong 192.16.0.1
- vip    192.16.0.2
- pgpool 192.16.0.3   bind vip 192.16.0.2
- postgres master  192.16.0.4
- postgres slave     192.16.0.5

### Steps To Reproduce

1.config vip 192.16.0.2 to kong.conf
2.kong start
3.there are some errors in log file
[error] 17314#0: *1046 [lua] cluster.lua:20: log(): [cluster] could not update node in datastore:[postgres error] ERROR: cannot execute UPDATE in a read-only transaction, context: ngx.time

 [error] 21899#0: *33227 [lua] cluster.lua:20: log(): [cluster] could not update node in datastore:[postgres error] ERROR: function upsert_ttl(unknown, unknown, unknown, unknown, timestamp without time zone) does not exist (12), context: ngx.timer

### Summary
Pgpool redirect  'SELECT upsert_ttl' to postgres slave.  unfortunately, slave process read request only , but upsert_ttl have some insert operation. above errors occur.

should kong add  /*NO LOAD BALANCE*/  with below sql?

SELECT upsert_ttl('localhost.localdomain_0.0.0.0:7946_9a0dd35c94334021bd13d46ec96e0adc', NULL, 'name', 'nodes', to_timestamp(1495510800000/1000) at time zone 'UTC')；

**Comment by toby2** [comment]
http://www.pgpool.net/docs/pgpool-II-3.6.3/doc/en/html/runtime-config-load-balancing.html#RUNTIME-CONFIG-LOAD-BALANCING-IN-STREAMING-RAPLICATION

Note: If you don't want a query that qualifies for the load balancing to be load balanced by Pgpool-II, you can put /*NO LOAD BALANCE*/ comment before the SELECT statement. This will disable the load balance of the particular query and Pgpool-II will send it to the master node (the primary node in Master Slave mode).

**Comment by p0pr0ck5** [comment]
@toby2 thanks for the report. This is a result of how we handle object TTLs in postgres. In the future we plan on replacing this upsert mechanism with a more performant solution; for now I'm not sure that adding this comment (even though it's just a comment) for one particular use case is warranted.

**Comment by p0pr0ck5** [comment]
(Although TBH this sounds like a bit of a limitation in pgpool; perhaps it shouldn't shard SELECTs against functions?)

**Comment by toby2** [comment]
Stand in pgpool's position; There were two types of function,  include  read and read-write function. 
In order to be flexible enough, developer decide what kind of sql could be sent to the master node.
I think this issue should be resolved.

**Comment by p0pr0ck5** [comment]
Closing based on the above comment.
