### ISSUE TITLE
docker cloud swarm and upstream urls

### ISSUE THREAD

**Issue by andy9775** [Mashape/kong#2568]
### Summary
When trying to configure an api when running in docker (swarm or otherwise) and using link names or service names as the upstream url, the upstream does not resolve.

I've tried this configuration in both non-swarm mode (using links) via docker cloud as well as swarm mode.

An example file would be:
```
curl -i -X POST http://localhost:8001/apis/ \
  --data 'name=api' \
  --data 'uris=/' \
  --data 'strip_uri=false' \
  --data "https_only=true" \
  --data "upstream_url=my-api"
```
Where `my-api` is exposed on port 80

### Additional Details & Logs

- Kong version (`0.10.2`)
- operating system (`centos 7`)
All of this is configured via a docker image. Further, when querying the postgres database, the api is registered in the table. Also, if using environment variables which resolve to the IP address of the upstream service it works fine.

**Comment by thefosk** [comment]
You need to specify the protocol in the `upstream_url`, ie `http://my-api`. Have you tried setting the protocol?

**Comment by andy9775** [comment]
Actually I had it specified and it didn't work. 

It's now resolved but the problem was a combination of 2 issues:

1. My docker compose file was misconfigured
2. Docker takes a while to build its network therefore you have to wait a few minutes before it starts working - changes aren't immediate

Otherwise kong works perfectly well when it comes to proxying to upstream docker service via the service name.
