### ISSUE TITLE
my upstream url is not called without the configured parameters

### ISSUE THREAD

**Issue by simocl** [Mashape/kong#2573]
### Summary

I configured my private hook with an upstream_url like this: http://my-api.com?apikey=234523
When I called my public api, I observed that upstream_url is called without the apikey=234523.
How to ensure that kong calls my upstream_url with the configured parameter?  I created my API with the following settings:

{"strip_uri":"false"}

### Steps To Reproduce

1. create an API with the following upstream_url  http://my-api.com?apikey=234523
2. observe that the upstream url is called without apikey=234523
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
0.10.2

**Comment by bungle** [comment]
I suppose you could try this:
https://getkong.org/plugins/request-transformer/

**Comment by simocl** [comment]
Thanks that should work :-)
