### ISSUE TITLE
Config Kong tracking $upstream_response_time on log file ?

### ISSUE THREAD

**Issue by hungpt91** [Mashape/kong#2575]
How can i config Kong to tracking $upstream_response_time like Nginx's log ?
https://lincolnloop.com/blog/tracking-application-response-time-nginx/
Tks.

*Note: GitHub issues should be reserved only for bug reports. Please use the
[Kong mailing list](https://groups.google.com/forum/#!forum/konglayer) or
[Gitter](https://gitter.im/Mashape/kong) for user support, development
questions, feature requests, etc.*

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by p0pr0ck5** [comment]
Hi @hungpt91,

Kong already provides this value in any logging plugin as part of the `latencies` family of data points. See https://getkong.org/plugins/tcp-log/ for an example and description of these.

Also please note, as was noted in the boilerplate presented to you when you open this issue, that Github issues should be reserved for actual issues running Kong, not support questions. lease use the
Kong mailing list or Gitter for user support, development questions, feature requests, etc. Doing so reduces overhead for the Kong team and allows us to continue best serving the community. Thank you.
