### ISSUE TITLE
Permission of Cassandra's user

### ISSUE THREAD

**Issue by vinceFr44** [Mashape/kong#2576]
Hi,

for a security constraints, i need restrict permissions of my cassandra's user (limit permissions on keyspace kong). 
I tested to create a keyspace empty, but the first start of kong run "CREATE KEYSPACE IF NOT EXIST (...)" and cassandra return errors (even if keystore exist).

What are your recommendations for user permissions?

*****
Kong : 0.10.3 (Docker)
Cassandra : 3.10
*****

Regards,
Vincent

**Comment by thibaultcha** [comment]
Feel free to read up on Cassandra authentication/authorization online, reading the appropriate resources (Datastax is a good one). I recommend that you create the keyspace yourself, manually, with the appropriate user for more flexibility.

> and cassandra return errors

We can't help you if you don't tell us what the error is.
