### ISSUE TITLE
request-transformer plugins are not backward compatible in Kong 0.10.3

### ISSUE THREAD

**Issue by ryancutter** [Mashape/kong#2580]
### Summary

Not really a big deal but request-transformer doesn't appear to be backward compatible.  Had the request-transformer plugin on an API with only a 'config.add.body' value.  Upgraded from Kong 0.9.x to 0.10.3.  Encountered the following error.  Deleted and re-added the request-transformer to resolve this issue.

```
2017/05/30 23:00:03 [debug] 69#0: *824 [lua] base_plugin.lua:24: access(): executing plugin "request-transformer": access
2017/05/30 23:00:03 [error] 69#0: *824 lua entry thread aborted: runtime error: ...hare/lua/5.1/kong/plugins/request-transformer/access.lua:334: attempt to index field 'rename' (a nil value)
stack traceback:
coroutine 0:
	...hare/lua/5.1/kong/plugins/request-transformer/access.lua: in function 'transform_body'
	...hare/lua/5.1/kong/plugins/request-transformer/access.lua:383: in function 'execute'
	...are/lua/5.1/kong/plugins/request-transformer/handler.lua:12: in function 'access'
	/usr/local/share/lua/5.1/kong.lua:295: in function 'access'
	access_by_lua(nginx.conf:87):2: in function <access_by_lua(nginx.conf:87):1>, client: 172.18.72.41, server: kong, request: "POST /foo HTTP/1.1", host: "localhost"
```

### Steps To Reproduce

1. Add a request-transformer using Kong 0.9.x
2. Upgrade to Kong 0.10.x
3. Send a request to the API using the request-transformer created in step 1

**Comment by thibaultcha** [comment]
Hi,

If you are using Postgres, then you are hitting a known issue which is the lack of migrations for 0.10 and this plugin. It is addressed in #2499. Can you confirm?

**Comment by ryancutter** [comment]
Yes, I'm using Postgres.  Looks great, thanks!

**Comment by thibaultcha** [comment]
Ok, closing this in the meanwhile then :)
