### ISSUE TITLE
Bug: preflight_continue=true

### ISSUE THREAD

**Issue by Bl4ckM** [Mashape/kong#259]
Hi found the reason, why i had some probs with my request. With preflight_continue=true kong adds incoming header to its header. So one problem is:

(Reason: CORS-Header 'Access-Control-Allow-Origin' don't fit '*, *')

default-Value for Origin is *. My Server return also an * in its header for the request. Kong concatenate the headers to *,*. This produce the already shown error above and no cross site request could pass kong. Any Ideas or could you fix this?

**Comment by Bl4ckM** [comment]
Do some Quick'n'Dirty fix. Just saw that you strip Linux Variables out of your URL Requests, so just add data with --data "variable.origin=$test", so your API delete my variable and add only "" + incoming * to the header file. That results in only one * in Origin and enable my cross site requests

**Comment by thefosk** [comment]
Pinging @Nijikokun who built the plugin

**Comment by Bl4ckM** [comment]
I think the problem is that the 2 header got concatenated. Just ignore your defaults and add only the header behind kong.

**Comment by Nijikokun** [comment]
It appears that this is due to how NGiNX treats the headers table, instead of overwriting a value, it adds another header with the same name and then concatenates them in the response.

**Comment by thefosk** [comment]
@Nijikokun to set an output header that overrides the proxied header, you need to use [`header_filter_by_lua`](http://wiki.nginx.org/HttpLuaModule#header_filter_by_lua)

**Comment by sinzone** [comment]
@Nijikokun ping

**Comment by thefosk** [comment]
I will look into this.

**Comment by thefosk** [comment]
Related to #241

**Comment by t1tcrucible** [comment]
+1
We are having the same issue; When an upstream server has already CORS enables, the CORS plugin should deal with it.

**Comment by mjhlobdell** [comment]
+1 Same issue.  Please fix.

**Comment by t1tcrucible** [comment]
Some additional info on why some APIs have CORS enabled as well. For some APIs registered on Kong, the API has an admin interface, which is not using the gateway to request the API (with restricted access). The admin interface used - mainly for maintenance and some other management tasks - triggers CORS from the browser. When we disable CORS from the API and add CORS policy on Kong, that's ok for integrating consumers, but not for those 'admin interfaces' going directly to the API.

**Comment by sinzone** [comment]
@thefosk  ^

**Comment by shashiranjan84** [comment]
I have been through the code, plugin intercept the request and update all the headers according to configuration. If `preflight_continue` is set then request would be upstreamed. Seems like upstream server also updating the `Access-Control-Allow-Origin` header , which in above case concatenating the `*` . Once solution can be the Upstream server should itself check if CORS headers already set. Another solution would be handling the modification of CORS headers in `body_filter` context if `preflight_continue` is set otherwise in `access` context.

**Comment by thefosk** [comment]
Hello - I have pushed a PR (#1240) that seems to be fixing this problem. Could you try it and let me know if it effectively closes this issue? (@Bl4ckM @t1tcrucible @mjhlobdell)

**Comment by t1tcrucible** [comment]
Thank you @thefosk, we'll test it out and provide feedback

**Comment by thefosk** [comment]
@t1tcrucible if you guys could test it within 24h, and it works, I will make sure to include it in the 0.8.2 release on Wednesday

**Comment by t1tcrucible** [comment]
hi @thefosk it works, sorry for the late reply - but already in release :-). Thank you very much!

**Comment by thefosk** [comment]
Perfect - 0.8.2 has been just released.
