### ISSUE TITLE
Picture check code redirect to origin url

### ISSUE THREAD

**Issue by qingziguanjun** [Mashape/kong#2593]
how can i proxy a url return a check code picture?when i do this,i call the proxy url,but the kong will move Moved Permanently to the origin source url,this will dispose my url,how can i fix it?

**Comment by qingziguanjun** [comment]
@p0pr0ck5 @nikz

**Comment by p0pr0ck5** [comment]
Closing this as it was x-posted to multiple environments. In the future, please take note of the issue boilerplate:

NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help
