### ISSUE TITLE
kong proxy dispose origin url 

### ISSUE THREAD

**Issue by qingziguanjun** [Mashape/kong#2594]
The Kong version is kong:0.10.2 and the database is postgres:9.4.
when i  paste the proxy url in chrome ,the kong will move Moved Permanently to the origin source url,this will dispose my url.

First,i add a proxy url:

  curl -i -X POST \
  --url http://localhost:8001/apis/ \
  --data 'name=check-image' \
  --data 'uris=/checkImage' \
  --data 'hosts=kong.d.internetware.cn' \
  --data 'upstream_url=http://api.internetware.cn/social5'

then i paste call url in chrome:  kong.d.internetware.cn/checkImage?iw-cmd=110000_CW0061&iw-apikey=123
but the url will finally redirect to "http://api.internetware.cn/social5/?iw-cmd=110000_CW0061&iw-apikey=123"
i get the result,but it dispose my proxy url ,how can i fix it?

**Comment by p0pr0ck5** [comment]
Hi,

Enable the `strip_uri` property on your API object to enable the behavior you're looking for: https://getkong.org/docs/0.10.x/proxy/#the-strip_uri-property.

**Comment by qingziguanjun** [comment]
default strip_uri property  is true , so it can not sovle the  problem

**Comment by ioneyed** [comment]
If I understand correctly, you are looking to keep the url "kong.d.internetware.cn" ? If so I belive you could use the `preserve_host` property (https://getkong.org/docs/0.10.x/proxy/#the-preserve_host-property)
