### ISSUE TITLE
Timeout when I add a plugin in the version of 0.10.3

### ISSUE THREAD

**Issue by rosehua** [Mashape/kong#2596]
### Summary
**When I add a plugin , the response data returns very slowly. Then I check the error.log file and export KONG_LOG_LEVEL=debug.
I find the error:**
```
2017/06/02 13:25:38 [debug] 22464#0: *504 [lua] client.lua:531: lookup(): [dns-client] querying 'kong-hf.mashape.com' for type 33 took 10000
2017/06/02 13:25:38 [debug] 22464#0: *504 [lua] client.lua:533: lookup(): [dns-client] querying: 'kong-hf.mashape.com' for type 33 error: failed to receive reply from UDP server 10.135.9.15:53: timeout
2017/06/02 13:25:48 [debug] 22464#0: *504 [lua] client.lua:531: lookup(): [dns-client] querying 'kong-hf.mashape.com' for type 1 took 10000.999927521
2017/06/02 13:25:48 [debug] 22464#0: *504 [lua] client.lua:533: lookup(): [dns-client] querying: 'kong-hf.mashape.com' for type 1 error: failed to receive reply from UDP server 10.135.9.15:53: timeout
2017/06/02 13:25:58 [debug] 22464#0: *504 [lua] client.lua:531: lookup(): [dns-client] querying 'kong-hf.mashape.com' for type 28 took 10001.999855042
```
**It seems that my DNS server can't query the domain kong-hf.mashape.com. I use Kong in my internal network and my DNS server ip is 10.135.9.15, Our internal  network is limited and it can not connect to the external network, so it can't resolve the domain name kong-hf.mashape.com. How to edit my Configuration file to avoid Kong lookup the domain name kong-hf.mashape.com when I add a plugin in my internal network. Thank you very much!**

**Comment by Tieske** [comment]
not entirely sure, but probably the anonymous reports. You can turn them of in the config file iirc.

**Comment by p0pr0ck5** [comment]
Yes, disable reporting by setting `anonymous_reports off` in the Kong config file: https://getkong.org/docs/0.10.x/configuration/.

**Comment by rosehua** [comment]
@p0pr0ck5 Thank you very much, According to that configuration, the problem has been solved.
