### ISSUE TITLE
http host routing problem

### ISSUE THREAD

**Issue by saga1015** [Mashape/kong#2597]
kong version: 0.10.3
Problem description:
Default,Our APIs are use nginx $host or $http_host to do http routing.  But, only one api cann't use $host or $http_host to do http routing ,we add header $http_AppHost to do http routing.  
on kong 0.9.x
we add line in nginx_kong.lua
location / {
        set $upstream_host nil;
        set $upstream_url nil;
        if ($http_AppHost) {
           set $upstream_host $http_AppHost;
        }
        access_by_lua_block {
            kong.access()
        }

it's work fine.
But on Kong 0.10.3. it's not work for me.
I think i can modify router.lua to do that ,but I don't know how to modify,please help me.  
Thanks very very much :-)

**Comment by p0pr0ck5** [comment]
@saga1015 so you were using a custom Nginx template before? Is there any reason you cannot do so now? We definitely don't recommend modifying Kong source directly :)

**Comment by saga1015** [comment]
@p0pr0ck5 yes,I were useing custom nginx_kong.lua before.
now my team don't modifying Kong 0.10.3 source, we read the kong 0.10.x doc, solved our problems.
thanks very much :-)

**Comment by p0pr0ck5** [comment]
Wonderful, thank you!

**Comment by ronak15** [comment]
@saga1015, can you say what exactly did you do to get this issue resolved?  I am trying to do the same thing and we are stuck since it used to work with 0.9 but not with 0.10.  TIA.

**Comment by blixathecat** [comment]
What exactly did you do to resolve the issue? 0.9 but not with 0.10.3.

**Comment by ronak15** [comment]
We ended up writing our own plugin that would do the routing!
