### ISSUE TITLE
Unable to start Kong (0.10.3)

### ISSUE THREAD

**Issue by theashwin007** [Mashape/kong#2599]
After installing kong(0.10.3) via pkg, I am not unable to run kong. It gives below error 

/Users/akumar $ kong restart --conf /etc/kong/kong.conf --vv
2017/06/05 16:48:02 [verbose] Kong: 0.10.3
2017/06/05 16:48:02 [debug] ngx_lua: 10007
2017/06/05 16:48:02 [debug] nginx: 1011002
2017/06/05 16:48:02 [debug] Lua: LuaJIT 2.1.0-beta2
2017/06/05 16:48:02 [verbose] reading config file at /etc/kong/kong.conf
2017/06/05 16:48:02 [debug] admin_access_log = "logs/admin_access.log"
2017/06/05 16:48:02 [debug] admin_error_log = "logs/error.log"
2017/06/05 16:48:02 [debug] admin_listen = "0.0.0.0:8001"
2017/06/05 16:48:02 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/06/05 16:48:02 [debug] admin_ssl = true
2017/06/05 16:48:02 [debug] anonymous_reports = true
2017/06/05 16:48:02 [debug] cassandra_consistency = "ONE"
2017/06/05 16:48:02 [debug] cassandra_contact_points = {"127.0.0.1"}
2017/06/05 16:48:02 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/06/05 16:48:02 [debug] cassandra_keyspace = "kong"
2017/06/05 16:48:02 [debug] cassandra_lb_policy = "RoundRobin"
2017/06/05 16:48:02 [debug] cassandra_port = 9042
2017/06/05 16:48:02 [debug] cassandra_repl_factor = 1
2017/06/05 16:48:02 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/06/05 16:48:02 [debug] cassandra_schema_consensus_timeout = 10000
2017/06/05 16:48:02 [debug] cassandra_ssl = false
2017/06/05 16:48:02 [debug] cassandra_ssl_verify = false
2017/06/05 16:48:02 [debug] cassandra_timeout = 5000
2017/06/05 16:48:02 [debug] cassandra_username = "kong"
2017/06/05 16:48:02 [debug] client_ssl = false
2017/06/05 16:48:02 [debug] cluster_listen = "0.0.0.0:7946"
2017/06/05 16:48:02 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/06/05 16:48:02 [debug] cluster_profile = "wan"
2017/06/05 16:48:02 [debug] cluster_ttl_on_failure = 3600
2017/06/05 16:48:02 [debug] custom_plugins = {"request-validate-userid","request-validate-userid-in-header"}
2017/06/05 16:48:02 [debug] database = "cassandra"
2017/06/05 16:48:02 [debug] dns_hostsfile = "/etc/hosts"
2017/06/05 16:48:02 [debug] dns_resolver = {}
2017/06/05 16:48:02 [debug] latency_tokens = true
2017/06/05 16:48:02 [debug] log_level = "info"
2017/06/05 16:48:02 [debug] lua_code_cache = "on"
2017/06/05 16:48:02 [debug] lua_package_cpath = ""
2017/06/05 16:48:02 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/06/05 16:48:02 [debug] lua_socket_pool_size = 30
2017/06/05 16:48:02 [debug] lua_ssl_verify_depth = 1
2017/06/05 16:48:02 [debug] mem_cache_size = "128m"
2017/06/05 16:48:02 [debug] nginx_daemon = "on"
2017/06/05 16:48:02 [debug] nginx_optimizations = true
2017/06/05 16:48:02 [debug] nginx_worker_processes = "auto"
2017/06/05 16:48:02 [debug] pg_database = "kong"
2017/06/05 16:48:02 [debug] pg_host = "127.0.0.1"
2017/06/05 16:48:02 [debug] pg_port = 5432
2017/06/05 16:48:02 [debug] pg_ssl = false
2017/06/05 16:48:02 [debug] pg_ssl_verify = false
2017/06/05 16:48:02 [debug] pg_user = "kong"
2017/06/05 16:48:02 [debug] prefix = "/usr/local/kong/"
2017/06/05 16:48:02 [debug] proxy_access_log = "logs/access.log"
2017/06/05 16:48:02 [debug] proxy_error_log = "logs/error.log"
2017/06/05 16:48:02 [debug] proxy_listen = "127.0.0.1:9900"
2017/06/05 16:48:02 [debug] proxy_listen_ssl = "127.0.0.1:9943"
2017/06/05 16:48:02 [debug] serf_path = "serf"
2017/06/05 16:48:02 [debug] server_tokens = true
2017/06/05 16:48:02 [debug] ssl = true
2017/06/05 16:48:02 [debug] ssl_cipher_suite = "modern"
2017/06/05 16:48:02 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2017/06/05 16:48:02 [debug] upstream_keepalive = 60
2017/06/05 16:48:02 [verbose] prefix in use: /usr/local/kong
2017/06/05 16:48:02 [verbose] reading config file at /etc/kong/kong.conf
2017/06/05 16:48:02 [debug] admin_access_log = "logs/admin_access.log"
2017/06/05 16:48:02 [debug] admin_error_log = "logs/error.log"
2017/06/05 16:48:02 [debug] admin_listen = "0.0.0.0:8001"
2017/06/05 16:48:02 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/06/05 16:48:02 [debug] admin_ssl = true
2017/06/05 16:48:02 [debug] anonymous_reports = true
2017/06/05 16:48:02 [debug] cassandra_consistency = "ONE"
2017/06/05 16:48:02 [debug] cassandra_contact_points = {"127.0.0.1"}
2017/06/05 16:48:02 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/06/05 16:48:02 [debug] cassandra_keyspace = "kong"
2017/06/05 16:48:02 [debug] cassandra_lb_policy = "RoundRobin"
2017/06/05 16:48:02 [debug] cassandra_port = 9042
2017/06/05 16:48:02 [debug] cassandra_repl_factor = 1
2017/06/05 16:48:02 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/06/05 16:48:02 [debug] cassandra_schema_consensus_timeout = 10000
2017/06/05 16:48:02 [debug] cassandra_ssl = false
2017/06/05 16:48:02 [debug] cassandra_ssl_verify = false
2017/06/05 16:48:02 [debug] cassandra_timeout = 5000
2017/06/05 16:48:02 [debug] cassandra_username = "kong"
2017/06/05 16:48:02 [debug] client_ssl = false
2017/06/05 16:48:02 [debug] cluster_listen = "0.0.0.0:7946"
2017/06/05 16:48:02 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/06/05 16:48:02 [debug] cluster_profile = "wan"
2017/06/05 16:48:02 [debug] cluster_ttl_on_failure = 3600
2017/06/05 16:48:02 [debug] custom_plugins = {"request-validate-userid","request-validate-userid-in-header"}
2017/06/05 16:48:02 [debug] database = "cassandra"
2017/06/05 16:48:02 [debug] dns_hostsfile = "/etc/hosts"
2017/06/05 16:48:02 [debug] dns_resolver = {}
2017/06/05 16:48:02 [debug] latency_tokens = true
2017/06/05 16:48:02 [debug] log_level = "info"
2017/06/05 16:48:02 [debug] lua_code_cache = "on"
2017/06/05 16:48:02 [debug] lua_package_cpath = ""
2017/06/05 16:48:02 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/06/05 16:48:02 [debug] lua_socket_pool_size = 30
2017/06/05 16:48:02 [debug] lua_ssl_verify_depth = 1
2017/06/05 16:48:02 [debug] mem_cache_size = "128m"
2017/06/05 16:48:02 [debug] nginx_daemon = "on"
2017/06/05 16:48:02 [debug] nginx_optimizations = true
2017/06/05 16:48:02 [debug] nginx_worker_processes = "auto"
2017/06/05 16:48:02 [debug] pg_database = "kong"
2017/06/05 16:48:02 [debug] pg_host = "127.0.0.1"
2017/06/05 16:48:02 [debug] pg_port = 5432
2017/06/05 16:48:02 [debug] pg_ssl = false
2017/06/05 16:48:02 [debug] pg_ssl_verify = false
2017/06/05 16:48:02 [debug] pg_user = "kong"
2017/06/05 16:48:02 [debug] prefix = "/usr/local/kong"
2017/06/05 16:48:02 [debug] proxy_access_log = "logs/access.log"
2017/06/05 16:48:02 [debug] proxy_error_log = "logs/error.log"
2017/06/05 16:48:02 [debug] proxy_listen = "127.0.0.1:9900"
2017/06/05 16:48:02 [debug] proxy_listen_ssl = "127.0.0.1:9943"
2017/06/05 16:48:02 [debug] serf_path = "serf"
2017/06/05 16:48:02 [debug] server_tokens = true
2017/06/05 16:48:02 [debug] ssl = true
2017/06/05 16:48:02 [debug] ssl_cipher_suite = "modern"
2017/06/05 16:48:02 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2017/06/05 16:48:02 [debug] upstream_keepalive = 60
2017/06/05 16:48:02 [verbose] prefix in use: /usr/local/kong
Error: 
/usr/local/share/lua/5.1/resty/cassandra/cluster.lua:190: attempt to call field 'new' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/resty/cassandra/cluster.lua:190: in function 'spawn_peer'
	/usr/local/share/lua/5.1/resty/cassandra/cluster.lua:201: in function 'check_peer_health'
	/usr/local/share/lua/5.1/resty/cassandra/cluster.lua:416: in function 'first_coordinator'
	/usr/local/share/lua/5.1/resty/cassandra/cluster.lua:488: in function 'refresh'
	/usr/local/share/lua/5.1/kong/dao/db/cassandra.lua:141: in function 'init'
	/usr/local/share/lua/5.1/kong/dao/db/cassandra.lua:89: in function 'new'
	/usr/local/share/lua/5.1/kong/dao/factory.lua:98: in function 'new'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:18: in function 'execute'
	/usr/local/share/lua/5.1/kong/cmd/restart.lua:13: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:40: in function <init_worker_by_lua:38>
	[C]: in function 'pcall'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
/Users/akumar $ 

### Additional Details & Logs

- Kong version : 0.10.3
- Operating System - MAC OS Sierra  10.12.3

**Comment by Tieske** [comment]
do you have multiple installs? or even Lua installations? the error reminds me of older lua-cassandra drivers.

so maybe your system is mixing Lua installations? check your paths.

**Comment by theashwin007** [comment]
I think I have just one version of lua - 5.1 

```
/usr/local/share/lua/5.1 $ luarocks path
export LUA_PATH='/Users/akumar/.luarocks/share/lua/5.1/?.lua;/Users/akumar/.luarocks/share/lua/5.1/?/init.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;./?.lua;/usr/local/share/luajit-2.1.0-beta2/?.lua'
export LUA_CPATH='/Users/akumar/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?.so;./?.so;/usr/local/lib/lua/5.1/loadall.so'```

BTW, first i tried to install via home brew , it installed successfully but I didn't find the executable, and then I installed via pkg. May be that screwed the things? 

 But as per the error( /usr/local/share/lua/5.1/resty/cassandra/cluster.lua:190: attempt to call field 'new' (a nil value)), I think below line is failing to get the cassandra instance  local cql = require 'cassandra.cql'...

**Comment by thefosk** [comment]
You can try to purge your local luarocks folder and install again.

`luarocks purge --tree=/usr/local`

and install Kong again.

**Comment by Tieske** [comment]
you probably need to clean your system, and use homebrew. We actually discussed removing the pkg distribution for mac just last week, as it is more cumbersome.

**Comment by theashwin007** [comment]
I tried cleaning up and reinstall ( luarocks purge --tree=/usr/local), I get the same above error as mentioned above. But when I tried to run kong from /usr/local/share/lua/5.1, looks like it is proceeding further and then giving below error trace. Any issue with the PATHs ..etc ?



/usr/local/share/lua/5.1 $ kong start -c /etc/kong/kong.conf -vv
2017/06/06 12:52:47 [verbose] Kong: 0.10.3
2017/06/06 12:52:47 [debug] ngx_lua: 10007
2017/06/06 12:52:47 [debug] nginx: 1011002
2017/06/06 12:52:47 [debug] Lua: LuaJIT 2.1.0-beta2
2017/06/06 12:52:47 [verbose] reading config file at /etc/kong/kong.conf
2017/06/06 12:52:47 [debug] admin_access_log = "logs/admin_access.log"
2017/06/06 12:52:47 [debug] admin_error_log = "logs/error.log"
2017/06/06 12:52:47 [debug] admin_listen = "0.0.0.0:8001"
2017/06/06 12:52:47 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/06/06 12:52:47 [debug] admin_ssl = true
2017/06/06 12:52:47 [debug] anonymous_reports = true
2017/06/06 12:52:47 [debug] cassandra_consistency = "ONE"
2017/06/06 12:52:47 [debug] cassandra_contact_points = {"127.0.0.1"}
2017/06/06 12:52:47 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/06/06 12:52:47 [debug] cassandra_keyspace = "kong"
2017/06/06 12:52:47 [debug] cassandra_lb_policy = "RoundRobin"
2017/06/06 12:52:47 [debug] cassandra_port = 9042
2017/06/06 12:52:47 [debug] cassandra_repl_factor = 1
2017/06/06 12:52:47 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/06/06 12:52:47 [debug] cassandra_schema_consensus_timeout = 10000
2017/06/06 12:52:47 [debug] cassandra_ssl = false
2017/06/06 12:52:47 [debug] cassandra_ssl_verify = false
2017/06/06 12:52:47 [debug] cassandra_timeout = 5000
2017/06/06 12:52:47 [debug] cassandra_username = "kong"
2017/06/06 12:52:47 [debug] client_ssl = false
2017/06/06 12:52:47 [debug] cluster_listen = "0.0.0.0:7946"
2017/06/06 12:52:47 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/06/06 12:52:47 [debug] cluster_profile = "wan"
2017/06/06 12:52:47 [debug] cluster_ttl_on_failure = 3600
2017/06/06 12:52:47 [debug] custom_plugins = {"request-validate-userid","request-validate-userid-in-header"}
2017/06/06 12:52:47 [debug] database = "cassandra"
2017/06/06 12:52:47 [debug] dns_hostsfile = "/etc/hosts"
2017/06/06 12:52:47 [debug] dns_resolver = {}
2017/06/06 12:52:47 [debug] latency_tokens = true
2017/06/06 12:52:47 [debug] log_level = "info"
2017/06/06 12:52:47 [debug] lua_code_cache = "on"
2017/06/06 12:52:47 [debug] lua_package_cpath = ""
2017/06/06 12:52:47 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/06/06 12:52:47 [debug] lua_socket_pool_size = 30
2017/06/06 12:52:47 [debug] lua_ssl_verify_depth = 1
2017/06/06 12:52:47 [debug] mem_cache_size = "128m"
2017/06/06 12:52:47 [debug] nginx_daemon = "on"
2017/06/06 12:52:47 [debug] nginx_optimizations = true
2017/06/06 12:52:47 [debug] nginx_worker_processes = "auto"
2017/06/06 12:52:47 [debug] pg_database = "kong"
2017/06/06 12:52:47 [debug] pg_host = "127.0.0.1"
2017/06/06 12:52:47 [debug] pg_port = 5432
2017/06/06 12:52:47 [debug] pg_ssl = false
2017/06/06 12:52:47 [debug] pg_ssl_verify = false
2017/06/06 12:52:47 [debug] pg_user = "kong"
2017/06/06 12:52:47 [debug] prefix = "/usr/local/kong/"
2017/06/06 12:52:47 [debug] proxy_access_log = "logs/access.log"
2017/06/06 12:52:47 [debug] proxy_error_log = "logs/error.log"
2017/06/06 12:52:47 [debug] proxy_listen = "127.0.0.1:9900"
2017/06/06 12:52:47 [debug] proxy_listen_ssl = "127.0.0.1:9943"
2017/06/06 12:52:47 [debug] serf_path = "serf"
2017/06/06 12:52:47 [debug] server_tokens = true
2017/06/06 12:52:47 [debug] ssl = true
2017/06/06 12:52:47 [debug] ssl_cipher_suite = "modern"
2017/06/06 12:52:47 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2017/06/06 12:52:47 [debug] upstream_keepalive = 60
2017/06/06 12:52:47 [verbose] prefix in use: /usr/local/kong
2017/06/06 12:52:47 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/06/06 12:52:47 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2017/06/06 12:52:47 [debug] searching for OpenResty 'resty' executable
2017/06/06 12:52:47 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.2'
2017/06/06 12:52:47 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2017/06/06 12:52:47 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2017/06/06 12:52:47 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/06/06 12:52:47 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2017/06/06 12:52:47 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2017/06/06 12:52:47 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2017/06/06 12:52:47 [warn] ulimit is currently set to "256". For better performance set it to at least "4096" using "ulimit -n"
2017/06/06 12:52:47 [verbose] running datastore migrations
2017/06/06 12:52:47 [verbose] migrations up to date
2017/06/06 12:52:47 [verbose] serf agent not running, deleting /usr/local/kong/pids/serf.pid
2017/06/06 12:52:47 [debug] searching for 'serf' executable
2017/06/06 12:52:47 [debug] serf version: 'Serf v0.7.0'
2017/06/06 12:52:47 [debug] found 'serf' executable at serf
2017/06/06 12:52:47 [debug] starting serf agent: nohup serf agent -profile 'wan' -bind '0.0.0.0:7946' -log-level 'err' -rpc-addr '127.0.0.1:7373' -event-handler 'member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf/serf_event.sh' -node 'macbook-pro-2.corp.bluejeans.com_0.0.0.0:7946_8ef2f9a098864cff8201798f66be5f11' > /usr/local/kong/logs/serf.log 2>&1 & echo $! > /usr/local/kong/pids/serf.pid
2017/06/06 12:52:47 [verbose] waiting for serf agent to be running
2017/06/06 12:52:47 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/06/06 12:52:47 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/06/06 12:52:47 [verbose] serf agent started
2017/06/06 12:52:47 [verbose] auto-joining serf cluster
2017/06/06 12:52:47 [verbose] no other nodes found in the cluster
2017/06/06 12:52:47 [verbose] registering serf node in datastore
2017/06/06 12:52:47 [verbose] cluster joined and node registered in datastore
2017/06/06 12:52:47 [debug] searching for OpenResty 'nginx' executable
2017/06/06 12:52:47 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.11.2.2'
2017/06/06 12:52:47 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2017/06/06 12:52:47 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2017/06/06 12:52:47 [verbose] could not start Kong, stopping services
2017/06/06 12:52:47 [verbose] leaving serf cluster
2017/06/06 12:52:47 [verbose] left serf cluster
2017/06/06 12:52:47 [verbose] stopping serf agent at /usr/local/kong/pids/serf.pid
2017/06/06 12:52:47 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/06/06 12:52:47 [debug] kill -15 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/06/06 12:52:47 [verbose] serf agent stopped
2017/06/06 12:52:47 [verbose] stopped services
Error: 
./kong/cmd/start.lua:34: ./kong/cmd/start.lua:23: nginx: [error] init_by_lua error: ./kong.lua:43: module 'kong.core.globalpatches' not found:Failed loading module kong.core.globalpatches in LuaRocks rock kong 0.10.3-0
	no field package.preload['kong.core.globalpatches']
	no file 'kong/core/globalpatches/init.lua'
	no file './kong/kong/core/globalpatches.lua'
	no file '/usr/local/openresty/site/lualib/kong/core/globalpatches.lua'
	no file '/usr/local/openresty/site/lualib/kong/core/globalpatches/init.lua'
	no file '/usr/local/openresty/lualib/kong/core/globalpatches.lua'
	no file '/usr/local/openresty/lualib/kong/core/globalpatches/init.lua'
	no file './kong/core/globalpatches.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/kong/core/globalpatches.lua'
	no file '/usr/local/share/lua/5.1/kong/core/globalpatches.lua'
	no file '/usr/local/share/lua/5.1/kong/core/globalpatches/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/kong/core/globalpatches.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/kong/core/globalpatches/init.lua'
	no file '/Users/akumar/.luarocks/share/lua/5.1/kong/core/globalpatches.lua'
	no file '/Users/akumar/.luarocks/share/lua/5.1/kong/core/globalpatches/init.lua'
	no file '/usr/local/openresty/site/lualib/kong/core/globalpatches.so'
	no file '/usr/local/openresty/lualib/kong/core/globalpatches.so'
	no file './kong/core/globalpatches.so'
	no file '/usr/local/lib/lua/5.1/kong/core/globalpatches.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/kong/core/globalpatches.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/akumar/.luarocks/lib/lua/5.1/kong/core/globalpatches.so'
	no file '/usr/local/openresty/site/lualib/kong.so'
	no file '/usr/local/openresty/lualib/kong.so'
	no file './kong.so'
	no file '/usr/local/lib/lua/5.1/kong.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/kong.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/akumar/.luarocks/lib/lua/5.1/kong.so'
stack traceback:
	[C]: in function 'require'
	./kong.lua:43: in main chunk
	[C]: in function 'require'
	init_by_lua:4: in main chunk

stack traceback:
	[C]: in function 'error'
	./kong/cmd/start.lua:34: in function 'cmd_exec'
	./kong/cmd/init.lua:88: in function <./kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	./kong/cmd/init.lua:88: in function <./kong/cmd/init.lua:45>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:40: in function <init_worker_by_lua:38>
	[C]: in function 'pcall'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>

**Comment by Tieske** [comment]
Yes, seems like a path issue to me.

**Comment by theashwin007** [comment]
Can you please suggest where I am doing wrong(w.r.t any lua path envs )? Or steps to clean and fresh install ?

**Comment by Tieske** [comment]
lua paths, see http://www.thijsschreijer.nl/blog/?p=1025

**Comment by p0pr0ck5** [comment]
Closing as stale. Feel free to reopen if there are any further questions. Thank you!
