### ISSUE TITLE
Kong API Gateway reorders the parameters and reponse payload.

### ISSUE THREAD

**Issue by Devin-Grant** [Mashape/kong#2601]
### Summary

If you send a request through Kong (see the example below) it will order the parameters which break my signature verification.

**Request**: https://localhost/v1/GetUser?userId=1&name=Foo
to
**Endpoint**: https://localhost/v1/GetUser?name=Foo&userId=1

### Additional Details & Logs

- Kong version (`0.10.2`)
- macOS Operating System

**Comment by Devin-Grant** [comment]
the issue is with the **request-transformer** plug-in.

**Comment by thibaultcha** [comment]
This is expected behavior indeed. Are you closing this because you found a workaround?

**Comment by Devin-Grant** [comment]
The work around is to not use the transformation plug-in.  As mentioned, we are use signatures that's base off of the URL order.  A user will generate a signature from the order that they specify in the request. If Kong alters the URL in any way, it will cause the signature to also change when the target endpoint validates it by regenerating the signature from the URL it receives from Kong.  Therefore, the signature verification will fail because the server will not match the client's signature. 

-Devin's iPhone

On Jun 5, 2017, at 6:13 PM, Thibault Charbonnier <notifications@github.com> wrote:

This is expected behavior indeed. Are you closing this because you found a workaround?
