### ISSUE TITLE
how to set api access times for a constumer

### ISSUE THREAD

**Issue by qingziguanjun** [Mashape/kong#2609]
When i use kong 0.10.0 proxy my url,i encounter a problem:
First, I want set access times for a constumer to an api,when the constumer call the proxy url with a key,
the access times will minus, eventually the times is zero, the constumer can not access the api ,but i can
again add the access times for  him ,and he can access again.

i know i should wirte my own plugin,but how can i do it? is there an doc?

**Comment by coopr** [comment]
You'll find docs on writing custom plugins for Kong here https://getkong.org/docs/0.10.x/plugin-development/

It seems you might be able to use the existing rate-limiting plugin https://getkong.org/plugins/rate-limiting/ by setting a rate limit - then, when a given user exceeds their limit, you can reconfigure the limit for that user to give them more access to the API. In your case, it is possible that setting a yearly limit would be ideal.

**Comment by qingziguanjun** [comment]
how can i know how many times remain for every consumer? I use  PostgreSQL 9.4, so i have to query  PostgreSQL 9.4 to get the remain times?
