### ISSUE TITLE
For rate-limiting plugin, how to get these X-Ratelimit-Limit-* values without calling url 

### ISSUE THREAD

**Issue by qingziguanjun** [Mashape/kong#2610]
For kong 0.10.0 wihte pgSql 9.4, I add a plugin:
	curl -X POST http://localhost:8001/apis/seqingshibie1/plugins \
    --data "name=rate-limiting" \
    --data "config.second=5" \
    --data "config.minute=15" \
    --data "config.hour=100"

every time i call the prxy url i get such response header:
X-Ratelimit-Limit-Hour →
X-Ratelimit-Limit-Hour 100
X-Ratelimit-Limit-Minute → 15
X-Ratelimit-Limit-Second → 5
X-Ratelimit-Remaining-Hour → 97
X-Ratelimit-Remaining-Minute → 14
X-Ratelimit-Remaining-Second → 4

if i do not call the proxy url ,how can i get these X-Ratelimit-Limit-* values?
i didn't find these data in psSql tables?

**Comment by fachri-amin** [comment]
did you get a solution for this issue?
