### ISSUE TITLE
Using one host for all API, can i do that?

### ISSUE THREAD

**Issue by hungpt91** [Mashape/kong#2616]
In my Case:
I have two API are A and B.

Normally, I create two API with two host A.kong.com and B.kong.com and "upstream url" + "upstreams" + "targets" -> It work perfectly.
But I want to use one host for all API above, and i set it is  AB.kong.com. But when i do that, Kong dont know target to forward request. Kong response error 404. I cannot understand because in Kong 's document, Kong forward request to target by "upstream url" and not base on "hosts". Can u explain ? Thankyou. 

NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by p0pr0ck5** [comment]
Hi,

Yes, you can have one host define multiple APIs. See https://getkong.org/docs/0.10.x/proxy/ for documentation on how to define API endpoints via hosts, URIs, or HTTP methods (or a combination of the three).

**Comment by hungpt91** [comment]
Thankyou your answer, but in my situation like that:
1) -> I config one host define mutiple APIs, and i config Kong will used file /etc/hosts to find upstream, not define upstream and target -> it Work.
2) -> Same above - one host. But i define upstreams (name=upstream_url) and targets (x.x.x.x:80) for API, dont used /etc/hosts. -> Kong not work, it response error 404. I try enable "preserve_host", it still dont work. Any wrong in here ?
