### ISSUE TITLE
Inconsistent JSON format for Active Targets List API

### ISSUE THREAD

**Issue by vaibhav-sinha** [Mashape/kong#2618]
### Summary

The ``data`` key in ``/upstreams/{name or id}/targets/active`` API response should always contain a list. But if the total number of active targets is 0, ``data`` contains an empty object instead of an empty list.

    {
      "data": {},
      "total": 0
    }

**Comment by p0pr0ck5** [comment]
Thanks @vaibhav-sinha. This should be an easy fix :)
