### ISSUE TITLE
Kong 0.10.3 Initial Core Migration Failure

### ISSUE THREAD

**Issue by nareen2** [Mashape/kong#2622]
### Summary
Kong 0.10.3 Initial Core Migration Failure when using 3-node Cassandra cluster with RF=3 and Consistency = QUORUM in kong.conf

### Steps To Reproduce

1. 3 Kong nodes 
2. 3 Cassandra nodes
3. `kong start` on kong nodes
4. Results in this error at <prefix>/logs/error.log
2017/06/14 15:47:39 [notice] 16543#0: [lua] log.lua:55: log(): migrating core for keyspace kong
2017/06/14 15:47:40 [notice] 16543#0: [lua] log.lua:55: log(): core migrated up to: 2016-02-25-160900_remove_null_consumer_id
2017/06/14 15:47:40 [notice] 16543#0: [lua] log.lua:55: log(): core migrated up to: 2016-02-29-121813_remove_ttls
2017/06/14 15:47:40 [error] 16543#0: init_by_lua error: /usr/local/share/lua/5.1/kong.lua:150: [cassandra error] Error during migration 2016-09-05-212515_retries_step_1: [Invalid] Invalid column name retries because it conflicts with an existing column
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong.lua:150: in function 'init'
        init_by_lua:5: in main chunk

### Additional Details & Logs

- Kong version (`$ kong version`) 0.10.3
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
2017/06/14 15:47:39 [notice] 16543#0: [lua] log.lua:55: log(): migrating core for keyspace kong
2017/06/14 15:47:40 [notice] 16543#0: [lua] log.lua:55: log(): core migrated up to: 2016-02-25-160900_remove_null_consumer_id
2017/06/14 15:47:40 [notice] 16543#0: [lua] log.lua:55: log(): core migrated up to: 2016-02-29-121813_remove_ttls
2017/06/14 15:47:40 [error] 16543#0: init_by_lua error: /usr/local/share/lua/5.1/kong.lua:150: [cassandra error] Error during migration 2016-09-05-212515_retries_step_1: [Invalid] Invalid column name retries because it conflicts with an existing column
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong.lua:150: in function 'init'
        init_by_lua:5: in main chunk

- Kong configuration (registered APIs/Plugins & configuration file) 
Default Kong Conf with cassandra_contact_points as only customization.
- Operating System
Redhat 7.2

**Comment by nareen2** [comment]
Any ideas or recommendations to resolve this? Thanks.

**Comment by marccardinal** [comment]
I moved to a PostgreSQL backend and never saw the issue again where I ran into those issues many times with Cassandra even when simply doing a restart on a kong node.

**Comment by thibaultcha** [comment]
@marccardinal Just to make sure, are you migrating from a single node (manually), or starting all of your Kong nodes at the same time? Because that could trigger such an issue.

**Comment by nareen2** [comment]
FWIW, I automated the whole cluster set-up process. Last step in that process is running `kong start` on all Kong servers. Even I tried manually like this:
1. `kong stop` on all the servers.
2. `kong start` on each node one after the other.
But this issue is still persistent.

**Comment by thibaultcha** [comment]
As mentioned, the migrations need to run from a single node, and *cannot* be run concurrently from multiple nodes at the same time. In your setup, you should have a migration step (`$ kong migrations up -c kong.conf`) that is *not* being run concurrently.

**Comment by nareen2** [comment]
Oh okay, thanks. Also, I never had this issue when I tried the same set-up with RF=1 and Consistency = ONE.

**Comment by p0pr0ck5** [comment]
Closing, since this was a result of running migrations simultaneously (documented to avoid this). Let us know if there are any other pending questions here. Thank you!

**Comment by ilucker** [comment]
i have the same issue. 
i ran migration using`$ kong migrations up -c kong.conf` and after that started restarting nodes one by one. The first node restart failed with exactly same error.
