### ISSUE TITLE
"preverse host" field, it didn't working ?

### ISSUE THREAD

**Issue by hungpt91** [Mashape/kong#2624]
In Kong's document, i found : When set "preverse host = false" .Kong would extract the Host header value from the the hostname of the API's upstream_url field, and would send the following request to your upstream service.
But i do that, Kong dont send Host header from API's upstream_url field to target. Kong sent Host header = target ip address. Why ?
Pictures:
https://prnt.sc/fjznz0
https://prnt.sc/fjzpot

NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by thefosk** [comment]
What Kong version?

**Comment by hungpt91** [comment]
I used Kong 0.10.3

**Comment by thefosk** [comment]
Can you give me the curl output of the API: `curl 127.0.0.1:8001/apis/{id}` ?

**Comment by hungpt91** [comment]
Dear @thefosk , my output here:
https://prnt.sc/fled5p
https://prnt.sc/fled9c

**Comment by thefosk** [comment]
Since your `target` has an IP address, the IP address will be sent. But if your `target` has a hostname, then the hostname will be used.

**Comment by hungpt91** [comment]
@thefosk 
Ohm, that define about "preverse host = false" is not true when i use target on upstream? I think define is unclear. 
But if I want use target = ipaddress:port, and " Kong wil extraxt Host header value from the the hostname of the API's upstream_url field, and would send the following request to  target , not the IP address. I try to change syntax in nginx : "proxy_set_header Host $upstream_host;", but i dont know how to point nginx understand upstream_url value. Is there any way to do that ?
Thankyou your support and sorry about my english, it's not good :+1:

**Comment by hungpt91** [comment]
Problem is solved, i using prefix location on nginx. When client request match with location /uri, nginx will set proxy_set_header with the value i define before -> that value = API's upstream_url . Kong will proxy it to target -> success. 
But i think it is a trick, i hope Kong will solve it in next version. Can you consider about that ?
Again, thanks for your support. Have a nice day.

**Comment by p0pr0ck5** [comment]
Closing based on response.
