### ISSUE TITLE
TIME_WAIT caused 'Can not assign requested address' in rate-limiting with redis policy

### ISSUE THREAD

**Issue by lixin1234qqq** [Mashape/kong#2626]
### Summary

I was testing the Rate Limit Plugin with redis for stress. I found that in the case of high concurrent requests,  too many port were in TIME_WAIT state, which caused new connections could not bind to port------'Can not assign requested address' 

### Steps To Reproduce

1.install kong according https://getkong.org/install/source/
2.set Key-ayth and rate limit (redis policy) 
3.I used Apache Jmeter to initiate http request 
4.In lower concurrent request condition, it worked fine. However, with the number of threads increasing (eg, >1000qps), there were many 'cannot assign requested address'(while executing red:connect() method in rate-limiting/policies/init.lua) in error.log. 

Looking forward to your reply.

#### Kong version 
    0.10.3
#### Kong configuration 
   Modified parameters were list here:
   lua_socket_pool_size 30 -> 1024
   red:set_keepalive(10000, 100) -> red:set_keepalive(100000, 1024)
   config.redis_timeout 2000 -> 10000
#### Operating System and some configuration
  centos6.3
  cpu processor number : 8
  Mem 64G
  net.ipv4.tcp_timestamps=1 
  net.ipv4.tcp_tw_reuse=1
  net.ipv4.tcp_tw_recycle=1
  net.ipv4.tcp_keepalive_time=60
  net.ipv4.tcp_keepalive_intvl=10
  net.ipv4.tcp_keepalive_probes=30

**Comment by thefosk** [comment]
Can you try to increase the `ulimit` value on your server?

**Comment by lixin1234qqq** [comment]
Thank you for your reply! @thefosk 
I have increased `ulimit` , while it didn't solve the problem. 
Here is my ulimit parameter:
    
	core file size          (blocks, -c) unlimited
	data seg size           (kbytes, -d) unlimited
	scheduling priority             (-e) 0
	file size               (blocks, -f) unlimited
	pending signals                 (-i) 515229
	max locked memory       (kbytes, -l) 64
	max memory size         (kbytes, -m) unlimited
	open files                      (-n) 801111
	pipe size            (512 bytes, -p) 8
	POSIX message queues     (bytes, -q) 819200
	real-time priority              (-r) 0
	stack size              (kbytes, -s) 10240
	cpu time               (seconds, -t) unlimited
	max user processes              (-u) 30720
	virtual memory          (kbytes, -v) unlimited
	file locks                      (-x) unlimited

**Comment by p0pr0ck5** [comment]
@lixin1234qqq can i ask why you've enabled `tcp_tw_recycle`?

**Comment by CaledoniaProject** [comment]
Well, both `kong` and `openresty` are to be blamed.

Sadly `ngx.socket.tcp:setkeepalive` method does not actually set `SO_KEEPALIVE`, I had to add that part.

And `kong` itself forget to call `red:set_keepalive` in the `usage` method, twice. Those files are:

```
./kong/plugins/rate-limiting/policies/init.lua
./kong/plugins/capacity-limiting/redis.lua
```

Solving the two problems above solves this TIME_WAIT issue, case closed.

P.S  [set_keepalive has no effect](https://github.com/openresty/lua-resty-redis/issues/121)

**Comment by p0pr0ck5** [comment]
@CaledoniaProject as noted in https://github.com/openresty/lua-resty-redis/issues/121, SO_KEEPALIVE is unrelated here :)

It does look like the redis usage function in the rate-limiting plugin fails to add the connection into the keepalive pool, nice find. The increment function works as expected :)

`capacity-limiting` is not an official Kong plugin. We'd need to look at the entire codebase for this custom plugin to examine it.

**Comment by thibaultcha** [comment]
> It does look like the redis usage function in the rate-limiting plugin fails to add the connection into the keepalive pool, nice find. The increment function works as expected :)

@CaledoniaProject Mind proposing a patch for this? :D

**Comment by p0pr0ck5** [comment]
The fix here was merged!
