### ISSUE TITLE
Kong seemingly modifying json response body without being asked

### ISSUE THREAD

**Issue by mrproper** [Mashape/kong#2628]
NOTE: GitHub issues are reserved for bug reports only.

### Summary

Response body json seems to be modified by kong
json keys with a value of true are replaced with null

### Steps To Reproduce
I have not been able to setup a static website and just return a string with the json and receive the same results
```
curl -i https://api.tld/foo/${ID}
HTTP/1.1 200 OK
Date: Fri, 16 Jun 2017 04:57:47 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 467
Connection: keep-alive
Cache-Control: no-cache
Server: nginx/1.11.9
Vary: Accept
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: b225b8e4-5726-49d0-80dd-0e4b31d6a080
X-Robots-Tag: noindex, nofollow
X-Runtime: 0.993276
X-Server-Hostname: XXX
X-XSS-Protection: 1; mode=block
X-Kong-Upstream-Latency: 1005
X-Kong-Proxy-Latency: 1
Via: kong/0.10.2

{"data":{"key1":null,"key2":null}}

curl -i https://upstream/foo/${ID}

HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Fri, 16 Jun 2017 04:57:54 GMT
Server: nginx/1.11.9
Vary: Accept
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 89442bf9-3605-4336-9a23-6291732ced5f
X-Runtime: 0.546303
X-Server-Hostname: XXX
X-XSS-Protection: 1; mode=block
Content-Length: 504
Connection: keep-alive

{"data":{"key1":true,"key2":true}}
```

### Additional Details & Logs

- Kong version 0.10.2
- Kong error logs: no plugins enabled
- Kong configuration: standard add api with upstream as per the 5 minute intro
- Operating System: docker

**Comment by p0pr0ck5** [comment]
@mrproper do you have any plugins enabled?

Also, do you have `server_tokens` disabled on this Kong instance?

**Comment by mrproper** [comment]
@p0pr0ck5 I have one api with the request-transformer plugin enabled and key auth, i then added another api without those enable to test if theres a difference and there is not going through either.

no server_tokens is true

**Comment by mrproper** [comment]
The strange part is i cant replicate it on another upstream, but i have aws api gw set to the same upstream with the same basic config and it does not suffer the same issue

**Comment by p0pr0ck5** [comment]
You could try tcpdumping the response as it comes into Kong, and as it goes out of Kong, to confirm that the packets are actually being altered by the proxy. If so, this sounds like a Kong misconfiguration (or wonky behavior in the request transformer plugin); by default, with no plugins, Kong just leverages Nginx's proxy_pass mechanism, which performs no inspection/transformation of the response body whatsoever.

**Comment by p0pr0ck5** [comment]
@mrproper any update? I have duplicated your config environment locally (via Vagrant using Kong 0.10.3) and cannot reproduce this. Any more details or info you can provide?

**Comment by mrproper** [comment]
oh my. it totally slipped my mind to close this. turns out it was something
yhat the upstream was doing based on a non existent header...please close.
apologues for the tardiness

**Comment by p0pr0ck5** [comment]
Thanks for the report back! Glad it got sorted :)
