### ISSUE TITLE
Kong rate limiting concurrent problem

### ISSUE THREAD

**Issue by qingziguanjun** [Mashape/kong#2629]
For kong 0.10.2, i add rate limiting plugin for my api:
curl -X POST http://10.10.11.152:8001/apis/bjlife615/plugins \
    --data "name=rate-limiting" \
    --data "config.second=5" \
    --data "config.minute=100"

i use java code call the proxy url:
	`final String url = "http://kong.d.internetware.cn/bjlife/vericode615?apikey=sy1";
		 for(int i=0;i<10;i++){
	                	 System.out.println(HttpTool.sendGet(url, null));
	        }
`	

i will get error：
{"message":"API rate limit exceeded"}

but if i use concurrent code:
`         for(int i=0;i<10;i++){
       new Thread(){
                public void run() {
                	 System.out.println(HttpTool.sendGet(url, null));
                };
            }.start();
        }
`
i will never get rate limit  error,how can i fix it?

**Comment by p0pr0ck5** [comment]
@qingziguanjun by default, the `cluster` policy is used to track usage data across the Kong cluster, but in its current design, it can be susceptible to race conditions in benchmark environments such as this. If you run just a single Kong node, try setting the `config.policy` value to `local` on the plugin config.

**Comment by qingziguanjun** [comment]
If i set like this:
    curl -X POST http://10.10.11.152:8001/apis/bjlife615/plugins \
    --data "name=rate-limiting" \
    --data "config.second=5" \
    --data "config.minute=100"  --data "

> config.policy=local

"

Then there is no rate-limit effort,i will never get such error:
{"message":"API rate limit exceeded"}

**Comment by p0pr0ck5** [comment]
Hi,

In the future please avoid cross posting to both the mailing list and GH issues. Since there is a discussion going on here (https://groups.google.com/forum/#!topic/konglayer/JRpoNnDuEZ8) I will close this. Thanks.
