### ISSUE TITLE
Kong not starting in MAC

### ISSUE THREAD

**Issue by asingh493** [Mashape/kong#2646]
### Summary
We were trying to install Kong (docker) on my Mac by following the instructions mentioned on the website (https://getkong.org/install/docker/ ).
When it ask to start Kong…..we are facing error

KONG START
/usr/local/bin/KONG:7: module 'kong.cmd.init' not found:No LuaRocks module found for kong.cmd.init
                no field package.preload['kong.cmd.init']
                no file 'kong/cmd/init/init.lua'
                no file '/usr/local/openresty/site/lualib/kong/cmd/init.lua'
                no file '/usr/local/openresty/site/lualib/kong/cmd/init/init.lua'
                no file '/usr/local/openresty/lualib/kong/cmd/init.lua'
                no file '/usr/local/openresty/lualib/kong/cmd/init/init.lua'
                no file './kong/cmd/init.lua'
                no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/kong/cmd/init.lua'
                no file '/usr/local/share/lua/5.1/kong/cmd/init.lua'
                no file '/usr/local/share/lua/5.1/kong/cmd/init/init.lua'
                no file '/usr/local/openresty/luajit/share/lua/5.1/kong/cmd/init.lua'
                no file '/usr/local/openresty/luajit/share/lua/5.1/kong/cmd/init/init.lua'
                no file '/Users/asingh493/.luarocks/share/lua/5.1/kong/cmd/init.lua'
                no file '/Users/asingh493/.luarocks/share/lua/5.1/kong/cmd/init/init.lua'
                no file '/usr/local/openresty/site/lualib/kong/cmd/init.so'
                no file '/usr/local/openresty/lualib/kong/cmd/init.so'
                no file './kong/cmd/init.so'
                no file '/usr/local/lib/lua/5.1/kong/cmd/init.so'
                no file '/usr/local/openresty/luajit/lib/lua/5.1/kong/cmd/init.so'
                no file '/usr/local/lib/lua/5.1/loadall.so'
                no file '/Users/asingh493/.luarocks/lib/lua/5.1/kong/cmd/init.so'
                no file '/usr/local/openresty/site/lualib/kong.so'
                no file '/usr/local/openresty/lualib/kong.so'
                no file './kong.so'
                no file '/usr/local/lib/lua/5.1/kong.so'
                no file '/usr/local/openresty/luajit/lib/lua/5.1/kong.so'
                no file '/usr/local/lib/lua/5.1/loadall.so'
                no file '/Users/asingh493/.luarocks/lib/lua/5.1/kong.so'

### Steps To Reproduce
as per website https://getkong.org/install/docker/ 

1. docker run -d --name kong-database \
              -p 9042:9042 \
              cassandra:3.10
2. docker run -d --name kong \
              --link kong-database:kong-database \
              -e "KONG_DATABASE=cassandra" \
              -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
              -e "KONG_PG_HOST=kong-database" \
              -p 8000:8000 \
              -p 8443:8443 \
              -p 8001:8001 \
              -p 7946:7946 \
              -p 7946:7946/udp \
              kong:latest
3. Kong Start

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System - MAC Sierra

**Comment by shashiranjan84** [comment]
@asingh493 would you please try again, I tried locally on my mac and it just worked fine. Also please give it a try with  explicit version `kong:0.10.3`

![image](https://user-images.githubusercontent.com/8146958/27495488-e7be78a8-5806-11e7-9025-e48a6046347c.png)

**Comment by asingh493** [comment]
It seems problem was because of Docker Machine. I installed Docker toolbox and as a result, there was a default docker machine and as a result, if I just issue command like 
curl http://127.0.0.1:8001......give connection refused.

But if I give cmd like

curl http://192.168.99.100:8001....I see a response.

**Comment by asingh493** [comment]
So I removed everything....and installed native Docker.
once I installed Kong again...I see the same problem.

asingh493$ kong stop
/usr/local/bin/kong:7: module 'kong.cmd.init' not found:No LuaRocks module found for kong.cmd.init
	no field package.preload['kong.cmd.init']
	no file 'kong/cmd/init/init.lua'
	no file '/usr/local/openresty/site/lualib/kong/cmd/init.lua'
	no file '/usr/local/openresty/site/lualib/kong/cmd/init/init.lua'
	no file '/usr/local/openresty/lualib/kong/cmd/init.lua'
	no file '/usr/local/openresty/lualib/kong/cmd/init/init.lua'
	no file './kong/cmd/init.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/kong/cmd/init.lua'
	no file '/usr/local/share/lua/5.1/kong/cmd/init.lua'
	no file '/usr/local/share/lua/5.1/kong/cmd/init/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/kong/cmd/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/kong/cmd/init/init.lua'
	no file '/Users/asingh493/.luarocks/share/lua/5.1/kong/cmd/init.lua'
	no file '/Users/asingh493/.luarocks/share/lua/5.1/kong/cmd/init/init.lua'
	no file '/usr/local/openresty/site/lualib/kong/cmd/init.so'
	no file '/usr/local/openresty/lualib/kong/cmd/init.so'
	no file './kong/cmd/init.so'
	no file '/usr/local/lib/lua/5.1/kong/cmd/init.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/kong/cmd/init.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/asingh493/.luarocks/lib/lua/5.1/kong/cmd/init.so'
	no file '/usr/local/openresty/site/lualib/kong.so'
	no file '/usr/local/openresty/lualib/kong.so'
	no file './kong.so'
	no file '/usr/local/lib/lua/5.1/kong.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/kong.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/asingh493/.luarocks/lib/lua/5.1/kong.so'

**Comment by thibaultcha** [comment]
Are you running those commands on your host machine instead of inside the container? It looks like it, since the steps you described show:

2. `docker run kong:latest` (this should start Kong in the created container already)
3. `kong start` (if you did not ssh into your container, this will attempt to start Kong into the host machine, where Kong doesn't seem to be installed...)

The 0.10 family of images has been released for a while and running in production with no such issue.

**Comment by asingh493** [comment]
I’m just following your docs.
In that case you need to update your doc.


-----------------------
Cheers
Abhishek Singh
PMP, CSM, SAFe, CSPO
DXC | EGL | Bengaluru | India
Ph: + 91 80 61762299 | CUG: 762299

**Comment by thibaultcha** [comment]
The doc does not instruct to run `kong start`. If you hit the admin API on your container's IP, it seems to work?

**Comment by asingh493** [comment]
yes… once I give
curl http://127.0.0.1:8001

I get response.


-----------------------
Cheers
Abhishek Singh
PMP, CSM, SAFe, CSPO
DXC | EGL | Bengaluru | India
Ph: + 91 80 61762299 | CUG: 762299

**Comment by asingh493** [comment]
but I see same error whenever I try to issue Kong commands as per doc
https://getkong.org/docs/0.10.x/getting-started/quickstart/

kong start
kong stop
kong reload

Can you please suggest how can I make use of these commands?

**Comment by p0pr0ck5** [comment]
@asingh493 the commands above need to be issued inside the machine/container running Kong, not the Docker host.

**Comment by asingh493** [comment]
thanks @p0pr0ck5 

Will try....Kong document does not talk about if these commands need to be run inside the container.

**Comment by p0pr0ck5** [comment]
@asingh493 the docs assume, I think, some basic knowledge of using Docker in the context. The docs are also open source at github.com/mashape/getkong.org; feel free to submit a PR to improve them if you think they are lacking. Thanks! :)

**Comment by NICK-DUAN** [comment]
i also got this problem in my mac, anyone has a solution? it's 2020!

**Comment by louisluhao** [comment]
> i also got this problem in my mac, anyone has a solution? it's 2020!
> it's not in docker, just in my mac machine.

I got similar error, completely followed https://docs.konghq.com/install/source/?_ga=2.262757068.1939498096.1595639928-1882141532.1595639928

**Comment by mariuswang007** [comment]
> _ga

same error in ubuntu 18.04: 

![image](https://user-images.githubusercontent.com/4271618/89616178-8085f200-d8ba-11ea-8fe3-50a7b007c5d6.png)

**Comment by 610991905** [comment]
> i also got this problem in my mac, anyone has a solution? it's 2020!
> it's not in docker, just in my mac machine.

i got an similar error  in my mac too,steps followed https://docs.konghq.com/install/source/ ,have you solved the problem?

**Comment by niraj28** [comment]
similar issue followed the same steps in mac followed https://docs.konghq.com/install/source/ ,have you solved the problem?

**Comment by 610991905** [comment]
I slove it.  when you according to the official steps successfully installed,  and run kong cmd  must be in path **$xxx/kong-sources/kong**
for example:
cd xxxx/kong-sources/kong 
kong start

**Comment by 610991905** [comment]
> similar issue followed the same steps in mac followed https://docs.konghq.com/install/source/ ,have you solved the problem?

I slove it. when you according to the official steps successfully installed, and run kong cmd must be in path $xxx/kong-sources/kong
for example:
cd xxxx/kong-sources/kong
kong start

**Comment by niraj28** [comment]
I am in /kong-sources/kong and doing kong start having same error.

**Comment by 610991905** [comment]
> I am in /kong-sources/kong and doing kong start having same error.
try run
export LUA_PATH="xxxxxx/kong-sources/deps/luarocks/share/lua/5.1/?.lua;"

**Comment by niraj28** [comment]
tried as you suggested , sharing the structure 
*****/kong-sources/kong/kong
ERROR: /Users/niraj/kong-sources/kong/bin/kong:9: module 'kong.cmd.init' not found:
	no field package.preload['kong.cmd.init']
	no file './kong/cmd/init.lua'

*****/kong-sources/kong
ERROR: ./kong/globalpatches.lua:50: module 'socket' not found:
	no field package.preload['socket']
	no file './socket.lua'

**Comment by niraj28** [comment]
and also when $ git clone git@github.com:Kong/kong.git
 $ cd kong
 $ git checkout 2.2.1
 $ make install
  an error is coming 
    Error: Failed installing dependency: https://luarocks.org/kong-plugin-serverless-functions-1.0.0-1.src.rock - Could not fetch rock file: Error fetching file: Failed downloading https://luarocks.org - Failed downloading https://luarocks.org/kong-plugin-serverless-functions-1.0.0-1.src.rock - /Users/niraj/.cache/luarocks/https___luarocks.org/kong-plugin-serverless-functions-1.0.0-1.src.rock

**Comment by niraj28** [comment]
Thank you :), issue got resolved.
I have ran the below command and its working now.
$luarocks install luasocket

**Comment by apodemakeles** [comment]
same error, it's 2021!!!!!!

**Comment by vinkin** [comment]
when I meet the error like "no file xxxxxxx",I try to add the file to the lua path，such like:
1.change the file`bin/kong`, the value of `package.path`,try to add the path you need
2.change the environment variable `LUA_PATH`,try to add the path you need
3.change the file `kong.conf`,the value of `lua_package_path`,try to add the path you need

lua or kong will scan the path above。

the only way what I do is try to add the lua file to the path,now it works。I‘m build kong1.4.0.now it works,but maybe not in a standard way.

![image](https://user-images.githubusercontent.com/12459182/147315223-25ef6047-2b25-4d42-a825-3c2f641f2c06.png)
