### ISSUE TITLE
Can not  start kong 

### ISSUE THREAD

**Issue by qingziguanjun** [Mashape/kong#2647]
For kong 0.10.2
When i start kong using:
kong restart

I get error:
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/dao/db/postgres.lua:270: Expected value but found T_END at character 1
stack traceback:
        [C]: in function 'decode'
        /usr/local/share/lua/5.1/kong/dao/db/postgres.lua:270: in function 'deserialize_rows'
        /usr/local/share/lua/5.1/kong/dao/db/postgres.lua:291: in function 'find_all'
        /usr/local/share/lua/5.1/kong/dao/dao.lua:178: in function 'find_all'
        /usr/local/share/lua/5.1/kong/core/handler.lua:37: in function 'build_router'
        /usr/local/share/lua/5.1/kong.lua:162: in function 'init'
        init_by_lua:4: in main chunk

stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'execute'
        /usr/local/share/lua/5.1/kong/cmd/restart.lua:13: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:5: in function 'file_gen'
        init_worker_by_lua:38: in function <init_worker_by_lua:36>
        [C]: in function 'pcall'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>

**Comment by Tieske** [comment]
that would most likely be a JSON decoding error

Some questions:
what platform? what postgres version? where did you find that trace (cli or error logs)? have you tried resetting the migrations (drops database!)?

**Comment by qingziguanjun** [comment]
The platform is CentOS release 6.8 (Final).
PGSQL:9.6
I find this trace when i start kong using "kong restart --v"
I have not reset the migrations. I don not know how to do it? I guess it is  pgsql that has errors. 
I can start kong before,but after i add about 132 apis and 360 plugins , when i restart the kong using command "kong restart",i suddenly get this error.

**Comment by qingziguanjun** [comment]
I drop kong database in pgsql,and recreate it :CREATE DATABASE kong OWNER kong
now i solve the problem ,Thank U
