### ISSUE TITLE
Joining a new Kong container in a Kong cluster will cause some HTTP connexion refused

### ISSUE THREAD

**Issue by JnMik** [Mashape/kong#2656]
Hello guys ! 

So I was running Siege benchmark on the Kong cluster, and discovered that when I scale down containers and bring them back up, when the containers are booting, there is a short time when the container is available, reachable and accept HTTP request, but it has not fetch his API & consumers data yet. So I see multiples connections refused error (in a window of maybe 6-7 seconds).

When the container has fetched his data, everything goes back to normal.

Maybe changing something in the boot sequence could help prevent this ? (Like enabling port 8000 after pulling the data)  

Or maybe add a Docker healthcheck that won't enable the container until it has fully completed boot sequence ? 

I'd like to hear your thoughts on this ! 
Cheers

**Comment by p0pr0ck5** [comment]
This is closely related to https://github.com/Mashape/kong/issues/1678 and friends. There is some discussion to be had about Kong defining itself as "ready". The "boot sequence" to which you refer is not a function of Kong itself starting, but the eventual consistency of the database. This brings up an interesting point- are you starting and stopping multiple nodes running Kong AND postgres/cassandra, or just Kong nodes? Ideally, this should just be the latter. As soon as the Nginx process starts, any requests for uncached DB objects will be fetched from the DB, but if there are DB changes in progress (e.g. you are not adding new nodes to a psql/cassandra cluster), there should be no data missing from Kong. It would be helpful if you could provide detailed error/debug logs of the case which you are describing, so we can better understand how we can improve Kong here (or how we can suggest you tune your environment).

**Comment by JnMik** [comment]
Hello @p0pr0ck5 

I'm not at the office at the moment so I won't be able to provide logs,  but my setup was like 5 cassandra containers and 4 kong containers.

The error is constant, when I'm scaling kong containers up, the error happens everytime.

**Comment by p0pr0ck5** [comment]
Having the exact error message at stack trace will be helpful for us to understand what's going on :)

**Comment by JnMik** [comment]
Hello @p0pr0ck5 

So here's configuration details and logs I can fetch: 

**Freshly booted container (sadly there is no specific error log when the HTTP request are dropped**

```
Details from docker logs (catching up all stdout and stderr)

2017/07/03 17:06:43 [verbose] Kong: 0.10.3
2017/07/03 17:06:43 [debug] ngx_lua: 10007
2017/07/03 17:06:43 [debug] nginx: 1011002
2017/07/03 17:06:43 [debug] Lua: LuaJIT 2.1.0-beta2
2017/07/03 17:06:43 [verbose] no config file found at /etc/kong/kong.conf
2017/07/03 17:06:43 [verbose] no config file found at /etc/kong.conf
2017/07/03 17:06:43 [verbose] no config file, skipping loading
2017/07/03 17:06:43 [debug] KONG_ADMIN_ERROR_LOG ENV found with "/dev/stderr"
2017/07/03 17:06:43 [debug] KONG_ADMIN_ACCESS_LOG ENV found with "/dev/stdout"
2017/07/03 17:06:43 [debug] KONG_PROXY_ACCESS_LOG ENV found with "/dev/stdout"
2017/07/03 17:06:43 [debug] KONG_CASSANDRA_REPL_FACTOR ENV found with "3"
2017/07/03 17:06:43 [debug] KONG_CASSANDRA_CONSISTENCY ENV found with "QUORUM"
2017/07/03 17:06:43 [debug] KONG_CASSANDRA_SCHEMA_CONSENSUS_TIMEOUT ENV found with "30000"
2017/07/03 17:06:43 [debug] KONG_DATABASE ENV found with "cassandra"
2017/07/03 17:06:43 [debug] KONG_LOG_LEVEL ENV found with "debug"
2017/07/03 17:06:43 [debug] KONG_CASSANDRA_CONTACT_POINTS ENV found with "gateway_cluster_cassandra-peer1,gateway_cluster_cassandra-peer2,gateway_cluster_cassandra-peer3"
2017/07/03 17:06:43 [debug] KONG_CLUSTER_LISTEN ENV found with "0.0.0.0:27946"
2017/07/03 17:06:43 [debug] KONG_CLUSTER_ADVERTISE ENV found with "172.28.0.47:27946"
2017/07/03 17:06:43 [debug] KONG_NGINX_DAEMON ENV found with "off"
2017/07/03 17:06:43 [debug] KONG_PROXY_ERROR_LOG ENV found with "/dev/stderr"
2017/07/03 17:06:43 [debug] KONG_CASSANDRA_REPL_STRATEGY ENV found with "SimpleStrategy"
2017/07/03 17:06:43 [debug] KONG_CASSANDRA_TIMEOUT ENV found with "5000"
2017/07/03 17:06:43 [debug] admin_access_log = "/dev/stdout"
2017/07/03 17:06:43 [debug] admin_error_log = "/dev/stderr"
2017/07/03 17:06:43 [debug] admin_listen = "0.0.0.0:8001"
2017/07/03 17:06:43 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/07/03 17:06:43 [debug] admin_ssl = true
2017/07/03 17:06:43 [debug] anonymous_reports = true
2017/07/03 17:06:43 [debug] cassandra_consistency = "QUORUM"
2017/07/03 17:06:43 [debug] cassandra_contact_points = {"gateway_cluster_cassandra-peer1","gateway_cluster_cassandra-peer2","gateway_cluster_cassandra-peer3"}
2017/07/03 17:06:43 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/07/03 17:06:43 [debug] cassandra_keyspace = "kong"
2017/07/03 17:06:43 [debug] cassandra_lb_policy = "RoundRobin"
2017/07/03 17:06:43 [debug] cassandra_port = 9042
2017/07/03 17:06:43 [debug] cassandra_repl_factor = 3
2017/07/03 17:06:43 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/07/03 17:06:43 [debug] cassandra_schema_consensus_timeout = 30000
2017/07/03 17:06:43 [debug] cassandra_ssl = false
2017/07/03 17:06:43 [debug] cassandra_ssl_verify = false
2017/07/03 17:06:43 [debug] cassandra_timeout = 5000
2017/07/03 17:06:43 [debug] cassandra_username = "kong"
2017/07/03 17:06:43 [debug] client_ssl = false
2017/07/03 17:06:43 [debug] cluster_advertise = "172.28.0.47:27946"
2017/07/03 17:06:43 [debug] cluster_listen = "0.0.0.0:27946"
2017/07/03 17:06:43 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/07/03 17:06:43 [debug] cluster_profile = "wan"
2017/07/03 17:06:43 [debug] cluster_ttl_on_failure = 3600
2017/07/03 17:06:43 [debug] custom_plugins = {}
2017/07/03 17:06:43 [debug] database = "cassandra"
2017/07/03 17:06:43 [debug] dns_hostsfile = "/etc/hosts"
2017/07/03 17:06:43 [debug] dns_resolver = {}
2017/07/03 17:06:43 [debug] latency_tokens = true
2017/07/03 17:06:43 [debug] log_level = "debug"
2017/07/03 17:06:43 [debug] lua_code_cache = "on"
2017/07/03 17:06:43 [debug] lua_package_cpath = ""
2017/07/03 17:06:43 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/07/03 17:06:43 [debug] lua_socket_pool_size = 30
2017/07/03 17:06:43 [debug] lua_ssl_verify_depth = 1
2017/07/03 17:06:43 [debug] mem_cache_size = "128m"
2017/07/03 17:06:43 [debug] nginx_daemon = "off"
2017/07/03 17:06:43 [debug] nginx_optimizations = true
2017/07/03 17:06:43 [debug] nginx_worker_processes = "auto"
2017/07/03 17:06:43 [debug] pg_database = "kong"
```

Files in /usr/local/kong/logs (access.log admin_access.log error.log are empty)
And Serf.log contains : 
```
==> Starting Serf agent...
==> Starting Serf agent RPC...
==> Serf agent running!
         Node name: '153595761b69_0.0.0.0:27946_da1973c384354eab80e83569a451c93f'
         Bind addr: '0.0.0.0:27946'
    Advertise addr: '172.28.0.47:27946'
          RPC addr: '127.0.0.1:7373'
         Encrypted: false
          Snapshot: false
           Profile: wan

==> Log data will now stream in as it occurs:

```

**Siege**
Here's how my siege benchmark tool react when I scale containers up :
You can see many connection refused in between

```
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
[error] socket: 1090860800 connection refused.: Connection refused
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
[error] socket: 1080370944 connection refused.: Connection refused
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
[error] socket: 870573824 connection refused.: Connection refused
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
[error] socket: 828614400 connection refused.: Connection refused
HTTP/1.1 200   0.00 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
[error] socket: 1027921664 connection refused.: Connection refused
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
HTTP/1.1 200   0.01 secs:       2 bytes ==> GET  /some-url/1.0/status
```

**Kong environement variables**
```
CHECK_TIMEOUT: 1
SLEEP_INTERVAL: 3
KONG_NGINX_DAEMON: off
KONG_DATABASE: cassandra
KONG_CASSANDRA_CONTACT_POINTS: gateway_cluster_cassandra-peer1,gateway_cluster_cassandra-peer2,gateway_cluster_cassandra-peer3
KONG_CASSANDRA_CONSISTENCY: QUORUM
KONG_CASSANDRA_REPL_FACTOR: 3
KONG_CASSANDRA_REPL_STRATEGY: SimpleStrategy
KONG_CASSANDRA_TIMEOUT: 5000
KONG_CASSANDRA_SCHEMA_CONSENSUS_TIMEOUT: 30000
KONG_CLUSTER_LISTEN: 0.0.0.0:27946
KONG_PROXY_ACCESS_LOG: /dev/stdout
KONG_PROXY_ERROR_LOG: /dev/stderr
KONG_ADMIN_ACCESS_LOG: /dev/stdout
KONG_ADMIN_ERROR_LOG: /dev/stderr
KONG_LOG_LEVEL: debug
```

**Cassandra environment variables**
```
CASSANDRA_SEEDS: gateway_cluster_cassandra-peer1,gateway_cluster_cassandra-peer2,gateway_cluster_cassandra-peer3
CASSANDRA_BROADCAST_ADDRESS: gateway_cluster_cassandra-peer1
CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
```

I gotta admit tho I just realized I have a custom way of booting Kong. 
Before launching kong start, I run a small python script which check if at least one of my cassandra peers is reachable. It might contribute to the delay before Kong is ready to be use... but still a Docker healthcheck would surely prevent that.

```
#!/usr/bin/python

import os
import sys
import time
import telnetlib


check_timeout = int(os.environ.get('CHECK_TIMEOUT', 1))
sleep_interval = int(os.environ.get('SLEEP_INTERVAL', 1))

peer_increment = 0

while True:
    try:
        peer_increment += 1;
        target_cassandra_server = 'gateway_cluster_cassandra-peer' + str(peer_increment)
        print 'Testing connexion to peer', target_cassandra_server
        conn = telnetlib.Telnet(target_cassandra_server, '9042', check_timeout)
        break
    except Exception, e:
        sys.stderr.write('%s\n' % repr(e))
        sys.stdout.write('Sleeping %s sec before checking for cassandra status\n' % sleep_interval)
        if peer_increment == 4:
            peer_increment = 0
        time.sleep(sleep_interval)

sys.stdout.write('Cassandra is up, Kong is now in control :)\n')

sys.exit(0)

```

If you're telling me you guys don't have the issue at all with the defaut kong image, I'll consider the issue to be related to my custom setup and implement a kong healthcheck on my end. I didn't took into consideration I had a custom script before I posted the issue lol. But still, my script delay the "kong start" command, my guess is the container should not even be considered healthy at that point. We cannot expect the container to be healthy just because it usually start faster. 

What's your thinking on this? Anything else you would like me to provide ? 
Cheers & thx for your time

**Comment by thibaultcha** [comment]
Hi @JnMik

What we would need here is the Nginx error logs, and not the CLI ones which are the ones sent to stdout/stderr on the default image as of today. If you are using the default image, those are located in `/usr/local/kong/logs/error.log` in your container.

**Comment by JnMik** [comment]
Hello @thibaultcha 

Yeah like I said, Files in /usr/local/kong/logs (access.log admin_access.log error.log) are completely empty. 

I'm not using directly the default image, but clearly I'm close, here's my Dockerfile : 

```
FROM kong:0.10.3

COPY etc/yum.repos.d/nginx.repo /etc/yum.repos.d/nginx.repo
COPY init-kong.sh /etc/kong/init-kong.sh
COPY wait.py /wait.py

RUN yum install nginx-nr-agent -y

```

So if error.log is empty, that would probably mean the error occurs before nginx / kong is even started.
Probably related to the delay caused by my python wait.py script. 
A healthcheck would clearly help with that. 
I believe the Docker healthcheck would bring some good for the kong default image, even for people not using a custom script like mine. It's usually a good practice to implement one.

**Comment by p0pr0ck5** [comment]
Yes, it sounds like what's happening is that siege is trying to make connections to an instance that is not responding on the proxy port. This is where the `connection refused` error comes from: siege wants to initiate a connection to port 8000, and the OS refuses because (obviously) no bind() has been initiated on that port. So this has nothing to do with Cassandra/cluster consistency, but that your setup is sending requests to a host that is not ready to accept traffic yet.

How are you load balancing connections to your Kong cluster? The solution here would be to define a healthcheck on your loadbalancer that attempts to initiate an HTTP request to the proxy port (or admin API port) on the Kong node. Since the problem here is that a layer 7 connection cannot be established to the node, the node should not consider itself healthy until Kong is running. But this would be an improvement with the Docker image, not Kong itself.

Given the above, it seems this issue should be closed. @JnMik you may want to open a PR or issue on the docker-kong project (https://github.com/Mashape/docker-kong), or, if we don't actually want to define a default healthcheck for the docker image, we could document this behavior on getkong.org (feel free to submit PRs/issues to https://github.com/Mashape/getkon.org). Thank you!

**Comment by JnMik** [comment]
The load balancer is simply the service layer of the swarm cluster. 
I wasn't aware of the docker-kong project, alright then, I'll close the issue here !

thx !
