### ISSUE TITLE
Kong doesn't start on ubuntu 32-bits 

### ISSUE THREAD

**Issue by amatosc** [Mashape/kong#2658]
### Summary

After to install Kong following [this](https://getkong.org/install/ubuntu/) guide `https://getkong.org/install/ubuntu/`, I tried to start it but I have got the next error:

```
ubuntu@kong:~$ kong start
/usr/local/openresty/bin/../nginx/sbin/nginx: 1: /usr/local/openresty/bin/../nginx/sbin/nginx: �: not found
/usr/local/openresty/bin/../nginx/sbin/nginx: 2: /usr/local/openresty/bin/../nginx/sbin/nginx: �BD�HC!�Ԡ@@I%����BD
                                                                                                                  D��$: not found
/usr/local/openresty/bin/../nginx/sbin/nginx: 5: /usr/local/openresty/bin/../nginx/sbin/nginx: �T#: not found
/usr/local/openresty/bin/../nginx/sbin/nginx: 1: /usr/local/openresty/bin/../nginx/sbin/nginx: Syntax error: "|" unexpected (expecting ")")
ubuntu@kong:~$ /usr/local/openresty/bin/../nginx/sbin/nginx: 1: /usr/local/openresty/bin/../nginx/sbin/nginx: ELF: not found
```

### Steps To Reproduce

1. Install ubuntu 32bits
2. Install kong
3. Try to start it

### Additional Details & Logs

- Kong version (0.10.3)
- Kong debug-level startup logs (`$ kong start --vv`) -> `Same error above`
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) -> `Empty` 
- Kong configuration (registered APIs/Plugins & configuration file) -> `by default`
- Operating System:
``` sh
ubuntu@kong:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

ubuntu@kong:~$ uname -m
i686
```

**Comment by p0pr0ck5** [comment]
Hi @amatosc,

Thanks for the report. As noted in the ticket you mentioned, this is a result of trying to run a 64 bit image of Kong (built against 64 bit libc/etc) on a 32 bit image. For such a use case, consider building Kong from source: https://getkong.org/install/source/. Thank you!
