### ISSUE TITLE
Load Balancing with HAProxy 

### ISSUE THREAD

**Issue by younisshah** [Mashape/kong#2660]
I'm trying to load balance Kong using HAProxy. Here is my haproxy.cfg file:

```
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	# Default ciphers to use on SSL-enabled listening sockets.
	# For more information, see ciphers(1SSL). This list is from:
	#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
	# An alternative list with additional directives can be obtained from
	#  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
	ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
	ssl-default-bind-options no-sslv3

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http

frontend localnodes
	bind 0.0.0.0:9876
	mode http
	default_backend nodes

backend nodes
	mode http
	balance roundrobin
	option forwardfor
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	option httpchk HEAD / HTTP/1.1\r\nHost:localhost
	server web01 127.0.0.1:8443/my-uri check
```

I've added an API to Kong with `uris` set to `my-uri` and enabled OAuth 2.0 plugin as well with `config.accept_http_if_already_terminated` set to `true`. However, when I hit `localhost:9876`, HAProxy responds with `503 Service Unavailable. No server is available to handle this request.`. 

I am trying to get @DonMartin76's solution to work. #1683 

Also when I `curl` with `curl https://localhost:8443/my-uri -k`, Kong responds with `missing authorization token` which is totally normal.

Kong is up and running.

Kong version: 0.10.3

Much appreciated.

**Comment by DonMartin76** [comment]
Hey Younis. At first glance, what looks suspicious is that you are forwarding to the SSL port (8443) of Kong, but you are using HAproxy for TLS termination. You should use port 8000 instead.

What's your setup? Is Kong running on the same machine as HAproxy, both on the same VM, which OS? I usually run everything in docker, and thus use the prepackaged haproxy docker images, which make the configuration a lot easier.

**Comment by younisshah** [comment]
Thanks for the quick response.

Here is my modified haproxy.cfg file:


```
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	# Default ciphers to use on SSL-enabled listening sockets.
	# For more information, see ciphers(1SSL). This list is from:
	#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
	# An alternative list with additional directives can be obtained from
	#  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
	ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
	ssl-default-bind-options no-sslv3

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http

frontend localnodes
	bind 0.0.0.0:9876
	mode http
	default_backend nodes

backend nodes
	balance source
  	mode http
	balance roundrobin
	option forwardfor
	option httpchk HEAD / HTTP/1.1\r\nHost:localhost
	server web01 127.0.0.1:8000 check
listen stats
	bind *:1936
	stats enable
	stats uri /
	stats hide-version
    stats auth someuser:password
```

I changed the port to `8000` but still I'm not able to access Kong.

Basically, I'm trying to secure my APIs using Kong with OAuth 2.0. All the tokens are getting generated successfully. Earlier from my react native app I tried accessing Kong via `192.168.xx.xxx:8443/my-uri`, but I got a `Network request failed` response. After much googling, I stumbled upon your solution which I am trying to get to work.

All the setup is on a single machine running Ubuntu 16.04.

**Comment by younisshah** [comment]
@DonMartin76 If you have a better solution or a way to get my APIs up and running, I am all ears. Thanks so very kindly!

**Comment by p0pr0ck5** [comment]
@younisshah Have you confirmed that Kong is actually running? Is Kong running on the same machine as HAProxy? Otherwise you will need to adjust the `server` HAProxy directive to . the appropriate IP.

BTW a GitHub issue is not really the appropriate place for this discussion, as GitHub issues should be reserved for problems with Kong itself. Please consider moving this discussion to the mailing list, or a similar appropriate forum: https://groups.google.com/forum/#!forum/konglayer. Thank you.

**Comment by p0pr0ck5** [comment]
Closing following no response. do let us know if there are any pending questions with Kong specifically, and feel free to continue this discussion on the Kong mailing list. Thank you!
