### ISSUE TITLE
Kong doesn't match the longest uri when multiple uris are defined on an api

### ISSUE THREAD

**Issue by tanelso2** [Mashape/kong#2662]
### Summary

If two (or more) APIs have uris that match the incoming uri, Kong will route to the API with the longest uri, even if that uri is not the one that matches.

### Steps To Reproduce

1. Fresh Kong install
2. Setup routes: 
`curl -X POST -H "Content-Type: application/json" -d '{"name":"a", "uris":"/a,/cccccc", "upstream_url":"https://google.com"}' localhost:8001/apis`
`curl -X POST -H "Content-Type: application/json" -d '{"name":"b", "uris":"/a/bb", "upstream_url":"https://example.com"}' localhost:8001/apis`
3. `curl localhost:8000/a/bb/123` will route to google.com instead of example.com

Note:
- If `/a` and `/ccccc` are defined as separate APIs, `curl localhost:8000/a/bb/123` will route to example.com instead.
- Also, if you replace `/a,/ccccc` with `/a,/cc` in the first route, `curl localhost:8000/a/bb/123` will route to example.com.
- Therefore, I think that there is an issue with how Kong is calculating the length of a matching uri. I'm not familiar with the code, but it seems like when an API matches, Kong thinks the longest uri on that API is the length of the match.

### Additional Details & Logs

- Kong version 0.10.3

**Comment by thibaultcha** [comment]
Good catch! I remember this edge-case now and never came back to it to fix it...

I just opened #2664 to take care of this. Thanks for the report!

**Comment by thibaultcha** [comment]
Thanks for the report, I just merged #2664 which takes care of this and should land in 0.11 and 0.10.4.

**Comment by tanelso2** [comment]
@thibaultcha Thanks for fixing this!
