### ISSUE TITLE
Method not allowed - DELETE

### ISSUE THREAD

**Issue by Izhaki** [Mashape/kong#2663]
### Summary

DELETE, PUT, PATCH all return `{"message":"Method not allowed"}`

### Steps To Reproduce

`Makefile`:
```
kong-init:
	@curl -X POST http://0.0.0.0:8001/upstreams \
		--data "name=blue"
	@curl -X POST http://0.0.0.0:8001/upstreams/blue/targets \
		--data "target=0.0.0.0:49160" \
		--data "weight=100"
	@curl -X POST http://0.0.0.0:8001/upstreams \
		--data "name=green"
	@curl -X POST http://0.0.0.0:8001/upstreams/green/targets \
		--data "target=0.0.0.0:49161" \
		--data "weight=100"
	@curl -X POST http://0.0.0.0:8001/apis/ \
		--data "name=dockerapp" \
		--data "hosts=0.0.0.0" \
		--data "upstream_url=http://green"

kong-reset:
	@curl -X DELETE http://0.0.0.0:8001/upstreams \
		--data "name=blue"
	@curl -X DELETE http://0.0.0.0:8001/upstreams/blue/targets \
		--data "target=0.0.0.0:49160"
	@curl -X DELETE http://0.0.0.0:8001/upstreams \
		--data "name=green"
	@curl -X DELETE http://0.0.0.0:8001/upstreams/green/targets \
		--data "target=0.0.0.0:49161"
	@curl -X DELETE http://0.0.0.0:8001/apis/ \
		--data "name=dockerapp"
```
### Additional Details & Logs

- Kong version (0.10.3)
- Operating System (Docker)

**Comment by p0pr0ck5** [comment]
@Izhaki please have a read through of the Admin API docs: https://getkong.org/docs/0.10.x/admin-api/

`DELETE` methods should never take any request body data. For example, deleting an API object `dockerapp` would look like:

`@curl -X DELETE http://0.0.0.0:8001/apis/dockerapp`

Similarly, `PATCH`/`POST`/`PUT` methods for each applicable object are documented at the Admin API reference noted above. If you are having trouble with these, consider posting to the mailing list (https://groups.google.com/forum/#!forum/konglayer) with a detailed description of your issue, as there is no bug with Kong here per se. Thank you!
