### ISSUE TITLE
Galileo Plugin breaks Basic-Auth

### ISSUE THREAD

**Issue by Tigraine** [Mashape/kong#2665]
### Summary

Whenever I enable the Galileo Plugin it will break with a nullref on the following line:
https://github.com/Mashape/kong/blob/next/kong/plugins/galileo/handler.lua#L43
The request is not being served and there is no response from the API.

We are upstreaming to a PHP service that worked fine all the time, but with basicauth
Disabling Galileo fixes the issue.

### Additional Details & Logs

- Kong version 0.10.3
- Docker on Kubernetes

Things I found out in debugging: Apparently the galileo access filter is not being run in this case - that's why it's then breaking in the handler.

**Comment by p0pr0ck5** [comment]
Thanks for the report @Tigraine. With basic auth enabled, do you only see Galileo errors when authorization fails, or with all requests?

Also, it looks like this should be an easy fix, but for completeness, can you provide us with an error log/stack trace when you encounter this?

**Comment by Tigraine** [comment]
I'll have to check the logs again on Monday. But the issue being that the browser is not being presented with a basic auth dialog at all. If you already completed the auth and I turn on Galileo it works. If there is no active session the site is broken

**Comment by p0pr0ck5** [comment]
Can you define "broken" for us? Do you get a 4xx/5xx status code? Can you also clarify if you are using the  basic-auth plugin in Kong, or is your upstream handling the basic auth exclusively?

**Comment by Tigraine** [comment]
We are using basic-auth on kong. If we enable Galileo we get a empty response from server. I'll have to check on the exact status code.

**Comment by Tieske** [comment]
@Tigraine any update on this?

**Comment by Tigraine** [comment]
experimenting with it right now .. will update once I figure it out

**Comment by thefosk** [comment]
@Tigraine just a ping to check for further updates

**Comment by Tigraine** [comment]
@thefosk I guess this can be closed for now.
We now went with enabling Galileo only on specific public-facing APIs that don't have basic-auth and it seems to work fine that way. If I run into this again I'll investigate further and re-open if necessary.
