### ISSUE TITLE
Error,can't Install with source code in Centos6.5

### ISSUE THREAD

**Issue by sioomy** [Mashape/kong#2667]
hi,team,
     I am using kong ,but i can't install it in Centos6.4 with source code.
     I operate as the document  ,the comment with this

$ wget http://ftp.pcre.org/pub/pcre/pcre-8.00.tar.gz
    $ tar zxvf pcre-8.00.tar.gz
    $ cd pcre-8.00
    $ make
    $ sudo make install
    $ cd ~
$ wget http://openresty.org/download/openresty-1.11.2.3.tar.gz
    $ tar zxvf openresty-1.11.2.3.tar.gz
    $ cd openresty-1.11.2.3
    $ ./configure \
          --with-pcre-jit \
          --with-ipv6 \
          --with-http_realip_module \
          --with-http_ssl_module \
          --with-http_stub_status_module \
          --without-luajit-lua52
    $ gmake
    $ sudo gmake install

$ wget http://luarocks.github.io/luarocks/releases/luarocks-2.4.2.tar.gz
    $ tar zxvf luarocks-2.4.2.tar.gz
    $ cd luarocks-2.4.2
    $ ./configure --help
    $ ./configure \
        --lua-suffix=jit \
        --with-lua=/usr/local/openresty/luajit \
        --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1
    $ make build
    $ sudo make install

when i type 
   sudo  luarocks install kong 0.10.3-0
then ,the Error happend:

EAD is now at ad0412a... Update to 1.0.2
gcc -O2 -fPIC -I/usr/include -c bit.c -o bit.o
bit.c:83:2: 错误：#error "Unknown number type, check LUA_NUMBER_* in luaconf.h"

Error: Failed installing dependency: http://www.luarocks.org/repositories/rocks/lua-resty-mediador-0.1.2-1.src.rock - Failed installing dependency: http://www.luarocks.org/repositories/rocks/luabitop-1.0.2-3.rockspec - Build error: Failed compiling object bit.o

then : I type 
$ wget http://www.luarocks.org/repositories/rocks/lua-resty-mediador-0.1.2-1.src.rock --no-check-certificate
$ sudo luarocks make lua-resty-mediador-0.1.2-1.src.rock
then 
bit.c:83:2: 错误：#error "Unknown number type, check LUA_NUMBER_* in luaconf.h"

Error: Failed installing dependency: http://www.luarocks.org/repositories/rocks/luabitop-1.0.2-3.rockspec - Build error: Failed compiling object bit.o

as so on~~~~~~

NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by p0pr0ck5** [comment]
What version of the Lua library do you have installed on your system?

**Comment by p0pr0ck5** [comment]
Closing as stale following no response. If you have further details to provide us, please let us know. Thank you!

**Comment by bungle** [comment]
This is not about Kong, but `luabitop` compilation. We don't actually needed but some libraries that Kong uses depend on this for Lua compatibility (LuaJIT is fine without it). LuaRocks doesn't support different dependencies for different flavours of runtimes. Consult this http://bitop.luajit.org/install.html.

**Comment by bungle** [comment]
I stand corrected, actually LuaRocks is aware of LuaJIT and doesn't require luabitop when run on LuaJIT. It must be that you are running with Lua then.

**Comment by sumufan** [comment]
thank you
