### ISSUE TITLE
Are any further plugins going to be open source?

### ISSUE THREAD

**Issue by Floby** [Mashape/kong#2668]
With the new plugins for OAuth2 Introspect and OIDC being released as enterprise-only plugins, I would like to know if this is the direction that Kong is taking.

**Comment by Tieske** [comment]
We are committed to open source and would love to open source everything, but it is the reality of doing business that we also have to make money. We will only be able to support the Kong Community Edition if we sell enough enterprise licenses. So we are currently working hard to build the extra business value for enterprises, as you've noticed by the Oauth2 Introspection and OIDC plugins.

>  I would like to know if this is the direction that Kong is taking

We are not 'taking a direction' here, it depends on the plugin functionality. When it is something that is typical for enterprises and represents enough value for them to buy the Kong Enterprise package then it will probably be enterprise only for starters. But this is not set in stone, any specific plugin might be open sourced later on, provided enough value remains for Kong Enterprise Edition.

Wether you choose to stick with Kong Community Edition is up to you, considering you're getting a fast API gateway, horizontally scaling in a cluster, load balancing over your services, covering logging, lots of authentication options, and a whole lot more, for exactly  0 USD. Now I think that's a lot of bang for no buck.

So I hope you don't blame us for having to make a living to, and I'd like to thank you (and the rest of the community) for your support in helping us to get Kong this far. I sincerely hope you stay with us. 😄

**Comment by paritoshmmmec** [comment]
I agree with @Tieske  , For supporting open source need money.  Open source should not be free at all (at least it never meant to)

**Comment by Floby** [comment]
@Tieske Thank you for your answer.

@paritoshmmmec I think you are reading into my question.

**Comment by Floby** [comment]
@Tieske Follow-up questions/remark =)
As part of my job is to counsel companies regarding the right tools for their API strategies, one very useful thing for me would be to be able to access the same level of documentation without needing an enterprise account. Part of this is because there is no way to tell what the price of a mashape enterprise account is from the website (or I cannot find it). So it seems to me that I'm being asked to pay to read a document which will tell me if this plugin is the right one for any given use-case. I know you have to retain value for your enterprise edition, but it feels that a freely accessible documentation would be able to showcase said value =)

**Comment by p0pr0ck5** [comment]
I don't think a GitHub issue is the appropriate place for this discussion. If there are still pending questions here, let's move this to the mailing list instead of keeping discussion in a closed issue.

**Comment by Tieske** [comment]
In addition to @p0pr0ck5 , please use the form here https://www.mashape.com/enterprise/#demo-form to leave your contact details so we can make sure you get all the details you need.
