### ISSUE TITLE
kong-0.10.1-1 with redis policy for  rate limit  ( When limit reaches instead to giving exceeded messages everytime it's giving messages on every alternative time )

### ISSUE THREAD

**Issue by anupam4881** [Mashape/kong#2669]
Dear Team,

I am trying to check rate limit functionality. With cluster policy, it works fine ( give a message "API rate limit exceeded") if crossing limit every time.  Now keeping performance in mind We installed redis and change the policy to redis with all required setting. For testing purpose, we set initial limit very low and it starts giving the same message once it crossing define limits  (API rate limit exceeded")
Now there is a difference, which we are unable to understand. 
When limit reaches instead to giving exceeded messages everytime it's giving messages on every alternative time ( 50% only). same behavior we are observing with local policy also.  Need your help to fix this configuration issue.

 

Thanks in Advance. 

[root@psld-ggn-176 ~]#  curl -X GET http://localhost:8001/apis
{"data":[{"http_if_terminated":true,"id":"cd41a5e7-51a9-4b79-a9e9-b3f6301356d5","retries":5,"preserve_host":false,"created_at":1499047197542,"upstream_connect_timeout":60000,"upstream_url":"http:\/\/address.v1.service\/codeigniter\/index.php\/A\/emp","uris":["\/A"],"upstream_send_timeout":60000,"https_only":true,"upstream_read_timeout":60000,"strip_uri":true,"name":"address-service","hosts":{}}],"total":1}
[root@psld-ggn-176 ~]# curl -X GET    http://localhost:8001/upstreams/address.v1.service/
{"orderlist":[77,91,74,54,6,76,51,94,58,17,82,4,73,14,47,56,7,85,86,28,71,5,32,57,37,21,99,88,25,75,59,83,39,44,15,24,93,66,80,19,63,60,61,68,52,9,1,90,50,67,16,18,55,62,38,72,12,42,97,26,35,10,33,81,79,45,41,2,98,23,100,34,13,70,40,87,53,65,84,43,48,22,96,31,27,46,20,3,30,95,69,78,36,8,29,64,92,89,49,11],"slots":100,"id":"46df6b58-fe69-4811-92f7-52a4bbd3a31c","name":"address.v1.service","created_at":1499046571719}
[root@psld-ggn-176 ~]# curl -X GET    http://localhost:8001/upstreams/address.v1.service/targets
{"data":[{"target":"192.168.0.205:80","id":"b6b82120-2724-4736-9ddb-941544b9688d","weight":50,"created_at":1499067581294,"upstream_id":"46df6b58-fe69-4811-92f7-52a4bbd3a31c"}],"total":1}

[root@psld-ggn-176 ~]# curl -X GET    http://localhost:8001/plugins
{"data":[{"api_id":"cd41a5e7-51a9-4b79-a9e9-b3f6301356d5","id":"0cb03f10-9655-44bb-8fb4-b7407fb2066c","created_at":1499143201383,"enabled":true,"name":"rate-limiting","config":{"limit_by":"consumer","policy":"redis","redis_database":9,"redis_password":"edispassword","redis_port":6379,"day":1,"redis_timeout":2000,"fault_tolerant":false,"redis_host":"192.168.0.167"}},{"api_id":"cd41a5e7-51a9-4b79-a9e9-b3f6301356d5","id":"0ac252b4-bbb6-4fd1-96c1-0e074e243ac8","created_at":1499139095161,"enabled":true,"name":"ip-restriction","config":{"blacklist":["192.168.45.0\/24"]}}],"total":2}
[root@psld-ggn-176 ~]#

Regards
Anupam Narayan

**Comment by anupam4881** [comment]
Any help will be very helpful to fix this issue. 

Thanks in advance.

Regards
Anupam Narayan

**Comment by p0pr0ck5** [comment]
@anupam4881 can you try this behavior on Kong 0.10.3? Recently there were some changes to related to handling Redis databases, which according to your config you are using, so this may have been resolved in a recent release.

**Comment by anupam4881** [comment]
@p0pr0ck5 (Robert), Thanks it is working in new available version 0.10.3. 
Regards, 
Anupam Narayan
