### ISSUE TITLE
Add name field to certificate object giving it similar semantics to that of other entities

### ISSUE THREAD

**Issue by calvinlfer** [Mashape/kong#2677]
Hello there, 

For [certificate objects](https://getkong.org/docs/0.10.x/admin-api/#certificate-object) in Kong, they only possess an `id` which makes it hard to identify and manage. I was wondering if it was possible to add a `name` field with the same semantics found in API objects enabling you to search by `name` or uniquely identify an object by `name`. It would be more consistent with the other existing objects and it makes it easier to manage with declarative configuration tools because it's a lot of guesswork to figure out how to properly identify a certificate without a friendly name.

**Comment by p0pr0ck5** [comment]
Hey @calvinlfer,

Thanks for bringing this up! Since SNI names are enforced with uniqueness to Certificate objects, would this suffice for your use case? e.g. either the UUID or an SNI name can be used as route params: https://getkong.org/docs/0.10.x/admin-api/#retrieve-certificate

**Comment by calvinlfer** [comment]
Hey @p0pr0ck5, that's actually a good point. I'll have to think about this some more. I'll close this out for now. 

Cheers
Cal
