### ISSUE TITLE
how can use nginx log_format on kong 10.3

### ISSUE THREAD

**Issue by Hello-Mango** [Mashape/kong#2678]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary
I want to use nginx log_format on kong 10.3 access_log ,how can I config this info? thank you

**Comment by Hello-Mango** [comment]
I find this config ,sorry  I will close this issue

**Comment by p0pr0ck5** [comment]
Hi,

See the following docs: https://getkong.org/docs/0.10.x/configuration/#custom-nginx-configuration-embedding-kong

**Comment by Hello-Mango** [comment]
![tim 20170710134658](https://user-images.githubusercontent.com/29136644/28004311-4dd9fa6e-6576-11e7-8f44-de706c8c6744.png)
I See this dics and I Use the configration, But log_format also not be work,what should I do to resolve this question?

**Comment by EverCurse** [comment]
@Hello-Mango  do u resolve this question？
