### ISSUE TITLE
[rate-limiting] rate-limiting plugin reset quota in UTC time 00:00

### ISSUE THREAD

**Issue by passos** [Mashape/kong#2680]
### Summary
rate-limiting plugin doesn't reset usage quota at 00:00. 

Since rate-limiting plugin use `local current_timestamp = timestamp.get_utc()` in `function RateLimitingHandler:access(conf)` as current time so that the `redis` cache key `local cache_key = get_local_key(api_id, identifier, period_date, period)` is named by UTC time.

The consequence is the consumer rate-limiting quota will not reset at 00:00. The reset time is depends on the timezone. For example, it reset quota data at 8am in China which time zone is UTC+8 .

I think the `current_timestamp` should use local time instead of UTC time.

### Steps To Reproduce

1. install kong and rate-limiting plugin 
2. set a day limit for a consumer
3. set server's timezone to `+x`
4. watch the response header `X-RateLimit-Limit-Day` and `X-RateLimit-Remaining-Day`, they will be reset at time `x`

### Additional Details & Logs
- Kong version 0.10.3

**Comment by thefosk** [comment]
The reason we use UTC time is to take into account multiple Kong nodes in different data-centers or regions. By using UTC time, we are sure that the behavior is consistent across the entire cluster.

**Comment by p0pr0ck5** [comment]
Closing given the above. Thanks thefosk!

**Comment by passos** [comment]
There is no problem to use  UTC time internal. But the behavior is weird that the quota of a "day" reset at morning or noon for a cluster deployed in same time-zone. 

I would suggest having an option to set when to reset the time.

**Comment by olderwei** [comment]
Yes, I have the same problem. Is there any solution to this problem? Now, I have set current_timestamp to local time to solve this problem.
