### ISSUE TITLE
I would like to ask, how can be achieved without the registration of the api can also be forwarded to the specified server

### ISSUE THREAD

**Issue by inewlife** [Mashape/kong#2688]

**Comment by Tieske** [comment]
@inewlife please do not use such long titles, but short descriptive ones. Use the description for more details.

Kong cannot forward requests if you do not create an api with it. How would Kong know where it would have to send the request?

One options that is available is to create an API that matches **every** request. You can do so by creating an api without `hosts` and `methods` specified, and set field `uris=/`. This will effectively create a 'catch-all' api. Every request received will be forwarded to the upstream as specified in the `upstream_url` field.
