### ISSUE TITLE
Kong fails to start

### ISSUE THREAD

**Issue by ksachdeva11** [Mashape/kong#2690]
**Logs** :

ksachdeva$ kong restart --conf kong.conf --vv
2017/07/11 15:43:22 [verbose] Kong: 0.10.3
2017/07/11 15:43:22 [debug] ngx_lua: 10007
2017/07/11 15:43:22 [debug] nginx: 1011002
2017/07/11 15:43:22 [debug] Lua: LuaJIT 2.1.0-beta2
2017/07/11 15:43:22 [verbose] reading config file at kong.conf
2017/07/11 15:43:22 [debug] admin_access_log = "logs/admin_access.log"
2017/07/11 15:43:22 [debug] admin_error_log = "logs/error.log"
2017/07/11 15:43:22 [debug] admin_listen = "0.0.0.0:8001"
2017/07/11 15:43:22 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/07/11 15:43:22 [debug] admin_ssl = true
2017/07/11 15:43:22 [debug] anonymous_reports = true
2017/07/11 15:43:22 [debug] cassandra_consistency = "ONE"
2017/07/11 15:43:22 [debug] cassandra_contact_points = {"127.0.0.1"}
2017/07/11 15:43:22 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/07/11 15:43:22 [debug] cassandra_keyspace = "kong"
2017/07/11 15:43:22 [debug] cassandra_lb_policy = "RoundRobin"
2017/07/11 15:43:22 [debug] cassandra_port = 9042
2017/07/11 15:43:22 [debug] cassandra_repl_factor = 1
2017/07/11 15:43:22 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/07/11 15:43:22 [debug] cassandra_schema_consensus_timeout = 10000
2017/07/11 15:43:22 [debug] cassandra_ssl = false
2017/07/11 15:43:22 [debug] cassandra_ssl_verify = false
2017/07/11 15:43:22 [debug] cassandra_timeout = 5000
2017/07/11 15:43:22 [debug] cassandra_username = "kong"
2017/07/11 15:43:22 [debug] client_ssl = false
2017/07/11 15:43:22 [debug] cluster_listen = "0.0.0.0:7946"
2017/07/11 15:43:22 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/07/11 15:43:22 [debug] cluster_profile = "wan"
2017/07/11 15:43:22 [debug] cluster_ttl_on_failure = 3600
2017/07/11 15:43:22 [debug] custom_plugins = {"request-validate-userid","request-validate-userid-in-header"}
2017/07/11 15:43:22 [debug] database = "cassandra"
2017/07/11 15:43:22 [debug] dns_hostsfile = "/etc/hosts"
2017/07/11 15:43:22 [debug] dns_resolver = {}
2017/07/11 15:43:22 [debug] latency_tokens = true
2017/07/11 15:43:22 [debug] log_level = "info"
2017/07/11 15:43:22 [debug] lua_code_cache = "on"
2017/07/11 15:43:22 [debug] lua_package_cpath = ""
2017/07/11 15:43:22 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/07/11 15:43:22 [debug] lua_socket_pool_size = 30
2017/07/11 15:43:22 [debug] lua_ssl_verify_depth = 1
2017/07/11 15:43:22 [debug] mem_cache_size = "128m"
2017/07/11 15:43:22 [debug] nginx_daemon = "on"
2017/07/11 15:43:22 [debug] nginx_optimizations = true
2017/07/11 15:43:22 [debug] nginx_worker_processes = "auto"
2017/07/11 15:43:22 [debug] pg_database = "kong"
2017/07/11 15:43:22 [debug] pg_host = "127.0.0.1"
2017/07/11 15:43:22 [debug] pg_port = 5432
2017/07/11 15:43:22 [debug] pg_ssl = false
2017/07/11 15:43:22 [debug] pg_ssl_verify = false
2017/07/11 15:43:22 [debug] pg_user = "kong"
2017/07/11 15:43:22 [debug] prefix = "/usr/local/kong/"
2017/07/11 15:43:22 [debug] proxy_access_log = "logs/access.log"
2017/07/11 15:43:22 [debug] proxy_error_log = "logs/error.log"
2017/07/11 15:43:22 [debug] proxy_listen = "127.0.0.1:9900"
2017/07/11 15:43:22 [debug] proxy_listen_ssl = "127.0.0.1:9943"
2017/07/11 15:43:22 [debug] serf_path = "serf"
2017/07/11 15:43:22 [debug] server_tokens = true
2017/07/11 15:43:22 [debug] ssl = true
2017/07/11 15:43:22 [debug] ssl_cipher_suite = "modern"
2017/07/11 15:43:22 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2017/07/11 15:43:22 [debug] upstream_keepalive = 60
2017/07/11 15:43:22 [verbose] prefix in use: /usr/local/kong
2017/07/11 15:43:22 [verbose] reading config file at kong.conf
2017/07/11 15:43:22 [debug] admin_access_log = "logs/admin_access.log"
2017/07/11 15:43:22 [debug] admin_error_log = "logs/error.log"
2017/07/11 15:43:22 [debug] admin_listen = "0.0.0.0:8001"
2017/07/11 15:43:22 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/07/11 15:43:22 [debug] admin_ssl = true
2017/07/11 15:43:22 [debug] anonymous_reports = true
2017/07/11 15:43:22 [debug] cassandra_consistency = "ONE"
2017/07/11 15:43:22 [debug] cassandra_contact_points = {"127.0.0.1"}
2017/07/11 15:43:22 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/07/11 15:43:22 [debug] cassandra_keyspace = "kong"
2017/07/11 15:43:22 [debug] cassandra_lb_policy = "RoundRobin"
2017/07/11 15:43:22 [debug] cassandra_port = 9042
2017/07/11 15:43:22 [debug] cassandra_repl_factor = 1
2017/07/11 15:43:22 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/07/11 15:43:22 [debug] cassandra_schema_consensus_timeout = 10000
2017/07/11 15:43:22 [debug] cassandra_ssl = false
2017/07/11 15:43:22 [debug] cassandra_ssl_verify = false
2017/07/11 15:43:22 [debug] cassandra_timeout = 5000
2017/07/11 15:43:22 [debug] cassandra_username = "kong"
2017/07/11 15:43:22 [debug] client_ssl = false
2017/07/11 15:43:22 [debug] cluster_listen = "0.0.0.0:7946"
2017/07/11 15:43:22 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/07/11 15:43:22 [debug] cluster_profile = "wan"
2017/07/11 15:43:22 [debug] cluster_ttl_on_failure = 3600
2017/07/11 15:43:22 [debug] custom_plugins = {"request-validate-userid","request-validate-userid-in-header"}
2017/07/11 15:43:22 [debug] database = "cassandra"
2017/07/11 15:43:22 [debug] dns_hostsfile = "/etc/hosts"
2017/07/11 15:43:22 [debug] dns_resolver = {}
2017/07/11 15:43:22 [debug] latency_tokens = true
2017/07/11 15:43:22 [debug] log_level = "info"
2017/07/11 15:43:22 [debug] lua_code_cache = "on"
2017/07/11 15:43:22 [debug] lua_package_cpath = ""
2017/07/11 15:43:22 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/07/11 15:43:22 [debug] lua_socket_pool_size = 30
2017/07/11 15:43:22 [debug] lua_ssl_verify_depth = 1
2017/07/11 15:43:22 [debug] mem_cache_size = "128m"
2017/07/11 15:43:22 [debug] nginx_daemon = "on"
2017/07/11 15:43:22 [debug] nginx_optimizations = true
2017/07/11 15:43:22 [debug] nginx_worker_processes = "auto"
2017/07/11 15:43:22 [debug] pg_database = "kong"
2017/07/11 15:43:22 [debug] pg_host = "127.0.0.1"
2017/07/11 15:43:22 [debug] pg_port = 5432
2017/07/11 15:43:22 [debug] pg_ssl = false
2017/07/11 15:43:22 [debug] pg_ssl_verify = false
2017/07/11 15:43:22 [debug] pg_user = "kong"
2017/07/11 15:43:22 [debug] prefix = "/usr/local/kong"
2017/07/11 15:43:22 [debug] proxy_access_log = "logs/access.log"
2017/07/11 15:43:22 [debug] proxy_error_log = "logs/error.log"
2017/07/11 15:43:22 [debug] proxy_listen = "127.0.0.1:9900"
2017/07/11 15:43:22 [debug] proxy_listen_ssl = "127.0.0.1:9943"
2017/07/11 15:43:22 [debug] serf_path = "serf"
2017/07/11 15:43:22 [debug] server_tokens = true
2017/07/11 15:43:22 [debug] ssl = true
2017/07/11 15:43:22 [debug] ssl_cipher_suite = "modern"
2017/07/11 15:43:22 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2017/07/11 15:43:22 [debug] upstream_keepalive = 60
2017/07/11 15:43:22 [verbose] prefix in use: /usr/local/kong
2017/07/11 15:43:22 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/07/11 15:43:22 [info] prefix directory /usr/local/kong not found, trying to create it
2017/07/11 15:43:22 [verbose] could not start Kong, stopping services
2017/07/11 15:43:22 [verbose] leaving serf cluster
2017/07/11 15:43:22 [verbose] left serf cluster
2017/07/11 15:43:22 [verbose] stopping serf agent at /usr/local/kong/pids/serf.pid
2017/07/11 15:43:22 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/07/11 15:43:22 [debug] no pid file at: /usr/local/kong/pids/serf.pid
2017/07/11 15:43:22 [verbose] serf agent stopped
2017/07/11 15:43:22 [verbose] stopped services
Error:
...enresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/start.lua:34: ...enresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/start.lua:20: Permission denied
stack traceback:
	[C]: in function 'error'
	...enresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/start.lua:34: in function 'execute'
	...resty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/restart.lua:13: in function 'cmd_exec'
	...penresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/init.lua:88: in function <...penresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	...penresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/init.lua:88: in function <...penresty/1.11.2.2/luajit/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:40: in function <init_worker_by_lua:38>
	[C]: in function 'pcall'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
bldm2558-mac:kong ksachdeva$

### Additional Details & Logs

- Kong version (`$ kong version`) - 0.10.3
- Operating System - Mac OS Sierra

**Comment by kikito** [comment]
Hello @ksachdeva11,

The problem you are having is that the *prefix folder* isn't writable.

The prefix folder is a place where each kong instance creates and stores files it needs in order to operate: for example logs and process Ids. Your config file says that the prefix folder is `/usr/local/kong`. Since it didn't exist, it attempted to create it inside `/usr/local`, at which point it threw a "permission denied" error - this seems to indicate that your user doesn't have write access to `/usr/local`.

My suggestion would be either to manually create a `/usr/local/kong` folder with a super user, (granting write permissions to your regular user), or changing the `prefix_folder` option in your config file to a place where your user has write access (on osx, you should be able to write `/usr/local/opt/kong`, or anywhere in your personal folder) 

If you still have questions regarding this, kindly use [one of the appropiate support channels](https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help). Github issues are for actual bug reports only. Thank you.

**Comment by ksachdeva11** [comment]
Thanks @kikito ! Manually adding a directory with admin permissions worked.

**Comment by DemonLee0719** [comment]
There hava a new issua, when I command "kong reload";
WHY? Thank you.


drwxr-xr-x    2 root     root            37 Jan  8 00:19 bin
/usr/local/opt/kong # ls -l
total 16
drwx------    2 kong     root             6 May  9 05:27 client_body_temp
drwx------    2 kong     root             6 May  9 05:27 fastcgi_temp
drwxr-xr-x    2 kong     root            65 May  9 05:27 logs
-rw-r--r--    1 kong     root          1590 May  9 05:28 nginx-kong-stream.conf
-rw-r--r--    1 kong     root          5156 May  9 05:28 nginx-kong.conf
-rw-r--r--    1 kong     root           221 May  9 05:28 nginx.conf
drwxr-xr-x    2 kong     root            23 May  9 05:27 pids
drwx------    2 kong     root             6 May  9 05:27 proxy_temp
drwx------    2 kong     root             6 May  9 05:27 scgi_temp
drwxr-xr-x    2 kong     root           114 May  9 05:27 ssl
drwx------    2 kong     root             6 May  9 05:27 uwsgi_temp
/usr/local/opt/kong # kong reload
Kong reloaded
/usr/local/opt/kong # ls -l
total 16
drwx------    2 nobody   root             6 May  9 05:27 client_body_temp
drwx------    2 nobody   root             6 May  9 05:27 fastcgi_temp
drwxr-xr-x    2 kong     root            65 May  9 05:27 logs
-rw-r--r--    1 kong     root          1590 May  9 05:58 nginx-kong-stream.conf
-rw-r--r--    1 kong     root          5156 May  9 05:58 nginx-kong.conf
-rw-r--r--    1 kong     root           221 May  9 05:58 nginx.conf
drwxr-xr-x    2 kong     root            23 May  9 05:27 pids
drwx------    2 nobody   root             6 May  9 05:27 proxy_temp
drwx------    2 nobody   root             6 May  9 05:27 scgi_temp
drwxr-xr-x    2 kong     root           114 May  9 05:27 ssl
drwx------    2 nobody   root             6 May  9 05:27 uwsgi_temp
/usr/local/opt/kong #

**Comment by BrixSat** [comment]
if you have "nginx_daemon=on" in config also add to /lib/systemd/system/kong.service Type=forking or it wont work.
