### ISSUE TITLE
Logging to SPLUNK supported ?

### ISSUE THREAD

**Issue by mkasmani** [Mashape/kong#2691]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by Tieske** [comment]
Please search for answers before creating new issues, and read the posted guidelines ^^^

> We already support splunk via our TCP/UDP logging plugins. How would a splunk plugin be different?

see #1620
