### ISSUE TITLE
how to use request_path in 0.10.3?

### ISSUE THREAD

**Issue by bringtree** [Mashape/kong#2697]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

in v0.9.x when i add apis.
I can use request_path  in List APIs, but i can't find it in v.10.x.
I hope you can tell me ,how to do it ,if i need to use  request_path in v.10.x.   
 Thx

### Additional Details & Logs

- Kong version (`$ kong version`)
v0.10.x

**Comment by thibaultcha** [comment]
Hi,

0.10 introduced different variables for API matching, namely: `hosts`, `uris`, and `methods`. Each of those attributes can contain several value, as it was not the case with `request_path`. 

I highly recommend that you spend some time reading the documentation on this topic (and others). You can find the guide for this particular topic on 0.10.x here: https://getkong.org/docs/0.10.x/proxy/

**Comment by bringtree** [comment]
and when i use the Galileo Plugin , should i pay for this service in advance ?

**Comment by longxianlin** [comment]
same question.

localhost:8000/user/{:id} is good

localhost:8000
Host: userapi

not good
