### ISSUE TITLE
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:23

### ISSUE THREAD

**Issue by inewlife** [Mashape/kong#2698]
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:385: /usr/local/share/lua/5.1/kong/core/globalpatches.lua:328: no request found
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:385: in function 'load_module_if_exists'
	/usr/local/share/lua/5.1/kong.lua:89: in function 'load_plugins'
	/usr/local/share/lua/5.1/kong.lua:154: in function 'init'
	init_by_lua:5: in main chunk

**Comment by Tieske** [comment]
@inewlife There is no possible way for us to make any sense of this issue without you providing some context. Please read and follow the instructions in the template for new issues.

This most likely is not a bug but a configuration error, so please post issues like this first on the [Gitter channel](https://gitter.im/Mashape/kong) or in the [mailing list](https://groups.google.com/forum/#!forum/konglayer)
