### ISSUE TITLE
[feather] Can i custom the 'kong error' page

### ISSUE THREAD

**Issue by Cospotato** [Mashape/kong#2701]
In the production environment, we need add some logic to the page when upstream response an error. I found that the error handler was hard coded in `kong.core.error_handlers`.

Have some easy way to custom the 'kong error' page like redirect to some url or any others?

**Comment by chenyukang** [comment]
Hi @Cospotato ,
 I am also have this feature requirement, this is our solution right now, it's a little hack, but currently it's works. 
 Currently we just ngx.say out some html, but we can do more thing in the 'error_handle'.

  FYI: https://github.com/chenyukang/kong/pull/1/files

**Comment by Cospotato** [comment]
@chenyukang Nice work! I will try it out recently

**Comment by p0pr0ck5** [comment]
Currently this cannot be done programmatically with Kong; however, you can use a custom Nginx configuration file and modify the error page location accordingly. See https://getkong.org/docs/0.10.x/configuration/#custom-nginx-configuration

BTW, please try to reserve Github issues for actual problems running Kong, not just asking questions. Please see https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help
