### ISSUE TITLE
Logformat changes

### ISSUE THREAD

**Issue by mynameisgv** [Mashape/kong#2723]
How do I change the default logformat in kong.
I tried changing "logformat main" in 
/usr/local/openresty/nginx/conf/nginx.conf

But I did not see any impact on the log file. (Access.log or error.log)

Is there any other place this can be changed?

Thanks

**Comment by p0pr0ck5** [comment]
Hello!

Currently this needs to be done with a custom Nginx configuration. Please see https://getkong.org/docs/0.10.x/configuration/#custom-nginx-configuration from the docs.

In the future, please use [Gitter](https://gitter.im/Mashape/kong) or the [mailing list](https://groups.google.com/forum/#!forum/konglayer) for such questions. The Github issue boilerplate you removed explicitly states that Github issues should be reserved for issues running Kong. Thank you!
