### ISSUE TITLE
Exception in base_controller.lua when value is missing

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#273]
I was trying to add a plugin to an API:

```shell
curl -d "name=filelog&api_id=fbaf95a1-cd04-4bf6-cb73-6cb3285fef58" 127.0.0.1:8001/plugins_configurations/
{"value":"value is required"}
```

It tells me `value` is required. I then pretend to be a user who just follows the instructions, and I add `value`:

```shell
curl -d "name=filelog&api_id=fbaf95a1-cd04-4bf6-cb73-6cb3285fef58&value" 127.0.0.1:8001/plugins_configurations/
{"message":"An unexpected error occurred"}
```

1. The API shoudn't tell me to add `value`, but to add every `value.property_name` that is required.
2. When adding just `value`, it shouldn't fail with 500 error but return the same error message as (1).

**Comment by thibaultCha** [comment]
Valid, but please dont use this endpoint anymore tho, the new routing needs to be tested.

**Comment by thibaultCha** [comment]
Also the real bug is that value shouldn't be required here, filelog doesn't have any configuration

**Comment by thefosk** [comment]
I am working on my local changes where filelog now has a value in the schema (didn't push yet), you can replicate it with any other plugin that requires a value.
