### ISSUE TITLE
Docker Kong does not start - Following the getting started guide

### ISSUE THREAD

**Issue by augusto-altman** [Mashape/kong#2730]
### Summary

I'm just following the [getting started guide with Docker Kong](https://getkong.org/install/docker/). I'm able to start Cassandra correctly (step 1 in the guide), and when I try to start Kong (step 2 in the guide) I get the following error: 

> docker: Error response from daemon: driver failed programming external connectivity on endpoint kong (d6f3d2198b6f6785b1a7dfa09189fe1dd624eb8a423c593ced39ddfd6a1b7d64): Error starting userland proxy: listen tcp 0.0.0.0:7946: bind: address already in use.

### Steps To Reproduce

Follow the [getting started guide for Docker Kong](https://getkong.org/install/docker/)

### Additional Details & Logs

- Kong version: 0.10.3
- Kong configuration: The one specified in the guide
- Operating System: Ubuntu 16.04
- Docker version: 17.06.0-ce, API Version 1.30
- **Things to  notice:** Something that  called my attention is that in my local machine I have the port 7946 taken by the process dockerd (both tcp and udp). As far as I read this is related with Docker Swarm.

**Comment by shashiranjan84** [comment]
Kong use port 7946(UPD, TCP) for clustering, so please make sure its not being used by any other application.

**Comment by augusto-altman** [comment]
@shashiranjan84 Yes I know! That is why I put the _Things to notice_ point on my original post. I have an Ubuntu fresh install and a Docker fresh install and is DOCKER who is taking the port 7946. So Kong seems to be crashing against Docker, and therefore I think that this may be an incompatibility issue between Kong and the latest Docker version (v17.06.0-ce). If that is the case then this bug cannot be closed. I mean, if that is the case it is not possible to go through the [Getting started guide with Docker](https://getkong.org/install/docker/) with Docker v17.06.0-ce.

**Comment by shashiranjan84** [comment]
In that case you can map different host port to container port 7946. You would also need to update 
`KONG_CLUSTER_ADVERTISE`  with `<HOST_IP>:<HOST_PORT_USED_SERF>`  

More info regarding clustering **https://getkong.org/docs/0.10.x/clustering/**

**Comment by augusto-altman** [comment]
Wow thanks! this is good info, I'm going to try it out today :)
I think it should be officially included on the [Getting started guide with Docker](https://getkong.org/install/docker/) (at least a simple comment mentioning it), this could save a lot of time to a lot of people.

**Comment by shashiranjan84** [comment]
@augusto-altman Yes

**Comment by shashiranjan84** [comment]
@augusto-altman may I know why you want to expose that port in Docker Swarm setup? Should't you using be create kong as service in a overlay network? We definitely need separate documentation for running Kong in swarm mode.

**Comment by augusto-altman** [comment]
@shashiranjan84 Mmmm, I am really not intending to do so, actually I'm just learning, trying to setup a fresh infrastructure using Kong as Api Gateway. Look this is the complete _shortened_ story about what happened:

1. I installed Ubuntu 16.04 in my personal laptop this monday.
2. Right after that I installed docker ce following [this](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/). This installed docker v17.06.0-ce on my machine.
3. I completed the [official Docker getting started guide](https://docs.docker.com/get-started/). So far everything was working very smooth. That guide is really focused on Docker Swarm.
4. I tried to follow the [Kong over Docker getting started guide](https://getkong.org/install/docker/) and I got blocked on the step 2 because of the issue with the port 7946.
5. I checked with _lsof lsof -i tcp:7946_ which process was taking the port 7946 in my machine and surprisingly it was docker :/ (process name _dockerd_)
6. I dag a little and I found that Docker Swarm was the one taking that port.

I don't know if I am missing something here, but it seems to be that Docker latest (or at least Docker v17.06.0-ce) comes with Docker Swarm enabled out of the box and is taking that port by default to communicate between Docker Swarm nodes. So basically what I think is that, if I'm correct, newcomers as me trying to start from the ground (fresh install) with Kong will crash against the same wall (because they will probably have the latest Docker version on their machines as well).

I'm far of being an expert, I'm actually a new starter. As you can see I'm just following getting started guides (docker, kong, etc). But I got blocked doing this, so I think it is worth to use my case to improve the docs. I know Kong is an awesome product, very mature, that is why I wanted to use it. We can work through this and maybe find some points for improving the getting started experience for newcomers.

**Comment by shashiranjan84** [comment]
Thanks for information. We are glad you like Kong. We will try to reproduce and resolve it asap. Meanwhile feel free to send us feedback or even a PR with correction.

**Comment by shashiranjan84** [comment]
@augusto-altman I just followed your steps and Kong ran just fine for me on Ubuntu 16.04 LTS

```
  sudo apt-get update
  sudo apt-get install     apt-transport-https     ca-certificates     curl     software-properties-common
  sudo apt-get install     linux-image-extra-$(uname -r)     linux-image-extra-virtual
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
  sudo apt-get update
  sudo apt-get install docker-ce
```

![image](https://user-images.githubusercontent.com/8146958/28652743-7f4a7aae-723e-11e7-8cd9-1ce447d05ebc.png)

**Comment by augusto-altman** [comment]
> Seems like you were running swarm mode.

@shashiranjan84 Yes!! you are right. I ran a _sudo docker node ls_ and effectively my machine was a node (as you said I was running on swarm mode). After finding that I ran _sudo docker swarm leave --force_ and then everything worked as expected.

Thank you so much for your help and sorry for the inconvenience. Just a question out of curiosity, is there any known guide or documentation for using Kong over Docker Swarm (it doesn't have to be an official docs)? The only thing that somebody would have to do to run Kong over Docker Swarm is to change the the _KONG_CLUSTER_ADVERTISE_ property?

**Comment by CodingAdai** [comment]
`......listen tcp 0.0.0.0:7946: bind: address already in use.`, I have this problem, too. if swarm mode is active. 
After `docker swarm leave --force` , worked ok.

**Comment by WALL-E** [comment]
7946 port conflict

# serf
The address that Serf will bind to for communication with other Serf nodes. By default this is "0.0.0.0:7946".
#  docker swarm
In order to use the ingress network in the swarm, you need to have the following ports open between the swarm nodes before you enable swarm mode:

Port 7946 TCP/UDP for container network discovery.
Port 4789 UDP for the container ingress network.
