### ISSUE TITLE
After updating the ACL plug-in, it is invalid

### ISSUE THREAD

**Issue by koyuhau** [Mashape/kong#2731]
**Problem description**
I have a API that has configured the ACL plug-in. When I want to change the ACL configuration again, I find that the current ACL plug-in is invalid.

But when I deleted the ACL plug-in and added the configuration again, it worked again, and I thought it might be a bug.

**kong version**:0.10.0

**Comment by p0pr0ck5** [comment]
@koyuhau you will need to provide us much more detailed information about your configuration besides "it's invalid" :D 

What specific configuration did you try? What steps can we take to reproduce? What explicit details can you share with us about this?

**Comment by koyuhau** [comment]
@p0pr0ck5 
**Step:**

1. create a API, configure the basic-auth, ACL plug-in, where the ACL whitelist is set to 'testA'.

2. create consumer, configure the basic-auth parameter, and configure the ACL grouping name "testA"

3. test the API, configure the appropriate permissions parameters. It is accessible at this time.

4., Modify the parameters of ACL white list for'testB'.

5. test the API again.It can still access the interface successfully. However, the consumer is different from the API group and should not be accessible.

6. run command: Kong restart

7. re test interface A. Prompt without permission, normal at this time.

**I think the question might be related to caching。**

**Comment by koyuhau** [comment]
After update to 0.10.3 , it is no problem. Thanks for help.
