### ISSUE TITLE
Request-Transformer Plugin does not replace headers when append.headers is set

### ISSUE THREAD

**Issue by Tigraine** [Mashape/kong#2733]
### Summary

We are running kong 0.10.3 with the `request-transformer` plugin to add user-ids and some other values to our incoming requests.

Authentication is handled through `key-auth` and we have global plugins for each consumer that have the relevant ids:

```
        {
            "config": {
                "add": {
                    "body": {},
                    "headers": {},
                    "querystring": {}
                },
                "append": {
                    "body": {},
                    "headers": [
                        "X-User-Id:2ef463b1-6a55-4ca3-b265-cf72c5da94db",
                    ],
                    "querystring": {}
                },
                "remove": {
                    "body": {},
                    "headers": {},
                    "querystring": {}
                },
                "rename": {
                    "body": {},
                    "headers": {},
                    "querystring": {}
                },
                "replace": {
                    "body": {},
                    "headers": {},
                    "querystring": {}
                }
            },
            "consumer_id": "904a1380-03cd-4ef4-859c-7ddebb704dfb",
            "created_at": 1500540288313,
            "enabled": true,
            "id": "08e330a5-3057-477d-b396-f0ea879d74e0",
            "name": "request-transformer"
        }
```

If I omit the `X-User-Id` parameter the correct values are set on the upstream request.
If the user sends the `X-User-Id` header the value **is not** correctly replaced but just upstreamed directly.

Steps to reproduce:
http http://service/ X-Api-Key:foo => X-User-Id header = foo
http http://service/ X-Api-Key:foo X-User-Id:bar => X-User-Id header = bar and X-Api-Key = foo

This is contrary to the docs where it clearly states:

> List of headername:value pairs. If the header is not set, set it with the given value. If it is already set, a new header with the same name and the new value will be set.

The current behavior obviously allows impersonation attacks since any user knowing the user-id of another user can trick the upstream services into thinking they are actually someone else.

**Comment by Tieske** [comment]
Have you tried the `replace` option? If you add both, it will add it if non-existing, or replace it if it does exist

**Comment by shashiranjan84** [comment]
@Tigraine If you use `append`, all the values would set to same header separated by comma.  Like following example. So check if upstream server getting comma separated value for `X-User-Id` 

```
curl "http://mockbin.com/request?name=foo&name=bar" -H "x-header:foo" -H "x-header:bar"
{
  "startedDateTime": "2017-07-25T20:01:06.135Z",
  "clientIPAddress": "64.125.191.29",
  "method": "GET",
  "url": "http://mockbin.com/request?name=foo&name=bar",
  "httpVersion": "HTTP/1.1",
  "cookies": {},
  "headers": {
    "host": "mockbin.com",
    "connection": "close",
    "accept-encoding": "gzip",
    "x-forwarded-for": "64.125.191.29, 173.245.50.250",
    "cf-ray": "3841b58cd79c262f-DFW",
    "x-forwarded-proto": "http",
    "cf-visitor": "{\"scheme\":\"http\"}",
    "user-agent": "curl/7.51.0",
    "accept": "*/*",
    "x-header": "foo, bar",
    "cf-connecting-ip": "64.125.191.29",
    "x-request-id": "c4c26d6b-4feb-401c-9587-dc05acdbe209",
    "x-forwarded-port": "80",
    "via": "1.1 vegur",
    "connect-time": "6",
    "x-request-start": "1501012866125",
    "total-route-time": "0"
  },
  "queryString": {
    "name": [
      "foo",
      "bar"
    ]
  },
  "postData": {
    "mimeType": "application/octet-stream",
    "text": "",
    "params": []
  },
  "headersSize": 505,
  "bodySize": 0
}
```

**Comment by Tigraine** [comment]
@Tieske I'll try that as a workaround - is this now intended behavior or not?
@shashiranjan84 If you read the documentation closely it clearly states that it will replace the current value: `If it is already set, a new header with the same name and **the new value** will be set` This is either a mistake in the documentation and we have been using this incorrectly so far or a bug in the plugin

**Comment by shashiranjan84** [comment]
`List of headername:value pairs. If the header is not set, set it with the given value. If it is already set, a new header with the same name and the new value will be set.`

I don't see problem with documentation, it basically means a new header with same name and new value will be added to the request without removing the old. I do not see any mention of replacing existing header value. But we will update the doc to make it more explicit.

Logic works as expected, here is the test 
https://github.com/Mashape/kong/blob/master/spec/03-plugins/15-request-transformer/02-access_spec.lua#L1015

Closing this card.

**Comment by Tigraine** [comment]
Hmm. Ok - then it works. Although this could be clearer in the docs.

**Comment by Tieske** [comment]
@Tigraine docs are here https://github.com/Mashape/getkong.org/tree/master/app/plugins , a PR that clarifies this is most welcome :+1:

**Comment by Tigraine** [comment]
Done - thanks for the awesome work :)
