### ISSUE TITLE
relation "nodes" does not exist

### ISSUE THREAD

**Issue by Zeous9** [Mashape/kong#2745]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

 **relation "nodes" does not exist (13)**

/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:22: [postgres error] ERROR: relation "nodes" does not exist (13)

### Steps To Reproduce

1. git checkout next
2. sudo luarocks make
3. sudo luarocks install
4. cd bin/
5. sudo ./kong start --vv

### Additional Details & Logs

- Kong version (next)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System ubuntu 16.04

The details as follow, please help me:

2017/07/27 19:20:36 [verbose] Kong: 0.10.3
2017/07/27 19:20:36 [debug] ngx_lua: 10007
2017/07/27 19:20:36 [debug] nginx: 1011002
2017/07/27 19:20:36 [debug] Lua: LuaJIT 2.1.0-beta2
2017/07/27 19:20:36 [verbose] no config file found at /etc/kong/kong.conf
2017/07/27 19:20:36 [verbose] reading config file at /etc/kong.conf
2017/07/27 19:20:36 [debug] admin_access_log = "logs/admin_access.log"
2017/07/27 19:20:36 [debug] admin_error_log = "logs/error.log"
2017/07/27 19:20:36 [debug] admin_listen = "0.0.0.0:8001"
2017/07/27 19:20:36 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/07/27 19:20:36 [debug] admin_ssl = true
2017/07/27 19:20:36 [debug] anonymous_reports = true
2017/07/27 19:20:36 [debug] cassandra_consistency = "ONE"
2017/07/27 19:20:36 [debug] cassandra_contact_points = {"127.0.0.1"}
2017/07/27 19:20:36 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/07/27 19:20:36 [debug] cassandra_keyspace = "kong"
2017/07/27 19:20:36 [debug] cassandra_lb_policy = "RoundRobin"
2017/07/27 19:20:36 [debug] cassandra_port = 9042
2017/07/27 19:20:36 [debug] cassandra_repl_factor = 1
2017/07/27 19:20:36 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/07/27 19:20:36 [debug] cassandra_schema_consensus_timeout = 10000
2017/07/27 19:20:36 [debug] cassandra_ssl = false
2017/07/27 19:20:36 [debug] cassandra_ssl_verify = false
2017/07/27 19:20:36 [debug] cassandra_timeout = 5000
2017/07/27 19:20:36 [debug] cassandra_username = "kong"
2017/07/27 19:20:36 [debug] client_ssl = false
2017/07/27 19:20:36 [debug] cluster_listen = "0.0.0.0:7946"
2017/07/27 19:20:36 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/07/27 19:20:36 [debug] cluster_profile = "wan"
2017/07/27 19:20:36 [debug] cluster_ttl_on_failure = 3600
2017/07/27 19:20:36 [debug] custom_plugins = {"hello"}
2017/07/27 19:20:36 [debug] database = "postgres"
2017/07/27 19:20:36 [debug] dns_hostsfile = "/etc/hosts"
2017/07/27 19:20:36 [debug] dns_resolver = {}
2017/07/27 19:20:36 [debug] latency_tokens = true
2017/07/27 19:20:36 [debug] log_level = "notice"
2017/07/27 19:20:36 [debug] lua_code_cache = "on"
2017/07/27 19:20:36 [debug] lua_package_cpath = ""
2017/07/27 19:20:36 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/07/27 19:20:36 [debug] lua_socket_pool_size = 30
2017/07/27 19:20:36 [debug] lua_ssl_verify_depth = 1
2017/07/27 19:20:36 [debug] mem_cache_size = "128m"
2017/07/27 19:20:36 [debug] nginx_daemon = "on"
2017/07/27 19:20:36 [debug] nginx_optimizations = true
2017/07/27 19:20:36 [debug] nginx_worker_processes = "auto"
2017/07/27 19:20:36 [debug] pg_database = "kong"
2017/07/27 19:20:36 [debug] pg_host = "0.0.0.0"
2017/07/27 19:20:36 [debug] pg_port = 5432
2017/07/27 19:20:36 [debug] pg_ssl = false
2017/07/27 19:20:36 [debug] pg_ssl_verify = false
2017/07/27 19:20:36 [debug] pg_user = "kong"
2017/07/27 19:20:36 [debug] prefix = "/usr/local/kong/"
2017/07/27 19:20:36 [debug] proxy_access_log = "logs/access.log"
2017/07/27 19:20:36 [debug] proxy_error_log = "logs/error.log"
2017/07/27 19:20:36 [debug] proxy_listen = "0.0.0.0:8000"
2017/07/27 19:20:36 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2017/07/27 19:20:36 [debug] serf_path = "serf"
2017/07/27 19:20:36 [debug] server_tokens = true
2017/07/27 19:20:36 [debug] ssl = true
2017/07/27 19:20:36 [debug] ssl_cipher_suite = "modern"
2017/07/27 19:20:36 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2017/07/27 19:20:36 [debug] upstream_keepalive = 60
2017/07/27 19:20:36 [verbose] prefix in use: /usr/local/kong
2017/07/27 19:20:36 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/07/27 19:20:36 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2017/07/27 19:20:36 [debug] searching for OpenResty 'resty' executable
2017/07/27 19:20:36 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.2'
2017/07/27 19:20:36 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2017/07/27 19:20:36 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2017/07/27 19:20:36 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/07/27 19:20:36 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2017/07/27 19:20:36 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2017/07/27 19:20:36 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2017/07/27 19:20:41 [verbose] running datastore migrations
2017/07/27 19:20:41 [verbose] migrations up to date
2017/07/27 19:20:41 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/07/27 19:20:41 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/07/27 19:20:41 [verbose] serf agent not running, deleting /usr/local/kong/pids/serf.pid
2017/07/27 19:20:41 [debug] searching for 'serf' executable
2017/07/27 19:20:41 [debug] serf version: 'Serf v0.8.0'
2017/07/27 19:20:41 [debug] found 'serf' executable at serf
2017/07/27 19:20:41 [debug] starting serf agent: nohup serf agent -profile 'wan' -bind '0.0.0.0:7946' -log-level 'err' -rpc-addr '127.0.0.1:7373' -event-handler 'member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf/serf_event.sh' -node 'Desktop_0.0.0.0:7946_5d9640aae790475b94d9a78600ac1db4' > /usr/local/kong/logs/serf.log 2>&1 & echo $! > /usr/local/kong/pids/serf.pid
2017/07/27 19:20:41 [verbose] waiting for serf agent to be running
2017/07/27 19:20:41 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/07/27 19:20:41 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/07/27 19:20:41 [verbose] serf agent started
2017/07/27 19:20:41 [verbose] could not start Kong, stopping services
2017/07/27 19:20:41 [verbose] leaving serf cluster
2017/07/27 19:20:41 [verbose] stopped services
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:22: [postgres error] ERROR: relation "nodes" does not exist (13)
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        ./kong:7: in function 'file_gen'
        init_worker_by_lua:38: in function <init_worker_by_lua:36>
        [C]: in function 'pcall'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>

**Please help me if you know how to fix this. Thank you every much.**

**Comment by Tieske** [comment]
is this a new Kong installation?

if so, please execute `kong migrations reset` to clear the database schema, followed by `kong migrations up` to initialize the database schema. Once that succeeds you should be able to run `kong start`

**Comment by Zeous9** [comment]
Thanks a lot, but the terminal shows 'Enter PEM pass phrase:' when i execute kong start --vv, and i know nothing about PEM pass.

**Comment by Zeous9** [comment]
nginx-kong.conf :
 listen 0.0.0.0:8443 ssl;
    ssl_certificate /usr/local/kong/ssl/kong-default.crt;
    ssl_certificate_key /usr/local/kong/ssl/kong-default.key;

and  i find the kong-default.key under /usr/local/kong/ssl
maybe the key file incorrect?
