### ISSUE TITLE
Is kong only for API security?

### ISSUE THREAD

**Issue by ldeveloperl1985** [Mashape/kong#2754]
Hello,
Is kong only for API security?

https://github.com/pingidentity/mod_auth_openidc
mod_auth_openidc allows to secure the folder using Apache config means we can authenticate API as well as folder also.

Thanks

**Comment by Tieske** [comment]
Please respect the support channels. This question belongs either in the email list or in the gitter channel. The github issue tracker is reserved for actual bugs and issues with the product.
