### ISSUE TITLE
two domains with different upstream

### ISSUE THREAD

**Issue by xxwade** [Mashape/kong#2755]
There are two domains in a server, for example www.a.com, www.b.com
if visit www.a.com, I hope it can forward baidu.com, and visit www.b.com, I hope it can forward qq.com

how can I configure

**Comment by salazar** [comment]
Please visit https://getkong.org to learn more about Kong; in the meanwhile, you might want to consider uginx Nginx for that -- see, for instance, [this](https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-server-blocks-virtual-hosts-on-ubuntu-14-04-lts) and [this](https://www.digitalocean.com/community/tutorials/understanding-nginx-http-proxying-load-balancing-buffering-and-caching).
