### ISSUE TITLE
OAuth2 client storage rationale?

### ISSUE THREAD

**Issue by Vermeille** [Mashape/kong#2763]
Hello,

This is not an issue but a question. If I'm correct, the way the plugin works now is by creating consumers, then creating an Application for each Consumer.

Given that you usually  have more Consumers than you have Applications, it creates a lot of duplication, and make Application management a pain, if you need to change the secret or the redirect_api and consumes a lot of storage.

What am I missing? What's the rationale behind this design decision?

Many thanks!

**Comment by hishamhm** [comment]
> This is not an issue but a question. 

Hi! Thank you for reaching out, but as per the [CONTRIBUTING.md](https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#community-edition) document, it is best to keep this kind of discussions out of the issues list. 

It would probably be best to send this question to the [Google Group](https://groups.google.com/forum/#!forum/konglayer), where the engineers who are knowledgeable on the design will be able to provide some insight. Thanks!
