### ISSUE TITLE
Build error: Failed compiling object src/auxiliar.o

### ISSUE THREAD

**Issue by gumho** [Mashape/kong#2772]
### Summary

Followed the instructions on https://getkong.org/install/source/ to install Kong from source. Ran into failure when install kong via luarocks:

```
kong 0.10.3-0 depends on luasocket == 2.0.2 (3.0rc1-2 installed)
Installing https://luarocks.org/luasocket-2.0.2-6.rockspec
gcc -O2 -fPIC -I/home/centos/ayasdi/openresty/luajit/include/luajit-2.1/ -c src/buffer.c -o src/buffer.o -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
gcc -O2 -fPIC -I/home/centos/ayasdi/openresty/luajit/include/luajit-2.1/ -c src/auxiliar.c -o src/auxiliar.o -DLUASOCKET_DEBUG -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
In file included from src/auxiliar.c:10:
src/auxiliar.h:38: error: expected declaration specifiers or ‘...’ before ‘luaL_reg’
src/auxiliar.c:27: error: expected declaration specifiers or ‘...’ before ‘luaL_reg’
src/auxiliar.c: In function ‘auxiliar_newclass’:
src/auxiliar.c:38: error: ‘func’ undeclared (first use in this function)
src/auxiliar.c:38: error: (Each undeclared identifier is reported only once
src/auxiliar.c:38: error: for each function it appears in.)

Error: Failed installing dependency: https://luarocks.org/luasocket-2.0.2-6.rockspec - Build error: Failed compiling object src/auxiliar.o
```

### Steps To Reproduce

Used the following versions:

http://openresty.org/download/openresty-1.11.2.4.tar.gz
http://www.openssl.org/source/openssl-1.0.2f.tar.gz
http://luarocks.github.io/luarocks/releases/luarocks-2.4.2.tar.gz
https://releases.hashicorp.com/serf/0.7.0/serf_0.7.0_linux_amd64.zip

Operating System:
CentOS 6.8

Full kong install log:
https://pastebin.com/J1PgEF8d

**Comment by hishamhm** [comment]
This could be an incompatibility between Lua version and its header files.
Do you have Lua installed in your machine? (and specifically, `lua-devel`) If so, what version?

**Comment by gumho** [comment]
Hi @hishamhm, thanks for your response. I do not have lua-devel installed on my machine, however, I was under the impression that I would not need it as I have Lua installed via Openresty.  

https://pastebin.com/Wqi0ipXR

By header files I assume you mean these?

```
/home/centos/ayasdi/openresty/luajit/include/luajit-2.1/luajit.h
/home/centos/ayasdi/openresty/luajit/include/luajit-2.1/lua.hpp
/home/centos/ayasdi/openresty/luajit/include/luajit-2.1/luaconf.h
/home/centos/ayasdi/openresty/luajit/include/luajit-2.1/lauxlib.h
/home/centos/ayasdi/openresty/luajit/include/luajit-2.1/lua.h
/home/centos/ayasdi/openresty/luajit/include/luajit-2.1/lualib.h
```

What would be the best way to investigate the issue if the problem is indeed an incompatibility between Lua and the header files?

**Comment by thibaultcha** [comment]
@gumho If you want to use OpenResty 1.11.2.4, you will need to bump LuaSocket to `3.0rc1`. That is because OpenResty 1.11.2.3 bumped its embedded LuaJIT version by quite a bit (all additions between Nov 2016 and May 2017). One of those changes from Mike Pall is the removal of outdated Lua 5.0 compatibility artifacts. The related commit for this particular one is: https://github.com/openresty/luajit2/commit/dc320ca70f2c5bb3977b82853bcee6dad2523d01

Kong 0.11.0rc2 has a bumped LuaSocket dependency already to circumvent this issue.

**Comment by gumho** [comment]
@thibaultcha Thank you for this information, that makes so much sense now!

**Comment by hbasafa** [comment]
@hishamhm How can we install ```lua-devel``` in openwrt?
