### ISSUE TITLE
key-auth plugin schema returned by kong admin api is not correct

### ISSUE THREAD

**Issue by shazha** [Mashape/kong#2775]
### Summary

The schema for key-auth plugin returned by kong admin api is:

```
{
    "fields": {
        "hide_credentials": {
            "type": "boolean",
            "default": false
        },
        "anonymous": {
            "type": "string",
            "func": "function",
            "default": ""
        },
        "key_names": {
            "type": "array",
            "required": true,
            "func": "function",
            "default": "function"
        },
        "key_in_body": {
            "type": "boolean",
            "default": false
        }
    },
    "no_consumer": true
}
```
The `default` value for `key_names` field is not correct. I think it should be `{ "apikey" }` rather than `function`

### Steps To Reproduce

access `http://<kong_host>:8001/plugins/schema/key-auth`

### Additional Details & Logs

- Kong version (0.10.1)

**Comment by shashiranjan84** [comment]
@shazha no, its correct type, default is evaluated through a function,

https://github.com/Mashape/kong/blob/master/kong/plugins/key-auth/schema.lua#L39.
