### ISSUE TITLE
statsd_logger instance counter method throws no method error

### ISSUE THREAD

**Issue by argentum47** [Mashape/kong#2782]
### Summary
Previously with kong 0.10.1, we used to have a wrapper to use the statsd_logger to push custom metrics to datadog. With kong 0.11(rc2) the behaviour breaks.

### Steps To Reproduce
```
local statsd_logger = require "kong.plugins.datadog.statsd_logger"
local _M = {}

function _M.ddcount(config, metric_key, value)
  local ddlogger, err = statsd_logger:new({ host = config.datadog_host, port = config.datadog_port })

  if err then
    logger.error("Auth", "Error connecting to datadog agent"..err)
    return
  end

  if not value then
    value = 1
  end

  if not ddlogger.counter then
    logger.error("Failed to push metric due to unexpected reason, counter method is not defined on datadog logger. metric_key "..metric_key)
    return
  end

  ddlogger:counter("gojek.kong."..metric_key, value, 1)
  ddlogger:close_socket()
end

return _M
```

add this to rockspec file
```
["kong.plugins.kong-plugins.utils"]  = "shared/utils.lua"
```

Use it in another plugins handler or somewhere

```
local Auth = require("kong.plugins.base_plugin"):extend()
local utils  = require "kong.plugins.kong-plugins.utils"
function GojekAuth:access(conf)
  Auth.super.access(self)

  local auth_header = ""

  if headers["Authorization"] then
    utils.ddcount(conf, "customer_auth.auth_attempts.count", 1)

    ngx.log(ngx.DEBUG, "Auth(): Invoking Customer Auth")
    auth_header = headers["Authorization"]

    local token = utils.get_token_from_header(headers["Authorization"]) #gets bearer token
    ngx.log(ngx.INFO, "Token "..token)
  end
end
```

and include the later plugin in an api and send a curl request with `-H 'Authorization: Bearer 12345`

### Expected behaviour
To increment the datadog metric and no error in error log

### Got Behaviour

In error log I get `Failed to push metric due to unexpected reason, counter method is not defined on datadog logger. metric_key customer_auth.auth_attempts.count`

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by p0pr0ck5** [comment]
Possibly related to https://github.com/Mashape/kong/pull/2400 @shashiranjan84?

**Comment by shashiranjan84** [comment]
@p0pr0ck5 @argentum47 yes, code has been refactored to support new features in 0.11,

use https://github.com/Mashape/kong/blob/feat/configurable-datadog/kong/plugins/datadog/handler.lua#L62 as an example to send a `counter` metric.

Also any code written in a plugin module is solely for that plugin and subjected to change and should be avoided to be used as an API for new plugin development.

**Comment by argentum47** [comment]
Thanks
