### ISSUE TITLE
Documentation page should warn that kong/templates must match your kong release

### ISSUE THREAD

**Issue by frank-carnovale** [Mashape/kong#2783]
Documentation suggestion:

This 'latest' online Docs page:
https://getkong.org/docs/0.10.x/configuration/#custom-nginx-configuration

Advised me to collect lua templates from this resource:
https://github.com/Mashape/kong/tree/master/kong/templates. 

But the templates in that 'master' branch lead to a bug "no resolver defined to resolve kong_upstreamnil".   The templates appear to be out-of-date with the "lastest" kong (as retrieved from docker's kong:latest).

This was a very hard-to-trace error.  I suggest, the documentation should have a note warning you to make sure you copy the version of templates tagged with the release you are running.

**Comment by p0pr0ck5** [comment]
Hi @frank-carnovale, thanks for the report! Do note that the docs for getkong.org are open source and available here: github.com/mashape/getkong.org. Feel free to open an issue (or better, a PR!) if you notice a discrepancy. Thanks! :)

**Comment by hishamhm** [comment]
I was wondering if we should ship the example templates (and default `kong.conf`, which I don't think the Homebrew installer is installing) and install those locally in an `examples/` directory or something like that, and then have the documentation point to a local path in the user's box.

**Comment by thibaultcha** [comment]
Maybe something more or less like a set of default files?
```
/etc
├── kong.conf
├── kong.conf.default
├── nginx-conf.template
├── nginx-conf.template.default
├── nginx-kong-conf.template
└── nginx-kong-conf.template.default
```

**Comment by hishamhm** [comment]
That works! And I like the `.template` filename extension too

**Comment by hishamhm** [comment]
(Also, all those files would go under `/etc/kong` rather than plain `/etc`, right?)

**Comment by thibaultcha** [comment]
Yes, my mistake
