### ISSUE TITLE
0.11.0 Preserve host fails when using multiple doimains

### ISSUE THREAD

**Issue by thochra** [Mashape/kong#2825]
### Summary

Hello, last friday we found the preserveHost option messed up when using mutliple domains (on 0.11.0rc2).
I quickly tested on 0.11.0 and it's the same.

Let's say we have api.domain1.com and api.domain2.com.
When using only domain1 everything works correctly.

At the time we start doing some requests on domain2, we may have randomly `Host` header  messup.
Sometime requests done with domain2 will have `Host: api.domain1.com` sometime they will have the right header `Host: api.domain2.com`.
The same could happen with request coming from domain1.

The good news is the header `X-Forwarded-Host` seems always correct.
So for the workarround we reused this header to update the `Host` before sending Kong's outgoing requests to other services (we have an HAproxy instance on each kong instance to manage some balancing strategies).

### Steps To Reproduce

1. Setup a kong instance using JWT credentials to access an API
2. Setup an app which will log when header `host` and `x-forwarded-host` differs
3. Start sending queries with api.domain1.com
4. Start sending queries with api.domain2.com

### Additional Details & Logs

- Kong version 0.11.0rc2 and 0.11.0
- Operating System Docker kong container v0.11.0 (and v0.10.3 with a manual update to 0.11.0rc2)

**Comment by thibaultcha** [comment]
Hello,

I just gave this a try with 0.11.0 and the following *minimal reproducible* example:
```json
        {
            "created_at": 1503300445000,
            "hosts": [
                "api.domain1.com",
                "api.domain2.com"
            ],
            "http_if_terminated": false,
            "https_only": false,
            "id": "aefaa44f-2fc4-433c-add9-6a5d9542c149",
            "name": "test",
            "preserve_host": true,
            "retries": 5,
            "strip_uri": true,
            "upstream_connect_timeout": 60000,
            "upstream_read_timeout": 60000,
            "upstream_send_timeout": 60000,
            "upstream_url": "http://httpbin.org"
        }
```

And the following 2 requests made with httpie:
```
$ http :8000/get Host:api.domain1.com
$ http :8000/get Host:api.domain2.com
```

Both requests seem to send `Host: api.domain1.com` and `Host: api.domain2.com` respectively over the wire according to tcpdump.

> Hello, last friday we found the preserveHost option messed up when using mutliple domains (on 0.11.0rc2).
> I quickly tested on 0.11.0 and it's the same.

Fortunately, this is exactly why we have RCs! Unfortunately, if a bug is found in an RC but never reported to us, it will obviously not get fixed in the final release :)

**Comment by thochra** [comment]
Sorry I was unprecise for the kong configuration.
I will provide you a more detailed configuration soon (have production issue to deal with right now).
About the RC we found it 2-3 days after your release :/

**Comment by thochra** [comment]
So for API configuration we use something more like this:
```json
{
    "name": "sample",
    "uris": [ "/v1/sample" ],
    "methods": [ "GET" ],
    "upstream_url": "http://127.0.0.1:8070/",
    "strip_uri": true,
    "preserve_host": true,
    "retries": 1,
    "upstream_connect_timeout": 6000,
    "upstream_send_timeout": 6000,
    "upstream_read_timeout": 6000,
    "https_only": false,
    "http_if_terminated": true
}
```

To reproduce the bug you need to loop on the API after Kong have been restarted.
As I explained in your upstream app you can log the `host` and `x-forwarded-host` headers for each request or filter it to log only if the two differs.

So far no problem should have occured.
Now, if you try some request from the second domain, you should sometime see the request loop from first domain will have `host: api.domain2.com` and `x-forwarded-for: api.domain1.com`.

We have a LB before kong, but I guess modifying you `hosts` to point to kong instance will be enough.
Our requests are done like that:
* call http://api.domain2.com/v1/sample
* loadbalancer haproxy does forward reqs to Kong keeping the Host header and on 172.20.1.1:8000
* Kong does his logic
* the app received the (eventually) the wrong Host

**Comment by thibaultcha** [comment]
@thochra Thanks for the additional details! I was indeed able to reproduce the behavior to once I configured an API **without** `hosts` (Hence the importance of providing us with the full configuration of your nodes in opened issues :wink:).

I wrote a fix available at #2832, if you'd like to check it out or maybe even apply the patch and confirm it resolves the issue on your side :)

Thanks!

**Comment by thibaultcha** [comment]
#2832 has been merged - thanks again for the report @thochra!

**Comment by thochra** [comment]
Hi @thibaultcha 
Sorry I had no time to test it. And now as we are using the workaround.
But I trust you ;)
