### ISSUE TITLE
Kong 0.11.0 install lua_system_constants-0.1.2 in mac os failed

### ISSUE THREAD

**Issue by icyxp** [Mashape/kong#2828]
$ luarocks make
Missing dependencies for kong 0.11.0-0:
   lua_system_constants == 0.1.2 (0.1.1-0 installed)
   lua_pack == 1.0.5 (1.0.4-0 installed)
   lua-resty-dns-client == 0.6.0 (0.4.2-1 installed)
   lua-resty-mediador == 0.1.2 (not installed)

kong 0.11.0-0 depends on lua_system_constants == 0.1.2 (0.1.1-0 installed)
Installing https://luarocks.org/lua_system_constants-0.1.2-0.rockspec
Cloning into 'lua-system-constants'...
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 0), reused 7 (delta 0), pack-reused 0
Receiving objects: 100% (11/11), done.
Checking connectivity... done.
Note: checking out 'b25fa47653f5657e24c960e0121eb818285026c0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

package = "kong"
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -c -O2 -fPIC -fPIC -I/server/openresty/luajit/include/luajit-2.1 lua_system_constants.c -o lua_system_constants.o
lua_system_constants.c:13:10: warning: 'luaL_newlib' macro redefined [-Wmacro-redefined]
`#` define luaL_newlib(L,l) (lua_newtable(L), luaL_register(L,NULL,l))
         
/server/openresty/luajit/include/luajit-2.1/lauxlib.h:123:9: note: previous definition is here
`#` define luaL_newlib(L, l)       (luaL_newlibtable(L, l), luaL_setfuncs(L, l, 0))
        
1 warning generated.
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load -L/server/openresty/luajit/lib -o lua_system_constants.so lua_system_constants.o
/server/openresty/luajit/bin/luajit test/lua_system_constants_test.lua
/server/openresty/luajit/bin/luajit: test/lua_system_constants_test.lua:4: attempt to call field 'O_RDONLY' (a nil value)
stack traceback:
	test/lua_system_constants_test.lua:4: in main chunk
	[C]: at 0x0104dc3df0
make: *** [lua_system_constants.so] Error 1

Error: Failed installing dependency: https://luarocks.org/lua_system_constants-0.1.2-0.rockspec - Build error: Failed building.

**Comment by p0pr0ck5** [comment]
@icyxp just curious, what happens when you try to install `lua_system_constants 0.1.1`? its not compatible with Kong 0.11, just curious what your system behavior is.

**Comment by icyxp** [comment]
install lua_system_constants 0.1.1 is ok，no error， just not compatible with O_RDONLY，I guess if you can change O_RDONLY to 00 can work。@p0pr0ck5

**Comment by icyxp** [comment]
I have solved this problem because the compiled file was not put into the lua dependency directory and then run the unit test failed
