### ISSUE TITLE
After upgrading my tests are failing

### ISSUE THREAD

**Issue by mwaaas** [Mashape/kong#2830]
### Summary

After an upgrade then running my test they are failing.

### Steps To Reproduce

1.Upgrade kong (image docker) to 0.11 
2. Run test
3. They will fail with the following error message
Error → /usr/local/openresty/lualib/ngx/semaphore.lua @ 118
suite /usr/src/app/kong/plugins/api_authorization/test.lua
/usr/local/openresty/lualib/ngx/semaphore.lua:118: attempt to yield across C-call boundary

### Additional Details & Logs

- Kong version (`0.11.0`)
- Using the official docker iage

**Comment by hnq90** [comment]
My integration tests are failed too. My custom plugin provides some API Endpoint but when I run tests, seem Kong didn't recognize it. Although it's still available when I run Kong without testing mode.

**Comment by p0pr0ck5** [comment]
@mwaaas without seeing your test code this is impossible for us to tell. Possibly it comes from behavior changes in `aa11ecaa94c241e6e82b31ac6f1080b05a902573`. You may consider posting more details to the mailing list to see if anyone else has had similar experiences.

**Comment by mwaaas** [comment]
I changed my spec helper to match the one on master branch and it started working. 

Fixed it but didn't now the root cause of it.
