### ISSUE TITLE
Small mistake in doc: dao:find_by_keys doesn't exist

### ISSUE THREAD

**Issue by GuillaumeSmaha** [Mashape/kong#2831]
### Summary

In the page https://getkong.org/docs/0.11.x/plugin-development/entities-cache/
The following example use the function `find_by_keys` which doesn't exist anymore (according to the doc page: https://getkong.org/docs/0.11.x/lua-reference/modules/kong.dao/)

```lua
-- access.lua
local singletons = require "kong.singletons"

local function load_entity_key(api_key)
  -- IMPORTANT: the callback is executed inside a lock, hence we cannot terminate
  -- a request here, we MUST always return.
  local apikeys, err = dao.apikeys:find_by_keys({key = api_key}) -- Lookup in the datastore
  if err then
    error(err) -- caught by kong.cache and logged
  end

  if not apikeys then
    return nil -- nothing was found (cached for `neg_ttl`)
  end

  -- assuming the key was unique, we always only have 1 value...
  return apikeys[1] -- cache the credential (cached for `ttl`)
end
```

**Comment by p0pr0ck5** [comment]
Hey @GuillaumeSmaha, thanks for the report! The docs are available open source here: https://github.com/mashape/getkong.org. Would you consider opening a PR to fix this? Thanks!

**Comment by GuillaumeSmaha** [comment]
@p0pr0ck5 Thakns, I created a PR: https://github.com/Mashape/getkong.org/pull/499
