### ISSUE TITLE
Method Not Allowed when trying to fetch upstream's active targets

### ISSUE THREAD

**Issue by cfajardo** [Mashape/kong#2840]
### Summary

When i want to fetch upstream's active targets i have a 400 response METHOD NOT ALLOWED

[https://getkong.org/docs/0.11.x/admin-api/#list-active-targets](https://getkong.org/docs/0.11.x/admin-api/#list-active-targets)

### Steps To Reproduce

1. `curl http://kong:8001/upstreams/{id}/targets/active -X GET`

### Additional Details & Logs

- Kong version (`0.11`)
- Operating System Linux
- If i add a `/` like this : `curl http://kong:8001/upstreams/{id}/targets/active/ -X GET` everything is ok, but not compliant with the documentation.
- An hotfix has been merged before in this pull request #2307
- The issue has been reintroduce by this pull request #2252

**Comment by lamielle** [comment]
I too am seeing this behavior in Kong 0.11.  I have also implemented the workaround of appending a trailing /.  Thanks for filing this and for the workaround suggestion @cfajardo!
