### ISSUE TITLE
Kong 301 Moved Permanently

### ISSUE THREAD

**Issue by qingziguanjun** [Mashape/kong#2853]
The Kong version is kong:0.10.2 and the database is postgres:9.4.
when i paste the proxy url in chrome ,the kong will move Moved Permanently to the origin source url,this will dispose my url.

First,I add a proxy url:

curl -i -X POST 
--url http://localhost:8001/apis/ 
--data 'name=check-image' 
--data 'uris=/checkImage' 
--data 'hosts=kong.d.internetware.cn' 
--data 'upstream_url=http://api.internetware.cn/social5'

then i input call url in firefox: 
kong.d.internetware.cn/checkImage?iw-cmd=110000_CW0061&iw-apikey=123

but the url will finally redirect to "http://api.internetware.cn/social5/?iw-cmd=110000_CW0061&iw-apikey=123" with 301 Moved Permanently

Is there anything wrong? In /usr/local/kong/logs/access.log  I didn't find access log to the api, how could it possible?  Does my origin url have problem?

**Comment by thefosk** [comment]
I believe this is some configuration on your side.

**Comment by andersenq** [comment]
@thefosk 
I also got this issue in the whole new KONG vagrant installation. I got a **HTTP 301** instead of the expected **reverse proxy**, please advise, thanks...


**the curl request.**
```
✔ ~/kong-test/kong-vagrant [master|✔]
18:29 $ curl -i -X POST --url http://localhost:8001/apis/ --data 'name=ktv' --data 'upstream_url=http://172.17.35.184:5603/api/v1' --data 'uris=/my-ktv'
```

**response seems ok.**
```
HTTP/1.1 201 Created
Date: Mon, 18 Dec 2017 10:31:19 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.11.2

{"created_at":1513593079211,"strip_uri":true,"id":"02acc076-c2bb-469a-b2eb-0aaebe540e2f","name":"ktv","http_if_terminated":false,"preserve_host":false,"upstream_url":"http:\/\/172.17.35.184:5603\/api\/v1","uris":["\/my-ktv"],"upstream_connect_timeout":60000,"upstream_send_timeout":60000,"upstream_read_timeout":60000,"retries":5,"https_only":false}
```

**then use firefox network monitor can see the HTTP 301 returned.**

![2017-12-18 7 08 49](https://user-images.githubusercontent.com/34337355/34103263-1e121214-e427-11e7-8e48-24bceca98555.png)

**Comment by andersenq** [comment]
@thefosk 

I found the root cause is the **slash** in my request url,

a) no redirect 
```
http://172.17.35.184:9531/my-ktv/songs/
``` 
b) got redirect
```
http://172.17.35.184:9531/my-ktv/songs/
``` 

still confused, why not kong deal with the '301 redirect' instead of pass it to consumer?

**Comment by thibaultcha** [comment]
This is by design. Kong is a transparent reverse proxy, and its purpose is to faithfully send back the response sent by a remote server. It is the client’s responsibility to follow (or not) a redirect from the upstream.

**Comment by andersenq** [comment]
@thibaultcha 
Thanks.   seems I need to find away to implement **ProxyPassReverse** in KONG or OpenResty.
