### ISSUE TITLE
SSL Verifed connection to PostgreSQL\RDS

### ISSUE THREAD

**Issue by matangiz** [Mashape/kong#2856]
### Summary

Hi,
I am trying to connect Kong (docker based) to PostgreSQL database over ssl connection with verification.
The Kong on version is 0.11 - but I failed doing it few weeks ago with Kong 0.9.9 and preferred waiting for the upgrade before attempting to analyze something that might be deprecated.
when enabling the ssl connection there is no errors - the problem began when I configure Kong to verify the connection with the PG_SSL_VERIFY flag.
I failed getting this to work with local PostgreSQL docker that support ssl connection - and also over Amazon RDS.
I attached Kong debug logs - and other than that I tried placing the CA certificate in
/etc/ssl/certs/ and got the same error.

one thing that I can mention is when I configured the CA certificate file path while there is no such file - I do get an error. even when the verify flag is off.

### Steps To Reproduce

1. run postgres with SSL secured - with a given\generated matched CA certificate.
2. Configure Kong to work with postgres over ssl connection as written in Kong official documentation - set relevant environment variables
```
        KONG_PG_SSL: 'on'
        KONG_PG_SSL_VERIFY: 'on'
        KONG_LUA_SSL_TRUSTED_CERTIFICATE: '/path/of/db/ca/cert/server.crt'
```
3. pass certificate as pem - using docker volume (can build new Docker image and copy the file inside)
4. run docker container from https://github.com/Mashape/docker-kong

### Additional Details & Logs

Kong version (0.11.0)
Kong log level set to DEBUG by using the log level environment variable 
PostgreSQL version 9.5 (locally and in Amazon RDS)

```
 2017/08/23 11:36:30 [verbose] Kong: 0.11.0
 2017/08/23 11:36:30 [debug] ngx_lua: 10008
 2017/08/23 11:36:30 [debug] nginx: 1011002
 2017/08/23 11:36:30 [debug] Lua: LuaJIT 2.1.0-beta2
 2017/08/23 11:36:30 [verbose] reading config file at /etc/kong/kong.conf
 2017/08/23 11:36:30 [debug] KONG_PREFIX ENV found with "/usr/local/kong"
 2017/08/23 11:36:30 [debug] KONG_PG_USER ENV found with "kong"
 2017/08/23 11:36:30 [debug] KONG_PG_HOST ENV found with "postgres-int"
 2017/08/23 11:36:30 [debug] KONG_DB_UPDATE_FREQUENCY ENV found with "1"
 2017/08/23 11:36:30 [debug] KONG_PG_SSL_VERIFY ENV found with "on"
 2017/08/23 11:36:30 [debug] KONG_PG_SSL ENV found with "on"
 2017/08/23 11:36:30 [debug] KONG_LUA_SSL_TRUSTED_CERTIFICATE ENV found with "/usr/local/kong/certs/server.crt"
 2017/08/23 11:36:30 [debug] KONG_NGINX_DAEMON ENV found with "off"
 2017/08/23 11:36:30 [debug] KONG_LOG_LEVEL ENV found with "debug"
 2017/08/23 11:36:30 [debug] KONG_PG_PORT ENV found with "5432"
 2017/08/23 11:36:30 [debug] KONG_PG_PASSWORD ENV found with "******"
 2017/08/23 11:36:30 [debug] admin_access_log = "logs/admin_access.log"
 2017/08/23 11:36:30 [debug] admin_error_log = "logs/error.log"
 2017/08/23 11:36:30 [debug] admin_http2 = false
 2017/08/23 11:36:30 [debug] admin_listen = "0.0.0.0:8001"
 2017/08/23 11:36:30 [debug] admin_listen_ssl = "0.0.0.0:8444"
 2017/08/23 11:36:30 [debug] admin_ssl = true
 2017/08/23 11:36:30 [debug] anonymous_reports = true
 2017/08/23 11:36:30 [debug] cassandra_consistency = "ONE"
 2017/08/23 11:36:30 [debug] cassandra_contact_points = {"127.0.0.1"}
 2017/08/23 11:36:30 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
 2017/08/23 11:36:30 [debug] cassandra_keyspace = "kong"
 2017/08/23 11:36:30 [debug] cassandra_lb_policy = "RoundRobin"
 2017/08/23 11:36:30 [debug] cassandra_port = 9042
 2017/08/23 11:36:30 [debug] cassandra_repl_factor = 1
 2017/08/23 11:36:30 [debug] cassandra_repl_strategy = "SimpleStrategy"
 2017/08/23 11:36:30 [debug] cassandra_schema_consensus_timeout = 10000
 2017/08/23 11:36:30 [debug] cassandra_ssl = false
 2017/08/23 11:36:30 [debug] cassandra_ssl_verify = false
 2017/08/23 11:36:30 [debug] cassandra_timeout = 5000
 2017/08/23 11:36:30 [debug] cassandra_username = "kong"
 2017/08/23 11:36:30 [debug] client_body_buffer_size = "8k"
 2017/08/23 11:36:30 [debug] client_max_body_size = "0"
 2017/08/23 11:36:30 [debug] client_ssl = false
 2017/08/23 11:36:30 [debug] custom_plugins = {"jwt_generator","multicors"}
 2017/08/23 11:36:30 [debug] database = "postgres"
 2017/08/23 11:36:30 [debug] db_cache_ttl = 3600
 2017/08/23 11:36:30 [debug] db_update_frequency = 1
 2017/08/23 11:36:30 [debug] db_update_propagation = 0
 2017/08/23 11:36:30 [debug] dns_error_ttl = 1
 2017/08/23 11:36:30 [debug] dns_hostsfile = "/etc/hosts"
 2017/08/23 11:36:30 [debug] dns_no_sync = false
 2017/08/23 11:36:30 [debug] dns_not_found_ttl = 30
 2017/08/23 11:36:30 [debug] dns_order = {"LAST","SRV","A","CNAME"}
 2017/08/23 11:36:30 [debug] dns_resolver = {}
 2017/08/23 11:36:30 [debug] dns_stale_ttl = 4
 2017/08/23 11:36:30 [debug] error_default_type = "application/json"
 2017/08/23 11:36:30 [debug] http2 = false
 2017/08/23 11:36:30 [debug] latency_tokens = true
 2017/08/23 11:36:30 [debug] log_level = "debug"
 2017/08/23 11:36:30 [debug] lua_code_cache = "on"
 2017/08/23 11:36:30 [debug] lua_package_cpath = ""
 2017/08/23 11:36:30 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
 2017/08/23 11:36:30 [debug] lua_socket_pool_size = 30
 2017/08/23 11:36:30 [debug] lua_ssl_trusted_certificate = "/usr/local/kong/certs/server.crt"
 2017/08/23 11:36:30 [debug] lua_ssl_verify_depth = 1
 2017/08/23 11:36:30 [debug] mem_cache_size = "128m"
 2017/08/23 11:36:30 [debug] nginx_daemon = "off"
 2017/08/23 11:36:30 [debug] nginx_optimizations = true
 2017/08/23 11:36:30 [debug] nginx_user = "nobody nobody"
 2017/08/23 11:36:30 [debug] nginx_worker_processes = "auto"
 2017/08/23 11:36:30 [debug] pg_database = "kong"
 2017/08/23 11:36:30 [debug] pg_host = "postgres-int"
 2017/08/23 11:36:30 [debug] pg_password = "******"
 2017/08/23 11:36:30 [debug] pg_port = 5432
 2017/08/23 11:36:30 [Error:
 /usr/local/share/lua/5.1/kong/cmd/start.lua:62: /usr/local/share/lua/5.1/kong/cmd/start.lua:22: [postgres error] could not retrieve current migrations: [postgres error] 18: self signed certificate
 stack traceback:
         [C]: in function 'error'
         /usr/local/share/lua/5.1/kong/cmd/start.lua:62: in function 'cmd_exec'
         /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
         [C]: in function 'xpcall'
         /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
         /usr/local/bin/kong:7: in function 'file_gen'
         init_worker_by_lua:43: in function <init_worker_by_lua:41>
         [C]: in function 'xpcall'
         init_worker_by_lua:50: in function <init_worker_by_lua:48>
 debug] pg_ssl = true
 2017/08/23 11:36:30 [debug] pg_ssl_verify = true
 2017/08/23 11:36:30 [debug] pg_user = "kong"
 2017/08/23 11:36:30 [debug] prefix = "/usr/local/kong"
 2017/08/23 11:36:30 [debug] proxy_access_log = "logs/access.log"
 2017/08/23 11:36:30 [debug] proxy_error_log = "logs/error.log"
 2017/08/23 11:36:30 [debug] proxy_listen = "0.0.0.0:8000"
 2017/08/23 11:36:30 [debug] proxy_listen_ssl = "0.0.0.0:8443"
 2017/08/23 11:36:30 [debug] real_ip_header = "X-Real-IP"
 2017/08/23 11:36:30 [debug] real_ip_recursive = "off"
 2017/08/23 11:36:30 [debug] server_tokens = true
 2017/08/23 11:36:30 [debug] ssl = true
 2017/08/23 11:36:30 [debug] ssl_cipher_suite = "modern"
 2017/08/23 11:36:30 [debug] ssl_ciphers = "******************"
 2017/08/23 11:36:30 [debug] trusted_ips = {}
 2017/08/23 11:36:30 [debug] upstream_keepalive = 60
 2017/08/23 11:36:30 [verbose] prefix in use: /usr/local/kong
 2017/08/23 11:36:31 [verbose] preparing nginx prefix directory at /usr/local/kong
 2017/08/23 11:36:31 [verbose] SSL enabled, no custom certificate set: using default certificate
 2017/08/23 11:36:31 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
 2017/08/23 11:36:31 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
 2017/08/23 11:36:31 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
 2017/08/23 11:36:31 [verbose] running datastore migrations
 2017/08/23 11:36:31 [verbose] could not start Kong, stopping services
 2017/08/23 11:36:31 [verbose] stopped services
```

**Comment by aviben01** [comment]
@thibaultcha , @Tieske was there any flow that was tested with tls verification vs. database?
Cannot use `pg_ssl_verify: true` with rds

**Comment by aviben01** [comment]
@thibaultcha , @Tieske , do you expect to look into this issue soon?

Please see more info investigating issue and workaround found:

We are using `FROM: kong:0.11.0`
Trying to connect to RDS on AWS with `pg_ssl_verify = true`

We could manage to workaround this issue when enforcing pgmoon work with nginx socket type in contexts of `timer`, `access` and `content` (edited `forced_luasocket_phases` table in _kong.dao.db.postgres_)

* Also needed to edit `reachable` method (_kong.dao.db.postgres_) to allow non nginx socket_type: replaced line `pg:keepalive()` into:
```lua
if conn_opts.socket_type == "nginx" then
  pg:keepalive()
else
  pg:disconnect()
end
```

* Without editing `timer` context, I get following error in migrations step of kong start:
_(NGX PHASE print added by me)_

```
2017/09/24 20:27:51 [verbose] preparing nginx prefix directory at /usr/local/kong                                                                               
2017/09/24 20:27:51 [verbose] SSL enabled, no custom certificate set: using default certificate                                                                 
2017/09/24 20:27:51 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt                                                             
2017/09/24 20:27:51 [verbose] Admin SSL enabled, no custom certificate set: using default certificate                                                           
2017/09/24 20:27:51 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt                                                         
2017/09/24 20:27:51 [verbose] running datastore migrations                                                                                                      
2017/09/24 20:27:51 [error] 572#0: *2 [lua] postgres.lua:69: query_opts(): --- NGX PHASE: timer, context: ngx.timer                                             
2017/09/24 20:27:51 [verbose] could not start Kong, stopping services                                                                                           
2017/09/24 20:27:51 [verbose] stopped services                                                                                                                  
Error:                                                                                                                                                          
/usr/local/share/lua/5.1/kong/cmd/start.lua:62: /usr/local/share/lua/5.1/kong/cmd/start.lua:22: [postgres error] could not retrieve current migrations: [postgre
s error] 19: self signed certificate in certificate chain                                                                                                       
stack traceback:                                                                                                                                                
        [C]: in function 'error'                                                                                                                                
        /usr/local/share/lua/5.1/kong/cmd/start.lua:62: in function 'cmd_exec'                                                                                  
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>                                              
        [C]: in function 'xpcall'                                                                                                                               
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>                                              
        /usr/local/bin/kong:7: in function 'file_gen'                                                                                                           
        init_worker_by_lua:43: in function <init_worker_by_lua:41>                                                                                              
        [C]: in function 'xpcall'                                                                                                                               
        init_worker_by_lua:50: in function <init_worker_by_lua:48>                                                                                              
```

Result is that kong is not loaded.

* Without editing `content` context, we get internal server error when trying to reach admin port, with following message:
```
{"db":true,"db_name":"postgres","message":"2: unable to get issuer certificate"}
```

* Without editing `access` context, we get an error when trying to reach mapped api, with following message:
```
2017/09/24 20:59:04 [error] 959#0: *81 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/core/balancer.lua:82: attempt to index local 'upstreams_dict' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/share/lua/5.1/kong/core/balancer.lua: in function 'get_upstream'
        /usr/local/share/lua/5.1/kong/core/balancer.lua:155: in function 'get_balancer'
        /usr/local/share/lua/5.1/kong/core/balancer.lua:274: in function 'execute'
        /usr/local/share/lua/5.1/kong/core/handler.lua:387: in function 'after'
        /usr/local/share/lua/5.1/kong.lua:353: in function 'access'
        access_by_lua(nginx.conf:99):3: in function <access_by_lua(nginx.conf:99):1>, client: 127.0.0.1, server: _, request: "GET /v1/login HTTP/1.1", host: "localhost:8000"
```

It seems like either we are doing something wrong in our configuration or the `ngx.socket.tcp()` does not fit for connecting to the database, and probably all phases should be overridden to use luasocket.
This function is not supported in all lua flows and it seems like you already needed to override it in some of your flows.

Please kindly respond to our findings

**Comment by trianglee** [comment]
Here are simple reproduction instructions for seeing that there is a problem connecting to Postgres with SSL verification, with out-of-the-box Kong (no configuration changes).

The reproduction should be executed on a machine (or a VM) with Docker. Ubuntu 14 is known to work well.
The reproduction steps are deliberately simple, so a review of the scripts can be performed before running them if desired.

1. Clone the reproduction git repo - 
`git clone git@github.com:trianglee/kong-ssl-problem.git`

2. Change into the cloned directory.
`cd kong-ssl-problem`

3. Build and run two Postgres database instances, one without SSL support and another with mandatory SSL support, and initialize both of them with Kong migrations -
`./build-and-run-all.sh`

4. You should now have two running Postgres containers with Kong schemas -
postgres-no-ssl
postgres-with-ssl
(can be verified with "docker ps")

5. Start psql on the Postgres instance without SSL, *with* verifying SSL certificate, and observe that it fails to connect (as it should) -
`./psql-with-ssl.sh postgres-no-ssl postgres-with-ssl/cert.pem`

6. Start psql on the Postgres instance *with* SSL, *with* verifying SSL certificate, and observe that it starts correctly -
`./psql-with-ssl.sh postgres-with-ssl postgres-with-ssl/cert.pem`
(use "\quit" to exit)

7. Start psql on the Postgres instance *with* SSL, *with* verifying SSL certificate, with a *wrong* certificate, and observe that it fails to start (as it should) -
`./psql-with-ssl.sh postgres-with-ssl postgres-with-ssl/cert-wrong.pem`

8. Start Kong on the Postgres instance without SSL, and observe that it correctly starts -
`./kong/run-no-ssl.sh`
(use Ctrl-C to shut Kong down)

9. Start Kong on the Postgres instance with SSL, without verifying SSL certificate, and observe that it correctly starts -
`SSL_VERIFY=false ./kong/run-with-ssl.sh`
(use Ctrl-C to shut Kong down)
 
10. Start Kong on the Postgres instance with SSL, *with* verifying SSL certificate, and observe that it fails to start -
`SSL_VERIFY=true ./kong/run-with-ssl.sh`
The error is -
[postgres error] 18: self signed certificate

Conclusions from the above are that -
a. The Postgres instance with SSL is configured correctly with cert.pem as its public key, and only accepts connections with SSL.
b. Kong successfully connects to this Postgres instance, when NOT verifying SSL certificate.
c. Kong refuses to connect to this Postgres instance, when verifying SSL certificate (using cert.pem).

I hope this demonstrates the problem clearly, and explains why the work-around described by aviben01 is needed.
Thanks!

**Comment by thibaultcha** [comment]
Hi,

Thank you for the report! I just submitted a patch to remedy this issue. Could you apply it anf give it a try?

> We could manage to workaround this issue when enforcing pgmoon work with nginx socket type in contexts of timer, access and content (edited forced_luasocket_phases table in kong.dao.db.postgres)

@aviben01 Thanks for the detailed investigation. However this would be considered very wrong fix because you would now use LuaSocket in the main Nginx event loop (timer and access phases) which would introduce blocking I/O and could have terrible impact on performance.

@trianglee Thank you for providing these replication steps.

Would all of you be willing to give a try to @2908 and let us know of your findings? All of the following components should be tested:

* kong migrations/start (CLI)
* Proxy port (`8000`)
* Admin port (`8001`)

Thank you!

**Comment by thibaultcha** [comment]
> was there any flow that was tested with tls verification vs. database?

@aviben01 No, those tests are (unfortunately) non-existing. We are aware of it. I've taken note of this internally and we'll do our best to upgrade our CI infrastructure to implement such tests!

**Comment by trianglee** [comment]
Thanks @thibaultcha! I can confirm that zero order verification of this fix - works (I can run Kong migrations and Kong itself with Postgres with SSL verification, and access a mapped URL).
I'm sure @matangiz or @aviben01 would follow with more serious verifications.

**Comment by aviben01** [comment]
@thibaultcha , thank you for your suggested solution.
Unfortunately it only resolves the `kong start --run-migrations` case.
Other cases remain the same.
I am aware that using luasocket is not optimal, but nginx tcp socket doesn't work with ssl at all in my environment. 
Is there any other configuration that I should have to enable it other than:
```
pg_ssl = on
pg_ssl_verify = on
lua_ssl_trusted_certificate = /path/to/certificate
```

**Comment by thibaultcha** [comment]
@aviben01 I will get a look. Thanks for giving it a try.

**Comment by trianglee** [comment]
@thibaultcha, @aviben01, I did some more tests on the proposed fix.
It worked correctly with a simple Postgres certificates setup, but didn't work with a more complicated setup with a chain of certificates.

The circumstances were -

If Postgres certificate (cert1) is self-signed, and cert1 is the SSL verification certificate – everything is okay.
If Postgres certificate (cert2) is signed by a self-signed certificate (cert1), and cert1 is the SSL verification certificate – everything is okay.
If Postgres certificate (cert3) is signed by an intermediate certificate (cert2) which is signed by a self-signed certificate (cert1), and cert1+cert2 are the SSL verification certificates (two certificates in a single .pem file) – various errors occur ("internal server error" when trying to add an endpoint, for example).

But, there is a way around this - by setting KONG_LUA_SSL_VERIFY_DEPTH to a larger value (2 is sufficient in the case above) - things again work correctly.

Given the verification depth **must** be set correctly for verification to work (it isn't a nice-to-have setting for "extra security"), it might be a good idea to change the default of KONG_LUA_SSL_VERIFY_DEPTH to be larger (is there a downside to simply always using "10"?).

**Comment by aviben01** [comment]
@trianglee thank you very much! that did the job!
@thibaultcha when can you provide an official build with your PR?

**Comment by thibaultcha** [comment]
@trianglee @aviben01 Great, thanks for testing this! Yes indeed, `lua_ssl_verify_depth` is the setting you have to tweak in cases like this.

> it might be a good idea to change the default of KONG_LUA_SSL_VERIFY_DEPTH to be larger (is there a downside to simply always using "10"?)

Our policy with such Nginx/ngx_lua directives has so far been to use the defaults provided by those modules. If we want to change its defaults, this warrants another discussion that isn't part of the scope of this thread. Whether or not that would be considered safe, I have my doubts, but cannot answer definitively at this time.

We will be merging this patch and including it in our upcoming `0.11.1` release coming in the next couple of weeks. Thanks again!
