### ISSUE TITLE
JWT and Auth0 authentication failure

### ISSUE THREAD

**Issue by Harry97** [Mashape/kong#2863]
So, I've followed the last part of this [tutorial](https://getkong.org/plugins/jwt/#using-the-jwt-plugin-with-auth0) right to finest details and implemented it accordingly, and when I create a post request signed with JWT that was made out of `{
  "alg": "HS256",
  "typ": "JWT"
}`
`{
  "iss": "https://{mycompany'sname}.auth0.com/authorize" //don't worry I did insert my actual company name
}`
and of course signed it with the secret key that I've been given and performing this operation mentioned in the tutorial `curl -i -X POST http://localhost:8001/consumers/{consumer}/jwt \
    -F "algorithm=RS256" \
    -F "rsa_public_key=@./pubkey.pem" \
    -F "key=https://{COMPAYNAME}.auth0.com/" # the `iss` field`

I get an error saying `No credentials found for given \'iss\'` I'm trying to authorize a backend service to talk to another backend service

**Comment by p0pr0ck5** [comment]
@Harry97 you may want to try asking Gitter or the mailing list to see if anyone in the community has any feedback here, as GitHub issues should be reserved for actual bugs with Kong. See https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help. Thanks!

**Comment by Harry97** [comment]
I apologize, this was a problem with my configuration of Auth0 and has nothing to do with Kong and this should be kept for bugs reporting only, sorry for the inconvenience.
