### ISSUE TITLE
Is there a dependency between plugins?

### ISSUE THREAD

**Issue by WALL-E** [Mashape/kong#2865]
For stability and maintainability, only enable a few plugins, other plugins is disable.

Please give me some advice, thanks

**Comment by Tieske** [comment]
So this is unclear? is this a question, a problem, or a bug?

**Comment by WALL-E** [comment]
Question：

Can plugins be enabled separately? 
For example, I only enable Rate-Limiting-Plugin, disable other plugins, will there be any potential problems?

**Comment by hishamhm** [comment]
Yes, they can be enabled and disabled separately. That's the main nice thing about a plugin-based architecture. :)

Also, you may want to try asking Gitter or the mailing list for questions about how to use Kong, as GitHub issues should be reserved for actual bugs. See https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help for more details. Thank you!

**Comment by WALL-E** [comment]
@hishamhm Thank you! I remember
