### ISSUE TITLE
Weirdness in tests

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#287]
This is an interesting problem that I noticed. When running tests locally with `busted -o spec/busted-print.lua --coverage spec/ spec/` two things happen:

* The same tests are executed more than once. Here is my log: https://gist.github.com/thefosk/7fa5c1e92f637810acf2 (for example search for `admin_api_spec.lua`, it appears two times)
* Some tests are not being executed at all, for example `plugins_configurations_routes.lua` (you can see it from my same log).

I noticed the same problem on Travis (for example at https://travis-ci.org/Mashape/kong/builds/65202359).

**Comment by thibaultCha** [comment]
- it runs twice because the right command is `busted -o spec/busted-print.lua --coverage spec/`.
- It doesn't run because it doesn't have the `_spec` suffix.
