### ISSUE TITLE
ginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong.lua:149: [postgres error]

### ISSUE THREAD

**Issue by harryjie** [Mashape/kong#2881]
my kong is start error, the logs is as below, how can i reslove?
kong version: 0.11
postgress version: 9.4
[root@localhost ~]# docker logs b77daeebdb34
prefix directory /usr/local/kong not found, trying to create it
2017/09/13 02:49:04 [warn] postgres database 'kong' is missing migration: (response-transformer) 2016-05-04-160000_resp_trans_schema_changes
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong.lua:149: [postgres error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong.lua:149: in function 'init'
	init_by_lua:3: in main chunk

**Comment by p0pr0ck5** [comment]
Please see the first step at https://getkong.org/docs/0.11.x/getting-started/quickstart/#start-kong. And please read the error message, it details exactly what you need to do.

BTW please do not use GitHub issues for support questions if you have not read the docs. Please also read https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help for better ideas on how and where to ask this sort of question. Thank you!

**Comment by harryjie** [comment]
thanks for your answer.

**Comment by devenfan** [comment]
@harryjie Have you resolved this issue? We've just meet the same issue after interruption of power supply……

**Comment by devenfan** [comment]
Now kong cannot start……
<pre>
2018/04/02 18:22:26 [verbose] Kong: 0.11.0
2018/04/02 18:22:26 [verbose] reading config file at /etc/kong/kong.conf
2018/04/02 18:22:26 [verbose] prefix in use: /usr/local/kong
2018/04/02 18:22:26 [verbose] preparing nginx prefix directory at /usr/local/kong
2018/04/02 18:22:26 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2018/04/02 18:22:26 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2018/04/02 18:22:26 [warn] Unable to set kong env permissions: 
2018/04/02 18:22:26 [warn] cassandra keyspace 'keyspace_kongqa' is missing migration: (response-transformer) 2016-03-10-160000_resp_trans_schema_changes
2018/04/02 18:22:26 [verbose] could not start Kong, stopping services
2018/04/02 18:22:26 [verbose] stopped services
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:62: /usr/local/share/lua/5.1/kong/cmd/start.lua:28: [cassandra error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:62: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'xpcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>

</pre>
