### ISSUE TITLE
OpenWhisk demonstration doc bug

### ISSUE THREAD

**Issue by jonocodes** [Mashape/kong#2886]
Not sure if this is a bug because I dont use Kong or OpenWhisk.
Looking at sample in documentation here:
https://getkong.org/plugins/openwhisk/

The API is created with "hosts=example.com"
then the curl requests are made using -H "Host:hello.com".
Should these values match?

**Comment by shashiranjan84** [comment]
@jonocodes thanks for letting  us know. We will update the doc asap.

**Comment by thibaultcha** [comment]
Fixed!
