### ISSUE TITLE
kong loadbalancing don't take effect 

### ISSUE THREAD

**Issue by wuyachao** [Mashape/kong#2887]
I want to use kong upstreams. But kong loadbalancing don't take effect. I do not know if it is used correctly.

### steps to add upstreams
1. I test some api having different port,such as:
```
request 1: http://aaa.wyc.com:8888/aaa   it's response: server_name:aaa.wyc.com,port:8888
request 2: http://aaa.wyc.com:8889/aaa   it's response: server_name:aaa.wyc.com,port:8889
request 3: http://aaa.wyc.com:8890/aaa   it's response: server_name:aaa.wyc.com,port:8890
...
```

2. add a upstream

```
curl -i -X POST \
  --url http://127.0.0.1:8001/upstreams/ \
  --data 'name=test_v1' \
  --data 'slots=400'
```

3. add target

```
curl -i -X POST \
  --url http://127.0.0.1:8001/upstreams/test_v1/targets \
  --data 'target=aaa.wyc.com:8888' \
  --data 'weight=10'
curl -i -X POST \
  --url http://127.0.0.1:8001/upstreams/test_v1/targets \
  --data 'target=aaa.wyc.com:8889' \
  --data 'weight=10'
curl -i -X POST \
  --url http://127.0.0.1:8001/upstreams/test_v1/targets \
  --data 'target=aaa.wyc.com:8890' \
  --data 'weight=10'
...
```

4. add a api to kong

```
{
    "http_if_terminated": true,
    "id": "d7685fd9-4caa-4f61-9b2c-8cc874ebc4d9",
    "retries": 5,
    "preserve_host": false,
    "created_at": 1496395744000,
    "upstream_connect_timeout": 60000,
    "upstream_url": "http://test_v1/aaa",
    "upstream_read_timeout": 60000,
    "upstream_send_timeout": 60000,
    "https_only": false,
    "strip_uri": true,
    "uris": [
        "/test"
    ],
    "name": "wyc",
    "hosts": {}
}
```

When i did the above steps, I request the api from kong.
```
curl -v "localhost:8000/test"
```
I use the same weight, so I think the api  will take from request 1 to request 4.
but, response is always `server_name:aaa.wyc.com,port:8890`. the post 8888, 8889,8891 is not requested.

### Additional Details & Logs
- kong version : kong/0.10.3

first, I add the upstream as slots=10, when i read the doc, I add the upstream as slots=400.
I reload and restart kong many times. it always return  server_name:aaa.wyc.com,port:8890.

**Comment by Tieske** [comment]
what is returned if you do a GET request on `http://127.0.0.1:8001/upstreams/test_v1/targets/`

**Comment by wuyachao** [comment]
@Tieske T  hi, this is the reponse.
```
{
    "data": [
        {
            "weight": 10,
            "id": "29350d60-3a88-4871-943f-e116e7d8044a",
            "target": "aaa.wyc.com:8888",
            "created_at": 1505288038400,
            "upstream_id": "a4e760ef-705f-4d60-b114-30a0cf479341"
        },
        {
            "weight": 10,
            "id": "3039d31b-452a-4bc9-9eef-1b6ab141dc09",
            "target": "aaa.wyc.com:8889",
            "created_at": 1505288046638,
            "upstream_id": "a4e760ef-705f-4d60-b114-30a0cf479341"
        },
        {
            "weight": 10,
            "id": "274db6bc-260e-41e6-b4ec-8d3dde69a8b2",
            "target": "aaa.wyc.com:8890",
            "created_at": 1505288051398,
            "upstream_id": "a4e760ef-705f-4d60-b114-30a0cf479341"
        },
        {
            "weight": 10,
            "id": "e1668046-aede-4557-9c37-87afe267126d",
            "target": "aaa.wyc.com:8891",
            "created_at": 1505288055262,
            "upstream_id": "a4e760ef-705f-4d60-b114-30a0cf479341"
        }
    ],
    "total": 4
}
```

**Comment by wuyachao** [comment]
I request on `http://localhost:8001/upstreams/test_v1/targets/active`. the reponse is the same.

**Comment by Tieske** [comment]
Note: the `slots` (400 in your upstream) are randomly distributed over the `targets`. You have 4 targets, with equal weights, so each of your targets gets 100 `slots` assigned.

So depending on how often you tried, you could just be unlucky that for example the first 10 slots are all on the target with `port=8890`, and you tried 10 times.

To be sure you should try 400 times, and then each target should get 100 hits. (You may also alter the upstream and change it to 12 slots, and then hit it 12 times)

**Comment by wuyachao** [comment]
@Tieske  hi, According to your suggestion， I update my config with kong.
 1. curl "http://localhost:8001/upstreams" 
```
{
    "data": [
        {
            "orderlist": [
                4,
                2,
                8,
                3,
                10,
                1,
                9,
                6,
                11,
                5,
                12,
                7
            ],
            "slots": 12,
            "id": "b0369cf1-468c-4d08-904b-c2d29f646ece",
            "name": "test_v1",
            "created_at": 1505300553214
        }
    ],
    "total": 1
}
```
2.curl "http://127.0.0.1:8001/upstreams/test_v1/targets"
```
{
    "data": [
        {
            "weight": 10,
            "id": "a0920e7b-2b2e-47d8-948d-ecf5b4b49598",
            "target": "aaa.wyc.com:8888",
            "created_at": 1505300583798,
            "upstream_id": "b0369cf1-468c-4d08-904b-c2d29f646ece"
        },
        {
            "weight": 10,
            "id": "2c9994eb-3f6d-4a1b-9f9e-fa7086e4b83c",
            "target": "aaa.wyc.com:8889",
            "created_at": 1505300588178,
            "upstream_id": "b0369cf1-468c-4d08-904b-c2d29f646ece"
        },
        {
            "weight": 10,
            "id": "6a682f75-dc64-407b-ad0d-4f57ac52cfa2",
            "target": "aaa.wyc.com:8890",
            "created_at": 1505300606328,
            "upstream_id": "b0369cf1-468c-4d08-904b-c2d29f646ece"
        },
        {
            "weight": 10,
            "id": "2a7da195-0ee4-4593-8ff3-c831482d0ba9",
            "target": "aaa.wyc.com:8891",
            "created_at": 1505300610730,
            "upstream_id": "b0369cf1-468c-4d08-904b-c2d29f646ece"
        }
    ],
    "total": 4
}
```
when i update,  I request `localhost:8000/test` about 10 times,but it also return `server_name:aaa.wyc.com,port:8890` .
so I restart kong. 
It return `server_name:aaa.wyc.com,port:8889`.
I request it about 20 times. the return is also same.

**Comment by Tieske** [comment]
can you try to replace the name with an IP address in the targets? So change `aaa.wyc.com:8888` to `1.2.3.4:8888` and see whether that resolves it?

**Comment by wuyachao** [comment]
sorry for my poor english. I request the api:
```
➜  5.1 curl "http://aaa.wyc.com:8889/aaa"
server_name:aaa.wyc.com,port:8889
➜  5.1 curl "http://aaa.wyc.com:8888/aaa"
server_name:aaa.wyc.com,port:8888
➜  5.1 curl "http://aaa.wyc.com:8890/aaa"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://aaa.wyc.com:8891/aaa"
server_name:aaa.wyc.com,port:8891
```

**Comment by wuyachao** [comment]
@Tieske  ok ,i will try it

**Comment by wuyachao** [comment]
@Tieske  other config is the same. i update target with ip:port
```
{
    "data": [
        {
            "weight": 10,
            "id": "abd067cc-fa73-4d01-b653-33dd5d688fe7",
            "target": "127.0.0.1:8888",
            "created_at": 1505301994485,
            "upstream_id": "e1f58129-127a-4503-8e27-b97e1a47a9fc"
        },
        {
            "weight": 10,
            "id": "8cc633c9-315f-4d08-a171-8859390f4451",
            "target": "127.0.0.1:8889",
            "created_at": 1505301998699,
            "upstream_id": "e1f58129-127a-4503-8e27-b97e1a47a9fc"
        },
        {
            "weight": 10,
            "id": "be80d4c8-2f03-49f8-a95e-78e1f2671b47",
            "target": "127.0.0.1:8890",
            "created_at": 1505302003798,
            "upstream_id": "e1f58129-127a-4503-8e27-b97e1a47a9fc"
        },
        {
            "weight": 10,
            "id": "edebbf38-2fb9-430d-8a78-0b172a201896",
            "target": "127.0.0.1:8891",
            "created_at": 1505302008814,
            "upstream_id": "e1f58129-127a-4503-8e27-b97e1a47a9fc"
        }
    ],
    "total": 4
}
```
this is my api reponse:
```
➜  5.1 curl "http://127.0.0.1:8888/aaa" 
/aaa
nil
/aaa
end
200
➜  5.1 curl "http://127.0.0.1:8889/aaa"
server_name:aaa.wyc.com,port:8889
➜  5.1 curl "http://127.0.0.1:8890/aaa"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8891/aaa"
server_name:aaa.wyc.com,port:8891
```
this is my request ：
```
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
➜  5.1 curl "http://127.0.0.1:8000/test"
server_name:aaa.wyc.com,port:8890
```

**Comment by wuyachao** [comment]
the kong is already restart after I update it.

**Comment by wuyachao** [comment]
Who can tell me where it is wrong，please.

**Comment by wuyachao** [comment]
I want to let requests from the same client will always be passed to the same server.  can I set upstreams/target with kong to realization it?

**Comment by Tieske** [comment]
> I want to let requests from the same client will always be passed to the same server. can I set upstreams/target with kong to realization it?

Not yet. Is in the works, but will be at least 0.12 or even later (consistent hashing)

**Comment by wuyachao** [comment]
@Tieske  thank you for your reply.  
I have add three target to a upstream. The kong will always proxy a request to a server such as 127.0.0.1:8889. If 127.0.0.1:8889 is down, kong will proxy the request to another target 127.0.0.1:8890.

It just right for my needs. But It is not the same as the description of the document. https://getkong.org/docs/0.11.x/loadbalancing/ 
the doc say it will ring-balance. Maybe I'm wrong.

**Comment by wuyachao** [comment]
kong version 0.11.0 is ok. so close this issue.

**Comment by simonpie** [comment]
I dont think this should be close.  We have kong 0.11 and yet, kong does not balanced between the two targets I have set :

`
[udesr6t@dvllkg01a ~]$ curl localhost:8001/upstreams/transition-approvisionnement-api-upstream/targets
{"total":2,"data":[{"created_at":1507043934975,"id":"9e379e1a-6a6b-4c56-bcee-693be7b709dc","upstream_id":"a6d2d4ba-2987-4074-9747-184d31bb2f87","target":"dvlldk02b.ile.montreal.qc.ca:3119","weight":100},{"created_at":1507042911912,"id":"2504b904-0234-4379-9bcf-5e6b4039a94c","upstream_id":"a6d2d4ba-2987-4074-9747-184d31bb2f87","target":"dvlldk02a.ile.montreal.qc.ca:3119","weight":100}]}
[udesr6t@dvllkg01a ~]$ curl localhost:8001/upstreams/transition-approvisionnement-api-upstream/
{"created_at":1507042854418,"orderlist":[598,866,973,841,339,88,603,843,555,672,742,726,64,176,309,684,802,435,758,517,52,172,869,950,619,602,409,455,756,772,208,216,635,595,998,16,828,426,145,449,557,129,733,243,13,393,930,46,699,949,5,908,38,30,437,947,317,781,496,954,783,562,768,128,98,453,855,987,353,91,797,231,205,419,490,857,219,260,487,2,778,358,141,881,824,584,488,714,40,966,851,952,501,936,245,202,887,990,799,629,20,302,927,177,815,400,399,940,61,835,773,263,878,461,75,553,601,565,586,360,394,370,423,664,594,416,812,119,894,477,439,348,229,568,850,74,770,199,486,951,315,786,114,429,418,43,379,374,254,448,296,115,137,905,592,956,290,323,873,246,203,518,478,641,493,44,313,451,267,779,748,689,691,413,154,564,259,667,628,679,944,241,462,880,155,775,538,648,984,531,192,22,193,266,832,294,522,919,996,251,639,722,970,433,643,436,805,276,225,289,41,364,232,530,915,899,242,871,42,269,875,215,324,788,79,521,943,625,408,105,979,244,434,948,369,546,389,224,165,552,395,270,576,685,249,911,37,785,445,386,27,803,18,297,764,303,390,138,306,620,676,230,334,902,991,686,682,909,362,113,705,725,861,701,482,925,784,403,615,54,112,328,280,35,678,690,907,574,673,194,747,852,169,162,721,407,331,284,879,669,533,82,515,988,571,675,741,484,168,24,868,831,213,967,765,480,606,103,671,863,884,432,356,211,235,366,494,375,790,378,859,288,757,548,720,392,125,397,743,420,605,221,989,506,191,7,117,127,901,516,528,969,659,373,218,196,746,505,891,500,274,965,258,228,352,102,261,647,363,345,457,401,422,424,848,286,460,519,827,549,980,26,760,311,131,547,197,476,942,665,737,730,734,1000,210,591,466,544,17,346,48,412,116,885,301,142,65,299,693,178,68,273,359,9,272,133,862,917,837,440,888,307,892,474,580,332,766,800,73,762,694,330,634,252,752,575,939,642,443,983,283,147,670,872,789,865,226,525,623,660,918,166,398,175,937,207,719,600,572,604,268,982,57,182,823,931,470,825,959,107,662,953,404,650,271,285,717,787,233,558,415,287,735,529,159,292,223,391,321,217,782,84,780,540,170,122,427,452,12,361,472,809,161,96,895,201,886,596,847,160,771,421,933,99,593,611,731,777,763,502,485,278,651,377,818,627,567,351,85,148,666,636,277,380,624,414,66,468,759,444,81,256,534,227,738,834,385,491,164,849,715,396,255,712,239,755,935,376,240,583,829,681,295,904,512,921,481,732,751,402,67,234,655,23,300,167,372,876,999,55,110,736,509,589,702,563,543,560,489,77,425,677,511,724,238,198,882,808,101,821,632,51,381,810,134,795,890,281,83,923,649,250,503,997,578,910,617,305,126,754,388,963,188,729,707,135,265,275,336,767,71,798,320,833,140,59,761,542,498,459,442,938,683,121,184,842,183,56,492,264,237,839,946,971,139,870,610,405,745,209,889,541,171,993,740,63,189,21,792,335,590,698,204,50,236,916,187,97,631,447,844,11,867,304,262,975,34,291,464,206,898,357,932,14,368,709,573,326,793,995,106,417,186,817,840,561,928,279,33,87,706,10,700,585,456,661,76,874,406,978,49,151,410,539,93,903,688,499,508,653,819,514,156,28,658,124,814,657,308,293,830,520,32,78,621,60,253,450,15,446,438,945,728,458,143,992,365,618,545,53,769,322,150,806,39,95,791,527,753,697,465,163,559,120,523,607,428,858,550,181,31,656,644,19,622,774,668,630,570,248,597,695,856,906,846,86,316,149,8,118,582,475,883,981,179,588,338,70,89,104,976,180,174,507,1,750,310,836,90,577,497,637,569,340,716,343,25,663,158,739,820,58,325,4,247,640,853,146,958,510,708,350,796,674,813,69,633,535,845,314,614,626,411,972,926,29,652,955,430,108,612,744,47,710,212,185,467,469,977,152,922,220,344,537,479,900,504,986,327,431,382,711,384,696,463,816,687,608,924,222,934,329,826,718,157,92,136,860,312,964,298,638,811,441,929,495,483,864,749,383,45,333,822,962,897,960,587,609,654,132,776,838,173,893,877,532,985,387,941,581,974,371,723,646,94,454,680,613,914,968,579,342,80,807,100,111,318,341,727,36,471,913,257,355,599,920,794,713,367,214,854,153,804,801,190,957,109,616,354,473,130,692,566,645,704,554,536,994,195,961,896,3,72,513,282,123,62,349,912,526,144,524,6,319,200,703,556,551,337,347],"id":"a6d2d4ba-2987-4074-9747-184d31bb2f87","name":"transition-approvisionnement-api-upstream","slots":1000}
[udesr6t@dvllkg01a ~]$ `

If I run tcpdump for port 3119 on one kong server and run a few hundred api calls, Only the first target that was added will be called.
