### ISSUE TITLE
[ratelimiting] bug when cassandra counter exceeds the limit

### ISSUE THREAD

**Issue by smanolache** [Mashape/kong#289]
Hello,

For some reason (non-atomicity of the read-modify-write counter operation in cassandra?) the request counter of the ratelimiting_metrics may exceed the configured limit. In this case

    local remaining = conf.limit - current_usage

in `kong/plugins/ratelimiting/access.lua` becomes negative.

The condition

    if remaining == 0 then

is then false and the request is passed through even if the limit is exceeded.

I propose to replace the condition with

    if remaining <= 0 then

**Comment by thibaultCha** [comment]
Yes, the atomicity of the read-write operation is absolutely not guaranteed. I've been wanting to tweak the [consistency](http://docs.datastax.com/en/cassandra/2.0/cassandra/dml/dml_config_consistency_c.html) but even for a single node Kong, single node Cassandra cluster, there is no atomicity, so there is an error rate especially for the `second` period.

I agree with the proposed change, if you want to submit a PR.

**Comment by smanolache** [comment]
Submitted the pull request.

**Comment by sinzone** [comment]
thank you!

**Comment by thibaultCha** [comment]
Yep closing this now
