### ISSUE TITLE
Kong  (0.10.3) gives  502 error when I post a url which include "create"

### ISSUE THREAD

**Issue by hayatitan** [Mashape/kong#2890]
### Summary

Hello,
I created such an api
  {
             "name": "blabla",
              "uris": [
                "/abc/cde"
               ],
            "upstream_url": "http://*.*.*:7777/ttw/cld",
            "strip_uri": true,
            "preserve_host": false,
            "http_if_terminated": true,
            "retries": 5,
            "upstream_read_timeout": 60000,
            "upstream_connect_timeout": 60000,
            "upstream_send_timeout": 60000
}

When I post a url which is like http://*.*.*/abc/cde/create

I got http 502 server hangup error. There are no log in Access,error ant other logs. 

When I post a url which is like http://*.*.*/abc/cde/test

It strips /abc/cde and post http://*.*.*:7777/ttw/cld/test . It Works correctly. 

We were using this api before we upgrade kong to 0.10.3. 

### Steps To Reproduce

1. Create a api like above
2. Post a request which include "create" keyword
3. Get http 502
4.

### Additional Details & Logs

- Kong version (0.10.3)

- Operating System : Red Hat Linux

**Comment by hayatitan** [comment]
In addition to this, I also got tcpdump to see source of http 502 but I could not see any http request in dump file.

**Comment by chenyukang** [comment]
Did the upstream server received request?

**Comment by hayatitan** [comment]
Ok I found the problem It is about LB. Therefore , I am closing the issue...
