### ISSUE TITLE
http to https

### ISSUE THREAD

**Issue by satrox28** [Mashape/kong#2892]
### Summary

Is it possible to route the http request to https url on Kong Nginx.

### Steps To Reproduce

1. I tried to modify the nginx-kong.conf, but its getting overridden during stop/start.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`) - 0.11.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System
Ubuntu 16.04

**Comment by Tieske** [comment]
the issue tracker is for bugs only, please use other fora as described in the template for generic usage questions like this.

for the record: see https://github.com/Mashape/kong/issues/1946
