### ISSUE TITLE
Oauth2 endpoint not found issue

### ISSUE THREAD

**Issue by senthil-nathan** [Mashape/kong#2903]
Hi,

1. I have created an api end point as 

curl -i -X POST \
  --url http://localhost:8001/apis/ \
  --data 'name=auth' \
  --data 'upstream_url=http://mockbin.com/bin/16a657d4-2319-426b-ae24-798ca41e7dd6' \
  --data 'uris=/auth' 

2. Created customer as 

curl -X POST http://localhost:8001/consumers/ \
    --data "username=user123" \
    --data "custom_id=mrx"

3. Created an App, linked the customer to it as 

curl -X POST http://localhost:8001/consumers/4a14d9a8-8c0d-48c7-ae48-b12923a48398/oauth2 \
    --data "name=Test_App" \
    --data "redirect_uri=http://some-domain/endpoint/"

4. Finally, added oauth2 plugin on top of auth end point as 

curl -X POST http://localhost:8001/apis/auth/plugins \
    --data "name=oauth2" \
    --data "config.enable_client_credentials=true" \
    --data "config.scopes=email,phone,address" \
    --data "config.mandatory_scope=true"

When I am try to get a Bearer token using 

curl --silent --insecure -X POST \
--url https://localhost:8443/oauth2/token \
--data "client_secret=9Ss9Epz29SigiZY9692nHWXncXLARDsL" \
--data "client_id=nLEcsmhZiaFNspYps9tOlzBBy8GedeDm" \
--data "grant_type=client_credentials" \
--data "scope=email" 

which returns 404 - {"message":"no API found with those values"} 

I tried with Kong versions 0.10.0 & 0.11.0 both of them returned same messages.  Any help ?

**Comment by senthil-nathan** [comment]
any help @thibaultcha ?

**Comment by DonMartin76** [comment]
As we just discussed on gitter, the problem was that you had specified `uris` and `hosts` (which is though not reflected in what you wrote as `curl` statement above), and that has to be used in the `POST` to the token endpoint as well, in your case

```
curl --silent --insecure -X POST 
--url https://localhost:8443/auth/oauth2/token 
--data "client_secret=9Ss9Epz29SigiZY9692nHWXncXLARDsL" 
--data "client_id=nLEcsmhZiaFNspYps9tOlzBBy8GedeDm" 
--data "grant_type=client_credentials" 
--data "scope=email"
--header "Host: example.com"
```

**Comment by senthil-nathan** [comment]
Thanks @DonMartin76 for helping out, closing the issue

**Comment by senthil-nathan** [comment]
Hey @DonMartin76 should the generic endpoint /oauth2/token work ?

I am trying 
curl --silent --insecure -X POST --url https://localhost:8443/oauth2/token --data "client_secret=9Ss9Epz29SigiZY9692nHWXncXLARDsL" --data "client_id=nLEcsmhZiaFNspYps9tOlzBBy8GedeDm" --data "grant_type=client_credentials" --data "scope=email" --header "Host: example.com"

but the response is {"message":"no API found with those values"}

**Comment by DonMartin76** [comment]
The generic endpoint only works if you have **only** specified `hosts`, and **not** `uris`.

In short:

* Specify `uris` --> You will need to hit `/<your api>/oauth2/token`
* Specify `hosts`--> You will need to specify `Host: <...>` as a header (or really point a DNS entry to Kong, obviously)

They combine, so if you specify both `uris` and `hosts`, you will have to do both. Please note that up until 0.9.x, it was not possible to specify both, but only one of the two. 0.10.x introduced more advanced routing, which in this case is nagging you a little.

**Comment by senthil-nathan** [comment]
Thanks @DonMartin76
