### ISSUE TITLE
It must create consumers before using kong jwt

### ISSUE THREAD

**Issue by wow3065** [Mashape/kong#2909]
I can't sure that it nesscery  to created consumer if you use kong jwt.
Because I want to use dynamic consumer to using kong jwt.
But i have no idea. 

Have any goog idea?

**Comment by DonMartin76** [comment]
Some more details would be a good idea. What are you trying to achieve using the JWT plugin?

For Kong, all authentication plugins will want to resolve to a consumer, whatever that is in your context. Usually it is some kind of web application or whatever consumes your API.

Using a JWT you can add additional data, like an end user identity, which then can be verified as "authentic" by the JWT plugin, if Kong is able to verify that the token is valid (has a valid signature).

The concept of "consumer" tripped me up in the beginning as well - it is usually **not** an end user, but the application to which the user gives access to the API on behalf of himself.

**Comment by wow3065** [comment]
@DonMartin76 
Thank you for answer.

Details:
I have one web application which have many user and some services(restful api). When user have login to the application ,the user will get the jwt token, when user try to access the services which use kong jwt plugin auth, If user have right token,user will get the info which form services, if user have wrong token or not token , will return 401.

I can understand how to manager the token that can auth by jwt plugin for each user.

**Comment by DonMartin76** [comment]
What type of web application do you have? Is it a single page application (runs only in browser)? Or does it have a server side component? All these things are important when deciding on how your "login" is supposed to work, and how the access to your APIs can and should be hidden away from the web application.

You will also need to ask yourself how your application is supposed to obtain the token; this also depends on what type of web application you are using. Are you planning to go with OAuth2 flows, are you doing it differently,...?

**Comment by wow3065** [comment]
@DonMartin76 
Thank you 

Yes ,it's one web application. But it has many apis,such as auth api,customer api and so on.

I want to create token to each user by auth api (HS256). And when user use the application to access the customer apis , I want to use kong controller the auth about accesses.
But if i create the token with the auth api ,I must known the kong consumer's info. So I don't known how to solve.

**Comment by DonMartin76** [comment]
You don't have to have different consumers per end user, it's enough to have one consumer (which is your web application). The information on the end user should be encoded into other JWT claims, from where your APIs can take it out again.

Your issuing instance must be able to verify the identity of the user, and only after that was done, a token for the consumer (your web application, `iss` claim) on behalf of the end user (some other claim) is issued and passed back for use by the web application.

**Comment by wow3065** [comment]
@DonMartin76 
Thank you for much.I will try that.

**Comment by wow3065** [comment]
@DonMartin76 

Thank you for guidance。It worked out。
