### ISSUE TITLE
Kong installation issue

### ISSUE THREAD

**Issue by senthil-nathan** [Mashape/kong#2912]
I am setting dev environment for custom plugin development.

I have a docker env with centos7, lua 5.1.4.5, luarocks 2.4.1 & I have cloned the latest kong https://github.com/Mashape/kong and following the documentation as per https://github.com/Mashape/kong#Development.

when I run make install on the kong folder

[root@accaf5fb6f95 kong]# make install
kong 0.11.0-0 is now installed in /usr/local (license: MIT)

looks like kong is installed in /usr/local but I cannot seem to find any binaries. 

[root@accaf5fb6f95 kong]# ls /usr/local/
bin  etc  games  include  lib  lib64  libexec  openresty  sbin  share  src

[root@accaf5fb6f95 kong]# kong 
bash: kong: command not found 

any advise on how to fix this ?

**Comment by Tieske** [comment]
@senthil-nathan can you please respect the support channels? To keep on top of things we reserved the github issue tracker for bugs. For general support questions, please use the mailing list or Gitter channel.

That said, if you want to install from source, please follow those instructions. The Kong repo does not include the binaries, it won't run with PuC-Rio Lua, but with LuaJIT.

**Comment by lyyoung** [comment]
@senthil-nathan How do you solve this problem?
