### ISSUE TITLE
make tests failing 

### ISSUE THREAD

**Issue by senthil-nathan** [Mashape/kong#2913]
I am setting dev environment for custom plugin development.

I have a docker env with centos7, lua 5.1.4.5, luarocks 2.4.1 & I have cloned the latest kong https://github.com/Mashape/kong and following the documentation as per https://github.com/Mashape/kong#Development.

make dev works fine,
[root@cadd96ec2457 kong]# make dev
kong 0.11.0-0 is now installed in /usr/local (license: MIT)
busted already installed, skipping
luacheck already installed, skipping
lua-llthreads2 already installed, skipping

make test fails,
[root@ac213cf7df7a kong]# make test
●●●●●●●●●●●✱✱✱●●●●●✱✱✱✱✱✱✱●●●●●●✱✱
22 successes / 0 failures / 13 errors / 0 pending : 1.161994 seconds
Error → ./kong/tools/utils.lua @ 11
suite spec/01-unit/002-conf_loader_spec.lua
./kong/tools/utils.lua:11: module 'ffi' not found:No LuaRocks module found for ffi

any advise on how this can be fixed ?

**Comment by Tieske** [comment]
as just remarked in your other issue, please use proper channels. the `ffi` module is LuaJIT specific.

For a quick route, use the Kong-Vagrant box, see the instructions there https://github.com/Mashape/kong-vagrant/blob/master/README.md
