### ISSUE TITLE
lua-resty-iputils v0.2.1 error with ip-restriction plugin

### ISSUE THREAD

**Issue by gideonw** [Mashape/kong#2915]
### Summary

I was setting up my ip-restriction plugins for a new product and ran into an issue when I created and enabled an ip-restriction plugin on an API with a whitelist of ["0.0.0.0/0"].

Related issue: https://github.com/hamishforbes/lua-resty-iputils/issues/11
Rockspec line: https://github.com/Mashape/kong/blob/master/kong-0.11.0-0.rockspec#L26

An update to `lua-resty-iputils => 0.3.0` has fixed this issue for me.

NOTE: I realize that adding a plugin with a whitelist of 0.0.0.0/0 is the same as no plugin at all.

```
*10094715 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/resty/iputils.lua:199: attempt to compare number with nil
stack traceback:
coroutine 0:
    /usr/local/share/lua/5.1/resty/iputils.lua: in function 'binip_in_cidrs'
    ...al/share/lua/5.1/kong/plugins/ip-restriction/handler.lua:78: in function 'access'
    /usr/local/share/lua/5.1/kong.lua:350: in function 'access'
    access_by_lua(nginx-kong.conf:89):2: in function <access_by_lua(nginx-kong.conf:89):1>
```

### Steps To Reproduce

1. Create 'ip-restriction' plugin.
2. Set config.whitelist=["0.0.0.0/0"]
3. Access API, see error.
4. Check logs.

### Additional Details & Logs

- Kong version (`0.11.0`)

**Comment by thibaultcha** [comment]
Thank you for the report. This has been fixed in #2918 and will be in our upcoming 0.11.1 release.
