### ISSUE TITLE
[kong version 0.11.0] kong/core/plugins_iterator.lua:40: attempt to index field 'cache' (a nil value)

### ISSUE THREAD

**Issue by icyxp** [Mashape/kong#2916]
I am upgrading from 0.10.3 to 0.11.0，when i visit http://xxx:8000，Encountered the following questions：

2017/09/29 11:47:30 [notice] 31458#0: signal 17 (SIGCHLD) received
2017/09/29 11:47:30 [notice] 31458#0: signal 17 (SIGCHLD) received
2017/09/29 11:47:30 [notice] 31458#0: signal 17 (SIGCHLD) received
2017/09/29 11:47:30 [notice] 31458#0: signal 17 (SIGCHLD) received
2017/09/29 11:47:30 [notice] 31458#0: unknown process 31522 exited with code 0
2017/09/29 11:47:30 [error] 31458#0: *78 lua entry thread aborted: runtime error: ./kong/core/plugins_iterator.lua:40: attempt to index field 'cache' (a nil value)
stack traceback:
coroutine 0:
	./kong/core/plugins_iterator.lua: in function 'load_plugin_configuration'
	./kong/core/plugins_iterator.lua:90: in function '(for generator)'
	./kong/kong.lua:338: in function 'rewrite'
	rewrite_by_lua(nginx-kong.conf:84):2: in function <rewrite_by_lua(nginx-kong.conf:84):1>, client: 192.168.6.135, server: kong, request: "GET / HTTP/1.1", host: "192.168.6.10:8000"
2017/09/29 11:47:30 [notice] 31458#0: signal 17 (SIGCHLD) received
2017/09/29 11:47:30 [notice] 31458#0: signal 17 (SIGCHLD) received
2017/09/29 11:47:30 [notice] 31458#0: signal 17 (SIGCHLD) received
2017/09/29 11:47:30 [notice] 31458#0: signal 17 (SIGCHLD) received
2017/09/29 11:47:30 [notice] 31458#0: unknown process 31533 exited with code 0

**Comment by icyxp** [comment]
I tracked the following questions，when i set lua_code_cache = off then singletons.cache return nil, when i set lua_code_cache = on , it work ok, so how can i debug?

**Comment by Tieske** [comment]
`lua_code_cache=off` is no longer supported (actually hasn't worked properly since 0.9 or 0.10)

Debugging can be done by doing a reload to activate your changed code.
