### ISSUE TITLE
Kong development environment - tests failing

### ISSUE THREAD

**Issue by senthil-nathan** [Mashape/kong#2930]
I have an issue with setting up Kong development environment. I have set up the dev env in docker (ubuntu), pulled the latest source from https://github.com/Mashape/kong. While trying to run Unit tests using make test the following errors appear - root@6d8209285b4c:confused:kong_dev# make test
●●●●●●●●●●●✱✱✱●●●●●✱✱✱✱✱✱✱●●●●●●✱✱
22 successes / 0 failures / 13 errors / 0 pending : 2.235656 seconds
Error → ./kong/tools/utils.lua @ 33
suite spec/01-unit/002-conf_loader_spec.lua
./kong/tools/utils.lua:33: attempt to index global 'ngx' (a nil value)
stack traceback:
./kong/tools/utils.lua:33: in main chunk

I downloaded the debian kong-community-edition-0.11.0 and extracted it. I believe by default this has all the dependencies, looking at the openresty installation folder, 
root@6d8209285b4cusr/local/openresty/lualib# pwd
/usr/local/openresty/lualib
root@6d8209285b4cusr/local/openresty/lualib# ls -ltr
total 140
-rwxr-xr-x 1 root root 124475 Aug 16 20:15 cjson.so
drwxr-xr-x 8 root root 4096 Oct 3 00:03 resty
drwxr-xr-x 2 root root 4096 Oct 3 00:03 redis
drwxr-xr-x 2 root root 4096 Oct 3 00:03 rds
drwxr-xr-x 3 root root 4096 Oct 3 00:03 ngx

Note : openresty path is set export PATH=/usr/local/openresty/bin:$PATH & I first ran make dev before make test

any help on how to run all tests successfully?

**Comment by Tieske** [comment]
you're running the tests apparently in an enviornment without the `ngx` global. This means you are probably running against the wrong Lua engine (should be against `resty`, the cli for openresty)

If you don't know how to build it, pleas use the `kong-vagrant` repo.

Last but not least: Github issues are meant for bugs, not general support. Please ask questions like this on Gitter or the mailing list.
