### ISSUE TITLE
UPSTREAM - PATCH slots should generate new orderlist

### ISSUE THREAD

**Issue by marceldiass** [Mashape/kong#2933]
### Summary

I'm trying to update the number of slots of an upstream with the PATCH. But It's returning this error  `{"message":"size mismatch between 'slots' and 'orderlist'"}` message.

I believe setting a new slots number should generate a new orderlist with the new size automatically as the PUT method does.

### Steps To Reproduce

Unable to update slots number of an 

1. Create an upstream
```bash
curl -X POST localhost:8001/upstreams --data "slots=15" --data "name=teste.com"
{"created_at":1507215541798,"orderlist":[5,14,10,4,13,15,11,3,9,2,12,1,8,7,6],"id":"91e346c5-4391-4ad5-b46d-24ab4b84f251","name":"teste.com","slots":15}
```
2. Get the upstream by name
```bash
❯ curl localhost:8001/upstreams/teste.com
{"created_at":1507215541798,"orderlist":[8,9,6,11,13,1,5,12,7,3,15,14,2,10,4],"id":"c5d5111a-89aa-4e7f-a3ad-d69bcbcdf27d","name":"teste.com","slots":15}
```
3. Try to update it
```bash
❯ curl -X PATCH localhost:8001/upstreams/teste.com --data "slots=30"
{"message":"size mismatch between 'slots' and 'orderlist'"}
```

### Additional Details & Logs

- Kong version (`$ kong version`)
  - `version 0.11.0`
- Operating System
  - Running the oficial Docker version with postgres DB

**Comment by Tieske** [comment]
as a workaround you can delete and add a new one (by the same name)

The orderlist will be gone in the next release (0.12) anyway.

**Comment by marceldiass** [comment]
Thanks, I will PUT method instead of PATCH for now.
