### ISSUE TITLE
transmission of consumer's infos

### ISSUE THREAD

**Issue by Niradnik** [Mashape/kong#2934]
Hey all thanks for the amazing tool you developed !

I was wondering if there is any way to transmit any info, from the user to the apis. In a practical way I want to give access to read on my api through kong plugins but I want to manage more precise access with the api like this user can delete this. To do so I need to have info on who is the user and thus I would need that kong give to the api some user's info.

**Comment by thefosk** [comment]
Kong already sends a few `X-Consumer-*` headers that you can read from the upstream service.

**Comment by thefosk** [comment]
@Niradnik can you confirm you are receiving those headers? ^
