### ISSUE TITLE
Proposal/feature: List all consumers for key-auth plugin with their keys

### ISSUE THREAD

**Issue by hbagdi** [Mashape/kong#2945]
Getting ACL group or API keys for all consumer from Kong requires multiple REST requests.

 ```
for-each(consumer)
  GET /consumers/{consumer_id}/key-auth
  GET /consumers/{consumer_id}/acl                          
 ```
I would like to propose the following two endpoints:
 ```
GET /plugins/key-auth/consumers
                Returns all consumers with their key(s))
GET /plugins/acl/consumers
                Returns all consumers and the ACL group(s) they belong to
```
The code could be as simple as (no grouping):

```lua
local crud = require "kong.api.crud_helpers"
return {
  ["/plugins/key-auth/consumers"] = {
    GET = function(self, dao_factory)
      crud.paginated_set(self, dao_factory.keyauth_credentials)
    end
  }
}
```

I can't think of a reason why this could be a problem or is a bad idea. 
Please let me know if this is avoided for good reason.

If not, then I can do a PR.

**Comment by p0pr0ck5** [comment]
Hi,

Thank you for the post, but please dot cross post to both GitHub and the mailing list. GitHub is for issues running Kong, not feature requests or community discussion. Since there is a mailing list thread for this topic, I will close this issue. Thank you!
