### ISSUE TITLE
Global plugin configuration

### ISSUE THREAD

**Issue by Nijikokun** [Mashape/kong#295]
I've got a bunch of APIs and it is becoming a hassle to apply individual plugins for each API (they all have the same settings for each one) that I create through Kong Admin API.

Is it possible to have a way to create setup a configuration for a plugin to be globally applied to all of my APIs? The same goes for my consumers, some of them have generic settings on each of my APIs and I end up having to add this to each API and Consumer individually.

I was thinking an easy way to implement this is when enabling a plugin, you could *omit* the **API ID** for a completely **GLOBAL** plugin. If you *omit* the **API ID** but have a **CONSUMER ID** it is global across *all* APIs for that **specific** consumer.

Also, any plugin applied to a specific API or API + Consumer should **override** the global configuration.

**Comment by ahmadnassri** [comment]
> I was thinking an easy way to implement this is when enabling a plugin, you could omit the API ID for a completely GLOBAL plugin. If you omit the API ID but have a CONSUMER ID it is global across all APIs for that specific consumer.

makes sense, would dramatically cut down the setup time for a business with many internal APIs / Microservices.

**Comment by montanaflynn** [comment]
I've been thinking the same thing, originally I thought of a whitelist/blacklist implementation but it also seems intuitive to introduce levels of hierarchy for plugins as you suggest.

**Comment by thefosk** [comment]
The solution to this issue could be similar to https://github.com/Mashape/kong/issues/225, just applied to different entities

**Comment by nicksamps** [comment]
+1

**Comment by thefosk** [comment]
Closed in favor of #505.
