### ISSUE TITLE
ngx_http_rewrite_module support

### ISSUE THREAD

**Issue by denniswebb** [Mashape/kong#2966]
### Summary

Looking to use an nginx `if` statement for detecting if the connections is coming from CloudFlare.  From what I can tell, the version of nginx shipped with the kong container does not support this.  Is there a way to add support?

I'm trying to implement the if statement found here - https://gist.github.com/Doonga/dc91f2c52f17c9931e269966dfcb956d#file-realip-cf-haproxy-conf-L30

### Additional Details & Logs

- Kong version (`$ kong version`) = 0.10.3
- Operating System: Docker image tag kong:0.10.3

**Comment by p0pr0ck5** [comment]
Hi,

If you want to use custom Nginx directives, please have a look at https://getkong.org/docs/0.11.x/configuration/#custom-nginx-configuration-embedding-kong. 

You may also consider writing a custom plugin if you have more complex application logic requirements: https://getkong.org/docs/0.11.x/plugin-development/.

Please also note that Github issues are not the appropriate forum for questions like this. Please consider posting to Gitter or the mailing list as noted here: https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help. Thank you!
