### ISSUE TITLE
Supporting wildcard subdomains 

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/kong#297]
It's extremely common to use wildcards in DNS records, and I've hit a case where I need to have kong match all requests with the host `*.example.org`. Currently kong only works with an exact match of `public_dns` but my DNS record is set to `*.example.org` so I'd like Kong to match  `example.com`, `something.example.com` and even `a.b.c.example.com`.

Relevant nginx doc: http://nginx.org/en/docs/http/server_names.html#wildcard_names

**Comment by thibaultCha** [comment]
Multiple public_dns/paths and regex matching for both will be added later as discussed in #282, #192, and having #15 implemented before would almost be a requirement.

**Comment by montanaflynn** [comment]
I know we discussed some of the functionality prior but both those issues are specifically titled as pertaining to paths and nothing turned up when searching for wildcard or subdomains in the issues. I thought it best to create a separate issue specific to this case which can be found by anyone looking.

**Comment by thibaultCha** [comment]
Nothing wrong with the issue.

**Comment by vmattos** [comment]
This feature is really important for me too! :)

**Comment by sinzone** [comment]
+1

**Comment by lucamaraschi** [comment]
:+1:

**Comment by thibaultCha** [comment]
Implemented.

**Comment by thibaultCha** [comment]
Just a heads up on this: 0.4 has been quietly released now so this is available. We would love to hear feedback about 0.4 and the new features if you want to try it out. Thanks!

**Comment by sudheer-jerripotula** [comment]
How can do this in DB less mode?? When I use regex in domain part kong is throwing an error. I came across https://docs.konghq.com/hub/flash/set-dynamic-upstream-host/ which is not compatible in DB less mode.

**Comment by hishamhm** [comment]
> How can do this in DB less mode?? When I use regex in domain part kong is throwing an error

This is a very old issue that was closed a long time ago — any routing configuration that's supported with DB mode should work with DB-less as well. Which error are you getting?

> I came across https://docs.konghq.com/hub/flash/set-dynamic-upstream-host/ which is not compatible in DB less mode.

@sudheer-jerripotula The info in that documentation page looks inconsistent (I just [posted a docs issue about it](https://github.com/Kong/docs.konghq.com/issues/4094)), but the sidebar info says it _is_ compatible with DB-less. Did you give that plugin a try?
