### ISSUE TITLE
/bin/kong global script

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#3]
The global script for Kong should invoke commands such as `migrate`, `start`, `stop` etc...

We need to consider if we are going to write it in Lua or Bash. Lua will be installed on the machine anyways to run Kong and we could leverage tools already written such as migrate and seed.

**Comment by thibaultCha** [comment]
We have a good enough MVP script for now!

**Comment by kylegato** [comment]
@thibaultcha What happened with this? I can't seem to find any init scripts shipped with Kong. You said in #7 it was moved to this issue, so the trail seems to end here.

**Comment by thibaultcha** [comment]
This was about implementing a CLI, which we now have, not init scripts. For the record: so far we do not provide init scripts.

**Comment by kylegato** [comment]
What is the reasoning behind not offering init scripts?

**Comment by thibaultcha** [comment]
The community pressure for it is not huge so we currently allocate our - limited - resources on Kong itself. We would welcome such a contribution given it is provided for all our distribution packages - https://getkong.org/install/
