### ISSUE TITLE
[request] Add an api to expose the plugin schema

### ISSUE THREAD

**Issue by ajayk** [Mashape/kong#309]
For a plugin like filelog , an api like "/plugins/filelog/schema" which returns the plugin schema if exposed would help in creating an automated ui generation for the ever growing plugins

**Comment by thibaultCha** [comment]
The tricky part with this will be custom validation functions that are used for some values.

On a side note, it would be cool to also have an endpoint to explain what the plugin is doing, like a description string.

**Comment by Nijikokun** [comment]
Kind of like the package details, I like this idea. :+1:

**Comment by thibaultCha** [comment]
`/details` is cool, and could give a response with:

```json
{
  "name": "filelog",
  "description": "Logs to file [...]",
  "conf": {
    "path": { "type": "string" [...], "default": "...", "description": "where the logs will be written" }
  }
}
```

It only needs work on the `description` keys which don't exist for now (neither per plugin or per property).
Also notice how `conf` is actually the `value` of a `plugin_configuration` here, but it would also be the time to rename it.

**Comment by thefosk** [comment]
For custom functions, we can require a structured format that also includes a description, like:

```lua
local custom_validations = {
   validate_username = {
     description = "Validates that the username is an alphanumeric string",
     func = return function(val)
      -- Do something
     end)
   },
   validate_zipcode = {
     description = "Something",
     func = return function(val)
      -- Do something
     end)
   }
}
```

**Comment by thibaultCha** [comment]
Hi @ajayk, please check #376 to see if it satisfies your idea/needs, thanks

**Comment by ajayk** [comment]
@thibaultCha :+1:  Sorry for the delayed response , works like a charm !

**Comment by thibaultCha** [comment]
Pleased to hear it'll be useful to you then
