### ISSUE TITLE
Add API: path depth

### ISSUE THREAD

**Issue by tbrownMT** [Mashape/kong#310]
When adding a new API and routing using the path parameter, Kong only supports a "1 deep" resource path.  For instance:

curl -X POST http://localhost:8001/apis --data 'name=test2' --data 'target_url=http://myapiserver:8080/someapi' --data 'path=/api/'

works, but:

curl -X POST http://localhost:8001/apis --data 'name=test2' --data 'target_url=http://myapiserver:8080/someapi' --data 'path=/api/v1/'

Does not.  Note the difference /api/ vs /api/v1/

When trying to add a deep path, Kong responds with:

{"path":"path must only contain alphanumeric and '. -, _, ~' characters"}

Kong should support arbitrary path depth.

**Comment by thibaultCha** [comment]
#318 implements this
