### ISSUE TITLE
DAO for plugins developers

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#312]
Like the way we allow developers to easily extend the Admin API, we need a way to allow them to easily extend the DAO, so they can interact with their plugin's tables.

Right now DAOs are implemented OOP-style, which is not very intuitive and need to have written queries. I am not sure about hiding the queries in this implementation tho. More to come later about this.

**Comment by thefosk** [comment]
IMHO it would be nice to have a DAO implementation that can auto-generate operations for the standard CRUD operations, especially if we plan to use multiple DAOs. Something like (*pseudo-code*):

```lua
local dao_crud = dao.dao_crud -- The right dao_crud is set by the dao_factory
dao_crud:insert("sometable", schema, value)
dao_crud:find_one("sometable", schema, query)
```

We would then need one implementation of `dao_crud` per datastore, and any new datastore we might introduce won't affect the plugins with the exception of rate-limiting which has a specific `increment` method that is deeply integrated with the underlying datastore and needs to be specifically implemented for each datastore. 

We can also wait until we really have another DAO to see what we really need.
