### ISSUE TITLE
Add API: path value being passed to the proxied API.

### ISSUE THREAD

**Issue by tbrownMT** [Mashape/kong#313]
Consider the following scenario. Proxy the Mashape Yoda Speak API:

https://yoda.p.mashape.com/yoda

behind Kong, using a custom path:

curl -X POST --url http://localhost:8001/apis --data 'name=yodabad' --data 'target_url=https://yoda.p.mashape.com/yoda' --data 'path=/v1.0/'

If you call the proxied endpoint (kongserver:8000/v1.0), it fails.  

curl -X GET --url http://localhost:8000/v1.0/?sentence=Hello --header 'X-Mashape-Key: mashape_key_here'

because the forwarded call to Yoda includes the specified path variable. Error from Mashape:

Cannot GET /yoda/v1.0/?sentence=Hello

If you define the API at the root, it works:

curl -X POST --url http://localhost:8001/apis --data 'name=yodagood' --data 'target_url=https://yoda.p.mashape.com/yoda' --data 'path=/'

I would expect that the path definition should be independent of the actual implementation. That is to say Kong should strip off the /v1.0 path and pass the rest of the query string along to the proxied API.

**Comment by thibaultCha** [comment]
It does. See the `strip_path` option in the PR [here](https://github.com/Mashape/kong/pull/282)

**Comment by tbrownMT** [comment]
Oh shoot! My fault. RTFM I suppose. :) Sorry for the bad issue report.

**Comment by thibaultCha** [comment]
Well it's not yet properly documented on the website so it's fine. It'll be taken care of tho

**Comment by montanaflynn** [comment]
I'd also have guessed the option would be true by default.
