### ISSUE TITLE
Immutable credentials

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#321]
Should the `key` property in the Key Authentication plugin, or the `client_id` and `client_secret` properties of the OAuth plugin be also `immutable` to prevent them from being updated?

Do we want to force a creation of a new credential if the credential data changes, or do we want to allow updating an existing one?

**Comment by thibaultCha** [comment]
From a consumer's POV, I find it more human-friendly to have to drop an existing key and create a new one. It enforces on the fact that you don't want key X anymore, and want to use a new one. So i'm in favour of making it immutable.

**Comment by thefosk** [comment]
How about `username` and `password` in the Basic Authentication plugin. Should those be `immutable` too?

**Comment by thibaultCha** [comment]
I can see those be updatable, but again, it's just my way of seeing things. It's closer to like, a website login and password than an API key.

**Comment by thibaultCha** [comment]
Are we in favour of making `key` immutable? Same for an OAuth `client_id`/`client_secret` imo.

**Comment by thefosk** [comment]
I think we gave it a try to close implement this, but then there was some obscure problem that broke everything.

**Comment by thibaultCha** [comment]
No we did this, it's the immutability of other properties in many plugins that is not done because of some bugs.

**Comment by thefosk** [comment]
Okay, opened #630 for that.
