### ISSUE TITLE
try using sudo with travis' new container based infrastructure

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#325]
we're now seeing this message in separate project using the new container based infrastructure, indicating that you can still get access to `sudo` in containers.

```
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
```

of course the document link does not expand on this, in fact it does not even mention `sudo: required` at all.

worth a try if it adds more speed to builds + ability to cache build directories.

\* *Travis documentation is always lacking behind actual features and functions.*

**Comment by thefosk** [comment]
This is not possible to implement now - I talked with some TravisCI engineers, and they plan to enable `sudo` for their new infrastructure (it's a work in progress on their side). When that happens we will adopt the new infrastructure.

In the meanwhile we also have support for CircleCI: https://circleci.com/gh/Mashape/kong

**Comment by driverpt** [comment]
@thefosk , i believe that if you distributed Debian/Ubuntu package through a Deb Repository or PPA, it would make it possible to use Travis PPA Plugin just by adding Kong official source.

There are tools that make that job easy. e.g.: [Aptly](https://www.aptly.info/)
