### ISSUE TITLE
[request] HMAC Signature

### ISSUE THREAD

**Issue by sinzone** [Mashape/kong#335]
Hash-based message authentication code

**Comment by lucamaraschi** [comment]
:+1:

**Comment by bigpg** [comment]
:+1:

**Comment by pcolby** [comment]
:+1: 

Ideally this would implement some existing / draft standard such as [draft-cavage-http-signatures-00](https://tools.ietf.org/html/draft-cavage-http-signatures-00).

**Comment by sinzone** [comment]
@pcolby  +1

**Comment by shashiranjan84** [comment]
What resources we are targeting here for signature? Shall we follow "draft-cavage-http-signatures-00" as @pcolby advised or we come up with our own standard?

**Comment by pcolby** [comment]
> Shall we follow "draft-cavage-http-signatures-00" ... or we come up with our own standard?

By principal, I'd recommend following a standard over inventing our own.

> What resources we are targeting here for signature?

It might make sense to make the targeted resources part of the configuration... if that doesn't complicate things too much?

Just my 2c :smile: 

PS [Tyk](https://tyk.io/), the only API management tool I'm aware of that supports HMAC out of the box, [currently implements draft-cavage-http-signatures](https://tyk.io/v1.8/access-control/hmac/) (not sure which draft).

**Comment by sinzone** [comment]
Thoughts? @lucamaraschi @bigpg

**Comment by shashiranjan84** [comment]
So final plugin implementation  would be similar to Key-Auth except the user will send a digest instead of password as part of Authentication header something like this. 

`Authentication: hmac username:base64(hmac-sha1(Date))`

where Date is the http date header.

Kong will create the signature using the password and match it with request signature to validate.

**Comment by lucamaraschi** [comment]
I like the idea of @shashiranjan84

**Comment by shashiranjan84** [comment]
@pcolby @lucamaraschi @bigpg [HMAC Plugin](https://getkong.org/plugins/hmac-authentication/) has been released, please give it a try.
