### ISSUE TITLE
[Documentation] Paginating results , limit query parameter 

### ISSUE THREAD

**Issue by ajayk** [Mashape/kong#339]
In the http://getkong.org/docs/0.3.2/admin-api/ 

in the /apis?limit=5

Response
{"limit":"limit is not queryable."}

limit
optional, default is 100	A limit on the number of objects to be returned.

In the code 
https://github.com/Mashape/kong/blob/master/kong/api/crud_helpers.lua#L45
query parameter size is used , 

Updating documentation would be helpful

**Comment by thibaultCha** [comment]
I updated the documentation yesterday, thank you for reporting!
