### ISSUE TITLE
[request] Api Service with plan support availability to control ratelimiting

### ISSUE THREAD

**Issue by jeevanrd** [Mashape/kong#343]
Hi,

We have requirement for user engagement with multiple plans for the same API service and want to enable rate limiting in some plans only. I don't see the kong in current form support this kind of feature.
Correct me if I am wrong.

Ex:
Service Name :  ProductService
Plans: 
UNLIMITED - no rate limiting
PREMIUM - with rate limiting

We even want to have ratelimiting support at api service per endpoint level as well. From one of the github issue comments, I saw a comment saying it is planned for near future. Any idea on this timelines for this to happen??

Thanks,
Jeevan

**Comment by jeevanrd** [comment]
cc @thefosk

**Comment by sinzone** [comment]
Before getting there we have to close #224

**Comment by Tieske** [comment]
This can be done using the rate limiting plugin on a consumer.

closing this.
