### ISSUE TITLE
CORS + Kong admin is 500ing

### ISSUE THREAD

**Issue by nicksamps** [Mashape/kong#345]
When I create an API that points at the Kong admin and add CORS to that api I'm getting 500s when I try to use it.

Here's what's in the error.log:
2015/06/17 21:51:53 [error] 10789#0: 178399 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/plugins/cors/access.lua:6: attempt to index local 'conf' (a nil value)
stack traceback:
coroutine 0:
/usr/local/share/lua/5.1/kong/plugins/cors/access.lua: in function 'configure_origin'
/usr/local/share/lua/5.1/kong/plugins/cors/access.lua:53: in function 'execute'
/usr/local/share/lua/5.1/kong/plugins/cors/handler.lua:12: in function 'access'
/usr/local/share/lua/5.1/kong.lua:206: in function 'exec_plugins_access'
access_by_lua(nginx.conf:87):1: in function <access_by_lua(nginx.conf:87):1>, client: **, server: _, request: "GET /plugins_configurations/ HTTP/1.1", host: "***"
2015/06/17 21:51:53 [error] 10789#0: 178399 [lua] responses.lua:52: send_HTTP_INTERNAL_SERVER_ERROR(): An unexpected error occurred, client: *, server: _, request: "GET /plugins_configurations/ HTTP/1.1", host: "***"

The CORS setup is using all default values and I'm running 0.3.2

**Comment by thefosk** [comment]
@nicksamps Can you please post here the HTTP requests that you used for adding the plugin ?

**Comment by nicksamps** [comment]
Sorry I've been in the wilderness for a few days! Here's what I used to add CORS.

```
POST /apis/kong-admin/plugins HTTP/1.1
Content-Type: application/x-www-form-urlencoded
apikey: ***
Host: ***
Connection: close
User-Agent: Paw/2.2.2 (Macintosh; OS X/10.10.3) GCDHTTPRequest
Content-Length: 9

name=cors
```

**Comment by thefosk** [comment]
@nicksamps found the bug, will be fixed in the next release.

**Comment by nicksamps** [comment]
Great, thanks!
