### ISSUE TITLE
cassandra_spec unit tests require Cassandra to be running

### ISSUE THREAD

**Issue by jasonmotylinski** [Mashape/kong#347]
I don't have Cassandra installed, purposefully, because I just wanted to build out some simple unit tests before building a custom plugin. 

When I run `make test` I receive an error which seems to indicate the unit tests are attempting to connect to Cassandra. 

```
Error → spec/unit/dao/cassandra_spec.lua @ 46
Cassandra DAO setup
./spec/spec_helpers.lua:161: Cassandra error: connection refused
```
Since the documentation indicated `make test-all` runs unit + integration tests I assume that unit tests shouldn't require Cassandra. 

Would it be possible to either update the documentation to include Cassandra as a dependency before running `make test` or update the test accordingly? If I can figure out Lua before you get to it I'll submit a pull request. :-)

**Comment by thibaultCha** [comment]
Cassandra is indeed a dependency to run the unit tests. The integration tests focus on a running Kong while unit are composants tests individually, and the DAO requires a running instance of Cassandra.

**Comment by ahmadnassri** [comment]
@thibaultcha what's a quick method to selectively run certain tests, or perhaps exclude some?

**Comment by jasonmotylinski-dowjones** [comment]
All the other tests in the `spec/unit` directory don't seem to have an issue with Cassandra not running. I found it interesting that just that one test required it.

**Comment by thibaultCha** [comment]
Plugins will ultimately be splitted to their own repos, so their tests will live on their own, developers will never in Kong's tests. Integration test a running Kong, and unit tests components and have coverage. So Cassandra shouldn't be moved out of unit/. 

It's possible with busted and tags to include/exclude specific tests.

**Comment by thibaultCha** [comment]
#410 addresses this and move the tests requiring Cassandra to be running to integration tests. I wasn't sure about this change but I do not want people to be confused and to not be able to run their tests, so here we go.
