### ISSUE TITLE
[request] Developer Portal Plugin

### ISSUE THREAD

**Issue by sinzone** [Mashape/kong#367]
- Landing pages/CMS
- Developer on-boarding (issuing keys, etc)
- Dashboard (charts, keys)
- API Editor + Docs

More in details:

User details
View/edit email address/Change password/etc
API details/API keys
API subscriptions
Analytics/Usage statistics/Charts
Documentation/code-snippet

**Comment by lucamaraschi** [comment]
:+1:  :+1:

**Comment by jasonmotylinski-dowjones** [comment]
+1

**Comment by sinzone** [comment]
How you guys envision this? As on-prem plugin or cloud plugin that you click a button and spin up a developer.yourcompany.com dev portal w/ relative admin in the cloud as well.

**Comment by dvh** [comment]
I think the nice thing about Kong is that it's just doing the technical stuff, making it ideal to implement in your own portal. Kong is a gateway, not a management suite. Perhaps you should use Mashape then ;-)

**Comment by sinzone** [comment]
@dvh Kong core is the gateway and always will be. 

But the plugins, can be 1,000s and eventually cover all the use cases related to API problems,: from monitoring to dev portal.  In this case Kong will become a platform and the value from the ecosystem will be much greater than the sum of the parts.

Those who just want the gateway won't activate other plugins, while companies looking into one-shop to solve all their API problems can find all their solutions in the plugins, and if not, they can build one their self.

**Comment by dvh** [comment]
Alright, then I agree ;-)

**Comment by acesyde** [comment]
Pretty cool feature, I agree :+1:

**Comment by sinzone** [comment]
coming very soon.

**Comment by sinzone** [comment]
Dev Portal plugin will be available in the 0.6

**Comment by CConnection** [comment]
+1

**Comment by sinzone** [comment]
Integration on the way! http://blog.mashape.com/mashape-acquires-gelato-io-to-provide-dev-portals-for-everyone/

**Comment by acesyde** [comment]
It's pretty cool thank @sinzone :+1:

**Comment by thefosk** [comment]
@thibaultCha @nikz @ahmadnassri write the technical Gelato integration here.

**Comment by CoreySwish** [comment]
Any docs for this integration?

**Comment by thefosk** [comment]
@CoreySwish It's still in the works, but coming soon.

**Comment by JohanTan** [comment]
Following up on this: Is this feature going to be available as a free plugin or only as a part of paid plans?

**Comment by sinzone** [comment]
@JohanTan  This integration (not a full plugin yet) is now live:  https://docs.gelato.io/guides/using-gelato-with-kong  - it's a commercial integration but there is a free plan if you need it for OSS projects.

**Comment by arsdehnel** [comment]
Is the plan that Gelato will also be able to do the creation (and maintenance) of APIs, Consumers and Plugins?  From what I can see now there is a way to "integrate" with Kong but that doesn't actually appear to give me an ability to add new APIs through the Gelato interface.  Maybe I'm missing something though.

**Comment by thefosk** [comment]
@arsdehnel the plan would be to release a separate product that will provide a GUI for Kong, built on top of the Kong API. The plan is to release it tentatively around Q3/Q4 2016.

**Comment by arsdehnel** [comment]
Alright, good deal and thanks for the clarification.

**Comment by mytototo** [comment]
@thefosk The Kong GUI will be an open-source product or a SaaS like Gelato or Galileo?

**Comment by thibaultcha** [comment]
Closing this due to the now-available Admin Portals and Gelato integration options.
