### ISSUE TITLE
Multiple paths & hosts per API.

### ISSUE THREAD

**Issue by sonicaghi** [Mashape/kong#369]
With regex support. See #192  for more details.

**Comment by thibaultCha** [comment]
- Support for regex
- Support for priority between multiple paths

**Comment by dvh** [comment]
+1. Any progress? Can't find it in the roadmap yet... I think this conflicts a bit with the ACL issue that consumers are not related to a single API but have access to all APIs. However, all APIs should have a different host, making that thought quite strange imho ;-)

**Comment by ahmadnassri** [comment]
+1 multiple host matching is certainly needed

**Comment by Malet** [comment]
:+1:

**Comment by frascuchon** [comment]
+1

**Comment by alexanderyoung** [comment]
+1, this is a roadblock for my use case too.

**Comment by thefosk** [comment]
The proposed solution would be to support the following properties on the API object:

* `request_hosts` (instead of `request_host`)
* `request_paths` (instead of `request_path`)

Both would support a list of values, and both would support named parameters with regex support, like: `api.$environment(staging|production).helloworld.com` or `/accounts/$user/invoices/$invoice_id(\d+)/`.

We still need to find a consensus about the format of the named parameter. The above format works well when the parameter is delimited by slashes `/` or dots `.`, but it wouldn't work well if there is a need to use them in a more free form, like `api.$environmentservice.com` (we don't know if the parameter ends at `$environment` or `$environmentservice`, so maybe something with explicit beginning and ending like `api.{environment}service.com` would work better (or `api.{environment(\d+)}service.com`).

Thoughts?

**Comment by leozc** [comment]
Thanks, @thefosk, I suggest just use a simple pattern to indicate the boundary of regex, {} may work well.

e.g
{REGEX}service.com where regex can be the regular expression.

NOTE: {} may collide with {min,max} in regex, but if your parser is greedy and extract the longest pattern between {} that should not be a problem.

**Comment by supagroova** [comment]
:+1:

**Comment by nickmchardy** [comment]
:+1:

**Comment by noamelf** [comment]
:+1:

**Comment by tjsousa** [comment]
:+1:

**Comment by RossJayJones** [comment]
+1

**Comment by rsbarata** [comment]
👍

**Comment by JingWZ** [comment]
👍
eager for this. Any progress on it?

**Comment by pochadri** [comment]
+1

**Comment by kylegato** [comment]
+1

**Comment by fredericocabral** [comment]
+1

**Comment by checkbutton** [comment]
+1

**Comment by haimsabag** [comment]
Hi, any concrete plans or updates on the subject? We really need this :)

**Comment by vitorsdcs** [comment]
+1

**Comment by zack9433** [comment]
👍

**Comment by rogoman** [comment]
👍

**Comment by LouisKottmann** [comment]
While I understand it is not trivial to implement, this subject has been going on for well over a year.

Does Mashape plans to implement a way to do path-based routing at all or should we turn to another solution?

**Comment by thibaultcha** [comment]
We do have such plans and are currently working on it. The reason for the wait is not because of the non-triviality, but rather a long list of more pressing matters to address so far.

Initial support for multiple paths and hosts should land in an upcoming 0.10.

**Comment by Roam-Cooper** [comment]
Is there currently any way to have kong use routes with url parameters with Kong or is that not possible? I don't necessarily want to map the parameters differently, I just want kong's request path to be able to have wildcards the same as my app.

Ie "/resource/:id" or "/resource/:id(/^\d+$/)".

**Comment by alfirin** [comment]
👍

**Comment by Marak** [comment]
I'm helping setup Kong for a major enterprise and we are somewhat dependent on this feature.

If you'd like any additional resources for performing acceptance testing on `v0.10.0` when it's ready please let us know.

**Comment by thibaultcha** [comment]
> If you'd like any additional resources for performing acceptance testing on v0.10.0 when it's ready please let us know.

@Marak I would love to hear more about what would be those requirements indeed.

**Comment by Marak** [comment]
@thibaultcha -

One of our Senior Developers submitted the enterprise sales form a couple of times this month with no response.

We are looking to host APIs for multiple applications in one Kong. Without the ability to enter the same `request_path` or `request_host` twice, it seems fairly difficult to setup a streamlined solution. Not 100% sure I'm responding to the correct issue here.

For example, we can't figure out how to easily do something like:

```
1. 
request_host: marak.com
request_path: /foo

2. 
request_host: larry.com
request_path: /foo
```

This fails in Kong Dashboard with `already exosts with value /foobar`, is that expected? 

If so, it seems impossible to setup granular routes in Kong for multiple applications which share the same routing namespaces.

**Comment by thibaultcha** [comment]
@Marak In that particular case you described, wouldn't setting those 2 different APIs work with:
```
1. 
request_host: marak.com

2. 
request_host: larry.com
```

Since there doesn't seem to be a need for `request_path` here?

**Comment by Marak** [comment]
Why would you assume there is no need for `request_path`?

I'll try to make it more clear:

```
1. 
request_host: marak.com
request_path: /foo
upstream_url: http://google.com/foo

2. 
request_host: marak.com
request_path: /foobar
upstream_url: http://bing.com/foo

3. 
request_host: larry.com
request_path: /foo
upstream_url: http://yahoo.com/foo

4.
request_host: larry.com
request_path: /foobar
upstream_url: http://altavista.com/foo

```

**Comment by thibaultcha** [comment]
There was no assumption but a clear indication that *in that particular example* you have, there was no need for it; surely it had to be more than that :)

Yes, that use case in the second example is covered in the upcoming new router.

**Comment by vautrinr** [comment]
Hello!

I would like to know, when it could be available??

Rémi 👍

**Comment by Marak** [comment]
@thibaultcha - 

Sounds good. 

When the `0.10` branch is ready for acceptance testing, please let us know and I can devote some resources for testing.

**Comment by bakstad** [comment]
Any progress on this issue?

**Comment by loicboutet** [comment]
Juste encountered this issue, any update on this ?

**Comment by david-dumas** [comment]
+1

**Comment by kstigen** [comment]
+1

**Comment by alfirin** [comment]
Any progress on this issue please?

**Comment by thefosk** [comment]
Available in latest `0.10.0rc1`. Please set the `hosts` and `paths` parameters when adding an API. Regex support is not enabled.

**Comment by Marak** [comment]
@thefosk @thibaultcha 

I've dedicated some resources to testing `0.10.0rc1` and this feature over the next week.

Will let you know how our testing goes. Thanks again!

**Comment by phlllpe** [comment]
:+1:

**Comment by diegonobre** [comment]
:+1:

**Comment by Marak** [comment]
Initial reports from our engineers are saying that it's working. Great success so far. Thank you!

Will be moving on to stress tests in the upcoming weeks.

FYI, we've got a test suite / client adapter for the kong admin api written in Node.js. I've found a few of these already on NPM, but none of them were slim / separated concerns. Do you guys have any interest in this? I can see if the company is willing to open-source the Node.js kong admin api client library.

**Comment by thibaultcha** [comment]
@Marak Glad to hear. The new router should slightly improve performance compared to Kong 0.9 but not by a significant margin, as plugins remain the bottleneck of the proxied traffic.

> Do you guys have any interest in this?

Any tool benefiting the community is most welcome! I am sure it would find its user base. Would you open-source it, we would add it to our list of [community tools](https://github.com/Mashape/kong#community-resources-and-tools) in this repo.

**Comment by thibaultcha** [comment]
I have opened #1970 which includes some detailed changes and documentations (non-exhaustive) concerning the new router and its capabilities, in case anyone is interested in consulting it. Reviews are welcome too (however the branch needs some cleanup).

**Comment by thibaultcha** [comment]
FYI, here is the documentation for this new router: https://github.com/Mashape/getkong.org/blob/release/0.10/app/docs/0.10.x/proxy.md

Reviews appreciated.

**Comment by thibaultcha** [comment]
Closing this as Kong 0.10.0 is now released with support for this, and regex support is part of another discussion.

**Comment by leozc** [comment]
@thibaultcha  Thanks!
PS: the link to the doc is 404
https://github.com/Mashape/getkong.org/blob/release/0.10/app/docs/0.10.x/proxy.md

**Comment by thibaultcha** [comment]
Yes, the branch was merged and deleted and the doc is now published at:

https://getkong.org/docs/0.10.x/proxy/

**Comment by RodH257** [comment]
Are there plans to add the regex support at some point? It was mentioned a few times in this issue

I'd love to be able to do:
`GET /accounts/:id/documents` -> service A
`GET /accounts/` -> service B

**Comment by thibaultcha** [comment]
Yes, see the related issue for that.

**Comment by RodH257** [comment]
Ah sorry it didn't come up on my initial searches, for others reference here is the discussion: https://github.com/Mashape/kong/issues/677 

Thanks @thibaultcha !
