### ISSUE TITLE
Admin Authentication

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#378]
To support authentication with multiple admin users. This is also related to #338, and may impact #298 (different CORS setting per admin user, etc). It's somehow related to #133.

**Comment by thefosk** [comment]
Also related to #380

**Comment by harlow** [comment]
+1

**Comment by BrianHutchison** [comment]
+1

**Comment by geovanisouza92** [comment]
+1

**Comment by wsenjer** [comment]
+1

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [admin authentication](https://trello.com/c/8Xmdxpy0/25-admin-authentication)

**Comment by coopr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Admin Authentication, Admin API security, Plugins on Admin API](https://trello.com/c/8Xmdxpy0/25-admin-authentication-admin-api-security-plugins-on-admin-api)

**Comment by feichaohao** [comment]
+1

**Comment by p0pr0ck5** [comment]
Kong Enterprise now offers RBAC authorization! https://getkong.org/docs/0.10.x/secure-admin-api/#role-based-access-control :D
