### ISSUE TITLE
Kong on Azure Marketpleace

### ISSUE THREAD

**Issue by sonicaghi** [Mashape/kong#387]
A joy for the million of devs using MSFT technologies

![](https://loopconf.io/wp-content/uploads/2015/01/azure.jpg)

**Comment by jiteshBhate** [comment]
am facing following issue, to deploy Kong in Azure portal
New-AzureRmResourceGroupDeployment : 10:12:57 AM - Resource Microsoft.Compute/virtualMachines 'MyAzureKongVM' failed with message '{
"error": {
"code": "InvalidParameter",
"target": "linuxConfiguration.ssh.publicKeys.path",
"message": "The value of parameter linuxConfiguration.ssh.publicKeys.path is invalid."
}
}'

I followed https://github.com/Mashape/kong-dist-azure
And generated ssh key using
ssh-keygen -t rsa -b 2048
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys

key is getting saved in file is C:\users@username.ssh\id_rsa.pub
and I updated sshKeypath and sshKeyData as per intruction
I am using windows 7.

Thanks,
Jitesh

**Comment by tavikukko** [comment]
By clicking the button "Deploy to Azure" will open a form in Azure Marketplace and the installation of KONG will start. Created [PR](https://github.com/Mashape/kong-dist-azure/pull/1) for the button.
<img width="1000" alt="screen shot 2017-04-13 at 1 14 36" src="https://cloud.githubusercontent.com/assets/2223355/24981770/d0394440-1fe6-11e7-97b3-890d4c194bbc.png">

The form:

<img width="772" alt="screen shot 2017-04-13 at 1 12 57" src="https://cloud.githubusercontent.com/assets/2223355/24981957/acd55114-1fe7-11e7-9207-3b67daa685f2.png">

The installation:

<img width="573" alt="screen shot 2017-04-13 at 1 23 25" src="https://cloud.githubusercontent.com/assets/2223355/24982004/ee0ae428-1fe7-11e7-9eeb-753053f569ac.png">

**Comment by p0pr0ck5** [comment]
https://github.com/Mashape/kong-dist-azure :D
