### ISSUE TITLE
Kong on Google Cloud Engine

### ISSUE THREAD

**Issue by sonicaghi** [Mashape/kong#388]
![](https://www.twilio.com/blog/wp-content/uploads/2013/04/01-digital_google_cloud_platform_logo_lockup-01-1.png)

**Comment by jasonmotylinski-dowjones** [comment]
We were able to use the docker images to push to Container Engine in GCP. Worked nicely.

**Comment by sinzone** [comment]
https://cloud.google.com/launcher/

nginx example: https://cloud.google.com/launcher/solution/nginx-public/nginx-plus?q=nginx

**Comment by shashiranjan84** [comment]
We now have templates to launch Kong + Cassandra cluster on GKE. Support for Postgres would be added once Kong 0.9.0 docker image is released

https://github.com/Mashape/kong-dist-google-cloud

**Comment by thibaultcha** [comment]
@shashiranjan84 Can we close this? This is the last issue part of the 0.10 milestone 😄

**Comment by shashiranjan84** [comment]
@thibaultcha  https://github.com/Mashape/kong-dist-mesos will work will any provider which supports Kubernetes managed cluster. Will be sending a doc PR by today or tomorrow.

**Comment by thibaultcha** [comment]
Okay, thanks, closing this then.
