### ISSUE TITLE
Kong AWS AMI

### ISSUE THREAD

**Issue by shashiranjan84** [Mashape/kong#389]
Example: kong/downloads/#aws

https://coreos.com/docs/running-coreos/cloud-providers/ec2/

**Comment by thefosk** [comment]
Because Kong doesn't work without Cassandra, we should also investigate in creating a CloudFormation stack that also starts a Cassandra cluster (I know @ahmadnassri was supposed to look into this, but maybe @shashiranjan84 can help).

**Comment by sinzone** [comment]
+100

**Comment by ahmadnassri** [comment]
I have not made any progress on this. @shashiranjan84 feel free to go at it!
