### ISSUE TITLE
[request] Admin Frontend GUI

### ISSUE THREAD

**Issue by theopak** [Mashape/kong#391]
Any interest in having a multi-user frontend interface for the Admin API? It would need to use the API documented here: http://getkong.org/docs/0.3.2/admin-api/. 

The API is already easy to use from the command line (via curl), but if it's going to support multiple users in the future then I would imagine that it would be useful to have a CRUD interface for APIs and Consumers. Anyone else agree? 

Apigee, Auth0, AWS, Mashery, and other competitors have frontend UIs for this purpose.

The prerequisites would be:

- The Admin API is a plugin (suggested by a comment in #133)
- The Admin API supports multiple users (#378)

**Comment by theopak** [comment]
Forgot to mention, this is related to #367 although here I'm talking specifically about an interface for _administrative_ users, not just developers that consume the APIs.

**Comment by sinzone** [comment]
@theopak this is definitely coming and we'll put in our roadmap after the 0.4 release of next week. 

There is also a basic OSS GUI verson built by the community: https://github.com/rsdevigo/jungle

**Comment by theopak** [comment]
Awesome! :100:

**Comment by pileenretard** [comment]
Hello, is this request still in the roadmap? maybe you could start by integrating jungle as is, and as a plugin? 
Any release date to share with community?

**Comment by sinzone** [comment]
Planned for 2016. 

There is another one here worth a look: https://github.com/vikingco/django-kong-admin

**Comment by Toilal** [comment]
@PGBI :+1: Thanks, it works well.

Some ideas to investigate if you have time ...
1) Use [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular) ? It's really good and includes features like ES6, Jade templates.
2) Use [Angular Material](https://material.angularjs.org/latest/) instead of Materialize ? It will hit 1.0.0 really soon and is designed for AngularJS.
3) Use [Restangular](https://github.com/mgonto/restangular). As kong API is really straigthfoward, it should works nicely and will reduce you services code.

But anyway great job ! It's really usable, thanks !

**Comment by PGBI** [comment]
@Toilal Thanks for your ideas. I had a look at Angular Material but it wasn't stable yet. Didn't know about Restangular or generator-gulp-angular, will have a look!

**Comment by rafaelspecta** [comment]
Awesome alternatives, congrats.

**Comment by kamoljan** [comment]
@PGBI thank you!

**Comment by geovanisouza92** [comment]
+1

**Comment by apiplug** [comment]
We have created a web based Kong Admin Manager. You can check details from our blog post [https://apiplug.com/blog/web-based-kong-api-gateway-manager/](https://apiplug.com/blog/web-based-kong-api-gateway-manager/) We would like to hear your feedbacks and suggestions about it.

**Comment by thibaultcha** [comment]
You could use any of the available ones out there developed by the community, Closing this in the meantime.

**Comment by pantsel** [comment]
All the GUIs mentioned in this post are awesome!
We've been also working on an open source Kong Admin GUI built on sails js.
We're adding more features as we go.
You are most welcome to check it out https://github.com/pantsel/konga

**Comment by sinzone** [comment]
@pantsel looks cool!

**Comment by pantsel** [comment]
@sinzone  cheers!

**Comment by sashahilton00** [comment]
@sinzone am update on when Kong will be getting an Admin UI? Just wondering as 2016 is drawing to a close. If you wanted to bundle an existing interface with Kong, Konga is the best one I've used by far, and has relatively few bugs, and would need minimal work to adjust the interface to look more like the other Mashape interfaces.

**Comment by harryparmar** [comment]
@apiplug is your solution for ui, premium product? also is it hosted solution or it can be deployed internally?
