### ISSUE TITLE
response_transformer: option to not overwrite header

### ISSUE THREAD

**Issue by jkarneges** [Mashape/kong#393]
When I try to add a header that already exists, the original is overwritten. This is for a type of header that can appear multiple times.

Perhaps you could add another option, ``value.concat.headers``, where any headers specified would be added without removing any that already exist. That or the original header is rewritten as a comma-separated list of all the values (both forms are synonymous according to the HTTP spec).

**Comment by shashiranjan84** [comment]
@jkarneges we released kong 0.6.0 with the fix. now 'add' only add if header is not already set. we also 'append' to append values to already set header.
