### ISSUE TITLE
[request] Allow target_url to contain env vars

### ISSUE THREAD

**Issue by adamclerk** [Mashape/kong#429]
I'm working with kong within docker. I'd love to be able to specify target_url to include env vars that are evaluated and replaced in the `get_backend_url` function.

https://github.com/Mashape/kong/blob/a01fbfad0f26b0faeabd8363447dd8d0b90f512a/kong/resolver/access.lua#L52

**Comment by thefosk** [comment]
Hi @adamclerk, can you please explain your use case? Maybe we can find a better solution to this

**Comment by adamclerk** [comment]
Sure thing. 

I had this idea as I was struggling to get nginx to resolve a linked container's hostname. I realized that I didn't have to worry about hostname resolution. Docker would put the ip address of the linked container in a env var for me when the containers were linked.

So...

When I link a docker container, other than casandra, to kong.
```
docker run -d -p 8000:8000 -p 8001:8001 --name kong --link cassandra:cassandra mashape/kong --link apiv1:apiv1
```
I would like kong use the environment variable `APIV1_PORT_8080_TCP_ADDR` in the target url.

So I might have a target_url that is configured like...
`target_url=http://{APIV1_PORT_8080_TCP_ADDR}:8080/'

I'm more than happy to consider alternatives.

**Comment by thefosk** [comment]
So, when linking containers in Docker, a new entry is created into `/etc/hosts`, like:

```
cassandra 1.2.4.5
```

You can leverage this by setting a `target_url` that's something like `http://cassandra`. nginx will resolve `cassandra` to whatever container that DNS is associated with.

**Comment by thefosk** [comment]
I am closing this issue now. Please re-open it if the above solution didn't work. @adamclerk
