### ISSUE TITLE
Better 404 page in the website

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#43]
Funny ideas are welcome :)

**Comment by thibaultCha** [comment]
TODO label is supposed to be **absolutely** necessary for one of the releases.

**Comment by thibaultCha** [comment]
Also this could just be in the already #5 issue....... We'll end up with tons of duplicates again.

**Comment by thefosk** [comment]
@ahmadnassri can join us on this too

**Comment by thefosk** [comment]
#5 made sense when everything had to be built from scratch for the first time. Now that things are coming closer to their final shape, for specific tasks on the website we should open specific issues.
