### ISSUE TITLE
[request] More OAuth 2.0 grant types?

### ISSUE THREAD

**Issue by marcoleary** [Mashape/kong#430]
Hi, great work so far on the OAuth 2.0 plugin. Will you be adding the client_credentials grant type in the near future?

**Comment by thefosk** [comment]
@marcoleary yes, that is in the roadmap and coming soon.

**Comment by thefosk** [comment]
@marcoleary this has been implemented. Today we are going to release 0.4.1 so you will see the updated doc here: http://getkong.org/plugins/oauth2-authentication/

**Comment by thefosk** [comment]
@marcoleary we have just released 0.4.1, with an updated doc on the website for the Client Credentials flow. Let me know if you experience any issue.

**Comment by marcoleary** [comment]
Cheers! Looking forward to giving it a whirl.
