### ISSUE TITLE
Support for multiple auth methods for single consumer

### ISSUE THREAD

**Issue by zeridon** [Mashape/kong#435]
Hi Guys,

While playing around i reached the following:
* Single API
* Single consumer
* Basic auth credentials for this consumer (more than one set)
* Keyauth - more than one set
* Keyauth was enabled first

This leads to basic auth being unusable. E.g. when authing with user/pass combos it says i need a keyauth also. Is this intended effect?

Is it possible to configure stuff like this. E.g. auth either with basic or key.

**Comment by thefosk** [comment]
To better understand your question, would you like to chain multiple authentication systems together?

**Comment by zeridon** [comment]
Chaining is currently what happens. I want to be able to use any of the available.

I.e. use user/pass (aka basic) for one system (e.g manual tester/qa) OR keyauth (aka hash/header) with other system (production)

**Comment by thefosk** [comment]
Do you think it's reasonable to have two APIs on Kong? One production and one development, with different plugin configurations?

**Comment by zeridon** [comment]
Reasonable yes, unfortunately not really feasible. Main driver behind this setup is we are migrating to an API style auth (e.g. header, with some magic value (even if statically configured)). We were wondering if we could use kong as both LB frontend and cheap auth implementation.

**Comment by thefosk** [comment]
For the Load Balancer part, this is referenced to #157.

When I mentioned "two APIs on Kong", doesn't necessarily mean two different APIs on your side, but two different API objects in Kong that point to one API on your side. Like:

```bash
curl -d "name=test-production&public_dns=test-production.com&target_url=http://my.api/" ...
curl -d "name=test-staging&public_dns=test-staging.com&target_url=http://my.api/" ...
```

Where both APIs point to the same `target_url` (or `path`, if you are using the path resolver), but on Kong's side you can configure the authentication plugins independently for each of them.

**Comment by neilalbrock** [comment]
I think it would be useful to enable optional authentication using any one of the available methods, for a single API.  I say this would be useful because I have existing code authenticating using basic auth but would like to deploy new code using key auth and gradually migrate to that over time.  In the meantime, having to choose one or the other is a little inflexible.

**Comment by zeridon** [comment]
Yes indeed it would be usefull for exactly this migration scenario

**Comment by sinzone** [comment]
+1

**Comment by thibaultCha** [comment]
I am closing this in favor of #590 which I slightly updated to also reflect the concerns described here.
