### ISSUE TITLE
CLI tool should be made into separate project

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#441]
- should allow for installation separately from Kong core
- should allow for controlling a remote instance(s) of Kong
- should come bundled with distribution packages either as a dependency (debian) or compiled in (docker)

**Comment by thefosk** [comment]
@ahmadnassri Why do we want the CLI to be installed separately from Kong core?

**Comment by ahmadnassri** [comment]
you can still package it with the code in the distributions of course.

but just like `mysql-server` & `mysql-client` you can install them separately and use the client to control a remote instance of Kong.

when you have multiple servers running Kong remotely in production, its much easier to run the Kong CLI locally and make any modifications needed, than SSH into the host every time.

**Comment by thefosk** [comment]
The CLI we currently have is the CLI for the server, which cannot be exported away from core. It's the equivalent of `mysqld` of `mysql-server`.

Currently the `mysql-client` equivalent for Kong is `curl` or any other HTTP client library.
