### ISSUE TITLE
strip_path strips multiple matching prefixes

### ISSUE THREAD

**Issue by codewaffle** [Mashape/kong#442]
I've got a setup mostly like this, under Kong 0.4.1 on Debian Wheezy using a precompiled release:
```
path: /embed
strip_path: true
target_url: http://my_api_host.com/embed-api
```
I want to access the endpoint at `http://my_api_host.com/embed-api/embed/[stuff]` via `http://kong_host.com/embed/embed/[stuff]`

Kong is giving me back `http://my_api_host.com/embed-api/[stuff]` instead, treating both `embed` entries in the path as parts to be stripped instead of just the first.

**Comment by sycdan** [comment]
Can we not just limit the gsub to 1?

```
request_uri = string.gsub(request_uri, escaped_path, "", 1)
```
