### ISSUE TITLE
use the requested Host header in the proxied request

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#444]
When setting up Kong in-front of an API service that relies on the Host header for routing (e.g. Kong itself), Kong uses the `target_url` in the proxied request.

it should either:

- have a flag to use the client-side `Host` header all the way through *(perhaps this should be the default?)*
- allow the `Host` header to be set at the time of creation as an additional property of the API object.

alternatively the `request-transformer` plugin could be used here, however, currently attempting to overwrite the `Host` header with `request-transformer` does nothing. *(see #445)*

###### detailed example:

```
┌────────────────────┐
│      Consumer      │
└────────────────────┘
           │
           ▼
┌────────────────────┐
│GET / HTTP/1.1      │
│Accept: */*         │
│Host: mockbin.com   │
└────────────────────┘
           │             ┌─────────────────────────────────────────┐
           ▼             │{                                        │
┌────────────────────┐   │  "public_dns": "mockbin.com",           │
│        Kong        │───│  "target_url": "http://173.236.235.78/" │
└────────────────────┘   │}                                        │
           │             └─────────────────────────────────────────┘
           ▼
┌────────────────────┐
│GET / HTTP/1.1      │
│Accept: */*         │
│Host: 173.236.235.78│
└────────────────────┘
           │             ┌─────────────────────────────────────────┐
           ▼             │{                                        │
┌────────────────────┐   │  "public_dns": "mockbin.com",           │
│        Kong        │───│  "target_url": "http://mockbin.org/"    │
└────────────────────┘   │}                                        │
           │             └─────────────────────────────────────────┘
           ▼
┌────────────────────┐
│  API not found :(  │
└────────────────────┘

           x
┌────────────────────┐
│    mockbin.org     │
└────────────────────┘
```

**Comment by thefosk** [comment]
I can easily fix this, but it *may* lead to some problems. I believe the reason we decided to change the `Host` header to reflect the target url's host, is because it created issues with the Virtual Host resolution.

We need to better test this.

**Comment by thefosk** [comment]
Specifically, we need to understand if this is really required: https://github.com/Mashape/kong/blob/master/kong/resolver/access.lua#L179

The fix to this issue would be to comment that line, and add the following nginx directive before the `proxy_pass` instruction:

```nginx
proxy_set_header Host $host;
```

**Comment by ahmadnassri** [comment]
as mentioned, I believe both solutions are valid (in different scenarios) therefore, should be flag ... or a feature of request transform plugin

**Comment by thefosk** [comment]
I have added the `preserve_host` flag (default `false`) when adding a new API.
