### ISSUE TITLE
request_host should allow regex names similar to nginx's method

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#446]
when attempting to create an API profile with a wildcard subdomain and a wildcard TLD, I get the following error message:

```
"request_host": "Only one wildcard is allowed: *.mockbin.*"
```

###### expected

should allow for using [regex naming](http://nginx.org/en/docs/http/server_names.html#regex_names) for `request_host`

**Comment by thibaultCha** [comment]
That is just how nginx implemented their wildcard support

**Comment by ahmadnassri** [comment]
right, so is there another issue to track [regex names](http://nginx.org/en/docs/http/server_names.html#regex_names)?

**Comment by thibaultCha** [comment]
Yeah the one you commented on I think is the right spot.

What you want is regex I think, not 2 wildcards

**Comment by thefosk** [comment]
Closing in favor of #369.
