### ISSUE TITLE
[Question] 404 being returned when resources accessed through Kong

### ISSUE THREAD

**Issue by cedw93** [Mashape/kong#447]
This is my first time using Kong so maybe I'm doing something wrong.

I have a simple application with two `API endpoints` which are currently located at (GET) `localhost:3000/` (POST)`localhost:3000/auth` (not very good end points but this is a simple test app). 

If I use `postman` or similar I can successfully access these routes 
and return the desired results.

For testing purposes I have set the POST and GET routes above to return a simple string, currently `POST` will return `post route` and `GET` will return `get route` this is for testing kong. I also have a default `not found` error message which returns `route not found`

If I have the following routes stored in my `kong/cassandra`:
```
{
    -data: [2]
     -0:  {
            public_dns: "*.testing.home"
            id: "26ece684-dd6f-434d-c3d7-b3b283db170e"
            target_url: "http://localhost:3000/"
           created_at: 1438350460000
           name: "home"
           }
    -1:  {  
           public_dns: "*.testing.auth"
           id: "6b423d9d-16b8-4131-c1a8-976550695141"
           target_url: "http://localhost:3000/auth"
           created_at: 1438348064000
           name: "auth"
          }
     }
```
Now If i execute the following `CURL` command:

```
curl -X GET  --url http://localhost:8000 -H 'Host: curl.testing.home'
```
I get the expected result, however if I do the following:

```
curl -X POST --url http://localhost:8000 -H 'Host: curl.testing.auth' -H 'Content-Type: application/json' --data '{"user":"xxxxx","password":"xxxxxxxx"}'
```
`route not found` is returned but this exact route is accessible if I set the `CURL --url` to `http://localhost:3000/auth` it works as expected.

I also tried to set up the route in this format:

```
{
    -data: [2]
     -0:  {
            public_dns: "*.testing.home"
            id: "26ece684-dd6f-434d-c3d7-b3b283db170e"
            target_url: "http://localhost:3000/"
           created_at: 1438350460000
           name: "home"
           }
    -1:  {  
           public_dns: "*.testing.auth"
           id: "6b423d9d-16b8-4131-c1a8-976550695141"
           target_url: "http://localhost:3000/"
           path: "/auth"
           created_at: 1438348064000
           name: "auth"
          }
     }
```

But the problem still persists.

Is there anything I doing wrong?

Ideally I want kong to authorise using my code and rules located at `http://localhost:3000/auth` which returns a status code based on authentication, depending on the result the user will be routed elsewhere.

Thank you.

**Comment by thibaultCha** [comment]
I just created a mock of your application and setup 2 apis just like you:

```json
{
    "data": [
        {
            "created_at": 1439258856000,
            "id": "6b357c32-0e39-42fa-c27b-84a977a61baf",
            "name": "auth",
            "public_dns": "*.testing.auth",
            "target_url": "http://localhost:3000/auth"
        },
        {
            "created_at": 1439258839000,
            "id": "7e746067-8049-44b5-c45c-a6aa7c042c60",
            "name": "home",
            "public_dns": "*.testing.home",
            "target_url": "http://localhost:3000/"
        }
    ]
}
```

I then query the API this way:

```bash
$ curl -X POST --url http://localhost:8000 -H 'Host: curl.testing.auth' -H 'Content-Type: application/json' --data '{"user":"xxxxx","password":"xxxxxxxx"}'
post route
```

And the request is indeed proxied. The GET request works too:

```bash
$ curl --url http://localhost:8000 -H 'Host: curl.testing.home'
get route
```

What version of Kong are you using and if not the latest, are you still experiencing this issue?
