### ISSUE TITLE
Resource Owner/Password Credential for OAuth2

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#448]
Implement the [Resource Owner Password Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.3).

**Comment by sinzone** [comment]
+1

**Comment by givmefive5** [comment]
May I ask how the authentication flow of this grant will be?

What I have in mind based from reading the updated code and reviewing the Authorization Code grant is as follows:

1. The client will connect to http://your.app.com/oauth2/token
2. Kong redirects this request to an upstream server that will check if the client id, username and password fields are valid.
3. This upstream server would send a post to Kong's your.api.com/oauth2/authorize to authorize the client.
4. Kong then sends a response back to the client with the generated access token, refresh token, and expiry time.

Is this correct or am I missing out something? Thank you!

**Comment by thefosk** [comment]
@givmefive5 it works in a similar way, just slightly in reverse order:

1. The client will connect to an endpoint on your side, sending a bunch of OAuth2 parameters including `username` and `password`.

2. You validate the `username` and `password`, and if they are correct, your make a `POST` request to Kong on the `/oauth2/token` endpoint sending all the parameters that the original client has sent, plus the `provision_key` (a secret that identifies it's you making the request) and `authenticated_userid` (a custom ID that identifies the user whose `username` and `password` belong to.

3. Kong will generate a JSON output

4. That you will just send back to the client as it is.

![oauth2-flow2](https://cloud.githubusercontent.com/assets/964813/9143283/3f7d0e94-3cfa-11e5-9fd7-024db1a02c18.png)

**Comment by givmefive5** [comment]
Thank you for that explanation. 

Regarding the authenticated_userid, can it be just the same as the user's username? 

Also, can one API be an endpoint for all user authentication? What I am thinking is that I want to have an Accounts API that manages the users for all my other APIs (Let's call one API in this as API 1) since they basically have the same users. 
As the client, can I call the oauth2/authorize of the Accounts API but the Accounts API would send a POST request to API 1's oauth2/token to generate an access token for the client to use the API 1?

Thank you very much!

**Comment by givmefive5** [comment]
Thanks @thefosk !

Another thing, just for clarification, provision_key only checks if the request for an access token came from a valid API right? We can still use the generated access token across all APIs under Kong and not just for the API that owns the provision key right?

**Comment by thefosk** [comment]
`authenticated_userid` can be any value that will allow you to identify the user later by reading the `X-Authenticated-Userid` header. In the docs we recommend using an ID because sometimes the username can change, while the ID should always be the same.

**Comment by thefosk** [comment]
The `provision_key` is not part of the OAuth 2.0 flow per-se. During the provisioning process your backend will talk with Kong, and the `provision_key` is just a secret key that makes sure it's really you talking to Kong and not a malicious user.

The final client/application will never have anything to do with the `provision_key`.

**Comment by givmefive5** [comment]
Thanks @thefosk ! 

This is just what we need for our project. Looking forward to your next release with this grant type in it!

**Comment by givmefive5** [comment]
Thanks @thefosk ! This is exactly what we need. Looking forward to your next version release with this!

**Comment by sinzone** [comment]
:hand: hive five!

**Comment by iconist** [comment]
how are we creating username and password for Resource Owner/Password Credential for OAuth2 in KongApi?
