### ISSUE TITLE
cannot start kong when using docker containers

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#452]
if I attempt to run a shell in `mashape/kong` and start kong, it hangs forever.

```
$ docker run -p 9042:9042 -d --name cassandra mashape/cassandra
$ docker run -it -p 8000:8000 -p 8001:8001 --name kong --link cassandra:cassandra mashape/kong bash
$ kong start
```

```
bash-4.2# kong start
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Kong version.......0.4.1
       Proxy HTTP port....8000
       Proxy HTTPS port...8443
       Admin API port.....8001
       dnsmasq port.......8053
       Database...........cassandra keepalive=60000 hosts=cassandra port=9042 timeout=1000 keyspace=kong
[INFO] Connecting to the database...
[INFO] dnsmasq started (dnsmasq)
```

**Comment by thibaultCha** [comment]
I think it has to do with the fact that you are not running the container in background mode.

**Comment by ahmadnassri** [comment]
> I think it has to do with the fact that you are not running the container in background mode.

perhaps, though that shouldn't be a requirement ...

**Comment by thefosk** [comment]
To login into a running Kong container, execute:

```shell
$ sudo docker exec -i -t 665b4a1e17b6 bash #by ID
$ sudo docker exec -i -t kong bash #by Name
```

**Comment by ahmadnassri** [comment]
that's not the point, I know how to exec bash in Docker. follow the steps I listed and you'll see the problem ... likely it's a Docker specific issue with centos and kong

**Comment by thefosk** [comment]
So you are linking `cassandra` to the container, which means that Docker will automatically create an entry like this into `/etc/hosts`:

```
172.17.0.1	cassandra 4d49987e149a
```

Did you now set `cassandra` as the host in the `kong.yml` file:

```yaml
databases_available:
  cassandra:
    properties:
      hosts: "cassandra"
      port: 9042
      timeout: 1000
      keyspace: kong
      keepalive: 60000 # in milliseconds
```
?

**Comment by thefosk** [comment]
Which is also what the official nginx container also does https://github.com/nginxinc/docker-nginx/blob/f4f58b1c4b433b0f82687a326d9c79d216c41de9/Dockerfile#L22

**Comment by thefosk** [comment]
I will close this issue now because it doesn't belong here, and it's not really an issue.
