### ISSUE TITLE
Unprivileged user destroys pidfile with kong service script

### ISSUE THREAD

**Issue by vacri** [Mashape/kong#459]
Running 'kong stop' as a non-privileged user destroys the pidfile at /usr/local/kong/kong.pid, which means that the privileged user can no longer stop the process.

The gist file below shows the root user starting and stopping kong, followed by the unprivileged user destroying the pidfile and stopping root from managing the process.

https://gist.github.com/8d72e2ceb26fadf8f0dc.git

Looks like the perms on /usr/local/kong (where the pidfile lives) are too open (777 instead of 755)

**Comment by thefosk** [comment]
@vacri thanks for the heads up. This problem will be fixed starting from the next version.
