### ISSUE TITLE
should be able to enable a plugin more than once on the same API profile

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#462]
using different configurations, plugins should be stacked in execution, perhaps with an order value.

e.g. any logging plugin, I should be able to log to more than one destination with the same plugin.

**Comment by thefosk** [comment]
I don't think I fully understand this - can you provide an example?

**Comment by ahmadnassri** [comment]
quite simply:

adding a plugin the first time works:

```bash
$ http POST localhost:8001/apis/mockbin/plugins name=filelog value.path=/tmp/log1.log
```
```http
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 11 Aug 2015 04:07:56 GMT
Server: kong/0.4.1
Transfer-Encoding: chunked

{
    "api_id": "a1818678-a319-4390-c337-5ab692a8b530", 
    "created_at": 1439266076000, 
    "enabled": true, 
    "id": "d105c64f-1acf-4482-c48d-3447484a1c1b", 
    "name": "filelog", 
    "value": {
        "path": "/tmp/log1.log"
    }
}
```

attempting to add another plugin configuration for the same plugin to the same api fails:

```bash
$ http POST localhost:8001/apis/mockbin/plugins name=filelog value.path=/tmp/log2.log
```

```http
HTTP/1.1 409 Conflict
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 11 Aug 2015 04:07:59 GMT
Server: kong/0.4.1
Transfer-Encoding: chunked

{
    "message": "Plugin configuration already exists"
}
```

###### expectation

should be able to add unlimited plugin configurations for the same plugin (as logic permits)

e.g. on the **same** API profile:

- should **not** be able to configure more than one SSL plugin
- should **not** be able to configure more than one Authentication plugin with the same header field (#460)
- should be able to configure more than one Authentication plugin with different header fields (e.g. `Authorization`, `X-Authorization`, `Proxy-Authorization`, etc...) (#460)
- should be able to configure more than one logging plugin
- should be able to configure more than one Request Transformer plugin 
- should be able to configure more than one Mashape Analytics plugin

**Comment by thefosk** [comment]
Plugins can be enabled only once for an API to avoid redundancy, keep clarity, and improve performance. For example:

> should be able to configure more than one logging plugin

In your example, instead of having nginx to write simultaneously to two files (which doubles the I/O activity and may potentially slow down the server), use a system tool to copy `/tmp/log1.log` into `/tmp/log2.log`.

> should be able to configure more than one Request Transformer plugin

Instead of having two Request Transformer plugins on the same API, we recommend having one with all the transformations in one plugin configuration.

> should be able to configure more than one Mashape Analytics plugin

What would be the use-case scenario? Even if Mashape Analytics wants to provide this feature, then it should be a plugin feature allowing to set more than one token when adding the plugin. We don't need to change Kong core to handle this.

**Comment by ahmadnassri** [comment]
my examples perhaps are not detailed enough:

- logging: I might want to have a local log file that's erased automatically or cleared by a cronjob, logrotate, etc... with an additional log file sent to a mounted NFS file system, yes this adds load, but that's my choice as the operator.

the idea here is "stacking" Plugins, which would also simplify or complicate logic of course.

example in `keyauth` plugin you can specify more than one header key name to use, instead, using stacking logic, you just add another `keyauth` plugin with new header key name

**Comment by thibaultCha** [comment]
Added to #505
