### ISSUE TITLE
ability to disable default SSL cert

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#463]
by default Kong has an SSL cert enabled signed by localhost.

there should be a way to disable this certificate (essentially turning the https port into another http port)

**Comment by ahmadnassri** [comment]
example of this in action: https://mockbin.com

**Comment by thefosk** [comment]
The reason why the SSL port is enabled by default is to allow the SSL Plugin to work without restarting or reloading the Kong cluster (thus avoiding having an exception in the way plugins are being installed).

For a more detailed explanation: https://github.com/Mashape/kong/issues/453#issuecomment-129634211

**Comment by Hughiegao** [comment]
The only place I see ssl;true with 5.1 configuration file is for cassandra ssl. Is there new setting for it?

## Databases configuration
databases_available:
  cassandra:
    properties:
      contact_points:
        - "localhost:9042"
      timeout: 1000
      keyspace: kong
      keepalive: 60000 # in milliseconds
      # ssl: false
      # ssl_verify: false
      # ssl_certificate: "/path/to/cluster-ca-certificate.pem"
      # user: cassandra
      # password: cassandra

**Comment by thefosk** [comment]
I think that disabling the SSL port can be done by just not exposing it to the world, by putting a firewall rule in front of it or by using `iptables`. That would be the best solution that would not affect how plugins work.
