### ISSUE TITLE
Empty response when perform GET or PATCH on oauth2 endpoints

### ISSUE THREAD

**Issue by dirkmoors** [Mashape/kong#469]
When performing GET or PATCH request on the endpoint "http://kong:8001/consumers/{consumer_id}/oauth2/{oauth2_id}", Kong returns an empty response, instead of a structure containing the oauth2 info related to {oauth2_id}. 
This behavior does not match other endpoints in the admin API.

**Comment by thefosk** [comment]
@dirkmoors this was a bug indeed. Just pushed a fix into master.
