### ISSUE TITLE
Mashape Analytics URI bug

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#470]
```
Aug 11 16:29:59 91.202.65.74 Aug 11 23:29:59 8851f804c05e nginx: 2015/08/11 23:29:59 [error] 54#0: [lua] buffer.lua:164: [mashape-analytics] socket server refused the batch. Status: (400) Error: (["[1] har.log.entries.0.request.url must be uri format"]), context: ngx.timer, client: 188.196.56.12, server: 0.0.0.0:8000
```

**Comment by SGrondin** [comment]
I added better debugging, so now it'll say `[1] har.log.entries.0.request.url must be uri format in [whatever]` where [whatever] is the incorrect value.

**Comment by thefosk** [comment]
@SGrondin did you deploy your fix? Because the log message is still the same.

**Comment by thibaultCha** [comment]
As of today, the error still says:

```
[3] har.log.entries.0.request.url must be uri format
```

So there is no way to know what it really contains.

**Comment by thefosk** [comment]
Now I can see the URI error properly:

```
Aug 26 16:16:14 52.18.160.195 Aug 26 23:14:58 ca6a250858df nginx: 2015/08/26 23:14:58 [error] 37#0: [lua] buffer.lua:164: [mashape-analytics] socket server refused the batch. Status: (400) Error: (["[0] har.log.entries.0.request.url must be uri format in 'http://square-core-qa.elasticbeanstalk.com/api/v1/customer/1_0_0/ideapiu/registrationservice/Dimitri/De Franciscis/12345'","[1] har.log.entries.0.request.url must be uri format in 'http://square-core-qa.elasticbeanstalk.com/api/v1/customer/1_0_0/ideapiu/registrationservice/Dimitri/De Franciscis/12345'"]), context: ngx.timer, client: 5.157.103.239, server: 0.0.0.0:8000
```

**Comment by thibaultCha** [comment]
Here are several values reported as invalid:

```
http://haproxy.marathon.mesos/spored/article/get/ekskluziv/tuja-scena/foto-ali-voscena-nicki-minaj-dobiva-kar-si-za sluzi.html
http://square-core-qa.elasticbeanstalk.com/api/v1/customer/1_0_0/ideapiu/registrationservice/Dimitri/De Franciscis/12345
http://cart.lmcloud.aws/cart/v1/remove/dKonDHcKn73Z1UFm9TSFRrnmQe2m8RZz/[object Object]
```

Any idea why? I will check the validation code later.

**Comment by thibaultCha** [comment]
It is visibly the space (see the [regex](https://github.com/mafintosh/is-my-json-valid/blob/master/formats.js#L7)). I will encode the URI but lua-nginx only offers [escape_uri](https://github.com/openresty/lua-nginx-module#ngxescape_uri) which is meant for URI components, and destroys the URI, so that will probably have to be custom.

**Comment by thibaultCha** [comment]
On a second though, I am not sure I should touch the URI at all. After all, it is the client who requested it without escaping it (and using `[]` which are reserved characters. I feel like the socket should accept those values, as they might not be valid URIs, but that is what was requested and as an API provider, I want to see those erroneous requests (and potentially reach out to my users to point the issue to them). @SGrondin @ahmadnassri thoughts as mashape analytics maintainers?

**Comment by ahmadnassri** [comment]
this is more of a HAR format / JSON validation issue than it is Mashape analytics ... we could expand the allowed character set ... maybe

actually surprised nginx even allows it?

**Comment by thefosk** [comment]
So does this issue bounce back to @SGrondin (or @kennethklee)?

**Comment by ahmadnassri** [comment]
bounce back to you first, do you want to follow the RFC specs or not?

On Wed, Aug 26, 2015, 11:17 PM Marco Palladino <notifications@github.com>
wrote:

> So does this issue bounce back to @SGrondin <https://github.com/SGrondin>
> (or @kennethklee <https://github.com/kennethklee>)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mashape/kong/issues/470#issuecomment-135271525>.
>
-- 

Ahmad Nassri

**Comment by thibaultCha** [comment]
It's not so much about the specs. The client did not respect the spec, we have to reflect it in the analytics logs.

**Comment by ahmadnassri** [comment]
that I agree with, and I believe latest build has error logging output in
detail

-- 

Ahmad Nassri

**Comment by thibaultCha** [comment]
No, I meant the logs stored by analytics. I mean on analytics's dashboard.

**Comment by ahmadnassri** [comment]
but we are discarding the input if its invalid ... not storing anywhere, so no way to message the user about it ... is that what you mean? otherwise I'm not following

**Comment by thibaultCha** [comment]
I mean you should not discard it, and you should store it.

**Comment by ahmadnassri** [comment]
that could become very dangerous since clients are paying for analytics data retention and storage, if somebody is sending malformed requests they could easily take over a user's quota and flood the system ..

that said, this conversation is about Analytics then, so lets take the discussion there, unless there's something specific to Kong, otherwise, lets close this issue,

**Comment by thibaultCha** [comment]
They would not take more space because of accepting invalid URIs. They could as well flood the system with valid URIs?

**Comment by thibaultCha** [comment]
Moved to Mashape Analytics.

**Comment by ahmadnassri** [comment]
actually, all of the examples provided above of the errors are because of the space in the URL, not the `[]` characters ... seems like the analytics plugin in Kong, is not properly parsing & encoding the URI before setting it in the JSON object.

**Comment by thibaultCha** [comment]
Damn it, ngx_lua returns those values unescaped. And the only way to escape them back is with `escape_uri` which break the URI (also escaping `/` separating components)

**Comment by ahmadnassri** [comment]
> Damn it, ngx_lua returns those values unescaped. And the only way to escape them back is with escape_uri which break the URI (also escaping / separating components)

I had the same problem with Node / PHP ... I end up parsing and re-constructing the URI every time to be safe.

**Comment by thibaultCha** [comment]
So while writing the serializer I respected the [ALF schema](https://github.com/Mashape/api-log-format/blob/master/versions/1.0.0.md) (where `request.url` does not contain the querystring) but [the HAR specs](http://www.softwareishard.com/blog/har-12-spec/) do contain the querystring.

Hence I used `ngx.var.uri` -> without the querystring (but unescaped). If we just use `request_uri`, it contains the querystring but it is the raw URI, as made by the client.
