### ISSUE TITLE
ratelimiting on API level is not overwritten by consumer level

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#474]
###### scenario:

- enable `ratelimiting` plugin on API profile, set to 2 req/min
- enable `ratelimiting` plugin on same API profile with a `consumer_id`, set to 20 req/min

###### result

throttled after 2 requests per minute.

###### expected

global API rate limit should be overwritten by consumer level rate limit

**Comment by thefosk** [comment]
Cannot replicate this problem. These are the commands that I have executed:

```bash
# Adding API
curl -d "public_dns=test.com&target_url=http://mockbin.org" 127.0.0.1:8001/apis

# Adding Key Authentication to API
curl -d "name=keyauth" 127.0.0.1:8001/apis/test.com/plugins

# Adding Consumer
curl -d "username=thefosk" 127.0.0.1:8001/consumers

# Adding Key to consumer
curl -X POST 127.0.0.1:8001/consumers/thefosk/keyauth

# Adding Ratelimiting to API
curl -d "name=ratelimiting&value.minute=2" 127.0.0.1:8001/apis/test.com/plugins
```

When consuming the API, I am now blocked after two requests:

```bash
curl -i -H "Host: test.com" 127.0.0.1:8000/request?apikey=e8a252a42e1e40e6c0036cb7353ee3c2
...
X-RateLimit-Limit-minute: 2
...
{"message":"API rate limit exceeded"}
```

I override the ratelimiting configuration with a per-consumer setting:

```bash
X-RateLimit-Limit-minute: 20
```

**Comment by ahmadnassri** [comment]
you're correct, the mistake I made is not adding the `keyauth` plugin to the API ... but that brings up another issue ... #475
