### ISSUE TITLE
File log formatting goes crazy when there is ugly cookie

### ISSUE THREAD

**Issue by tamizhgeek** [Mashape/kong#477]
For example, we got this as a cookie in a request:

mp_b46d27d6e2e966466ad3c3545a97a01a_mixpanel=%7B                     0istinct_id%3A%xxxx                                      0ndix.com%2C%24initial_referrer%3A%22                       0irect%2C%24initial_referring_domain%3A%22                       0irect%2C%22__mps%3A%7B%7D

This breaks the JSON log formatting, munges a large part of the log (the part of JSON which comes after {request: {header: {"cookie":xxx} ... }} ) *AND* the new line. Because of this all log entries are shown in a single line, which breaks the log analyzer we have. I tried tracking down the source for this, but couldn't Any help is highly appreciated. Please.

**Comment by thefosk** [comment]
@tamizhgeek Which logging plugin are you using?

**Comment by tamizhgeek** [comment]
@thefosk we are using the filelog. Then, updating to latest  or 4.0.1 solves this. I think your optimize buffer commit fixed this as a side effect ;-) Closing the bug
