### ISSUE TITLE
[resolver/path] trailing slash 404 on master

### ISSUE THREAD

**Issue by jeevanrd** [Mashape/kong#479]
Hi,

I have created an API as below
http://localhost:8001/apis?
name: hi
target_url:http://testapp.com/hi
strip_path:true
path: /hi

Today I have got the latest kong code and was testing it. When I access http://localhost:8000/hi throws 404 error now which is used to work until kong version 0.4.1.

Appending trailing slash will work http://localhost:8000/hi/ will work?

Pls advise.

Thanks, 
Jeevan

**Comment by thibaultCha** [comment]
Hi,

Using Kong 0.4.1 I just setup this API:

```shell
$ http :8001/apis name=mockbin target_url=http://mockbin.com/status strip_path=true path=/status
HTTP/1.1 201 Created
```

Then I query it through Kong:

```shell
$ http :8000/status/200
HTTP/1.1 200 OK

$ http :8000/status/200/
HTTP/1.1 200 OK

$ http :8000/status/
HTTP/1.1 404 NOT FOUND # returned by upstream API, correctly proxied

$ http :8000/status
HTTP/1.1 404 NOT FOUND # returned by upstream API, correctly proxied
```

Wether or not I add a trailing slash the call is correctly proxied to the upstream API. Could you please provide more details and test your API without going through Kong?

**Comment by jeevanrd** [comment]
By latest code, I mean latest master code. It works perfectly fine in kong 0.4.1.
It fails both in kong 0.4.2 or latest master code.

Thanks,
Jeevan

**Comment by thibaultCha** [comment]
I just retried the same steps as my previous comment on both 0.4.2 and master and both worked well. I have the same results as my previous comments. Could you please give it a try with the mockbin API?

**Comment by jeevanrd** [comment]
@thibaultCha Sorry to comment on the closed issue. The issue I have faced exactly like #495 . But I haven't added the query string in the url. Sry for that. 
Currently we are using the kong latest tag 0.4.1 and we want to migrate to latest tag (0.4.2 currently). This bug is stopping us to migrate. It would be g8 if you can push #495 fix to 0.4.2 tag  or create a new tag.

**Comment by thibaultCha** [comment]
Unfortunately we cannot do that, we'll have to wait for 0.5.0, sorry...

**Comment by jeevanrd** [comment]
Any idea on  0.5.0 release date ??

**Comment by thibaultCha** [comment]
We are finishing the ACL plugin, and polishing a few thing (including the 0.5.0 migration script and a few bugs), so it should't be too long. I would say a week or so.
