### ISSUE TITLE
Auto-generate keys when none is being specified

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#48]
In the authentication plugins, auto-generate keys when they're not being specified.

**Comment by thefosk** [comment]
This should probably be explicit, with a querystring parameter like:

 ```shell
curl -d "autogenerate_credentials=true" ...
```

**Comment by thibaultCha** [comment]
For generating keys and more: https://github.com/openresty/lua-resty-string 

I think they should be generated if none is in the parameters. Or maybe all the time, as it is safer.

**Comment by thefosk** [comment]
It will generate a `key` if none has been specified (only applies to Key Authentication).
