### ISSUE TITLE
Deleting / Invalidating Access Tokens

### ISSUE THREAD

**Issue by givmefive5** [Mashape/kong#483]
Is there a way to delete access tokens? If an admin blocks a user account through an API, the API should also call a delete_access_token function in Kong, using the authenticated_user_id. 

This way, since Kong will immediately block all requests with an invalid token, only the login method in the API will need to check if the account is blocked or not before issuing a new access token.

**Comment by dirkmoors** [comment]
+1

**Comment by t1tcrucible** [comment]
In this case we delete the consumer credential or we update the ACL for the API.

**Comment by dirkmoors** [comment]
The idea is that a user could decide to revoke only HIS access tokens. In that case, we don't want to delete the consumer or change the ACL

**Comment by dirkmoors** [comment]
Also, the user should be able to revoke access tokens for a specific consumer (e.g. A malicious third party service)

**Comment by rafael** [comment]
:+1: . I think this could a pretty cool feature. Right now I'm thinking of a way to invalidate all access token for an user when he changes a password and a way to invalidate access token based on `authenticated_user_id` would be super handy.

**Comment by thefosk** [comment]
This will be released in 0.6.0, and the route would be `/oauth2_tokens/:id`. Methods supported are `GET`, `PATCH`, `DELETE`.

**Comment by thefosk** [comment]
Adding a note to myself to support `PUT`, and that will likely land into 0.6.1.

**Comment by rafael** [comment]
Nice!  :rocket:

**Comment by thefosk** [comment]
I confirm `PUT` support has been implemented and will land in 0.6.1

**Comment by sashahilton00** [comment]
Are there any plans to allow one to delete tokens through an endpoint that isn't the admin API (ie. one can access /oauth2/token and /oauth2/authorize on any api with OAuth enabled), yet it seems that it isn't possible to delete access/refresh tokens on a normal endpoint. Also, is it possible to delete based on authenticated_userid yet?
