### ISSUE TITLE
What is the difference between OpenResty and Kong？

### ISSUE THREAD

**Issue by thinkwing** [Mashape/kong#484]
All of OpenResty and Kong are based on nginx, and what is the difference between OpenResty and Kong？

**Comment by thefosk** [comment]
Hi @thinkwing - let me answer your question. Kong is built on top of OpenResty, and provides a system for easily applying extra functionality to backend services using a RESTful API interface. You can see the Plugins that it offers from the [Plugin Gallery](https://getkong.org/plugins/). Some of the extra functionality that Kong provides out of the box are rate-limiting, security and transformations.

By leveraging OpenResty, thus also nginx, Kong can be deployed like an nginx (or OpenResty) server. It leverages Cassandra as a datastore (with plans to support SQL) to keep eventually consistency in multi-datacenter or hybrid (cloud + bare metal) environments.

Kong can also be expanded with custom plugins (that leverage the OpenResty internals) to add more functionality. Let me know if you have any question.

**Comment by thinkwing** [comment]
Great project!

Hi, @thefosk, many thanks for your reply!!!

I have some questions below:
1. Because of building on top of OpenResty, also can be expanded with custom plugins (that leverage the OpenResty internals) to add more functionality, will Kong be compatible with OpenResty in the future?
2. Something about source layout, how about the Kong source code is organized? how to communicate with each independent layer?
3. Something about the datastore, is there an implementation of datastore abstraction layer, in order that we can add customizable datastore? (I want to add other NOSQL implementation, for instance, LevelDB  and Cayley, unfortunately, I don`t know how to start any more!) By the way, if no, is there a plan to  implement the datastore abstraction layer?

**Comment by thefosk** [comment]
> Because of building on top of OpenResty, also can be expanded with custom plugins (that leverage the OpenResty internals) to add more functionality, will Kong be compatible with OpenResty in the future?

Since Kong is built in OpenResty, and because it leverages the OpenResty internals, it will always be compatible with OpenResty.

> Something about source layout, how about the Kong source code is organized? How to communicate with each independent layer?

You can take a look at how the plugins have been built: https://github.com/Mashape/kong/tree/master/kong/plugins

> Something about the datastore, is there an implementation of datastore abstraction layer, in order that we can add customizable datastore? (I want to add other NOSQL implementation, for instance, LevelDB and Cayley, unfortunately, I don`t know how to start any more!) By the way, if no, is there a plan to implement the datastore abstraction layer?

We have plans to create a DAO reference after we introduce support for SQL.

**Comment by thefosk** [comment]
@thinkwing does this answer your questions?

**Comment by thinkwing** [comment]
@thefosk  Thanks！I see. I shall go into the architecture (source layout, being organized, ......). And I am  watching developments closely.

What a great project!

**Comment by thefosk** [comment]
Thanks! Let me know if you have more questions, I will close this issue now.
