### ISSUE TITLE
Add pluggable backend

### ISSUE THREAD

**Issue by thinkwing** [Mashape/kong#487]
If Kong runs with other NOSQL backend, for instance, LevelDB, MongoDB and Cayley, it would be great!

**Comment by thefosk** [comment]
We are planning to add support to SQL first #331, as Cassandra is already a NoSQL database. But pull requests for other implementations are welcomed :)

**Comment by majgis** [comment]
If we want to create a pull request for other implementations, do you have suggestions on how to get started?  What would you like to see?
