### ISSUE TITLE
Without scaling Kong horizontally, whether Cassandra is necessary or not?

### ISSUE THREAD

**Issue by thinkwing** [Mashape/kong#488]
I learned that Kong uses Cassandra for storing config, in order to run a Kong cluster. Then if we do not  scale Kong horizontally, whether Cassandra is necessary or not?

**Comment by thefosk** [comment]
Cassandra is still necessary to run Kong, with plans to also add support for PostgreSQL #331. You can use instaclustr.com to run a Cassandra cluster in the cloud.
