### ISSUE TITLE
Kong error response are not getting logged

### ISSUE THREAD

**Issue by tamizhgeek** [Mashape/kong#490]
When there is a error raised by other plugins, for example say ratelimiting, those are not logged in any of the log plugins. The stop_phases check fails and none of them get executed. I think we need to remove this check at least for the 'function _M.exec_plugins_log()'. Or add the log plugins to a special list, which will execute no matter what. Let me know your thoughts. Will be happy to contribute a patch.

**Comment by thibaultCha** [comment]
The logging plugins are for logs of the requests (successfully proxied). Check the Kong error file for kong logging.

**Comment by thefosk** [comment]
@tamizhgeek The Kong error file is the nginx error file, and if you are using Kong in the default working directory is should be located at `/usr/local/kong/logs/error.log`.

**Comment by tamizhgeek** [comment]
But, see the logging plugins are mostly used as a input for the analytics
systems. In analytics we would definitely want to know how much of requests
got ratelimited/quota exceeded. Won't it be good have them logged in the
plugins also?

**Comment by tamizhgeek** [comment]
@thefosk @thibaultCha any more comments on this?

**Comment by thefosk** [comment]
@tamizhgeek the initial reason why the rate-limiting plugins have logging disabled was because effectively if there is a DDOS attack and logging is enabled, that will DDOS also the logging output.

Maybe we could add a boolean flag `enable_log` when adding a rate-limiting plugin?

**Comment by jeevanrd** [comment]
@thefosk Any progress made on this?

**Comment by sinzone** [comment]
@tamizhgeek if all you need is "how much requests, etc" then you should use mashape analytics plugin for that.

**Comment by thefosk** [comment]
@sinzone, @tamizhgeek was asking for a different feature.

**Comment by ahmadnassri** [comment]
this is a valid issue and should not have been closed, now being tracked in https://github.com/Mashape/kong/issues/892

**Comment by amankumarjain** [comment]
How to log request payload and response body using any logging plugin or using some other way, is it allowed to do it?

**Comment by Tieske** [comment]
@amankumarjain please do not reply on closed issues, just accidentally caught this one. Please check the [gitter community channel](https://gitter.im/Mashape/kong) for questions like this.
