### ISSUE TITLE
Concurrent migrations caused by "kong start"

### ISSUE THREAD

**Issue by Gingonic** [Mashape/kong#491]
After restarting the official docker container Kong 0.4.2 seems to want to update Casandra. I haven't updated the version.

```
[INFO] Connecting to the database...
[ERR] Cassandra error: Cassandra returned error (Invalid): Invalid column name preserve_host because it conflicts with an existing column
```

My migration table looks like this :

```
 id         | migrations
------------+------------------------------------------------------------------------------------------------------------------------------
 migrations | ['2015-01-12-175310_init_schema', '2015-01-12-175310_init_schema', '2015-04-24-154530_plugins', '2015-04-24-154530_plugins']
```

**Comment by thibaultCha** [comment]
There is something very wrong with your `schema_migrations` table. If I believe the error, its content should be:

```
 id         | migrations
------------+-------------------------------------------------------------------------------------------------------------------------------------------------
 migrations | ['2015-01-12-175310_init_schema', '2015-04-24-154530_plugins', '2015-05-22-235608_0.3.0', '2015-06-09-170921_0.4.0', '2015-08-10-813213_0.4.2']
```

I don't know what went wrong during your previous installation/migrations to cause this. A way to fix it would be to execute the following queries with cqlsh:

```
DELETE FROM schema_migrations WHERE id = 'migrations';
INSERT INTO schema_migrations (id, migrations) VALUES('migrations', ['2015-01-12-175310_init_schema', '2015-04-24-154530_plugins', '2015-05-22-235608_0.3.0', '2015-06-09-170921_0.4.0', '2015-08-10-813213_0.4.2']);
```

Note that when 0.5.0 will be released, the schema changes will require that you run a python script to migrate your database, that will definitely be something to watch closely.

**Comment by Gingonic** [comment]
Thanks. The interesting thing is that I did not upgrade. The Kong instances were shutdown abruptly due to a scheduler glitch but were restarted on the same version.

I think I have an idea where the error might have originated from. We are using the Marathon  scheduler from Mesosphere with two instances. They get started at the same time on multiple machines. If there is a migration to be done both instances are competing to update the DB as they are doing this on start-up, this might explain the double entries in the migration table. I'm under the impression that the script is not thread safe. 

What do you think? A lock flag in the DB itself could prevent this behavior.

**Comment by thibaultCha** [comment]
Yes that is an issue we had with our AWS AMI and cloudformation distributions too. I always wanted the migration step to be manual `$ kong init && kong start` but having the migrations bundled in `kong start` is what was decided...

As for a lock in the DB, well I think it would only move the problem, what if the two instances create the lock at the same time?

Another solution I thought for this is to document this edgecase, explain to run the `$ kong migrations up` manually and then run `kong start --no-migrations`, and this flag prevents the command from running the migrations. I still think the first solution is cleaner and more common though...

**Comment by thefosk** [comment]
@thibaultCha any updates?

**Comment by hutchic** [comment]
Closing this as it's an old version of Kong and an old ticket. If the behaviour is still occurring open a new ticket
