### ISSUE TITLE
Dao error mechanism is error prone

### ISSUE THREAD

**Issue by Tieske** [Mashape/kong#499]
in `kong/dao/error.lua`

```lua
  local t = {
    is_dao_error = true,
    [err_type] = true,
    message = err
  }
````
the `[err_type] = true` line above is akward.
Creating an error of type `constants.DATABASE_ERROR_TYPES.DATABASE` for example can now be tested using `if my_error.database then ...` (the constants table defines the values as lowercase)
Shouldn't that be my_error.DATABASE (uppercase) as it is a constant, and make it explicit to the reader as such. 
But even then it violates DRY, the code is littered with magic values this way. The above exmaple uses 2 magic values per error type, `DATABASE` and `database` in this case.

Proposal:
Introduce a `type` field and then use `if my_error.type == constants.DATABASE_ERROR_TYPES.DATABASE then ...`

or shorter;
```lua
local dberrors = require("kong.constants").DATABASE_ERROR_TYPES

if my_error.type == dberrors.DATABASE then ...
```` 

This is more verbose, but less error prone when combined with an access check on constants.DATABASE_ERROR_TYPES. (a metatable that throws an error when accessing a non-existing key) This will quickly catch any typos in the magical values.

**Comment by thibaultCha** [comment]
My original thought too but @thefosk wanted it to contain a Boolean so that it could be less verbose.

**Comment by Tieske** [comment]
If you modify the error metatable and include a comparison method, I think we can reduce it further to;
```lua
local dberrors = require("kong.constants").DATABASE_ERROR_TYPES

if my_error == dberrors.DATABASE then ...
````
(maybe easier to make the error types tables with metatables in that case)

**Comment by Tieske** [comment]
no longer applicable
