### ISSUE TITLE
Plugins system

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#50]
Separate plugins from the core repo.

**Comment by thefosk** [comment]
This also requires separating the authentication plugins (query/basic/header) and the network log plugins (tcp/udp)

**Comment by thibaultCha** [comment]
Writing down the results of our recent discussions:

I think our best current option is to consider Kong not as a dependency, but as a requirement, like a container, the same way openresty is required for Kong.

If Kong is installed on the machine, we can require any of its tools (`require "kong.utils.timestamps") or use the global `dao_factory` (or accept a constructor with it) in the plugin's code or tests.

From there, our current solution is to sign official plugins to approve they are safe (as mentioned in #18) and users would install them with `luarocks`, and specify them in their `kong.yml` file along with needed properties if any.

**Comment by thefosk** [comment]
Plugins have been separated with #82 , but they are still living in the same repo. To separate them in a separate repo we need to move kong to luarocks as mentioned in #83.

**Comment by thibaultCha** [comment]
#93 Has a more descriptive comment of what is needed for plugins.
