### ISSUE TITLE
Whitelist and blacklist order in ACL and IP Restriction plugins

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#506]
Currently whitelisted elements have the precedence over blacklisted elements. There should be a plugin configuration property that allows to set the right behavior.

Also, implement a check so that the same element cannot be both whitelisted and blacklisted.

**Comment by lucamaraschi** [comment]
:+1:

**Comment by thefosk** [comment]
I think we should actually only support either `whitelist` or `blacklist`, but not both. Makes more sense to me. Having both is currently a design problem.
