### ISSUE TITLE
Error object; bug?

### ISSUE THREAD

**Issue by Tieske** [Mashape/kong#509]
Consider this code: https://github.com/Mashape/kong/blob/master/kong/tools/utils.lua#L81-L100 

Now if I do this;
```lua
local p = require("pl.pretty")

local e
e = add_error(e, "key1", "value1")
e = add_error(e, "key2", "value2")
p.dump(e)

e = add_error(e, "key1", "value3")
e = add_error(e, "key1", "value4")
p.dump(e)

e = add_error(e, "key1", "value5")
e = add_error(e, "key1", "value6")
p.dump(e)
````

I get a table with a lot of nested tables;
````
{
  key1 = {
    {
      {
        {
          "value1",
          "value3"
        },
        "value4"
      },
      "value5"
    },
    "value6"
  },
  key2 = "value2"
}
````

And I would have expected errors with the same keys in only one table;
````
{
  key1 = {
    "value1",
    "value3",
    "value4",
    "value5",
    "value6",
  },
  key2 = "value2"
}
````

So what is wrong; the code or my expectations?

**Comment by thibaultCha** [comment]
I have to admit the code of that function is rather weird. I believe the expectations are right, now we'll see if by changing it we break some tests or not

**Comment by Tieske** [comment]
I'll have a look at it once I get the testsuite to run locally.
