### ISSUE TITLE
Try to distribute a binary

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#51]
Let's try to use https://github.com/openresty/lua-nginx-module#statically-linking-pure-lua-modules and repackage openresty with Kong inside for the most popular platforms. This way we just have a binary to distribute: `kong` and we could run it via `/bin/kong-cli` for example.

Other platforms will just have to run the build process.

**Comment by thefosk** [comment]
@mschurenko is working on creating RPM and DEB packages that will improve the way Kong can be installed. We'll take this as the first step and investigate other ways of distributing the software including investigating binary releases.

Regarding installations of Kong though the RPM or DEB packages, should we move the configuration file to `/etc/kong.yml`and the output to `/var/log/kong/`? @thibaultCha @mschurenko

**Comment by thibaultCha** [comment]
With #88, there is no need to do this anymore since we simplified the install process to leverage luarocks and include a binary executable (lua script).
