### ISSUE TITLE
HTTP Token Auth Plugin

### ISSUE THREAD

**Issue by soulware** [Mashape/kong#511]
Wondering what would be involved in adding a plugin for HTTP Token Auth.

Basically passing the api_key along in the Authorization header like - 

    "Authorization: Token token=<api_key>"

Draft spec - http://tools.ietf.org/html/draft-hammer-http-token-auth-01

Example client - https://github.com/lostisland/faraday/blob/81f16593a0138ec58bb6f25e1c2804e91589662f/lib/faraday/connection.rb#L208

Seems like it would be very similar to the existing keyauth plugin (at least for the simple case).

**Comment by ahmadnassri** [comment]
[`draft-hammer-http-token-auth-01`](http://tools.ietf.org/html/draft-hammer-http-token-auth-01) is a dead spec, left in "draft" (background story behind it [here](http://hueniverse.com/2012/07/26/oauth-2-0-and-the-road-to-hell/))

the author gave up on it and moved on to create [Oz](http://hueniverse.com/2015/09/19/auth-to-see-the-wizard-or-i-wrote-an-oauth-replacement/)

**Comment by montdidier** [comment]
I would just like to point out the background story link doesn't actually discuss the background of that spec at all. It only discusses oauth, oauth2 and Oz. While the spec still is in draft it is not clear based on information presented here why the author abandoned it or even if fact that he has.
