### ISSUE TITLE
[request] JWT Plugin

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#519]
Support for [JSON Web Token](https://tools.ietf.org/html/rfc7519) authentication.

We had a try with #404, but never merged because we wanted to use lua-resty-jwt.

**Comment by lucamaraschi** [comment]
:+1:

**Comment by thibaultCha** [comment]
What is expected that this plugin do? Receive a JWT, validate it against a secret (one secret by user? If so users must also give their usernames in the claims) and forward the claims to the upstream API if valid? That seems very limited to me. Any other logic is application-dependant and cannot be reasonably integrated into Kong.

Let me know.

**Comment by sinzone** [comment]
@lucamaraschi @jasonmotylinski-dowjones @jerizm @thefosk ^

**Comment by lucamaraschi** [comment]
@sinzone the plugin looks great to me...I would also add the capability of generating a JWT token (issuer).
Can we also reference in the description of the plugin the associated [JWT standard](https://tools.ietf.org/html/rfc7519)?

**Comment by thibaultCha** [comment]
I don't think we can do everything the plugin does, only validating a JWT and forward it to upstream if valid. You would have to create secrets (just like the Basic auth plugin needs a password for each consumer) for each of your consumers. Also what do you mean by "generating a JWT token"?

**Comment by lucamaraschi** [comment]
@thibaultCha how do you see then a normal JWT flow from an app/web site perspective?

**Comment by thibaultCha** [comment]
A client would simply send a JWT signed with a secret retrieved by Kong, along with the username (eventually in the JWT claims) to Kong, and Kong would validate it. If it is valid, Kong forwards it to the upstream API, if not, Kong discards it. Again, if you have any other use cases, please share.

**Comment by lucamaraschi** [comment]
It makes sense to me.

**Comment by jerizm** [comment]
:+1: Sounds good to me @thibaultCha

**Comment by thibaultCha** [comment]
Ok, one JWT plugin coming right away then.

**Comment by thefosk** [comment]
JWT has been implemented, and available with 0.5.0 at https://getkong.org/plugins/jwt/
