### ISSUE TITLE
ability to create webhooks based on events in the system / plugins

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#520]
###### Scenarios

- trigger emails (in 3rd party system) based on plugin actions ratelimit / quota / billing
- trigger actions in API provider system / CRM based on events such as new consumer, update keys, etc ...

###### Behavior

- a plugin or perhaps a core system API endpoint
- custom callback url (anywhere on the network)
- send JSON data matching the action / plugin related details

**Comment by sinzone** [comment]
#326

**Comment by ahmadnassri** [comment]
I get its duplicate (search for "hook" didn't return anything at the time) but this one has better details than #326

**Comment by thibaultCha** [comment]
Then post your comment on 326.
