### ISSUE TITLE
Add ability to configure APIs using a config file

### ISSUE THREAD

**Issue by mingfang** [Mashape/kong#528]
Currently we can use the cli or REST api to configure APIs.
I need to be able to do the same but using a file, preferably JSON or YML.

**Comment by thibaultCha** [comment]
There is only REST to configure APIs right now. This is something I've been wanting too but as of today I am not sure it is worth the time and effort. The possible configurations might be too complex to be described easily in a simple file.

**Comment by gavinlove** [comment]
Hey @mingfang we had exactly the same problem so we have now released [Kongfig](https://github.com/mybuilder/kongfig) https://github.com/mybuilder/kongfig which does exactly what you want.

**Comment by thefosk** [comment]
Closing this since [kongfig](https://github.com/mybuilder/kongfig) already seems to provide a way of doing this.

**Comment by Maples7** [comment]
I've written a new CLI tool to manage the config with JSON files these days, you can have a try :D

https://github.com/Maples7/kong-config-manager

**Comment by thibaultcha** [comment]
@Maples7 Nice! Have you thought of maybe announcing that tool on our community mailing list?

**Comment by Maples7** [comment]
@thibaultcha Sounds good! I'll do that~ 😃
