### ISSUE TITLE
request_transformer not adding key:value to message body

### ISSUE THREAD

**Issue by bisoldi** [Mashape/kong#529]
I've setup two services, one I wrote in Java with an interceptor as well as a mockbin service, both of which show the insertion into the query string and header by the request_transformer.  I can't get confirmation that the insertion into the message body is taking place.  

The mockbin is located at:  http://www.mockbin.com/bin/e4dee421-0e16-482d-ba69-4b507bef3346/log

Below is my Kong configuration:

```bash
$ curl -X GET http://localhost:8001/apis
```

```json
{
  "data": [
    {
      "path": "\/mock",
      "target_url": "http:\/\/www.mockbin.com\/bin\/e4dee421-0e16-482d-ba69-4b507bef3346",
      "created_at": 1441216341000,
      "id": "07ecccc6-e7a2-494d-c95d-f4e8bcc436c9",
      "name": "mock",
      "strip_path": true
    }
  ]
}
```
```bash
$ curl -X GET http://localhost:8001/apis/mock/plugins
```

```json
{
  "data": [{
    "api_id": "07ecccc6-e7a2-494d-c95d-f4e8bcc436c9",
    "id": "5ea3f322-f77e-4dbf-cd7d-70a353089b1e",
    "value": {
      "add": {
        "querystring": ["testQueryStrKey:20u3ihf2ku1khe89"],
        "headers": ["testHeaderKey:20u3ihf2ku1khe89"],
        "form": ["testBodyKey:20u3ihf2ku1khe89"]
      }
    },
    "enabled": true,
    "name": "request_transformer",
    "created_at": 1441216373000
  }]
}
```
Below are the 3 commands I issued:

```bash
curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" http://localhost:8000/mock/ -d '{"name":"Mike"}'
```
```bash
curl -X GET -H "Content-Type: application/json" -H "Accept: application/json" http://localhost:8000/mock/
```
```bash
curl -X PUT -H "Content-Type: application/json" -H "Accept: application/json" http://localhost:8000/mock/ -d '{"name":"Mike"}'
```

**Comment by ahmadnassri** [comment]
@bisoldi seems like your example of the JSON output from `/apis` is duplicated, can you please update the ticket?

P.S. I cleaned up the formatting.

**Comment by ahmadnassri** [comment]
as for the actual issue, I just tested locally and reviewed your mockbin example, it seems you're sending an `application/json` content-type for the request ... which is the problem

the `request_transformer` plugin currently only supports Form Data (a.k.a content type of: `application/x-www-form-urlencoded`)

**Comment by bisoldi** [comment]
Thank you for the help with that.  I think it would be beneficial if the documentation for the plugin (likely the response transformer as well?) clearly stipulated that requirement.

**Comment by mashapedeployment** [comment]
@thefosk ^

**Comment by sinzone** [comment]
@thefosk ^

**Comment by ahmadnassri** [comment]
> Thank you for the help with that. I think it would be beneficial if the documentation for the plugin (likely the response transformer as well?) clearly stipulated that requirement.

agreed

**Comment by thefosk** [comment]
Closing this in favor of #569.
