### ISSUE TITLE
Attempt to call a nil value

### ISSUE THREAD

**Issue by dirkmoors** [Mashape/kong#532]
I'm running into an issue when running the latest build from source. Any idea where this could go wrong?

I've build Kong the same way I'm used to -via Docker:
https://github.com/vikingco/docker-kong

The output when starting the container (check the first line):
```
kong_1      | nginx: [error] [lua] init_by_lua:5: Startup error: /usr/local/share/lua/5.1/kong/dao/cassandra/plugins.lua:58: attempt to call a nil value
kong_1      | [INFO] Using configuration: /etc/kong/kong.yml
kong_1      | [INFO] Kong version.......0.4.2
kong_1      |        Proxy HTTP port....8000
kong_1      |        Proxy HTTPS port...8443
kong_1      |        Admin API port.....8001
kong_1      |        dnsmasq port.......8053
kong_1      |        Database...........cassandra keepalive=60000 timeout=1000 contact_points=cassandra:9042 keyspace=kong
kong_1      | [INFO] Connecting to the database...
kong_1      | [OK] core migrated up to: 2015-01-12-175310_skeleton
kong_1      | [OK] oauth2 migrated up to: 2015-08-03-132400_init_oauth2
kong_1      | [OK] oauth2 migrated up to: 2015-08-24-215800_cascade_delete_index
kong_1      | [OK] key-auth migrated up to: 2015-07-31-172400_init_keyauth
kong_1      | [OK] basic-auth migrated up to: 2015-08-03-132400_init_basicauth
kong_1      | [OK] rate-limiting migrated up to: 2015-08-03-132400_init_ratelimiting
kong_1      | [OK] response-ratelimiting migrated up to: 2015-08-03-132400_init_oauth2
kong_1      | [INFO] Auto-generating the default SSL certificate and key...
kong_1      | [INFO] dnsmasq started (dnsmasq)
kong_1      | [INFO] dnsmasq stopped
kong_1      | [ERR] Could not start Kong
```

**Comment by thibaultCha** [comment]
Similar to what @ahmadnassri experienced. Could never reproduce.

**Comment by dirkmoors** [comment]
Ok the way I install everything is like this:

```
set -x \
    && buildDeps="unzip wget build-essential make git-core ca-certificates" \
    && deps="netcat lua5.1 openssl libpcre3 dnsmasq sudo" \
    && apt-get update \
    && apt-get install -y ${buildDeps} ${deps} --no-install-recommends \
    && wget https://github.com/Mashape/kong/releases/download/0.4.2/kong-0.4.2.jessie_all.deb \
    && dpkg -i kong-0.4.2.*.deb \
    && rm -rf /etc/kong/ \
    && rm -rf kong-0.4.2.*.deb \
    && git clone https://github.com/Mashape/kong.git --branch master --single-branch --depth=1 \
    && cd kong/ \
    && make install \
    && apt-get purge -y --auto-remove ${buildDeps}
```

**Comment by thibaultCha** [comment]
I just ran those installation instructions on a fresh Docker image (Ubuntu 14.02) and did not run into any issue.

**Comment by dirkmoors** [comment]
That is so strange... could you please try to compile my Dockerfile (https://github.com/vikingco/docker-kong) and see if you get similar results?

Thank you in advance!

**Comment by thibaultCha** [comment]
Same, did not encounter any issue.

**Comment by dirkmoors** [comment]
I cannot explain how or why, but I've rebuilt, and now it works. Thanks for testing with me @thibaultCha

**Comment by thibaultCha** [comment]
I actually encountered this yesterday on Ubuntu too and spent most of my day trying to fix it. So far my feeling is that this is somehow related with Luarocks not handling properly and upgrade from 0.4.2 to 0.5.0. Really not sure but I had no success in tracking in down anyways.

**Comment by thibaultCha** [comment]
I might have found the cause. In my case it was because of a migration failing on 0.5.0 start (because I did not run the migration script first). Could it be that you were trying to run this 0.5.0 Kong under Docker on a 0.4.2 Cassandra cluster? The glitch was on a missing error reporting (as well as not running the migration script, of course).

**Comment by ahmadnassri** [comment]
yes, I had the same Cassandra instance running for `0.4.2` then I started `0.5.0` on it

**Comment by dirkmoors** [comment]
@thibaultCha Correct, I did the same; I'd installed 0.4.2 with the installer, and then I've started 0.5.0 (or at least, master branch from github) on it.

**Comment by thibaultCha** [comment]
The error message is now correct (table plugin does not exist). The "fix" is to run the migration script, as indicated in UPDATE.yml.
