### ISSUE TITLE
How do you delete an OAuth2 credential?

### ISSUE THREAD

**Issue by darkaeon10** [Mashape/kong#534]
I've already deleted all consumers, but when I create a new consumer and try to add the same credentials to it, Kong tells me the credentials already exist. So presumably this is due to previous credentials not being deleted. I've tried doing a DELETE on http://localhost:8001/consumers/consumer-id/oauth2 but it tells me method is not allowed. 

Any help would be greatly appreciated. Thanks!

P.S.
I think this is the same as #438, which I see has been closed 12 days ago. Does this mean the fix for this will be included in the next release?

**Comment by thibaultCha** [comment]
Yes, this is exactly #438 and will be included in the next release. For now, if you deleted your consumers, I can only advise to `cqlsh` into the Cassandra cluster and run:

```
TRUNCATE oauth2_tokens;
TRUNCATE oauth2_credentials;
TRUNCATE oauth2_authorization_codes;
``` 

You cannot delete entire collections at once hence why the DELETE method does not work on that endpoint. But that still wouldn't work, you'd have to run the statements I described.

**Comment by darkaeon10** [comment]
Ok thanks! Any estimate on when the next release would be @thibaultCha ? :)
