### ISSUE TITLE
Spawned processes under supervisord do not stop

### ISSUE THREAD

**Issue by mikesparr** [Mashape/kong#537]
Everything in our stack managed under supervisord including mysql using their pidproxy lib. Kong using luajit and nginx to start for some reason wont work. After restarting supervisord there are kong master process and children still running so restart fails. Oddly if I run `kong start` from command line and then `CTRL+C` and kill process the children all stop but if I run `command=kong start` from supervisord and restart the children remain running.

**supervisor config**
~~~
[program:kong]
command=kong start
stdout_logfile=/var/log/supervisor/kong.log
redirect_stderr=true
autostart=true
stopasgroup=true
stopsignal=KILL
;directory=
;environment=
~~~

**console shows processes still running after stop**
~~~
root      7481  6940  0 12:40 ?        00:00:00 /usr/local/bin/luajit -e package.path="/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;"..package.path; package.cpath="/usr/local/lib/lua/5.1/?.so;"..package.cpath -e local k,l,_=pcall(require,"luarocks.loader") _=k and l.add_context("kong","0.4.2-1") /usr/local/lib/luarocks/rocks/kong/0.4.2-1/bin/kong start
root      7518     1  0 12:40 ?        00:00:00 dnsmasq -p 8053 --pid-file=/usr/local/kong/dnsmasq.pid -N -o
root      7533  7481  0 12:40 ?        00:00:00 sh -c KONG_CONF=/etc/kong/kong.yml /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong/ -c nginx.conf -g 'pid kong.pid;' 
root      7534  7533  0 12:40 ?        00:00:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong/ -c nginx.conf -g pid kong.pid;
~~~

Is there perhaps a `stopsignal` other than `KILL` that might signal to stop children or some better way to start/stop Kong from command line so I can manage under supervisor?  Thanks!

**Comment by mikesparr** [comment]
I did edit the nginx conf for `daemon off` as well, fyi.

**Comment by mikesparr** [comment]
I changed `stopsignal=INT` and it appears to work now. I hope this helps others.

**Comment by thibaultCha** [comment]
FIY `daemon off` is an nginx directive that was intended for development only, and probably shouldn't be used in production.

**Comment by mikesparr** [comment]
Thanks @thibaultCha I will indeed try variations. Goal is to get every process managed under supervisor and lots of levers that we can tweak. One strategy I've seen is for people to add two commands to supervisor to start/stop services and let init scripts run them so that's always an option for nginx as well.

**Comment by mmonroe86** [comment]
@mikesparr  did this ever get resolved? Im experiencing the same issue
