### ISSUE TITLE
Api  Proxy and OAuth2 question

### ISSUE THREAD

**Issue by rafael** [Mashape/kong#540]
Hi, 

I'm starting to play with Kong and I'm trying to setup the proxy so it points to different backends depending on the path. Also, I would like some endpoints to require oauth2). Something like this

```
[Kong]/users (Authenticated by Oauth2) -> users-service 
[Kong]/purchases (Authenticated by Oauth2)  -> purchases-service
[Kong]/auth -> auth-service
```

I did something like this:

```
$ curl -i -X POST http://`docker-machine ip dev`:8001/apis  --data 'name=users-service'  --data 'target_url=http://192.168.0.103:3000/ops/status'  --data "path=/users" --data "strip_path=true"

$ curl -i -X POST http://`docker-machine ip dev`:8001/apis  --data 'name=purchases-service'  --data 'target_url=http://192.168.0.103:3000/ops/status'  --data "path=/purchases" --data "strip_path=true"

$curl -i -X POST http://`docker-machine ip dev`:8001/apis  --data 'name=auth-service'  --data 'target_url=http://192.168.0.103:3000/ops/status'  --data "path=/auth" --data "strip_path=true"
```

So far so good and I'm able to do the following:

```
$ curl -X GET https://`docker-machine ip dev`/users --insecure
{"status":"ok"}%        
$ curl -X GET https://`docker-machine ip dev`/purchases --insecure
{"status":"ok"}%
```

Now I would like to protect this endpoints with oauth2, but not sure how to do that in a way that applies to the whole domain. I'm trying to do this:

```
curl -i -X POST http://`docker-machine ip dev`:8001/apis/purchases-resource/plugins --data "name=oauth2" --data "value.scopes=app"   --data "value.mandatory
_scope=true" --data "value.enable_password_grant=true"

curl -i -X POST http://`docker-machine ip dev`:8001/apis/users-resource/plugins --data "name=oauth2" --data "value.scopes=app"   --data "value.mandatory
_scope=true" --data "value.enable_password_grant=true"
```

But then that creates this endpoint: 

```
curl -X POST  https://`docker-machine ip dev`/purchases/oauth2/token 
```

I would like to have something that works for both `users` and `purchases`: 
```
curl -X POST  https://`docker-machine ip dev`/oauth2/token 
```

Is this possible?

**Comment by thibaultCha** [comment]
No, that wouldn't be possible. Each plugin is applied to one and only one API. Having a better granularity is something we are planning on.

**Comment by rafael** [comment]
Oh I see. Thanks! But if I apply the oauth plugin to two endpoints, I can use the same token to authenticate to both right? This seems to work: 

```
$ curl -X POST  https://`docker-machine ip dev`/users/oauth2/token  --data "client_id=xxx" --data "client_secret=xxx" --data "scope=app"  --data "provision_key=xxx"  --data "username=XXX" --data "password=XXX" --data "grant_type=password"  --data "authenticated_userid=xasasda" --insecure
=> {"refresh_token":"47c6a3abc32c42f1c2ba27e4c5deb8b2","token_type":"bearer","access_token":"90e3fca9035646a8c68e296c0c5c79ef","expires_in":7200}

$ curl -X GET  https://`docker-machine ip dev`/users -H "Authorization: Bearer 90e3fca9035646a8c68e296c0c5c79ef"  --insecure
=> {"status":"ok"}%  

$ $ curl -X GET  https://`docker-machine ip dev`/purchases -H "Authorization: Bearer 90e3fca9035646a8c68e296c0c5c79ef"  --insecure                          <<<
=> {"status":"ok"}%     
```

**Comment by thibaultCha** [comment]
Yes, because they both use the same credentials table. But you still have to add them on both APIs as separate plugins (and interact with them via the endpoints you posted, not an endpoint that groups them).

**Comment by sambostock** [comment]
@thibaultcha Is this still the case, or has the OAuth2 support been extended to allow a global `/oauth/{authorize|token}` endpoint?

**Comment by sashahilton00** [comment]
bumping this. It would be nice to have a global endpoint that we could use, as the documentation is a bit vague leading to some confusion. (The use of http://your.api.com/oauth2/token had me going crazy for about 30 mins.) Also, since the plugin can be applied globally by a POST to /plugins, surely it stands to reason that we have a universal endpoint as well? Plus, it is also aesthetically nicer, as we currently have a bogus API in kong just to access the /oauth2/token endpoint for the resource owner grant, though this admittedly is unnecessary, and just a personal choice.

**Comment by beniwtv** [comment]
We just got bitten by this. This is one of the most basic things for an API wit OAuth2.

**Comment by Lube** [comment]
@sashahilton00  @beniwtv  in the password flow should you implement the /token endpoint outside kong? 
Should it pass through kong before hitting the authentication server?

**Comment by sashahilton00** [comment]
@Lube no it isn't necessary to have an API running behind it iirc. You could have a siple HTTP service that returns `200 OK` if you want but that's about it. Pinging @thibaultcha to request a review on this suggestion of having a universal API endpoint for oAuth 2 tokens.
