### ISSUE TITLE
Cassandra - Replication factor

### ISSUE THREAD

**Issue by jeevanrd** [Mashape/kong#545]
Currently I see the cassandra replication_factor is hardcoded to 1 in migrations. Doesn't it be dynamic?
My requirement is to set my custom replication_factor (>1) to achieve more consistency. Is there any way to configure it.

**Comment by thibaultCha** [comment]
You can simply create the keyspace manually with any option you want before running the migrations.

**Comment by thibaultCha** [comment]
Closing in favor of #543
