### ISSUE TITLE
API created with 'path' can not have a name

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#547]
```
$ http POST :8001/apis path=/mockbin upstream_url=http://mockbin.com
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Server: kong/0.5.0
Transfer-Encoding: chunked

{
    "created_at": 1442503117000,
    "id": "d96aaf1a-8d06-4ecc-cea4-9c21ac3da416",
    "path": "/mockbin",
    "upstream_url": "http://mockbin.com/"
}
```

**Comment by lucamaraschi** [comment]
:+1:

**Comment by thefosk** [comment]
This is in a way related to #489, because the easy fix for this would be to make `name = request_path`. Because the `request_path` contains slashes though, then we incur issue #489.

**Comment by thibaultCha** [comment]
In my implementation I replaces slashes (except the first one) by dashes. But that is not a problem anymore, consider this resolved, the real issue here is #489. Are we satisfied with forbidding reserved characters or do we want to allow them and deal with percent-encoded URI parameters?

**Comment by thefosk** [comment]
@thibaultCha i would forbid them, or slugify them

**Comment by thibaultCha** [comment]
That also means no more spaces.

**Comment by thefosk** [comment]
Slugifying parameters also brings some new issues:

* We need to make sure the slug is unique
* We need to make sure it gets updated every time the property is getting updated

Although slugs are the de-facto solution to this problems pretty much everywhere in the web.

I don't know. What's your idea on this issue?

**Comment by thibaultCha** [comment]
No, slugs have never been a solution for me because I think it is better to refuse a value if it contains invalid characters than unpredictably change them, which is a confusing experience.

However, when the name is **not** specified, and is taken from the `request_path`, it replaces slashes by dashes. That is my current implementation in a local branch.

**Comment by thefosk** [comment]
@thibaultCha so the following request_path: `/helloworld` becomes `-helloworld` ?

Makes sense to remove the first slash too maybe?

**Comment by thibaultCha** [comment]
Obviously, already done.

**Comment by thibaultCha** [comment]
See #560 for both those issues. If restricting characters in an API names is what we chose, then it is the fix. I believe it is reasonable.
