### ISSUE TITLE
Inconsistent error messages from DAO

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#55]
I expect DAO errors to be returned in the following form:

```lua
{
  database = true,
  message = "localhost could not be resolved (3: Host not found)"
}
```

But sometimes they show up in an inconsistent format, like: 

```lua
{
  database = true,
  message = {
    database = true,
    message = "localhost could not be resolved (3: Host not found)"
  }
}
```

This specific example can be replicated by setting an invalid IP address/host in the Cassandra `hosts` property, starting the server and making a request.

**Comment by thibaultCha** [comment]
I really can't reproduce this. Here is an attempt:

```lua
local inspect = require "inspect"

local new_factory = CassandraFactory({ hosts = "helloworld",
                                       port = 45678,
                                       timeout = 1000,
                                       keyspace = configuration.cassandra.keyspace
})

local err = new_factory:prepare()
print(inspect(err))

local api_t = faker:fake_entity("api")
local api, err = new_factory.apis:insert(api_t)
print(inspect(err))
```

It's just doing as currently expected, failing on prepare and throwing an error on insert:

```
{
  database = true,
  message = "host not found"
}
```

But since `main.lua` exits on a prepare error, I really don't understand how this can happen. Please provide a test to reproduce.

**Comment by thibaultCha** [comment]
Please try to reproduce against master.

**Comment by thefosk** [comment]
I'm not getting 

```
 [lua] init_by_lua:5: Startup error: host not found
```

Can't reproduce.
