### ISSUE TITLE
Possible strategic partnership?

### ISSUE THREAD

**Issue by brylie** [Mashape/kong#552]
We are collaborating on an API proxy solution and notice a bit of duplication among several projects. While diversity seems good to promote evolution, our projects may be developing very similar features. Would you please join us in a [discussion about how open-source API proxy solutions can coordinate efforts](https://github.com/NREL/api-umbrella/issues/159), so that we effectively use our time and energies.

**Comment by ahmadnassri** [comment]
followed up on the discussion thread. happy to discuss ideas.
