### ISSUE TITLE
Listing enabled plugins

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/kong#56]
So I have three plugins enabled but they don't show up when I query `/plugins/`

![screen shot 2015-03-04 at 2 48 36 am](https://cloud.githubusercontent.com/assets/24260/6497984/73049784-c29b-11e4-935d-7c95d0166ef7.png)

![screen shot 2015-03-04 at 2 54 29 am](https://cloud.githubusercontent.com/assets/24260/6497959/4c5e219a-c29b-11e4-89c7-16608999a5f5.png)

**Comment by thibaultCha** [comment]
`/plugins/` is not for enabled plugins but for created plugins (from `curl`)

**Comment by thibaultCha** [comment]
You should see a list of enabled plugins on `/` (soon)

**Comment by thibaultCha** [comment]
It's actually more `plugins_installed` than `plugins_enabled`

**Comment by montanaflynn** [comment]
The doc for that endpoint just says "List Plugins" which could be elaborated upon.

**Comment by thefosk** [comment]
It's more like `plugins_available`, will make sure to change that.
