### ISSUE TITLE
Request transformations for JSON payloads

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#569]
Support modifying JSON payloads, by removing or adding JSON elements. This feature could also support dot-notation to add a JSON key to another JSON's key value.

**Comment by cgarvis** [comment]
:+1:

**Comment by thefosk** [comment]
We should also update the documentation at https://github.com/Mashape/getkong.org/blob/master/app/plugins/request-transformer.md

**Comment by thibaultCha** [comment]
Closing because implemented and soon to be released in 0.6.0 stable.

**Comment by Diwann** [comment]
> This feature could also support dot-notation to add a JSON key to another JSON's key value. 
Hi, just to check: how can I modify or delete a JSON subkey? for example, if I want to remove a property of a dictionary?

**Comment by jeremyjpj0916** [comment]
> Hi, just to check: how can I modify or delete a JSON subkey? for example, if I want to remove a 
property of a dictionary?

I am trying to work in this in lua, but I am brand new to the language so its tougher on me than normal hah.
