### ISSUE TITLE
Replace openresty server header with kong

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/kong#57]
It would be good to return the server header with kong and it's version from the admin API. Currently it's showing openresty.

![screen shot 2015-03-04 at 6 24 06 pm](https://cloud.githubusercontent.com/assets/24260/6498031/d5a5c386-c29b-11e4-91fa-338717e20a52.png)

**Comment by thefosk** [comment]
Closed with ae84a6c2da1376e34e865615ae877f4d3a7316b0
