### ISSUE TITLE
Support for HTTP/2

### ISSUE THREAD

**Issue by sinzone** [Mashape/kong#574]

**Comment by thibaultCha** [comment]
https://github.com/openresty/lua-nginx-module/issues/566

**Comment by ybv** [comment]
+1

**Comment by thibaultCha** [comment]
Not related to Kong.

**Comment by thefosk** [comment]
This has been implemented in:

* Distribution scripts: https://github.com/Mashape/kong-distributions/commit/5ca1bdd67e46587146f6669ae509c867806555dd
* Kong: #2540 and #2541
