### ISSUE TITLE
Replace default error responses

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/kong#58]
The 500 error response returns an html page, it should be JSON. There's probably other default error pages that nginx may serve that should be converted as well.

![screen shot 2015-03-04 at 10 32 56 pm](https://cloud.githubusercontent.com/assets/24260/6500283/77049d98-c2be-11e4-8a2f-b30ec93d43e9.png)

**Comment by thefosk** [comment]
This has been closed with f818bd49f24afd9b590dd2e90989e0e1c659e1f5
