### ISSUE TITLE
rename mashape analytics to galileo

### ISSUE THREAD

**Issue by sinzone** [Mashape/kong#583]

**Comment by thibaultCha** [comment]
Renaming plugins is a very expansive and painful operations. We should give them an id or something and the name should not have any particular meaning in the code. Same for the `plugins_available` configuration property. cc @thefosk

**Comment by thefosk** [comment]
Yes - although in this specific case we can simply fix this by using Galileo in the website, and then just keep `mashape-analytics` in the `kong.yml` file.
