### ISSUE TITLE
Link "Configuring Kong" is broken in README.md

### ISSUE THREAD

**Issue by debraj-manna** [Mashape/kong#586]
The link [Configuring Kong](http://rotlogix.com/2015/06/18/configuring-kong-for-a-services-layer/) is broken, under [Community Resources & Tools](https://github.com/mashape/kong#community-resources-and-tools) in README.md.

**Comment by sinzone** [comment]
Interesting. It was a valid post last week. Will ping the owner.

**Comment by debraj-manna** [comment]
Thanks Augusto.
