### ISSUE TITLE
HTTP status code mismatch in docs when using key-auth plugin

### ISSUE THREAD

**Issue by ybv** [Mashape/kong#587]
Environment:
Ubuntu 14.04
Kong: 0.5.0

Newbie to kong land! 
I was following the getting started [guide](https://getkong.org/docs/0.5.x/getting-started/enabling-plugins/) with key-auth plugin. I added the plugin, and requested mockbin api without auth data in the header, the docs say I should be getting a 403 Forbidden, but it actually is 401 Unauthorized, which indeed was the response from the server, I believe the docs should be updated? 
Also, [this](http://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses?answertab=votes#tab-top) says a 401 will always include a ` WWW-Authenticate` header, how strictly does kong (or its plugins) follow these conventions?

**Comment by thibaultCha** [comment]
Thanks, updates. Kong does not send a WWW-Authenticate header.
