### ISSUE TITLE
Kong fails to process path based routing rquests immediately after adding an API

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#592]
- add an API profile using `request_path`
- attempt to make a request to proxy port using the path specified
- Kong fails to respond with the message `API not found with these values`
- after a while (a few seconds) the request seems to go through *(seems to be cache related?)*

![image](https://cloud.githubusercontent.com/assets/183195/10292062/ecbbc1dc-6b61-11e5-82d3-0d833596cad1.png)

**Comment by thibaultCha** [comment]
This is the expected behavior until #15 is implemented.
