### ISSUE TITLE
Kong: Updating Plugin Configuration

### ISSUE THREAD

**Issue by sebicas** [Mashape/kong#595]
I am trying to update the 'key-auth' plugin configuration "config.hide_credentials' value, by POSTing to http://kong:8001/apis/{api}/plugins

But I keep getting:

```
{
  "message" : "Plugin configuration already exists"
}
```

Also tried DELETE, PATCH, PUT but I get:

```
{
  "message" : "Method not allowed"
}
```

Could you please tell me how can I update the plugin configuration?

**Comment by thibaultCha** [comment]
What is the request you are making?

**Comment by sebicas** [comment]
@thibaultCha I am doing this:

```
curl -X POST http://kong:8001/apis/{api}/plugins \
    --data "name=key-auth&config.hide_credentials=true"
```

**Comment by thibaultCha** [comment]
The Admin API is a REST API. If you POST, then you are asking to create an entity. You need to use PUT, and thus give the id, or PATCH and use another route. See the [docs](https://getkong.org/docs/0.5.x/admin-api/).

**Comment by sebicas** [comment]
@thibaultCha thanks!
```
curl -X PATCH http://kong:8001/plugins/{plugin id} \
   --data "config.hide_credentials=true"
```

Did it!
