### ISSUE TITLE
Kong - 0.5.0: Creating hmac failing because no hmac table

### ISSUE THREAD

**Issue by maheshoml** [Mashape/kong#598]
Error: `24123#0: *134 [lua] responses.lua:61: handler(): Cassandra error: Error during UNIQUE check: Cassandra error: Failed to prepare statement: "SELECT * FROM hmacauth_credentials WHERE username = ?". Cassandra returned error (Invalid): unconfigured table hmacauth_credentials`

Installation Source: using AWS cloudformation.
Action: Trying to create credentials for a user

**Comment by maheshoml** [comment]
Manually creating the tables from the Cassandra CLI works.

**Comment by shashiranjan84** [comment]
@maheshoml  would you please share the CF information like which template and parameters values like how many cassandra nodes and kong nodes did you choose?
