### ISSUE TITLE
hmac-auth returning 403 always

### ISSUE THREAD

**Issue by maheshoml** [Mashape/kong#599]
I am trying to get Kong - hmac-auth to work, I am prototyping with this node.js client

```javascript
var fs = require('fs');
var http = require('http');
var httpSignature = require('http-signature');


var options = {
  host: my_host,
  path: my_path,
  method: 'GET',
  headers: {
    'Content-Type': 'application/json'
  }
};

// Adds a 'Date' header in, signs it, and adds the
// 'Authorization' header in.
var req = http.request(options, function(res) {
  console.log(res.statusCode);
  res.setEncoding('utf8');
  res.on('data', function(d) {
    console.log(d);
  });
});


httpSignature.sign(req, {
  key: my_kong_consumer_secret,
  keyId: my_kong_consumer_username,
  algorithm: 'hmac-sha1'
});

req.end();
```

I get always get 403 from the Kong end point. And the same when using the following python script:

```python
import requests
from httpsig.requests_auth import HTTPSignatureAuth

test_data = {}
username = my_kong_consumer_username
test_headers = {
    'Content-Type': 'application/json',
    'Host': default_host,
    'Date': formatdate(timeval=None, localtime=False, usegmt=True),
}
auth = HTTPSignatureAuth(secret=my_kong_consumer_secret, key_id=username, 
        algorithm='hmac-sha1', headers=test_headers)
res = requests.post(proxy_url, auth=auth, json=test_data, headers=test_headers)
print(res.json())
```

Documentation lacks any example of how to generate the signature and only points to the  draft-cavage-http-signatures-00 document.

A definite example of generating signature would be helpful.

**Comment by radioverve** [comment]
By the looks of it, the node lib creates an Authentication header in this format 

'Signature keyId="%s",algorithm="%s",headers="%s",signature="%s"';

And Kong seems to expect it in this format

"\\s*[Hh]mac\\s*username=\"(.+)\",\\s*algorithm=\"(.+)\",\\s*headers=\"(.+)\",\\s*signature=\"(.+)\""

I found an other plugin which did it in a completely different manner. So not sure, which approach is best here.

**Comment by shashiranjan84** [comment]
sorry for inconvenience,  i just noticed that some of the info missing in doc. we will update it soon.
basically you supposed to set the authentication header in following format. let say i am using date header and content-md5 header

hmac username="bob",  algorithm="hmac-sha1",   headers="date",  signature="digest"

digest=base64_encode(hmac_sha1_binary(secret, signature_string))

signature_string =  "date: " + <date value in gmt> + "\n" + "content-md5" + <content-md5>

**Comment by sinzone** [comment]
having an example like we did with OAuth2 plugin is a good idea.

**Comment by shashiranjan84** [comment]
I already updated the doc with an example. Just need to be reviewed by
marco and deployed.

**Comment by shashiranjan84** [comment]
@maheshoml Site has been updated with HMAC specs.

**Comment by isanjaykp** [comment]
I  am getting 403  error  when I make hmac post request and I also see line "RequestProxyAuthentication:88 - Proxy auth state: UNCHALLENGED" . Is anything wrong with kong ?  Any pointer ?

**Comment by shashiranjan84** [comment]
@isanjaykp can't say much from the data you provided except Authorization header value would be something like this .

`Authorization: hmac username="XXXX", algorithm="hmac-sha1", headers="date content-md5", signature= "[B@23065e8"`

Note: order is important

**Comment by isanjaykp** [comment]
I am getting error like **HMAC signature cannot be verified, a valid date or x-date header is required for HMAC Authentication**

Here is the date format  **date: Fri, 10 Jun 2016 06:39:57 GMT**

And also configured  **config.clock_skew=3000000000000**  

still no luck ;)

How can I print all the headers at kong error log  ?  I have already enabled log level to debug. Still I can't see detail logs , it shows very high level log.

**Comment by isanjaykp** [comment]
This is  working now. Apart from adding signature Authentication headers , need to add date and content-md5 headers also, otherwise it returns 403 .
