### ISSUE TITLE
Sending a wrong username results in an exception in auth-hmac plugin

### ISSUE THREAD

**Issue by radioverve** [Mashape/kong#600]
If a wrong username is sent as a part of the Authorization header, an exception occurs. Ideally this should just throw unauthorised since we should not be leaking the fact that such a username does not exist. 

stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/plugins/hmac-auth/access.lua: in function 'execute'
	/usr/local/share/lua/5.1/kong/plugins/hmac-auth/handler.lua:14: in function 'access'
	/usr/local/share/lua/5.1/kong.lua:191: in function 'exec_plugins_access'
	access_by_lua(nginx.conf:89):1: in function <access_by_lua(nginx.conf:89):1>, client: 203.192.239.8, server: _, request: "GET /transaction/redeemInventory HTTP/1.1", host: "gateway.insider.in"
2015/10/08 19:53:33 [error] 25512#0: *354 [lua] responses.lua:61: send_HTTP_INTERNAL_SERVER_ERROR(): An unexpected error occurred, client: 203.192.239.8, server: _, request: "GET /transaction/redeemInventory HTTP/1.1", host: "gateway.insider.in"
2015/10/08 19:58:57 [error] 25512#0: *397 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/plugins/hmac-auth/access.lua:157: attempt to index local 'secret' (a nil value)

**Comment by shashiranjan84** [comment]
@radioverve I found the issue. Got it fixed, will merge soon. 

Returning 403 for internal error would be misleading for the client but I also agree with you to limit the info.
