### ISSUE TITLE
GET /consumers fails when username is UUID

### ISSUE THREAD

**Issue by maheshoml** [Mashape/kong#603]
TRY:
``` HTML
<!-- 123e4567-e89b-12d3-a456-426655440000 is Username -->
GET /consumers/123e4567-e89b-12d3-a456-426655440000
<!-- Fails with 404 -->
```

I think it is happening because the internal `id` field for consumer is itself a UUID.

**Comment by thibaultCha** [comment]
The username value should not contain a uuid, see the discussion here: https://groups.google.com/forum/m/#!topic/konglayer/2cbfHnm2drY
