### ISSUE TITLE
Loggly integration

### ISSUE THREAD

**Issue by sinzone** [Mashape/kong#604]

**Comment by rafaelspecta** [comment]
Any news on this? Seems very interesting the possibility of this integration.

**Comment by vmercierfr** [comment]
For our usage, we use the file log plugin (https://getkong.org/plugins/file-log) and we send logs to Loggly with Logstash (https://www.elastic.co/products/logstash) via the Loggly's plugin (https://www.loggly.com/docs/logstash-logs).

It works very well and we use logstash to pre-process logs (hash the API keys, add geo IP information, ...).

Example of configuration:

    filter {
        if [type] == "kong" {
            # Set the timestamp
            date {
                locale => "en"
                timezone => "UTC"
                match => [ "[kong][started_at]", "UNIX_MS" ]
                target => "timestamp"
            }

            # Anonymize API keys
            anonymize {
                algorithm => "SHA256"
                fields => ["[kong][authenticated_entity][key]", "[kong][request][headers][apikey]"]
                key => '<your_hashing_key>'
            }
            # Remove raw message due to API keys in the message
            mutate {
                replace => [ "message", "This field was cleaned due to API keys" ]
            }

            # Extend client_ip information
            geoip {
                source => "[kong][client_ip]"
                target => "geoip"
                database => "/etc/logstash/GeoLiteCity.dat"
                add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
                add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
            }
        }
    }

    output {
        # Send logs to loggly
        loggly {
            key => "<your_loggly_key>"
            proto => "http"
            tag => "%{type}"
        }
    }

**Comment by thibaultCha** [comment]
@rafaelspecta A Loggly plugin was implemented in #698, and should be available in the next major release. We are thinking about doing an RC release very soon.

**Comment by rafaelspecta** [comment]
@vmercierfr thanks, @thibaultCha great and is there an ongoing changelog for this next RC ?

**Comment by thibaultCha** [comment]
The [Changelog (in next)](https://github.com/Mashape/kong/blob/next/CHANGELOG.md#unreleased) has an "unreleased" section but it is still incomplete for now. It is missing changelog for clustering, new cassandra driver and configuration file changes. A look at the commits added between `0.5.4` and `next` (by clicking on "Unreleased" will give you a better idea (but no complete either as everything is not merged in `next` yet).

**Comment by thefosk** [comment]
Implemented in 0.6.0
