### ISSUE TITLE
cross-service document population

### ISSUE THREAD

**Issue by jtmarmon** [Mashape/kong#621]
A common feature for api gateways sitting in front of microservices, as kong is for us, is to handle aggregating data from multiple sources to return to the client in one API call.

I wonder if there's a generic way one could describe document populations so that kong can do so automatically.

For example, you might use the following json to describe a cross-service population for the orders service

```javascript
{"product_id": "/products@response.products.id"}
```
This would go through all `product_id` in the orders response if it's an array, or take the `product_id` key if it's a map, and send it to `/products` (copying all request headers so it looks like it's made by the same user), joining the two responses on `orders.product_id=response.products.id`

Obviously nuances need to be works out in the design like handling more edge cases, allowing custom manipulation of the response data, and handling different structures (like nested arrays or nested objects or arrays nested within objects) but it'd be quite valuable for us. For the time being we're just doing the joins at the service level but they should really be handled by the gateway to keep everything clean.

**Comment by sinzone** [comment]
have you look at this one: https://github.com/Mashape/kong/issues/155

**Comment by thibaultCha** [comment]
Closing since it duplicates an already opened issue.
