### ISSUE TITLE
[hmac-auth] handle X-Date header for browsers

### ISSUE THREAD

**Issue by radioverve** [Mashape/kong#641]
We are trying to write a Single Page browser app which authenticates with Kong using the HMAC signature. The problem is xmlHttpRequest on the browser does not allow setDate header (security issue). To get around this, it probably makes sense for the plugin to handle the X-Date header instead which can be set across different platforms.

**Comment by shashiranjan84** [comment]
@radioverve `date` header is only required for skew purpose, you can use other headers to create hmac signature. So assuming browser itself sets the date header, it should not be a problem

**Comment by neeharv** [comment]
@shashiranjan84 just tested this out on Chrome and FF, the browser *does not* add a `date` header. This breaks HMAC auth, as expected. Any thoughts as to how we can get around this?

**Comment by shashiranjan84** [comment]
@radioverve @neeharv yes chrome terminates XHR if date is included. I'll update the plugin to check `x-kong-date` or `date` header for date value. wait for ETA

**Comment by thibaultCha** [comment]
Maybe X-Date as suggested by @neeharv is better.

**Comment by shashiranjan84** [comment]
@thibaultCha sure, that sounds more transparent.

**Comment by thibaultCha** [comment]
Merged, a patch version of Kong is incoming.
