### ISSUE TITLE
[oauth2] Make ssl optional

### ISSUE THREAD

**Issue by PGBI** [Mashape/kong#646]
The oauth2 plugin requires to have the ssl one installed. Which is perfectly understandable since the oauth2 specs require communication to be made through [TLS](https://tools.ietf.org/html/rfc6749#section-1.6).

However, in the company I work for, we have several kong instances behind a load balancer. Communications between the API consumers and the load balancer are secured. But within our internal network, communications are not encrypted. As a result, I can not implement the oauth2 plugin.

I would like to add a parameter to the endpoint `POST http://kong:8001/apis/{api}/plugins` when creating the oauth2 plugin that would be called `config.require_ssl`. This parameter would be optional and defaulted to true. I would be glad to prepare a pull request for that. But before doing so, I just want to check with you if such a request would be approved on your side.

**Comment by PGBI** [comment]
By the way, our load balancers on aws add the following header when transmitting an ssl request to kong:
`X_FORWARDED_PROTO https`.

Maybe a better way of doing would be to check this header, and not only the request scheme in the `is_https()` function?
https://github.com/Mashape/kong/blob/master/kong/plugins/oauth2/access.lua#L79

**Comment by thefosk** [comment]
This has been closed by #650.
