### ISSUE TITLE
Broken links on download page

### ISSUE THREAD

**Issue by Nijikokun** [Mashape/kong#65]
None of the links in the section above the newsletter box work.
Log history link doesn't work either.

**Comment by thefosk** [comment]
We are aware of this problem, the website is still a work in progress and this functionality will be implemented before the release of the next version.

**Comment by thefosk** [comment]
In the meanwhile we put an alert bar: 

![screen shot 2015-03-17 at 3 57 09 pm](https://cloud.githubusercontent.com/assets/964813/6699335/4b968fc2-ccbe-11e4-89d6-e4836ee139e4.png)

**Comment by thibaultCha** [comment]
The whole download page is not redacted, the docs too, a lot of the text. Mhhhh I'm going to close this issue and since the website is such a general WIP, advise to discuss about things on #5
