### ISSUE TITLE
Securing Kong from unauthorized users

### ISSUE THREAD

**Issue by mavencode01** [Mashape/kong#668]
Am looking into Kong now, really interesting but am wondering how do I secure Kong access to prevent unauthorized access ?

**Comment by thibaultCha** [comment]
Which part of Kong is your question about? Securing access to the APIs you are proxying through Kong (default port `3000`) or securing the Admin API (default port `8001`)?

**Comment by mavencode01** [comment]
I'm talking about the admin API (default port 8001)

**Comment by thibaultCha** [comment]
You have different ways of doing so:

- Firewall
- Looping through Kong
- Editing the nginx configuration

All 3 are described in details in the Google groups [here](https://groups.google.com/forum/#!topic/konglayer/UpwtWHH_dTc) and [here](https://groups.google.com/forum/#!topic/konglayer/veIk6o-UXuY).

In the future we shall make plugins applicable to the Admin API too (such as authentication ones).

**Comment by p0pr0ck5** [comment]
We have published a doc that highlights some of the best practices we suggest when considering securing the Admin API: https://getkong.org/docs/0.10.x/secure-admin-api/
