### ISSUE TITLE
Kong user management

### ISSUE THREAD

**Issue by mavencode01** [Mashape/kong#670]
I'm trying to get my head wrap around Kong and wondering how I would tie in my users 
with Kong API management.

For example, I wanna use Kong authentication plugin to authenticate my users in my database.

How would I go about this ?

Do I have to map each of my users as consumer in Kong ? If that's the case, when user
signs up on my website via my API, Do I have to also create a corresponding consumer in Kong ????

Please explain how this would work - thanks

**Comment by thibaultCha** [comment]
Yes, that is how one would proceed. Provisioning will soon be added as for example discussed in #685.
