### ISSUE TITLE
configurable consistency level

### ISSUE THREAD

**Issue by smanolache** [Mashape/kong#671]
Hello,
I've tried to modify the code in order to use a configurable consistency level when issuing requests to cassandra.

I've decided to modify directly in kong/dao/cassandra/base_dao.lua, in the BaseDao:_execute function. The patch is quite simple and listed below:
```lua
  if not options then
     if self._properties.consistency_level then
	options = {
	   consistency_level = self._properties.consistency_level
	}
     else
	options = {
	   consistency_level = cassandra_constants.consistency.LOCAL_QUORUM
	}
     end
  elseif not options.consistency_level then
     if self._properties.consistency_level then
	options.consistency_level = self._properties.consistency_level
     else
	options.consistency_level = cassandra_constants.consistency.LOCAL_QUORUM
     end
  end
```
However, there's a problem. When auto_paging is on (which is the default) then cassandra/session.lua ignores the options passed to `session.execute` and hard-codes some options (see session:execute and session:page_iterator in cassandra/session.lua). Therefore, I would need to change cassandra/session.lua too, but this file is not part of kong but of lua-cassandra.

What would you suggest in this case? Would you accept the patch to kong? Should I ask for a patch to lua-cassandra? Are you related to the team that maintains lua-cassandra?

Thank you,
Sorin

**Comment by thibaultCha** [comment]
I would see this option rather being set in the Cassandra factory `get_session_options`. However `auto_paging` is not the default. Is your problem due to when `auto_paging` is enabled, `page_iterator` *overrides* the options? I just noticed this [here](https://github.com/thibaultCha/lua-cassandra/blob/master/src/cassandra/session.lua#L228).

**Comment by smanolache** [comment]
Thanks for the tip. Yes, `get_session_options` definitely looks the better solution.

When I tested my patch I used a trivial http request that triggers the `select * from apis` query in dao/cassandra/apis.lua. That query has `{auto_paging=true}` hard-coded.

Yes, my problem comes from the fact the `page_iterator` overrides the options when `auto_paging` is enabled. So, either there's a reason why `page_iterator` overrides the options (instead of merging them or selectively overriding) and its logic would break if we added the consistency level to the options that `page_iterator` passes to `session.execute`; or `auto_paging` must not be used if I want configurable consistency levels; or `page_iterator` must be modified. Obviously I prefer the latter.

**Comment by thibaultCha** [comment]
No, that just seem like a bug in the [cassandra driver](https://github.com/thibaultCha/lua-cassandra) :) or at least an unsupported feature. It should be easily fixable on the driver itself (I will accept a PR).

**Comment by thibaultCha** [comment]
PS: I have to add, it probably won't be released before the driver rewrite (#660), so you'll have to install your own version of the driver for some time. But I will make sure that this is supported in future versions.

**Comment by smanolache** [comment]
I've tried to add the consistency_level options in `get_session_options` as you suggested. I didn't get the desired effect. `get_session_options` is used in `session:connect` exclusively. The options are not stored in some member of the `session` object in order to be reused in `session:execute`. Thus query execution does not use the options initialised by `get_session_options`.
I realise that it is rather inelegant to set the options in `BaseDao:_execute` but I'll stick to this solution for the time being.

**Comment by thibaultCha** [comment]
Ah right

**Comment by smanolache** [comment]
Do you want me to create a pull request with the patch shown in the first message of this thread, knowing that it won't work without the modification in `lua-cassandra`, `cassandra/session.lua`?

**Comment by thibaultCha** [comment]
Sure, a patch for both would be welcome.

`self._properties.consistency_level` can also be enforced from the `config_defaults.lua` file in the `next` branch.

**Comment by smanolache** [comment]
Created a pull request

**Comment by thibaultCha** [comment]
Closed since made obsolete by the new driver. Sorry!
