### ISSUE TITLE
Issue with Sub URLS in Domain Name settings

### ISSUE THREAD

**Issue by incubator235** [Mashape/kong#673]
I have hosted an Kong Gateway application in one of our server which gives us an output url with a public IP  111.92.xx.xx

http://111.92.xx.xx:8000

And i have different sub urls like

http://111.92.xx.xx:8000/ABC
http://111.92.xx.xx:8000/ABC?find={bla,bla,bla}
http://111.92.xx.xx:8000/XYZ/findOne?access_token=ksdgasdgausygdasj     etc

This working fine and accessible everywhere.

Now i want to add a domain name for my ip "111.92.xx.xx:8000"

then may be my urls will be

http://exmaple.com

and

http://exmaple.com/ABC
http://exmaple.com/ABC?find={bla,bla,bla}
http://exmaple.com/XYZ/findOne?access_token=ksdgasdgausygdasj

I have checked with my network admin and added the DNS settings for this but now i can only able to access the main url like this "http://exmaple.com:8000"

And I can't able to to access the sub URLs,  I am getting the errors like {"request_path":"\/XYZ\/findOne","message":"API not found with these values","request_host":["example.com"]}

If i need to access the Sub URLs i need to pass the Host header like "Host: 111.92.xx.xx".

We have tried different options in DNS settings like URL Redirect, Adding A or CNAME record... but still it is not working

So how to resolve this issue? Is it some thing that we can do in DNS settings or in myserver i have to make some changes?

**Comment by thibaultCha** [comment]
Have you read the [proxy docs](https://getkong.org/docs/latest/proxy/)?
