### ISSUE TITLE
Allow admin server to be deployed separately from the proxy server

### ISSUE THREAD

**Issue by dcberg** [Mashape/kong#680]
I would like to separate the admin server from the proxy server to allow them to be scaled independently. I also have a desire to isolate the management of the cassandra db and want to avoid direct access from the proxy server. Enabling the separation of the admin server from the proxy server would be a key enabler for this scenario.

**Comment by thefosk** [comment]
@dcberg can you achieve this isolation by having a firewall rule that prevents accessing the admin API from untrusted sources? As for scaling, the Admin API is very lightweight and scaling it independently from the proxy server is not necessary imho.

Thoughts?

**Comment by Tieske** [comment]
Kong is a cluster of nodes, each providing the proxy capability as well as the admin api. As both need to be redundant in an infrastructure it does not make sense to disentangle the two. From a functional perspective this sounds reasonable, but practically it would be easier to shield the admin port from access, or protect it (several issues/requests on that). Considering the effort involved in splitting the two, I won't see this happening.

hence closing this.
