### ISSUE TITLE
Hook / Event System

### ISSUE THREAD

**Issue by nijikokun** [Mashape/kong#690]
Would provide an ample and powerful solution to many outstanding issues including #682 and #338 by having hooks / events that plugins can register functions on for listening or actionable purposes.

**Hook Examples**

- `PLUGIN_ENABLED`
- `PLUGIN_DISABLED`
- `PLUGIN_DELETED`
- `API_CREATED`
- `API_DELETED`
- `API_UPDATED`
- `CONSUMER_...`
- `PROVISION`
- etc...

Effectively allowing plugins to do actions throughout kong, without kong being aware of the plugins existence or calling the plugin directly.

**Some Use Cases**

- #338 (audit plugin) would just attach to all events and register the information as a log. done.
- #682 (provisioning endpoint) each authentication plugin registers a provision function and handles the data passed accordingly to provision credentials.

These are just two, but there are countless more, even the #640 (slack integration) would benefit from hooks.

---

![](http://cl.ly/image/3s46191K471k/Image%202015-11-06%20at%205.01.16%20PM.png)

**Comment by Tieske** [comment]
this might help; https://github.com/Olivine-Labs/mediator_lua

**Comment by thibaultCha** [comment]
I'd say it looks overcomplicated for the very simple goal we are trying to achieve here. We simply want a hash table with keys being the event ids, and values being arrays containing functions to execute on a given key.

I can see a simple Lua module doing the job here.

**Comment by Tieske** [comment]
I see what you mean. But in my experience, the simple module will quickly get a few feature requests and then ends up being a copy of an existing, fancier, module. It all depends on how confident you are that it stays "simple".

Also; this module is only 160 lines ([126 sloc](https://github.com/Olivine-Labs/mediator_lua/blob/master/src/mediator.lua)),

**Comment by thibaultCha** [comment]
Yes you're right. We should consider it as an implementation. We would need some sort of wrapper around it though.

**Comment by Nijikokun** [comment]
I think this needs some clarification that isn't introduced, this is not actually an *event bus* pattern.

It's more along the lines of a *middleware pattern* from node (for the lack of a better term, should anyone have one, I was looking into command pattern / etc).

Essentially to satisfy this ticket, you must be able to hook into a location in the code via a passed method, that method will be invoked when the block of code arrives at its execution point, and it will invoke (in order) each method which can then do its necessary actions, modify the result, and the chain continues to the next method in the hook chain.

**Comment by Tieske** [comment]
There are many ways to do roughly the same thing. I think an important distinction here is whether the event handler (or hook) is trusted or not. If it's trusted, pass the full set of data along and let the handler decide whether or not to modify it (usually it will be tables, which are passed by reference anyway).

But if the code is not trusted, only a minimum set of data should be passed (by value, not by reference), and any results should be validated and copied back. Performance wise this is a tough one, considering deep copying of tables etc.

The first approach is far simpler of course... but because it is security related it is a rather fundamental choice.

**Comment by Nijikokun** [comment]
I assume that plugins would be trusted or at least go through some form of audit (community, or developer).

I don't think we should waste our time with the copying mechanism, since the administrator of Kong would most likely only add trusted or self-created plugins.

I think this was a discussion previously brought up on plugins when separating them out and it is not really our concern.

**Comment by Tieske** [comment]
It comes down to what your security philosophy is. So I guess it comes down to making a choice (Kong wide), document it, stick with it. 

Anyway, my personal opinion is that I would leave it to the admin as to which plugins he/she wants to install. The complexity and performance hit will probably not be worth it.

**Comment by Tieske** [comment]
So far for off-topic. On the event bus itself; the picture just registers callbacks for kong events (single producer, multiple consumer, hardly a bus).

Could it be useful to have any component register its own events (multi producer, multi consumer)? for example; a logger that subscribes to authentication events.

**Comment by Nijikokun** [comment]
> Anyway, my personal opinion is that I would leave it to the admin as to which plugins he/she wants to install. The complexity and performance hit will probably not be worth it.

:+1:

> Could it be useful to have any component register its own events (multi producer, multi consumer)? for example; a logger that subscribes to authentication events.

If you pass along the hook mechanisms in the new `ngx.ctx` and `kong.core` (#736) (attach / create) then I wouldn't see why a plugin couldn't have them (in fact I would expect some to create their own so other plugins could also hook into them -- auditing plugin, etc)

**Comment by Tieske** [comment]
Couldn't the event/hook system also resolve #267? (provided the hook mechanism is passed along to enable multi-producer/multi-consumer setups)

**Comment by thibaultCha** [comment]
In 0.6.0 too.
