### ISSUE TITLE
Use plain form parameters when valuing the properties of a plugin

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#70]
Right now the plugin-related properties are sent as a JSON object in a `value` form field, like:

```bash
curl -d 'name=ratelimiting&api_id=ID&value={"period":"second", "limit": 10}' http://127.0.0.1:8001/plugins/
```

I believe that accepting those parameters in plain form values instead of encoding them into a JSON object will make the interface cleaner, so the same request becomes:

```bash
curl -d 'name=ratelimiting&api_id=ID&period=second&limit=10' http://127.0.0.1:8001/plugins/
```

Internally nothing will change in the way we validate the schema. Thoughts? @thibaultCha

**Comment by thefosk** [comment]
The solution I decided to adopt is to set the plugins properties using the dot notation like `value.limit`:

```shell
curl -d 'name=ratelimiting&api_id=ID&value.period=second&value.limit=10' http://127.0.0.1:8001/plugins/
```

**Comment by thibaultCha** [comment]
I don't like `value.*`. Why not what was originally planned? just `period`, `limit`... What's the reason?

**Comment by thefosk** [comment]
Since schemas can support sub-schemas, and sub-schemas could support other sub-schemas (since they're just plain schemas), using just the property name is not enough and could cause name clashes. Using dot-notation fixes this problem, for example:

```
value.limit=10&value.extra.limit=20
```
