### ISSUE TITLE
Properly handle request bodies in Nginx temporary files

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#701]
Properly use [`ngx.req.get_body_file`](https://github.com/openresty/lua-nginx-module#ngxreqget_body_file) to handle chunked request bodies that exceed [`client_body_buffer_size`](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_buffer_size).

This should be a utility function because will be shared among all the plugins.

**Comment by thibaultcha** [comment]
Not a good idea until officially supported by ngx_lua. Reading the returned file from the Lua land will be blocking. Should be closed.

**Comment by bungle** [comment]
Yes I do agree with @thibaultcha that this is problematic. 

Why is this problematic:

1. If you grow `client_body_buffer_size` and `client_max_body_size` you end up creating a DDOS access point to your memory.
2. If you let Nginx to write files to a disk, you have to rely on blocking IO to read them back.

Sometimes you don't have options though, and have to accept something for things to work (e.g. if you want large file uploads, you don't have many options but accept some drawbacks). Here is something that may be considered:

1. provide configuration argument for maximum (single) file size on a multipart body
2. provide configuration argument for maximum number of bytes in data (aka non-files) parts on a multipart body
3. provide configuration argument for maximum number of separate files that can be uploaded on a multipart body
4. stream files using `lua-resty-upload` to a non-blocking store (or temporary files) and store only the metadata of it
5. create `lua-resty-upload` for non-multipart bodies (`lua-resty-bodystream`) with the mentioned safe guards (see above) — also handle timeouts in socket reading

**Comment by p0pr0ck5** [comment]
we now have configurable options for body buffer size, giving control over if/when request bodies are buffered to disk. We can probably close this?
