### ISSUE TITLE
kong.lua improvements

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#709]
After #708, still left to do:

- don't store the configuration and the DAO factory in globals anymore. Pass them along plugins through `ngx.ctx` and `kong.core`.
- maybe consider using the `ngx.ctx.kong.{dao_factory,configuration,...}` namespace (for timers too).
- improve `plugins_iterator.lua` so it can automatically execute the handler function for a given context.
- avoid OOP pattern for plugins handlers. They can simply be a table and the `xxx plugin executed` messages can be done by `plugins_iterator.lua`.

**Comment by thefosk** [comment]
@thibaultCha we did some changes on `kong.lua` in 0.6.0 - does this issue need any update given the new code?
