### ISSUE TITLE
Default folders and configuration location

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#71]
When installing Kong with a package manager, we can create default folders for the output and for the configuration file. This will require to implement the following changes in the `bin/kong` script:

* If the system already has a configuration file at `/etc/kong.yml`, then it takes precedence over any other configuration file unless explicitly specified with `-c`
* If the system has `/var/log/kong` folder, then it takes precedence over any other output folder, unless explicitly specified with `-o`

**Comment by thibaultCha** [comment]
:+1:

**Comment by thefosk** [comment]
I decided to not implement a `-o` option, and introduce an `output` property in `kong.yml`. If the property is not being set, then Kong will put the output into `nginx_tmp` like it did before. If it's set, then `bin/kong` will try to use that folder as the output dir.
