### ISSUE TITLE
Questions regarding `GET /plugins/schema/{plugin name}`

### ISSUE THREAD

**Issue by PGBI** [Mashape/kong#710]
I'm currently building a UI client to configure our Kong gateway. To do so, i'm using the `GET /plugins/schema/{plugin name}` endpoint to build the forms to manage plugins. Most of the time, the response given by this endpoint is self-explanatory.

Here are some cases where I would need some explanation:

`GET plugins/schema/key-auth` returns:
```json
{
  "fields": {
    "key_names": {
      "type": "array",
      "required": true,
      "default": "function"
    },
    "hide_credentials": {
      "type": "boolean",
      "default": false
    }
  },
  "no_consumer": true
}
```
What does `"default": "function"` mean?

`GET plugins/schema/oauth2` returns:
```json
{
  "fields": {
    "mandatory_scope": {
      "type": "boolean",
      "required": true,
      "func": "function",
      "default": false
    },
    "...": {},
  },
  "no_consumer": true
}
```
In this example, what does `"func": "function"` mean?

`GET plugins/schema/acl` returns:
```json
{
  "no_consumer": true,
  "fields": {"...":"..."},
  "self_check": "function"
}
```
What does `"self_check": "function"` mean?

Thanks a lot!

**Comment by thibaultCha** [comment]
When the value is "function" it is because is is a function iirc.

**Comment by PGBI** [comment]
thanks!
