### ISSUE TITLE
JWT plugin is failing to verify a valid signature in some environments

### ISSUE THREAD

**Issue by kdstew** [Mashape/kong#719]
I've described the issue here
https://github.com/Mashape/kong-dist-cloudformation/issues/5

But in summary it looks like the version of openssl installed on the server running kong can cause the JWT plugin to return `{"message":"Invalid signature"}` when the signature of the token is in fact valid.

**Comment by thefosk** [comment]
@kdstew would you be able to tell us which openssl version are you using in order to replicate the issue?

**Comment by ryanbreen** [comment]
I did some digging into this, and the AWS Marketplace image has a busted `crypto.hmac` function.  Every call, regardless of inputs, returns an array of `0`s.  I'm guessing it's something wonky with the Lua install or the (perhaps) OpenSSL libs that sit under those crypto functions.

**Comment by thefosk** [comment]
Related to https://github.com/Mashape/kong-dist-cloudformation/issues/5

**Comment by thefosk** [comment]
Do you still experience this issue? If you are using AWS, we are now distributing an AWS-specific distribution that should have fixed this problem: https://getkong.org/install/aws-linux/

**Comment by thefosk** [comment]
Please re-open if the issue persists.

**Comment by jdaviscooke** [comment]
I am hitting what looks like this issue with a new 0.8.3 environment running on Amazon Linux. Relevant environment setup as well as comparison to a working 0.8.3 environment running on Amazon ECS can be found in this gist: https://gist.github.com/jdaviscooke/cfc173bd69ba34b8e616644c5a3ec8e0

**Comment by thefosk** [comment]
@jdaviscooke what Kong distribution are you using in your AWS environment?

**Comment by jdaviscooke** [comment]
@thefosk It's in the Gist; kong version: 0.8.3 Installed Packages kong.noarch 0.8.3-1 @/kong-0.8.3.aws

**Comment by thefosk** [comment]
@jdaviscooke on your machine, is `openssl098e` installed and if not, does `sudo yum install openssl098e` fix the problem?

**Comment by jdaviscooke** [comment]
@thefosk confirmed via yum that openssl098e is already installed 
Installed Packages openssl098e.x86_64    0.9.8e-29.19.amzn1          @amzn-updates

**Comment by thibaultCha** [comment]
@jdaviscooke Have you tried the solution detailed at Mashape/kong-dist-cloudformation#5 by @kdstew (removing luacrypto and reinstalling it with the latest openssl-devel)?

**Comment by jdaviscooke** [comment]
@thibaultCha That has unblocked me, thank you for the link!
