### ISSUE TITLE
Impossible to reset a plugin configuration parameter with PUT

### ISSUE THREAD

**Issue by PGBI** [Mashape/kong#720]
I have the rate-limiting plugin configured as follow:
```json
{
      "api_id": "66212e8a-81e9-4798-c7c5-ed4429d3074c",
      "id": "15712463-44a5-436b-c325-465343b138c5",
      "created_at": 1447624025000,
      "enabled": true,
      "name": "rate-limiting",
      "config": {
        "hour": 36000
      }
}
```

Let's say I want to remove the "hour" limit, and add a "second" one. Here is my request:

`PUT http://localhost:8001/plugins`
```json
{
      "api_id": "66212e8a-81e9-4798-c7c5-ed4429d3074c",
      "id": "15712463-44a5-436b-c325-465343b138c5",
      "created_at": 1447624025000,
      "enabled": true,
      "name": "rate-limiting",
      "config": {
        "second": 10
      }
}
```

Now my plugin is configured as follow:
```json
{
      "api_id": "66212e8a-81e9-4798-c7c5-ed4429d3074c",
      "id": "15712463-44a5-436b-c325-465343b138c5",
      "created_at": 1447624025000,
      "enabled": true,
      "name": "rate-limiting",
      "config": {
        "hour": 36000,
        "second": 10
      }
}
```

The "hour" limit is still there. How can I reset the "hour" parameter? I've tried sending an empty string for config.hour, but I then get a validation error "this is not a number".

I took the rate-limiting plugin as an example, but I have the same problem with other plugins. Apart from string parameters that one can set empty, it looks like it is not possible to reset a plugin config parameter.

**Comment by thibaultCha** [comment]
Thanks for reporting, since PUT is the only method that would allow to remove values from the `config` property, this needs to be possible. We'll take a look at this.

**Comment by thefosk** [comment]
@PGBI we have identified the problem, the fix will be available in the next version.

**Comment by PGBI** [comment]
Thank you!
