### ISSUE TITLE
Multi Factor Authentication

### ISSUE THREAD

**Issue by esatterwhite** [Mashape/kong#723]
I would ultimately like to allow for multiple authentication types for a service, and return the first success, and only return an error response if none of them succeed.

For example, I would like `/orders` to allow for `basic`, `hmac`, or `jwt`.

**Comment by thibaultCha** [comment]
Dup of #590

**Comment by mvanholsteijn** [comment]
and available https://getkong.org/docs/0.10.x/auth/#multiple-authentication
