### ISSUE TITLE
OAuth2 Resource Owner/Password not parsing JSON?

### ISSUE THREAD

**Issue by Floby** [Mashape/kong#730]
Hello,

I'm trying the password grant on my application. So far I managed to curl my way to a complete workflow following examples. 
Coming the implementation, I'm switching to JSON for the payloads. Specifically when posting to kong from my backend on `/oauth2/token` with the authenticated_userid and everything. 

It keeps coming back with `invalid client_id`.

Curling again shows that everything works as expected when sending urlencoded data with curl, but JSON keeps failing. trying to remove any field one by one while urlencoded shows that client_id is just the first being checked for presence. It looks to me that something is failing at the JSON level but I can't really grasp what.

this is the complete JSON I am sending to Kong
```javascript
{ 
  "grant_type": "password",
  "username":"john.doe@mail.com",
  "password": "password",
  "client_id": "cid",
  "provision_key": "cf6b2705117340d7c068d5413ff0d821",
  "authenticated_userid": "floby",
  "client_secret": "csecret",
  "scope": "test"
}
```

Sending the same data as `--data client_id=cid` in curl works.

EDIT:
looking at https://github.com/Mashape/kong/blob/master/kong/plugins/oauth2/access.lua#L136 or https://github.com/Mashape/kong/blob/master/kong/plugins/oauth2/access.lua#L233 it seems that the message comes from kong failing to find the client in cache or database by that id. I have no idea how to check what it's using as client_id at that moment.

**Comment by thefosk** [comment]
@Floby currently we only support `application/x-www-form-urlencoded` request bodies when trying to issue a new access token.

**Comment by Floby** [comment]
I see.
Is this intentional or can I try and submit a pull request ?

**Comment by thefosk** [comment]
We just never planned support for it. A PR would work.
