### ISSUE TITLE
Support Mutual SSL for API Clients

### ISSUE THREAD

**Issue by aelmhorst** [Mashape/kong#740]
This would be useful for legacy client protocol implementations that use mutual SSL

**Comment by thefosk** [comment]
This possibility seems to be blocked by a limitation of OpenResty (https://github.com/openresty/lua-nginx-module/issues/331#issuecomment-164989178).

> No, this thread is all about downstream SSL connections. Your requirement requires patching the standard ngx_http_proxy_module I'm afraid.

**Comment by p0pr0ck5** [comment]
Closing this, tracking in #1547 .
