### ISSUE TITLE
Unhandled lua error when no available plugins in configuration

### ISSUE THREAD

**Issue by siddharthist** [Mashape/kong#742]
I was running Kong (from the `mashape/kong:latest` Docker container) on Mesos with a malformed config, specifically, one that had no plugins_available field. I got this error:
```
/usr/local/bin/luajit: /usr/local/share/lua/5.1/kong/tools/migrations.lua:55: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
	[C]: in function 'ipairs'
	/usr/local/share/lua/5.1/kong/tools/migrations.lua:55: in function 'migrate_all'
	/usr/local/share/lua/5.1/kong/cli/utils/signal.lua:174: in function 'prepare_database'
	/usr/local/share/lua/5.1/kong/cli/utils/signal.lua:225: in function 'prepare_kong'
	/usr/local/share/lua/5.1/kong/cli/start.lua:21: in main chunk
	[C]: in function 'require'
	/usr/local/lib/luarocks/rocks/kong/0.5.3-1/bin/kong:55: in main chunk
	[C]: at 0x00404ac0
```
[Looks like the error happens here](https://github.com/Mashape/kong/blob/bf8465fe8d3b7fcc394c37bf3bfd3f936d9658f7/kong/tools/migrations.lua#L55). After putting this field in my config, I no longer saw this error. 

While the Kong docs say that every field is required, this is not a particularly helpful error message!

**Comment by thibaultCha** [comment]
Yes, that is taken care of by #596 already, and in `next`, which will be out with the next feature-release (0.6). Thanks
