### ISSUE TITLE
Add new thrid-party tool to tools list: Konga

### ISSUE THREAD

**Issue by Floby** [Mashape/kong#755]
Hello,
I have written a kong cli tool to use a client for the admin API. I know this isn't the first but seeing the existing list I figured it could as well be in there. So if you think it's interesting I'd love to see it here =)

It's written in node.js and available on [npm](https://www.npmjs.com/package/konga-cli) but the repository is here https://github.com/Floby/konga-cli

it's a idempotent cli tool that I wrote to configure my servers with ansible.

**Comment by sinzone** [comment]
sure. we'll update the readme once the 0.6 is out and will include this.

**Comment by thibaultCha** [comment]
Nice, feel free to submit a PR with the changes.

As a side node, I have to say: the goal for the current Kong CLI is to also do this. Adding APIs, Consumers, plugins etc from the Kong CLI has been on our minds since the beginning. We simply did not find the time to do it yet.

**Comment by Floby** [comment]
Well I needed to configure my APIs. Seeing the python module was completely
undocumented and failed to pass CI I went on writing a tool with whatever
I'm more proficient in.

The code is MIT licenced anyway so feel free to either contribute or copy ;)

**Comment by thibaultCha** [comment]
Thanks, I merged this.
