### ISSUE TITLE
404 when requesting an API

### ISSUE THREAD

**Issue by jney** [Mashape/kong#761]
hi guys. we're doing some load testing on our APIs. Our APIs are callable through kong. At some point we just got 404 errors.

ie :

```json
{"request_path":"/some/path","message":"API not found with these values","request_host":["some.host"]}
```

it's weird, because it is not the status code i was expecting.
And the status message is not very explicit.

we did the same test, bypassing kong and we have 0%  error rate.

what can i do to improve kong perfs and have approriate response status ?

**Comment by thibaultCha** [comment]
If Kong is able to send this reply, my first impression would be that it is not overloaded. This response likely indicates that Kong is healthy but could really not find an API with the values requested.

At this point I have several questions:
- any errors appearing in the `error.log` file?
- did you make any change to the API registered in Kong during the benchmark? Or was the API created just before starting the benchmark? Kong 0.5.x currently caches those values for 60s to avoid querying Cassandra on each request (until #729). Which means that any modification in the Admin API *potentially* needs up to 60s to propagate, for now.

**Comment by jney** [comment]
your answer makes sense.
i'm wondering if the service behind is not so much loaded that it doesn't answer anything at all, so kong reply with a `404` status code, i have to check it

**Comment by thibaultCha** [comment]
No, if the API was unreachable, that would not be how Kong would reply either.

**Comment by thefosk** [comment]
@jney were you able to figure this out?

**Comment by jney** [comment]
we had a sinatra/heroku webservice, we migrated to lapis/aws.
the problem is not present anymore.
my feeling is i should blame sinatra, but i haven't dig enough

**Comment by thefosk** [comment]
Okay I am closing this for now - feel free to reopen if the problem arises again.
