### ISSUE TITLE
Support for SPDY - HTTP/2

### ISSUE THREAD

**Issue by kishorgandham** [Mashape/kong#773]
Is there a plan to support SPDY on Kong? Given that nginx supports SPDY with an add-on module and has HTTP/2 in the roadmap, what is the plan for supporting these on Kong?

**Comment by thibaultCha** [comment]
Since Kong is built on top of Nginx, whenever Nginx adopts HTTP/2, and once ngx_lua supports it, Kong will support it too. See #574

**Comment by thibaultcha** [comment]
Not dependent on Kong, closing this now.
