### ISSUE TITLE
[CI] use Apache's archives to download Cassadra

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#784]
Our current CI platforms use mirrors that only maintain the latest Cassandra release. As soon as a new version is released, CI tests will fail because they cannot download Cassandra (the link changes).

CI platforms should use [Apache's archives](https://archive.apache.org/dist/cassandra) like other projects (like `ccm`) do to retrieve the Cassandra version we want to run our tests against.

**Comment by Tieske** [comment]
fixed by #798
