### ISSUE TITLE
[jwt plugin] Allow for optional "typ" (Type) Header Parameter in JWT token

### ISSUE THREAD

**Issue by cromark** [Mashape/kong#796]
If the **typ** header is missing , the jwt plugin should be able to safely accept the token if it is signed correctly 

Some JWT offerings such as [CloudFoundry UAA] (https://github.com/cloudfoundry/uaa) do not emit a **typ** header. 

ref: [Section 5.1 of the JWT specification]    
(http://tools.ietf.org/html/rfc7519#section-5.1) notes the **typ** header as OPTIONAL

**Comment by tony-kerz** [comment]
+1

**Comment by sinzone** [comment]
+1

**Comment by thefosk** [comment]
Related to #1191 which proposes a solution.

**Comment by thefosk** [comment]
Fixed with cab241fdf5e8c008a859cd01f79da8b0c96c0c67
