### ISSUE TITLE
Keep track of migrations

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#8]
In order to have a fully working migrations system, Kong should keep track of the last migration in order to properly revert, or properly go up.

**Comment by thibaultCha** [comment]
My idea as an MVP is that `up` will execute them all, `rollback` will revert 1 by 1 (in case a migration shouldn't have happened, that's why we need to keep track of them), and `reset` goes down all the way. Implementing it now.

**Comment by thefosk** [comment]
As a side note, it would be nice if *at least* the first migration could be embedded in the `kong start` command.

**Comment by thibaultCha** [comment]
Implemented in #45.
