### ISSUE TITLE
Leverage Lapis utilities

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#80]
Lapis has built-in cache, JSON encode/decode, base64... We should leverage them instead of our custom methods: http://leafo.net/lapis/reference/utilities.html

Eventually, it also has schemas and migrations, even tho unfortunately, they only support PostgreSQL. Writing a Cassandra adapter would be a great contribution from Mashape. We could discuss this with the author of Lapis.

(cross referencing #18)

**Comment by thefosk** [comment]
Regarding cache, not sure we can leverage that because the API server is not a Lapis app.
