### ISSUE TITLE
HMAC: Keyed-Hashing for Message Authentication

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#808]
>    This document describes HMAC, a mechanism for message authentication
   using cryptographic hash functions. HMAC can be used with any
   iterative cryptographic hash function, e.g., MD5, SHA-1, in
   combination with a secret shared key.  The cryptographic strength of
   HMAC depends on the properties of the underlying hash function.

-- [RFC 2104](http://tools.ietf.org/html/rfc2104)
-- related [RFC 6151](http://tools.ietf.org/html/rfc6151)

**Comment by thibaultCha** [comment]
What is this?

**Comment by ahmadnassri** [comment]
alternative authentication method with HMAC
