### ISSUE TITLE
Installation ERROR

### ISSUE THREAD

**Issue by yanlinaung30** [Mashape/kong#813]
$ brew tap mashape/kong
==> Tapping mashape/kong
Cloning into '/usr/local/Library/Taps/mashape/homebrew-kong'...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
Checking connectivity... done.
Tapped 4 formulae (34 files, 140K)
$ brew install kong
==> Installing kong from mashape/kong
==> Installing dependencies for mashape/kong/kong: openssl, dnsmasq, mash
==> Installing mashape/kong/kong dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2e.el_capitan.b
######################################################################## 100.0%
==> Pouring openssl-1.0.2e.el_capitan.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2e: 465 files, 17M
==> Installing mashape/kong/kong dependency: dnsmasq
==> Downloading https://homebrew.bintray.com/bottles/dnsmasq-2.75.el_capitan.bot
######################################################################## 100.0%
==> Pouring dnsmasq-2.75.el_capitan.bottle.tar.gz
==> Caveats
To configure dnsmasq, copy the example configuration to /usr/local/etc/dnsmasq.conf
and edit to taste.

  cp /usr/local/opt/dnsmasq/dnsmasq.conf.example /usr/local/etc/dnsmasq.conf

To have launchd start dnsmasq at startup:
  sudo cp -fv /usr/local/opt/dnsmasq/*.plist /Library/LaunchDaemons
  sudo chown root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
Then to load dnsmasq now:
  sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
==> Summary
🍺  /usr/local/Cellar/dnsmasq/2.75: 7 files, 512K
==> Installing mashape/kong/kong dependency: mashape/kong/luajit
==> Cloning http://luajit.org/git/luajit-2.0.git
Cloning into '/Library/Caches/Homebrew/luajit--git'...
Checking connectivity... done.
==> Checking out branch v2.1
==> make amalg PREFIX=/usr/local/Cellar/luajit/2.1_1 INSTALL_TNAME=luajit
==> make install PREFIX=/usr/local/Cellar/luajit/2.1_1 INSTALL_TNAME=luajit
🍺  /usr/local/Cellar/luajit/2.1_1: 27 files, 2.1M, built in 4.9 minutes
==> Installing mashape/kong/kong dependency: mashape/kong/luarocks
==> Downloading http://luarocks.org/releases/luarocks-2.2.2.tar.gz
==> Downloading from http://keplerproject.github.io/luarocks/releases/luarocks-2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/luarocks/2.2.2 --with-lua=/usr/local/
==> make build
==> make install
==> Caveats
Rocks will be installed to: /usr/local/lib/luarocks/rocks
==> Summary
🍺  /usr/local/Cellar/luarocks/2.2.2: 71 files, 596K, built in 5 seconds
==> Installing mashape/kong/kong dependency: pcre
==> Downloading https://homebrew.bintray.com/bottles/pcre-8.38.el_capitan.bottle
######################################################################## 100.0%
==> Pouring pcre-8.38.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/pcre/8.38: 146 files, 5.9M
==> Installing mashape/kong/kong dependency: mashape/kong/ngx_openresty
==> Downloading http://openresty.org/download/ngx_openresty-1.9.3.1.tar.gz
######################################################################## 100.0%
==> Patching
patching file bundle/nginx-1.9.3/src/event/ngx_event_openssl.c
Hunk #1 succeeded at 1206 (offset 85 lines).
patching file bundle/nginx-1.9.3/src/event/ngx_event_openssl.h
==> curl -s -L -o /private/tmp/ngx_openresty20151221-13365-1h7xl3o/ngx_openresty
==> tar -xzf ssl-cert-by-lua.tar.gz
==> rm -rf bundle/ngx_lua-0.9.16/*
==> cp -R lua-nginx-module-ssl-cert-by-lua/* bundle/ngx_lua-0.9.16/
==> ./configure --prefix=/usr/local/Cellar/ngx_openresty/1.9.3.1 --with-ipv6 --w
==> make
==> make install
🍺  /usr/local/Cellar/ngx_openresty/1.9.3.1: 61 files, 1.5M, built in 101 seconds
==> Installing mashape/kong/kong
==> Downloading https://github.com/Mashape/kong/archive/0.5.4.tar.gz
==> Downloading from https://codeload.github.com/Mashape/kong/tar.gz/0.5.4
######################################################################## 100.0%
==> make install
Last 15 lines from /Users/yanlinaung/Library/Logs/Homebrew/kong/01.make:
export MACOSX_DEPLOYMENT_TARGET=10.8; gcc -bundle -undefined dynamic_lookup -all_load -o socket/core.so -L/usr/local/Cellar/luajit/2.1_1/lib src/luasocket.o src/timeout.o src/buffer.o src/io.o src/auxiliar.o src/options.o src/inet.o src/except.o src/select.o src/tcp.o src/udp.o src/usocket.o
export MACOSX_DEPLOYMENT_TARGET=10.8; gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/buffer.c -o src/buffer.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
export MACOSX_DEPLOYMENT_TARGET=10.8; gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/auxiliar.c -o src/auxiliar.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
export MACOSX_DEPLOYMENT_TARGET=10.8; gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/options.c -o src/options.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
export MACOSX_DEPLOYMENT_TARGET=10.8; gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/timeout.c -o src/timeout.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
export MACOSX_DEPLOYMENT_TARGET=10.8; gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/io.c -o src/io.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
export MACOSX_DEPLOYMENT_TARGET=10.8; gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/usocket.c -o src/usocket.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
export MACOSX_DEPLOYMENT_TARGET=10.8; gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/unix.c -o src/unix.o -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DUNIX_HAS_SUN_LEN -DLUASOCKET_API=__attribute__((visibility("default"))) -DUNIX_API=__attribute__((visibility("default"))) -DMIME_API=__attribute__((visibility("default")))
export MACOSX_DEPLOYMENT_TARGET=10.8; gcc -bundle -undefined dynamic_lookup -all_load -o socket/unix.so -L/usr/local/Cellar/luajit/2.1_1/lib src/buffer.o src/auxiliar.o src/options.o src/timeout.o src/io.o src/usocket.o src/unix.o

Error: Failed installing dependency: https://luarocks.org/luasec-0.5-2.src.rock - Could not find expected file openssl/ssl.h, or openssl/ssl.h for OPENSSL -- you may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command. Example: luarocks install luasec OPENSSL_DIR=/usr/local
Updating manifest for /usr/local/lib/luarocks/rocks
luasocket 3.0rc1-2 is now built and installed in /usr/local (license: MIT)

make: *** [install] Error 1

**Comment by yanlinaung30** [comment]
Problem solved.
https://github.com/Mashape/homebrew-kong/issues/14

**Comment by Tieske** [comment]
glad it works!

**Comment by thibaultCha** [comment]
There is also a note for this in the troubleshooting section: https://github.com/Mashape/homebrew-kong#troubleshooting
