### ISSUE TITLE
production and development paths are not in sync

### ISSUE THREAD

**Issue by Tieske** [Mashape/kong#817]
The [rockspec](https://github.com/Mashape/kong/blob/next/kong-0.5.4-1.rockspec#L40-L45) moves files to different locations.

This is bad! doing so will introduce very subtle bugs when testing. The code will `require` the production path. So when testing, it will look in the wrong place in the source tree, will not find it, and fall back to the default system location. There it will find a previously installed released version, and then use that code to run the tests.

Paths in the rockspec, left-hand side and right-hand side, must be the same to prevent this.

Additionally, there is a [double entry](https://github.com/Mashape/kong/blob/next/kong-0.5.4-1.rockspec#L209-L210)

**Comment by thibaultCha** [comment]
Yep, their names 9left-side) should include the full path (`kong.vendor.classic`). The vendor files are not to be touched (ideally though) but the Kong one yes. This last one should probable be relocated to `./kong.lua`, because having it named `kong.kong` would be confusing.

**Comment by thibaultCha** [comment]
I would like to only label an issue "big" when it is an actual one (abnormal behavior that goes against the documentation and/or hurting the usability). This does not fall into this category as it

- concerns development
- is intended for the vendor modules
- works well for kong.lua
