### ISSUE TITLE
Lua CLI

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#83]
Let's switch our current CLI from a bash script to a Lua script. Here are reasons why and features we can accomplish:

- By having a Lua binary, we are closer to Kong's source code and can leverage any module (`migrations.lua`, dao factories...)
- `luarocks install kong` would install Kong with our `.rockspec`, copying the bin into the user's `$PATH`. This solves our #51 issue by having this desired "simple way" to install Kong.
- We can separate every CLI command in sub-scripts, which is way more maintainable
- We can install plugins via a `kong install <plugin>` command that leverages luarocks. It could download the plugin, verify the signature, prompt questions to the terminal for configuration of the installed plugin (ex: `Do you want to enable this freshly installed plugin on your machine? [y/n]: `, etc...
- We can provide native `kong start/stop` scripts with nicer `stdout`/`stderr` outputs.
- We can migrate from the CLI (including the first migration) instead of wrapping a lua script from bash or migrating once kong is running (in Nginx like currently).
- We can unit test the CLI with busted
- A Lua CLI can be easily extended in the future, adding support for "add-user", or cluster-related informations will be much easier.

TODO list:

- [x] Global `kong` bin with sub-binaries for each command
- [x] Convert existing scripts to Lua (start/stop/migrate/rollback/reset/seed/drop)
- [x] Default config loading system (`/etc/kong/kong.yml` or `{rocks_path}/kong/conf/kong.yml`)
- [x] Convert the Makefile
- [x] Cleanup `tools.utils` and `cmd.utils` now that we have a CLI utils file.
- [x] Switch first migrations from `kong.lua` to be bundled in the `start` command.
- [ ] Configuration validation

**Comment by thefosk** [comment]
Some of the points above are also referencing #21

**Comment by thibaultCha** [comment]
TODO list:

- [x] Global `kong` bin with sub-binaries for each command
- [x] Convert existing scripts to Lua (start/stop/migrate/rollback/reset/seed/drop)
- [x] Default config loading system (`/etc/kong/kong.yml` or `{luarocks}/kong/conf/kong.yml`)
- [x] Convert the Makefile
- [ ] Cleanup `tools.utils` and `cmd.utils` now that we have a CLI utils file.
- [ ] Switch first migrations from `kong.lua` to be bundled in the `start` command.
- [ ] Configuration validation

**Comment by thibaultCha** [comment]
@thefosk I believe this can be in the next release by tonight ^

**Comment by thibaultCha** [comment]
#92
