### ISSUE TITLE
Redis Caching plugin

### ISSUE THREAD

**Issue by tinkajts** [Mashape/kong#830]
Enable caching via Redis, so that NginX do not need to go to a registered api endpoint to get data for the current request. Just serve from the redis cache directly.

Caching via normal caching params;  headers / url / url params /

**Comment by allynalford** [comment]
That would be great. Expirations config would be needed i think.

**Comment by thibaultCha** [comment]
Let's keep this in the scope of #411, with a note to consider Redis (the actual implementation not being determined yet).
