### ISSUE TITLE
Change kong's datastore with an existing one

### ISSUE THREAD

**Issue by senj** [Mashape/kong#836]
According to https://getkong.org/docs/0.5.x/plugin-development/access-the-datastore/ Kong currently supports only Cassandra.

Is it somehow possible to write plugins that hook up at the extension points where we write and read the registered API information and make a REST call to some service that should serve the information instead, maybe with ResolverHandler:access(conf)?

![apigw1](https://cloud.githubusercontent.com/assets/5556013/12110999/2fbc3354-b392-11e5-989f-71bbc3487ad4.PNG)
![apigw2](https://cloud.githubusercontent.com/assets/5556013/12111000/2fc069ba-b392-11e5-985b-3fafedc33a35.PNG)

To clarify this, I need read only because the registry is handled by my service.

**Comment by thibaultCha** [comment]
Since Kong is an OpenResty application, you are free to use the wide variety of lua-resty-* modules such as lua-resty-redis, lua-resty-postgres, lua-resty-mysql, and potentially others. You can create a plugin extending the Admin API and using one of those libraries to interact with a datastore other than the one storing Kong's configuration.

**Comment by senj** [comment]
Ok great. I wrote a plugin that can do what I want, but https://github.com/Mashape/kong/blob/master/kong/resolver/access.lua will always execute before my plugin, knowing that the url isn't registered and breaking the execution. (API not found with these values)
Well this is what it's supposed to do. The Kong resolver core-plugin is executed before any other.

I tried it with PRIORITY but this order seems to be handled somewhere else. Is there a way to get my plugin execute before the core plugin without changing kong code?

**Comment by thibaultCha** [comment]
> Inject it directly into kong.yaml nginx part?

It would seem to be the only way as of now. And yes the resolver is meant to be run as soon as possible in the request lifecycle so that all other plugins can now which API this request is targeting and how to behave.
