### ISSUE TITLE
Typo error in milestone name

### ISSUE THREAD

**Issue by nazarhussain** [Mashape/kong#842]
It seems there is typo error in milestones page. Instead of Feb 2016, it is listed as Feb 2015. 

<img width="518" alt="screenshot at jan 07 14-14-25" src="https://cloud.githubusercontent.com/assets/112468/12166610/09668a5c-b549-11e5-91d0-2f104eed7603.png">

**Comment by ahmadnassri** [comment]
thanks for pointing that out! :)
