### ISSUE TITLE
Microservice Architecture with Kong

### ISSUE THREAD

**Issue by pvormittag** [Mashape/kong#844]
I've been evaluating Kong for fronting a Microservice architecture which will serve a web application under a single domain.

It's clear to me the advantages for API development and the ability to centralize typical API requirements: rate limiting, authentication, authorization, etc. However, is Kong a good choice for Microservice architectures which must additionally support features of a typical web application, such as serving HTML/CSS/JavaScript?

As Kong is RESTful, I cannot foresee any obvious limitations for this architecture, but the more I dig into and attempt an implementation, I'm less certain.

I was informed yesterday on [gitter](https://gitter.im/Mashape/kong?at=568d5bc1262659750bce96a5) it is not possible for Kong to proxy requests which are unmatched to a registered API. Therefore only Kong can return 404 errors in this scenario.

To further illustrate the problem, suppose I have the following API's registered and DNS for `example.com` is pointed at Kong:

```
{
  "data": [
    {
      "upstream_url": "http://admin.service.consul",
      "request_path": "/admin",
      "strip_request_path": true,
      "name": "admin.service"
    },
    {
      "upstream_url": "http://v1.api.service.consul",
      "request_path": "/api/v1",
      "strip_request_path": true,
      "name": "api.v1.service"
    },
    {
      "upstream_url": "http://product.service.consul",
      "request_path": "/products",
      "strip_request_path": true,
      "name": "products.service"
    },
    {
      "upstream_url": "http://embed.service.consul",
      "request_path": "/products/embed",
      "strip_request_path": true,
      "name": "embed.service"
    }
  ]
}
```

What are Kong's proxying rules in the case of `example.com/products` and `example.com/products/embed`? Also, if a request is made to simply `example.com`, Kong will return a 404 response in JSON format, which in the case of a web application is likely not wanted.

My concerns for this type of architecture could simply not be ideal for Kong, but since "Microservice" has already become an often-used nebulous term, it may help to clarify Kong's position on the matter.

**Comment by ahmadnassri** [comment]
just add a new API with the `request_host` set to `example.com` and it will proxy the requests unmatched by the paths back to whatever source you want ...

**Comment by thibaultCha** [comment]
If you do that and call any of those other APIs with example.com/path, this API @ahmadnassri suggested will "eat" all requests, since `request_host` is looked up first and because host and path were never intended to be combined together.

**Comment by pvormittag** [comment]
@ahmadnassri Using `request_host` makes sense if routing by domain, say `api.example.com` or `product.example.com`, but I am more interested in routing request paths of a single domain through to services which handle different concerns of the application: example.com/admin, example.com/store, etc.

@thibaultCha I noticed this as well which is why I asked about Kong's proxy rules. Thanks for clarifying.

**Comment by ahmadnassri** [comment]
I've created a number of tickets to track the different aspects to this:
#847 #846 #845

**Comment by thibaultCha** [comment]
Closing this since it is a question and tickets have been opened to track the decisions.
