### ISSUE TITLE
add a catch-all route

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#847]
instead of rejecting requests when no `request_path` or `request_host` are matched, should allow to forward requests to a custom endpoint instead of replying with a 404

**Comment by thibaultCha** [comment]
We could allow for a special API to be created, say for example with an attribute `fallback: true` or something, that acts as the API when no other API got matched. If no such API is configured, 404 is probably still the proper reply.

**Comment by senj** [comment]
This would be great because other plugins would have the chance to make actions although no API was found.

**Comment by thibaultcha** [comment]
The new router at #1970 addresses this concern. Some documentation regarding it have been added to the PR's description.

**Comment by Tieske** [comment]
merged in 0.10.0. Available in the RC for 0.10, closing this.
