### ISSUE TITLE
allow for anonymous access to APIs with authentication

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#853]
an "anonymous" consumer can be used to refer to none-authenticated caller to the API, perhaps an internal reference or an operator created one with a flag `anonymous: true`

should also allow for setting plugin rules as regular consumers, used when authentication plugins are present and no Authentication headers are sent.

**Comment by thibaultCha** [comment]
Not sure if this has anything to do with #475

**Comment by ahmadnassri** [comment]
thanks couldn't find that one! closing in favor of this one as its better described here.

**Comment by Tieske** [comment]
merged and available in the 0.10 RC. closing this

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [anonymous users / multiple-auth](https://trello.com/c/EPEDGoDc/36-anonymous-users-multiple-auth)
