### ISSUE TITLE
Using Ubuntu deb Package Install of Kong, attempting to start indicates bad cassandra version. 

### ISSUE THREAD

**Issue by jaschenk** [Mashape/kong#859]
Using Ubuntu deb Package Install of Kong, attempting to start indicates bad Cassandra version. 

:/etc/kong$ kong start
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Kong version.......0.5.4
       Proxy HTTP port....8000
       Proxy HTTPS port...8443
       Admin API port.....8001
       dnsmasq port.......8053
       Database...........cassandra password=cassandra timeout=1000 user=cassandra contact_points=localhost:9042 keepalive=60000 keyspace=kong
[INFO] Connecting to the database...
[ERR] Cassandra error: Invalid response version received from localhost
jaschenk@jaschenk-VirtualBox:/etc/kong$ cqlsh 
Connected to Test Cluster at localhost:9160.
[cqlsh 4.1.1 | Cassandra 2.0.11 | CQL spec 3.1.1 | Thrift protocol 19.39.0]
Use HELP for help.
cqlsh>

Documentation for Kong indicates it requires at least 2.x of Cassandra?

**Comment by jaschenk** [comment]
Need to use 2.1 of Cassandra.

**Comment by ialoft** [comment]
try to use : https://github.com/Mashape/docker-cassandra/pull/5
