### ISSUE TITLE
API Analytics Plugin

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#86]
Use [ALF](https://github.com/Mashape/api-log-format) as the default format for all HTTP logging.

**Comment by sinzone** [comment]
+1

**Comment by thefosk** [comment]
@Nijikokun @SGrondin @kennethklee @ahmadnassri please tell us more info about the ALF Plugin.

Where should the data be sent to: http, tcp? What address? @thibaultCha will take care of the implementation.

Renaming this issue to: API Analytics plugin

**Comment by ahmadnassri** [comment]
all the info is documented [here](https://github.com/Mashape/api-log-format)

**Comment by thibaultCha** [comment]
There is no such thing as "default logging". There is a plugin for each logging capacity. ALF appears to be one of the available logging plugin, but not the default because all plugins are equal...

Thus why it changed to the ALF logging plugin ticket. I knew for the ALF repo, but it does not provide info son how to send the data. Will follow up in 1-1

**Comment by ahmadnassri** [comment]
you have tcplog and udplog plugins... what formats are those using?

**Comment by thibaultCha** [comment]
I see your point. So rather to separate the plugins by logging format, it is true they are separated by protocol they're using to send the data. In that case, if I want to send data to apianalytics, can't I just use one of those and set the format to "ALF", or what other value would APIanalytics give me? More than logging? What do we need to build now? An ALF serializer for our current logging plugin or an API analytics plugin? There is no clear roadmap

**Comment by ahmadnassri** [comment]
yes, API Analytics integration can simply be the TCP plugin (potentially) or UDP, whatever .. its more about the format *(and setting a token)*

currently API Analytics is built on ZMQ, so TCP is certainly a preferred method, as long as its in ALF format + an API Analytics token is set, just send the data over TCP / HTTP and that's it.

I could see this same setup be used for any TCP based logging platform (splunk) hence why I'm more interested on the format since you already got a TCP plugin working.

*if it is possible for plugins to "stack" in a chain, where one plugin creates log data, and another sends it over a protocol, then that would be epic actually ... #IdealWorld*

**Comment by thefosk** [comment]
To recap, we want a new plugin called API Analytics that creates the ALF payload and send it to a configurable ZMQ server.

**Comment by ahmadnassri** [comment]
what formats are those plugins using:

- http://getkong.org/plugins/udp-log/
- http://getkong.org/plugins/tcp-log/
- http://getkong.org/plugins/file-log/

**Comment by thibaultCha** [comment]
> we want a new plugin called API Analytics that creates the ALF payload and sends it to a configurable ZMQ server.

That's the point, we have different ways of doing that.

1. Each logging plugin is tied to a protocol, and has different **formats**. tcplog sends data over tcp and can have an ALF format. And if you send data to API Analytics, it can also have a key. Which is kind of strange, but totally doable. In that case, the default format would be "ALF", and other formats could be "raw", however it is currently (not any specific format).

2. We have an API Analytics plugin, with a documentation of its own, a configuration of its own, and that plugin sends data over, say, tcp only.

What's the preferred approach?> we want a new plugin called API Analytics that creates the ALF payload and sends it to a configurable ZMQ server.

That's the point, we have different ways of doing that.

1. Each logging plugin is tied to a protocol, and has different **formats**. tcplog sends data over tcp and can have an ALF format. And if you send data to API Analytics, it can also have a key. Which is kind of strange, but totally doable. In that case, the default format would be "ALF", and other formats could be "raw", however it is currently (not any specific format).

2. We have an API Analytics plugin, with a documentation of its own, a configuration of its own, and that plugin sends data over, say, tcp only.

What's the preferred approach?

**Comment by thefosk** [comment]
The new plugin will create the ALF payload (only ALF) from the Lua object that Kong provides, and then send it to TCP. So it's your second option.

In the future we might want `tcplog` and `updlog` to have configurable log formats, but that would another issue. When we do that, we could unify/change the way logging works.

**Comment by SGrondin** [comment]
As stated in the ApiAnalytics docs, the server accepts both ZMQ and HTTP. For something like Kong, it's up to you to either include the ZMQ instructions into the install scripts (homebrew, .deb, etc etc) or, I think better in this case, use the batch HTTP input. Simply batch ALFs 1000 at a time into an array and send it off to the server.

**Comment by ahmadnassri** [comment]
you can batch both the ALFs + the entries within the ALFs, whaver makes the most sense for your agent's performance of course
