### ISSUE TITLE
Don't append port to outgoing Host header if it wasn't explicitly specified in upstream_url

### ISSUE THREAD

**Issue by ondrej** [Mashape/kong#869]
By default, Kong will replace the incoming Host header with the hostname of the upstream_url (unless preserve_host is true). It looks like Kong always adds the port to the new Host header, even if it wasn't explicitly specified. For example, a "https://www.foobar.com/" upstream_url will result in a "www.foobar.com:443" Host header.

This can cause problems if the upstream server isn't expecting (or doesn't support) port numbers in Host headers. This was the case with our setup, but preserve_host turned out to be an effective workaround. Is there a reason Kong does this? Would it make sense for Kong to extract the hostname exactly, and only include the port number in the outgoing Host header if it was also explicitly specified in upstream_url? That would leave it up to the Kong admin to determine what the Host header looks like.

**Comment by thibaultCha** [comment]
The port is included because it is allows by the [section 14.23](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23) of the HTTP/1.1 specs. Most of the time it is stripped out when it is the default port, but now always.

**Comment by thefosk** [comment]
@ondrej I agree with @thibaultCha that if the server doesn't support a port number in the `Host` header, that seems to be more of a problem of the server since it's part of the HTTP specification.
