### ISSUE TITLE
I always get this message: "HMAC signature cannot be verified"

### ISSUE THREAD

**Issue by MyungjinJung** [Mashape/kong#870]
I am trying to get Kong - hmac-auth to work, I am prototyping with this go-lang client.

this data has sent as like:
```
POST /api/v1/CreateUploadSession/601/n HTTP/1.1
Host: specific IP
User-Agent: Go-http-client/1.1
Content-Length: 0
Authorization: hmac username="jaster",algorithm="hmac-sha1",headers="date",signature="BnagiHTk8d9pPkFfNoZYAjb1yNI%3D"
Content-Type: application/json
Date: Wed, 13 Jan 2016 13:50:39 GMT
Accept-Encoding: gzip
```

signatureString created as like :
`Wed,13 Jan 2016 02:17:06 GMT`

however, Kong(0.5.4) always return 
`{"message":"HMAC signature cannot be verified, a valid date or x-date header is required for HMAC Authentication"}`

Please, could you tell what is the problem or something wrong with me ?

**Comment by MyungjinJung** [comment]
Additonally,  it is the dockerized kong version  from the official url.

**Comment by shashiranjan84** [comment]
That error is thrown either date headers are missing  or clock skew is higher than configured value. What is clock skew set in configuration. Your kong box and client need be in sync. For test purpose add x-date header with gmt date and set clock skew to a very high value

**Comment by MyungjinJung** [comment]
Thanks shashiranjan84,
Yes. you are right, docker's system time was different with the HOST. 
So, when docker starts , it needs this parameter "-v /etc/localtime:/etc/localtime:ro" . 
otherwise it couldn't be sync with the CLOCK_CKEW policy. 

There is  my client code and it works correctly.
```go 
	key := []byte("secret5825")
	h := hmac.New(sha1.New, key)
	h.Write([]byte(signatureString))
	sigString := base64.StdEncoding.EncodeToString(h.Sum(nil))
req.Header.Add("Authorization", fmt.Sprintf("hmac username=\"jaster\",algorithm=\"hmac-sha1\",headers=\"date\",signature=\"%s\"", sigString))
```
thank you for your comment. shashiranjan84

**Comment by shashiranjan84** [comment]
@MyungjinJung  welcome :), would you please close the ticket if you don't have any further doubt?

**Comment by thibaultCha** [comment]
Oops, did not see this comment before closing. Feel free to re-open if ever.

**Comment by MyungjinJung** [comment]
No problems, I have no any concern, thanks
