### ISSUE TITLE
Kong ssl plugin does not preserve certificate chain

### ISSUE THREAD

**Issue by cleblanc87** [Mashape/kong#872]
When uploading an ssl certificate to kong, the shelled out `openssl` call does not preserve the full certificate chain as detailed here: https://github.com/openresty/lua-nginx-module/issues/563#issuecomment-160051384

To reproduce, upload an ssl cert with intermediate certificate.
Check the response JSON's `_cert_der_cache` field, this will not contain the full cert, whereas the `cert` field of the response will.

This will produces the following openssl error, (same as seen in the lua-nginx-module issue thread)
`Verify return code: 21 (unable to verify the first certificate)`

**Comment by thefosk** [comment]
@cleblanc87 the fix for this has been pushed and it's in `next`. Will be available in the next version.

**Comment by lsh-0** [comment]
has this made a release yet?

**Comment by thefosk** [comment]
@lsh-0 yes
