### ISSUE TITLE
ELK integration 

### ISSUE THREAD

**Issue by sinzone** [Mashape/kong#879]
Plugin that connects to the ELK stack.

**Comment by thefosk** [comment]
This can already be done using the TCP/UDP Log plugin.

**Comment by samek** [comment]
@sinzone  exactly this is what we're using. 
UDP log ---> logStash --> Elastic search, then view it in Kibana .

**Comment by moyuanhui** [comment]
@sonicaghi do you know tcp how to config elk ,can u get me a blogs

**Comment by moyuanhui** [comment]
@samek get me a solution~~

**Comment by subnetmarco** [comment]
@moyuanhui you can use the TCP Logging plugin to send data to Logstash, and from Logstash store it into Elasticsearch and visualize it into Kibana.

**Comment by debu99** [comment]
in my case, the logstash ssl_verify_mode set to force_peer, the client requires the cert to, how to make the TCP support ssl cert

**Comment by prcongithub** [comment]
Can't we push logs from Kong directly to ElasticSearch? It has a TCP server listening on 9300.
