### ISSUE TITLE
Kong fails to match request_path ="/" ?

### ISSUE THREAD

**Issue by leozc** [Mashape/kong#880]
To reproduce:
> curl localhost:8001/apis
{"data":[{"upstream_url":"https:\/\/example.com\/","request_path":"\/api\/v2","id":"YYYY","name":"api-v2","created_at":xxx}
{"data":[{"upstream_url":"https:\/\/example.com\/","request_path":"\/","id":"xxx","name":"","created_at":xxx}]}

> curl localhost:8000
{"request_path":"\/","message":"API not found with these values","request_host":["localhost"]}

However if request to:
> curl localhost:8000/api/v2
this is fine.

**Comment by thibaultCha** [comment]
Yes, `/` is not considered to be a valid request path. In fact it should have not been possible to create an API with this value...

**Comment by leozc** [comment]
Arh, great, I meant to use / as a fallback value

**Comment by thibaultCha** [comment]
Were you abel to create an API with a `request_path` value of `/`? If so, that is not supposed to be so, there should have been an error.

**Comment by leozc** [comment]
@thibaultCha  yes I am able to create an API with a request_path value of "/".

kong --version
Kong version: 0.5.4
