### ISSUE TITLE
OAuth2 provision_key is not returned anymore when adding oauth2 plugin on an api in v0.5.4

### ISSUE THREAD

**Issue by t1tcrucible** [Mashape/kong#887]
When using Kong v0.5.4 - after applying an oauth2 policy to a pre-created api. The response lacks the provision_key.
When I rollback to Kong v0.5.3 - the provision_key is back. I checked in the release notes and documentation; but it seems that the provision_key is still expected. Is that correct?

**Comment by t1tcrucible** [comment]
For information, we could work around this issue. In stead of expecting Kong to generate automatically a UUID as provision key - we add the provision_key as a parameter when adding the OAuth plugin to an API.

**Comment by thefosk** [comment]
@t1tcrucible I cannot replicate this problem - is there any exception in the `error.log` file?

**Comment by Tieske** [comment]
@t1tcrucible any update on this? still an issue or can it be closed?
