### ISSUE TITLE
Kong responds with a 401 with no Auth plugin enabled and no Authorization header in request

### ISSUE THREAD

**Issue by siddharthkchatterjee** [Mashape/kong#890]
Kong (kong-0.5.4-1, CASSANDRA_VERSION=2.1.10) seems to be in some kind of inconsistent state where the lack of an `Authorization` header results in a `401 Unauthorized` response even though the HMAC plugin is **not** enabled on the route. 

Calling /tag-list/plugins for a route called `tag-list` returns this —

```
{
  "data": [
    {
      "api_id": "ab02edb3-648f-44b5-c470-4823cd7d9f7d",
      "id": "3b44d473-367f-4d85-cd5b-ac9eee2f1c13",
      "created_at": 1453202992000,
      "enabled": true,
      "name": "rate-limiting",
      "config": {
        "second": 50
      }
    },
    {
      "api_id": "ab02edb3-648f-44b5-c470-4823cd7d9f7d",
      "id": "356e2d4b-4e11-421d-c294-84cef3223f15",
      "created_at": 1453202993000,
      "enabled": true,
      "name": "file-log",
      "config": {
        "path": "/tmp/file.log"
      }
    },
    {
      "api_id": "ab02edb3-648f-44b5-c470-4823cd7d9f7d",
      "id": "afc17326-0971-4825-c864-be9bc5609ffc",
      "created_at": 1453202991000,
      "enabled": true,
      "name": "cors",
      "config": {
        "preflight_continue": false,
        "credentials": false
      }
    }
  ]
}
```

We use some JavaScript to setup our routes on Kong. This inconsistent state only occurs one out of three times or so but is easily reproducible. I tried to take a look at error.log in the `debug` level but it doesn't seem to print anything of circumstance. 

```
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:74: init_plugins(): Discovering used plugins
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: ssl
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: jwt
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: acl
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: cors
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: oauth2
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: tcp-log
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: udp-log
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: file-log
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: http-log
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: key-auth
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: hmac-auth
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: basic-auth
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: ip-restriction
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: mashape-analytics
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: request-transformer
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: response-transformer
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: request-size-limiting
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: rate-limiting
2016/01/19 11:29:16 [notice] 25539#0: [lua] kong.lua:94: init_plugins(): Loading plugin: response-ratelimiting
```

Here is the script you can use to reproduce this —

```
// setup.js
var format = require('url').format;
var request = require('request');
var Promise = require('bluebird');

var routes = require('./routes.js');
var config = require('./config');

let requestKongAdmin = Promise.promisify(request.defaults({
	baseUrl: format(config.kong.admin),
	json: true
}));

let addAPI = function (configuration) {
	let options = {
		method: 'POST',
		uri: '/apis',
		body: {
			name: configuration.name,
			upstream_url: format(config.self), //eslint-disable-line camelcase
			request_path: configuration.url //eslint-disable-line camelcase
		}
	};
	return requestKongAdmin(options)
		.then(() => configuration);
};

let deleteAPI = function (configuration) {
	let options = {
		method: 'DELETE',
		uri: `/apis/${configuration.name}`
	};

	return requestKongAdmin(options)
		.then(() => configuration);
};

var listAPIs = function () {
	let options = {
		method: 'GET',
		uri: '/apis'
	};
	return requestKongAdmin(options)
		.spread((_, body) => body.data);
};

let enableAuth = function (configuration) {
	let options = {
		method: 'POST',
		uri: `/apis/${configuration.name}/plugins`,
		json: {
			name: 'hmac-auth'
		}
	};
	if (configuration.auth) {
		return requestKongAdmin(options)
			.then(() => configuration);
	} else {
		return Promise.resolve(configuration);
	}
};

let enableCORS = function (configuration) {
	let options = {
		method: 'POST',
		uri: `/apis/${configuration.name}/plugins`,
		json: {
			name: 'cors'
		}
	};
	return requestKongAdmin(options)
		.then(() => configuration);
};

let enableRateLimiting = function (configuration) {
	let options = {
		method: 'POST',
		uri: `/apis/${configuration.name}/plugins`,
		json: {
			name: 'rate-limiting',
			'config.second': config.kong.rateLimitingSeconds
		}
	};
	return requestKongAdmin(options)
		.then(() => configuration);
};

let enableFileLog = function (configuration) {
	let options = {
		method: 'POST',
		uri: `/apis/${configuration.name}/plugins`,
		json: {
			name: 'file-log',
			'config.path': config.kong.fileLogLocation
		}
	};
	return requestKongAdmin(options)
		.then(() => configuration);
};

listAPIs()
	.map(deleteAPI)
	.return(routes)
	.map(route => {
		return addAPI(route)
			.then(enableAuth)
			.then(enableCORS)
			.then(enableRateLimiting)
			.then(enableFileLog);
	});

// './config';
{
	"self": {
		"protocol": "http",
		"hostname": "localhost",
		"port": 3000
	},
	"kong": {
		"admin": {
			"protocol": "http",
			"hostname": "localhost",
			"port": 8001
		},
		"rateLimitingSeconds": 50,
		"fileLogLocation": "/tmp/file.log"
}

// routes.js
module.exports = [
	{
		name: 'login',
		url: '/admin/login',
		method: 'POST',
		auth: true
	},
	{
		name: 'logout',
		url: '/admin/logout',
		method: 'POST',
		auth: false
	},
	{
		name: 'list-events',
		url: '/events',
		method: 'GET',
		auth: true
	}
];
```

`routes.js` on average has around 50 or so routes.

**Comment by ahmadnassri** [comment]
would this be better titled as:

> "Kong responds with a `401` when no Auth plugin is enabled and request include an `Authorization` header"

?

**Comment by shashiranjan84** [comment]
@siddharthkchatterjee what makes you conclude that HMAC plugin throwing `401`

**Comment by shashiranjan84** [comment]
@thefosk it seems like invalidation problem, do 0.6.0 resolve this issue?

**Comment by thefosk** [comment]
Can you create a test case on 'next' branch?

**Comment by siddharthkchatterjee** [comment]
@shashiranjan84 The response is a 401, Unauthorized. I am pretty certain that is thrown by the plugin since adding an authorization header resolves this, if I'm not wrong. 

@thefosk I will try to reproduce this on the latest 0.6.0rc (next).

**Comment by siddharthkchatterjee** [comment]
@shashiranjan84 @thefosk 

This still occurs on the `next` branch.

**Comment by siddharthkchatterjee** [comment]
@thefosk Any update on this? We're unfortunately going to have to switch to another gateway if we can't fix this because it makes it pretty unusable for us if there is such inconsistency.

**Comment by thefosk** [comment]
@siddharthkchatterjee I will take ownership of this ticket. To reproduce the problem, can you please give the bare minimum HTTP requests that I need to execute? Possibly in curl format or pseudo-code.

**Comment by siddharthkchatterjee** [comment]
@thefosk As far as we know, this has been hard to reproduce unless the number of requests are significant. The script above reproduces this pretty consistently when the number of routes is high enough but I'm not sure of a bare minimum required. That's where our guess that perhaps this has to do with concurrency, comes from.

**Comment by thefosk** [comment]
@siddharthkchatterjee - before investigating further, could you update Kong to the latest version?

**Comment by siddharthkchatterjee** [comment]
I have. The problem persists with the latest version as well. 

Sent from Outlook Mobile




On Thu, Feb 18, 2016 at 11:57 AM -0800, "Marco Palladino" <notifications@github.com> wrote:












@siddharthkchatterjee - before investigating further, could you update Kong to the latest version?

**Comment by thefosk** [comment]
@siddharthkchatterjee I am trying to create a test case to replicate this issue. The plugins that you have added are `rate-limiting`, `cors` and `file-log`. Is it correct?

Could it be that the upstream server is returning `401` (and not Kong)? I am confused as to why you think it's the HMAC plugin returning this status code, if the HMAC plugin has not been installed?

**Comment by siddharthkchatterjee** [comment]
@thefosk I am also adding the `hmac-auth` plugin. If you look at the code above, you'll see an `enableAuth` function that makes the request to enable that plugin as well.

**Comment by thefosk** [comment]
Okay, so isn't it correct that the HMAC plugin refuses requests without an `Authorization` header?

**Comment by siddharthkchatterjee** [comment]
@thefosk Correct, but in my example above the route doesn't have the `hmac-auth` plugin enabled and still returns a 401. I am certain that it isn't the upstream server since if I pass an appropriate `Authorization` header, the request goes through. 

We have even seen the reverse where the `hmac-auth` plugin is enabled but does not function, hence my guess that it is some kind of inconsistency.

**Comment by siddharthkchatterjee** [comment]
@thefosk I could setup a test environment on an instance on AWS and reproduce the issue for you if that helps.

**Comment by thefosk** [comment]
Maybe I am wrong, but in the code I don't see the HMAC plugin being set to `enabled: false`. When you say the plugin is not enabled, do you mean that it has been added but it's disabled, or that it's not added at all?

**Comment by siddharthkchatterjee** [comment]
@thefosk If you notice, inside the `enableAuth` function, the HTTP request to the Kong Admin API to enable `hmac-auth` is only made if the configuration object has the `auth` key set to true. In case of the examples, the second route object in `routes.js` has auth set to false and I am certain that the request to Kong is not made since an empty Promise is resolved. 

Even though the request is not made, `Authorization` still seems necessary. That is the problem.

**Comment by thefosk** [comment]
@siddharthkchatterjee can we try to replicate this with some simple curl commands? I have executed the following commands:

## Adding API

```shell
$ curl -d "request_path=/test" \
       -d "strip_request_path=true" \
       -d "upstream_url=http://httpbin.org" 127.0.0.1:8001/apis
```
```json
{
	"upstream_url": "http:\/\/httpbin.org",
	"request_path": "\/test",
	"id": "8908dc98-b5be-47b7-a685-6aa824f8edf9",
	"name": "test",
	"created_at": 1456183585000,
	"strip_request_path": true
}
```

## Adding HMAC plugin

```shell
$ curl -d "name=hmac-auth" 127.0.0.1:8001/apis/8908dc98-b5be-47b7-a685-6aa824f8edf9/plugins/
```
```json
{
	"api_id": "8908dc98-b5be-47b7-a685-6aa824f8edf9",
	"id": "d5eb1d39-9edd-42ec-aa37-603e54f68655",
	"created_at": 1456183727000,
	"enabled": true,
	"name": "hmac-auth",
	"config": {
		"hide_credentials": false,
		"clock_skew": 300
	}
}
```

## Consuming API

### With HMAC enabled

```shell
$ curl -i 127.0.0.1:8000/test/get
```
```json
{"message":"Unauthorized"}
```

Correct, because we didn't send any `Authorization` header.

### With HMAC disabled

Let's disable HMAC first:

```shell
$ curl -X PATCH -d "enabled=false" http://127.0.0.1:8001/apis/8908dc98-b5be-47b7-a685-6aa824f8edf9/plugins/d5eb1d39-9edd-42ec-aa37-603e54f68655
```
And make the request without `Autorization`:

```shell
$ curl -i 127.0.0.1:8000/test/get
```
```json
{
	"args": {},
	"headers": {
		"Accept": "*/*",
		"Host": "httpbin.org",
		"User-Agent": "curl/7.43.0"
	},
	"origin": "127.0.0.1, 40.140.33.170",
	"url": "http://httpbin.org/get"
}
```

Seems to be working.

**Comment by siddharthkchatterjee** [comment]
@thefosk, this doesn't fail generally for a route at a time but occurs in one of fifty routes when my script is run. In fact, my script makes the same set of requests that you have pointed out. But I am certain that this occurs. The only thing is that it isn't deterministic. It seems to occur for a random route every time I setup all the routes using my script. 

That's why I think it could be a data inconsistency issue or some kind of concurrency issue. Would you like me to setup an environment and reproduce this to demonstrate? That ought to help.

**Comment by thefosk** [comment]
@siddharthkchatterjee yes, that would help to replicate the problem

**Comment by siddharthkchatterjee** [comment]
@thefosk, closing this since the issue is identified more precisely in #1144.
