### ISSUE TITLE
Is it possible to use Kong transparently ?

### ISSUE THREAD

**Issue by KrishnaPG** [Mashape/kong#894]
We are evaluating Kong, and from the quick example [here](https://getkong.org/docs/0.5.x/getting-started/adding-your-api/) it looks like Kong needs a `header` to be explicitly set by end-user to function properly.

This requires our customer to know two things: 1. the front end Kong proxy and 2. the back-end real host, which is not an ideal situation.

It is possible to make Kong work transparently (without having to specify explicit host header)?  For example, `path based routing`?

The goal is: Customer should only know about one Host and he should get all behavior from that,  without having to explicitly state 'connect to this, but fetch that' kind of requests. (For example, a typical `curl http://my-site.com/api/` should work normally without having to use the explicit headers)

If headers cannot be avoided, one question we have is: since customer knows the real host, what is preventing them from using that original host directly, instead of going through the Kong front-end?

**Comment by ahmadnassri** [comment]
yes, path based routing is available out of the box.

`request_path` and `request_host` are semi optional, meaning you can use either one to define your API
