### ISSUE TITLE
Impossible to retrieve clear auto-generated basic authentication password

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#901]
When creating the credentials for Basic Authentication, if the password is not specified the system will auto-generate a password. The problem is the API response doesn't give back the clear-text password that has been auto-generated, thus is impossible to use.

**Comment by thibaultCha** [comment]
Duplicate of #771, which has more subtleties, but includes this:

> when creating a credential without a password, the password is auto-generated. But the answer to that request should include the password, otherwise the Consumer never knows the password that was chosen. 2 solutions: disable password auto-generation, or show the plain password ONLY on a result from POST/PUT.

**Comment by Tieske** [comment]
closing this as it is a duplicate
