### ISSUE TITLE
Better http_client.lua

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#903]
That can handle requests for both LuaSocket and OpenResty.

**Comment by thibaultCha** [comment]
Even better would be to drop LuaSocket support and run the CLI and the tests with the `resty` interpreter. From there we can use https://github.com/pintsized/lua-resty-http directly.

**Comment by thefosk** [comment]
We would still need to rewrite `http_client.lua` because we are making requests in multiple places now, the HTTP Log plugin and the upcoming Pushpin plugin (and I can see it being by other plugins too).

**Comment by thibaultCha** [comment]
No we wouldn't, we would just switch to using lua-resty-http.

**Comment by thefosk** [comment]
I will use https://luarocks.org/modules/pintsized/lua-resty-http for inside openresty.
