### ISSUE TITLE
Refactor Applications

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#91]
Applications should support the following features:

* Whitelisted APIs
* Blacklisted APIs
* #87 

And should be more intuitive to use. @montanaflynn brought up the following issue: it is possible to create applications even if no authentication is being enabled, and the application properties depend on the authentication type that has been configured. 

For the last point maybe Application's should be authentication-related by supporting a list of `authentication_types`, as discussed at #18. More or less `authentication_types` can be added to an Application depending what authentication schemes the API has installed through the relative Plugins.

**Comment by thibaultCha** [comment]
Since yesterday we decided to ditch out the concept of applications in favour of `consumers` + still have multiple keys per authentication type, this issue kind of becomes obsolete. Update with yesterday's discussion in #18. #87 is still relevant.
