### ISSUE TITLE
Adding the Cassandra SSL certificate to lua_ssl_trusted_certificate

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#915]
Reimplement this directive https://github.com/Mashape/kong/blob/0.5.4/kong/cli/utils/signal.lua#L106

**Comment by thefosk** [comment]
This has been implemented with #921.

**Comment by mars** [comment]
I'm using kong/master at 282481ba572bf4a6ed6172664cc6b8de7da0416a (which includes this commit) and cannot connect to Cassandra via SSL.

The same error as we experienced together at the meetup is occurring now:
```
2016/02/03 22:34:17 [error] 73#0: [lua] cluster.lua:84: Cassandra error: NoHostAvailableError: All hosts tried for query failed. 10.1.13.186:9042: SocketError: 18: self signed certificate for socket with peer 10.1.13.186:9042. 10.1.16.105: SocketError: 18: self signed certificate for socket with peer 10.1.16.105. 10.1.60.153: SocketError: 18: self signed certificate for socket with peer 10.1.60.153., context: ngx.timer
```

I do have the template value in the Nginx config:
```
nginx: |
  …
  http {
    …
    {{lua_ssl_trusted_certificate}}
```

I see in the rendered `nginx.conf` that the value is inserted:
```
http {
  …
  lua_ssl_trusted_certificate "/app/config/cassandra.cert";
```

It references a valid certificate file (used successfully with Kong 0.5.4):
```
~ $ cat /app/config/cassandra.cert
-----BEGIN CERTIFICATE-----
…
-----END CERTIFICATE-----
```

Our fix of manually inserting the certificate path into the Nginx config as `lua_ssl_trusted_certificate '/app/config/cassandra.cert';` no longer works, either.

Kong 0.5.4 can still connect to this Cassandra cluster via SSL using the same certificate, so I'm pretty certain it's not a higher-level Cassandra connection problem.

**Comment by thibaultCha** [comment]
Using the current master I have no problem connecting Kong to my local Cassandra cluster with SSL and certificate verification enabled:

```yaml
  ssl:
    enabled: true
    verify: true
    certificate_authority: "/paht/to/cassandra.pem"
```

Would you mind giving it a try?

**Comment by mars** [comment]
Yes! Using kong/master at df123de2a1ee2dde5284cf6bc25da8b6622eb587 now allows Cassandra SSL certficates to be verified!

:fireworks: :cocktail:

**Comment by thibaultCha** [comment]
Very good!
