### ISSUE TITLE
CLI roadmap

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/kong#92]
Following #83 and #88, TODO for the CLI:

- [ ] Validate configuration (so we don't try to start Kong with a broken conf)
- [ ] Add apis/consumers #147
- [x] Restart
- [x] Reload #113
- [ ] Plugins installation

**Comment by thefosk** [comment]
I use `restart` a lot, it would be nice to have it and shouldn't be hard to implement.

**Comment by thibaultCha** [comment]
Closing this, outdated.
