### ISSUE TITLE
Log streams go silent with Nginx `daemon off`

### ISSUE THREAD

**Issue by mars** [Mashape/kong#920]
With container runtimes like Docker & Heroku, the initial process of an app must remain running, attached to the parent process. Otherwise, when the process daemonizes, the container will appear finished.

For reference:
- [Heroku foreground execution](https://devcenter.heroku.com/articles/runtime-principles#foreground-execution)
- [Official Nginx Dockerfile `CMD`](https://github.com/nginxinc/docker-nginx/blob/master/Dockerfile#L19)

As of **Kong 0.6.0**, when Nginx is configured with:
- `daemon off;` and
- `error_log stderr debug;`

…the stderr stream goes silent. No more output. The stderr stream last worked with Kong 0.5.4.

Some debugging with @thefosk at the meet-up last night revealed that the errors are being sent to Mashape's syslog though.

Also, some cursory exploration of the new release revealed that Serf module is hardcoded to [write to](https://github.com/Mashape/kong/blob/0.6.0/kong/cli/services/serf.lua#L158) & [pull last error from](https://github.com/Mashape/kong/blob/0.6.0/kong/cli/services/serf.lua#L174) a log file.

**Comment by mars** [comment]
Further exploration has revealed that this is symptomatic of a higher-level issue. (Though still unsure why exactly it did not become an issue until 0.6.0.)

The `kong start` command spawns all the services (nginx, dnsmasq, serf) and then exits. Ideally, to be compatible with containers like Docker & Heroku, `kong start` CLI would offer a "foreground" or "no-daemonize" mode so that it does not exit, but instead remains attached to the parent process until either SIGTERM or SIGQUIT is received, or a child process exits/crashes.

This problem is beginning to smell like something that a real process supervisor would be better fit to solve, like [supervisor](https://github.com/Supervisor/supervisor). Instead of [using Lua](https://github.com/Mashape/kong/blob/0.6.0/kong/tools/io.lua#L33) to [start each service](https://github.com/Mashape/kong/tree/0.6.0/kong/cli/services) as a daemonized system process.

**Comment by thibaultCha** [comment]
Thanks for the detailed explanation, we'll investigate this. Still unsure where this is coming from...

> This problem is beginning to smell like something that a real process supervisor would be better fit to solve

Totally with you here.

**Comment by opyate** [comment]
This problem is masked in the docker-kong repo by the addition of `&& tail -f /log/...` in [this commit](https://github.com/Mashape/docker-kong/commit/33eb3edc61a191b4bc4067258ce34def01234eb7#diff-3254677a7917c6c01f55212f86c57fbfR14). Without the tail, the container exits.

**Comment by thefosk** [comment]
This will be finally fixed in the Kong 0.11 Docker image, since `nginx` becomes the only dependency (`dnsmasq` and `serf` are gone). I have been experimenting with a custom 0.11 build and you can see [here](https://github.com/Mashape/docker-kong/blob/0.11.x/Dockerfile#L16) that `nginx` is the only process running.

The final Kong 0.11 Docker image will implement this behavior by default. Closing this issue now.
