### ISSUE TITLE
502 Bad gateway in html format

### ISSUE THREAD

**Issue by codebien** [Mashape/kong#927]
Kong version: 0.6.0

If upstream is unreachable Nginx returns a bad gateway response in HTML format. IMO a JSON response would be better.

Thank you for this great product!

**Comment by codebien** [comment]
Sorry, I miss #163!

**Comment by thefosk** [comment]
This will require a configuration change and can land in 0.7.0. I will work on it.

**Comment by elruwen** [comment]
I would be nice if one could configure an error page per API. Maybe even per status code and having a catch all. Of course if those pages fail, one could still show the current error page, but it would at least allow a little bit more customisation.

**Comment by thefosk** [comment]
Once this issue is closed, a next iteration on the feature could include what @elruwen is suggesting. I opened #972 to keep track of this.

**Comment by elruwen** [comment]
Thanks!
