### ISSUE TITLE
Source install: `serf_event.sh` not generated; LuaJIT cannot be found

### ISSUE THREAD

**Issue by mars** [Mashape/kong#933]
When installing from source, OpenResty itself installs LuaJIT at `$PREFIX/luajit/bin/luajit-2.1.0-alpha`

It seems that Kong does not honor the environment's `$PATH` to find LuaJIT, instead searching a fixed [table of paths](https://github.com/Mashape/kong/blob/0.6.0/kong/cli/services/base_service.lua#L20):
```
    "/usr/local/sbin",
    "/usr/local/bin",
    "/usr/sbin",
    "/usr/bin",
    "/bin"
```

The result is that after building from source, the [Serf prepare method quietly bails on creating the event handler script](https://github.com/Mashape/kong/blob/0.6.0/kong/cli/services/serf.lua#L49).

What do you think of building this table of paths with something like the following, so that Kong will honor the layout of the host?
```lua
function env_path()
  local path_string = os.getenv('PATH')
  local paths = {}
  for path in string.gmatch (path_string, "[^:]+") do
    table.insert(paths, path)
  end
  return paths
end
```

**Comment by shashiranjan84** [comment]
@mars you would need to put serf directory on the PATH. Check CI build for refrence

https://github.com/Mashape/kong/blob/master/.travis.yml

**Comment by mars** [comment]
@shashiranjan84 In this situation, serf is started correctly:
```
==> Starting Serf agent RPC...
         Node name: …
          RPC addr: '127.0.0.1:7373'
          Snapshot: false

buildpack=runit ps=dnsmasq at=start
==> Starting Serf agent...
==> Serf agent running!
         Bind addr: '10.0.158.174:7946'
         Encrypted: true
           Profile: wan
==> Log data will now stream in as it occurs:
```

…but the `serf_event.sh` file is missing:
```
[ERR] agent: Error invoking script '/app/nginx-working/serf_event.sh': exit status 127
```

Serf is clearly in the `PATH` already.

I'm pretty certain this is an issue with the [code that generates `serf_event.sh`](https://github.com/Mashape/kong/blob/0.6.0/kong/cli/services/serf.lua#L49).

**Comment by thibaultCha** [comment]
There used to be a [special value](https://github.com/Mashape/kong/blob/0.5.4/kong/cli/utils/signal.lua#L54) in the Lua code for services executables which would search in the `$PATH` (no need to manually parse it). I am curious as to why it was removed.

Secondly, I do not see the need to check on the Lua side if LuaJIT is in the `$PATH`: if the Kong CLI is being executed at all, it means the `luajit` interpreter is *probably* [already in it](https://github.com/Mashape/kong/blob/master/bin/kong#L1), but why not.

Finally, I wonder why we would need to do that in Lua, when the bash script could probably handle it better (the `serf_event.sh` could simply search for `luajit` itself).

**Comment by thibaultCha** [comment]
> When installing from source, OpenResty itself installs LuaJIT at $PREFIX/luajit/bin/luajit-2.1.0-alpha

Regarding this, I believe you would still have to add the `luajit` interpreter to your `$PATH` in order to run the CLI (as per the shebang link in my previous comment).

There are plans to make an install script which would install a properly *bundled/not-system-wide* Kong (LuaJIT + OpenResty + Luarocks + Kong resulting in something like `$PREFIX/bin/kong` and `$PREFIX/sbin/nginx|luajit|luarocks`), and hence, would allow us to use the same LuaJIT interpreter from both the CLI and OpenResty without touching one's `$PATH`.

**Comment by thibaultCha** [comment]
> It seems that Kong does not honor the environment's $PATH to find LuaJIT

Labelling this issue as a bug because of this.

Possible fixes:
- Re-implementing the empty value in the prefixes which triggers a search in the PATH ( believe this is needed regardless of wether or not we still do this check from Lua
- Think about the bash script being a better solution to find the LuaJIT interpreter (there might be no need to check this in the Lua side).

**Comment by thefosk** [comment]
A common reason why the `serf_event.sh` file is not created is because the process does not have write permissions to the folder. Can you try to `chmod -R +wr nginx_working_dir` and restart kong?

**Comment by mars** [comment]
**Symlinking OpenResty's LuaJIT binary into the `PATH` solves this issue.**

For example, if the configured prefix for OpenResty is `/app`:
```bash
./configure --prefix=/app --with-pcre-jit --with-ipv6 --with-http_realip_module --with-http_ssl_module --with-http_stub_status_module --with-openssl=${OPENSSL_DIR}
```

…and `/app/bin` is in Kong's runtime `PATH`:
```bash
export PATH=/app/bin:$PATH
```
…then symlinking `luajit` into the `PATH` will allow `serf_event.sh` to be generated:
```bash
ln -s /app/luajit/bin/luajit-2.1.0-alpha /app/bin/luajit
```

So it's now it seems obvious  :crystal_ball:  that [`IO.cmd_exists()` is used to check for the command in the environment's `PATH`](https://github.com/Mashape/kong/blob/0.6.0/kong/cli/services/base_service.lua#L11) before deferring to that fixed table of bin paths.

**Comment by thefosk** [comment]
@mars that is correct - `IO.cmd_exists()` is used to check for the command into the env `PATH`, and it will fallback on those pre-defined location only if the command cannot be found.

**Comment by thibaultCha** [comment]
I am confused now: since LuaJIT was not in your PATH, how were you able to use the Kong CLI? LuaJIT's interpreter must be in one's PATH to use Kong.

**Comment by thefosk** [comment]
Maybe the `kong` executable hard codes the location of LuaJIT, like:

```
#!/bin/sh

exec '/usr/local/bin/luajit'

...
```

**Comment by mars** [comment]
The reason Kong CLI worked for me, even though `luajit` was not in my path, is that `bin/kong` is generated as a shell script that explicitly loads package paths from build-time environment, and it couldn't find `luajit` either so defaulted to `lua` :fearful: 

Here's what mine looks like from a source installation using custom prefix:
```bash
~ $ cat `which kong`
#!/bin/sh

exec '/app/.heroku/bin/lua' -e 'package.path="/app/.luarocks/share/lua/5.1/?.lua;/app/.luarocks/share/lua/5.1/?/init.lua;/app/.heroku/share/lua/5.1/?.lua;/app/.heroku/share/lua/5.1/?/init.lua;"..package.path; package.cpath="/app/.luarocks/lib/lua/5.1/?.so;/app/.heroku/lib/lua/5.1/?.so;"..package.cpath' -e 'local k,l,_=pcall(require,"luarocks.loader") _=k and l.add_context("kong","0.5.4-1")' '/app/.heroku/lib/luarocks/rocks/kong/0.5.4-1/bin/kong' "$@"
```

Clearly building from source is missing this LuaJIT linking.

**Comment by thibaultCha** [comment]
Oh I see, alright then! Closing this?

**Comment by mars** [comment]
This symlink doesn't make `luajit` used in `bin/kong`, but that's not this bug!

Might it be worth adding this step to the [Install from Source](https://getkong.org/install/source/) docs?

**Comment by thibaultCha** [comment]
> Also make sure to add it [luajit] to your $PATH so the Kong CLI can find it.

Are we talking about adding this step to it? I am confused now ^^

**Comment by mars** [comment]
Yes, that is true. Specifically:

`ln -s $PREFIX/luajit/bin/luajit-2.1.0-alpha $PREFIX/bin/luajit`
is the symlink required from a source install of OpenResty.

`$PREFIX` is the value passed to OpenResty `./configure --prefix`

Clearly there are other ways `luajit` may be available, as long as it's findable on the env `PATH`. Using the one bundled with OpenResty avoids variability in the runtime CLI vs Nginx.

**Comment by thibaultCha** [comment]
Yes, then this (having `luajit` in your `$PATH`) is already instructed in the installation steps (my quote comes from getkong.org/install)

**Comment by mars** [comment]
Sounds good! Thanks everyone for the help. Source install is not for the faint of heart :8ball:

**Comment by thibaultCha** [comment]
Yes, most definitely not! We're aware of it, and that's why we provide as many package distributions as we can.

I am really eager to start working on a proper source install setup (the one with `./configure --prefix=...` which bundles everything in the prefix). And just after that, allowing ENV variables for configuration. Those two features together would make Kong very easy to setup anywhere! I am currently busy on the Postgres implementation and various bug fixes though...

**Comment by mars** [comment]
BTW, here are all the prefix-related source install commands that finally made LuaJIT first-class for my build:

```bash
# LuaJIT
make PREFIX=${APP_PREFIX}
make install PREFIX=${APP_PREFIX}
ln -sf luajit-2.1.0-beta1 ${APP_PREFIX}/bin/luajit

# OpenResty
./configure --prefix=${APP_PREFIX} --with-luajit=${APP_PREFIX} --with-pcre-jit --with-ipv6 --with-http_realip_module --with-http_ssl_module --with-http_stub_status_module --with-openssl=${OPENSSL_DIR}

# LuaRocks
./configure --prefix=${APP_PREFIX} --lua-suffix=jit --with-lua=${APP_PREFIX} --with-lua-include=${APP_PREFIX}/include/luajit-2.1

# runtime environment
export PATH=${APP_PREFIX}/bin:${PATH}
```

**Comment by thibaultCha** [comment]
Yes, this is how Kong is installed in Travis (https://github.com/Mashape/kong/tree/master/.ci)
