### ISSUE TITLE
Incompatible serf versions aren't messaged clearly

### ISSUE THREAD

**Issue by ThorArakis** [Mashape/kong#946]
It's a pretty small issue, but got me for a couple hours today. The error message returned when starting up kong with a bad version of serf is the same as if serf is totally missing:
```
[ERR] Can't find serf
[ERR] Could not start Kong
```

It would be great if the error could be more explicit.

**Comment by ThorArakis** [comment]
I was hoping it could be as simple as tossing in a warn somewhere around here: https://github.com/ThorArakis/kong/blob/master/kong/cli/services/serf.lua#L31
But my lua-foo isn't so strong and I'm struggling with calling warn/error in that method.

**Comment by ThorArakis** [comment]
Possible fix: https://github.com/Mashape/kong/pull/947

**Comment by Tieske** [comment]
superseded by #1221 against branch `refactor/cli`
