### ISSUE TITLE
Rate limiting per consumer (using jwt auth) doesn't appear to be working with a custom `key_claim_name`

### ISSUE THREAD

**Issue by ThorArakis** [Mashape/kong#948]
I am currently trying to get rate limiting working with the JWT plugin. I found the following use cases seem to work just fine:
global rate limiting (aka: rate limit not associated with a consumer_id) and using jwt auth with `iss` claim
rate limiting per consumer with `iss` claims
global rate limiting and auth when using `aud` as `config.key_claim_name`
fyi: I'm also using base_64 encoded keys

However, when the API is auth'ed with the custom `key_claim_name` and I attempt to associate a new rate limit with a consumer_id it doesn't appear to work. I currently have a global policy on that API for 5 per minute, and I added a 2 per minute consumer related end point. But the global rate limit is still showing up. 

I then deleted the global rate limit so the only 2 plugins on the api were the JWT auth and the rate limiting with the consumer_id and there were no rate limit headers returned on the response and no throttling when over limit.

I checked the request headers being sent to the backend server and found that the `X-Consumer-Custom-Id` header was getting set to the contents of the `aud` claim in the JWT. And the `X-Consumer-Id` seems to be getting set to some guid, however it's not the id of either of the 2 consumers I have in the app or any of the plugin ids. So I'm not really sure where it's coming from.

Install details:
Kong 0.6.0
Ubuntu Trusty 14.04.3 LTS
Nothing notable in the error log

**Comment by ThorArakis** [comment]
Anybody else able to reproduce? Let me know if I can provide more details.

**Comment by thefosk** [comment]
@ThorArakis can you try with the latest version 0.7.0? This should have been fixed.

**Comment by ThorArakis** [comment]
Will do, thanks!

**Comment by ThorArakis** [comment]
Confirmed. Rate limiting is working as expect in 7.0 for jwt consumers!
