### ISSUE TITLE
Kong start error in Ubuntu 15

### ISSUE THREAD

**Issue by venquet** [Mashape/kong#949]
![kongerror](https://cloud.githubusercontent.com/assets/1101530/12814833/0f654756-cb68-11e5-950c-f828b260b7f2.png)

Above error appears when we try to start the kong instance, configured cassandra in same machine changed/enabled the configuration in kong.yml to refer local cassandra instance.

**Comment by ThorArakis** [comment]
At a glance it appears that it can't parse the changes you made to the config file. You might want to revert the change and see if it starts up. Otherwise try including your updated yml file since it could provide an easier way to find the culprit.

**Comment by thefosk** [comment]
I confirm, it seems like the YAML file is not valid (bad formatting or indentation probably).

**Comment by thibaultCha** [comment]
It would be good to simply `pcall` the `yaml.load` call and catch any error, and let the user know the YAML formatting is wrong rather than such an obscure error with an unfriendly stacktrace. Any takers?

**Comment by ajayk** [comment]
@thibaultCha Here you go https://github.com/Mashape/kong/pull/983
