### ISSUE TITLE
Getting "HMAC signature does not match" error when accessing the api from Ruby via HMAC plugin

### ISSUE THREAD

**Issue by rtsinani** [Mashape/kong#955]
Following the instructions here (https://getkong.org/plugins/hmac-authentication/) I created an api on my local kong (*request_host* 'api.demo2.com') and a consumer with username 'user66'. Then I added the hmac plugin credentials with username 'user66' and secret 'secret66'. I am now trying to access the api via ruby, by generating the HMAC signature below (as per some of your tests).
But I'm getting a "HMAC signature does not match" message as response.

Below is the code:

```
username = 'user66'
secret   = 'secret66'
date     = Time.now.httpdate
digest   = OpenSSL::Digest.new('sha1')
hmac     = Base64.encode64(OpenSSL::HMAC.digest(digest, secret, "date: #{date}")).chomp

headers = {
  "Host"          => "api.demo2.com",
  "Authorization" => %(hmac username="#{username}", algorithm="hmac-sha1", headers="date", signature="#{hmac}"),
  "X-Date"        => date
}

**Comment by shashiranjan84** [comment]
Would you please provide the date you passed in and  the hmac signature

**Comment by rtsinani** [comment]
Sure, 
date: Fri, 05 Feb 2016 16:12:51 GMT
hmac: NnHA/wR93+E4EXKnO1lanChRzo4=

**Comment by shashiranjan84** [comment]
Ahh, you passing  `x-date` but you set headers as `date`

"Authorization" => %(hmac username="#{username}", algorithm="hmac-sha1", headers="date", signature="#{hmac}"),

**Comment by rtsinani** [comment]
That was it! Thank you!

**Comment by shashiranjan84** [comment]
Great, just wondering If it was confusing in the doc. 

Your feedback will help me make the doc better for other user.

**Comment by rtsinani** [comment]
Wonder if it could be a bit clearer that the `header` part of `Authorisation` header should refer to the actual request headers.

**Comment by bglusman** [comment]
I'm struggling with the same issue, but using "Date" header is not working for me...  wondering if @rtsinani can share the final code/current version of kong they're using, or if there's anything else useful in troubleshooting?  

Relatedly wondering if the hmac plugin can get a troubleshooting/configuration mode we can enable on a staging environment to help us and our customers troubleshoot when THEIR hmac isn't working exactly what the mismatch is?  Aside from getting this to work for myself, I'm concerned about asking our customers to implement this and having limited insight for how to help them debug their signing process in various languages without the ability to tell exactly what the difference between computed signature and actual signature is... obviously in production we wouldn't want to reveal extra information, but for initial setup of request signing with various different API integrations something with additional logging or help would be very useful.

**Comment by rtsinani** [comment]
@bglusman In my case I had to make sure that the header in the `Authorisation` matched perfectly with the request header passed; i.e. if you specify

`headers=Date`

in `Authorisation`, make sure you pass a `Date` request header, with the same capitalisation. 

Hope that helps.

**Comment by bglusman** [comment]
Thanks, I did get it working! I think I had actually messed up the secret IIRC, but when I checked that I had too many other variables I was varying in tandem that I thought might be messed up.
