### ISSUE TITLE
kong migration.py script  TypeError object of type resultSet has no len()

### ISSUE THREAD

**Issue by bwoodring** [Mashape/kong#957]
When attempting to upgrade from 0.4.2 I receive this error when running migration.py

`[ec2-user@i]$ sudo python migration.py -c /etc/kong/kong.yml
[INFO]: Using Kong configuration file at: /etc/kong/kong.yml
[INFO]: Using datacenter 'datacenter1' for DCAwareRoundRobinPolicy (via host 'localhost'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
Traceback (most recent call last):
  File "migration.py", line 274, in <module>
    main(sys.argv[1:])
  File "migration.py", line 239, in main
    is_migrated = len(rows) > 1 and any(mig.id == "core" for mig in rows)
TypeError: object of type 'ResultSet' has no len()
`
Please excuse my ignorance as I am new to Kong and Python. I feel this should be trivial for some, but this has me stuck without being able to finish my upgrade. Any advice and/or help is greatly appreciated.

**Comment by thibaultCha** [comment]
Are you trying to upgrade from 0.4 to 0.6?

**Comment by bwoodring** [comment]
yes, attempting to upgrade from 0.4.2 to 0.6.1

**Comment by thibaultCha** [comment]
That won't work. You have to upgrade to 0.5 first, and using a 0.5 config file especially, since the YAML format changed.

**Comment by bwoodring** [comment]
OK, thank you for the information. I tried to locate a 0.5 version to download and install, but I can only find the most recent version. Where can you find the older version packages to install?

**Comment by thibaultCha** [comment]
https://github.com/Mashape/kong/releases

**Comment by bwoodring** [comment]
Your quick help is greatly appreciated!

**Comment by bwoodring** [comment]
I am not sure what I am doing wrong. I download kong-0.5.0.el7.noarch.rpm
I am following the upgrade instructions here: https://github.com/Mashape/kong/blob/0.5.0/UPDATE.md#update-to-kong-050
I am running Kong 0.4.2 and Python 2.7.
Update the hosts property to contact_points
Install  pip install cassandra-driver pyyaml 
Then run python migration.py -c /etc/kong/kong.yml

I am still getting the same error from the script. 
`[ec2-user@]$ sudo python migration.py -c /etc/kong/kong.yml
[INFO]: Using Kong configuration file at: /etc/kong/kong.yml
[INFO]: Using datacenter 'datacenter1' for DCAwareRoundRobinPolicy (via host 'localhost'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
Traceback (most recent call last):
  File "migration.py", line 274, in <module>
    main(sys.argv[1:])
  File "migration.py", line 239, in main
    is_migrated = len(rows) > 1 and any(mig.id == "core" for mig in rows)
TypeError: object of type 'ResultSet' has no len()
`

**Comment by thibaultCha** [comment]
I will need a full output of what your schema_migrations table contains, of the configuration file you are using, of the version of the Cassandra driver you installed and details on your Cassandra cluster to investigate this.

**Comment by bwoodring** [comment]
Successfully installed cassandra-driver-3.0.0 futures-3.0.4
`Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.2.3 | CQL spec 3.3.1 | Native protocol v4]
`
[cassandra.txt](https://github.com/Mashape/kong/files/119854/cassandra.txt)
[kong.txt](https://github.com/Mashape/kong/files/119856/kong.txt)

Please let me know if you need anything else. Sorry to be such a pain, but how can I obtain the schema_migration table?

**Comment by thibaultCha** [comment]
> Please let me know if you need anything else. Sorry to be such a pain, but how can I obtain the schema_migration table?

You could run this query in cqlsh:

```
SELECT * FROM <keyspace>.schema_migrations;
```

**Comment by bwoodring** [comment]
`cqlsh> DESCRIBE keyspaces;

system_traces  system_distributed  system_auth  system  kong

cqlsh> SELECT * FROM kong.schema_migrations;

 id         | migrations
------------+-------------------------------------------------------------------------------------------------------------------------------------------------
 migrations | ['2015-01-12-175310_init_schema', '2015-04-24-154530_plugins', '2015-05-22-235608_0.3.0', '2015-06-09-170921_0.4.0', '2015-08-10-813213_0.4.2']

(1 rows)
`

Is this all you need or more?

**Comment by thibaultCha** [comment]
Could install the Cassandra driver at its `2.7.2` version? It seems since then, the newer version of the Python driver has some breaking changes.

```
pip install cassandra-driver==2.7.2
```

**Comment by bwoodring** [comment]
That was the trick! Thank you!

**Comment by thibaultCha** [comment]
Perfect, I'll update the migration instructions.

**Comment by bwoodring** [comment]
@thibaultCha When I attempt to reload kong I get this error:
`kong reload /usr/local/bin/luajit: /usr/local/share/lua/5.1/luarocks/loader.lua:117: error loading module 'rex_pcre' from file '/usr/local/lib/lua/5.1/rex_pcre.so': libpcre.so.1: cannot open shared object file: No such file or directory stack traceback: [C]: in function 'a_loader' /usr/local/share/lua/5.1/luarocks/loader.lua:117: in function </usr/local/share/lua/5.1/luarocks/loader.lua:114> [C]: in function 'require' /usr/local/share/lua/5.1/kong/tools/ngx_stub.lua:7: in main chunk [C]: in function 'require' /usr/local/lib/luarocks/rocks/kong/0.5.0-1/bin/kong:52: in main chunk [C]: at 0x00404ac0 `

Is there an upgrade setup that I missed? I am unable to get it to reload kong as this time.
