### ISSUE TITLE
Patch method on REST API doesn't behave correctly or as expected

### ISSUE THREAD

**Issue by dmportella** [Mashape/kong#962]
Hello 

I have been playing with Kong today and while following the tutorials etc I found that when trying to update the config for a plugin against an api using the patch method without content-type specified  Kong returns a response HTTP status code **200 OK** but the data is not patched.

**Request example**
```
PATCH /apis/toolbox/plugins/4566c95b-c686-4778-8141-f66286c7fdcb HTTP/1.1
Host: 0.0.0.0:8001
Cache-Control: no-cache
Postman-Token: 1454dbdd-ca2d-f2a0-212d-dd4339efb85a

{
  "api_id": "e235c7ac-82a1-4be2-917e-27690a400901",
  "id": "4566c95b-c686-4778-8141-f66286c7fdcb",
  "created_at": 1454928137000,
  "enabled": true,
  "name": "key-auth",
  "config": {
    "key_names": [
      "api-key", "function"
    ],
    "hide_credentials": false
  }
}
```

Response code from the above is **200 OK** but no data is changed only if you set the content type to `application/json` is that the config is changed.

The api should return a **415 Unsupported Media Type** or try to infer the media type from the payload.

I have tested other parts of the REST API where the patch method is supported and they also inhibit the same issue. 

This issue was found on the current release for kong.

**Comment by thefosk** [comment]
I think this is was actually a bug and fixed with https://github.com/Mashape/kong/pull/941

**Comment by thibaultCha** [comment]
No this is not related, this is very probably also in `next`.
