### ISSUE TITLE
Upgrade to 0.5.0 form 0.4.2 error on kong reload

### ISSUE THREAD

**Issue by bwoodring** [Mashape/kong#971]
When attempting to upgrade from 0.4.2 to 0.5.0 everything goes smooth until I try to reload kong. I recieve the below error:
` kong reload
/usr/local/bin/luajit: /usr/local/share/lua/5.1/luarocks/loader.lua:117: error loading module 'rex_pcre' from file '/usr/local/lib/lua/5.1/rex_pcre.so':
        libpcre.so.1: cannot open shared object file: No such file or directory
stack traceback:
        [C]: in function 'a_loader'
        /usr/local/share/lua/5.1/luarocks/loader.lua:117: in function </usr/local/share/lua/5.1/luarocks/loader.lua:114>
        [C]: in function 'require'
        /usr/local/share/lua/5.1/kong/tools/ngx_stub.lua:7: in main chunk
        [C]: in function 'require'
        /usr/local/lib/luarocks/rocks/kong/0.5.0-1/bin/kong:52: in main chunk
        [C]: at 0x00404ac0
`

Is there an upgrade setup that I missed? I am unable to get it to reload kong as this time.

**Comment by thibaultCha** [comment]
I looks like you don't have libpcre installed? Can you try installing it and try again?

**Comment by bwoodring** [comment]
after installing libpcre everything reloaded. Thanks!
