### ISSUE TITLE
Kong 0.6 is failing to start while doing migration of mashape_analytics

### ISSUE THREAD

**Issue by debraj-manna** [Mashape/kong#977]
Posting this [issue](https://groups.google.com/forum/#!topic/konglayer/6XY1mTNLJcg) from Kong user group.

I was trying to set up a fresh 2 Node Kong Cluster with 2 Node Cassandra Cluster. But whenever I am trying to start the kong. I am getting the below error:-

```
root@SPK-D-0611:/opt/cassandra# kong start -c /etc/kong/kong2.yml
[INFO] Kong 0.6.0
[INFO] Using configuration: /etc/kong/kong2.yml
[INFO] database...........cassandra ssl=verify=false enabled=false contact_points=172.16.85.228:9042,172.16.85.230:9042 data_centers= replication_strategy=SimpleStrategy replication_factor=2 keyspace=kong
[INFO] Database not initialized. Running migrations...
[INFO] Migrating core on keyspace "kong" (cassandra)
[INFO] core migrated up to: 2015-01-12-175310_skeleton
[INFO] core migrated up to: 2015-01-12-175310_init_schema
[INFO] core migrated up to: 2015-11-23-817313_nodes
[INFO] Migrating key-auth on keyspace "kong" (cassandra)
[INFO] key-auth migrated up to: 2015-07-31-172400_init_keyauth
[INFO] Migrating rate-limiting on keyspace "kong" (cassandra)
[INFO] rate-limiting migrated up to: 2015-08-03-132400_init_ratelimiting
[INFO] Migrating mashape-analytics on keyspace "kong" (cassandra)
[INFO] Leaving cluster..
[ERR] Error executing migration for "mashape-analytics": Cassandra error: ResponseError: [Invalid] Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING
[ERR] Could not start Kong

```
In the `kong2.yml` I just updated the database section which looks like below:-

```
database: cassandra
cassandra:
  contact_points:
    - "172.16.85.228:9042"
    - "172.16.85.230:9042"
  keyspace: kong
  replication_strategy: SimpleStrategy
  replication_factor: 2

```
Below is the schema of `plugins` table:-

```
cqlsh> DESCRIBE kong.plugins;

CREATE TABLE kong.plugins (
    id uuid,
    name text,
    api_id uuid,
    config text,
    consumer_id uuid,
    created_at timestamp,
    enabled boolean,
    PRIMARY KEY (id, name)
) WITH CLUSTERING ORDER BY (name ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
CREATE INDEX plugins_api_id_idx ON kong.plugins (api_id);
CREATE INDEX plugins_consumer_id_idx ON kong.plugins (consumer_id);

```
I tried several times by dropping the Kong keyspace but every time getting the same error. As suggested I tried by increasing the `timeout` to a large value of 30000 in 0.6.1. But still seeing the same issue.

**Comment by thibaultCha** [comment]
As discussed in the thread you linked to, your plugins table should also have an index on `name`:

```
CREATE INDEX plugins_api_id_idx ON kong_development.plugins (api_id);
CREATE INDEX plugins_consumer_id_idx ON kong_development.plugins (consumer_id);
CREATE INDEX plugins_name_idx ON kong_development.plugins (name);
```

I cannot reproduce this with Kong (any version) and Cassandra 2.2.4 (1 to 3 nodes), nor does it happen on Travis either. In fact, there is nothing we can do without more informations or an actual error from Kong or Cassandra.

**Comment by afajem** [comment]
As stated on the Kong Gitter channel, I was also able to recreate this issue on Kong 0.6.1 with Cassandra 2.2.5. I was able to reproduce the issue repeatedly.  I am running on RHEL 7.2; not sure if that make any difference. 

So if I'm understanding the issue correctly, the suggestion is to manually create an index on `name` :

`CREATE INDEX plugins_name_idx ON kong.plugins (name);`

Given that you now have a couple people able to reproduce this issues, the question then becomes would you recommend using 0.6.1 (or 0.6 for that matter) in a clustered fashion in a production environment or would you suggest sticking to 0.5.4. 

Thanks again.

**Comment by thefosk** [comment]
This is an old issue - are you guys still experiencing it?

**Comment by afajem** [comment]
Upgrading to 0.7.0 took care of that issue. Thanks @thefosk for checking in.
