### ISSUE TITLE
Kong start issue due configuration 

### ISSUE THREAD

**Issue by jeevaengg21** [Mashape/kong#986]
Getting below error while start kong. As reported in the error line 166 has ngix configuration, but i haven't change anything in that part. Only change i made was cassandra configuration

**nginx: |
  user {{user}};
  worker_processes auto;
  error_log logs/error.log error;
  daemon on;**

**ERROR**

[INFO] Using configuration: /etc/kong/kong.yml
/usr/local/bin/luajit: did not find expected <document start> at document: 1, line: 166, column: 1

stack traceback:
	[C]: in function 'load'
	/usr/local/share/lua/5.1/kong/tools/config_loader.lua:151: in function 'load_default'
	/usr/local/share/lua/5.1/kong/cli/cmds/start.lua:19: in main chunk
	[C]: in function 'require'
	/usr/local/lib/luarocks/rocks/kong/0.6.1-0/bin/kong:55: in main chunk
	[C]: at 0x00404760
jeevanantham@solverubuntulaptop:~$ sudo gedit /etc/kong/kong.yml

**Comment by thibaultCha** [comment]
I believe this is #949: bad configuration format.

**Comment by jeevaengg21** [comment]
yup, u are correct i revert back the configuration its working now. @Kong It would be more useful if the error information are more precise because i was looking in the wrong part of configuration.

**Comment by thibaultCha** [comment]
Yes, it will be the case, as @ajayk was nice enough to provide a patch for this in #949.

**Comment by olufemi** [comment]
This error " did not find expected <document start> at document: 1, line: 166, column: 1". I'm also facing in starting kong.
@jeevaengg21 did not really indicate how he resolved this. Or may be you can paste on this blog correct cassandra setting in kong.yml. i'm using redhat server with a public ip.

Please i need your help to resolve this, my client is on me. Thank you.

**Comment by Tieske** [comment]
@olufemi please see #949 probably you have a formatting error in your yml config file. Please check carefully the indentations etc.

**Comment by jeevaengg21** [comment]
@olufemi if your running the cassandra in the same machine, do not make any change in kong.yml. so revert all the changes you have done and try again.

**Comment by olufemi** [comment]
Thanks so much @jeevaengg21 , i'm running cassandra on the same machine. As you asked me to do i have restored kong.yum to its defualt. But when i ran "kong start", i got the following response:

[olufemi@localhost ~]$ kong start
[INFO] Kong 0.7.0
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........cassandra keyspace=kong ssl=verify=false enabled=false replication_factor=1 contact_points=127.0.0.1:9042 replication_strategy=SimpleStrategy timeout=5000 data_centers=
[INFO] Leaving cluster..
[ERR] Cassandra error: [Invalid] unconfigured table schema_keyspaces
[ERR] Could not start Kong

Please assist me, what can i do to it, and my cassandra is running.
Also how can i know the status of cassandra from command terminal?

Thank you. Please any body should help.

**Comment by martin-dostal** [comment]
@olufemi don't you run Kong against Cassandra 3.x? It is not supported, see #831.

**Comment by SandeshSarfare** [comment]
How can I downgrade cassandra version from 3.5
