### ISSUE TITLE
Consumer not able to access the API after ACL plugin configuration

### ISSUE THREAD

**Issue by jeevaengg21** [Mashape/kong#987]
Environment:
Ubuntu 15

At initial setup of Kong,

1. Created API
2. Created Consumers.
3. Added Key-Auth authetication plugin to API
4. Generated apikey for cosumers

After did above steps all consumers was able to access the API. But after add ACL Plugin to API to control access by consumer it fails to work.

While POST request to the API from Consumer available in ACL whitelist, kong response with 

_{
message: "Cannot identify the consumer, add an authentication plugin to use ACL plugin"
}_

But i have already added a authentication plugin key-auth to the API and generate the apikey for consumer. How to resolve this.

**NOTE**

http://kong:8001/apis/myserver/plugins

{"data":[{"api_id":"78e5e06e-4cea-4f90-b1f2-2e315fcf2aae","id":"73c10a2b-d7eb-44bf-92c2-dea8d27de8fa","created_at":1455182885000,"enabled":true,"name":"acl","config":{"whitelist":["group1"]}}],"total":1}

http://kong:8001/consumers/admin/key-auth

{"data":[{"key":"03e8fe4c82174fdfbb6482f07b073005","consumer_id":"17d44d9f-94ee-45ac-8ba1-ce601fcdf002","created_at":1455175654000,"id":"f05f8efe-4a63-4556-8cb6-ca421f8233a2"}],"total":1}

http://kong:8001/consumers/admin/acls

{"data":[{"group":"group1","consumer_id":"17d44d9f-94ee-45ac-8ba1-ce601fcdf002","created_at":1455182969000,"id":"fb0a28ee-55ed-421f-ba7f-046abf6840dd"},{"group":"group2","consumer_id":"17d44d9f-94ee-45ac-8ba1-ce601fcdf002","created_at":1455183030000,"id":"0153e64d-f2e1-491a-8887-2fe3ef3b45e7"}],"total":2}

**Comment by zhoux0130** [comment]
Hi, how did you resolve this problem?

**Comment by zhoux0130** [comment]
I know the reason. If you want to use the ACL plugins, first of all, the consumer must have used auth plugins(such as key-auth etc)

**Comment by narongdejsrn** [comment]
For someone who passing by this post

Make sure you assign Configuration to each APIs 
https://getkong.org/plugins/key-authentication/#configuration
