### ISSUE TITLE
Bug in documentation about how to write a custom plugin

### ISSUE THREAD

**Issue by elruwen** [Mashape/kong#989]
Hi!

Since kong 0.6.x is out, I migrated my custom plugins to the new version. I followed the documentation. I think there is a bug here:
https://getkong.org/docs/0.6.x/plugin-development/distribution/
"kong.plugins.my-custom-plugin.migrations.cassandra"
should be
"kong.plugins.my-custom-plugin.schema.migrations"

Additionally there is now something called
kong.plugins.my-custom-plugin.hooks
if I am not wrong. Maybe it should be added to that page, too.

Cheers
Ruwen

**Comment by thibaultCha** [comment]
Yes indeed, fixed with https://github.com/Mashape/getkong.org/commit/e24d015b025ef0ce10c8f24ad685f44d2577bbb2, thank you!

**Comment by elruwen** [comment]
What about the hooks?

**Comment by thibaultCha** [comment]
Right, @thefosk would have to write the documentation regarding those.

**Comment by thibaultCha** [comment]
As I come to think of this again, I would also add that hooks are still somewhat internal, and we would need more polishing and a few features before making them properly usable by plugins.

**Comment by thefosk** [comment]
The documentation for hooks is already written [here](https://getkong.org/docs/0.6.x/plugin-development/entities-cache/). I am pushing a mention to hooks also in the "Distribution" chapter.
