### ISSUE TITLE
Keep-alive upstream requests

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#990]
Being able to keep-alive the connections to the upstream services while proxying.

**Comment by jmdacruz** [comment]
Any updates on when this might be ready? It seems like an important feature from the performance perspective. Is this something that can be contributed by a 3rd party?

**Comment by thefosk** [comment]
Will show up in 0.9 and it's related to #1225

**Comment by jmdacruz** [comment]
Awesome! Do you have an ETA for 0.9?

**Comment by thefosk** [comment]
Currently working on it. We need to merge `refactor/cli` into `next` first, and then we can start working on this issue.

**Comment by patrickpierson** [comment]
Any update on this #1225 is closed now.

**Comment by thibaultcha** [comment]
See #1587

**Comment by Tieske** [comment]
part of 0.10, waitng to be released. Avaialble in the RC for 0.10. Closing this
