### ISSUE TITLE
can‘t log consumer info in v0.6.1

### ISSUE THREAD

**Issue by 85022134** [Mashape/kong#993]
Kong version: 0.6.1    

I read doc on https://getkong.org/plugins/syslog/

 "authenticated_entity": {
        "consumer_id": "80f74eef-31b8-45d5-c525-ae532297ea8e",
        "created_at":   1437643103000,
        "id": "eaa330c0-4cff-47f5-c79e-b2e4f355207e",
        "key": "2b64e2f0193851d4135a2e885cd08a65"
    },
but  I can't find consumer info in access-log ，by the way  I run kong in dokcer

[root@2698f7c4065a kong]# vi kong.yml 
database: cassandra
cassandra:
  contact_points:
    - "cassandra:9042"
nginx: |
  user {{user}};
  worker_processes auto;
  error_log logs/error.log error;
  daemon on;

  worker_rlimit_nofile {{auto_worker_rlimit_nofile}};

  env KONG_CONF;
  env PATH;

  events {
    worker_connections {{auto_worker_connections}};
    multi_accept on;
  }

  http {
    resolver {{dns_resolver}} ipv6=off;
    charset UTF-8;

    access_log logs/access.log;
    access_log on;

    # Timeouts
    keepalive_timeout 60s;
    client_header_timeout 60s;
    client_body_timeout 60s;
    send_timeout 60s;

    # Proxy Settings
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    proxy_ssl_server_name on;

    # IP Address
    real_ip_header X-Forwarded-For;
    set_real_ip_from 0.0.0.0/0;
    real_ip_recursive on;
-----------------------------------------------------------------------------------------------------------------------------
access-log 
172.16.14.1 - - [20/Jan/2016:01:52:10 +0000] "POST /kkk/login_peopleQuery HTTP/1.1" 200 353 "-" "Java/1.7.0_79"

thanks！

**Comment by thibaultCha** [comment]
Did you enable one of the authentication plugins? Otherwise Kong cannot know who the consumer is.

**Comment by 85022134** [comment]
thank you for your reply, I enable key-auth plugins,  and create a consumer. Then I send a Http request with key header

**Comment by 85022134** [comment]
@jerodsanto  I don't know where is the prolem .  Hope for your help .thanks

**Comment by mars** [comment]
@85022134 Nginx access.log [defaults to the "combined" format](http://nginx.org/en/docs/http/ngx_http_log_module.html#access_log), which does not contain any Kong consumer information.

"Combined" format only includes [`$remote_user` from Basic HTTP authentication](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_remote_user).

If your goal is to get consumer ID into access log, I believe you would need to [create a custom plugin](https://getkong.org/docs/0.6.x/plugin-development/custom-logic/) that logs that data.

**Comment by 85022134** [comment]
@mars  @thibaultCha  Thank you for your help . But I don't understand why I must create a custom plugin.   I  enabled syslog plugin for the api as the doc said.  https://getkong.org/plugins/syslog/

I also enabled  key-auth plugin for the api, and created a consumer.  

but there is no consumer info in access logs.

**Comment by 85022134** [comment]
I didn't  specified  consumer_id  parameter, because I think it will be for all consumers in this way.
curl -X POST http://kong:8001/apis/{api}/plugins \
    --data "name=syslog"

I read the source code 

\kong\plugins\log-serializers\basic.lua

function _M.serialize(ngx)
  local authenticated_entity
  if ngx.ctx.authenticated_credential ~= nil then
    authenticated_entity = {
      id = ngx.ctx.authenticated_credential.id,
      consumer_id = ngx.ctx.authenticated_credential.consumer_id
    }
  end

kong\kong\plugins\key-auth\handler.lua

function KeyAuthHandler:access(conf)
  KeyAuthHandler.super.access(self)
  local key, key_found, credential
  for _, v in ipairs({ constants.AUTHENTICATION.QUERY, constants.AUTHENTICATION.HEADER }) do
    key = retrieve_credentials[v](ngx.req, conf)
    if key then
      key_found = true
      credential = cache.get_or_set(cache.keyauth_credential_key(key), function()
        local credentials, err = dao.keyauth_credentials:find_by_keys {key = key}
        local result
        if err then
          return responses.send_HTTP_INTERNAL_SERVER_ERROR(err)
        elseif #credentials > 0 then
          result = credentials[1]
        end
        return result
      end)
      if credential then break end
    end
  end

  -- No key found in the request's headers or parameters
  if not key_found then
    ngx.header["WWW-Authenticate"] = "Key realm=\""..constants.NAME.."\""
    return responses.send_HTTP_UNAUTHORIZED("No API Key found in headers, body or querystring")
  end

  -- No key found in the DB, this credential is invalid
  if not credential then
    return responses.send_HTTP_FORBIDDEN("Invalid authentication credentials")
  end

  -- Retrieve consumer
  local consumer = cache.get_or_set(cache.consumer_key(credential.consumer_id), function()
    local result, err = dao.consumers:find_by_primary_key({id = credential.consumer_id})
    if err then
      return responses.send_HTTP_INTERNAL_SERVER_ERROR(err)
    end
    return result
  end)

  ngx.req.set_header(constants.HEADERS.CONSUMER_ID, consumer.id)
  ngx.req.set_header(constants.HEADERS.CONSUMER_CUSTOM_ID, consumer.custom_id)
  ngx.req.set_header(constants.HEADERS.CONSUMER_USERNAME, consumer.username)
  ngx.ctx.authenticated_credential = credential
end

I think it will work, But I don't know what's wrong. 

Looking forward to your help @thibaultCha @mars

**Comment by 85022134** [comment]
I run kong in docker，there is no syslog deamon.  it that the problem?

**Comment by mars** [comment]
Per the [syslog plugin docs](https://getkong.org/plugins/syslog/#notes):

> Make sure Syslog daemon is running on the instance and it's configured with logging level severity same as or lower than the set `config.log_level`.

**Comment by thefosk** [comment]
@85022134 were you able to figure it out?

**Comment by 85022134** [comment]
@thefosk @mars  thanks, I finally figured it out
