### ISSUE TITLE
Unable to validate apikey for the api for consumer

### ISSUE THREAD

**Issue by pranny** [Mashape/kong#997]
I have a fresh kong installation. I have added some APIs, Consumers, provisioned consumer's keys (I am using key-auth). However, when I am trying to query the kong using apikey like below, I get the error

```
$ curl -X POST --data '{"event_name":"page.view","event_param":"12"}' http://127.0.0.1:8000/events/?apikey=302fa1a9489c47f28f4a2505d0f1e1f0
{"message":"No API Key found in headers, body or querystring"}
```
The documentation https://getkong.org/plugins/key-authentication/#using-the-api-key says to send the `apikey`. I also tried with sending the key in header as well as in formdata, however this error does not go away. I am on kong 0.6.1.

**Comment by thefosk** [comment]
@pranny, can I see the key-auth plugin configuration for your API by running `http://127.0.0.1:8001/apis/{id_or_name}/plugins/`?

**Comment by pranny** [comment]
Thanks for assigning this. The output goes below
```
{"data":[{"api_id":"66ee9548-21f8-4586-8366-3cb271ddff16","id":"1e311e9a-8158-4928-b2b3-eca7b6012cd0","created_at":1455620635000,"enabled":true,"name":"key-auth","config":{"hide_credentials":false,"key_names":["function"]}}],"total":1}
```

I used Kong Dashboard (https://github.com/PGBI/kong-dashboard) as the UX from where I created the consumers, api etc.

**Comment by thefosk** [comment]
for some reason, the plugin is looking for the key not in the default `apikey` parameter, but in a `function` parameter (this was assigned when creating the plugin).

Executing this will work: `curl -X POST --data '{"event_name":"page.view","event_param":"12"}' http://127.0.0.1:8000/events/?function=302fa1a9489c47f28f4a2505d0f1e1f0`

**Comment by pranny** [comment]
You are correct. Replacing `apikey` with `function` does work. Also, I figured out how to update this in the kong-dashboard. The correct configuration should look like below

<img width="549" alt="screen shot 2016-02-17 at 10 50 34" src="https://cloud.githubusercontent.com/assets/82643/13100544/5645fb42-d564-11e5-84de-9bc679e65f43.png">

**Comment by KodeChampion** [comment]
thank you pranny. I encountered the same problem. I resolved it with your input here.
