### ISSUE TITLE
Pass consumer_id in Datadog plugin

### ISSUE THREAD

**Issue by mgvarley** [Mashape/kong#998]
Could the consumer_id be added to the Datadog plugin please?  This would allow analytics by consumer in Datadog which would be very useful

**Comment by mgvarley** [comment]
I would say this is a feature request rather than a question.  Essentially what I am suggesting is that the datadog plugin be enhanced so that it can be installed for an API and when communicating with the datadog agent the consumer_id and potentially also the credential_id be passed as tags so that usage metrics can be gathered for a given consumer and/or credential.  If this is possible that would be awesome.

**Comment by logantpowell** [comment]
+1

**Comment by BrianHutchison** [comment]
+1

**Comment by nvuppala** [comment]
+1

Thanks,
Naveen

**Comment by shashiranjan84** [comment]
@mgvarley Please use StatsD plugin, it logs Customer_id if there any. It works exactly same as Datadog. Meanwhile I will also update the Datadog plugin.

**Comment by thefosk** [comment]
Will be available in 0.8.1
